### ISSUE TITLE
Saving Files into /static doesn't include them in build-folder

### ISSUE THREAD

**Issue by flicksolutions** [sveltejs/kit#10254] opened 2023-06-26 13:32 UTC
### Describe the bug

When writing a file using `fs.writeFile()` in a +server.js-Route into /static the file is skipped during the build process and is only picked-up after a second build.
I'm writing a file on a server route (proxy.json/+server.js). As this route gets called during build, it writes a file in the static folder. This file is not found in the build-folder later. In fact, even stackblitz is not showing the file in the file-browser. But it's actually there, because if you run npm run build again, the buildprocess will work flawless. Why is that? How can I fix it?

Thank you so much in advance!

### Reproduction

I created this repo to illustrate the bug: https://stackblitz.com/edit/sveltejs-kit-template-default-rtpmiu?file=src%2Froutes%2Fproxy.json%2F%2Bserver.js

### Logs

```Shell
Error: Not found: /pic.jpg
    at resolve (/home/projects/sveltejs-kit-template-default-rtpmiu/.svelte-kit/output/server/index.js:2710:18)
    at resolve (/home/projects/sveltejs-kit-template-default-rtpmiu/.svelte-kit/output/server/index.js:2585:41)
    at  (/home/projects/sveltejs-kit-template-default-rtpmiu/.svelte-kit/output/server/index.js:2755:68)
    at respond (/home/projects/sveltejs-kit-template-default-rtpmiu/.svelte-kit/output/server/index.js:2583:43)
Error: 404 /pic.jpg (linked from /)
```
```


### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.5.0 => 1.20.4 
    svelte: ^3.54.0 => 3.59.2 
    vite: ^4.3.0 => 4.3.9
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment] 2023-06-26 13:56
Duplicate of #4832.

**Closed by Conduitry** 2023-06-26 13:56 UTC

**Comment by flicksolutions** [comment] 2023-06-26 17:06
Thank you @Conduitry ! This helped and I understand the problem better now. However, on build for a static site when you use adapter-static, this would not be a big performance-problem, since the code is only run once, right?
I'd like to test that using the static-adapter, but there is no direct call to `sirv`, how would I enable dev-mode in the static adapter?

Thanks for any hint in the right direction.
