### ISSUE TITLE
`$page.url.pathname` represented as "//prerender/" when building using the static adapter

### ISSUE THREAD

**Issue by metonym** [sveltejs/kit#3164] opened 2021-12-31 18:01 UTC
### Describe the bug

Using the latest versions:

- @sveltejs/kit version 1.0.0-next.211
- @sveltejs/adapter-static version 1.0.0-next.24

In development, `$page.url.pathname` in `routes/index.svelte` will correctly be displayed as "/".

However, when building for production using the static adapter, the same route is represented as "//prerender/".

Inspecting `build/index.html`, the markup has the correct "/" but the script that hydrates the markup has the following:

```js
<script type="module">
  import { start } from "/_app/start-40ff21d5.js";
  start({
    target: document.querySelector("#svelte"),
    paths: { base: "", assets: "" },
    session: {},
    route: true,
    spa: false,
    trailing_slash: "never",
    hydrate: {
      status: 200,
      error: null,
      nodes: [
        import("/_app/layout.svelte-96b29dd0.js"),
        import("/_app/pages/index.svelte-91ca303b.js"),
      ],
      url: new URL("sveltekit://prerender/"),
      params: {},
    },
  });
</script>
```

Evaluating `new URL("sveltekit://prerender/")` shows that the `URL.pathname` is `//prerender/`.

### Workaround

A workaround is to explicitly set `kit.ssr` or `kit.hydrate` to `false`.

### Reproduction

https://github.com/metonym/sveltekit-page.url.pathname

### System Info

```shell
System:
  OS: macOS 11.4
  CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Memory: 19.40 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
  Yarn: 1.22.17 - /usr/local/bin/yarn
  npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
Browsers:
  Chrome: 96.0.4664.110
  Firefox: 89.0.2
  Safari: 14.1.1
npmPackages:
  @sveltejs/adapter-static: next => 1.0.0-next.24 
  @sveltejs/kit: next => 1.0.0-next.211 
  svelte: ^3.44.0 => 3.44.3
```

### Severity

blocking an upgrade

**Comment by musaffar-patel** [comment] 2022-01-01 01:55
I've encountered the same issue.  Could you explain your workaround better for myself and other novices?  Which path/file exactly needs editing?

**Comment by matthewmullin01** [comment] 2022-01-02 08:11
I've found the same with both the nelify and vercel adapters.

Essentially any page that I am prerendering seems to have this issue

**Comment by bluwy** [comment] 2022-01-02 09:28
Note: I've tested `new URL("sveltekit://prerender/")` in a few places. The result of `pathname` are:

- Node, Safari: `/`
- Firefox, Chrome: `//prerender/`

So this behaviour would technically work in Safari, though I'm not sure who's correct here. A easy fix is to ensure the host have at least one `.`.

**Comment by brittneypostma** [comment] 2022-01-05 13:36
Looks like this is closed and merged, but I'm still experiencing this on [sveltesirens.dev](sveltesirens.dev). I was programmatically grabbing the title from the pathname, but had to change it due to this bug. If you went directly to any route, it was prefaced with `//prerender/`. I am also experiencing images not loading as seen below. 
![image](https://user-images.githubusercontent.com/45889730/148226150-effe57dd-4b8d-4b18-b850-6b3e4a081a3b.png)
If I navigate using the navbar which says `/about`, I am able to see the image. 
![image](https://user-images.githubusercontent.com/45889730/148226253-a3b2bc49-ac61-4e72-aa3c-9b4dc0db0ed4.png)

**Comment by moritzebeling** [comment] 2022-01-14 10:49
I noticed it in version `218` and it seemingly disappeared after upgrading to `225`

**Comment by moritzebeling** [comment] 2022-01-14 11:24
Well I have to correct myself:
- In version `218` when I visit my deployed production website and use the `goto` method to manipulate the URL, a new tab opened with a `//prerender/...` url.
- In version `225` that behaviour disappeared and the URL update worked as intended
- But when I now do a `//prerender/` search in the `build` folder, it matches every prerendered html file:
```js
start({
	target: document.querySelector("#svelte"),
	paths: {"base":"","assets":""},
	session: {},
	route: true,
	spa: false,
	trailing_slash: "never",
	hydrate: {
		status: 200,
		error: null,
		nodes: [
			import("/_app/pages/__layout.svelte-0057c1c3.js"),
			import("/_app/pages/_lang_/__layout.svelte-e41373d5.js"),
			import("/_app/pages/_lang_/index.svelte-5ab6d11c.js")
		],
		url: new URL("http://prerender/de"),
		params: {lang:"de"}
	}
});
```

**Comment by bluwy** [comment] 2022-01-15 08:34
> * But when I now do a `//prerender/` search in the `build` folder, it matches every prerendered html file:

This is normal as it's a valid URL. You can paste `new URL("http://prerender/de")` in the browser console to verify that `pathname` is `/de`.

@brittneypostma Can you confirm this is still an issue in the latest SvelteKit version?

**Comment by brittneypostma** [comment] 2022-01-15 12:32
Yes, this is same thing I am experiencing on sveltesirens.dev, I have a console.log running the `page.url.pathname` and it spits out the `//pretender/` instead of the expected `/` route.

**Comment by bluwy** [comment] 2022-01-15 13:55
Ah I didn't notice the `console.log` in production. When I inspect the HTML and search for `//prerender`, I noticed this in the markup:
```
import { start } from "/_app/start-297ca0d0.js";
start({
	target: document.querySelector("#svelte"),
	paths: {"base":"","assets":""},
	session: {},
	route: true,
	spa: false,
	trailing_slash: "never",
	hydrate: {
		status: 200,
		error: null,
		nodes: [
			import("/_app/pages/__layout.svelte-f663ade3.js"),
			import("/_app/pages/index.svelte-ba6002e1.js")
		],
		url: new URL("sveltekit://prerender/"),
		params: {}
	}
});
```

The `new URL("sveltekit://prerender/")` was there, but in recent versions, this should be `new URL("http://prerender/")` which fixes the issue. I checked the repo and SvelteKit wasn't updated yet, or was it tested locally?

I tried to spin up the svelte sirens repo locally too, but I'm getting `500 /speakers` error while building (adapt stage).

**Comment by metonym** [comment] 2022-01-15 19:51
I updated the [repro](https://github.com/metonym/sveltekit-page.url.pathname) to use the latest SvelteKit (v1.0.0-next.231) and also added `console.log($page.url.pathname)` to `routes/index.svelte`. I'm no longer seeing this error.

After building using the static adapter, I see "/" in the console, as expected.

**Comment by brittneypostma** [comment] 2022-01-23 00:10
Same here, after updating to latest, this issue seems to have been resolved.

**Closed** 2022-01-23 01:13 UTC
Labels: bug, p1-important

**Comment by ollyde** [comment] 2023-08-19 22:08
Also seeing the same issue but with `+layout.server.ts ` using the node adaptor, there seems to be no way to get the original request (which we need to set dynamic api urls)

My issue was closed very fast though, so not sure what to do, this seems like a bug too me

https://github.com/sveltejs/kit/issues/10586
