### ISSUE TITLE
CSS not loading properly after page navigation on Windows

### ISSUE THREAD

**Issue by asv1** [sveltejs/kit#956] opened 2021-04-10 17:57 UTC
https://user-images.githubusercontent.com/13184913/114505698-71b9c100-9c39-11eb-8b5b-59162f88e258.mp4

**Describe the bug**
CSS is not loaded properly when clicking on link. Only refresh page is helping here.

**Logs**

**To Reproduce**
Repository: [https://github.com/asv1/svelte_bug_ssr](https://github.com/asv1/svelte_bug_ssr)

1. npm run build
2. npm start
3. localhost:3000
4. click test link
5. see incorrect css.
6. reload page to see correct css.

**Expected behavior**
CSS is loaded properly

**Stacktraces**

**Information about your SvelteKit Installation:**

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 12.56 GB / 15.93 GB
  Binaries:
    Node: 14.16.0 - d:\portable\node\node.EXE
    npm: 6.14.11 - d:\portable\node\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.771
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5
```

**Severity**
I think bug is annoying because css not showed properly.

**Additional context**

**Comment by Theo-Steiner** [comment] 2021-04-11 04:18
I experience the same problem, and thought that it might be limited to dev and vite not properly reimporting css.
So I exported the site with `@sveltejs/adapter-static` and dragged and dropped it on netlify: But the problem even persists in production. 
```javascript
{
	"name": "skmb",
	"version": "0.0.1",
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"start": "svelte-kit start",
		"lint": "prettier --check . && eslint --ignore-path .gitignore .",
		"format": "prettier --write ."
	},
	"devDependencies": {
		"@sveltejs/adapter-node": "next",
		"@sveltejs/adapter-static": "^1.0.0-next.4",
		"@sveltejs/kit": "next",
		"eslint": "^7.22.0",
		"eslint-config-prettier": "^8.1.0",
		"eslint-plugin-svelte3": "^3.1.0",
		"prettier": "~2.2.1",
		"prettier-plugin-svelte": "^2.2.0",
		"svelte": "^3.29.0",
		"vite": "^2.1.0"
	},
	"type": "module"
}
```
You can see this behavior on [this netlify site](https://cocky-keller-ae2603.netlify.app/). (Click onto the upper right button of the "windows" and you can navigate to the "about page" upon navigating back by either using the browser navigation or the link on the about page, the css does not reload.)
I tried to reproduce this error on a fairly simple page but then it worked without hiccups. Please excuse the fairly big codebase and the terrible user experience but I was just playing around with converting my work-in-progress portfolio site from svelte to svelte-kit.
The source code for this netlify is [in this repo](https://github.com/Theo-Steiner/MortimerBaltus.com/tree/svelte-kit) (Just the svelte kit branch).

**Comment by asv1** [comment] 2021-04-11 06:19
@Theo-Steiner 
I have tested your site. If go from about page to home page - you have an empty page.
I think it vitejs bug, ssr here is experimental still.

**Comment by benmccann** [comment] 2021-04-13 00:00
Thanks for providing a repo to reproduce this. I just tried to reproduce this following you instructions and was not able to. I'm guessing there was perhaps an issue in some dependency that's been fixed. If you do `rm -rf package-lock.json node_modules && npm install` hopefully that fixes it for you

**Comment by asv1** [comment] 2021-04-13 05:17
@benmccann 
Bug does not dissapear :(. Have you checked Theo-Steiner repo too? Maybe windows related issue?

**Comment by asv1** [comment] 2021-04-13 06:21
@benmccann 
I have added a video in first message. Can you look at it?

**Comment by benmccann** [comment] 2021-04-13 06:25
Ah, this sounds like a duplicate of https://github.com/sveltejs/kit/issues/606

**Closed by benmccann** 2021-04-13 06:25 UTC
Labels: bug

**Comment by Theo-Steiner** [comment] 2021-04-13 08:35
@asv1 the problem on my site was caused by something else:
In the ScrollHandler.svelte component I accessed a DOM element in the upper level script tag. This resulted in an error, as I then subsequently tried to call scrollTop on that undefined component. If you actually open the console on this, you can see the error occurring.
This was easily fixed by putting the logic into onMount(), so that it is only run after the component is mounted.
Sorry for not noticing this earlier @ the svelte-kit team, keep up the great work!
