### ISSUE TITLE
Form Resets after Second Submit

### ISSUE THREAD

**Issue by n00ki** [sveltejs/kit#8909] opened 2023-02-06 17:03 UTC
### Describe the bug

I'm noticing a strange behavior on subsequent submits when using progressively enhanced form actions.
From the second form submission onwards, when the form elements' values are bound to the `ActionResult` data - the form resets all values (even if values were returned from the action successfully and exist in the `PageData` store).
In the attached video, you'll be able to see the responses to the first and second form submissions (passwords do not match in both cases). as email & password values are returned from the action, they remain in the form after calling `form.reset()`& `update()`. On the second submission onwards, though, they disappear.
Someone suggested that the reason for this behavior is the fact that SK doesn't update the form fields when the values don't change (the same actual values are returned from the server).
I want the form to reset and then get populated by data coming from the server, as it does on the first failed submission. It feels like the right flow to me (as it mimics the browser req-res default behavior).
I'm probably doing something wrong, yet beyond merely solving the issue I'd like to get a better understanding of the internal mechanism and flow.

https://user-images.githubusercontent.com/42724748/217035819-b3735fce-69ef-4420-89d6-9cb7a6c04355.mov

### Reproduction

https://gist.github.com/n00ki/ed50a7fdc6a96c077f3f32f8f8268557

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 115.29 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 107.0.1
    Firefox Developer Edition: 109.0
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.2 => 1.0.2
    @sveltejs/kit: ^1.3.9 => 1.3.9
    svelte: ^3.55.1 => 3.55.1
    vite: ^4.0.4 => 4.0.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment] 2023-02-06 17:04
Probably a duplicate of #8513

**Comment by n00ki** [comment] 2023-02-06 18:21
> Probably a duplicate of #8513

Probably.
Can we expect the suggested fix to be submitted any time soon?

**Comment by Rich-Harris** [comment] 2023-02-06 21:20
definitely a dupe — closing. it'll be fixed when someone fixes it :)

**Closed by Rich-Harris** 2023-02-06 21:20 UTC
