### ISSUE TITLE
ReferenceError: props_0 is not defined When trying to update svelte file

### ISSUE THREAD

**Issue by omar2205** [sveltejs/kit#644] opened 2021-03-24 18:17 UTC
**Describe the bug**
**Just an FYI** Sometimes HMR doesn't work (update content), results in this error `ReferenceError: props_0 is not defined`

https://user-images.githubusercontent.com/1373867/112363492-384b0100-8cde-11eb-9077-d28fc08b75a7.mp4

**Logs**
```
ReferenceError: props_0 is not defined
at $HOME/sveltekit/demo/.svelte/dev/generated/root.svelte:41:20
at $$render ($HOME/sveltekit/demo/node_modules/.pnpm/svelte@3.35.0/node_modules/svelte/internal/index.js:1369:22)                                                                                       
at Object.render ($HOME/sveltekit/demo/node_modules/.pnpm/svelte@3.35.0/node_modules/svelte/internal/index.js:1377:26)                                                                                  
at get_response (file://$HOME/sveltekit/demo/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.58_svelte@3.35.0+vite@2.1.2/node_modules/@sveltejs/kit/dist/ssr.js:2326:27)
at async get_response (file://$HOME/sveltekit/demo/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.58_svelte@3.35.0+vite@2.1.2/node_modules/@sveltejs/kit/dist/ssr.js:2330:10)
at async render_page (file://$HOME/sveltekit/demo/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.58_svelte@3.35.0+vite@2.1.2/node_modules/@sveltejs/kit/dist/ssr.js:2440:19)
at async ssr (file://$HOME/sveltekit/demo/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.58_svelte@3.35.0+vite@2.1.2/node_modules/@sveltejs/kit/dist/ssr.js:2594:9)
at async Immediate.<anonymous> (file://$HOME/sveltekit/demo/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.58_svelte@3.35.0+vite@2.1.2/node_modules/@sveltejs/kit/dist/chunks/index2.js:3286:23) 
```

**To Reproduce**
1. pnpm init svelte@next demo
2. pnpm i
3. pnpm dev
4. update `routes/index.svelte`

**Expected behavior**
Update DOM content without errors

**Information about your SvelteKit Installation:**

- Your browser
Chrome89
- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
node

**Severity**
LOW

**Comment by Rich-Harris** [comment] 2021-04-02 21:30
I'm unable to reproduce this (it could have been a bug in Vite that's since fixed) so I'll close this issue — thanks

**Closed by Rich-Harris** 2021-04-02 21:30 UTC
Labels: bug
