### ISSUE TITLE
Title deduplication wrongly uses parent title

### ISSUE THREAD

**Issue by vwkd** [sveltejs/kit#2146] opened 2021-08-09 17:24 UTC
### Describe the bug

If the parent component declares a title *after* the child component tag, then the parent component's title is used instead of the child component's.

According to @Conduitry in https://github.com/sveltejs/kit/issues/2009#issuecomment-886740203 the title of the deepest child component should be used instead.

> `<title>` is replaced by **lower-level components**

### Reproduction

See https://github.com/vwkd/sveltekit-bugs/tree/wrong-title

This example uses probably the most common case where the parent component is the layout component and the child component is the index component. But the issue occurs for any parent and child component pair.

### System Info

```shell
System:
    OS: macOS 11.5
  Binaries:
    Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
    npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.11 => 1.0.0-next.16 
    @sveltejs/kit: next => 1.0.0-next.142 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

annoyance

**Comment by benmccann** [comment] 2021-08-09 20:24
Duplicate of https://github.com/sveltejs/kit/issues/1540

**Closed by benmccann** 2021-08-09 20:24 UTC
