### ISSUE TITLE
Favicon Loading

### ISSUE THREAD

**Issue by Brolupyr777** [sveltejs/kit#11498] opened 2024-01-02 03:57 UTC
### Describe the bug

Whenever you try to swap the preloaded favicon from the skeleton project to your own, it refuses to do so unless you switch the HTML link to a non-existent path, reload, and set it back.

### Reproduction

`Need to install the following packages:
  create-svelte@6.0.5
Ok to proceed? (y) y

create-svelte version 6.0.5

┌  Welcome to SvelteKit!
│
◇  Where should we create your project?
│    (hit Enter to use current directory)
│
◇  Which Svelte app template?
│  Skeleton project
│
◇  Add type checking with TypeScript?
│  No
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-add

Next steps:
  1: npm install
  2: git init && git add -A && git commit -m "Initial commit" (optional)
  3: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat`

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (4) x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
    Memory: 16.30 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 16.5.2
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.1 
    @sveltejs/kit: ^2.0.0 => 2.0.6 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.10
```

### Severity

serious, but I can work around it

### Additional Information

Frustrating since I spent a decent amount of time trying to work with this problem not knowing of its existence.

**Comment by Conduitry** [comment] 2024-01-02 04:07
Duplicate of #11158.

**Closed by Conduitry** 2024-01-02 04:07 UTC

**Comment by Conduitry** [comment] 2024-01-02 04:08
Browsers cache favicon.ico files very aggressively. That's just how they work, it's unrelated to Svelte, and there's not really anything we can reasonably do about that.
