### ISSUE TITLE
Type definition for `goto` does not include `state`

### ISSUE THREAD

**Issue by WaltzingPenguin** [sveltejs/kit#11391] opened 2023-12-19 01:12 UTC
### Describe the bug

Using `state` as a parameter for `goto` fails TypeScript validation.  The type definition for `goto` is missing state.
```
@type {(url: string | URL, opts?: { replaceState?: boolean; noScroll?: boolean; keepFocus?: boolean; invalidateAll?: boolean; }) => Promise<void>}
```

### Reproduction

[StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-fxagsl?file=src%2Froutes%2F%2Bpage.svelte)

In the terminal, run `npm run check`

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.0 
    @sveltejs/kit: ^2.0.3 => 2.0.3 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.10
```

### Severity

annoyance

**Comment by LorisSigrist** [comment] 2023-12-19 09:16
`goto`'s state argument must adhere to the`App.PageState` interface as of SvelteKit 2.0. I believe you need to edit it in `app.d.ts`. 

https://kit.svelte.dev/docs/migrating-to-sveltekit-2#goto-changes

**Comment by eltigerchino** [comment] 2023-12-19 15:19
closed as duplicate of https://github.com/sveltejs/kit/issues/11397

**Closed by eltigerchino** 2023-12-19 15:19 UTC
