### ISSUE TITLE
Consistent strictness

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#5226] opened 2022-06-19 12:25 UTC
### Describe the problem

It appears that sveltekit isn't as strict during dev as during build.

See the silly mistake i made in the snippet below. When in `pnpm dev`, this endpoint magically works and there is no problem with me not declaring the variable first. However, when you `pnpm build` > `pnpm preview`, the same script will cause a runtime error.

```js
export function get()
{
    test = 123
    
    return {
        status: 200,
        body: {
            test
        }
    }
}
```

### Describe the proposed solution

Normalizing strictness. Both environments should throw an error.

### Alternatives considered

Keep this as is since it indirectly serves as a good reminder to check the sloppiness of the code you've written so far.
Or maybe run the endpoints in strict mode like after build? Not sure if that is possible though.

### Importance

would make my life easier

**Comment by UltraCakeBakery** [comment] 2022-06-19 12:28
Feel free to change the title to better fit the actual issue. I already spend too much time on this simple, possibly duplicate, issue 😅

**Comment by gtm-nayan** [comment] 2022-06-19 12:37
Wouldn't say it's a duplicate since the previous one was closed and we ought to do something about it.

I used to think that this was caused by strict mode not being present in dev mode, but now I remember modules should be strict by default right? Might be something weird going on there because of pre bundling otherwise the solution would be a lint rule I guess.

**Comment by Rich-Harris** [comment] 2022-07-18 19:04
This is a Vite issue — closing in favour of https://github.com/vitejs/vite/issues/9197

**Closed by Rich-Harris** 2022-07-18 19:04 UTC
