### ISSUE TITLE
Referencing a worker with URL breaks the build 

### ISSUE THREAD

**Issue by wyozi** [sveltejs/kit#9646] opened 2023-04-11 18:59 UTC
### Describe the bug

Running `npm build` breaks with `Error: Could not find file "node_modules/.pnpm/@sveltejs+kit@1.15.4_svelte@3.58.0+vite@4.2.1/node_modules/@sveltejs/kit/src/runtime/client/start.js" in Vite manifest`. This is caused by referencing a worker js file using `new Worker(new URL(.., import.meta.url))`

Even if this is caused by something like an invalid worker file (which it isn't, since it works fine in dev mode), the error message (or creation of start.js) should not break because of this

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-e7zbcm?file=src/routes/+layout.svelte

See src/routes/+layout.svelte. Reproduce by running `npm run build`

### System Info

```Shell
Reproable in stackblitz. Latest packages
```

### Severity

blocking an upgrade

### Additional Information

Unable to release a package using sveltekit due to the bug

**Comment by bluwy** [comment] 2023-04-12 03:39
Duplicate of https://github.com/sveltejs/kit/issues/9528

**Closed by bluwy** 2023-04-12 03:39 UTC
