### ISSUE TITLE
ESLint complains of unresolved when using $lib alias.

### ISSUE THREAD

**Issue by justingolden21** [sveltejs/kit#5564] opened 2022-07-16 04:11 UTC
### Describe the bug

When using the $lib alias, ESLint complains. See `import/no-unresolved`

### Reproduction

Create a `$lib` alias for your `lib` folder and import from there with ESLint set up.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.28 GB / 15.65 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-netlify: 1.0.0-next.49 => 1.0.0-next.49
    @sveltejs/kit: 1.0.0-next.291 => 1.0.0-next.291
    svelte: ^3.43.1 => 3.46.4
```

### Severity

annoyance

### Additional Information

Found this link: https://stackoverflow.com/questions/67685232/how-to-tell-eslint-about-the-svelte-kit-lib-folder

But no resolution and searched issues for "lib" and "eslint" but nothing relevant.

My workaround is adding:
`"import/no-unresolved": "off",`
To my `.eslintrc.json` but one could see how that's problematic (1. it should work out of the box, 2. this ignores potentially unwanted unresolved imports)

As a side note, since this is also ESLint and Svelte Kit related, having routes that have a single `get()` function have ESLint complain about preferring default export. I have to add
`// eslint-disable-next-line import/prefer-default-export`
above every single route in my project with a `get()` function.

**Comment by tcc-sejohnson** [comment] 2022-07-17 15:47
From the bug template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be short, self-contained and correct and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

It is much more likely we will look at this if you provide a repro.

My best guess is that you haven't run `npm i` or you need to run `npm run prepare`. You should not have to create a `$lib` alias at all -- it is provided by SvelteKit by default.

**Comment by justingolden21** [comment] 2022-07-18 21:51
It seems like `eslint-config-airbnb-base` was the problem. I tried adding it back to get formatting to work and it started complaining about everything again when running `lint`

```
C:\Users\justi\Documents\GitHub\desktopclock\src\lib\util\now.js
  5:26  error  Unable to resolve path to module '$lib/stores/settings'  import/no-unresolved

C:\Users\justi\Documents\GitHub\desktopclock\src\lib\util\timeText.js
  16:26  error  Unable to resolve path to module '$lib/stores/settings'  import/no-unresolved
  17:21  error  Unable to resolve path to module '$lib/util/now'         import/no-unresolved

C:\Users\justi\Documents\GitHub\desktopclock\src\lib\util\timetableDiff.js
   5:26  error    Unable to resolve path to module '$lib/stores/settings'  import/no-unresolved

C:\Users\justi\Documents\GitHub\desktopclock\src\routes\manifest.webmanifest.js
  4:1  error  Prefer default export  import/prefer-default-export

C:\Users\justi\Documents\GitHub\desktopclock\src\routes\robots.txt.js
  3:24  error  Unable to resolve path to module '$lib/data/consts'  import/no-unresolved
  5:1   error  Prefer default export                                import/prefer-default-export

C:\Users\justi\Documents\GitHub\desktopclock\src\routes\sitemap.xml.js
   3:24  error    Unable to resolve path to module '$lib/data/consts'  import/no-unresolved
  26:1   error    Prefer default export                                import/prefer-default-export
  35:1   warning  Expected indentation of 2 tabs but found 3           indent
  36:1   warning  Expected indentation of 3 tabs but found 4           indent
  37:1   warning  Expected indentation of 4 tabs but found 5           indent
  42:1   warning  Expected indentation of 2 tabs but found 3           indent
  43:1   warning  Expected indentation of 2 tabs but found 3           indent

C:\Users\justi\Documents\GitHub\desktopclock\src\service-worker.js
  7:41  error  Unable to resolve path to module '$service-worker'  import/no-unresolved
```

**Comment by justingolden21** [comment] 2022-07-18 22:04
Also, "error  Unable to resolve path to module '$lib/" gets 5 results on google, none of which are relevant except a SO post with no answers.

**Comment by tcc-sejohnson** [comment] 2022-07-18 22:06
Again, without a repro, this is pretty hard to help with.

**Comment by turkerdev** [comment] 2022-07-20 20:47
i had to add ``files: { lib: 'src/lib' }`` to config file.
this suppose to be default but seems like there is an issue.

**Comment by dominikg** [comment] 2022-07-21 07:04
prepare runs `svelte-kit sync`, which is also run at the start of dev and build. So this is mostly a temporary situation, albeit an unfortunate one.

The prepare lifecycle isn't the ideal solution to ensure sync is called immediately upon updating, in https://github.com/sveltejs/kit/issues/4585 there is a discussion to use postinstall of kit instead.

**Comment by tcc-sejohnson** [comment] 2022-07-22 02:09
So...

Is there actually a bug here, or is all of this just vaguely illustrating the rough edges with how and when `svelte-kit sync` runs?

**Comment by tcc-sejohnson** [comment] 2022-08-01 23:47
@benmccann 

I _think_ we can close this.

**Comment by dominikg** [comment] 2022-08-02 18:58
- no reproduction has been provided in 2 weeks
- part of the original report was caused by a third party eslint ruleset
- we changed the way `svelte-kit sync` is called on project initialization since then

@justingolden21 if this problem still persists for you with the latest version of svelte-kit, please file a new issue and include a link to a repository where we can reproduce it.

**Closed by dominikg** 2022-08-02 18:58 UTC
Labels: awaiting submitter
