### ISSUE TITLE
error with forwarded events

### ISSUE THREAD

**Issue by 524c** [sveltejs/kit#8218] opened 2022-12-18 20:46 UTC
### Describe the bug

related to the #8217

```stacktrace
The symbol "mouseenter_handler" has already been declared
814|    }
815|
816|    function mouseenter_handler(event) {
   |            ^
817|            bubble.call(this, $$self, event);
818|    }

The symbol "mouseleave_handler" has already been declared
818|    }
819|
820|    function mouseleave_handler(event) {
   |            ^
821|            bubble.call(this, $$self, event);
822|    }

The symbol "focusin_handler" has already been declared
822|    }
823|
824|    function focusin_handler(event) {
   |            ^
825|            bubble.call(this, $$self, event);
826|    }

The symbol "focusout_handler" has already been declared
826|    }
827|
828|    function focusout_handler(event) {
   |            ^
829|            bubble.call(this, $$self, event);
830|    }

The symbol "mouseenter_handler_1" has already been declared
846|    }
847|
848|    function mouseenter_handler_1(event) {
   |            ^
849|            bubble.call(this, $$self, event);
850|    }

The symbol "mouseleave_handler_1" has already been declared
850|    }
851|
852|    function mouseleave_handler_1(event) {
   |            ^
853|            bubble.call(this, $$self, event);
854|    }

The symbol "focusin_handler_1" has already been declared
854|    }
855|
856|    function focusin_handler_1(event) {
   |            ^
857|            bubble.call(this, $$self, event);
858|    }

The symbol "focusout_handler_1" has already been declared
858|    }
859|
860|    function focusout_handler_1(event) {
   |            ^
861|            bubble.call(this, $$self, event);
862|    }

error during build:
Error: Transform failed with 8 errors:
_app/immutable/components/pages/_page.svelte-!~{004}~.js:816:10: ERROR: The symbol "mouseenter_handler" has already been declared
_app/immutable/components/pages/_page.svelte-!~{004}~.js:820:10: ERROR: The symbol "mouseleave_handler" has already been declared
_app/immutable/components/pages/_page.svelte-!~{004}~.js:824:10: ERROR: The symbol "focusin_handler" has already been declared
_app/immutable/components/pages/_page.svelte-!~{004}~.js:828:10: ERROR: The symbol "focusout_handler" has already been declared
_app/immutable/components/pages/_page.svelte-!~{004}~.js:848:10: ERROR: The symbol "mouseenter_handler_1" has already been declared
...
    at failureErrorWithLog (/Users/rlucas/Desktop/sveltejs-kit-template/node_modules/.pnpm/esbuild@0.16.9/node_modules/esbuild/lib/main.js:1594:15)
    at /Users/rlucas/Desktop/sveltejs-kit-template/node_modules/.pnpm/esbuild@0.16.9/node_modules/esbuild/lib/main.js:831:29
    at responseCallbacks.<computed> (/Users/rlucas/Desktop/sveltejs-kit-template/node_modules/.pnpm/esbuild@0.16.9/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/rlucas/Desktop/sveltejs-kit-template/node_modules/.pnpm/esbuild@0.16.9/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/rlucas/Desktop/sveltejs-kit-template/node_modules/.pnpm/esbuild@0.16.9/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

```
# clone the repo
git clone https://github.com/524c/sveltejs-kit-template
```

```sh
# steps to reproduce
cd sveltejs-kit-template
pnpm i
pnpm build
```

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 33.38 MB / 8.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.n/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 105.0
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/kit: ^1.0.1 => 1.0.1
    svelte: ^3.54.0 => 3.55.0
    vite: ^4.0.2 => 4.0.2
```

### Severity

blocking all usage of SvelteKit

**Comment by dominikg** [comment] 2022-12-18 21:07
going to close this as duplicate of  #8217, the issue you already mentioned

**Closed by dominikg** 2022-12-18 21:07 UTC

**Comment by 524c** [comment] 2022-12-18 21:24
In the repository I created for repro, if you downgrade the esbuild, this error does not occur.

```
  rm -rf node_modules pnpm-lock.yaml .svelte-kit
  pnpm i esbuild@0.16.8
  npx svelte-kit sync
  pnpm build
```
