### ISSUE TITLE
Faulty <svelte:head> breaks styles in dev silently

### ISSUE THREAD

**Issue by iverks** [sveltejs/kit#10653] opened 2023-08-29 23:04 UTC
### Describe the bug

All styles break.

When sveltekit is hydrating the head, a faulty entry causes a silent fail, making a very hard to track down issue.

### Reproduction

https://github.com/iverks/sveltekit-head-bug

Note that the only thing necessary is

```
<svelte:head>
    <icon rel="favicon" src={"/favicon.ico"} />
</svelte:head>
```

which i have added 

### Logs

```Shell
There are no errors in console, nor in terminal. This is why the issue is so important, because it was impossible to debug.
```

### System Info

```Shell
Doesn't matter, reproduces in stackblitz and in sveltekit tutorial simulator.
```

### Severity

annoyance

**Comment by s3812497** [comment] 2023-10-05 12:47
Seemingly only occurs for invalid elements inside of `<head>`. Not sure what the cause is though. And it doesn't seem to happen in a Svelte REPL (exclusive to SvelteKit??)

**Comment by eltigerchino** [comment] 2024-12-04 07:24
Closing this because I can't reproduce it on the latest version of Svelte and SvelteKit

**Closed by eltigerchino** 2024-12-04 07:24 UTC
Labels: bug, p3-edge-case
