### ISSUE TITLE
Unable to use third party custom elements

### ISSUE THREAD

**Issue by fcrozatier** [sveltejs/kit#6509] opened 2022-09-01 13:45 UTC
### Describe the bug

Third party custom elements work fine in `app.html` but not in `+page.svelte`. 
I've only tested with Pyscript custom elements.

### Reproduction

[Reproduction repo](https://github.com/fcrozatier/kit_pyscript)

### System Info

```shell
System:
    OS: macOS 11.6.8
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 290.84 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.8.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Firefox Developer Edition: 105.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.70 
    @sveltejs/kit: next => 1.0.0-next.456 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

serious, but I can work around it

### Additional Information

Pyscript would bring pandas, numpy, matplotlib etc. to a sveltekit app...

**Comment by fcrozatier** [comment] 2022-09-03 06:20
Do you have a reproduction repo? This would document the issue a bit more

**Comment by Rich-Harris** [comment] 2022-09-03 15:47
It _looks_ like Pyscript has the same bug as Ionic — the custom element adds an `id` attribute to itself when it upgrades, which is destroyed by hydration: https://github.com/sveltejs/kit/issues/5143#issuecomment-1190843804

In the Ionic case, that basically rules out using the library with SSR. But in this case, since SSR doesn't really matter, all you need to do is ensure that the library doesn't load until after hydration:

```svelte
<!-- src/routes/+layout.svelte -->
<script>
  import { onMount } from 'svelte';

  onMount(async () => {
    await import('https://pyscript.net/latest/pyscript.js');
  });
</script>
```

You'll get some FOUC until the element is able to upgrade, of course. You could make this more sophisticated by waiting until the library has been imported before showing the elements, and you could abstract all that into a `<PyScript>` component if you were so inclined.

**Comment by Rich-Harris** [comment] 2022-09-03 16:24
will close this since I've tested this and confirmed it works

**Closed by Rich-Harris** 2022-09-03 16:24 UTC

**Comment by fcrozatier** [comment] 2022-09-03 19:49
Thanks for the explanations!
