### ISSUE TITLE
Fail prerendering if a page is shadowed by an endpoint

### ISSUE THREAD

**Issue by alexbjorlig** [sveltejs/kit#3410] opened 2022-01-19 11:54 UTC
### Describe the bug

If you create a `bob/index` with a POST and `bob/index.svelte` --> posting will not work when deployed to Vercel.

Vercel throws error 405.

### Reproduction

Deploy this [repo](https://github.com/21RISK/sveltekit) to Vercel, and visit `/bob` and hit the submit button - and then the error will appear.

As long as it exists 😅, you can also try it here: https://sveltekit-p9hxntt45-jeddah.vercel.app/bob

### System Info

```shell
Latest version `next` of kit and vercel adapter.
```

### Severity

serious, but I can work around it

### Additional Information

I can simply work around by not enabling `prerender=true` on the sveltekit component.

![Screen Shot 2022-01-19 at 12 53 36](https://user-images.githubusercontent.com/9967422/150124784-b7e292ea-3f40-4508-9b8c-ddefe20f0a02.png)

Let me know if you need more information 😎

**Comment by Rich-Harris** [comment] 2022-01-25 18:40
This is expected behaviour — prerendered pages always take priority over dynamic endpoints. The reason for that is that in most environments (Vercel included) there isn't even an opportunity to run SvelteKit if a matching file exists on the filesystem. The 405 you're seeing is coming from Vercel itself, which sees a request for `/bob`, sees that there's a matching `bob/index.html` file already prerendered, then says 'hang on a minute, you can't POST to a prerendered file'.

So you'll always need to disable prerendering for these pages. We could probably do a better job of diagnosing this at build time — if a page is shadowed by an endpoint, prerendering should fail. (When we implement #3532, we can change that to 'if a page is shadowed by an endpoint with non-GET handlers'.)

**Comment by tcc-sejohnson** [comment] 2022-04-22 20:55
@benmccann 

Can also take this one if you give me the go-ahead.

**Comment by tcc-sejohnson** [comment] 2022-05-03 23:58
@Rich-Harris

I was looking into this one, and I think you can just close it.

In the `prerendering/basics` test project, there's [already a test](https://github.com/sveltejs/kit/blob/39eaf0905f28c55ba7ee3fe9ba67ec487290a6b2/packages/kit/test/prerendering/basics/test/test.js#L71) verifying this behavior. The only reason the project can even build is because `continueOnError === true` for the test project. If it weren't, you'd see the error `'Cannot prerender pages that have endpoints with mutative methods'` thrown from [this line](https://github.com/sveltejs/kit/blob/39eaf0905f28c55ba7ee3fe9ba67ec487290a6b2/packages/kit/src/runtime/server/page/load_node.js#L408) and build would fail.

So I think this one's a freebie. :)

**Comment by tcc-sejohnson** [comment] 2022-05-04 00:02
[Here's a repo proving the point.](https://github.com/tcc-sejohnson/kit-mutative-prerender-fails)

**Comment by tcc-sejohnson** [comment] 2022-05-04 02:30
Looking into it a bit further, the only case in which this doesn't work is when running in dev (because the current condition only checks `state.prerender`). If we wanted it to throw when running the dev server, we could change [this line](https://github.com/sveltejs/kit/blob/39eaf0905f28c55ba7ee3fe9ba67ec487290a6b2/packages/kit/src/runtime/server/page/load_node.js#L61) to `node.module.prerender ?? state?.prerender?.default ?? false`. `prerender` isn't used anywhere else inside of `load_shadow_data`, so it won't cause any unexpected behavior. All tests still pass (I checked). If we want to make that change, I'm happy to open a PR.

**Comment by benmccann** [comment] 2022-05-04 03:09
Thanks for taking a look @tcc-sejohnson. I agree it's better to fail during dev when possible if an error state is encountered

**Comment by tcc-sejohnson** [comment] 2022-05-04 03:20
Thanks @benmccann. Opened #4812. That PR should also fix #4252 (it's pretty much a duplicate of this issue).

**Comment by benmccann** [comment] 2022-05-04 03:38
> That PR should also fix https://github.com/sveltejs/kit/issues/4252 (it's pretty much a duplicate of this issue).

I edited the PR description to include "fixes" before each issue number. You can see it linked the issues on the side of the PR so that they'll be automatically closed if the PR is merged

**Comment by tcc-sejohnson** [comment] 2022-05-04 03:42
> I edited the PR description to include "fixes" before each issue number. You can see it linked the issues on the side of the PR so that they'll be automatically closed if the PR is merged

Thanks! I was wondering why some of my PRs would auto-close issues and others wouldn't... I edited the few I have open as well.

**Closed** 2022-05-23 20:12 UTC
Labels: bug, help wanted, p2-nice-to-have
