### ISSUE TITLE
Svelte overrides (?) loaded JS from `<script>` tag

### ISSUE THREAD

**Issue by ItzaMi** [sveltejs/kit#2442] opened 2021-09-16 13:33 UTC
### Describe the bug

Once you load the page you're able to see the styled buttons but they immediately get unstyled

https://user-images.githubusercontent.com/30603437/133248943-7c035ca1-e240-4637-bc79-b2f3704cc8a2.mp4

Here's my setup

```javascript
// __layout.svelte

<footer class="footer">
  <SocialShare />
</footer>
```

```html
<body>
  <div id="svelte">%svelte.body%</div>

  <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
```

```javascript
// SocialShare.svelte
<a
  class="github-button"
  href="https://github.com/itzami"
  data-color-scheme="light"
  data-size="large"
  data-show-count="true"
  aria-label="Follow @itzami on GitHub">Follow @itzami</a
>

<a
  class="github-button"
  href="https://github.com/sponsors/itzami"
  data-color-scheme="light"
  data-icon="octicon-heart"
  data-size="large"
  aria-label="Sponsor @itzami on GitHub">Sponsor</a
>
```

### Reproduction

The reproducible version can be found [here](https://github.com/ItzaMi/sveltekit-github-buttons-bug)

### Logs

```shell
There are no errors on the logs
```

### System Info

```shell
System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 298.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /opt/homebrew/opt/node@14/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.13 - /opt/homebrew/opt/node@14/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Firefox Developer Edition: 92.0
    Safari: 14.0.3
  npmPackages:
    svelte: ^3.34.0 => 3.42.1
```

### Severity

annoyance

**Comment by Conduitry** [comment] 2021-09-16 13:59
I've transferred this to the SvelteKit repo since it looks like that's what you're using.

We also need a reproduction that we can clone.

**Comment by ItzaMi** [comment] 2021-09-16 16:12
Thank you, @Conduitry. I'll update the issue with the reproducible version (can also be found [here](https://github.com/ItzaMi/sveltekit-github-buttons-bug))

**Comment by rmunn** [comment] 2021-09-22 06:48
I cloned the reproduction, and it looks like there's a bit of a race condition between the https://buttons.github.io/buttons.js script and Svelte's Javascript. When I refresh a bunch of times, sometimes both buttons end up getting styled and then immediately unstyled, and sometimes they start out looking unstyled and then get styled.

Looking at [the source for the buttons.js script](https://github.com/ntkme/github-buttons/blob/929ffc44932465e8b6d2ceda38a7199bf4f4db95/dist/buttons.js#L560), I see it's doing this:

```js
defer(function () {
  var anchors = document.querySelectorAll('a.github-button');
  forEach(anchors, function (anchor) {
    render(anchor, function (el) {
      anchor.parentNode.replaceChild(el, anchor);
    });
  });
});
```

where `defer()` is a function that waits for the document to be ready before running your code.

So what's happening here is that Svelte and the buttons.js code are both expecting to be able to update the elements in the footer. If buttons.js gets there first, then Svelte comes along and replaces the elements that buttons.js added. If Svelte gets there first, then buttons.js comes along and replaces the elements that Svelte added.

In other words, this is a Javascript library whose basic approach is incompatible with Svelte. What you need to do is what the library's author told you in https://github.com/ntkme/github-buttons/issues/76#issuecomment-919374949: move your button code outside of the part of the page that Svelte is controlling. In other words, this will solve your problem:

```diff
diff --git a/src/app.html b/src/app.html
index 5bb079d..fb1595c 100644
--- a/src/app.html
+++ b/src/app.html
@@ -15,5 +15,24 @@
        </head>
        <body>
                <div id="svelte">%svelte.body%</div>
+               <footer class="footer">
+                       <a
+                               class="github-button"
+                               href="https://github.com/itzami"
+                               data-color-scheme="light"
+                               data-size="large"
+                               data-show-count="true"
+                               aria-label="Follow @itzami on GitHub">Follow @itzami</a
+                       >
+
+                       <a
+                               class="github-button"
+                               href="https://github.com/sponsors/itzami"
+                               data-color-scheme="light"
+                               data-icon="octicon-heart"
+                               data-size="large"
+                               aria-label="Sponsor @itzami on GitHub">Sponsor</a
+                       >
+               </footer>
        </body>
 </html>
diff --git a/src/routes/__layout.svelte b/src/routes/__layout.svelte
index 6122159..cba1765 100644
--- a/src/routes/__layout.svelte
+++ b/src/routes/__layout.svelte
@@ -5,22 +5,3 @@
 <div class="max-w-screen-xl m-auto">
        <slot />
 </div>
-<footer class="footer">
-       <a
-               class="github-button"
-               href="https://github.com/itzami"
-               data-color-scheme="light"
-               data-size="large"
-               data-show-count="true"
-               aria-label="Follow @itzami on GitHub">Follow @itzami</a
-       >
-
-       <a
-               class="github-button"
-               href="https://github.com/sponsors/itzami"
-               data-color-scheme="light"
-               data-icon="octicon-heart"
-               data-size="large"
-               aria-label="Sponsor @itzami on GitHub">Sponsor</a
-       >
-</footer>
```

**Closed** 2021-09-22 06:56 UTC
Labels: pending clarification

**Comment by ItzaMi** [comment] 2021-09-22 09:50
Thank you, @rmunn. I reached that conclusion of inserting it directly on `app.html` but, obviously, I was trying to prevent that.
Thank you for the explanation and for letting me know that `this is a Javascript library whose basic approach is incompatible with Svelte`. This pretty much tells me that there's no way of fighting this and I'll now try to build out something that indeed works with Svelte!

🤘
