### ISSUE TITLE
Forms don't work on localhost with adblock enabled

### ISSUE THREAD

**Issue by SaranSundar** [sveltejs/kit#10272] opened 2023-06-28 03:17 UTC
### Describe the bug

When using a form on localhost with uBlock origin a popular adblocker enabled

the behavior is very strange, it appends the forms fields to the url and causes a page reload, and never triggers the method in the forms on:submit|preventDefault={handleSubmit} 

http://localhost:5173/signup?email=test%40gmail.com&password=test

But when deployed to prod with vercel or disabling ad blocker the form works as expected where the input is not added to the url and page does not hard reload

So the issue is only present on localhost chrome with ad blocker enabled

```
<script lang="ts">
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';
	import { auth } from '../../stores/auth';

	import { initFirebase } from '$lib/firebase';
	import { createUserWithEmailAndPassword, type User } from 'firebase/auth';

	let error = '';
	let loading = false;

	onMount(() => {
		return auth.subscribe((user) => {
			console.log('Auth state changed in signup', user);
			if (user) {
				goto('/');
			}
		});
	});

	const signup = async (email: string | undefined, password: string | undefined): Promise<User> => {
		console.log('Email is ' + email + ' password is ' + password);
		if (!email || !password) {
			throw new Error('Email and password are required');
		}
		const { firebaseAuth } = initFirebase();
		const res = await createUserWithEmailAndPassword(firebaseAuth, email, password);
		return res.user;
	};

	async function handleSubmit(this: HTMLFormElement, event: unknown): Promise<void> {
		const formData = new FormData(this);
		const email = formData.get('email')?.toString();
		const password = formData.get('password')?.toString();

		loading = true;
		try {
			await signup(email, password);
		} catch (err) {
			error = String(err);
		} finally {
			loading = false;
		}
	}
</script>

<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
	<div class="sm:mx-auto sm:w-full sm:max-w-sm">
		<img
			class="mx-auto h-10 w-auto"
			src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
			alt="Your Company"
		/>
		<h2 class="h2 mt-10 text-center text-2xl font-bold leading-9 tracking-tight">
			Create a new account
		</h2>
	</div>

	<div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
		<form on:submit|preventDefault={handleSubmit} class="space-y-6">
			<div>
				<label for="email" class="label block text-sm font-medium leading-6">Email address</label>
				<div class="mt-2">
					<input
						disabled={loading}
						id="email"
						name="email"
						type="email"
						autocomplete="email"
						required
						class="input block w-full rounded-md border-0 py-1.5 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
					/>
				</div>
			</div>

			<div>
				<div class="flex items-center justify-between">
					<label for="password" class="label block text-sm font-medium leading-6">Password</label>
					<div class="text-sm">
						<a href="#" class="font-semibold text-indigo-600 hover:text-indigo-500"
							>Forgot password?</a
						>
					</div>
				</div>
				<div class="mt-2">
					<input
						disabled={loading}
						id="password"
						name="password"
						type="password"
						autocomplete="current-password"
						required
						class="input block w-full rounded-md border-0 py-1.5 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
					/>
				</div>
			</div>

			<div>
				<button
					disabled={loading}
					type="submit"
					class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
				>
					Sign Up
				</button>
			</div>
		</form>

		{#if error}
			<div class="mt-8 p-8 text-red-500 bg-red-100">There was an error registering: {error}</div>
		{/if}

		<p class="mt-10 text-center text-sm">
			Already have an account?
			<a href="#" class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500"
				>Sign in here</a
			>
		</p>
	</div>
</div>
```

### Reproduction

Try doing a form input submission on localhost chrome with u origin ad block on mac os ventura 13.4.1 chrome version 114.0.5735.133

### System Info

```Shell
N/A
```

### Severity

serious, but I can work around it

**Comment by hyunbinseo** [comment] 2023-06-28 06:18
I cannot reproduce the issue.

This seems to be the MRE, and it works as expected - the default action is not called on (localhost + ad-block).

```svelte
<script lang="ts">
  async function handleSubmit(this: HTMLFormElement): Promise<void> {
    console.log(Date.now());
  }
</script>

<form on:submit|preventDefault={handleSubmit}>
  <input name="email" type="email" required />
  <input name="password" type="password" required />
  <button type="submit">Sign Up</button>
</form>
```

Could you provide a reproduction repository? Or at least the system information and the browser logs?

> **Note**
> The browser is fully reloaded to the following URL because the `preventDefault` is not applied successfully. This is the browser default behavior.

```
http://localhost:5173/signup?email=test%40gmail.com&password=test
```

**Comment by bluwy** [comment] 2023-06-28 06:27
Don't think this is really something SvelteKit can fix. Most of the time this happens because you have some file named suspiciously like `analytics.js`, and in dev this file is served as-is individually so the adblocker sees the name and blocks it. In prod, the file is bundled so the adblocker doesn't see it. You can check the network tab and see what is being blocked.

**Comment by dummdidumm** [comment] 2023-06-28 10:34
Closing as @bluwy outlined this is usually due to file names etc - and we can't control what the adblocker does with the site. It's probably best to disable the ad blocker on localhost.

**Closed by dummdidumm** 2023-06-28 10:34 UTC
