### ISSUE TITLE
Page sends "accept: '*/*'" to page endpoint, but really only accepts 'application/json'

### ISSUE THREAD

**Issue by bluepuma77** [sveltejs/kit#4525] opened 2022-04-05 13:04 UTC
### Describe the bug

The page endpoint are a great way to reduce coding. But the headers sent seem not to be set correctly.

When a page is loaded the first time from the server, the endpoint seems to be called twice:
```
headers {}
headers {
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
  'accept-language': 'de,de-DE;q=0.8,en-US;q=0.5,en;q=0.3',
  'content-length': '0',
  host: 'localhost:3000',
  origin: 'https://localhost:3000',
  referer: 'https://localhost:3000/',
  'upgrade-insecure-requests': '1'
}
```

Every additional navigation (SPA mode) to the page results in:
```
headers {
  accept: '*/*',
  'accept-language': 'de,de-DE;q=0.8,en-US;q=0.5,en;q=0.3',
  'content-length': '0',
  host: 'localhost:3000',
  origin: 'https://localhost:3000',
  referer: 'https://localhost:3000/',
  'x-sveltekit-load': 'true'
}
```

1. Why are the headers different? Shouldn't they be the same (from a developer point of view)?

2. Why does SvelteKit send accept: `'text/html...` or `accept: '*/*'` instead of `accept: 'application/json'`, when 
```Body returned from endpoint request handler must be a plain object```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-sr9wef?file=src%2Froutes%2Findex.svelte&terminal=dev

### System Info

```shell
Latest https://stackblitz.com
```

### Severity

annoyance

**Comment by Rich-Harris** [comment] 2022-04-06 17:05
Is the endpoint called twice if you run the project locally? I can't reproduce that part outside StackBlitz.

When you hit a page directly, the headers are forwarded to the endpoint — it's not SvelteKit that's setting them, it's your browser. When you hit it during client-side navigation, it's making a `fetch` call, which I think has `accept: */*` by default (again, we're not setting any headers directly except `x-sveltekit-load`). We _could_ make it `application/json` but I'm not sure it really makes any difference (since the forwarded headers are loosey-goosey anyway), unless there's a reason to rethink this?

**Comment by bluepuma77** [comment] 2022-04-07 21:26
I want to use the headers to check if the call is from Svelte or the browser post-ing a form.

If I "progressively enhance a form that already works without JS" ([SvelteKit template](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/src/lib/form.ts)) I need to determine if the call is from the Svelte code expecting JSON or if I just send a 302 redirect for the browser to fetch the object after saving.

Why would SvelteKit forward the header of the browser if the consumer of the data is SvelteKit. Why would Svelte send `*/*` if the consumer is Svelte? To me it seems Svelte always expects JSON and will throw an error otherwise:
```
Body returned from endpoint request handler must be a plain object
```

**Comment by mrkishi** [comment] 2022-04-07 22:47
To me, it'd make sense for client-side fetches to page endpoints to include `accept: application/json`.

Is the header-forwarding mechanism the same as `load`'s ssr `fetch`? Because I'm not convinced we should automatically forward _almost_ everything. It's a bit [surprising](https://github.com/sveltejs/kit/issues/4431), so perhaps there's a sane way to make it explicit?

**Comment by Rich-Harris** [comment] 2022-08-25 21:14
I think this issue has been obsoleted by #5748 (and if not, will be by #5875), so I'll close it.

For reference, the easiest way to distinguish native form submissions from `fetch` ones is the `sec-fetch-dest` header, which will be `document` in the native case and `empty` otherwise

**Closed by Rich-Harris** 2022-08-25 21:14 UTC
Labels: bug, p1-important, breaking change, low hanging fruit
