### ISSUE TITLE
Animated page transitions break snapshotting

### ISSUE THREAD

**Issue by robertadamsonsmith** [sveltejs/kit#10224] opened 2023-06-22 23:38 UTC
### Describe the bug

Animated page transitions, cause the `capture()` callback in exported snapshot handlers to not always be called correctly, resulting in unexpected behaviour.

The behaviour can be seen here, with instructions:

https://www.sveltelab.dev/md7wsue2ps2nkfm

The transition is already local (to rule out global transition related issues). If the page transition is removed then snapshots work correctly again. Snapshots are also fine when navigating to external urls. 

Oddly, it appears that if the value that is snapshotted isn't altered, then `capture()` is called when changing pages, but if the value that is snapshotted _is_ altered, then `capture()` is _not_ called (apart from for the first time).

### Reproduction

https://www.sveltelab.dev/md7wsue2ps2nkfm

### System Info

```Shell
Sveltelab repro, currently on "@sveltejs/kit": "^1.5.0",
```

### Severity

serious, but I can work around it

**Comment by robertadamsonsmith** [comment] 2023-06-23 11:29
When snapshotting fails, it is because `components[1]` in `@sveltejs/kit/src/runtime/client/client.js` is unexpectedly `null`.

That happens the moment that any reactive value on the `+page.svelte` is altered (it doesn't have to be the value being snapshotted).

Modifying any reactive value on `+page.svelte` causes `make_dirty()` to be called which ultimately sets `components[1] = null` through the following call:

`make_dirty()` -> `schedule_update()` -> `flush()` -> `binding_callbacks.pop()` -> `components[1] = $$value` (where $$value is null)

If the page transition is removed, then `binding_callbacks` is instead a 0 length array at this point, and so `components[1]` are happily unaltered.

I don't follow the logic of how `binding_callbacks` work exactly. Is it correct that the anonymous callback added to `binding_callbacks` via `switch_instance_binding()` is nulling `components[1]` rather than setting a reference to the `+page.svelte` instance?

I hope this identifies the problem sufficiently well, for the fix to clearer to somebody else!

(By the way, and this bug aside, the new snapshot stuff is great!)

**Comment by Nicicalu** [comment] 2024-01-27 00:07
Yep, same issue here

**Comment by eltigerchino** [comment] 2024-11-25 06:37
Closing this as I cannot reproduce this on the latest version of Svelte and SvelteKit

**Closed by eltigerchino** 2024-11-25 06:37 UTC
