### ISSUE TITLE
Lib file only used on API endpoints causes and error on client

### ISSUE THREAD

**Issue by vbersier** [sveltejs/kit#5313] opened 2022-06-29 14:16 UTC
### Describe the bug

I have a file `src/lib/db.ts` to handle the database connection to MongoDB for my API endpoints.

When visiting the pages of the same project (that do not even call the API), I get an error related to MongoDB, even when none of my client-side stuff uses MongoDB.

Please note that **the page completely stops working after that**, it completely crashes.
No error is shown on the server side.

### Reproduction

Create the following file in `src/lib/db.ts` (inspired by Next.js):

```typescript
import { MongoClient, type MongoClientOptions } from 'mongodb'
import { dev } from '$app/env'

const uri = 'mongodb://localhost:27017'

const options: MongoClientOptions = {
	directConnection: true,
	tls: false
}

let client: MongoClient
let clientPromise: Promise<MongoClient>

declare global {
	var _mongoClientPromise: Promise<MongoClient>
}

if (dev) {
	// In development mode, use a global variable so that the value
	// is preserved across module reloads caused by HMR (Hot Module Replacement).
	if (!global._mongoClientPromise) {
		client = new MongoClient(uri, options)
		global._mongoClientPromise = client.connect()
	}
	clientPromise = global._mongoClientPromise
} else {
	// In production mode, it's best to not use a global variable.
	client = new MongoClient(uri, options)
	clientPromise = client.connect()
}

// Export a module-scoped MongoClient promise. By doing this in a
// separate module, the client can be shared across functions.
export default clientPromise
```

Then open any client-facing page, and witness the error (in the browser console) shown below.

### Logs

```shell
promise_provider.ts:41 Uncaught ReferenceError: global is not defined
    at node_modules/.pnpm/mongodb@4.7.0/node_modules/mongodb/lib/promise_provider.js (promise_provider.ts:41:21)
    at __require2 (chunk-OROXOI2D.js?v=d7045450:16:50)
    at node_modules/.pnpm/mongodb@4.7.0/node_modules/mongodb/lib/utils.js (utils.ts:28:1)
    at __require2 (chunk-OROXOI2D.js?v=d7045450:16:50)
    at node_modules/.pnpm/mongodb@4.7.0/node_modules/mongodb/lib/operations/add_user.js (add_user.ts:8:1)
    at __require2 (chunk-OROXOI2D.js?v=d7045450:16:50)
    at node_modules/.pnpm/mongodb@4.7.0/node_modules/mongodb/lib/admin.js (admin.ts:3:1)
    at __require2 (chunk-OROXOI2D.js?v=d7045450:16:50)
    at node_modules/.pnpm/mongodb@4.7.0/node_modules/mongodb/lib/index.js (index.ts:1:1)
    at __require2 (chunk-OROXOI2D.js?v=d7045450:16:50)
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 21.56 GB / 24.85 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.local/share/pnpm/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.52 
    @sveltejs/adapter-node: 1.0.0-next.78 => 1.0.0-next.78 
    @sveltejs/kit: next => 1.0.0-next.355 
    svelte: ^3.44.0 => 3.48.0 
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I am really wondering why the mongodb dev dependency is even included in the client bundle, when absolutely no part of the client uses it.

Please note that when I build the project and preview it (with the `preview` command), I get a different error on the client (browser):

```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at start-4b4a13ca.js:16:112230
```

**Comment by Rich-Harris** [comment] 2022-06-29 21:12
Works fine for me if I create that file (as I'd expect). Presumably some client-facing module or component is importing `$lib/db`. Please create an _actual_ reproduction, [per the instructions in the issue template](https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml)

**Comment by beeb** [comment] 2022-06-30 04:54
> Works fine for me if I create that file (as I'd expect). Presumably some client-facing module or component is importing `$lib/db`. Please create an _actual_ reproduction, [per the instructions in the issue template](https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml)

Yep that was my plan today, I didn't have time to create a blank project yesterday. I'll have to add my stuff into it until I repro.

**Comment by beeb** [comment] 2022-06-30 05:36
Ok I found the culprit. Since I'm using `ObjectId` from MongoDB in a custom matcher for the routes (in `src/params`) (because my API takes those as parameters) it gets imported on the client.

Here is `src/params/objectid.ts` which allows the reproduction:

```
import type { ParamMatcher } from '@sveltejs/kit'
import { ObjectId } from 'mongodb'

export const match: ParamMatcher = (param: any) => {
	return ObjectId.isValid(param)
}
```

I guess I could re-implement ObjectId or write the matcher in a way that it doesn't need to import MongoDB?

**Comment by beeb** [comment] 2022-06-30 05:46
Here is an implementation that matches the BSON one:

```
import type { ParamMatcher } from '@sveltejs/kit'

const checkForHexRegExp = new RegExp('^[0-9a-fA-F]{24}$')

export const match: ParamMatcher = (param: string) => {
	if (param.length !== 12 && param.length !== 24) {
		return false
	} else if (param.length === 12) {
		const bytes = Buffer.from(param)
		return bytes.byteLength === 12
	}
	// length is 24
	return checkForHexRegExp.test(param)
}
```

Issue can be closed as far as I'm concerned. It kinda makes sense that anything in `params` is included in the client for routing I guess?

**Closed** 2022-06-30 05:51 UTC
Labels: awaiting submitter
