### ISSUE TITLE
Upgrading @​sveltejs/kit from 1.0.0-next.117 to 1.0.0-next.119 results in runtime error

### ISSUE THREAD

**Issue by patrickleet** [sveltejs/kit#1809] opened 2021-07-02 17:37 UTC
**Describe the bug**
Upgrading @​sveltejs/kit from 1.0.0-next.117 to 1.0.0-next.119 results in runtime error

**Logs**
Please include browser console and server logs around the time this bug occurred.

```
➜  ~ k logs -n jx-presidio-pr-18 presidio-00001-deployment-7598655467-wshls user-container
file:///usr/src/app/build/index.js:1552
  serverFetch: hooks.serverFetch || fetch
                                    ^

ReferenceError: fetch is not defined
    at get_hooks (file:///usr/src/app/build/index.js:1552:37)
    at init (file:///usr/src/app/build/index.js:1512:12)
    at file:///usr/src/app/build/index.js:1574:1
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

**To Reproduce**
Please make sure you've tested with the latest versions of Svelte and SvelteKit.

Use the node adapter - build, then start project with `node ./build/index.js`

**Expected behavior**
Node adapter still works

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

file:///usr/src/app/build/index.js:1552
  serverFetch: hooks.serverFetch || fetch
                                    ^

ReferenceError: fetch is not defined
    at get_hooks (file:///usr/src/app/build/index.js:1552:37)
    at init (file:///usr/src/app/build/index.js:1512:12)
    at file:///usr/src/app/build/index.js:1574:1
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

npx envinfo --system --npmPackages svelte,@sveltejs/kit,@sveltejs/adapter-node,@sveltejs/adapter-static,@sveltejs/adapter-begin,@sveltejs/adapter-netlify,@sveltejs/adapter-vercel vite --binaries --browsers

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 7.78 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 82.0.2
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.27 => 1.0.0-next.27 
    @sveltejs/kit: 1.0.0-next.119 => 1.0.0-next.117 
    svelte: 3.38.3 => 3.38.3 
</details>

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

Blocking upgrade - just wanted to point it out as my CI tells me every minor version change if things are still working

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by GrygrFlzr** [comment] 2021-07-02 17:42
Duplicate of #1784

**Closed** 2021-07-02 17:42 UTC

**Comment by patrickleet** [comment] 2021-07-02 17:45
ah, duplicate - thanks!
