### ISSUE TITLE
Send startup data from custom server to handler

### ISSUE THREAD

**Issue by sujai1009** [sveltejs/kit#13115] opened 2024-12-06 15:38 UTC
### Describe the problem

I want to connect to keyserver to fetch keys for the application. If not, then server should not start. Once success i need to save to session/state of svelte. So i tried using custom server node adapter to fetch the keys, now my problem is add it to request header in hooks.server.ts, which i cannot. So how to transmit data inbetween custom server(server.js) and sveltekit(with hooks or store)

### Describe the proposed solution

Provide a method in "handler" for custom server and what data passed should be accessible in hooks/server.ts file as env variable.

### Importance

nice to have

**Comment by eltigerchino** [comment] 2024-12-10 04:26
closing as duplicate of https://github.com/sveltejs/kit/issues/6183

**Closed by eltigerchino** 2024-12-10 04:26 UTC
