### ISSUE TITLE
Specific route stops working when deployed

### ISSUE THREAD

**Issue by koryphaee** [sveltejs/kit#12514] opened 2024-07-28 13:39 UTC
### Describe the bug

I have 3 routes in my app:
* `/routes/charts/+page.svelte`
* `routes//favorites/+page.svelte`
* `/routes/[mode]/+page.svelte`

Using the vite dev server everything works as expected. Both `/charts` and `/favorites` lead to their specific pages and everything else is captured by the slug `[mode]`.

However, when deploying the frontend (using ASP.NET Core in this example) the `/charts` stops working. Its now also captured by the slug, leading to the wrong page.

### Reproduction

I have created repo with a minimal reproducible example here: https://github.com/koryphaee/SvelteBug. It should be very easy to reproduce: just clone and run `docker compose up`.

### System Info

```Shell
I made sure that everything is up-to-date:

System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 AMD Ryzen 7 5800X3D 8-Core Processor
  Memory: 45.22 GB / 63.91 GB
Binaries:
  Node: 21.0.0 - c:\programs\nodejs\node.EXE
  npm: 10.2.0 - c:\programs\nodejs\npm.CMD
Browsers:
  Edge: Chromium (127.0.2651.74)
  Internet Explorer: 11.0.22621.3527
npmPackages:
  @sveltejs/adapter-static: ^3.0.2 => 3.0.2
  @sveltejs/kit: ^2.5.18 => 2.5.18
  @sveltejs/vite-plugin-svelte: ^3.1.1 => 3.1.1
  svelte: ^4.2.18 => 4.2.18
  vite: ^5.3.5 => 5.3.5
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-10-26 07:35
closing as duplicate of https://github.com/sveltejs/kit/issues/12739 . See https://github.com/sveltejs/kit/issues/12739#issuecomment-2425524871 for a workaround using a matcher to specifically exclude the other routes in the dynamic route.

**Closed by eltigerchino** 2024-10-26 07:35 UTC
