### ISSUE TITLE
`load`'s `fetch` for `+server.ts`

### ISSUE THREAD

**Issue by AaronFlynn1989** [sveltejs/kit#6730] opened 2022-09-11 08:06 UTC
### Describe the problem

I have registered a `handleFetch` hook that does something very similar to the [example in the docs](https://kit.svelte.dev/docs/hooks#server-hooks-handlefetch), namely it replaces the public domain of the API with an internal URL.

Now, in my `+.server.ts` RequestHandler functions, sometimes I find myself needing a `fetch` with the same behavior as the [load fetch](https://kit.svelte.dev/docs/load#input-methods-fetch) that runs on the server, I want it to basically pass the cookies through if applicable, and also go through the `handleFetch` hook.

### Describe the proposed solution

It would be nice if you exposed the server-side version of load `fetch` through either the input params of RequestHandler or as an import:
```ts
export const GET: RequestHandler = async ({ fetch }) => {
   const res = await fetch('...');
};
```
or maybe like:
```ts
import { severFetch } from '@sveltejs/kit'; // I'm not sure about the source of the import...
export const GET: RequestHandler = async (event) => {
    const res = await severFetch(event)('...');
};
```

### Alternatives considered

The alternative currently would be to do those things manually. But that's kind of a bummer considering the fact that SvelteKit has already implemented that so we shouldn't have to.

### Importance

would make my life easier

**Comment by Conduitry** [comment] 2022-09-11 11:55
Almost a duplicate of #6320, although that is for `+page.server.js`, not `+server.js`. I'm still going to close this in favor of that, and will comment over there and this, because they would presumably be addressed at the same time.

**Closed by Conduitry** 2022-09-11 11:55 UTC
