### ISSUE TITLE
Add info `Port 3000 is occupied` for `npm run dev`

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/kit#2789] opened 2021-11-12 20:18 UTC
### Describe the problem

If you run the default `npm run dev` without specifying a specific port (-p), you will get the following error, if the port is already in use:
```
> listen EACCES: permission denied 127.0.0.1:3000
Error: listen EACCES: permission denied 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (node:net:1317:21)
    at listenInCluster (node:net:1382:12)
    at doListen (node:net:1520:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

If you run `npm run preview` and the port is already in use, you will get a more beginner friendly error message:
```
Port 3000 is occupied
Terminate the process occupying the port or specify a different port with --port
```

### Describe the proposed solution

Unify the error message. If a port is already in use, provide the same error message.

### Importance

nice to have

**Comment by benmccann** [comment] 2021-11-23 17:52
What OS are you running?

**Comment by Zerotask** [comment] 2021-11-23 19:49
Windows 10

**Comment by Conduitry** [comment] 2021-11-23 19:59
FWIW, I can't reproduce this. I tried this on Windows 10 earlier today (with both Node 14 and Node 16) and running `npm run dev` simultaneously in two different projects, and the second one displayed the more friendly error, and not the `EACCES` mentioned in the issue.

**Comment by Zerotask** [comment] 2021-11-23 20:38
I just tried to reproduce this right after I started my PC.

on the first run of `npm run dev` it started without problems (port was not occupied). Then after it was running, I started the command again (with the same project and another project) and got the user-friendly error message and not EACESS.

Then I stopped it and started an express web server on port 3000 and after it, I started `npm run dev`. The Vite dev server started without problems, but it can't be accessed. I got 404 from express. I tried the same with a Go (gin) web server and it was the same.
The expected behavior would be to see the user-friendly error message in this case.
Besides that, I could not reproduce the EACESS error. My Svelte, Node, NPM etc. versions were the same as from this test https://github.com/sveltejs/kit/pull/2792#issuecomment-968368935

The only difference was, that I left the Windows Insider Program (Release Preview Channel) a few days ago. But I can't imagine that this was the cause.

**Comment by bluwy** [comment] 2021-11-25 18:17
Thanks for the thorough investigation @Zerotask! Since the bug is in Vite, I'll close this in favour of https://github.com/vitejs/vite/issues/5801, which seems to be having similar issues. Your comment there would help too, and it seems like a workaround is also found there.

**Closed by bluwy** 2021-11-25 18:17 UTC
Labels: vite
