### ISSUE TITLE
Change the build script for the skeletonlib template to package and stick to `vite build` for the build one

### ISSUE THREAD

**Issue by paoloricciuti** [sveltejs/kit#8373] opened 2023-01-06 19:32 UTC
### Describe the problem

From discord seems that a lot of people wrongly select the skeleton lib template from create-svelte. Running the dev server does not "warn" you about the fact that you are actually in "package mode". This lead to confusion when they try to deploy because the build script that usually gets invoked from the various hosting services produce a package folder instead of a built website.

### Describe the proposed solution

Change the current build script to be package and maintain the build in sync with the other templates, so basically

```diff
- "build": "svelte-kit sync && sveltepackage",
+ "package": "svelte-kit sync && sveltepackage",
+ "build": "vite build",
```

### Alternatives considered

To avoid "breaking changes" we could keep the build the same but at least specify another script to build the web app.

```diff
+ "build:webapp": "vite build",
```

### Importance

nice to have

### Additional Information

I can obviously take care of this myself...I just wanted a feedback from the maintainers.

**Comment by Rich-Harris** [comment] 2023-01-06 19:37
closing as dupe of #8240

**Closed by Rich-Harris** 2023-01-06 19:37 UTC

**Comment by paoloricciuti** [comment] 2023-01-06 20:09
Ops, sorry for the litter...I can never seem to find anything in the issue search. Sorry again.
