### ISSUE TITLE
build single js file and single css file like Svelte does.

### ISSUE THREAD

**Issue by kauaicreative** [sveltejs/kit#3882] opened 2022-02-13 02:26 UTC
### Describe the problem

Is there an option or an adaptor that will build the app as svelte does - with a single js file and single css file? 

### Describe the proposed solution

This makes embedding into wordpress much simpler.

### Alternatives considered

I am using the `adapter from '@sveltejs/adapter-static'` but this builds each component into many individual js and css files.
Also tried the wordpress adapter. It is not compatible with the latest version of Svelte Kit. And I do not believe it will create a single js file and single css file.

### Importance

i cannot use SvelteKit without it

**Comment by benmccann** [comment] 2022-02-13 03:40
You may be interested in the `inlineStyleThreshold` option: https://kit.svelte.dev/docs/configuration#inlinestylethreshold

The name is based on the file contents. This allows the file to be cached. Can you explain more about why you would want to link to these files?

**Comment by kauaicreative** [comment] 2022-02-13 03:52
Thanks for the idea but I don't think it will work in this case.

I have several svelte apps which I am dynamically inserting into wordpress content via shortcodes. In wordpress/php I `wp_register_script()` and `wp_enqueue_script()` to add the css and js assets to the wordpress page render process. These filenames can not change. I then insert the svelte startup markup into the content. e.g. svelte: `<div id="app"></div>` , or sveltekit: `start({...})`

**Comment by kauaicreative** [comment] 2022-02-13 04:22
Wondering if I should be looking at component packaging instead https://github.com/sveltejs/kit/pull/1499

**Comment by gevera** [comment] 2022-07-12 17:45
Encountered same need, we are transitioning from a React SPA. Hopefully this will get some love

**Comment by cubic3d** [comment] 2022-08-12 11:40
@gevera looks like you can use vite config to influence file names: https://github.com/sveltejs/vite-plugin-svelte/issues/375#issuecomment-1156609925

**Comment by paolodina** [comment] 2023-01-07 03:57
@cubic3d 

I tried and doesn't work.

```text
The following Vite config options will be overridden by SvelteKit:
  - build.rollupOptions.output.entryFileNames
  - build.rollupOptions.output.chunkFileNames
  - build.rollupOptions.output.assetFileNames
```

**Comment by edwinspire** [comment] 2023-01-07 16:21
I have the same problem with the latest version of Svelte.

**Comment by d-velopment** [comment] 2023-01-26 21:31
While there's no solution or adapter itself hasn't been improved, I've created the "hacky" way of re-wrapping the project files to the bundle.js: https://github.com/d-velopment/SvelteKit-One-Bundle 

It's not solving the problem of thousand chunks but gives the **bundle.js** to be loaded from a custom index.html or another project to render the application.

**Comment by wozzashek** [comment] 2023-04-17 18:47
My use case is for an enterprise platform. In truth I don't need all the JS to be in a single file. Rather I need all the JS to be built to the /dist folder, no JS or CSS in subfolders. 

So the enterprise platform I use allows me to serve a single html page at an endpoint with all JS & CSS file requests coming from that endpoint e.g.

Index html: platform.com/webapp/my_app
All JS/CSS files: platform.com/webapp/my_app/{filename}

Although that forces me to use hashed routing as well which I guess I'll have to implement myself unless Sveltekit has one I can turn on.

**Comment by khromov** [comment] 2023-04-17 19:38
@benmccann I'm making a [Capacitor](https://capacitorjs.com/) application for iOS/Android. Capacitor works by starting a local web server and then serving your application like a static host on your phone. This local server does not have SSL or HTTP/2, so while some requests load in parallel, it takes quite a while to load 50+ resources over HTTP/1. It's hard to measure raw numbers but in our project it takes around ~1 second for loading up the app until interactable and about half that on our PWA version. So it takes twice as long to load a local application on your phone than going to servers in a different country.

**Comment by ChristianSch** [comment] 2023-04-18 14:14
This is also a common problem highlighted by SEO tools. 'reduce number of css files'. Would be good to be able to combine them.

**Comment by anakinjay** [comment] 2023-04-25 15:57
I have this need for importing components into other systems like wordpress or drupal.  

In react, we've always handled this by reading the assets manifest.json file from webpack to figure out which file names we need to load, which vite DOES support under the options build.manifest, but when I try and enable that settings I get the error:

```
The following Vite config options will be overridden by SvelteKit:
  - build.manifest
```

**Comment by mdocter** [comment] 2023-05-13 13:13
Like @wozzashek mentioned, I also work with an enterprise system, Microsoft Dynamics/Power Platform. 

1. In their case Microsoft prepends a cache busting version value (=hash/guid) in front of my web files in the url path. So a hash in de filename is unnecessary.

<Microsoft Dynamics URL>/%7B<version value>%7D/WebResources/index.html

2. Those web resources are part of a solution zip file which is used to deploy and redeploy updates. So I want to have the same file names, otherwise my solution grows and grows with each build being added. 

I tried all suggestions to disable the [hash] in the file names, but nothing works. Having multiple chunks is not a problem in my use case, as long as they have the same file names. 

Any suggestions on how to disable the hash in the file names?

**Comment by tystol** [comment] 2023-06-09 04:27
My use case is for packaging up an admin front-end UI within a back-end library. The devs consuming the library will ultimately choose which paths the UI will be served under, and it needs to be dynamic at runtime.
eg. The Hangfire dashboard UI (not my project, but a close analogy to what I need to do):
https://docs.hangfire.io/en/latest/configuration/using-dashboard.html
Note the end of the article, I'd like to support things like this too:

> [Multiple Dashboards](https://docs.hangfire.io/en/latest/configuration/using-dashboard.html#toc-entry-6)[¶](https://docs.hangfire.io/en/latest/configuration/using-dashboard.html#multiple-dashboards)
> You can also map multiple dashboards that show information about different storages.
> 
> var storage1 = new SqlServerStorage("Connection1");
> var storage2 = new SqlServerStorage("Connection2");
> 
> app.UseHangfireDashboard("/hangfire1", new DashboardOptions(), storage1);
> app.UseHangfireDashboard("/hangfire2", new DashboardOptions(), storage2);

**Comment by captainhusaynpenguin** [comment] 2023-07-25 17:31
My most obvious usecase is developing a CSS framework and using SvelteKit as a wrapper for documentations and also partially custom implementation of the CSS style for one off svelte components.

So, such a feature would be extremely, extremely appreciated;

PS. Stuff like these seemed to be the focus/concern of the dev team at some point in time? see: [Svelte.Dev Blog CSS-in-JS](https://svelte.dev/blog/svelte-css-in-js)

**Comment by mdocter** [comment] 2023-07-25 17:51
@benmccann Any updates on this topic?

**Comment by migbash** [comment] 2023-07-26 11:29
We need this solution in `sveltelkit` as well, as we have a `domain` issue restriction with the amount of `Page Resources` loaded, and need to minimize the number of `resources` Goolge-Bot needs to load.

The current solution, that we have identified that works as intended for `CSS`, is to use the following setup:

```html
📌 src/app.html

[...]

<link
  rel="preload"
  href="/all-css-chunk.css"
  as="style"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="/all-css-chunk.css"
/>

[...]
```

```typescript
📌  vite.config.ts

import { defineConfig } from 'vitest/config';
import { sveltekit } from '@sveltejs/kit/vite';
import cssInjectedByJsPlugin from "vite-plugin-css-injected-by-js";
import fs from 'fs';

[...]

plugins:
[
  sveltekit(),

  // ### WARNING:
  // ### 'this' plugin removes all 'CSS' from standard
  // ### importing by 'svelte/svelteki' and styles will be missing
  // ### if not imported as a '<link ... >' in the 'src/app.html'
  cssInjectedByJsPlugin
  (
    {
      // ### NOTE:
      // ### definitive 'hack' solution for 'single CSS file' output chunk.
      injectCode:
      (
        cssCode,
        options
      ) =>
      {

        // ### NOTE:
        // ### the 'cssCode' generated contains some 'formatting' issues.
        // ### remove 1st and last speech marks.
        // ### remove cases of `\n` chars.
        // ### correct custom case of 'ids'/'classes' using the 'forward-slash' in the declaration.
        let cssCodeMod: string = cssCode.slice(1, -1);
        cssCodeMod = cssCodeMod.replace(/\\n/g, "");
        cssCodeMod = cssCodeMod.replace(/\\\\/g,"\\")

        // ### WARNING:
        // ### 'all-css-chunk.css' must exist inside '/static'
        fs.writeFile
        (
          './static/all-css-chunk.css',
          cssCodeMod,
          err =>
          {
            if (err) console.error(err);
          }
        );

        return '';            
      }

    }
  ),

[...]
```

> **Warning**
> The only issue with this that has been detected, is that the `<style>` form the `src/routes/+layout.svelte` are not present in the `all-css-chunk.css` output, but every other `<style>` is present in the `final` chunk.

**Comment by Beyondo** [comment] 2023-07-27 02:44
No single js files? This destroys SEO. The latency between requests is just too much for any clients running below 3G. Be it microcontrollers like already mentioned or just generally bad connections which happen to everyone at some point.

**Comment by edwinspire** [comment] 2023-07-27 04:17
> No single js files? This destroys SEO. The latency between requests is just too much for any clients running below 3G. Be it microcontrollers like already mentioned or just generally bad connections which happen to everyone at some point. I think I'd just use Svelte for now.

I disagree with what you expose, I have been working with microcontrollers for a long time, where the number of concurrent connections is very limited and saturates the memory to the point of restarting the device. However, when I have a single file, the operation is the most optimal.

**Comment by Beyondo** [comment] 2023-07-27 12:04
> > No single js files? This destroys SEO. The latency between requests is just too much for any clients running below 3G. Be it microcontrollers like already mentioned or just generally bad connections which happen to everyone at some point. I think I'd just use Svelte for now.
> 
> I disagree with what you expose, I have been working with microcontrollers for a long time, where the number of concurrent connections is very limited and saturates the memory to the point of restarting the device. However, when I have a single file, the operation is the most optimal.

Did you even read my comment properly? That's literally what I said.

**Comment by Beyondo** [comment] 2023-07-27 12:07
> > No single js files? This destroys SEO. The latency between requests is just too much for any clients running below 3G. Be it microcontrollers like already mentioned or just generally bad connections which happen to everyone at some point. I think I'd just use Svelte for now.
> 
> I disagree with what you expose, I have been working with microcontrollers for a long time, where the number of concurrent connections is very limited and saturates the memory to the point of restarting the device. However, when I have a single file, the operation is the most optimal.

Did you even read my comment properly? That's literally what I said. SvelteKit is bad for this kind of stuff. And you are not the only one working with microcontrollers as I've been running my own camera surveillance for years.

**Comment by khromov** [comment] 2023-07-27 12:42
> No single js files? This destroys SEO. 
This is false. In fact multiple JS files make the page appear faster because the browser has time to render things between JS files instead of rendering one huge JS chunk.

> The latency between requests is just too much for any clients running below 3G. 
This is debatable. If you analyze a waterfall diagram you'll see that most requests load in parallel. When testing my latest project on https://web.dev/measure/ I got 99/100 in performance, which is using simulated 4G slowdown. So not even Google seems to think there is any issue with the current approach.

**Comment by khromov** [comment] 2023-07-27 12:43
@Beyondo 

> No single js files? This destroys SEO. 

This is false. In fact multiple JS files make the page appear faster because the browser has time to render things between JS files instead of rendering one huge blocking JS chunk.

> The latency between requests is just too much for any clients running below 3G. 

This is debatable. If you analyze a waterfall diagram you'll see that most requests load in parallel, it's not a chain of 30 requests one after another. When testing my latest project on https://web.dev/measure/ it got 99/100 in performance, when  using simulated 4G slowdown. So Google does not seem to think there is any issue with the current approach.

**Comment by Beyondo** [comment] 2023-07-27 13:30
So you are saying that because some clients load the files in parallel, it is justifiable to literally divide the website into these horrible chunks? Your simulated slowdown is different from real-world slowdown. And I realized this is the hard way. In an actual slow network scenario, it is not merely a matter of "bandwidth throttling" as commonly emulated in our development tools and all requests just 100% succeed after only a longer time. No. **In the real world, a sluggish network means any request could be dropped at any time.**

The division of our SvelteKit website into numerous requests is a nightmarish prospect, as it poses the risk of any of these requests being dropped, which causes the site to cease functioning correctly or rendering appropriately. In my humble opinion, SvelteKit remains unsuitable for any substantial project.

**Comment by Beyondo** [comment] 2023-07-27 13:32
> @Beyondo
> 
> > No single js files? This destroys SEO.
> 
> This is false. In fact multiple JS files make the page appear faster because the browser has time to render things between JS files instead of rendering one huge blocking JS chunk.
> 
> > The latency between requests is just too much for any clients running below 3G.
> 
> This is debatable. If you analyze a waterfall diagram you'll see that most requests load in parallel, it's not a chain of 30 requests one after another. When testing my latest project on https://web.dev/measure/ it got 99/100 in performance, when using simulated 4G slowdown. So Google does not seem to think there is any issue with the current approach.

I disagree. This is not "false". You are saying that because some clients load the files in parallel or have a guaranteed connection, it is justifiable to literally divide the website into these horrible chunks? Your simulated slowdown is different from real-world slowdown. And I realized this is the hard way. In an actual slow network scenario, it is not merely a matter of "bandwidth throttling" as commonly emulated in our development tools and all requests just 100% succeed after only a longer time. No. **In the real world, a sluggish network means any request could be dropped at any time.**

The division of our SvelteKit website into numerous requests is a nightmarish prospect, as it poses the risk of any of these requests being dropped, which causes the site to cease functioning correctly or rendering appropriately. In my humble opinion, SvelteKit remains unsuitable for any substantial project.

**Comment by Beyondo** [comment] 2023-07-27 13:34
> @Beyondo
> 
> > No single js files? This destroys SEO.
> 
> This is false. In fact multiple JS files make the page appear faster because the browser has time to render things between JS files instead of rendering one huge blocking JS chunk.
> 
> > The latency between requests is just too much for any clients running below 3G.
> 
> This is debatable. If you analyze a waterfall diagram you'll see that most requests load in parallel, it's not a chain of 30 requests one after another. When testing my latest project on https://web.dev/measure/ it got 99/100 in performance, when using simulated 4G slowdown. So Google does not seem to think there is any issue with the current approach.

I disagree. This is not "false". You are saying that because some clients load the files in parallel or have a guaranteed connection, it is justifiable to literally divide the website into these horrible chunks? Your simulated slowdown is different from real-world slowdown. And I realized this is the hard way.

In an actual slow network scenario, it is not merely a matter of "bandwidth throttling" as commonly emulated in our development tools and all requests just 100% succeed after only a longer time. No. **In the real world, a sluggish network means any request could be dropped at any time.**

Dvision of our SvelteKit website into numerous requests is nightmarish, as it poses the risk of any of these requests being dropped, which causes the site to cease functioning correctly or rendering appropriately. In my humble opinion, SvelteKit remains unsuitable for many projects.

**Comment by Beyondo** [comment] 2023-07-27 13:38
> @Beyondo
> 
> > No single js files? This destroys SEO.
> 
> This is false. In fact multiple JS files make the page appear faster because the browser has time to render things between JS files instead of rendering one huge blocking JS chunk.
> 
> > The latency between requests is just too much for any clients running below 3G.
> 
> This is debatable. If you analyze a waterfall diagram you'll see that most requests load in parallel, it's not a chain of 30 requests one after another. When testing my latest project on https://web.dev/measure/ it got 99/100 in performance, when using simulated 4G slowdown. So Google does not seem to think there is any issue with the current approach.

I disagree. This is not "false". You are saying that because some clients load the files in parallel or have a guaranteed connection, it is justifiable to literally divide the website into these horrible chunks? Your simulated slowdown is different from real-world slowdown. And I realized this is the hard way.

In an actual slow network scenario, it is not merely a matter of "bandwidth throttling" as commonly emulated in our development tools and all requests just 100% succeed after only a longer time like in your Google tests. No. **In the real world, a sluggish network means any request could be dropped at any time.**

Division of our SvelteKit website into numerous requests is nightmarish, as it poses the risk of any of these requests being dropped, which causes the site to cease functioning correctly or rendering appropriately. In my humble opinion, SvelteKit remains unsuitable for many projects (or at least not favorable).

**Comment by khromov** [comment] 2023-07-27 13:42
> I disagree. This is not "false".

The "This destroys SEO." part is false. I said that the latency part (which is what your post is about) is *debatable*. 

If you are worried about poor connectivity, you can implement a service worker. Requests can always be dropped, but with HTTP/2 multiplexing, multiple requests are handled in the same stream, so the chances are reduces since you are not creating one connection per request. 

I think the problem from your argument comes from your spreading FUD ("learned the hard way", "nightmarish") as opposed to trying to have a fact-based discussion. I am in favor of being able to build just one output file, but it's not for the reasons you suggested.

**Comment by Beyondo** [comment] 2023-07-27 15:01
> > I disagree. This is not "false".
> 
> The "This destroys SEO." part is false. I said that the latency part (which is what your post is about) is _debatable_.
> 
> If you are worried about poor connectivity, you can implement a service worker. Requests can always be dropped, but with HTTP/2 multiplexing, multiple requests are handled in the same stream, so the chances are reduces since you are not creating one connection per request.
> 
> I think the problem from your argument comes from your spreading FUD ("learned the hard way", "nightmarish") as opposed to trying to have a fact-based discussion. I am in favor of being able to build just one output file, but it's not for the reasons you suggested.

Wow I'm sorry this is my typo. I meant user-experience and was talking about user-experience for the entirety of my two comments if you noticed. I didn't mean to say 'SEO' in my first comment and didn't even see it at all till you just mentioned it now. I edited it, you can check it again. I'm honestly deeply sorry for this confusion. I never claimed my opinion is a "fact-based" either but actually said it is in my humble opinion to have one output file just like you said you favor them too.

In any case, I'd like to politely note that your premise that "chunky js files" are slower is not true but is that they actually they load faster (if not the same) since not only are they streamed straightforwardly in a single request, but you can always load them asynchronously (without waiting) while showing any pretty splash-screen for a few milliseconds before your layout loads to not have any layout shift. Of course this is just a design choice, like maybe splash screens aren't you thing, but again IMHO, they're much better than plain white backgrounds waiting for tens of preloaded scripts, and it gives the illusion that your app instantly loaded. Paired with a service worker for caching & some versioning, and any new updates would force the user to redownload the scripts making your app instant and versatile.

But it's not like this is new knowledge, single output files have always been favored by almost everyone. So although we both have might have different (or maybe overlapping) uses for a single chunky output, we both give legitimate reasons nonetheless or edge cases for own specific apps; it is not like Svelte is built only for a specific set of websites, but for all kind of web apps. So I might be wrong, but do we really disagree on anything here?

**Comment by luisfontes** [comment] 2023-09-04 02:52
Sharing my use case for this feature. I'm in the process of building a Google Sheets add-on, and Google mandates that the HTML must be served from a single file with no local imports. Right now I'm using Svelte + Vite with vite-plugin-singlefile.

**Comment by 6eDesign** [comment] 2023-09-07 13:05
We use kit to build the frontend for a major tv manufacturer.  Many of our SOCs have underwhelming performance and seem to struggle to efficiently download the 200+ JS files needed to load any given endpoint.

We use the static adapter currently as much of our content is very difficult to cache and SSR at this scale (tens of millions of active devices), without caching, becomes very "expensive" in many ways.

It would be great if we could experiment-with/optimize the build output for this use case (fewer files).  If we could get help with this I'd be more than happy to share some of the the real world results.

**Comment by kewp** [comment] 2023-10-20 06:10
My use-case is like OP: I'm building both a full-page application, deployed on a separate server, and an embedded version that is inserted into Wordpress articles via shortcode. I have gotten this to work using Svelte but can't seem to figure out how to do it with Sveltekit.

**Comment by kewp** [comment] 2023-10-20 06:13
@kauaicreative did you ever solve this? I have the exact same requirement as you ...

**Comment by kewp** [comment] 2023-10-22 03:49
I've had some success (at least so far) using the shortcode adapter for my use case (for those with the same requirement) https://github.com/tomatrow/sveltekit-adapter-wordpress-shortcode

**Comment by kewp** [comment] 2023-10-22 07:28
Yup got it working - just remember to turn off all `load` methods in your `*.server.js` files else you will get weird, un-debuggable JSON load errors coming from `client.ts` (trying to read JSON from a non-accessible server call). I know this isn't a support channel, just mentioning it for others!

**Comment by GetCurious** [comment] 2023-10-24 00:54
My use case: Microsoft Dynamics 365

I want only 3 files:
**index.html**
 **index.js**
**index.css**

for now, using Svelte only

**Comment by UnexDev** [comment] 2023-11-10 00:27
Use case: Microcontroller.

**Comment by dsbaars** [comment] 2023-11-17 03:12
> In my case I am using svelte to create a web interface inside an ESP32 (microcontroller), for the microcontroller, the fewer requests it has to attend to, the better, for this reason having everything in one file is ideal, or at least the html, js and css are each in a single file.

Similar use case here, also writing a web interface for a ESP32. As it uses SPIFFS/LittleFS, the filenames also need to be shorter than 31 characters.

**Comment by AndrewPenry** [comment] 2024-01-10 18:00
My use case: The new PCI DSS 4.0 - 11.6.1 requires anyone with a payment page to monitor the page (as rendered by the client) weekly for changes, to make sure no one has modified the code. Writing synthetic user monitoring services (in Playwright or whatever) will be much easier if there are less files to compare. Note that the requirement as written prevents you from checking the integrity of your files just on the server side; it must monitor it on the client side to ensure it catches attacks injected by malicious 3rd parties.

**Comment by craigkai** [comment] 2024-01-22 16:07
> > In my case I am using svelte to create a web interface inside an ESP32 (microcontroller), for the microcontroller, the fewer requests it has to attend to, the better, for this reason having everything in one file is ideal, or at least the html, js and css are each in a single file.
> 
> Similar use case here, also writing a web interface for a ESP32. As it uses SPIFFS/LittleFS, the filenames also need to be shorter than 31 characters.

Did you ever end up figuring this out?

**Comment by dsbaars** [comment] 2024-01-22 16:35
> Did you ever end up figuring this out?

I solved this in a quite ugly way. I created a [patch](https://github.com/btclock/webui/blob/main/patches/%40sveltejs%2Bkit%2B1.27.6.patch) that's applied automatically by [patch-package](https://www.npmjs.com/package/patch-package) when doing `yarn install`.

**Comment by theelims** [comment] 2024-01-22 20:47
@craigkai My project contains a small plugin for vite to shorten the filenames: https://github.com/theelims/ESP32-sveltekit/blob/main/interface/vite-plugin-littlefs.ts which must then be included into https://github.com/theelims/ESP32-sveltekit/blob/main/interface/vite.config.ts

**Comment by flo-at** [comment] 2024-02-14 00:08
Our use case: SPA that acts as the GUI to our software. SEO isn't a concern here at all. It works fine with many small files. But I'd prefer a longer initial loading time (for the bundles) and snappier navigation (fewer requests) over the current situation.

The websever serves precompressed files (br and gz) and large/merged files typically have a lot better compression ratio than small ones.

Ideally we could get this:
```
index.html
bundle.[hash].js
bundle.[hash].css
favicon.png
...
```

I'm overall pretty happy with Svelte(Kit). Thanks a lot for the awesome work!

**Comment by katriellucas** [comment] 2024-02-19 02:04
Adding to the comment above: https://csswizardry.com/2023/10/the-three-c-concatenate-compress-cache/

This article explains how **one file** is _sometimes_ better than a **many files** setup, which is due to how compression works by comparing the file against itself. A big file has more "historical data" to use and ends up finding way more repetitions thus compressing better.

**Comment by timoanttila** [comment] 2024-03-24 16:45
My use case for this would be admin area inside ProcessWire CMS. I want to import SvelteKit app with multiple pages to one PHP page. I have tried copying all the scripts and divs from the `build` folder's `index.html` and using `iframe`. It would be perfect if there would be only one JS and CSS file.

I want this to be fully client side because some of the information is dynamic and need to be fetched from backend after checking who user is and what rights (s)he has.

```JavaScript
import adapter from '@sveltejs/adapter-static'
const vitePreprocess = import('@sveltejs/vite-plugin-svelte').then(m => m.vitePreprocess())

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: {
    script: async options => (await vitePreprocess).script(options),
    style: async options => (await vitePreprocess).style(options)
  },
  kit: {
    adapter: adapter({
      fallback: 'index.html'
    }),
    prerender: {
      crawl: false,
      entries: []
    },
    alias: {src: './src'}
  }
}

export default config
```

I have used Vue before but I would really want to change to SvelteKit since it is much simpler and my frontend is made with it.

**Comment by DougAnderson444** [comment] 2024-03-25 21:47
I'd like to use [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) on the Svelte app code, so I need one file in order to hash it all and provide the integrity-hash on that one script.

**Comment by gregg-cbs** [comment] 2024-04-19 09:11
Im not looking for a single file but im looking for less files. On my home page which does not have much i am seeing 75 js file requests. Some are 500bytes. I would like to be able to group components/imports/files into chunks so there arent all these bitty requests.

The issue I see is that my burger menu code is being loaded last and so the burger menu does not have any functionality until the whole page is completely loaded -  on a slow network this is a horrible experience. If i could optimize this by grouping the burger menu code with other code/components into 1 file then my problem is alleviated.

Webpack has this functionality with their chunkName:
`import( /* webpackChunkName: "login" */ '../views/LoginView.vue'),`

**Comment by khromov** [comment] 2024-08-16 23:54
After discussion with a couple core maintainers, there are two solutions that can be used today to reduce the number of built JS bundles:

### Option 1: Configure experimentalMinChunkSize

This is an [Experimental Vite option](https://rollupjs.org/configuration-options/#output-experimentalminchunksize) that does some smart optimisation of joining multiple chunks together. This will cause a slight overlap in chunks (so some code might be loaded that isn't used for certain routes), but it seems to bring down the number of JS files loaded by ~30% (so for example, from 30 loaded JS files to 20).

A `vite.config.ts` example:

```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';

export default defineConfig({
	plugins: [sveltekit(),],
	test: { include: ['src/**/*.{test,spec}.{js,ts}']},
	build: {
		rollupOptions: {
			output: {
				experimentalMinChunkSize: 50000, // add this
			}
		}
	}
});
```

### Option 2: Configure manualChunks

Configuring [manualChunks](https://rollupjs.org/configuration-options/#output-manualchunks) is the best option to reduce the number of JS files. It can reduce the total number of files down to approximately 3 JS files. To set this option:

```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';

export default defineConfig({
	plugins: [sveltekit(),],
	test: { include: ['src/**/*.{test,spec}.{js,ts}']},
	build: {
		rollupOptions: {
			output: {
				manualChunks: (id) => {
					return 'my-app';
				}
			}
		}
	}
});

While this does not bring the number of built files to just one, it does fix a lot of the mentioned cases above where you have many dozens or even 100+ JS files being loaded for a single page load, or you are working in a constrained environment.

**Comment by ImXirvin** [comment] 2024-08-20 13:49
Does anyone have any solutions for this yet?

**Comment by gregg-cbs** [comment] 2024-09-06 10:31
Yeah so i did manual chunking @ImXirvin and I got performance improvements so i can recommend.

vite.config.ts
```ts
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';

// the chunks you want to group - common things around your site
const group_chunks = [
  "src/constants.ts",
  
  "src/lib/utils/util_fetch.ts",
  "src/lib/utils/util_date_get_time.ts",
  "src/lib/utils/util_price_to_rands.ts",
  "src/lib/utils/util_date_to_friendly_date.ts",
  
  "flowbite-svelte/dist/typography/A.svelte", // node package
  "flowbite-svelte/dist/typography/Button.svelte",
  "flowbite-svelte/dist/toast/Toast.svelte",
  
  "svelte-hero-icons/dist/Icon.svelte",
  
  "src/lib/components/metadata.svelte",
  "src/lib/components/logo.svelte",
  "src/lib/components/form/input.svelte",
  "src/lib/components/form/field.svelte",
  "src/lib/components/header/header.svelte",
  "src/lib/components/header/headerNavbar.svelte",
  "src/lib/components/general/loader.svelte",
]

export default defineConfig({
  plugins: [sveltekit()],
  test: {
    include: ['src/**/*.{test,spec}.{js,ts}']
  },
  server: {
    host: true
  },
  resolve: {
    alias: {
      '$types': "../types"
    }
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          const is_group_chunk = group_chunks.some(partialPath => id.includes(partialPath));
          
          if (is_group_chunk) {
            return "general" // the chunk name they will be grouped under
          }
        },
      },
    },
  },
});

```

**Comment by kran6a** [comment] 2024-09-07 01:14
I build svelte-based widgets. Currently they are tiny (~20kb - 100kb) self-contained svelte apps. They include their own css, fonts, images, svgs and js and are then bundled to a single js file using an internal tool I hacked together. Those widgets are then stored on a database along with their configuration/theming metadata so they are available for the end users.

I would like to be able to use sveltekit + adapter static to build them mainly to benefit from svelte-kit routing and layout system. Maybe we should have an official "adapter-component" which outputs either a single .js file file ready to be mounted on any DOM node or a .js file and a .css file.

**Comment by khromov** [comment] 2024-09-07 05:13
@kran6a We already have this, it's the Vite Svelte preset.

SvelteKit can't be mounted in a DOM node, as it needs to take over routing for the whole page.

Where I work we've had success using Kit for widgets by using iframes and Pym.js to handle the resizing.

**Comment by kran6a** [comment] 2024-09-07 07:44
> @kran6a We already have this, it's the Vite Svelte preset.
> 
> SvelteKit can't be mounted in a DOM node, as it needs to take over routing for the whole page.
> 
> Where I work we've had success using Kit for widgets by using iframes and Pym.js to handle the resizing. 

The default preset does not inline fonts and images in CSS as base64 data urls nor does it inline CSS into JS. Svgs also have their own inlining process since it is possible to inline them without base64 encoding, resulting in a few less bytes per svg.

**Comment by benmccann** [comment] 2024-10-28 22:43
Leaving some notes for when we hopefully come back to this before too long. Here's an old branch I found for this: https://github.com/sveltejs/kit/tree/iife

The main reason we hadn't moved forward with it was trying to nail down the API. I ended up with only a single option. I'm not sure that JS and CSS are separately controllable. We get the JS and CSS out of the client manifest: https://github.com/sveltejs/kit/blob/58fca9138d7f16c9b754c47053b3d20ee8239a73/packages/kit/src/exports/vite/build/build_server.js#L51 If there's only a single JS entry in the client manifest then there's only a single CSS entry in the client manifest as well I believe and so I don't think you could turn off code-splitting for JS, but leave it enabled for CSS.

**Closed** 2024-12-19 16:00 UTC
Labels: feature / enhancement

**Comment by flashblocks** [comment] 2024-12-19 17:13
What is the solution? Is this completed? Thank.

**Comment by brunnerh** [comment] 2024-12-19 17:17
There is a bundle strategy option now, see [release notes](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%402.13.0):

> - feat: add `bundleStrategy: 'split' | 'single'` option (https://github.com/sveltejs/kit/pull/13173)

**Comment by Rich-Harris** [comment] 2024-12-19 17:18
Yep — add [`output.bundleStrategy: 'single'`](https://svelte.dev/docs/kit/configuration#output) to your `svelte.config.js`:

```diff
import adapter from '@sveltejs/adapter-auto';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),

+   output: {
+     bundleStrategy: 'single'
+   }
  }
};

export default config;
```

**Comment by ligazetom** [comment] 2025-02-18 09:49
Based on the documentation 

> If 'single', creates just one .js bundle and one .css file containing code for the entire app.

I would expect there to be only one `css` file. I have one bundle `.js` file, but along with bundle `.css` file I also have `.css` files per page and layouts. Is that how it's supposed to behave? I'm prerendering without SSR and I don't really mind, just wondering if it's valid behavior.

I can see the same class definitions that are in page/layout files defined in the bundled `.css` so it just seems a bit redundant to me. If it's valid, can someone please explain why it's needed?
