### ISSUE TITLE
+server.ts API endpoint fails to parse body

### ISSUE THREAD

**Issue by callmeberzerker** [sveltejs/kit#7409] opened 2022-10-27 18:23 UTC
### Describe the bug

The only file new file in the blank svelte-kit project is the `+server.ts` located in `src/routes/api/+server.ts`. It just echoes the incoming JSON. Hitting `http://localhost:5173/api` (with `content-type` and `accept` headers set to `application/json` and body `{ "sample": "test"}` ) will return `HTTP 400 Bad request` -> and the request never hits the API endpoint.

If I remove the content-type and accept headers it will enter the API endpoint but it would error out on `await request.json()` with:

```
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
```

It might be a Windows issue but honestly I am not sure and can't test atm.

### Reproduction

https://github.com/callmeberzerker/body-not-working

Run `pnpm install` and then `pnpm dev`.

### Logs

```Shell
Sadly there are none.
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 16.30 GB / 31.92 GB
  Binaries:
    Node: 19.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.674.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^3.2.0 => 3.2.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

N/A

**Comment by georgdonner** [comment] 2022-10-27 18:39
I ran into the exact same issue today setting up a new Sveltekit project and am on MacOS, so it's probably not a Windows issue. It might be related to #5370, because I am seeing the same error "Invalid request body"

**Comment by Rich-Harris** [comment] 2022-10-27 18:42
Oddly, I can reproduce this by cloning the repo, but as soon as I add a pnpm override to start debugging it, it works... a true Heisenbug 🤔

**Comment by callmeberzerker** [comment] 2022-10-27 18:43
Thanks for the response - I almost went crazy trying out different things for this seemingly straight-forward thing!

**Comment by Conduitry** [comment] 2022-10-27 18:44
I think this is due to the new version of undici that was just released a few hours ago. Its `Request` implementation is throwing `RequestInit: duplex option is required when sending a body.` for the incoming request.

**Comment by Conduitry** [comment] 2022-10-27 18:47
Yeah, when I override to 5.11.0, things seem to work fine. The obvious change in 5.12.0 that would be causing this is https://github.com/nodejs/undici/pull/1681 but I haven't dug any further into what this was intended to do or whether this is a new bug there or what.

**Comment by Conduitry** [comment] 2022-10-27 18:55
I'm marking this as urgent. It might be a good idea to pin to undici 5.11.0 if we can't immediately see how we should now be calling `Request` now or if it looks like the new behavior is a bug.

**Comment by KhafraDev** [comment] 2022-10-27 21:12
This change is expected, see
https://github.com/whatwg/fetch/commit/edf07e58abdf6fbef0e1b0c3a6788dbfe93e14ad#diff-b4827ee42aceaf9dc3e7216f72262d81c32217e9996fb70a657f259e3ac92604R6899

**Comment by careerlister** [comment] 2022-10-27 23:34
Is there a work around or will the patch be coming soon?

**Comment by Conduitry** [comment] 2022-10-27 23:55
Until #7412 is released, the workaround is to use overrides to force undici@5.11.0.

**Closed** 2022-10-28 03:44 UTC
Labels: bug, p0-urgent
