### ISSUE TITLE
Sveltekit provided `fetch` function doesn't allow files or blobs to be sent in the body.

### ISSUE THREAD

**Issue by PeytonHanel** [sveltejs/kit#9790] opened 2023-04-28 01:16 UTC
### Describe the bug

The Sveltekit provided `fetch` function does not allow files or blobs to be sent in the request body.

According to your documentation [here](https://gitlab.com/peytonhanel/svelte-fetch-bug), the provided `fetch` function in Sveltekit is supposed to work identically to the native one apart from the specified differences. There is nothing to suggest that the request body can't be a file or a blob.

[Here](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_a_file) are the MDN docs explaining how to upload a file with `fetch`.

My reproduction demonstrates that the native `fetch` allows a file object, although I don't perfectly follow  the MDN instructions, while the provided Sveltekit `fetch` returns this error message:
> Error: Request body must be a string or TypedArray

The provided `fetch` should be fixed to follow the MDN documentation.

### Reproduction

https://gitlab.com/peytonhanel/svelte-fetch-bug

I use `yarn` to install
`yarn run dev` to run the server
On the webpage, there will be two buttons. The relevant files in the code are:
- /src/routes/api/+server.ts
- /src/routes/+page.svelte
- /src/routes/+page.server.ts

### Logs

```Shell
6:01:24 PM [vite] page reload src/routes/+page.server.ts (x3)
File { size: 15, type: '', name: 'file.name', lastModified: 1682643687867 }
Error: Request body must be a string or TypedArray
    at fetch (/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:120:12)
    at #options.hooks.handleFetch (/node_modules/@sveltejs/kit/src/runtime/server/index.js:46:66)
    at /node_modules/@sveltejs/kit/src/runtime/server/fetch.js:27:30
    at default (+page.server.ts:7:26)
    at call_action (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:228:9)
    at Module.handle_action_request (/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:149:22)
    at Module.render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:63:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:381:17)
    at async Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:250:20)
```

### System Info

```Shell
$ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 18.02 GB / 30.91 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    Yarn: 1.22.19 - /snap/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
  Browsers:
    Brave Browser: 112.1.50.125
    Chrome: 112.0.5615.165
    Firefox: 112.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1 
    @sveltejs/kit: ^1.5.0 => 1.15.9 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.3.0 => 4.3.3
```

### Severity

serious, but I can work around it

**Comment by PeytonHanel** [comment] 2023-04-28 01:27
So I went into the code base and found this little gem
`packages/kit/src/runtime/server/fetch.js`
```
if (request_body && typeof request_body !== 'string' && !ArrayBuffer.isView(request_body)) {
	// TODO is this still necessary? we just bail out below
	// per https://developer.mozilla.org/en-US/docs/Web/API/Request/Request, this can be a
	// Blob, BufferSource, FormData, URLSearchParams, USVString, or ReadableStream object.
	// non-string bodies are irksome to deal with, but luckily aren't particularly useful
	// in this context anyway, so we take the easy route and ban them
	throw new Error('Request body must be a string or TypedArray');
}
```

Can we just delete this line? I don't know the code base and I'm not sure if this will break anything or not :sweat_smile: It seems like an easy fix.

**Comment by dummdidumm** [comment] 2023-04-28 08:11
Closing as duplicate of #9420 - looking at the code I'm also wondering if that's just a leftover from a long time ago.

**Closed by dummdidumm** 2023-04-28 08:11 UTC
