### ISSUE TITLE
[[optional=matcher]] makes an optional route non-optional

### ISSUE THREAD

**Issue by yasserlens** [sveltejs/kit#7365] opened 2022-10-23 21:56 UTC
### Describe the bug

I expect an [[optional]] route to be optional, even with a matcher [[optional=matcher]]. However, adding a matcher makes the param a required part of the route.

To reproduce:
- Create an optional route with a matcher
- `routes/home/[[optional=matcher]]/reviews`
- This makes the optional parameter mandatory - if it's not there, the following route returns 404:
- home/reviews
- home/example/reviews works fine, assuming the matcher returns "true" for the param "example"

### Reproduction

See route "home" in the following repo:
https://stackblitz.com/edit/sveltejs-kit-template-default-bmxbym

### System Info

```Shell
this was replicated on Stackblitz - you can see the environment info there in a clean repo.
```

### Severity

serious, but I can work around it

**Comment by dominikg** [comment] 2022-10-23 22:19
Might be fixed by https://github.com/sveltejs/kit/pull/7346 /
 Duplicate of https://github.com/sveltejs/kit/issues/7344

Islightly different here is that there is an additional segment after the optional param but if the matcher is ignored, then it should match. As a workaround implement the matcher so that it returns true for undefined and empty string too

**Comment by dummdidumm** [comment] 2022-10-24 07:31
Closing as duplicate of #7344

**Closed by dummdidumm** 2022-10-24 07:31 UTC
