### ISSUE TITLE
Add stop sign to prevent inheriting from parent layouts

### ISSUE THREAD

**Issue by tonprince** [sveltejs/kit#6423] opened 2022-08-30 04:20 UTC
### Describe the problem

I have the following routes structure in my Sveltekit project:

```
src/routes/
└ +layout.svelte
├ Activities/
├ Transfers/
├ Products/
├ About/
├ Terms
├ Welcome/
  └ +layout.svelte
```

The `/Welcome` page needs to have its own layout, all the others inherit the layout from root.
Currently I have to put all other pages into a group like (app) so the `Welcome` page does not inherit from the root layout anymore.

The same applies if I want to have a totally different layout for home page `/`, I have to put it under a (root) group, and all the other pages under (app) group.

But in both use cases there is still the +error.svelte page, which now has no root layout anymore to inherit from.

### Describe the proposed solution

It would make life and routes structure much easier if we could append a stop sign to the layout file, like`+layout-.svelte` `+layout|.svelte` or any other suitable char indicating that this layout does not inherit from parent layouts (similar to the @ sign to break out of their parent layout hierarchy). 

### Importance

would make my life easier

### Additional Information
If the +error.svelte page should inherit from root layout, which now is under (app) group, I have to replicate the layout for the root error page. With the proposed solution this would not be necessary.

**Comment by rchrdnsh** [comment] 2022-08-30 04:43
If I understand the problem correctly I believe you could put parens around `(welcome)` and it will not inherit the parent layout…it was just added recently to kit.

https://kit.svelte.dev/docs/advanced-routing#advanced-layouts

**Comment by tonprince** [comment] 2022-08-30 06:39
> If I understand the problem correctly I believe you could put parens around `(welcome)` and it will not inherit the parent layout…it was just added recently to kit.
> 
> https://kit.svelte.dev/docs/advanced-routing#advanced-layouts

Layouts (normal and the ones in group) always inherit from the root layout, and this is exactly the problem. There is currently no way to say that a specific layout or page should NOT inherit from root. The only solution is to create 2 groups, but it seems a bit of a overhead for me.

**Comment by dummdidumm** [comment] 2022-08-30 07:39
What kind of issues does it create for with `+error.svelte` for you?

What we won't do is to provide a way to break out of the root layout. Making the guarantee that the root layout is always present makes it possible to put app-wide logic or UI in there. I understand that it may be cumbersome to create a group for this, but this is the tradeoff we are making. The alternative would be to create a `#if` statement in your root layout to hide the surrounding UI if you are on the welcome page.

**Comment by tonprince** [comment] 2022-08-30 08:04
Currently I have to include the layout into the `+error.svelte` page directly, which that does not feel well.

For our use case and I think for others as well, we need to escape from the root layout as well as from the app-wide logic for some pages like Welcome, Home etc. and other distinct pages which break out from the standard layout.

Currently it is already possible to escape from parent layouts in a nested page (by using @), so I am wondering what makes it different from the root one?

**Comment by dummdidumm** [comment] 2022-08-30 08:31
It was like this before and it lead to all kinds of subtle inconsistencies:
- We can't guarantee that the root layout is the one that is rendered in case of an error. But we would like to lead it and the root error page eagerly to have it available in case of a catastrophic error + no network at this point
- If you are on page X and an error occurs which would be rendered in a different root layout, is that what you want?
- No clear place to put app-wide logic: Imagine you have two root layouts, someone else would come along and say "but I don't want to duplicate my app-wide logic in these two places"

It's also harder to grasp what layout runs, right now you know the root layout is always there, and you can only go upwards when inheriting or skipping layouts.

As you can see, we need to make a tradeoff (there's no solution that makes everyone happy since use cases are so differently) and we chose "root layout is always present". Yes it means you may need to import your layout UI into your error page, yes it means you either need to create a group or use `if` statements in your layout UI and load function, but that's an acceptable solution which everyone coming into the code base can easily understand.

Closing this since it's working as designed.

**Closed by dummdidumm** 2022-08-30 08:31 UTC

**Comment by maximedupre** [comment] 2022-09-01 14:02
@dummdidumm I understand that there were tradeoffs to make. Can you let me know if I have understood the problem/solution correctly? 🥹

# Problem

I have two groups: `(maintenance)` and `(app)`.

I have a `/maintenance` page that I don't want to have the "normal" app/root layout. So I put `maintenance.svelte` in its own group. However, it is still affected by the route layout - it is impossible to break out of the root layout.

I can move the root layout into the `(app)` group, but then the error page has no more layout.

I can't move the error page into the `(app)` group because then root-level errors (e.g. 404) won't use the error page.

# Solution

Keep root layout and have `if` statements that remove part of the markup for the `/maintenance` route.

**Comment by dummdidumm** [comment] 2022-09-01 15:13
Yes that's one possible solution. The other one would be to reuse the layout UI inside the root error page.
