### ISSUE TITLE
BeforeNavigate not firing on Shallow routing

### ISSUE THREAD

**Issue by AndreasHald** [sveltejs/kit#12956] opened 2024-11-05 09:13 UTC
### Describe the bug

When you navigate shallowly to a page `beforeNavigate` will not work when you navigate away

### Reproduction

The repo has 2 links, one which uses normal navigation to go to `/bob` and one which uses shallow navigation
if you go to `/bob` normally and navigates back, you see an alert. however if you go there shallowly and back you do not.

https://www.sveltelab.dev/6kwef9i2beei35f?login=true&files=.%2Fsrc%2Froutes%2F%2Bpage.svelte%2C.%2Fsrc%2Flib%2Fshallow.svelte%2C.%2Fsrc%2Froutes%2Fbob%2F%2Bpage.svelte

### Logs

```Shell
No logs relevant
```

### System Info

```Shell
Here is my output, but i think this is reproducible everywhere

  System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 443.39 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.0 - ~/.nvm/versions/node/v20.13.0/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.13.0/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.0.1
  npmPackages:
    @sveltejs/adapter-vercel: ^5.4.3 => 5.4.5 
    @sveltejs/kit: ^2.7.3 => 2.6.4 
    @sveltejs/vite-plugin-svelte: ^3.1.2 => 3.1.2 
    svelte: ^4.2.17 => 4.2.19 
    vite: ^5.4.6 => 5.4.6
```

### Severity

annoyance  - with no viable workaround

### Additional Information

In my concrete case we use shallow routing for forms within modals, and normally when you taint a form and tries to navigate away, we stop you to make sure you do not throw away your changes. However this breaks when navigating shallowly.

As far as i could tell the only workaround would be something like the following

```svelte
<svelte:window
    on:popstate={(e) => {
        if (form_is_tainted) {
            history.pushState(null, '', window.location.href);
        }
    }} />
```

But this is discouraged because this conflicts with svelte kit router

**Comment by Conduitry** [comment] 2024-11-05 10:50
Duplicate of #11776.

**Closed by Conduitry** 2024-11-05 10:50 UTC
