### ISSUE TITLE
`$page.statics`

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#1459] opened 2021-05-15 14:03 UTC
**Is your feature request related to a problem? Please describe.**
I need to be able to set meta data for every route and access the correct meta data for the currently active route. The solution I have right now requires me to import all meta data upfront or use the context API which is not supported by the SSR without saying no to your no-JavaScript users.

**Describe the solution you'd like**
```html
<!-- One of your routes -->
<script context="module">
    import Component from './_someComponent.svelte'

    export const statics = {
        foo: 'bar',
        baz: false,
        someComponent: Component,
        requiredPermissions: ['view-page']
    }
</script>
```

```html
<!--  src/routes/__layout.svelte -->
<script context="module">
    import { hasPermissions } from '$lib/auth.js'

    export function load({ page })
    {
        if( !hasPermissions( page.statics.requiredPermissions ) )
        {
            return {
                status: 403,
                error: new Error( 'You do not have access to this page.' )
            }
        }

        return { status: 200 }
    }
</script>

<script>
    import page from '$app/stores'
</script>

<svelte:component this={$page.statics.someComponent}></svelte:component>
<slot />
```

I think the code snippets pretty much speaks for themselves. `$page.statics` is just equal to the current's page statics exported from its context module.

**Describe alternatives you've considered**
I first tried the context API in combination with a writable but quickly found out this isn't a good idea if you want a stable SSR and support no-JavaScript users. Now I am using `$page.path` in a big switch inside my primary layout. I already run in to maintainability issues though.

**How important is this feature to you?**
Currently the quality, complexity and maintainability of my application is heavily limited.

**Comment by mvolfik** [comment] 2021-05-17 11:18
The use case shown in the example looks like something solvable with named slots in layout (#627, but unfortunately doesn't seem to be tracked in 1.0), but I can definitely see use cases for this too

**Comment by UltraCakeBakery** [comment] 2021-05-17 12:19
> The use case shown in the example looks like something solvable with named slots in layout (#627, but unfortunately doesn't seem to be tracked in 1.0), but I can definitely see use cases for this too

It would but it is definitely something I wouldn't want to do in my case. If I could use named slots in my layout I would probably mess up the dataflow throughout my entire application and my route components would become messy quite quickly. In my opinion it should be possible though. Just not recommended in most use cases. Maybe even throw a warning...

**Comment by Conduitry** [comment] 2021-05-17 12:58
More or less a duplicate of #269. I think these two issues would be resolved by the same feature, whatever it ended up looking like.

**Closed** 2021-05-17 12:59 UTC

**Comment by UltraCakeBakery** [comment] 2021-05-17 13:09
> More or less a duplicate of #269. I think these two issues would be resolved by the same feature, whatever it ended up looking like.

I completely glossed over your issue. @benmccann would #269 be worthy of the `1.0` milestone?
