### ISSUE TITLE
Dynamic [slug].svelte page is not updating after 2 navigation

### ISSUE THREAD

**Issue by yassinrais** [sveltejs/kit#1449] opened 2021-05-14 14:32 UTC
Sorry again ! 

I have problem when i use a dynamic pages with svelte kit (node-adapter)
when i navigate between pages its change the first 2 diffirent pages but others does not change :( 

here the [slug].svelte code
```svelte
 <script context="module">
	/**
	 * @type {import('@sveltejs/kit').Load}
	 */
	export async function load({ page: { params }, fetch }) {
		const { slug } = params;

		const url = `/club/${slug}.json`;
		const res = await fetch(url);
		const data = await res.json();

		if (res.ok) {
			console.log('Fetch new data', slug);
			return {
				props: {
					data: data
				}
			};
		}
		return {
			status: res.status,
			error: new Error(`Could not load ${url}`)
		};
	}
</script>

<script>
	import Jumbotron from '../../components/Sections/Jumbotron.svelte';
	import Features from '../../components/Sections/Features.svelte';
	import Video from '../../components/Sections/Video.svelte';
	import Partners from '../../components/Sections/Partners.svelte';
	import Cta from '../../components/Button/Cta.svelte';
	import BannerClub from '../../components/Sections/BannerClub.svelte';
	import TeamInfo from '../../components/Sections/TeamInfo.svelte';
	import HowToParticipate from '../../components/Sections/HowToParticipate.svelte';
	import Participate from '../../components/Sections/Participate.svelte';
	import Gifts from '../../components/Sections/Gifts.svelte';
	import KitsGenerator from '../../components/Sections/KitsGenerator.svelte';
	import { onMount } from 'svelte';

	export let data;

	const getColoredTitle = (title) => {
		title = title.split(' ');
		let half = Math.round(title.length / 2);

		return `${title.slice(0, half).join(' ')} <span class='text-orange'>${title
			.slice(half, title.length)
			.join(' ')}</span>`;
	};

	const getLogo = (slug) => {
		return `/static/images/clubs/logo/${slug}.svg`;
	};

	const getHeader = (slug) => {
		return `/static/images/clubs/header/${slug}.jpg`;
	};

	onMount(() => {
		document.title = `${data.club.title} - 5km pour nos clubs`;
	});
</script>

<div class="page-index fill-current">
	<Jumbotron stats={data.stats} logoImg={data.club.slug} backgroundImg={getHeader(data.club.slug)}>
		<div slot="cta">
			<a href="#participate">
				<Cta mode="dark wtext">Je cours pour le {data.club.title}</Cta>
			</a>

			<style>
				.jumbotron .special {
					@apply md:ml-96 md:pl-8 !important;
				}
				.jumbotron .logo svg {
					max-height: 150px;
				}
				.jumbotron .logo {
					@apply text-white fill-current;
				}
			</style>
		</div>
	</Jumbotron>

	<TeamInfo
		coloredtitle={getColoredTitle(data.club.title)}
		logo={getLogo(data.club.slug)}
		info={data.club.page}
	/>
	<Features />
	<Participate slug={data.club.slug} />
	<Video>
		<p slot="title">
			{@html getColoredTitle(data.club.title)}
		</p>

		<p slot="desc">En quelques mots</p>

		<a slot="cta" href="#participate">
			<Cta mode="dark">Je cours pour le {data.club.title}</Cta>
		</a>
	</Video>

	<BannerClub />
	<HowToParticipate />
	<Gifts />
	<KitsGenerator club={data.club.page.shortname} />
	<Partners />
</div>
```

**Comment by Conduitry** [comment] 2021-05-14 14:47
Please provide a complete, minimal, self-contained reproduction - and not just parts of your app.

**Comment by yassinrais** [comment] 2021-05-14 14:59
Routes : 
![image](https://user-images.githubusercontent.com/25354731/118288429-bbb1f300-b4d4-11eb-862b-c4a842d0c8f2.png)

[slug].json.js
```js
import { getClub } from '$lib/clubs.js'


/**
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export async function get({ params }) {
    const { slug } = params;
    const club = await getClub(slug);

    /**
     * Fetch Club+Stats from Db
     */
    return {
        body: club
    }
}

```
**[slug].json.js endpoint work normaly , the data charged correctly for each club** 
Example :
```json
{
  "club": {
    "slug": "abc",
    "title": "ABC",
    "page": {
      "shortname": "AB",
      "createdAt": "1967",
      "location": "XXXX",
      "licensees": 0,
      "email": "XXXX",
      "website": "XXXX",
      "video": "XXXX",
      "story": "example of story. ...",
      "media": {
        "facebook": "https://www.facebook.com/.page"
      }
    }
  },
  "stats": {
    "amount": 0,
    "participants": 0
  }
}
```

**Oh ! i think i know where the issue come**
Im using a library [svelte-inline-svg](https://www.npmjs.com/package/svelte-inline-svg)
and yeah when i give it the logo source svg link its work , after changing to page 2 the logo change to the 2 one 
but after that , the logo never change anymore 

Is there any way to force the component to reload with the new source ?

**Comment by shah-mcc** [comment] 2021-05-17 15:35
I am facing the same issue. Say you have a route `/blog/[slug].svelte` that displays 1 blog article and links to 10 other blog articles (all which use the same route `/blog/[slug].svelte`). You can navigate 2 times to any other articles but not a 3rd time using the client router. If you manually refresh the browser you can again navigate another 2 times before it stops working again. I hope that clears up the issue. Thanks.

**Comment by yassinrais** [comment] 2021-05-17 15:47
@shah-mcc  Yes currect ! 

The solution i found is that you need to do like this 

when you have the load data 

```js
export let data; 
// and other things 
```
you will need to do something like 

```js
export let data;

let current_data;
$: data,  (()=>{
  // and here you do the update (its like watch in vuejs)
  // document.title = `Page ${data.title}`;
  current_data = data;
})();
```

this is how i solv this issue for now , but im not sur if this is the right way to do its in svelte

**Comment by shah-mcc** [comment] 2021-05-17 17:43
@yassinrais Your workaround works. Thanks for that.
I guess the prop `export let data` doesn't update when the route page doesn't change (eg. going from blog/1 to /blog/2) but when we force it to be reactive with the `$` symbol it updates and functions as expected.

**Comment by yassinrais** [comment] 2021-05-17 17:56
Your welcome 😉,

This toke me some days to figure out,
The documentation of svelte its small and need really to be more bigger 
Because i feel like trying to learn the svelte instead of using it for my project 😅

Im sur there is another way to do this more proply, but unfortunately im not svelte expert 🤭.

Greetings 👌

**Comment by ric2b** [comment] 2021-05-20 12:05
@Conduitry I believe this is the same issue as https://github.com/sveltejs/kit/issues/1497, where I added a minimal, self-contained reproduction.

**Comment by yassinrais** [comment] 2021-05-20 12:08
@ric2b Correct

**Comment by benmccann** [comment] 2021-07-23 18:28
Closing this as a duplicate of https://github.com/sveltejs/kit/issues/1497

**Closed by benmccann** 2021-07-23 18:28 UTC
Labels: pending clarification
