### ISSUE TITLE
Styles flash when using CSS Modules in the development environment

### ISSUE THREAD

**Issue by anpabupa** [sveltejs/kit#5019] opened 2022-05-21 19:00 UTC
### Describe the bug

Styles flash when using CSS Modules in the development environment .
I found that in inlineStyle, the style of CSS Module was not inserted correctly, and the [object object] was incorrectly spliced.
You 
You can view source code  by running the local environment (yarn dev).
![image](https://user-images.githubusercontent.com/35018996/169665626-f578e93f-2e90-464f-8431-cf2221abc0e9.png)

### Reproduction

https://github.com/anpabupa/sveltejs-kit-template-default-hf6rzq

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 475.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.44 
    @sveltejs/kit: next => 1.0.0-next.338 
    svelte: ^3.46.0 => 3.48.0
```

### Severity

annoyance

**Comment by gkatsanos** [comment] 2022-05-22 11:45
@anpabupa https://stackblitz.com/github/anpabupa/sveltejs-kit-template-default-hf6rzq can't reproduce your issue - please verify again on the link above (which is an import of your github repro)

**Comment by mrkishi** [comment] 2022-05-22 12:41
@gkatsanos I can see the issue in your Stackblitz. In fact, this has never been supported by SvelteKit.

Vite processes CSS modules as expected and returns an object for `mod.default` from `ssrLoadModule`. We assume it's a CSS string here:

https://github.com/sveltejs/kit/blob/01d9d30c1a7f71524e3fcc552bcb1f7de109f6db/packages/kit/src/core/dev/plugin.js#L76-L88

We'd need to inline the module's _original source_ in these cases, but I'm unsure if there's a Vite-recommended way to get them. I haven't found anything in the module graph nor in the transformed nodes. I may very well be missing it, but if not, perhaps we'll need to read the file ourselves and/or potentially upstream a way to get the plain source when needed.

**Comment by gkatsanos** [comment] 2022-05-22 13:09
Indeed, I see it when I edit the index file / HMR-ing. If its a dev-only thing, doesn't seem so dramatic ..

**Comment by Rich-Harris** [comment] 2023-01-23 18:14
Going to close this as there's really no reliable way to get hold of the underlying styles during SSR, and since it only happens during development it's low impact. This is a general limitation of CSS-in-JS solutions

**Closed by Rich-Harris** 2023-01-23 18:14 UTC
Labels: bug, p2-nice-to-have
