### ISSUE TITLE
Prerender setting affects all components within a route and thus ignores dynamic session state

### ISSUE THREAD

**Issue by eikaramba** [sveltejs/kit#1723] opened 2021-06-20 22:27 UTC
**Describe the bug**
Sry for the title if misleading, but let me explain.

I have a **navbar which shows a Login or Logout Button depending on whether the user is logged in**. This works on Server Side and Client Side on development server.

However when building via node adapter and running the application i noticed that the **authentication state was always lost upon refreshing** the page.

After some investigation i found out that removing `export const prerender = true;` from my index.svelte file fixes the problem.

The reason why this confuses me is that the index.svelte file never even uses the session store.

My __layout.svelte file is including a navbar.svelte file which renders the ui differently depending on `$session.authenticated`.

all other files do not change the prerender variable. i would expect that only the index.svelte component would be prerendered. And even if so honestly i am still confused why the navbar would not be rerendered at least once when the hydration on the client finishes. but maybe that is another topic.

**infos**
using
"@sveltejs/kit": "^1.0.0-next.115",
"@sveltejs/adapter-node": "^1.0.0-next.26",

**Expected behavior**
That the __layout contents and withing there the navbar component are not prerended and thus correctly making use of the session store during SSR.

if anything is unclear i can try to make a video showing the problem

**Comment by benmccann** [comment] 2021-06-22 03:01
Prerendering is currently all-or-nothing for a page. We don't prerender individual components. Though what some people do is prerender the whole page and then load dynamic pieces only on the client-side in `onMount`

**Comment by eikaramba** [comment] 2021-06-22 09:29
thanks for the info, i guess that is something maybe for the docs.

**Comment by benmccann** [comment] 2021-06-22 13:36
This is somewhat duplicate of https://github.com/sveltejs/kit/issues/1660#issuecomment-859232446

I took a look at the docs just now and it does refer to pages being prerendered. I'm not sure whether there's much else that should be clarified? I'm going to go ahead and close this, but let me know if there's anything you think is misleading in the docs

**Closed by benmccann** 2021-06-22 13:36 UTC
