### ISSUE TITLE
allow form actions without page component

### ISSUE THREAD

**Issue by stephane-vanraes** [sveltejs/kit#7392] opened 2022-10-26 07:27 UTC
### Describe the problem

I would like to make form actions available from anywhere in the app, as described in the documentation:
```html
<form method="POST" action="/login">
  <!-- content -->
</form>
```
This does however require me to make a route `/login`, `/logout`, `/register`, ... while it would make sense to me to group them in one file exporting several actions such that I can do (as in the example from the docs):
```html
<form method="POST" action="/login?/register">
```

However, if I just make a file `/login/+page.server.js` without a `+page.js` I get the following error:

> node.component is not a function TypeError: node.component is not a function

### Describe the proposed solution

Allow to have a similar construct as `Actions` in a pure API endpoint (+server.js).

### Alternatives considered

**Workaround**

This can be solved by adding an actual page and redirecting directly (I have no need for a login page in this case).

### Importance

nice to have

**Comment by dummdidumm** [comment] 2022-10-26 07:52
I'm not sure I fully understand. The idea of actions is that they work without JavaScript. If there is no page connected to the form action it wouldn't be possible to work without JavaScript.

If the problem is that you want to have several forms on the same page but only show one at a time, you could read the query string parameter in `+page.svelte` to only show the desired form.

**Comment by stephane-vanraes** [comment] 2022-10-26 08:22
Currently if I would have a pure API (no pages) with several related endpoints (let's say user things) I have to make a file for each, all with a POST handler:

```
/user/login/+server.js
/user/logout/+server.js
/user/register/+server.js
/user/reset/+server.js
```

Each of this can be accessed with a form like normally:
```html
<form method="POST" action="/reset/login">
```

The idea here is that we would be able to _group_ all these related endpoints easily, hooking into the same concepts as the form actions and have only one file (potentially benefiting from shared logic)
```
/user/+server.js
```

And call them _similar_ to how we would form actions
```html
<form method="POST" action="/reset?/login">
```

It doesn't have to be the same as "Form Actions", I am just referring to those because of the similarity.

This isn't a **must have**, but might be nice as I feel it reduces some boilerplate :)

**Comment by dummdidumm** [comment] 2022-10-27 12:20
Ok, so this would be something that would not work without JavaScript, but as I understand it you would like to keep using the form actions regardless.

**Comment by schmic** [comment] 2022-10-27 20:53
@stephane-vanraes You could create a `/user/[action]/+server.js` route and check for the action param

**Comment by stephane-vanraes** [comment] 2022-10-28 05:22
> @stephane-vanraes You could create a `/user/[action]/+server.js` route and check for the action param

Yes, that is the workaround we actually use.  In that case you would have a singular POST with a series of `if`s or a `switch` that pipes the request into the correct method.  What this proposal basically is, is removing this boilerplate.

The above method would work _without_ JavaScript enabled on the client, as it is a simple matter of reading the first (search) parameter.

On the other hand, doing this for POST would open up that people want it for the other verbs as well, raising complexity... (not to mention that it would be a breaking change)

**Comment by dummdidumm** [comment] 2022-10-28 07:51
> The above method would work without JavaScript enabled on the client, as it is a simple matter of reading the first (search) parameter.

I'm not sure that's true. You are saying that you want to be able to have a `+page.server.js` _without_ a `+page.svelte` - so what would happen in the success case? What would happen in case of a validation error? Would you place a `throw redirect` in your actions and always go somewhere else (because there's no page to render these things on)? Would you expect the action to automagically redirect back to where you came from? Not sure I understand exactly what you want.

**Comment by stephane-vanraes** [comment] 2022-10-28 08:07
> I'm not sure that's true. You are saying that you want to be able to have a `+page.server.js` _without_ a `+page.svelte` - so what would happen in the success case? What would happen in case of a validation error? Would you place a `throw redirect` in your actions and always go somewhere else (because there's no page to render these things on)? Would you expect the action to automagically redirect back to where you came from? Not sure I understand exactly what you want.

I think I see what is the misunderstanding, I want a functionality _like_ `+page.server.js` but _in_ `+server.js`, so the return would still be the same as in `+server.js`

Basically, it would be a way to reduce the checking in this (based on the previous answer's recommendations)
```js
export function POST({ params, request }) {
  if (params.action == 'dothis') {
    // process one way
  }
  if (params.action == 'dothat') {
   // process one way
  }
}
``` with obviously `dothis` and `dothat` very related to each other

perhaps it's a bit of silly way to try to not have this: ```
| api
- | dothis
--- | +server.js
- | dothat
--- | +server.js
```

especially if there is some shared logic between both endpoints

anyway, the more I think about it, the more it feels over complicated and there is a workaround for it that with some clever js hacks can be made fairly concise (think something like `return processors[ev.params.action](ev)`) 

Not sure if it is worth the extra complexity in kit itself, unless it can homogenize difference between `+page.server.js` and `+server.js`.

**Comment by dummdidumm** [comment] 2022-10-28 08:23
Ok I think I understand now - so it's about not having to create `login/+server.js`, `logout/+server.js` etc files because you'd like to have these things closer together / not as many files lying around.

**Comment by LucianVoju** [comment] 2022-10-28 08:33
Can the action point to a `+layout.server.js` ? So every page under that layout can point to it.

**Comment by stephane-vanraes** [comment] 2022-10-28 08:34
That part is probably where the confusion starts as it is a bad example, you are right that this is about pure API endpoints and therefore requires javascript because it would be done in a `fetch`.

All in all, it's a matter of organizing code that 'seems to belong together' that now feel disconnected because each endpoint would need it's own directory.  (imho this is a section where the directory structure falls short, while for pages it is very well implemented)

**Comment by Rich-Harris** [comment] 2022-11-17 14:11
Would this pattern make sense?

```js
// src/routes/auth/[action]/+server.ts
import { error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

const actions: Record<string, RequestHandler> = {
  login: async (event) => {...},
  logout: async (event) => {...},
  register: async (event) => {...}
};

export const POST: RequestHandler = (event) => {
  const handler = actions[event.params.action];
  if (!handler) throw error(404);

  return handler(event);
};
```

The boilerplate seems fairly minimal, and could even be abstracted into a helper function if it was needed in multiple places:

```js
export const POST = combineHandlers({
  login: async (event) => {...},
  logout: async (event) => {...},
  register: async (event) => {...}
});
```

**Comment by stephane-vanraes** [comment] 2022-11-17 21:09
> Would this pattern make sense?

Yes it would!

The combination of the 'action' as a param and then a lookup table seems the way to handle this in the current setup.  The `combineHandlers` function is not that hard to write and could probably be put as a package (or eventually incorporated into SvelteKit itself if this a often recurring pattern).

Unless there are plans to add a section of 'recipes/patterns' etc on the official site, I would think this is something that could be added to the Svelte Society site instead.

**Comment by Rich-Harris** [comment] 2022-11-17 22:49
Cool — will close this in that case

**Closed by Rich-Harris** 2022-11-17 22:49 UTC
