### ISSUE TITLE
Enabling https causes an infinite loop of reloads

### ISSUE THREAD

**Issue by arnu515** [sveltejs/kit#1464] opened 2021-05-16 13:27 UTC
**Describe the bug**
When we enable https as mentioned in the [documentation](https://kit.svelte.dev/docs#command-line-interface-svelte-kit-dev) with this command:
```bash
svelte-kit dev --https
```
The website, once accessed over `https` will cause an infinite loop of reloads.

**Logs**
Browser logs (brave browser, fork of chromium):
![Screenshot from 2021-05-16 18-51-55](https://user-images.githubusercontent.com/52203828/118398797-d53f7000-b677-11eb-8efc-ee35623c158c.png)

Browser logs (firefox)
![Screenshot from 2021-05-16 18-54-27](https://user-images.githubusercontent.com/52203828/118398900-35cead00-b678-11eb-8326-009faa4efc8d.png)

**To Reproduce**
Add the `--https` flag to the `dev` script in `package.json`.

**Expected behavior**
The website should load over https without infinite reload loops

**Stacktraces**
Nothing

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
  System:
    OS: Linux 5.11 Pop!_OS 20.10
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 794.92 MB / 7.67 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Brave Browser: 90.1.23.73
    Firefox: 87.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.107 
    svelte: ^3.34.0 => 3.38.2 
```

- Your browser
Tested on Brave v90 and firefox v87

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Node, but i used `svelte-kit dev`
</details>

**Severity**
Annoying

**Additional context**
N/A

**Comment by Conduitry** [comment] 2021-05-16 13:30
Duplicate of #844

**Closed by Conduitry** 2021-05-16 13:30 UTC

**Comment by arnu515** [comment] 2021-05-17 02:50
My bad, didn't show up when i searched for similar issues
