### ISSUE TITLE
app.html & %svelte.body%

### ISSUE THREAD

**Issue by snoriq** [sveltejs/kit#2508] opened 2021-09-27 20:50 UTC
### Describe the bug

Hi,
I've an app that I started in Sapper and updated through to current sveltkit version and realized that the following creates a bug, where the %svelte.body% that's in the comments is also interpreted & executed.

```
<body>
	<!-- The application will be rendered inside this element,
	     because `src/client.js` references it -->
	<!-- <div id="sapper">%svelte.body%</div> -->
	
	<div id="svelte">%svelte.body%</div>

	
</body>
```

### Reproduction

just modify app.html as below:

`<body>
	
	
	
	<div id="svelte">%svelte.body%</div>

	
</body>`

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 29.24 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    npm: 7.7.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.175 
    svelte: ^3.34.0 => 3.43.0
```

### Severity

annoyance

**Comment by benmccann** [comment] 2021-09-28 02:58
Yeah, I think this is mostly working as intended and changing it would be pretty low on the priority list, so I'm going to go ahead and close this one

**Closed by benmccann** 2021-09-28 02:58 UTC
Labels: p3-edge-case
