### ISSUE TITLE
TypeError: loader is not a function

### ISSUE THREAD

**Issue by allmors** [sveltejs/kit#12703] opened 2024-09-23 07:58 UTC
### Describe the bug

Create a simple route and the console reports an error
![image](https://github.com/user-attachments/assets/201670ce-b93f-43a8-ab15-a021df75d543)
![image](https://github.com/user-attachments/assets/42522d0b-d10d-4c5a-ba63-e5b50ea146c4)
![image](https://github.com/user-attachments/assets/a645a29e-3224-4cc8-b08a-b1c2724ed351)

### Reproduction

Install the sveltekit project normally

### System Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 AMD EPYC 7763 64-Core Processor
    Memory: 3.89 GB / 7.77 GB
    Container: Yes
    Shell: Unknown - /bin/sh
  Binaries:
    Node: 20.16.0 - /usr/bin/node
    npm: 10.8.1 - /usr/bin/npm
    pnpm: 9.6.0 - /usr/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.5 
    @sveltejs/kit: ^2.0.0 => 2.5.28 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.2 
    svelte: ^4.2.7 => 4.2.19 
    vite: ^5.0.3 => 5.4.6
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-10-21 07:43
Please provide a minimal reproduction in the form of a downloadable repository or stackblitz link so that we can diagnose the root cause of the problem. I'll be closing this until one is provided.

**Closed by eltigerchino** 2024-10-21 07:43 UTC
