### ISSUE TITLE
On page preload global css overrides currently loaded page styles

### ISSUE THREAD

**Issue by phoenisx** [sveltejs/kit#10595] opened 2023-08-21 18:36 UTC
### Describe the bug

When we have an `<a>` anchor tag that links to a separate page different from than the currently loaded page, and both these pages share a global class name, hovering over the anchor tag preloads the next page (or clicking -> navigating to page-2 -> and navigating back to page-1) and overrides the global styles of the currently loaded page.

### Reproduction

Repro: https://stackblitz.com/edit/sveltejs-kit-template-default-xsrzyd?file=src%2Froutes%2Fpage2%2F%2Bpage.svelte

**NOTE: The only limitation in the above repro is that hover is not preloading assets in _stackblitz_, but if you click on the anchor tag, navigate to page2 and navigate back to page1, the styles from page2 persist on page1**

### System Info

```Shell
System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 256.02 MB / 16.00 GB
  Shell: 3.5.1 - /opt/homebrew/bin/fish
Binaries:
  Node: 18.16.1 - /opt/homebrew/opt/nvm/versions/node/v18.16.1/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 9.6.6 - /opt/homebrew/bin/npm
  pnpm: 8.6.6 - /opt/homebrew/bin/pnpm
Browsers:
  Brave Browser: 116.1.57.47
  Chrome: 115.0.5790.170
  Safari: 16.5.2
npmPackages:
  @sveltejs/adapter-node: ^1.3.1 => 1.3.1
  @sveltejs/kit: ^1.22.3 => 1.22.3
  svelte: ^4.0.0 => 4.0.1
  vite: ^4.3.6 => 4.3.9
```

### Severity

serious, but I can work around it

### Additional Information

Not sure how serious this issue should be considered, cause leaking global CSS was a mistake on my end as well.
Though, both these global CSS existed inside two different pages, they shouldn't have affected each other.

**Comment by Conduitry** [comment] 2023-08-21 19:18
Essentially a duplicate of #7918/#7751. What happens with conflicting global styles isn't a behavior we want to define. If possible, you should make each page/component's styles be scoped to that page/component.

**Closed by Conduitry** 2023-08-21 19:18 UTC
