### ISSUE TITLE
Error: Can't find stylesheet to import when I start working opening main folder, but not client folder directly. But a projects runs and builds

### ISSUE THREAD

**Issue by xreider** [sveltejs/kit#13062] opened 2024-11-27 01:52 UTC
### Describe the bug

My project has the next structure:

main folder/
* api (with Express.js)
* client (with SvelteKit)

When I open main folder via VSCode and then run command `cd client & npm run dev`, I catch errors in all .svelte files where I import scss mixins in style section.

But SvelteKit runs and builds normally.

If I open client folder directly via VSCode and then run command `npm run dev`, I catch no errors in style sections.

### Reproduction

[https://github.com/xreider/bug.sveltekit-ts.2/tree/main](https://github.com/xreider/bug.sveltekit-ts.2/tree/main)

### Logs

```Shell
Error in referenced file

Error: Can't find stylesheet to import.
  ╷
2 │   @use "$lib/styles/includes/brakepoints.scss" as *;
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  client\src\routes\+page.svelte.vite-preprocess.scss 2:3  root stylesheetsvelte(style)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700HX
    Memory: 14.37 GB / 31.74 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.2 - ~\AppData\Roaming\npm\bun.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1
    @sveltejs/kit: ^2.0.0 => 2.8.1
    @sveltejs/package: ^2.0.0 => 2.3.7
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.1
    svelte: ^5.0.0 => 5.2.7
    vite: ^5.0.11 => 5.4.11
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-11-27 07:02
I can't reproduce this given the current reproduction. Please provide another minimal reproduction.

**Comment by xreider** [comment] 2024-11-27 07:29
1) Just install dependecies
2) Open main folder (not client folder) via VSCode
3) Open terminal
4) then run command `cd .\client\` via VSCode terminal
5) then run command `npm run dev` via VSCode terminal
6) Open file client/src/routes/+layout.svelte 
7) Scroll to style section
8) See the warnings on the right triangular bracket of `<style lang="scss">`


![2024-11-27_17-28-42](https://github.com/user-attachments/assets/ba06c685-db71-4afd-8d29-5ba15726a0d7)

**Comment by eltigerchino** [comment] 2024-11-28 02:12
This issue should be moved to https://github.com/sveltejs/language-tools

**Comment by jasonlyu123** [comment] 2024-11-28 13:48
This is because in the editor/language-server the process.cwd() is where you open your editor and differ from where you build. You can see https://github.com/sveltejs/language-tools/issues/1986 for workarounds.

**Comment by eltigerchino** [comment] 2024-11-29 01:20
closing as duplicate of https://github.com/sveltejs/language-tools/issues/1986

**Closed by eltigerchino** 2024-11-29 01:20 UTC
