### ISSUE TITLE
Redirects in "PageServerLoad" does result in 500 internal error within in a pnpm workspace if "preserveSymlinks" is used in vite.config.ts

### ISSUE THREAD

**Issue by msprada** [sveltejs/kit#12139] opened 2024-04-19 10:12 UTC
### Describe the bug

First of all I'm not 100% sure if this "defect" is caused by Vite or Svelte Kit.  But I decided to go for a issue in the svelte kit repo. If this is related to Vite and the Svelte Kit Team cannot handle it, I will definitely open the ticket or transfer the ticket to the other Repo.

**Update  07/08/2024:**
In the meantime I  created an issue for the vite team as well => https://github.com/vitejs/vite/issues/17631.

I search for similar bugs within the list and for sure within the www, but I could not find any ones. 
Maybe it is related to this  instance of Redirect Check wich was mentioned here  => [Redirects in load functions break when running client-side #5952](https://github.com/sveltejs/kit/issues/5952#issuecomment-1218844057)

Situation:
- I created a pnpm workspace including one application which provides a REST API (nestJS) and the second application which includes the svelte kit ui. Furthermore I have packages which includes all shared libraries e.g a lib for the dtos, models. etc.

To be able to reference the models library in the svelte application I added a symlink within the packages.json in the way pnpm wants it to be: "data-access-models": "workspace:*"

```
"dependencies":
 {
	"@lucia-auth/adapter-sqlite": "^3.0.1",
	"arctic": "^1.5.0",
	"better-sqlite3": "^9.5.0",
	"data-access-models": "workspace:*",
	"esm-env": "^1.0.0",
	"oslo": "^1.2.0"
},
```

So I can use this importing in my pages and components "page.svelte":

`<script lang="ts">
	import { OrderDto } from 'data-access-models';
	export let data;
	const orders: OrderDto[] = data.orders;
</script>`

Without further changes with in the application this resulted in following error:

<img width="1256" alt="image" src="https://github.com/sveltejs/kit/assets/6823525/2abb6774-922e-4cba-ae5c-8c4c695a32b4">

To get this working I had to change the vite.config  extend the "resolve" part which results in following.

```

import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vitest/config';

export default defineConfig({
	plugins: [sveltekit()],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	},
	resolve: {
		preserveSymlinks: true
	}
});
```

So far so could I could use the models and the component was rendered perfectly.

UPDATE 07/08/24: 
__In the meantime I build the shared lib as ES as well as commonJS lib and there is no need for symlinks.
But the issue when using preserveSymlinks set to true still exists.
See [Discord](https://discord.com/channels/457912077277855764/1232633875000197170) for details.__

Currently I'm implementing authentication and authorization using [Lucia Auth](https://lucia-auth.com).

So there is the need of redirect a user from my homepage if he/she is not logged in.

So I included following file under routes folder "page.server.ts" and implementing the PageServerLoad Method.

```
export const load: PageServerLoad = async (event) => {
	if (!event.locals.user) {
		console.error('redirect triggered!');
		redirect(302, "/signin");
	}
	return {
		user: event.locals.user
	};
};
```

If I open my homepage within login into the application the ui shows me a 500 error instead of redirecting me to the /signin route.

Within my server logs I can see following entry:

<img width="728" alt="image" src="https://github.com/sveltejs/kit/assets/6823525/a295b2c8-c0a1-473e-8f69-4e59c1b4ac3d">

And if navigating to the url /signin the Signin Screen is shown without any problems.

### Reproduction

- to reproduce the behavior visit [Following Repo](https://github.com/msprada/svelte-kit-issue--12139)
- it was newly created and only relevant part is included
- follow the steps within in the readme.md file which is included in the root folder

### System Info

```Shell
System:
    OS: macOS 11.7.10
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 437.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.4 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 16.6.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

If there is anything missing within the description please let me know.

**Comment by eltigerchino** [comment] 2024-10-23 02:56
closing as duplicate of https://github.com/sveltejs/kit/issues/12597

**Closed by eltigerchino** 2024-10-23 02:56 UTC
