### ISSUE TITLE
Add CSS variables to component.d.ts props

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#3434] opened 2022-01-20 10:18 UTC
### Describe the problem

This is more of a question than a request: Regarding `sveltekit package`, would it make sense to include CSS variables in the `props` of auto-generated `.d.ts` files?

Currently, a component `src/lib/link.svelte`

```svelte
<script lang="ts">
  export let text: string
  export let href: string
</script>

<a {href}>{text}</a>

<style>
  a {
    color: var(--color, 'red');
  }
</style>
```

generates this `package/test.svelte.d.ts`

```ts
import { SvelteComponentTyped } from "svelte";
declare const __propDef: {
    props: {
        text: string;
        href: string;
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {};
};
export declare type TestProps = typeof __propDef.props;
export declare type TestEvents = typeof __propDef.events;
export declare type TestSlots = typeof __propDef.slots;
export default class Test extends SvelteComponentTyped<TestProps, TestEvents, TestSlots> {
}
export {};
```

### Describe the proposed solution

Since it's possible to do `<Link {text} {href} --color="blue" />`, perhaps it should be

```diff
import { SvelteComponentTyped } from "svelte";
declare const __propDef: {
    props: {
        text: string;
        href: string;
+       '--color?': string;
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {};
};
export declare type TestProps = typeof __propDef.props;
export declare type TestEvents = typeof __propDef.events;
export declare type TestSlots = typeof __propDef.slots;
export default class Test extends SvelteComponentTyped<TestProps, TestEvents, TestSlots> {
}
export {};
```

### Importance

nice to have

### Additional Information

Not sure if this is even the right place to post. Maybe it belongs in [language-tools](https://github.com/sveltejs/language-tools)?

**Comment by dummdidumm** [comment] 2022-01-20 10:51
Duplicate of https://github.com/sveltejs/language-tools/issues/1326

**Closed by dummdidumm** 2022-01-20 10:51 UTC
