### ISSUE TITLE
$page store does not react to certain navigation changes or stores incorrect data

### ISSUE THREAD

**Issue by gyzerok** [sveltejs/kit#12742] opened 2024-10-02 03:24 UTC
### Describe the bug

I've found two bugs with navigating using both `goto` and `pushState` related to `$page` store.

When navigating with `goto` to the same route as the current one even though `$page.state` changes no `$effect` runs on it.

When using `pushState` and passing new url to it you get stuck with `$page.params` pointing to the previous incorrect url.

### Reproduction

Here is the repo: https://github.com/gyzerok/sveltekit-nav-bug

**Bug with `goto` and state:**
1. Go to page `/bug`
2. Click `goto` button
3. No effects run and console log anything (expected console log about state change)
4. Click `Log $page` button and see that actually state in the $page changed

With Svelte I strongly expect that if some state changes the effects are run as a result of this change which is not the case here.

**Bug with `pushState` and url:**
1. Go to page `/bug`
2. Click on `pushState` button
3. You get a log where `params.id: "bug"`, however in the browser url you see `/test`

### System Info

```Shell
@sveltejs/kit: 2.6.1
svelte: 5.0.0-next.260
```

### Severity

serious, but I can work around it

**Comment by eltigerchino** [comment] 2024-10-18 07:18
also related https://github.com/sveltejs/kit/issues/11503

**Comment by gyzerok** [comment] 2024-12-22 05:32
@eltigerchino it looks like the first part of this bug is fixed with https://github.com/sveltejs/kit/pull/13196, however the second one is still in place.

I've updated my repo with the latest version of `svelte` and `sveltekit`.

**Comment by eltigerchino** [comment] 2024-12-23 03:45
closing as duplicate of https://github.com/sveltejs/kit/issues/13200

**Closed by eltigerchino** 2024-12-23 03:45 UTC
Labels: bug
