### ISSUE TITLE
[kit] vitePreprocess + PostCSS = Corrupted svelte-check output. 

### ISSUE THREAD

**Issue by brev** [sveltejs/kit#10767] opened 2023-09-22 03:30 UTC
### Describe the bug

[kit] vitePreprocess + PostCSS = Corrupted svelte-check output. 

When using [`vitePreprocess`][preprocess] with `<style lang="postcss">`, the output of `svelte-check` becomes corrupted:

- Screen was cleared half-way through logging output.
- Extraneous log lines in orange warn color: `(x2)`, `(x3)`, etc. 
    - This ends up being the count of `.svelte` files containing `<style lang="postcss">`.

The trigger of the issue is here:
https://github.com/sveltejs/kit/blob/master/packages/kit/src/exports/vite/index.js#L328

The actual output formatting comes from Vite here:
https://github.com/vitejs/vite/blob/aae3a83b5fb49bbd9f174cfeac66f00483829da4/packages/vite/src/node/logger.ts#L97

[preprocess]: https://kit.svelte.dev/docs/integrations#preprocessors-vitepreprocess

### Reproduction

https://github.com/brev/issue-sveltekit-vite-preprocess-postcss-corrupts-svelte-check-output

### Steps to Reproduce

```sh
git clone https://github.com/brev/issue-sveltekit-vite-preprocess-postcss-corrupts-svelte-check-output.git
cd issue-sveltekit-vite-preprocess-postcss-corrupts-svelte-check-output.git
npm install
npx svelte-check
```

You will see the `svelte-check` output is corrupted:

- Screen was cleared half-way through logging output.
- Extraneous log items in orange warn color: `(x2)`, `(x3)`, etc.

### How Reproduction was Created

```sh
# skeleton, js
npm create svelte@latest issue-sveltekit-vite-preprocess-postcss-corrupts-svelte-check-output
cd issue-sveltekit-vite-preprocess-postcss-corrupts-svelte-check-output/
npm install
npm add --save-dev svelte-check
mkdir -p src/routes/{one,two,three}
cat << EOF | tee src/routes/{one,two,three}/+page.svelte
<p>Hello</p>
<style lang="postcss">p { color: red; }</style>
EOF
```

And add the following to `svelte.config.js`:

```js
import { vitePreprocess } from '@sveltejs/kit/vite'
config = { ...config, preprocess: [ vitePreprocess() ] }
```

### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (4) x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
    Memory: 462.32 MB / 8.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 20.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.7.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.92
    Edge: 117.0.2045.35
    Safari: 16.6
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.25.0
    svelte: ^4.0.5 => 4.2.1
    vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-11-18 09:14
Closing this because I can't reproduce this on the latest versions of SvelteKit and the Vite Svelte plugin

**Closed** 2024-11-18 09:13 UTC
