### ISSUE TITLE
ESLint misses broken imports, incorrectly reports $lib imports as broken or reports nothing at all

### ISSUE THREAD

**Issue by KonradHoeffner** [sveltejs/kit#1560] opened 2021-05-26 13:48 UTC
**Describe the bug**
I had the problem that my ESLint configuration throws errors on `$lib/...` imports so I created a new SvelteKit project to find out how that should be handled. However there I have the opposite problem that ESLint import checking is not working at all, as it doesn't even warn me when an import does not exist.

**Logs and To Reproduce**
There is no output from `eslint` even though 'thisdoesnot/exist.js' is not there and fails in the `npm run dev` step:

```
npm init svelte@next sveltetest
cd sveltetest
npm install
echo "<script>import doesnotexist from 'thisdoesnot/exist.js'</script>" >> src/routes/index.svelte
$ npm run lint      

> ~TODO~@0.0.1 lint
> prettier --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .

Checking formatting...
[warn] package-lock.json
[warn] package.json
[warn] src/routes/index.svelte
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
sveltetest$ eslint --ignore-path .gitignore .

/tmp/sveltetest/src/routes/index.svelte
  3:16  warning  'doesnotexist' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (0 errors, 1 warning)

npm run dev -- --open
> ~TODO~@0.0.1 dev
> svelte-kit dev

  SvelteKit v1.0.0-next.109

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network

Failed to resolve import "thisdoesnot/exist.js" from "src/routes/index.svelte". Does the file exist?

```

**Expected behavior**
1. Correct imports should not be shown as errors, even if they contain `$lib`.
2. Incorrect imports should cause errors.
3. ESLint output should always be visible when calling `npm run lint`.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
  System:
    OS: Linux 5.12 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 7.21 GB / 15.42 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.2.0 - /usr/bin/node
    npm: 7.14.0 - /usr/bin/npm
  Browsers:
    Chromium: 90.0.4430.212
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.109 
    svelte: ^3.34.0 => 3.38.2 
```
- Your browser: Firefox 89

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): The default one from npm init svelte@next, maybe static?
</details>

**Severity**
It is not blocking but annoying.

**Additional context**
I think there are three issues relating to ESLint:

1. When using the SvelteKit default ESLint configuration, ESLint does not notice broken imports at all.
2. When using another ESLint configuration, such as the one from the SvelteKit repository, '$lib' errors that are correct cause errors by ESLint.
3. Even if ESLint notices any errors or warnings, `npm run lint` does not output them. I assume that prettier exits with an error code and stops the second part of the `&&` from being executed.

**Comment by dummdidumm** [comment] 2021-05-26 14:27
Point 3 is "works as designed". Your assumption is correct, and if you want to change that, format the files first or switch the order of invocation.

**Comment by justingolden21** [comment] 2022-05-13 03:03
Is there any fix for this? All of my files are underlined in red with ESLint, and I'd rather not disable the entire rule checking unresolved imports. Would be awesome. Thanks :)

**Comment by iva2k** [comment] 2022-05-28 06:01
+1

**Comment by iva2k** [comment] 2022-05-29 04:39
I added a bit of stuff to the setup to resolve the issue like this:

1. `npm i -D eslint-plugin-import eslint-import-resolver-typescript`
2. Add few lines to `.eslintrc.cjs`:
```cjs
{
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
+    'plugin:import/recommended',
    'prettier'
  ],
  plugins: [
    ...
+    'import'
  ],
  settings: {
+    'import/resolver': {
+      typescript: {}
+    },
    ...
  },
  parserOptions: {
+    project: ['./tsconfig.json', './tsconfig.lint.json'],
+    tsconfigRootDir: './',
    ...
  }
}
```

3. Create file `tsconfig.lint.json` with:
```json
{
  "extends": "./tsconfig.json",
  "include": ["./playwright.config.ts", "./svelte.config.js", "./tests/**/*.ts"]
}
```

4. Add few lines to `tsconfig.json`:
```json
  "compilerOptions": {
    ....
+    "paths": {
+      "$app": ["./.svelte-kit/runtime/app"],
+      "$app/*": ["./.svelte-kit/runtime/app/*"]
+    }
  }
}
```

These changes fix the issue for me. I think those deserve to be added to svelte-kit templates.

**Comment by stalkerg** [comment] 2022-08-19 12:58
1. Because now all `load` functions in separate js files it's very annoying!!!
2. @iva2k not working for me because I am not using TS. 

Does somebody have a solution?

**Comment by stalkerg** [comment] 2022-08-19 14:23
Okay, I solve it for ESLint by `eslint-import-resolver-custom-alias` plugin. This is my config:
```json
    "settings": {
        "import/resolver": {
            "eslint-import-resolver-custom-alias": {
                "alias": {
                    "$lib":"./src/lib",
                    "$app":"./.svelte-kit/runtime/app",
                    "@sveltejs":"./.svelte-kit/dev"
                },
                "extensions": [".js"]
            },
        }
    },
```

I think we should have this in the default template.

**Comment by stalkerg** [comment] 2023-04-27 13:28
It seems like it will be good to write a new `eslint-import-resolver-` to support paths from jsconfig.json

**Comment by stalkerg** [comment] 2023-04-28 11:08
Okey, seems like 'eslint-config-airbnb-base' for some reason breaks the default resolver.

**Comment by stalkerg** [comment] 2023-04-28 12:37
Because new `eslint-plugin-svelte` using a ts parser inside, two rules from `airbnb` break it. It means we should disable it and add a new aliases, my new config works fine and looks like:
```json
  "rules": {
    "import/named": "off",
    "import/no-cycle": "off"
  },
  "env": {
    "browser": true,
    "es2017": true,
    "node": true
  },
  "settings": {
    "import/resolver": {
      "eslint-import-resolver-custom-alias": {
        "alias": {
          "$lib": "src/lib",
          "$app": "node_modules/@sveltejs/kit/src/runtime/app",
          "@sveltejs/kit": "node_modules/@sveltejs/kit/src/exports/index.js"
        },
        "extensions": [
          ".js"
        ]
      }
    }
  }
```

**Comment by dummdidumm** [comment] 2023-04-28 12:45
Are these rules (`import/..`) enabled in the `svelte-create` setup? If yes, then it makes sense to me to add the rules adjustments, else not.

**Comment by stalkerg** [comment] 2023-04-28 12:55
> Are these rules (import/..) enabled in the svelte-create setup?

@dummdidumm  As I can see,, no but it's not fair because the typescript setup does such a test by TS tools. 
Our TS default setup validates imports, but our JS setup, even with ESLint, does not include the `import` plugin by default.

**Comment by stalkerg** [comment] 2023-05-01 01:57
Okey I should say thanks @ota-meshi he find a better setup:
```
  "import/parsers": {
      "svelte-eslint-parser": [".svelte"],
      "espree": [".js"]
  },
  "settings": {
    "import/resolver": {
      "eslint-import-resolver-custom-alias": {
        "alias": {
          "$lib": "src/lib",
          "$app": "node_modules/@sveltejs/kit/src/runtime/app",
          "@sveltejs/kit": "node_modules/@sveltejs/kit/src/exports/index.js"
        },
        "extensions": [
          ".js"
        ]
      }
    }
  }
```

basically, we need an extra parser if we want to use `import` plugin.

**Comment by eltigerchino** [comment] 2024-11-14 03:03
Closing this because I can't seem to reproduce the issue with the latest SvelteKit. $lib aliases are correctly resolved by eslint without the custom alias resolver plugin.

**Closed by eltigerchino** 2024-11-14 03:03 UTC

**Comment by lemonlatte** [comment] 2025-01-13 01:23
@eltigerchino Currently as I test, we still need the custom alias plugin for settling the `$app` namespace. Would it be better to include it directly inside the `.svelte-kit/tsconfig.json` when we call `svelte-kit sync`? 

I am not sure if we should solve this here, in `eslint-plugin-svelte` or just leave it explicit in the `eslint-import-resolver-custom-alias` as the settings [above](https://github.com/sveltejs/kit/issues/1560#issuecomment-1529243642)?

**Comment by eltigerchino** [comment] 2025-01-13 01:32
> @eltigerchino Currently as I test, we still need the custom alias plugin for setting the [`$app/*`](https://svelte.dev/docs/kit/$app-navigation) namespace (with svelte 5). Would it be better to include it directly inside the `.svelte-kit/tsconfig.json` when we call `svelte-kit sync`?
> 
> I am not sure if this should solve this here, in `eslint-plugin-svelte` or just leave it explicit in the `eslint-import-resolver-custom-alias` as the settings [above](https://github.com/sveltejs/kit/issues/1560#issuecomment-1529243642)?

Can you create a new issue with a minimal reproduction?

**Comment by lemonlatte** [comment] 2025-01-13 02:16
> > @eltigerchino Currently as I test, we still need the custom alias plugin for setting the [`$app/*`](https://svelte.dev/docs/kit/$app-navigation) namespace (with svelte 5). Would it be better to include it directly inside the `.svelte-kit/tsconfig.json` when we call `svelte-kit sync`?
> > I am not sure if this should solve this here, in `eslint-plugin-svelte` or just leave it explicit in the `eslint-import-resolver-custom-alias` as the settings [above](https://github.com/sveltejs/kit/issues/1560#issuecomment-1529243642)?
> 
> Can you create a new issue with a minimal reproduction?

Sure. Will do! Thank you.

**Comment by stalkerg** [comment] 2025-01-13 05:49
@lemonlatte I think it should work without TS for jsconifg.json as well.

**Comment by lemonlatte** [comment] 2025-01-14 00:32
I do some test and compare some eslint configs from other projects and eventually figure out it is my own issue to use `airbnb-base` eslint rule in my project. The svelte-eslint itself works perfectly. Sorry for bothering 🙇‍♂️
