### ISSUE TITLE
Infinite refresh running vite with SvelteKit

### ISSUE THREAD

**Issue by mmarchois** [sveltejs/kit#2021] opened 2021-07-27 14:18 UTC
### Describe the bug

I have an inifinite refresh when opened in the browser with vitejs and sveltekit

```
[vite] new dependencies found: js-cookie, updating...
[vite] ✨ dependencies updated, reloading page...
```

### Reproduction

- Install dependencies with npm install
- Start app using npm run dev or yarn dev
- Open the app in a browser

### System Info

```shell
vite version: 2.4.3
sveltekit: 1.0.0-next.137
@sveltejs/vite-plugin-svelte: 1.0.0-next.14
Operating System: ubuntu
Node version: v14.17
Package manager: npm 7.20.1
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment] 2021-07-27 14:22
What URL are you visiting to see the app? I'm seeing this refreshing with http://127.0.0.1:3000/ but it works fine with http://localhost:3000/

**Comment by mmarchois** [comment] 2021-07-27 14:24
I'm trying both, randomly it works :(

**Comment by Conduitry** [comment] 2021-07-27 14:27
2.4.4 is the most recent version of Vite now, by the way, not 2.4.3.

**Comment by mmarchois** [comment] 2021-07-27 14:29
I have setup the project 4 days ago with the command `npm init svelte@next `. I'll try vite 2.4.4.

**Comment by mmarchois** [comment] 2021-07-27 14:33
@Conduitry i have `npm ERR! notarget No matching version found for vite@2.4.4.`

**Comment by dominikg** [comment] 2021-07-28 12:07
@mmarchois  i noticed you have filed a similar issue on vites repository https://github.com/vitejs/vite/issues/4406  please don't cross-post or at least mention the other issues if you do. Not everyone is following both repos and missing information from one side may cause extra work.
 
If you are not sure where to file an issue, you can ask on [svelte discord](https://svelte.dev/chat)

**Comment by dominikg** [comment] 2021-07-28 13:11
Can't reproduce with `pnpm init svelte@next` 

Please provide a repository and detailed steps on how to reproduce the issue if possible.
It would also help if you posted debug logs from while it's happening. 
To enable debug logging, start it like this: `DEBUG="vite:*" npm run dev`

**Comment by Flave** [comment] 2021-08-03 10:40
I'm experiencing the same issue. I have no possible explanation but it occurs after a clean install with `npm init svelte@next my-app` and then installing and importing `d3-scale` (`import {scaleLinear} from 'd3-scale';`) into `src/routes/index.svelte`. I tried other node modules but so far only `d3-scale` caused this issue.

**Comment by dominikg** [comment] 2021-08-03 19:57
adding d3-scale to a fresh skeleton project's index.svelte does not cause ininite reload for me, it causes a http 500 error. 

@Flave , @mmarchois 

Please provide a link to a repository where this problem is reproducible. It would also help if you provided logs of when it's happening. You can use `DEBUG="vite:*" npm run dev` to start the devserver and don't forget to also include browser console output.

this may be a vite issue, see  https://github.com/vitejs/vite/issues/4463

**Comment by mmarchois** [comment] 2021-08-06 10:30
it is noted that the production build works perfectly...

**Comment by dominikg** [comment] 2021-08-06 10:47
504 hints at a network setup issue though i wonder how that could happen on localhost.

I also find it hard to believe that you don't have access to console logs or browser logs during dev. Unless you start to provide the information i've asked for twice, i'm not going to respond here anymore.

**Comment by frederikhors** [comment] 2021-08-07 15:09
Same here. If you add a dep or event change package.json or package-lock.json manually it re-compile all "temp" files.

For it to work I need to stop and restart npm run dev many times!

**Comment by mmarchois** [comment] 2021-08-09 08:20
@dominikg For privacy reasons I can't share code :( 
It's like the nodejs event loop is not responding anymore.
I can share the logs of the DEBUG="vite:*" npm run dev command

**Comment by mmarchois** [comment] 2021-08-09 08:27
We always have this kind of logs `dependencies updated, reloading page`

```
10:25:53 [vite] new dependencies found: uuid, rfplayer-plugin-hls-adapter, rfplayer-plugin-html5-sound-adapter/src/index, rfplayer-plugin-live-api, rfplayer-plugin-kirby, rfplayer-plugin-smarttag, rfplayer/dist/rfplayer, updating...
10:25:53 [vite] ✨ dependencies updated, reloading page...
```

**Comment by frederikhors** [comment] 2021-08-09 09:14
> We always have this kind of logs `dependencies updated, reloading page`
> 
> ```
> 10:25:53 [vite] new dependencies found: uuid, rfplayer-plugin-hls-adapter, rfplayer-plugin-html5-sound-adapter/src/index, rfplayer-plugin-live-api, rfplayer-plugin-kirby, rfplayer-plugin-smarttag, rfplayer/dist/rfplayer, updating...
> 10:25:53 [vite] ✨ dependencies updated, reloading page...
> ```
> 
> Does this have anything to do with https://vitejs.dev/guide/dep-pre-bundling.html

Same here. I need to stop server many times before I can work. Everytime I change a dependency. Very bad.

**Comment by elfakamal** [comment] 2021-08-09 16:51
@dominikg Same issue here, we have so many 504 errors, it must come from the fact that the event loop is blocked or something, anyway, we make requests to the server any more.

when we run it in production mode (`svelte-kit build`), it works.

**Comment by ntchou** [comment] 2021-08-09 22:14
Same here. I try to stop and start server many times. It doesn't work. Like @elfakamal in production mode it works. With `DEBUG=vite:*` i don't have any more information about the issue

**Comment by anglol** [comment] 2021-08-10 08:41
Hi,
Same problem here. The application keeps reloading and updating new dependencies with each `npm run dev`. In the browser, I have infinite loading that ends in 504 error.

Everything is working in `npm run build` / `npm run preview`

**Comment by frederikhors** [comment] 2021-08-10 09:18
`1.0.0-next.146` fixes the issue for me (Windows 10).

I think that now I will cry with happiness.

**Comment by frederikhors** [comment] 2021-08-10 09:19
@mmarchois try and close this issue.

**Comment by mmarchois** [comment] 2021-08-10 09:36
@frederikhors Same issue with 146. To make it work, I need to comment out the import of an external library

**Comment by frederikhors** [comment] 2021-08-10 09:37
@mmarchois with 146 it works for me. I'm crying with happiness.

Can you post your svelte.config.js?

**Comment by mmarchois** [comment] 2021-08-10 09:39
@frederikhors my svelte.config.js : 
```
import preprocess from 'svelte-preprocess';
import svelteKitNodeAdapter from '@sveltejs/adapter-node';
import postcssImport from 'postcss-import';
import postcssMixins from 'postcss-mixins';
import postcssNested from 'postcss-nested';
import postcssCustomMedia from 'postcss-custom-media';
import postcssCustomProperties from 'postcss-custom-properties';
import autoprefixer from 'autoprefixer';
import postcssPresetEnv from 'postcss-preset-env';
import postcssGlobalNested from 'postcss-global-nested';
import cssnano from 'cssnano';
import precompileIntl from 'svelte-intl-precompile/sveltekit-plugin.js';

import { resolve } from 'path';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: preprocess({
    postcss: {
      plugins: [
        postcssImport(),
        postcssMixins,
        autoprefixer,
        postcssCustomMedia({
          importFrom: [
            './src/assets/styles/__customMedia.css',
          ]
        }),
        postcssCustomProperties(),
        postcssPresetEnv({
          stage: 3,
          features: {
            'nesting-rules': true,
          },
        }),
        postcssNested(),
        postcssGlobalNested(),
        cssnano({
          preset: 'default',
        }),
      ],
    }
  }),
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
    adapter: svelteKitNodeAdapter(),
    vite: {
      plugins: [
        precompileIntl('locales'),
      ],
      resolve: {
        alias: {
          assets: resolve('./src/assets'),
          components: resolve('./src/components'),
          helpers: resolve('./src/helpers'),
          lib: resolve('./src/lib'),
          auth: resolve('./src/auth'),
          pages: resolve('./src/pages'),
          providers: resolve('./src/providers'),
          repositories: resolve('./src/repositories'),
          services: resolve('./src/services'),
          src: resolve('./src'),
          stores: resolve('./src/stores'),
        }
      }
    }
  },
};

export default config;
```

**Comment by frederikhors** [comment] 2021-08-10 09:42
I don't know.

Can you please remove everything (node_modules, package-lock.json, svelte dirs)?

You can use `git clean -fdx` (please be aware this remove everything not commited).

**Comment by mmarchois** [comment] 2021-08-10 10:09
I remove all of them, but nothing change :( 
Can you share your svelte config ?

**Comment by frederikhors** [comment] 2021-08-10 10:46
It is simple:

```js
import preprocess from "svelte-preprocess";
import adapter from "@sveltejs/adapter-static";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: preprocess(),

  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: "#svelte",

    adapter: adapter({
      fallback: "200.html",
    }),

    vite: {
      optimizeDeps: {
        include: ["broadcast-channel"],
      },
    },

    ssr: false,

    appDir: "app",
  },
};

export default config;
```

**Comment by mmarchois** [comment] 2021-08-10 10:54
we removed an external dependency and the project build again. I'm going to dig into this to find out why (esm?)

**Comment by frederikhors** [comment] 2021-08-10 10:55
I don't know but 146 fixes all my issues! :)

**Comment by niketpathak** [comment] 2021-08-12 14:34
When I delete the folders `node_modules/.vite` as well as `.svelte-kit`, and then rebuild, it seems to work again. However, I am required to do this each time the inifinite refresh occurs which is quite often and which is pretty frustrating too!

**Comment by frederikhors** [comment] 2021-08-12 17:23
@niketpathak this was before 146 for me.

**Comment by niketpathak** [comment] 2021-08-13 09:05
@frederikhors , I am already on `SvelteKit v1.0.0-next.146` and it still happens for me.

**Comment by frederikhors** [comment] 2021-08-13 09:22
Windows or what? Node version?

**Comment by niketpathak** [comment] 2021-08-13 13:52
I'm on Ubuntu 20.04 running Node 14.17 LTS

**Comment by bluwy** [comment] 2021-08-13 14:12
Please set up a [repro](https://stackoverflow.com/help/minimal-reproducible-example) to save everyone's time, as requested by dominik many times.

**Comment by niketpathak** [comment] 2021-08-13 14:25
yep, gonna do that! Thanks!

**Comment by niketpathak** [comment] 2021-08-18 15:35
hello, a quick update, I tried to create a new repo to try to reproduce the issue, however, I wasn't able to reproduce it. Also, after having updated to `SvelteKit v1.0.0-next.151`, the problem seems to have gone away! So I won't be digging deeper into it anymore!

**Comment by benmccann** [comment] 2021-08-20 16:48
Given that there is not reproduction for this issue and multiple people have reported the problem solved I'm going to close this. If you're still hitting the issue please file a new issue with a reproduction. There's no way for us to investigate this bug otherwise

**Closed by benmccann** 2021-08-20 16:48 UTC
Labels: vite, pending clarification
