### ISSUE TITLE
Wrong hydration for @html, rendering text with different values on client and server

### ISSUE THREAD

**Issue by epavanello** [sveltejs/kit#11053] opened 2023-11-16 15:26 UTC
### Describe the bug

I have a simple component that renders Materialicon icons. 
With SSR enabled, if I render an icon on the backend that needs to change upon hydration on the frontend, that doesn't happen.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-pj9dut?file=src%2Froutes%2Ftest.svelte

### System Info

```Shell
any sveltekit version
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment] 2023-11-16 15:29
Closing as duplicate of https://github.com/sveltejs/svelte/issues/9057

**Closed by gtm-nayan** 2023-11-16 15:29 UTC
