### ISSUE TITLE
workspace dependencies are incorrectly bundled by vite

### ISSUE THREAD

**Issue by rsweeney21** [sveltejs/kit#8935] opened 2023-02-07 22:37 UTC
### Describe the bug

Given the following monorepo setup

```
monorepo_root/
├─ application/
├─ packages/
│  ├─ package1/
│  ├─ package2/
```

And the following package.json in application

```
"dependencies": {
    "package1": "workspace:*",
    "package2": "workspace:*",
},
```

Dependencies of package1 and package2 are not marked as external as they should be and instead are bundled by the server rollup build. 

adapter-node excludes direct dependencies listed in the package.json of `application` by adding them to the "external" list in the rollup config it uses, which is great! But it does not exclude transitive dependencies, i.e. dependencies listed in the package.json for package1 and package2. Relevant code below

```
const bundle = await rollup({
	input: {
		index: `${tmp}/index.js`,
		manifest: `${tmp}/manifest.js`
	},
	external: [
		// dependencies could have deep exports, so we need a regex
		...Object.keys(pkg.dependencies || {}).map((d) => new RegExp(`^${d}(\\/.*)?$`))
	],
	plugins: [nodeResolve({ preferBuiltins: true }), commonjs(), json()]
});
```

### Reproduction

https://github.com/rsweeney21/adapter-node-rollup-bug

1. Clone the repo
2. pnpm install
3. cd app
4. npm run build
5. Search app/.svelte-kit for "ioredis"

You'll find the ioredis module bundled in one of the files in the server build output.

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.58 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-node: ^1.1.7 => 1.1.7 
    @sveltejs/kit: ^1.5.0 => 1.5.0 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.1
```

### Severity

serious, but I can work around it

### Additional Information

The workaround is to add all the transitive dependencies (the dependencies of package1 and package2) as dependencies of application. It breaks encapsulation of the packages.

**Comment by rsweeney21** [comment] 2023-02-07 23:33
Another potential workaround is to add package1 and package2 to the list of external packages in rollupOptions in your vite config. This might even be the "right way". 

If it is, then a hint about this in the adapter-node docs would be quite useful.

```
const config = {
    plugins: [sveltekit()],
    test: {
        include: ['src/**/*.{test,spec}.{js,ts}']
    },
    build: {
        rollupOptions: {
            external: ["package1", "package2"]
        }
    }
};
```

**Comment by dummdidumm** [comment] 2023-02-08 10:55
This sounds like a Rollup bug to me. I would've expected Rollup to not look at the transitive dependencies. Maybe it has to do with the `workspace:*` value?

**Comment by rsweeney21** [comment] 2023-02-09 03:08
I realized that what I wanted is to treat the packages in my monorepo (package1 and package 2) as external during server build and NOT as external during client build. The server code doesn't need to be bundled and can resolve my local packages from the sym links in node_modules. The client code would need it bundled.

Vite offers a way to customize the config based on whether you are building server (SSR) or client. But it doesn't work because of the way the SvelteKit vite plugin works. (It overwrites the SSR setting in vite config and then internally spawns separate server and client builds.) 

So in order to make this work, I had to create a vite plugin that runs after the sveltekit plugin. Here it is

```
/// <reference types="vitest" />
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig, type UserConfig, type Plugin } from 'vite';

export default defineConfig(() => {
    const config: UserConfig = {
        plugins: [sveltekit(), externalizePackages],
        test: {
            include: ['src/**/*.{test,spec}.{js,ts}']
        }
    };

    return config;
});

const externalizePackages: Plugin = {
    name: 'externalize-packages',

    config: (config, { command }) => {
        if (command === 'build' && config.build?.ssr) {
            return {
                build: {
                    rollupOptions: {
                        external: [/@facet\/.*/]
                    }
                }
            };
        }
    }
};

```

**Comment by benmccann** [comment] 2023-03-02 22:37
I don't have any ideas off the top of my head. I'd recommend filing an issue with Vite. I've sent a PR describing how to do so here: https://github.com/sveltejs/kit/pull/9292

**Comment by rsweeney21** [comment] 2023-03-03 01:13
Vite treats dependencies in the workspace as source code.

For client builds this is okay because the source file and all its dependencies are bundled so they can be served to the client.

For server builds this is not desirable because bundling server only source files and their dependencies (ioredis, sharp, etc) often doesn't work. It's better to just leave dependencies in node_modules and modules located in the workspace in their original location.

Vite provides a way to control this behavior depending on whether you are building for server or client. I described this in my comment here: https://github.com/sveltejs/kit/issues/8935#issuecomment-1423558779

So I think if you filed this issue with Vite, they would say to just use the ```ssr``` flag change the rollup options for your SSR build. The problem for SvelteKit users is that its not possible to customize vite config for ssr builds. ssr is always false in defineConfig.

And if you use ```ssr.external```, then you lose the benefit of HMR in dev mode.

**Comment by Rich-Harris** [comment] 2023-03-03 01:18
HMR aside, why should `external: [some_workspace_dependency]` be ignored? I understand why treating workspace dependencies as source code makes sense in the common case, but if I'm _explicitly_ telling Vite to keep it external, it feels like a bug if it just ignores me

**Comment by rsweeney21** [comment] 2023-03-03 01:42
Yes, that would be a bug. It worked at one point because that was the workaround we used back in September.

Sorry, I thought you were suggesting to file a bug in vite for the original issue I reported.

**Comment by benmccann** [comment] 2023-03-03 02:35
> So I think if you filed this issue with Vite, they would say to just use the ssr flag change the rollup options for your SSR build.

We don't disallow you from setting `ssr.external`. You can't change `build.ssr`, but neither should you need to in order to solve this issue.

> And if you use `ssr.external`, then you lose the benefit of HMR in dev mode.

You can conditionally set it only in `build` mode: https://vitejs.dev/config/#conditional-config

**Comment by Rich-Harris** [comment] 2023-03-03 02:37
> We don't disallow you from setting `ssr.external`

Try the repro — it has no effect

**Comment by benmccann** [comment] 2023-03-03 03:27
Ah, yeah, that sounds like a Vite bug then.

**Comment by bluwy** [comment] 2023-03-03 08:44
I checked what Vite is doing, and the repro setup is quite specific that's triggering this issue. When setting `ssr.external: ['lib']`, Vite will externalize all root and subpath exports. BUT because "subpath exports" is implicitly given, Vite does another check to make sure it's actually externalizable before doing so, preventing potential runtime errors.

What it does is [this part](https://github.com/vitejs/vite/blob/38ce81ceb86d42c27ec39eefa8091f47f6f25967/packages/vite/src/node/ssr/ssrExternal.ts#L172-L178) and down-the-chain [this part](https://github.com/vitejs/vite/blob/38ce81ceb86d42c27ec39eefa8091f47f6f25967/packages/vite/src/node/plugins/resolve.ts#L781-L789), as shown in the second link, subpath exports is only externalized if it export JS.

In the repro, the workspace package is [exporting raw TS](https://github.com/rsweeney21/adapter-node-rollup-bug/blob/7f5cbca525a769b756e89eabef07a5d9ba5aab4e/packages/lib/package.json#L7-L8), so Vite is safeguarding this case to prevent runtime errors, which would happen if it eventually externalizes.

So I think Vite is working fine here. Changing to JS fixes it for me: [Stackblitz](https://stackblitz.com/edit/github-v3eef9?file=app%2F.svelte-kit%2Foutput%2Fserver%2Fentries%2Fpages%2F_page.server.ts.js). Though if it's intentional to externalize still, you can pass `ssr.external: ['lib/database']` instead.

**Comment by Rich-Harris** [comment] 2023-03-03 23:46
Ah, that makes sense — thanks. It sounds like everything is working as intended, even if it was tricky to diagnose. I'm not sure there's anything we could be doing differently here so I'm going to close this issue.

**Closed by Rich-Harris** 2023-03-03 23:46 UTC
Labels: vite
