### ISSUE TITLE
Esbuild Options on Adapters

### ISSUE THREAD

**Issue by yekta** [sveltejs/kit#5756] opened 2022-07-29 19:41 UTC
### Describe the problem

There is a 3rd party package I'm using which errors out with the Cloudflare adapter and Netlify adapter with the edge option.

The 3rd party package itself is at fault, but I can fix it with `define` option on esbuild. Unfortunately I can't do that currently with the adapters because they aren't taking esbuild options.

I saw Rich's comment here: https://github.com/sveltejs/kit/pull/4639. I don't know how can I achieve this without having access to the esbuild options currently. So only thing I can think of is forking the adapters and making a custom version myself which can take esbuild options.

### Describe the proposed solution

The ability to pass esbuild options on adapters.

### Alternatives considered

Making my own fork.

### Importance

would make my life easier

**Comment by benmccann** [comment] 2022-07-30 02:39
Closing as duplicate of https://github.com/sveltejs/kit/issues/3733

**Closed by benmccann** 2022-07-30 02:39 UTC
