### ISSUE TITLE
linting shows error on app.d.ts on newly created SvelteKit project

### ISSUE THREAD

**Issue by opensas** [sveltejs/kit#3994] opened 2022-02-18 15:01 UTC
### Describe the bug

when I create a new project `npm run lint` shows error from the `src/app.d.ts` file

### Reproduction

```shell
$ npm init svelte@next test-lint
✔ Which Svelte app template? › Skeleton project
✔ Use TypeScript? … Yes
✔ Add ESLint for code linting? … Yes
✔ Add Prettier for code formatting? … Yes

$ cd test-lint/

$ npm install

$ npm run format

> test-lint@0.0.1 format
> prettier --ignore-path .gitignore --write --plugin-search-dir=. .

$ npm run lint

> test-lint@0.0.1 lint
> prettier --ignore-path .gitignore --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .

Checking formatting...
All matched files use Prettier code style!

/home/sas/devel/apps/glas-it/apps/wingback/tmp/test-lint/src/app.d.ts
   6:12  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface
   8:12  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface
  10:12  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface
  12:12  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface

✖ 4 problems (4 errors, 0 warnings)
```

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 407.92 MB / 15.08 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Brave Browser: 98.1.35.101
    Chrome: 98.0.4758.102
    Firefox: 97.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.278 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

annoyance

**Comment by ignatiusmb** [comment] 2022-02-18 15:13
Duplicate of #3839

**Closed by ignatiusmb** 2022-02-18 15:13 UTC
