### ISSUE TITLE
Type of `request` property in `RequestEvent` is incorrect

### ISSUE THREAD

**Issue by aberndtiteratec** [sveltejs/kit#3681] opened 2022-02-02 14:18 UTC
### Describe the bug

When I try to call `getReader()` on `event.request.body` in a `handle` function, I receive an error: `response.body.getReader is not a function`, even though autocompletion suggests that it should be possible.
![autocomplete](https://user-images.githubusercontent.com/92023279/152146018-4c3528dc-64ab-4903-a520-096254681c5f.png)

### Reproduction

See the log outputs after clicking on `Test Request`
https://stackblitz.com/edit/svelte-kit-p42fqc?file=src/hooks.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz  
    Memory: 18.11 GB / 31.72 GB
  Binaries:
    Node: 16.11.1 - C:\Program Files\nodejs\node.EXE        
    npm: 8.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.67 => 1.0.0-next.67 
    @sveltejs/kit: ^1.0.0-next.251 => 1.0.0-next.251        
    svelte: ^3.46.3 => 3.46.3
```

### Severity

annoyance

**Comment by Rich-Harris** [comment] 2022-02-02 16:14
Yep, this is an unfortunate quirk of `node-fetch`. Handling streaming bodies is a high priority TODO, but we haven't quite figured out how to make the `ReadableStream` interface available on `node-fetch` `Request` bodies https://github.com/sveltejs/kit/issues/3419

**Comment by aberndtiteratec** [comment] 2022-02-03 12:26
If this is a problem with node-fetch, I think this type is supposed to come from node-fetch rather than from the fetch api

![sveltekit](https://user-images.githubusercontent.com/92023279/152342343-98399482-0fbb-4a81-b4c3-592581a43101.png)

**Comment by Rich-Harris** [comment] 2022-02-03 13:30
We don't want to use `node-fetch` types because while `node-fetch` is used in dev, preview and the netlify/node/vercel adapters, it's not used universally (e.g. Deno and Cloudflare Workers expose a more standards-compliant `fetch` interface). Node itself now has `fetch` behind a flag. Instead, we need to make interfaces like `getReader` available somehow

**Comment by jeremybradbury** [comment] 2022-03-24 04:52
FWIW `node-fetch` is garbage and is often the cause of issues with libraries like Directus, whose maintainers often argue "axios is too large". Well for those humans, there's Request which works fantastically with a simple JS wrapper, running in a compiled C++ binary bundled with node, it's not only not a dependency, it's not even really JS.

**Comment by Rich-Harris** [comment] 2022-04-05 01:41
The value of using `node-fetch` isn't the implementation, it's the standard, which allows developers to use the same code in Node, Deno, Cloudflare Workers, browsers, and so on. I'm sure your wrapper is great, but it can't do that.

We'll continue to use `node-fetch` until `fetch` is available natively in Node without a flag.

**Comment by jeremybradbury** [comment] 2022-04-19 00:59
>  I'm sure your wrapper is great, but it can't do that.

no it cannot, not without some modifications and planning. but in about 50 lines it handles any get/post binary/files/json/text streams or files of any kind.

anyway you'll likely need your own tooling for processing & rendering streaming (binary) results from a firehose, which I know is a highly anticipated feature.

I personally don't think `node-fetch` is close enough to the browser fetch APIs to be of much benefit, all `fetch` patterns have much to be desired without using some sort of wrapping, even what's in node. 

anyway, i only offered an idea that solves 2 (or more) problems. 

starting with a possible new feature & later considering it for replacement after some testing and API work, seems like a logical path.

> We'll continue to use `node-fetch` until `fetch` is available natively in Node without a flag.

for sure, use what you think is best. i'm just some dude on the internet. 

i wasn't expecting you to use my code, just explain what I meant by pointing at it like a document.

sorry for the tangent which was mostly unrelated to this particular thread, but also a possible solution here.

**Comment by Rich-Harris** [comment] 2022-04-25 13:32
Closing this in favour of #3419

**Closed by Rich-Harris** 2022-04-25 13:32 UTC
