### ISSUE TITLE
Prerender bug

### ISSUE THREAD

**Issue by AlexRMU** [sveltejs/kit#8246] opened 2022-12-22 13:52 UTC
### Describe the bug

When kit tries to create a new process [here](https://github.com/sveltejs/kit/blob/8380cee7d0d8907ff12b901f38ff4f5e919cec0c/packages/kit/src/exports/vite/index.js#L535), an error appears immediately.
If you add all the listeners on it, it turns out like this:
```
spawn
disconnect
exit(4294967295)
```
If you start the process manually with the necessary parameters, it will work endlessly.
Perhaps the problem is that `pnpm` is being used.

### Reproduction

-

### Logs

```Shell
[vite-plugin-sveltekit-compile] Prerendering failed with code 4294967295
error during build:
Error: Prerendering failed with code 4294967295
    at ChildProcess.<anonymous> (file:///D:/.../node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/exports/vite/index.js:568:36)
    at ChildProcess.emit (node:events:539:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
    Memory: 14.61 GB / 31.88 GB
  Binaries:
    Node: 16.15.0 - D:\Program Files\nodejs\node.EXE
    npm: 8.15.1 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: 1.0.0 => 1.0.0
    @sveltejs/kit: 1.0.1 => 1.0.1
    svelte: ^3.55.0 => 3.55.0
    vite: ^4.0.3 => 4.0.3
```

### Severity

blocking all usage of SvelteKit

**Comment by AlexRMU** [comment] 2022-12-22 14:11
[They](https://stackoverflow.com/a/73908658/13033436) write that this error appears because of WSL, but what does this have to do with it?

**Comment by AlexRMU** [comment] 2022-12-22 14:15
> Are you using WSL, incidentally?

No, I just upgraded to 1.0.0, launched exactly the same build command that worked before, and here it is.

**Comment by AlexRMU** [comment] 2022-12-22 14:37
I think I got it.
I have a large env, and when the values are normalized they take a similar form: `"APPDATA":"C:\\\\Users\\\\User\\\\AppData\\\\Roaming"`.
As a result, this whole string has a length of 12000 characters and it is passed simply as an argument.
Maybe it's too much.

**Comment by Conduitry** [comment] 2022-12-22 15:00
Closing as duplicate of #8081 then.

**Closed** 2022-12-22 15:00 UTC
Labels: awaiting submitter

**Comment by AlexRMU** [comment] 2022-12-23 14:13
The error is thrown here:
https://github.com/sveltejs/kit/blob/8380cee7d0d8907ff12b901f38ff4f5e919cec0c/packages/kit/src/core/prerender/prerender.js#L372
The `catch` can't catch it.
File `D:/folder/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/core/prerender/prerender.js` imports the manifest from `D:/folder/.svelte-kit/output/server/manifest-full.js` and tries to run `() => import("./nodes/0.js")`.
Inside this function cwd = `D:/folder/`, it tries to import the `D:/folder/nodes/0.js` file (I tested it by changing this function).
The result is this error:
```
[vite-plugin-sveltekit-compile] Prerendering failed with code 4294967295
error during build:
Error: Prerendering failed with code 4294967295
    at ChildProcess.<anonymous> (file:///D:/folder/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.3/node_modules/@sveltejs/kit/src/exports/vite/index.js:575:36)
    at ChildProcess.emit (node:events:539:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn vite ENOENT
    at notFoundError (D:\folder\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (D:\folder\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (D:\folder\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (D:\folder\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn vite',
  path: 'vite',
  spawnargs: [ 'build' ]
}
```

**Comment by AlexRMU** [comment] 2022-12-24 06:25
@Conduitry
Probably it needs to be reopened

**Comment by AlexRMU** [comment] 2022-12-24 09:44
Very strange.
In .env there is a similar variable:
```env
VAR="qwe123}_-[]:#"
```
Everything works fine in dev, dotenv parses everything correctly. 
But the above error still appears.
However, if these characters are escaped, the error will disappear.
Probably related to https://github.com/motdotla/dotenv/issues/633.
But it is unclear why the error appears, and even such.

**Comment by AlexRMU** [comment] 2023-01-07 16:10
The problem appears after the update and disappears after deleting the modules folder and reinstalling (using pnpm).
