### ISSUE TITLE
Errors from within +layout.js are not being caught and passed to +error

### ISSUE THREAD

**Issue by bdanoit** [sveltejs/kit#6002] opened 2022-08-17 21:43 UTC
### Describe the bug

Errors thrown from within +layout.js are not being caught and passed to +error.svelte

If I throw the error from +page.js it is being caught and passed to +error.svelte

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-f1qmuw?file=README.md

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.418 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment] 2022-08-17 21:47
Sounds like a duplicate of #3068. It's not immediately apparent what should happen when your top-level layout `load` throws an error, since that data is needed to render that layout, which is needed to render that top-level `+error.page`

**Closed by Conduitry** 2022-08-17 21:47 UTC
