### ISSUE TITLE
Specify Vite mode in `svelte-kit build`

### ISSUE THREAD

**Issue by edenworky** [sveltejs/kit#4584] opened 2022-04-10 10:59 UTC
### Describe the problem

I want to be able to set build mode. In Vite you can do `vite build --mode some-mode`, but this can currently only be set in `svelte.config.js`.

### Describe the proposed solution

Support `svelte-kit build --mode some-mode`

### Alternatives considered

Have a separate `svelte.config.js` just for the tests, but I can't find a way to point `svelte-kit build` to it

### Importance

i cannot use SvelteKit without it

### Additional Information

This makes testing very difficult since there's no simple way to detect that the app is running in test env

**Comment by jasonlyu123** [comment] 2022-04-10 11:12
Alternatively, you can use an environmental variable like `VITE_MODE=some-mode svelte-kit build`(or `cross-env VITE_MODE=some-mode svelte-kit build` to cover windows). And use it in `svelte.config.js`:

```ts
export default {
  kit: {
    vite: {
      mode: process.env.VITE_MODE
    }
  }
}
```

**Comment by bluwy** [comment] 2022-04-10 13:24
Duplicate of #1258

**Closed by bluwy** 2022-04-10 13:24 UTC
