### ISSUE TITLE
Pass cookie from `www.my.domain` to `api.my.domain` during SSR

### ISSUE THREAD

**Issue by rohanrajpal** [sveltejs/kit#6335] opened 2022-08-27 06:52 UTC
### Describe the bug

The current rule for passing cookies in SSR is

```
// allow cookie passthrough for "same-origin"
// if SvelteKit is serving my.domain.com:
// -        domain.com WILL NOT receive cookies
// -     my.domain.com WILL receive cookies
// -    api.domain.dom WILL NOT receive cookies
// - sub.my.domain.com WILL receive cookies
// ports do not affect the resolution
// leading dot prevents mydomain.com matching domain.com
```
[Link to code](https://github.com/sveltejs/kit/blob/621e07106045f7348587c5a1e940b3720b3d029a/packages/kit/src/runtime/server/page/load_node.js#L197)

This logic works great except for this test case:

Our SvelteKit server is hosted on `www.meetspur.app`
Backend is hosted on `api.meetspur.app`

_I guess we should make an exception for `www.` since it's not really a subdomain?_

One hack is to host my app on `meetspur.app` & redirect all traffic from `www.meetspur.app` to `meetspur.app.` I don't want to do this as:
My frontend is hosted on Vercel & Vercel recommends EXACTLY the opposite thing (redirect meetspur.app -> www.meetspur.app). So the hack does not seem to be a good practice in general.

### Reproduction

Host SvelteKit on `www.my.domain`

Host Backend on `api.my.domain`

You can pass cookies in SSR from `my.domain`->`api.my.domain` but not from `www.my.domain` -> `api.my.domain`

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 343.89 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.16.0 - ~/.local/share/nvm/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.local/share/nvm/v16.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 104.0
    Safari: 15.6.1
```

### Severity

blocking an upgrade

### Additional Information

This issue is blocking me from using cookies both on client and server side.

**Comment by Conduitry** [comment] 2022-08-27 07:02
This is a duplicate of #4750.

**Closed by Conduitry** 2022-08-27 07:02 UTC
