### ISSUE TITLE
`set-cookie` header is ignored by `fetch()` inside load function

### ISSUE THREAD

**Issue by Nickersoft** [sveltejs/kit#7467] opened 2022-11-01 23:26 UTC
### Describe the bug

Hey folks,

Not sure if this is by design or not, but a rather annoying issue I've encountered is that all `set-cookie` headers returned from the `fetch` method inside `load()` are ignored and do not store a cookie on the browser. When I use the non-load `fetch` (global fetch) inside my `+layout.ts` file, it works perfectly. 

However, I'm currently using URQL and its `authExchange` feature to make authenticated requests to my API, then refresh the access token when it expires. Unfortunately:

- Using the `fetch` inside `load()` makes the credentialed request correctly, but fails to set the new access token cookie when a response is returned
- Using the global `fetch` can't make _any_ credentialed request without manually passing in the cookies, yet it will assign the new access token cookie correctly if it receives a response

I would try passing my cookies in as layout data from the `+layout.server.ts` to the `+layout.ts` and _then_ pass a custom `fetch` function to URQL that manually assigns the cookies, _but_ I'm not sure if this could lead to stale cookies (I don't know when the `+layout.server.ts`'s `load()` function would run again). 

I've also tried using `hooks.server.ts` to manually assign the cookies from `set-cookie` to the `event` object, but I think `event` must be a copy or immutable because it doesn't make a difference.

Hopefully I'm making sense. I know it's a bit confusing! I've scoured the docs and the issues here and can't find anything to point me in the right direction. 

### Reproduction

I created a small reproduction on the `nickersoft/set-cookie` branch of [this repo](https://github.com/nickersoft/sveltekit-bugs/tree/nickersoft/set-cookie). Once you install deps with (P)NPM, just run `node server.js` in one terminal, and then `pnpm dev` in another. After opening the site, if you check the developer tools you'll see no cookie is set, _however_ in the terminal the response is logged, which includes a `set-cookie` header that attempts to set an `access_token` cookie to `hello_world`.

### System Info

```Shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 101.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.asdf/installs/nodejs/18.9.0/bin/node
    npm: 8.19.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 107.1.45.116
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.531 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.2.2 => 3.2.2
```

### Severity

serious, but I can work around it

### Additional Information

The only current way around this is not trying to server load my GraphQL queries in my app. It causes the layout to jump once it loads data, which is unfortunately not a great UX.

**Comment by dummdidumm** [comment] 2022-11-07 16:04
Is your API on the same domain? If not, cookies are not forwarded due to security considerations (as in the reproducible, the port means it's a different origin). You can forward them manually though.

That said, I'm wondering if our logic is too strict here. We already have some logic that forwards the cookies in case the domain is the same or a sub domain. Should we do the same the other way around and forward response cookies, too, in that case?

**Comment by Nickersoft** [comment] 2022-11-07 18:09
So it's not (well, my app is under an `app.` subdomain and my API is under `api.`), but I account for this in my `hooks.server.ts` file, as recommended by the documentation:

```typescript
export const handleFetch: HandleFetch = async ({ fetch, request, event }) => {
	if (request.url.startsWith(endpoints.api)) {
		request.headers.set('cookie', event.request.headers.get('cookie') ?? '');
	}

	return fetch(request);
};
```

So my cookies are actually being sent to the API. However, my API is returning with a `set-cookie` header, which the server-side `fetch` ignores, not setting my access tokens on my browser. I tried accounting for this with something like this:

```typescript
export const handleFetch: HandleFetch = async ({ fetch, request, event }) => {
	if (request.url.startsWith(endpoints.api)) {
		request.headers.set('cookie', event.request.headers.get('cookie') ?? '');
	}

	const res = await fetch(request);
	
	event.setHeaders({ cookie: res.headers.get('set-cookie') ?? '' });

	return res;
};
```

but to no avail. I don't think this function expects you to try using the request response to set data on the `event` object, only the other way around.

**Comment by dummdidumm** [comment] 2022-11-09 13:02
Your idea of passing them along is almost right, but:
- the header is called `set-cookie`, not `cookie` (mistake in `setHeaders`)
- you can't set cookies through `setHeaders`, use `cookies` for that: `event.cookies.set('name', 'value', options)`

Doing this should work as expected - therefore closing this.

**Closed by dummdidumm** 2022-11-09 13:02 UTC

**Comment by Nickersoft** [comment] 2022-11-13 07:33
Hey @dummdidumm! Sorry for the delay in circling back to this – I updated my code, but cookies still aren't being set sadly :/ 

```typescript
import { endpoints } from '$lib/constants';
import type { Handle, HandleFetch } from '@sveltejs/kit';
import type { CookieSerializeOptions } from 'cookie';
import scp from 'set-cookie-parser';

export const handleFetch: HandleFetch = async ({ fetch, request, event }) => {
	if (request.url.startsWith(endpoints.api)) {
		request.headers.set('cookie', event.request.headers.get('cookie') ?? '');
	}

	const res = await fetch(request);
	const setCookie = res.headers.get('set-cookie');

	if (setCookie) {
		const parsed = scp.parse(setCookie);

		parsed.forEach((cookie) => {
			event.cookies.set(cookie.name, cookie.value, {
				...cookie,
				sameSite: cookie.sameSite as CookieSerializeOptions['sameSite']
			});
		});
	}

	console.log(event.cookies.get('access_token'));

	return res;
};
```

The log statement actually prints out the correct value in my server log, but on the client the new cookie value never gets set. Is that intentional?

**Comment by dummdidumm** [comment] 2022-11-14 09:44
Have you tried setting a dummy cookie like `event.cookies.set('foo', 'bar', { path: '/' })` to rule out it's any specific cookie option that prevents them from being forwarded?

**Comment by Nickersoft** [comment] 2022-11-15 20:04
@dummdidumm Yep! So I dug into this anymore, and after being baffled as to why cookies were being set on my repro repo but not in my app, I realized: **for some reason, cookies won't be set on hosts other than `localhost`**.

To reproduce in the [repo I linked above](https://github.com/nickersoft/sveltekit-bugs/tree/nickersoft/set-cookie):

1. Change `localhost` to `yourdomain.com` on [line 4](https://github.com/Nickersoft/sveltekit-bugs/blob/nickersoft/set-cookie/server.js#L4) and [line 8](https://github.com/Nickersoft/sveltekit-bugs/blob/nickersoft/set-cookie/server.js#L8) of `server.js`.
2. In your `/etc/hosts` file, add `127.0.0.1 yourdomain.com` and save it with `sudo`.
3. Start the Svelte server with `pnpm dev --host=yourdomain.com`.

Loading the page won't set the cookie. 

I unfortunately need to use a host alias like this for my app to circumvent my API's CORS restrictions.

**Comment by Nickersoft** [comment] 2022-11-15 21:32
Also, I [added a hooks.server.ts](https://github.com/Nickersoft/sveltekit-bugs/blob/nickersoft/set-cookie/src/hooks.server.ts) to my repo to use the solution suggested above.

**Comment by dummdidumm** [comment] 2022-11-16 13:18
This all sounds more related to how browsers handle cookies and their various options which restrict where they are applied (domain, same-site, path, strict, etc), and not related to a SvelteKit issue.
I would suggest to tinker around with your cookie forwarding, leaving out all options first and adding them back one by one until you know which one is responsible for the cookie not showing up. It might also help to set the options to the most insecure configuration possible first, to see if that has any effect.

**Comment by Nickersoft** [comment] 2022-11-17 05:15
So I tried it by setting just a [basic cookie inside `hooks.server.ts`](https://github.com/Nickersoft/sveltekit-bugs/blob/nickersoft/set-cookie/src/hooks.server.ts#L9) which still does not get set on the client, despite getting logged on the server via `event.cookies.get('dummy')`. I added a button to my demo which calls the same API via a _client side fetch_, and the cookie is set properly, so it seems to be an issue with how event cookies are set inside `handleFetch` as far as I can tell when using alternative hosts. 

If you follow the reproduction steps you should be able to see it.

**Comment by Nickersoft** [comment] 2022-11-17 18:22
Wow! So I actually found the issue here. As it turns out, SvelteKit sets `secure` to `true` [if the origin URL is _not_ localhost](https://github.com/sveltejs/kit/blob/a6ad0ae998816269131acb7a5232b01c6801e712/packages/kit/src/runtime/server/cookie.js#L54). So in order to force the cookie to be set during dev, I need to set `secure` manually:

```typescript
import { dev } from '$app/environment';

export const handleFetch: HandleFetch = async ({ fetch, request, event }) => {
	const res = await fetch(request);
	const setCookie = res.headers.get('set-cookie');

	if (setCookie) {
		const parsed = scp.parse(setCookie);

		parsed.forEach((cookie) => {
			event.cookies.set(cookie.name, cookie.value, {
				secure: dev, // This line is needed
				...cookie,
				sameSite: cookie.sameSite as CookieSerializeOptions['sameSite']
			});
		});
	}
}
```

Not sure if this is surfaced at all in the docs, but it feels like a gotcha, as I had to dig through the source to learn this lol.
