### ISSUE TITLE
Custom server-side error handler

### ISSUE THREAD

**Issue by andrew-womeldorf** [sveltejs/kit#2121] opened 2021-08-06 18:46 UTC
### Describe the problem

I'm using the `adapter-node`, and ship my logs to a log aggregator. I try to send all logs in a similar format, to be able to reuse log parsers. Currently, the default error handler ([here](https://github.com/sveltejs/kit/blob/5538107377a6685ed78c666e8a77dd9a4184f5f0/packages/kit/src/core/dev/index.js#L336-L345) and [here](https://github.com/sveltejs/kit/blob/5538107377a6685ed78c666e8a77dd9a4184f5f0/packages/kit/src/core/build/index.js#L330-L336)) print the whole stack trace on multiple lines, which comes into the aggregator as separate log messages.

### Describe the proposed solution

I'd prefer if I were able to catch the errors and handle them myself, so that I can format and print them consistent with other logs in my projects.

### Alternatives considered

Make a new hook that can catch the error.

### Importance

would make my life easier

**Comment by benmccann** [comment] 2021-08-06 18:48
duplicate of https://github.com/sveltejs/kit/issues/1857

**Comment by andrew-womeldorf** [comment] 2021-08-06 18:49
Thank you. I did look for a similar error first, but didn't see this one.

**Closed by benmccann** 2021-08-06 18:48 UTC
