### ISSUE TITLE
Version polling does not work on static prerendered page 

### ISSUE THREAD

**Issue by alexbjorlig** [sveltejs/kit#12535] opened 2024-08-02 07:13 UTC
### Describe the bug

If you visit this page https://test-skew.vercel.app/static-prerendered and open the network tab, no version polling is happening.

### Reproduction

Link to repo is [here](https://github.com/21RISK/test-skew).

File in question is this one:
https://github.com/21RISK/test-skew/tree/main/src/routes/static-prerendered

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 262.25 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.5
```
```


### Severity

annoyance

### Additional Information

It seems to work only if I visit another page first.

Polling interval is configured to 30 seconds.
Deployed on Vercel

**Comment by eltigerchino** [comment] 2024-10-16 07:02
Closing this for now as I can't reproduce the issue after deploying the repository to Vercel. I navigated to the prerendered page and it polled for the version.json file after a bit of waiting.

**Closed by eltigerchino** 2024-10-16 07:02 UTC
