### ISSUE TITLE
Page throwing 4xx error turns into 500 when client-side-routed

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#6128] opened 2022-08-20 19:19 UTC
### Describe the bug

If you have a page that does a `throw error(403)` for example, and you navigate to that page via an `<a>` tag on the site (i.e. using the client-side router), you'll incorrectly always get a 500 error instead.

Dead-simple repro: https://github.com/aradalvand/sveltekit-error-problem

### Reproduction

1. Run `git clone https://github.com/aradalvand/sveltekit-error-problem`
2. Run `npm i && npm run dev`
3. Navigate to `/foo`, you'll get a 403 error, as expected.
4. Now, navigate to the home page, and click on the "Go to foo" button, now you'll get a 500 error while the page actually threw a 403.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 236.17 MB / 3.77 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    npm: 8.11.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65
    @sveltejs/kit: next => 1.0.0-next.428
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.4 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment] 2022-08-20 20:04
I'm fairly sure this is a duplicate of https://github.com/sveltejs/kit/issues/5952, so I'm going to close it in favour of that issue

**Closed by Rich-Harris** 2022-08-20 20:04 UTC
