### ISSUE TITLE
Building blocked if using Web Workers / Missing files in Vite manifest

### ISSUE THREAD

**Issue by regnaio** [sveltejs/kit#9600] opened 2023-04-05 08:17 UTC
### Describe the bug

Initializing a Web Worker in a TypeScript file imported into a Svelte component as [recommended by Vite](https://vitejs.dev/guide/features.html#web-workers):
```ts
new Worker(new URL('./core/worker', import.meta.url));
```

Building fails with the error: `[vite-plugin-sveltekit-compile] Could not find file "node_modules/@sveltejs/kit/src/runtime/client/start.js" in Vite manifest`

Is this related? [fix: throw error when file can't be found in Vite manifest #9558](https://github.com/sveltejs/kit/pull/9558)

This used to build fine. Last `@sveltejs/kit version` I was on where this worked was `1.0.1`

```shell
npm run build

...
✓ built in 19.21s
[vite-plugin-sveltekit-compile] Could not find file "node_modules/@sveltejs/kit/src/runtime/client/start.js" in Vite manifest
✓ built in 25.84s
error during build:
Error: Could not find file "node_modules/@sveltejs/kit/src/runtime/client/start.js" in Vite manifest
    at resolve_symlinks (file:///home/gbz/app/svelte/node_modules/@sveltejs/kit/src/exports/vite/build/utils.js:76:28)
    at find_deps (file:///home/gbz/app/svelte/node_modules/@sveltejs/kit/src/exports/vite/build/utils.js:57:26)
    at Object.handler (file:///home/gbz/app/svelte/node_modules/@sveltejs/kit/src/exports/vite/index.js:724:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginDriver.hookParallel (file:///home/gbz/app/svelte/node_modules/rollup/dist/es/shared/node-entry.js:24317:17)
    at async file:///home/gbz/app/svelte/node_modules/rollup/dist/es/shared/node-entry.js:25678:13
    at async catchUnfinishedHookActions (file:///home/gbz/app/svelte/node_modules/rollup/dist/es/shared/node-entry.js:24758:20)
    at async build (file:///home/gbz/app/svelte/node_modules/vite/dist/node/chunks/dep-79892de8.js:46246:22)
    at async CAC.<anonymous> (file:///home/gbz/app/svelte/node_modules/vite/dist/node/cli.js:813:9)
```

After the failed build, I looked in `.svelte-kit/output/client/vite-manifest.json`, which only has:
```json
{
  "src/lib/ts/game/core/worker.ts": {
    "file": "_app/immutable/workers/worker-ed4c4268.js",
    "isEntry": true,
    "src": "src/lib/ts/game/core/worker.ts"
  }
}
```

Looks like `node_modules/@sveltejs/kit/src/runtime/client/start.js` is missing

### Reproduction

Broken on Latest:
`create-svelte@3.2.0`
`@sveltejs/kit@1.15.1`

Used to work on:
`@sveltejs/kit@1.0.1`

Don't know exactly which version of @sveltejs/kit this broke

### System Info

```shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 8.23 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/adapter-static: ^2.0.1 => 2.0.1
    @sveltejs/kit: ^1.5.0 => 1.15.1
    svelte: ^3.54.0 => 3.58.0
    vite: ^4.2.0 => 4.2.1
```

### Severity

blocking an upgrade

**Comment by jsilveira** [comment] 2023-04-05 13:35
I'm getting the same error when trying to build a project with @sveltejs/kit 1.5.0 that uses a Worker. I hadn't connected it with the Worker until I saw this issue. Any ideas on a workaround?

**Comment by dummdidumm** [comment] 2023-04-05 13:37
Closing as duplicate of #9528 which also contains a workaround until it's fixed in Vite.

**Closed as not planned by dummdidumm** 2023-04-05 13:37 UTC
