### ISSUE TITLE
Navigation Bug with premature layout / page data updates

### ISSUE THREAD

**Issue by pheuter** [sveltejs/kit#11775] opened 2024-02-01 14:21 UTC
### Describe the bug

I'm noticing some weird behavior when attempting to use the latest version of SvelteKit with the latest preview release of Svelte 5. See the attached screenshot and the repro, but it appears that layout data is being prematurely updated (in this case being set to `undefined` during a navigate event while the current layout and page is still mounted, which causes references to layout / page data to throw runtime errors):

<img width="1426" alt="Screenshot 2024-02-01 at 9 15 23 AM" src="https://github.com/pheuter/sveltekit-navigate-repro/assets/92698/ddf90dc4-f3f9-4e5d-9b6c-81f76d285fe2">

### Reproduction

https://github.com/pheuter/sveltekit-navigate-repro

### System Info

```Shell
System:
    OS: macOS 14.3
    CPU: (16) arm64 Apple M3 Max
    Memory: 7.06 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.3.0 - ~/.nvm/versions/node/v20.11.0/bin/npm
    bun: 1.0.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 17.3
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1 
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2 
    svelte: ^5.0.0-next.1 => 5.0.0-next.44 
    vite: ^5.0.3 => 5.0.12
```

### Severity

blocking an upgrade

**Comment by eltigerchino** [comment] 2024-11-20 06:18
Closing this as I'm unable to reproduce it on the latest versions of Svelte and SvelteKit

**Closed by eltigerchino** 2024-11-20 06:18 UTC
