### ISSUE TITLE
Exclude directory from Routes for a Multi Domain App

### ISSUE THREAD

**Issue by ainsleyclark** [sveltejs/kit#10980] opened 2023-11-04 19:46 UTC
### Describe the problem

Our application is designed to support multiple domains, with a distinct directory structure that encapsulates the routes for each domain within the `/routes` folder. Here is a snapshot of our current directory tree:

```
├── routes/
│   ├── domain-a.com/
│   │   └── +page.svelte
│   ├── domain-b.com/
│   │   └── +page.svelte
│   └── domain-c.com/
│       └── +page.svelte
├── +error.svelte
├── +layout.svelte
└── +layout.ts
```

Dependant on an environment variable, I would like to exclude `domain-b.com` and `domain-c.com` (for example) from the build. 

Currently, I get an inevitable `The /(domain-a.com) and /(domain-b.com) routes conflict with each other.`

### Describe the proposed solution

We are looking for a method to conditionally exclude directories `domain-b.com` and `domain-c.com` from the build process, potentially using an environment variable. This would allow us to fine-tune our build output for different deployment scenarios.

### Importance

would make my life easier

**Comment by Conduitry** [comment] 2023-11-04 21:45
Duplicate of #10344.

**Closed by Conduitry** 2023-11-04 21:45 UTC
