### ISSUE TITLE
__error not correctly displayed when default layout inherits from a named layout

### ISSUE THREAD

**Issue by y0zong** [sveltejs/kit#4940] opened 2022-05-16 08:19 UTC
### Describe the bug

Let us assume such a file structure
``` hash
-routes
  └login
      └index@init.svelte
    |-__error.svelte
    |-__layout-init.svelte
    |-__layout@init.svelte
    └index.svelte
```
`__layout-init.svelte` used to load initialization content such as shared styles and external js files for whole site, login page use just `__layout-init.svelte` cuz it's a additional page that don't need `__layout@init.svelte`, everything is ok so far, but, the `__error.svelte` just inherit from `__layout@init.svelte` and lost `__layout-init.svelte` that means error page can't load initialization content ( which should inherit from -> `__layout@init.svelte` -> `__layout-init.svelte`)

I think it's a bug or design to?

### Reproduction

[here is online demo](https://stackblitz.com/edit/sveltejs-kit-template-default-fmnrme?file=src/routes/index.svelte)

### System Info

```shell
Browsers:
    Chrome: 101.0.4951.64
    Edge: 101.0.1210.47
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.40 
    @sveltejs/adapter-static: ^1.0.0-next.30 => 1.0.0-next.30 
    @sveltejs/kit: next => 1.0.0-next.326 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by ghostdevv** [comment] 2022-06-07 15:24
I am having this issue as well

**Comment by ghostdevv** [comment] 2022-06-07 15:52
Duplicate of #4582

**Comment by Conduitry** [comment] 2022-07-21 15:25
To be a little more specific: If a `load` function explicitly returns an `{ status, error }` object, it looks like `__error.svelte` renders correctly inside `__layout@foo.svelte` which renders inside `__layout-foo.svelte` like it's supposed to. When I navigate to a route that doesn't exist at all, `__error.svelte` renders inside `__layout@foo.svelte` but that does _not_ render inside `__layout-foo.svelte`.

**Comment by Conduitry** [comment] 2022-07-21 16:09
The error appears to be here: https://github.com/sveltejs/kit/blob/67e2342149847d267eb0c50809a1f93f41fa529b/packages/kit/src/runtime/server/page/respond_with_error.js#L74 The `respond_with_error` function is only including the main layout and the error layout. I haven't been able to sort through what the regular `respond` function is doing differently that it includes all of the appropriate `Loaded` objects.

**Comment by Conduitry** [comment] 2022-07-28 17:05
I believe this can be partly worked around, at least in the 404 case, by adding a dummy `[...catchAll].svelte` component:

```svelte
<!-- src/routes/[...catchAll].svelte -->
<script context="module">
	export function load({ url }) {
		return { status: 404, error: "Not found: " + url.pathname };
	}
</script>
```

**Comment by dummdidumm** [comment] 2022-08-18 14:24
This sounds like another instance of the root fallback behavior where the first layout is used to render the error page in - which in this case is wrong, because it depends on another one. I'm more and more of the opinion that we need to have a a fallback root layout regardless of other provided roots layouts, and in this case we need to apply some logic to not only know the root layout but also its dependencies.

**Closed** 2022-08-24 13:25 UTC
Labels: bug, p1-important
