### ISSUE TITLE
adapter-node makes build dependent on dev dependencies

### ISSUE THREAD

**Issue by SylvainGarrigues** [sveltejs/kit#5944] opened 2022-08-16 18:50 UTC
### Describe the bug

Just run the `build` directory:

```
# node build/
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'devalue' imported from /usr/src/camlacoste-run/build/server/index.js
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Reproduction

```
my-svelte-app # npm run build
my-svelte-app # mkdir ../my-app-run && cd ../my-app-run
my-app-run # npm install --omit=dev
my-app-run # node build/
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'devalue' imported from /usr/src/camlacoste-run/build/server/index.js
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### System Info

```shell
# npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: Linux 5.15 Alpine Linux
    CPU: (4) arm64 Cortex-A72
    Memory: 1.13 GB / 1.81 GB
    Container: Yes
    Shell: 1.35.0 - /bin/ash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.85 => 1.0.0-next.85 
    @sveltejs/kit: next => 1.0.0-next.411 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.8
```

### Severity

serious, but I can work around it

### Additional Information

Can work around it by installing dev dependencies

**Comment by Conduitry** [comment] 2022-08-16 18:52
Duplicate of #3176.

**Closed by Conduitry** 2022-08-16 18:52 UTC

**Comment by SylvainGarrigues** [comment] 2022-08-16 18:56
Is this really related? The documentation for adapter-node (see README) says I can just `npm ci --prod && node build` and be running straight away, it used to be the case until recently, now I need to use `npm ci` alone, while my code didn't change at all and I don't have external dependencies.

**Comment by SylvainGarrigues** [comment] 2022-08-16 19:12
Running `npm install devalue` after `npm ci --prod` and before `node build` solves this issue. I am not sure this is a really a duplicate of https://github.com/sveltejs/kit/issues/3176
