### ISSUE TITLE
Server `handle` hook returning `undefined` origin in `event.url` for local env

### ISSUE THREAD

**Issue by smblee** [sveltejs/kit#7168] opened 2022-10-07 04:31 UTC
### Describe the bug

logging `event.url` in `hooks.server.ts`'s `handle` function in local `preview` and `dev` returns `undefined` for all URLs.

```
URL {
  href: 'https://undefined/',
  origin: 'https://undefined',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'undefined',
  hostname: 'undefined',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

Is this intended? My use case for this is for e2e testing since we use some of these values to populate cookie in the handle hook.

### Reproduction

log `event.url` within `hooks.server.ts` `handle` hook.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 152.45 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.volta/tools/image/node/16.17.1/bin/node
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 105.0.2
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.80 => 1.0.0-next.80
    @sveltejs/kit: 1.0.0-next.511 => 1.0.0-next.511
    svelte: 3.50.1 => 3.50.1
    vite: 3.1.6 => 3.1.4
```

### Severity

annoyance

**Comment by Conduitry** [comment] 2022-10-07 14:29
I can't reproduce this. It logs fine for me.

**Comment by smblee** [comment] 2022-10-07 15:37
@Conduitry ah `dev` seems to work for me. it only seems to be an issue in `build && preview`

**Comment by benmccann** [comment] 2022-11-08 20:59
I'm closing this since it doesn't seem reproducible. We can reopen if you figure out a way to reproduce it

**Closed by benmccann** 2022-11-08 20:59 UTC
Labels: awaiting submitter

**Comment by PudottaPommin** [comment] 2023-05-19 05:52
Hello @benmccann , I figured, that origin is not set in preview, when we use `https`. If you want, I can upload repo, but just setting `vite.config.js` as below is enough.

```js
// vite.config.js
export default defineConfig({
  plugins: [sveltekit()],
  server: {
    https: {
      cert: "./cert.pem",
      key: "./cert.key",
    },
  },
});
```
