### ISSUE TITLE
Conditional Route ParamMatcher

### ISSUE THREAD

**Issue by arnoschn** [sveltejs/kit#9438] opened 2023-03-17 11:10 UTC
### Describe the problem

To build a multilingual website with language adapted urls, it would be great to be able to have routes that change its url based on the selected language.

Right now the ParamMatcher only receives the parameter that is to be validated, so an adaptive route matching based on language is not possible in this example:

routes/[[lang=iso]]/[directory=directoryInLanguage]

which in german should translate to /de/verzeichnis, while in english it would be /en/directory.

### Describe the proposed solution

A solution would be to add an optional parameter to the ParamMatcher, that contains all matched params left of the currently checked parameter.

<code>
import type { ParamMatcher } from '@sveltejs/kit';
 
export const match = ((param,params) => {
  if(params.lang=="de") return param=="verzeichnis";
else if(params.lang=="en") return param=="directory";
else return false;
}) satisfies ParamMatcher;
</code>

### Alternatives considered

Alternatives would be to implement components for each route and then have subroutes per language:

en/directory
de/verzeichnis

but that does not make my life easier 

### Importance

would make my life easier

**Comment by Conduitry** [comment] 2023-03-17 12:12
Duplicate of #4500.

**Closed by Conduitry** 2023-03-17 12:12 UTC
