### ISSUE TITLE
When running `vite build` it does not execute any adapter

### ISSUE THREAD

**Issue by gbkwiatt** [sveltejs/kit#7172] opened 2022-10-07 09:51 UTC
### Describe the bug

All happened after migrating to latest svelte-kit with latest routes pattern. 
Dev server works fine

When running `vite build` using any adapter - it runs 2 builds, one for production and SSR for production 
```terminal
vite v3.1.6 building for production...
transforming...
✓ 1374 modules transformed.
rendering chunks...
vite v3.1.6 building SSR bundle for production...
transforming...
✓ 1076 modules transformed.
rendering chunks...
```

looking at the vite build code, one of them should have `vite_config.build.ssr`: `false` so it executes adapters
```js
closeBundle: {
  sequential: true,
  async handler() {
  // vite calls closeBundle when dev-server restarts, ignore that,
  // and only adapt when build successfully completes.
  const is_restart = !completed_build;
  if (vite_config.build.ssr || is_restart) {
    return;
  }
```
But they both have `ssr: true` and I can't figure out why 
It does not fail any build, but it's not creating build output

### Reproduction

vite config
```js
const config = {
    plugins: [viteCommonjs(), sveltekit()],
    server: {
        fs: {
            allow: ['../..'],
        },
    },
    ssr: {
        noExternal: ['lucide-svelte'],
    },
};
```

svelte config

```js
const config = {
    // Consult https://github.com/sveltejs/svelte-preprocess
    // for more information about preprocessors
    preprocess: [
        preprocess({
            postcss: true,
        }),
    ],
    kit: {
        adapter: process.env.BUILD_NODE
            ? adapterNode({ out: 'build-node' })
            : adapterStatic({ pages: 'build', assets: 'build' }),
        files: {
            assets: 'src/site/static',
        },
        trailingSlash: 'never',
    },
};
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 5.13 GB / 9.72 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.1.0/bin/yarn
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.80 => 1.0.0-next.80 
    @sveltejs/adapter-node: 1.0.0-next.82 => 1.0.0-next.82 
    @sveltejs/adapter-static: 1.0.0-next.44 => 1.0.0-next.44 
    @sveltejs/kit: 1.0.0-next.508 => 1.0.0-next.508 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.4 => 3.1.4
```

### Severity

blocking an upgrade

**Comment by gbkwiatt** [comment] 2022-10-07 11:47
Ok turned out, that because I Was importing config from my template to the app directory - (vite config). It was causing that issue, but not sure why it was fine before and now it's not.

**Comment by benmccann** [comment] 2022-10-07 16:55
I'm going to close this since it seems like quite the edge case and a repository with a reproduction was not provided

**Closed by benmccann** 2022-10-07 16:55 UTC
