### ISSUE TITLE
prerender = true in /+layout.server.ts breaks the route after deployment to netlify / vercel

### ISSUE THREAD

**Issue by StephenGunn** [sveltejs/kit#6568] opened 2022-09-04 19:57 UTC
### Describe the bug

I found this bug in one of my bigger projects after migrating to the new routing configuration. It took me a while to pinpoint that it was the `prerender = true` setting in `/+layout.server.ts` that was causing the bug. The project runs fine locally using pnpm dev || pnpm build || pnpm preview. The project also has no problem building once deployed to Netlify / Vercel. It's only after publishing that it breaks.

I created a new project from scratch and was able to recreate the bug when deployed to both netlify and vercel.

- The repo for the scratch project is here: https://github.com/StephenGunn/layoutprerender

- The deployment on Netlify is here: https://glittering-mermaid-5b82d2.netlify.app

- The deployment on Vercel is here: https://layoutprerender.vercel.app

You'll be able to see the 500 error on both Netlify and Vercel using the above links. I also have examples of the exact same code but with prerendering not set and the routes work as intended.

I tried to make the code and example as clear as possible, let me know if you have any questions.

EDIT: prerender = true works on normal /+page.server.ts powered routes from my testing

### Reproduction

- clone https://github.com/StephenGunn/layoutprerender and deploy to netlify or vercel

### Logs

```shell
Netlify doesn't seem to log any error in the render.js function logs.

Vercel logs this: [GET] /episodes-3/__data.js?__invalid=nyn&__id=1

The error on the frontend is this:
500
Failed to fetch dynamically imported module: https://layoutprerender.vercel.app/episodes-3/__data.js?__invalid=nyn&__id=1
TypeError: Failed to fetch dynamically imported module: https://layoutprerender.vercel.app/episodes-3/__data.js?__invalid=nyn&__id=1
```

### System Info

```shell
Netlify / Vercel
```

### Severity

annoyance

### Additional Information

Marked as an annoyance because I can just turn off prerendering for my /+layout.server.ts and the site works.

But I would like to be able to turn this feature back on since it does slow down certain routes and puts added stress on my backend.

**Comment by s3812497** [comment] 2022-09-04 20:22
Hi Stephen,

What does the `ssr` `noExternal` config do in `vite.config.js`? [Link here](https://github.com/StephenGunn/layoutprerender/blob/4040b1692af8f7eae4bc5b6c1ccc8718f0b1af28/vite.config.ts#L6-L10).

Could this be the cause of the problem? (I've no idea, but just curious as I was looking through the code and comparing it to a new skeleton project).

**Comment by StephenGunn** [comment] 2022-09-04 20:34
The project breaks without it. See https://github.com/sveltejs/kit/issues/6462

**Comment by s3812497** [comment] 2022-09-04 21:00
It seems to work fine with `prerender = 'auto'` but that doesn't really explain the problem.
Also, this is the error message when going to the prerendered page directly:
```
404
Not found: /episodes-1
Error: Not found: /episodes-1
    at resolve2 (file:///var/task/.svelte-kit/output/server/index.js:2514:18)
    at Object.options.hooks.handle (file:///var/task/.svelte-kit/output/server/index.js:2643:69)
    at respond (file:///var/task/.svelte-kit/output/server/index.js:2528:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Hope some of this info helps with finding the bug.

**Comment by s3812497** [comment] 2022-09-04 21:25
After some additional testing:

1. The prerendered pages are missing from the output after build, hence the error.
2. Using the prerender option in `+page.ts` and `+layout.ts` instead of `+layout.server.ts` doesn't change anything.
3. Adding a static route to prerender causes the build to properly prerender the dynamic routes as well.

Somehow the compiler is skipping the dynamic routes for prerender (although there are links referencing them).

A workaround that works for @StephenGunn in the mean time is by specifying the dynamic route for prerender explicitly via the `svelte.config.js` `prerender` option:
```
import adapter from "@sveltejs/adapter-auto";
import preprocess from "svelte-preprocess";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: preprocess(),

  kit: {
    adapter: adapter(),
    prerender: {
      entries: ['/episodes-[number]'],
    },
  },
};

export default config;
```

Hope this helps!

**Comment by StephenGunn** [comment] 2022-09-04 22:04
Thanks for digging around @s3812497, I don't think that solution will work for me. I'll explain why:

Here is an episode page from the project that lead me to find this bug: https://craftroulette.live/episodes/episode-127

The version you're looking at is pre-route migration so everything is working. The layout file for the episode runs a couple of queries against the DB to get the gallery count, guest count, process video count, and extras gallery count and display them in the sidebar. I pre-render the layout on build so that site doesn't have to make those queries every time the episode is loaded.

Here is the catch, I need to keep some of the sub routes dynamic. So, the Contribution Gallery, Process Videos, and Extras Gallery pages are all dynamic because they allow people to submit to them. The numbers on the menu do get out of sync until the next build but that's not a big deal.

So as far as I know, I can't just specify the episode to be static because I have dynamic sub-pages.

I have the site ready to publish with the routing migration done and everything else up-to-date.. but the prerender = true was breaking the sub-routes on that page. It took me a few days to figure out what was going on, and that's when I build the tester project to make sure.

**Comment by s3812497** [comment] 2022-09-04 22:16
If I understand this correctly, you could try adding a group layout for your dynamic sub-pages and set `prerender = false` to get the result you want.
Example:
```
my-project/
├ src/
│ ├ routes/
│ │ ├ episodes-[number]/
│ │ │ ├ (dynamic)/
│ │ │ │ ├ gallery/
│ │ │ │ ├ videos/
│ │ │ │ └ +layout.svelte // <slot/>
│ │ │ │ └ +layout.ts // export const prerender = false
│ │ └ +page.svelte
│ │ └ +layout.server.ts
│ │ └ +layout.svelte
```

**Comment by StephenGunn** [comment] 2022-09-04 22:39
@s3812497 thanks. I will try this.

Question- I have not used the svelte.config.js prerender option before, will this affect the pages that I already have prerender = true set? Can I set it at the config level AND the route level? The majority of the routes are set to prerender.

Should I just set 

```
prerender: {
    default: true
},
```

and then specify all of the paths I don't want to pre-render? Might be easier?

**Comment by s3812497** [comment] 2022-09-04 22:41
> @s3812497 thanks. I will try this.
> 
> Question- I have not used the svelte.config.js prerender option before, will this affect the pages that I already have prerender = true set? Can I set it at the config level AND the route level? The majority of the routes are set to prerender.

I've never used the option before either, but I would assume the `entries` option would be in addition to per-route configuration.

> Should I just set
> 
> ```
> prerender: {
>     default: true
> },
> ```
> 
> and then specify all of the paths I don't want to pre-render? Might be easier?

Sounds like the right way to go :)

**Comment by StephenGunn** [comment] 2022-09-04 23:16
So,

```
prerender: {
    default: true
},
```

has been removed, according to the error I got during build, but is still in the docs.

and any route that I tried to specify with
`entries` that had a parameter in the route, failed:

```
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/exports/vite/index.js:435:15)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
 ELIFECYCLE  Command failed with exit code 1.

```

I think I was closer before but it was worth the shot.

**Comment by s3812497** [comment] 2022-09-04 23:22
> So,
> 
> ```
> prerender: {
>     default: true
> },
> ```
> 
> has been removed, according to the error I got during build, but is still in the docs.

Ah, right. I think it got removed in favour of just adding a `prerender = true` to the main layout in your application, thus affecting all routes.
 
> and any route that I tried to specify with `entries` that had a parameter in the route, failed:
> 
> ```
> [vite-plugin-svelte-kit] Prerendering failed with code 1
> error during build:
> Error: Prerendering failed with code 1
>     at ChildProcess.<anonymous> (file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/exports/vite/index.js:435:15)
>     at ChildProcess.emit (node:events:513:28)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
>  ELIFECYCLE  Command failed with exit code 1.
> ```

Can you post more of the error log? If you scroll up a bit more, the actual error has a more descriptive error message that will explain why the prerendering process failed and for which page.

**Comment by StephenGunn** [comment] 2022-09-04 23:31
I'm not having any luck using the prerender config object.. Here is the full error when trying to specify my episodes route:

file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:50
                                throw new Error(format_error(details, config));
                                      ^

```
Error: 404 /episodes/episode-[number=integer]
    at file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:50:11
    at save (file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:355:4)
    at visit (file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:232:3)
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/exports/vite/index.js:435:15)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
 ELIFECYCLE  Command failed with exit code 1.
```
So a 404- I also tried '*' with crawl: true and it didn't pre-render anything. I also tried leaving out the =integer part on the route and that 404'd.

I'm probably going to give this a rest for now and hope this gets fixed soon. :)

**Comment by s3812497** [comment] 2022-09-04 23:42
> ```
> file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:50
>                                 throw new Error(format_error(details, config));
>                                       ^
> Error: 404 /episodes/episode-[number=integer]
>     at file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:50:11
>     at save (file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:355:4)
>     at visit (file:///home/stephen/Projects/craftroulette/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.468_qevq5tvhizyxp44gfhkn6m3ljq/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:232:3)
> ```

It's weird that it can't find the route. What's the structure of your routes?

> So a 404- I also tried '*' with crawl: true and it didn't pre-render anything.

In the docs, it mentions the `'*'` value for `entries` doesn't include dynamic routes (must be why it ignores your routes).
> The * string includes all non-dynamic routes (i.e. pages with no [parameters] )
https://kit.svelte.dev/docs/configuration#prerender
I'd recommend just going with adding a `prerender = true` to your home page layout.

**Comment by StephenGunn** [comment] 2022-09-04 23:55
Ok, I think adding prerender = true to the root +layout.server.ts and then specifying prerender = false on the routes I want to keep dynamic worked. I'll keep playing with it and make sure this works for me. 

Thank you for helping me!

The original bug still exists though so I'm going to leave this open.

**Comment by StephenGunn** [comment] 2022-09-05 06:23
Just as a follow up- my site was acting weird before I realized that putting prerender = true in the +layout.server.ts prevented my UI from having logged in / logged out state. So I reverted again and I will wait until the original problem is fixed.

**Comment by s3812497** [comment] 2022-09-05 08:13
> Just as a follow up- my site was acting weird before I realized that putting prerender = true in the +layout.server.ts prevented my UI from having logged in / logged out state. So I reverted again and I will wait until the original problem is fixed.

That's what prerender does. It runs all the `layout` and `page` `load` functions for the specified route at runtime, then builds a HTML file for that page using the values returned from load. Thus, the HTML file is served when users go to that route, and no load functions are run.

I think you may not want to prerender your pages, or you'll want to check for the logged in / logged out state outside the `load` function.

**Comment by s3812497** [comment] 2022-09-05 16:53
> What's happening to me is any page that has a /+page.server.ts that is set to prerender is overwriting the $page.data store completely when I navigate to it. I don't know if that is intended behavior.

It should overwrite the `+page` data but retain the `+layout` data if the pages share the same layout.

> I followed the discussion thread about removing the session store where Rich suggested using the root level /+layout.server.ts to pass event.locals to the front-end.
> 
> I'm guessing that I need to create my own session store and pass the user object / auth state to that on login and use that session store to determine my UI state. Does that sound right?

You can [re-create the session store](https://www.captaincodeman.com/re-creating-the-sveltekit-session-store) and use it to keep track of auth state. Personally, I have been using just the layout `load` function and the `data` returned.

**Comment by StephenGunn** [comment] 2022-09-05 17:15
> It should overwrite the `+page` data but retain the `+layout` data if the pages share the same layout.

That is exactly what I am expecting but not seeing. I made a quick video to show you what is happening:

https://user-images.githubusercontent.com/7240548/188493836-09b232ff-879a-4f8f-8b17-6f36b4a08b6e.mp4

I really want to know what is happening rather than just writing a workaround. Any thoughts?

thanks again

**Comment by s3812497** [comment] 2022-09-05 17:40
>  2022-09-05.12-05-55.mp4 

Is this running with `dev` or `preview`? If in `dev`, is it fixed when you remove the `prerender` option?

**Comment by StephenGunn** [comment] 2022-09-05 18:01
The video is the production version is live on www.craftroulette.live - it works as intended on dev. And yes, removing the prerender = true solves the issue. Here is a video where the only altered code between the two videos is setting prerender = false on the page that reset my page.data earlier


https://user-images.githubusercontent.com/7240548/188498139-a0866533-bea7-49dd-8f07-10dd3dbfb35d.mp4

I will just set all my prerenders to false for the time being. I guess this is a bug?

**Comment by s3812497** [comment] 2022-09-05 18:17
> The video is the production version live on [www.craftroulette.live](http://www.craftroulette.live) - it works as intended on dev. And yes, removing the prerender = true solves the issue. Here is a video where the only altered code between the two videos is setting prerender = false on the page that reset my page.data earlier
> 
>  2022-09-05.12-56-27.mp4 
> 
> I will just set all my prerenders to false for the time being. I guess this is a bug?

It is working as intended on SvelteKit's part. Pre-rendering means saving the HTML of the page during build time. As a result, the page does not show any user logged in (as no user is logged in at build time). None of the server `load` functions will run because data has already been calculated at build time. So, the data while visiting that page will always be the same.

**Comment by StephenGunn** [comment] 2022-09-05 18:29
Is it intended to overwrite the data derived from the layout as well? If that's the case, creating my own session store would be the fix and I am fine with that. I think one of my hang-ups has been that I had prerendering working before the route migration with the built-in session store, so the UI stayed up to date even on prerendered routes.

**Comment by s3812497** [comment] 2022-09-05 18:50
> Is it intended to overwrite the data derived from the layout as well?

Yes, the layout server load function is not re-run. The data stays the same as it was during build.

> If that's the case, creating my own session store would be the fix and I am fine with that. I think one of my hang-ups has been that I had prerendering working before the route migration with the built-in session store, so the UI stayed up to date even on prerendered routes.

Yeah, you'll just want to mimic the same order of events:
1. While client-side, fetch data from an endpoint (`getSession()` runs on the server and returns data to the client)
2. Keep the data in a `store` (`$session` store).

**Comment by StephenGunn** [comment] 2022-09-06 00:02
Creating my own store was very simple, just had to wrap my thick head around the need to. Thanks again for your help.

If anyone is reading this wondering if we solved the original issue, we did not. @s3812497 just helped me figure out a few things.

**Comment by b3ngg** [comment] 2022-09-09 08:27
Same issue when deploying to Clodflare pages via the adapter.

**Comment by s3812497** [comment] 2022-09-09 08:32
> Same issue when deploying to Cloudflare pages via the adapter.

The title is misleading as the actual issue is SvelteKit did not pre-render dynamic routes marked for prerender, leading to missing html files. This only occurs if there aren't any other non-dynamic routes marked for prerender.

**Comment by Rich-Harris** [comment] 2022-09-22 15:47
The issue here is that `src/routes/episodes-[number]` is marked as prerenderable by virtue of the `export const prerender = true` in `src/routes/episodes-[number]/+layout.server.ts`, which means the code to generate the `__data.js` files needed by the page isn't included in the deployment to Vercel/Netlify, on the assumption that the `__data.js` files were already prerendered. But they weren't, because the crawler didn't get to them, because `/` (which contains the links the crawler would otherwise follow) is _not_ marked as prerenderable.

At the very least, we should make this bug more discoverable by omitting those routes from the manifest used during `preview`, so that it fails locally the same way it fails in production.

One solution could be to always render pages, whether or not they're marked as prerenderable, so that the crawler can find prerenderable pages via non-prerenderable pages. Non-prerenderable pages would just be discarded. But this would make everyone's builds much slower. Another (probably much more sensible) possibility would be to print a warning or error if a route was marked as prerenderable but wasn't actually prerendered.

**Comment by 24jr** [comment] 2022-09-27 16:09
I removed my 
```
prerender: {
	default: true
},
```
and added `export const prerender = true;` to +layout.js and using adapter static for npm run build get 
```
[vite-plugin-svelte-kit] Prerendering failed with code 1leted in 1ms
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///Users/jrose/Documents/the-plan/longhauler/node_modules/@sveltejs/kit/src/exports/vite/index.js:438:15)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```
I dont believe I have dynamic routes in the sense of something/[somecategory]/+page.svelte

I still don't know all the new file types and stuff so perhaps I'll go do that and maybe will understand better. Worked before though so do I need to reconfigure something or should I just wait to migrate and later it will work fine?

**Comment by s3812497** [comment] 2022-09-27 16:27
> added `export const prerender = true;` to +layout.js
I believe this isn't necessary because `adapter-static` will prerender all pages by default.

I'm not sure what's causing the error though. You may need to provide more information.

**Comment by 24jr** [comment] 2022-09-27 17:42
@s3812497 If I comment that line out I get 
```
Using @sveltejs/adapter-static
  @sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root layout.js — see https://kit.svelte.dev/docs/page-options#prerender for more details

```

**Comment by g012** [comment] 2022-10-01 22:08
I have a website with no server (it's deployed on Amplify), as SSG with the static adapter. I use another library as my backend.
Before the migration, everything was working fine like this:
 /* -> prerender = true
 /user/* -> prerender = false, ssr = false (pure SPA with fallback)

I've now migrated the project to the new routing system, and moved:
 /* to (public) group
 /user/* to (user) group

In /+layout.server.ts, I have `export const prerender = true;`, and in /(user)/+layout.server.ts, I have `export const prerender = false;` and `export const ssr = false;`. I also have dynamic route in /(user)/recipe/[...id=optuuid].

When I deploy, no __data.js is generated for page directories in (user). But when accessing the page, it tries to load `http://localhost:4173/subscription/__data.js?__invalid=nny&__id=1`, which fails on Amplify as there is no such file. Without prerendering, the build/subscription folder doesn't even exist.

What's wrong with the config ? How can I get it to work as before, without any sveltekit server running live ?
Thank you.

**Closed** 2022-11-08 09:37 UTC
Labels: bug
