### ISSUE TITLE
$page.query returns empty on prerendered pages

### ISSUE THREAD

**Issue by snird** [sveltejs/kit#1218] opened 2021-04-25 23:34 UTC
**Describe the bug**
Using $page.query sometimes returns as empty for pages with a query string.

**To Reproduce**
In my experience, any basic page using `page` from the store.

**Expected behavior**
It should always have the current page query string

**Severity**
It made this feature currently unusable for me.
In my case, I can check with `browser` and use `window.location.search` instead.
But I'm not sure how severe this might be for those relying on it in the backend.

**Comment by Conduitry** [comment] 2021-04-26 00:56
Do you have a more specific reproduction? It seems to be working for me. Also, make sure you're seeing is not #586.

**Comment by snird** [comment] 2021-04-26 07:51
@Conduitry My experience is similar to https://github.com/sveltejs/kit/issues/586
And I have used it as URLSearchParams - it's still empty.

**Comment by milky2028** [comment] 2021-04-28 21:33
I'm getting this issue as well

**Comment by Conduitry** [comment] 2021-04-28 21:53
Does anyone who's seeing this have a reproduction?

**Comment by milky2028** [comment] 2021-04-29 03:59
I will try to cook one up.

**Comment by uzuworks** [comment] 2021-05-03 17:18
I don't know if it is the same, but I am experiencing a similar thing.
In my case, it doesn't happen with “dev” or “preview" (a query exists), but when I build and run it with adapter-node.

I tried to create a simple reproduction environment.
https://github.com/uzuworks/query_example

As access the index with search parameters
“npm run dev”: no problem
“npm run build && npm run preview”: no problem
"npm run build && node ./build/“: only when I run this, the query doesn't exist

**Comment by milky2028** [comment] 2021-05-03 22:35
This is the same thing I’m experiencing, but I’m using adapter-static.

**Comment by mzaini30** [comment] 2021-05-08 09:25
I get this null too. I use adapter static

```html
<script context='module'>
 export async function load({page}){
  return {
   props: {
    name: await page.query.get('name')
   }
  }
 }
</script>
<script>
 export let name
</script>

<h1>Hi {name}</h1>
```

**Comment by sFiFty** [comment] 2021-05-17 11:39
Any progress with this? $page.query still doesn't work with adapter static

**Comment by benmccann** [comment] 2021-05-17 13:33
@mzaini30 yes, please feel free to send a PR with your solution

**Comment by benmccann** [comment] 2021-05-26 17:22
This happens when the page is prerendered. Closing as duplicate of https://github.com/sveltejs/kit/issues/669

**Closed by benmccann** 2021-05-26 17:22 UTC
Labels: bug
