### ISSUE TITLE
Getting vite build error when loading images from $lib

### ISSUE THREAD

**Issue by VerburgtJimmy** [sveltejs/kit#12393] opened 2024-06-22 14:28 UTC
### Describe the bug

I am getting this error: [vite:asset] Could not load src/lib/assets/logo.jpg (imported by src/lib/blocks/ui/HeaderBlock.svelte): ENOENT: no such file or directory, open '/src/lib/assets/logo.jpg'

when running npm run build on a server.

My images are in $lib/assets/logo.jpg and i import them like this: import logoimg from '$lib/assets/logo.jpg';

Is this a known issue for anyone? 

### Reproduction

I can't provide a reproduction link as this only happens on my ubuntu server. When running it locally the build runs succesfull

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (1) x64 Intel Core Processor (Skylake, IBRS, no TSX)
    Memory: 1.16 GB / 1.92 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.14.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.1
    @sveltejs/kit: ^2.0.0 => 2.5.10
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.1
    svelte: ^4.2.7 => 4.2.17
    vite: ^5.0.3 => 5.2.12
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment] 2024-06-23 14:47
If you can't reproduce it I'm afraid there's no way for us to know if there's any bug here. I'll close this for now, but if you can share more details we can reopen it

**Closed by benmccann** 2024-06-23 14:47 UTC

**Comment by VerburgtJimmy** [comment] 2024-06-23 14:49
Sorry forgot the close this. For anyone with the same problem my problem was that my images had .JPG in capital letters. Changing this to lowercase solved the problem
