### ISSUE TITLE
Parallel Routes

### ISSUE THREAD

**Issue by machycek** [sveltejs/kit#11306] opened 2023-12-14 00:59 UTC
### Describe the problem

We have a quite a large app with about ~400 svelte components and ~300 routes.

Some of the pages have a lot of logic and try to handle "one too many things". For example our analytics page has five fetch requests in one `+page.ts` (think about showing five different graph visualizations with separate data sets for each one of them). When we change a resolution of one graph the whole logic in `+page.ts` logic falls short (due to the nature if you calling invalidate it invalidates all 5 fetch requests). Due to that we only use `+page.ts` load function to receive initial data and escape the "SvelteKit way" where you separate data fetching from UI and actually write custom logic to handle loading more data.

### Describe the proposed solution

I find elegant what NextJS does with [parallel routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes) and it solves the problem for us and hopefully does for others as well. I also understand that lot of people don't hit this problem unless they have a rather larger app and handle lot of edge cases. Question would come how the design in SvelteKit would look like and I would take an inspiration from NextJS again.

```tsx
export default function Layout(props: {
  children: React.ReactNode
  analytics: React.ReactNode
  team: React.ReactNode
}) {
  return (
    <>
      {props.children}
      {props.team}
      {props.analytics}
    </>
  )
}
```

**V1** `+layout.svelte`
```svelte
<script>
  export let data;
</script>

<slot />
<slot name="team" />
<slot name="analytics" />
```

**V2** `+layout.svelte`
```svelte
<script>
  export let data;
  export let analytics;
  export let team;
</script>

<slot />
<svelte:component this={team} />
<svelte:component this={analytics} />
```

V1 feels like a great ergonomics but I'm not sure how would the parser be able to handle that since I don't know the internals of SvelteKit and how that plays.

Appreciate your time reading this.

### Importance

would make my life easier

**Comment by dummdidumm** [comment] 2023-12-14 08:16
I think parallel routes would be the wrong solution to this problem. What you want is more fine-grained control over which things rerun, for which #6294 or a way to define multiple load functions would be better suited. Closing this as duplicate of #10848

**Closed by dummdidumm** 2023-12-14 08:16 UTC
