### ISSUE TITLE
Fetch in load function not sending cookie when in production

### ISSUE THREAD

**Issue by mishrasatyam** [sveltejs/kit#2350] opened 2021-09-02 08:18 UTC
### Describe the bug

1. No issue in setting a cookie. Cookie is set and present in browser.
2. Cookie is being sent by the same code when it is running in localhost .
3. **Problem** : In production, fetch in load function isn't sending cookie, but browser fetch is able to send cookie.

### Reproduction

I created a [svelte-kit repo](https://github.com/mishrasatyam/load_fetch_not_sending_credentials) running on [https://expense.satyam.life/](https://expense.satyam.life/) . When you run it it just shows you a button set cookie. When you click the button cookie is set using an endpoint and you are redirected to a page displaying cookie sent by load_fetch and browser_fetch.

The backend fastify repo](https://github.com/mishrasatyam/fastify_send_read_cookie)  is running on [https://expenseapi.satyam.life/](https://expenseapi.satyam.life/) . It has two routes (one for creating cookie, other for sending back cookie received in request header).

Again, I am not having any issue when both servers are running on localhost. I am using seperate EC2 ubuntu 20.04 machines for deployment.

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
    Memory: 223.23 MB / 978.57 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.8.0 - ~/.local/share/pnpm/node
    npm: 7.21.0 - ~/.local/share/pnpm/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.44 => 1.0.0-next.44
    @sveltejs/kit: next => 1.0.0-next.162
    svelte: ^3.34.0 => 3.42.4
```

### Severity

serious, but I can work around it

### Additional Information

Work around is calling an endpoint from load fetch and using headers in endpoint. But this is a serious issue and hope it gets fixed soon. Thanks.

**Comment by benmccann** [comment] 2021-09-03 05:24
this sounds like a duplicate of https://github.com/sveltejs/kit/issues/1198. correct me if i'm wrong. i didn't look super closely

**Closed by benmccann** 2021-09-03 05:24 UTC

**Comment by mishrasatyam** [comment] 2021-09-05 14:12
Hey , it's close to [https://github.com/sveltejs/kit/issues/1777](https://github.com/sveltejs/kit/issues/1777). 
**Please check the issue**, it's really important as fetching from load is an ideal way to get data.
Fetch in load function is not sending credentials in production when svelte-kit is running on https://expense.satyam.life/ and backend server is running on https://expenseapi.satyam.life/

This should be blocker for 1.0.

**Comment by benmccann** [comment] 2021-09-05 15:15
That's not a bug. Please see this comment: https://github.com/sveltejs/kit/issues/1198#issuecomment-826051733

**Comment by mishrasatyam** [comment] 2021-09-05 15:22
> That's not a bug. Please see this comment: [#1198 (comment)](https://github.com/sveltejs/kit/issues/1198#issuecomment-826051733)

Hey, in my case I am using same domain with different subdomains. 

Can you please elaborate a bit more? Thanks.

**Comment by benmccann** [comment] 2021-09-05 15:39
That's still considered a cross-origin request by the browser

**Comment by mishrasatyam** [comment] 2021-09-06 02:15
Thanks I got it. I changed the backend url to api.expense.satyam.life and it works.

**Comment by bomgar** [comment] 2022-08-25 15:06
I don't get it. So a cookie on `.example.com` is not forwarded when my sveltekit server is on `webapp.example.com` and my API is on `api.example.com`.

This is a bit annoying. How would I handle this in the load function then?
