### ISSUE TITLE
transformPageChunk only applies if it is last step in sequence

### ISSUE THREAD

**Issue by kamerat** [sveltejs/kit#5752] opened 2022-07-29 12:15 UTC
### Describe the bug

When using transformPageChunk in a sequence of handlers, it only works if it is the last argument in the sequence.

Multiple transformPageChunks also does not work. It will only work for the last one.

Maybe this has to do with a race condition on what handle is run first, or is this an invalid way to use sequenes?

### Reproduction

[stackblitz repo](https://stackblitz.com/edit/sveltejs-kit-template-default-11j7bi?file=src%2Fhooks.js,src%2Fapp.html&terminal=dev)

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by kamerat** [comment] 2022-07-29 13:31
We temporarily refactored our multiple handles into one instead of using sequence to make it work.

**Comment by Conduitry** [comment] 2022-07-29 13:33
Duplicate of #4051.

**Closed by Conduitry** 2022-07-29 13:33 UTC
