### ISSUE TITLE
support svelte.config.ts

### ISSUE THREAD

**Issue by Tal500** [sveltejs/kit#5867] opened 2022-08-10 21:10 UTC
### Describe the problem

I think that SvelteKit should accept configuration also via typescript, by `svelte.config.ts` and not just `svelte.config.js`. For example, `vite.config.ts` file is already supported by Vite.

This is not only for "fancy" typescript support, I know that many of you will tell me to use JSDoc instead for simple config.
The real reason it's useful (or the real pain otherwise) is for allowing the config file load other typescript files for a computation in the svelte config file.

### Describe the proposed solution

Load `svelte.config.ts` by SvelteKit, whenever `svelte.config.js` isn't found.
Loading is either via `ts-node`, or by compiling it to JS internally first, need to see how Vite and Playwright had achieved this.

### Alternatives considered

 For doing so you need to compile these typescript files before, and then load them to the `svelte.config.js` file.
This is so bad for automation, and also results with compiled `*.js` files in the working dir.

### Importance

would make my life easier

**Comment by dominikg** [comment] 2022-08-11 06:36
duplicate of #2576

see the discussion in https://github.com/sveltejs/kit/pull/4031 too and also https://github.com/sveltejs/rfcs/pull/59

**Closed** 2022-08-11 06:37 UTC
