### ISSUE TITLE
Layout reset using `+layout@.svelte` is not working as documented

### ISSUE THREAD

**Issue by mabentley85** [sveltejs/kit#6280] opened 2022-08-25 17:33 UTC
### Describe the bug

When creating routing directory structure like this
```
src/routes/
├ (marketing)/
│ ├ +layout@.svelte
│ └ about/
│   └ +page.svelte
├ +page.svelte
└ +layout.svelte
```
I assume that the layout for the route `/about` should only be what is included in the "Marketing" `+layout@.svelte` file and not inherit anything from the root `+layout.svelte` file. Currently the `/about` page is inheriting both layouts.

Am I understanding how this should work correctly?

### Reproduction

Example Project: https://stackblitz.com/edit/sveltejs-kit-template-default-6fo4bq?file=src/routes/(marketing)/+layout@.svelte 

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (24) x64 Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
    Memory: 31.60 GB / 48.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /opt/local/bin/watchman
  Browsers:
    Brave Browser: 103.1.41.100
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5260.0
    Edge: 104.0.1293.63
    Firefox: 100.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.86 => 1.0.0-next.87 
    @sveltejs/kit: ^1.0.0-next.435 => 1.0.0-next.439 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment] 2022-08-25 17:42
`+layout@.svelte` means 'inherit directly from the root layout'. (Everything inherits from the root layout eventually.) In this case, it's not doing any work, since `(marketing)/+layout@.svelte` already inherits directly from the root layout.

In other words, this is working as intended. What are you trying to achieve?

**Comment by mabentley85** [comment] 2022-08-25 18:09
Hmm, OK.

I was thinking that the root `+layout.svelte` would be globally applied unless a "reset" layout existed in a child directory. At that point a new layout hierarchy would begin.

A more specific (incorrect) example
```
src/routes/
├ (auth)/
│ ├ +layout@.svelte
│ ├ signin/
│ | └ +page.svelte
| └ signup/
|   └ +page.svelte
├ +page.svelte
├ +layout.svelte
└ Many more routes...
```
The `/signin` and `/signup` pages should have a very minimal layout as set in the "Auth" `+layout@.svelte`. Where as most every other page will use the root `+layout.svelte`.

So to accomplish this now, I should create another group to contain all of the other routes that I want to have this more "global" layout with headers and footers etc...

Correct Example (?)
```
src/routes/
├ (auth)/
│ ├ +layout.svelte
│ ├ signin/
│ | └ +page.svelte
| └ signup/
|   └ +page.svelte
└ (global)
  ├ +page.svelte
  ├ +layout.svelte
  └ Many more routes...
```
Thanks for your help!

**Comment by dummdidumm** [comment] 2022-08-25 18:12
Yes, this is how you would do it with groups. If it's only about UI, then as an alternative you could also add an if clause to your root layout and switch between the minimal and more advanced layout depending on the url - you choose what fits better for you. 
Closing since this isn't a bug and the question has been answered.

**Closed** 2022-08-25 18:12 UTC

**Comment by akkie** [comment] 2022-08-29 16:08
What is if the error page should also inherit from the layout in (global)? It seems that currently the error page needs to be located at the root level. But if I now add a layout for that on the root level, every other layout will then inherit from it. Am I correct?

**Comment by dummdidumm** [comment] 2022-08-29 16:12
Honestly, I haven't tried that one yet, but in theory you should be able to place you `+error.svelte` inside your `(global)` group so it inherits that layout. What you can't do is occupy the same route with multiple (error) pages.

**Comment by akkie** [comment] 2022-08-29 16:20
I have tried to put the `+error.svelte` file into the (global) group. It doesn't work for me. It will not use my custom error page. Instead it shows the framework default page:

```
404
Not found: /how-it-works
Error: Not found: /how-it-works
    at resolve (file:///Users/akkie/.../app/node_modules/@sveltejs/kit/src/runtime/server/index.js:430:14)
```

**Comment by akkie** [comment] 2022-08-29 16:26
@Rich-Harris @dummdidumm Should I create a bug for that?

**Comment by dummdidumm** [comment] 2022-08-29 17:57
Oh you're having a 404 not found case. This always will show the root error page in the root layout. To do what you want, create a `[...rest]/+page.svelte` page at the appropriate place and show your error page content ("not found, go here instead" or whatever) there.

**Comment by akkie** [comment] 2022-08-29 19:15
Thank you for your answer. I would like the handle 404 and also errors globally with the error page. If I understand that correct, then currently it's not possible to use that page in a layout group, right? This means that if I want to style that page with a layout, it needs to be placed on the root level, right? But then all other layouts will inherhit from that layout, because there is no reset. Am I right or do I miss something?

**Comment by dummdidumm** [comment] 2022-08-29 19:28
Maybe we are talking past each other. What I mean is doing the following:
![image](https://user-images.githubusercontent.com/5968653/187282284-683f6d73-5453-4f4f-a9c6-c2633e243272.png)
`[...notFound]/+page.svelte` will be shown for all URLs the user enters that cannot be found. You can place that inside a group so your root layout can stay blank.
If both `[...notFound]/+page.svelte` and `+error.svelte` should look the same, then you can import one into the other and thereby reuse it as a regular component.

**Comment by akkie** [comment] 2022-08-29 20:01
Yes, I understand that. But the +error.page cannot be styled with a layout, because the root layout needs to be blank and actually the error page needs to be located also in the root. This means that the error page will inherhit the blank layout.

If it would be possible to place the error page in a layout group, then it could inherit from that layout. The other solution would be to provide a reset, so that a layout in a group does not inherhit from the root layout. In this case the error page can be placed in the root folder and would inherhit from the root layout.

**Comment by dummdidumm** [comment] 2022-08-30 12:41
You are allowed to place your error page in a layout group, and it will render inside that layout if the error comes from within that tree.
If you want the error page at the root, you can import the desired `+layout.svelte` as a regular component and reuse it that way, or put its UI in a reusable UI component.
