### ISSUE TITLE
afterNavigate callbacks get registered too late when importing opentelemetry dependency

### ISSUE THREAD

**Issue by crisguitar** [sveltejs/kit#5919] opened 2022-08-16 10:46 UTC
### Describe the bug

We noticed that the logic we have in the `afterNavigate` was not being called when expected. After investigating we found that importing `@opentelemetry/context-zone` somehow messes up with the registration of the after navigate functions and instead of being called when the component first loads, they are called when you leave the component.

### Reproduction

I created a [repository](https://github.com/crisguitar/after-navigate-issue) where you can see the normal operation and the affected one side by side. Just run the app `npm run dev` and use the links to navigate and see the order of the events.

https://github.com/crisguitar/after-navigate-issue

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 113.47 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.10.0 - /opt/homebrew/bin/node
    npm: 7.24.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.1
    Firefox Developer Edition: 103.0
    Safari: 15.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64
    @sveltejs/adapter-node: ^1.0.0-next.86 => 1.0.0-next.86
    @sveltejs/kit: next => 1.0.0-next.405
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.4
```

### Severity

blocking an upgrade

**Comment by crisguitar** [comment] 2022-08-17 13:15
Issue in opentelemetry: https://github.com/open-telemetry/opentelemetry-js/issues/3171

**Comment by vmarchaud** [comment] 2022-08-17 17:03
I'm one of the maintainer of the js implementation of opentelemetry, just wanted to add that the issue isn't with opentelemetry itself but rather one of the optional dependency of our browser sdk: zonejs. I suppose that the heavy monkeypatching of zone might break svelte at some point

**Comment by benmccann** [comment] 2022-08-17 21:21
Thanks for the update. I'll go ahead and close this since it sounds like the issue is in zonejs

**Closed by benmccann** 2022-08-17 21:21 UTC
