### ISSUE TITLE
CSP: 'unsafe-inline' is required when using bind:clientWidth

### ISSUE THREAD

**Issue by pimdewit** [sveltejs/kit#10928] opened 2023-10-26 09:52 UTC
### Describe the bug

When using `bind:clientWidth` (amongst others), an iframe is generated to keep track of it's parents sizing:

```html
<iframe style="display: block; position: absolute; top: 0; left: 0; width: 100%; height: 100%; overflow: hidden; border: 0; opacity: 0; pointer-events: none; z-index: -1;" aria-hidden="true" tabindex="-1" src="about:blank"></iframe>
```

the style attribute appended to this element makes it tricky to keep CSP's strict, to a point where 'unsafe-inline' is required

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-zemjvc

### Logs

```Shell
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-lJ7/G2Js+ZVE8z76tKAxfzSKR8TjT9mYsP+sBJmuNtI='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

### System Info

```Shell
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M2
    Memory: 66.72 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.96
    Chrome Canary: 120.0.6090.0
    Edge: 118.0.2088.69
    Firefox Nightly: 120.0a1
    Safari: 17.1
    Safari Technology Preview: 17.4
  npmPackages:
    @sveltejs/adapter-vercel: ^3.0.3 => 3.0.3
    @sveltejs/kit: ^1.27.1 => 1.27.1
    svelte: ^4.2.2 => 4.2.2
    vite: ^4.5.0 => 4.5.0
```

### Severity

serious, but I can work around it

**Comment by Jerboas86** [comment] 2023-11-06 12:32
probably duplicate [#8607](https://github.com/sveltejs/svelte/issues/8607)

**Comment by dummdidumm** [comment] 2023-12-09 15:15
Closing as duplicate of https://github.com/sveltejs/svelte/issues/8607

**Closed by dummdidumm** 2023-12-09 15:15 UTC
