### ISSUE TITLE
Parent element's unique class repeating on all the child elements

### ISSUE THREAD

**Issue by babakfp** [sveltejs/kit#2398] opened 2021-09-10 17:38 UTC
### Describe the bug

Hi
As you see the parent's class gets repeated on its all child elements.
![Screenshot 2021-09-10 102640](https://user-images.githubusercontent.com/44144724/132893915-0e4703f7-8970-4808-a67d-30e28990e007.png)
![Screenshot 2021-09-10 102704](https://user-images.githubusercontent.com/44144724/132893920-3d829a2b-7049-4267-9954-9eed77404b25.png)

### Reproduction

https://github.com/babakfp/sveltekit-unique-class-repetition

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 6.67 GB / 15.84 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.22.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.38)
    Internet Explorer: 11.0.19041.906
```
```


### Severity

annoyance

### Additional Information

### Severity
It won't look good for Sveltekit on v1.0 public release.

**Comment by dominikg** [comment] 2021-09-10 18:35
does this happen on build too? During dev vite-plugin-svelte enforces this to enable an improved hmr experience when editing css

**Comment by babakfp** [comment] 2021-09-10 19:29
> does this happen on build too?

No. This is the build result:
![Screenshot 2021-09-10 122034](https://user-images.githubusercontent.com/44144724/132906357-e31ae6e6-f367-4b2b-b2ee-0745cc70abf2.png)

Is it going to be like this in the v1.0 release? It's not pleasant.

**Comment by dominikg** [comment] 2021-09-10 19:37
without it your components local state would reset during hmr updateevery time you add or remove a css selector which is a lot more unpleasant than a few extra scope classes during dev only. 

this isn't caused by sveltekit so I'm closing here. If you see a better way to get css hmr updates working without this, please file an issue over at vite-plugin-svelte

**Closed by dominikg** 2021-09-10 19:37 UTC

**Comment by babakfp** [comment] 2021-09-10 21:14
What if I add an attribute instead of a class? This HMR thing going to work then or not? I don't know how it works but is it possible to use something like `data-vite-hmr="FKD*%0ruj"`?

@dominikg

**Comment by dominikg** [comment] 2021-09-10 21:24
no, the svelte compiler uses css class for scoping, not attributes. vite-plugin-svelte only changes the generated value to be a hash of the filename instead of a hash of the css content. 

if you have technical concerns or actual reproducible bugs i'm eager to learn more, but if this is an aesthetic issue i'm afraid thATS the way it is.
