### ISSUE TITLE
SvelteKit iOS Safari Crash

### ISSUE THREAD

**Issue by smhussain5** [sveltejs/kit#10835] opened 2023-10-05 20:17 UTC
### Describe the bug

**PROBLEM**: [SvelteKit tutorials](learn.svelte.dev/tutorial/) on iOS Safari repeatedly crashes with the error message "A problem repeatedly occured on 'learn.svelte.dev/tutorial/'."

_NOTE_: This is my first time raising an issue on GitHub, so there may be mistakes in reporting errors. I don't think I can reproduce the error via repo/REPL because it seems to be a browser issue but I am unsure. Apologies for any inconveniences with submission. Thank you in advance!

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Severity

annoyance

**Comment by geoffrich** [comment] 2023-10-05 21:06
Duplicate of https://github.com/sveltejs/learn.svelte.dev/issues/416 - it's an issue with web containers on iOS.

**Closed by geoffrich** 2023-10-05 21:06 UTC
