### ISSUE TITLE
`crypto.randomUUID()` fails on mobile in Dev

### ISSUE THREAD

**Issue by dangelomedinag** [sveltejs/kit#7726] opened 2022-11-19 14:47 UTC
### Describe the bug

```svelte
<!-- routes/+page.svelte -->
<script>
	let arr = [];
	const add = () => (arr = [{ id: crypto.randomUUID() }, ...arr]);
</script>

<button on:click={add}>add</button>
{#each arr as item (item.id)}
	<p>{item.id}</p>
{/each}
```
```bash
npm run dev -- --host

  VITE v3.2.4  ready in 681 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.X.X:5173/
```

open Network in dev mode on ***mobile*** and click add button. Not working
deploy on vercel [site](https://crypto-mobile-fail.vercel.app/) open on mobile. Working

### Reproduction

# [repo](https://github.com/dangelomedinag/crypto-mobile-fail.git)

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
    Memory: 7.96 GB / 15.41 GB
  Binaries:
    Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.42), ChromiumDev ((@(&"C:/Users/dange/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe" init pwsh --config="C:\Users\dange\AppData\Local\Programs\oh-my-posh\themes\jandedobbeleer.omp.json" --print) -join "`n") | Invoke-Expression)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.88
    @sveltejs/kit: next => 1.0.0-next.551
    svelte: ^3.44.0 => 3.53.1
    vite: ^3.1.0 => 3.2.4
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment] 2022-11-19 14:50
This almost certainly just means you're using an old browser that doesn't implement the Web Crypto API. What browser is it?

**Comment by Rich-Harris** [comment] 2022-11-19 14:51
Oh, except you said it works in prod. That's... bizarre.

**Comment by dangelomedinag** [comment] 2022-11-19 15:11
test in all possible browsers in Android 12 (except iOS) chrome/firefox/samsung internet/edge. It was very difficult to know the problem, since desktop works.

**Comment by repsac-by** [comment] 2022-11-19 15:42
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

>Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID#browser_compatibility).

**Comment by dummdidumm** [comment] 2022-11-19 16:21
That makes sense then - localhost runs on http by default

**Comment by dangelomedinag** [comment] 2022-11-19 16:28
@repsac-by oh, i didn't expect it. maybe there is something i am not understanding should it work on desktop in dev mode which is also not https?

**Comment by repsac-by** [comment] 2022-11-19 16:30
[secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts)

> Locally-delivered resources such as those with http://127.0.0.1 URLs, http://localhost and http://*.localhost URLs (e.g. http://dev.whatever.localhost/), and file:// URLs are also considered to have been delivered securely.

**Comment by Conduitry** [comment] 2022-11-19 18:19
Most browsers do treat HTTP localhost as secure, except not Safari IIRC.

**Comment by Rich-Harris** [comment] 2022-11-19 20:09
Presumably the problem is that the mobile browser is connecting to http://192.168.X.X:5173/ rather than localhost? Not sure there's a lot we can do about that, and it isn't specific to SvelteKit, so I'm inclined to close this as wontfix

**Comment by dangelomedinag** [comment] 2022-11-19 21:09
@Rich-Harris It's certainly not specific to Sveltekit, it's okay to close it, but given the behavior is different in some browsers, a little warning in the docs could prevent someone else from spending hours looking for a 'bug' that never shows up in the console.

**Comment by Rich-Harris** [comment] 2022-11-20 00:06
We just can't be responsible for documenting every aspect of the web platform — we're not MDN (where the secure context limitation is called out at the top of the [page](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)). Closing

**Closed by Rich-Harris** 2022-11-20 00:06 UTC
