### ISSUE TITLE
Circular dependencies throw error 500

### ISSUE THREAD

**Issue by lukeeno** [sveltejs/kit#684] opened 2021-03-25 19:10 UTC
**Describe the bug**
SvelteKit throws an error when using components with circular dependencies. Repository was created with commands shown on SK homepage and almost nothing was changed. I only included components from REPL.

**Logs**
Console
```
Circular dependency: path/to/repo/src/routes/index.svelte -> /src/lib/App.svelte -> /src/lib/Structure.svelte -> /src/lib/C.svelte -> /src/lib/Structure.svelte
```

**To Reproduce**

I created repo with the problem here
https://github.com/lukeeno/recursive-sveltekit

and also REPL with basically the same code, but in REPL it works
https://svelte.dev/repl/c90b530e67c94b8995bf4bb5b7f70d3b?version=3.35.0

**Expected behavior**
Not throwing error and recursively render components as shown in REPL

**Stacktraces**

<details>
  <summary>Browser message</summary>

```
500
Cannot read property 'default' of null

TypeError: Cannot read property 'default' of null
    at path/to/repo/src/lib/C.svelte:7:22
    at Object.$$render (path/to/repo/node_modules/svelte/internal/index.js:1369:22)
    at eval (/src/lib/Structure.svelte:18:197)
    at Proxy.each (path/to/repo/node_modules/svelte/internal/index.js:1335:16)
    at path/to/repo/src/lib/Structure.svelte:15:7
    at Object.$$render (path/to/repo/node_modules/svelte/internal/index.js:1369:22)
    at eval (/src/lib/App.svelte:21:97)
    at Object.$$render (path/to/repo/node_modules/svelte/internal/index.js:1369:22)
    at eval (path/to/repo/src/routes/index.svelte:11:91)
    at Object.$$render (path/to/repo/node_modules/svelte/internal/index.js:1369:22)
```

</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`

```
  System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 1.29 GB / 15.34 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/bin/node
    npm: 7.6.3 - /usr/bin/npm
  Browsers:
    Brave Browser: unknown
    Firefox: 86.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.60 
    svelte: ^3.29.0 => 3.35.0
```

- Your browser Brave Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) unknown (64-bit)

- Your adapter Node

**Severity**

Really severe if you need circular dependencies, but apart from that it's okay

**Additional context**

Is there any workaround with async component loading?

**Comment by Rich-Harris** [comment] 2021-03-25 21:47
I guess this is a Vite issue. It's definitely solvable — SvelteKit used to have an SSR runtime that handled this case, but we removed it because Vite implemented something very similar — though I can't speak to how straightforward it would be to add it to Vite. Looks like there's a couple of related issues already, e.g. https://github.com/vitejs/vite/issues/2258

**Comment by lukeeno** [comment] 2021-03-25 23:22
Thank you. I will watch that issue

**Comment by jnordberg** [comment] 2021-07-27 09:01
Also running into this, was able to work around it with dynamic imports:

```svelte
<script context="module" lang="ts">
    let Component: typeof import('$lib/component.svelte').default
    if (!Component) {
        import('$lib/component.svelte').then((result) => {
            Component = result.default
        })
    }
</script>

<svelte:component this={Component} />
```

**Comment by Buraburaite** [comment] 2021-08-04 01:05
Fix just landed in Vite: https://github.com/vitejs/vite/pull/3950 @Rich-Harris

**Comment by Dev1an** [comment] 2021-08-11 18:21
When I manually install vite v2.5.0-beta.2 using `npm install vite@beta` I'm still seeing these `Circular dependency: ...` messages though.

I'm not sure how to check if svelte kit is actually using that version of vite though... Any hints?

**Comment by Buraburaite** [comment] 2021-08-12 22:25
I believe that Svelte kit is still technically on version 0.0.1 (meaning that they aren't using versioning). Wait until vite 2.5.0 drops and then run something like npm upgrade vite or reinstall svelte kit, is what I would try. The relevant svelte kit package.json has vite as ^2.4.3, so it should not require any action on the svelte team's part.

**Comment by ignatiusmb** [comment] 2021-08-21 12:16
Fix confirmed, thanks for checking them out!

**Closed by ignatiusmb** 2021-08-21 12:16 UTC
Labels: vite
