### ISSUE TITLE
Named route `index.svelte` file can't take a named layout...

### ISSUE THREAD

**Issue by spences10** [sveltejs/kit#4523] opened 2022-04-05 08:06 UTC
### Describe the bug

Example, say you have an index page for a route `src/routes/products/index.svelte` and you have a layout for that route `src/routes/products/__layout-products.svelte` adding the layout to the index of that route `src/routes/products/index@products.svelte` will give a 404 and apply the layout from the top level `__layout.svelte` file.

### Reproduction

https://stackblitz.com/edit/sveltekit-mgtptj

### System Info

```shell
WSL


  System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 14.28 GB / 15.59 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.2/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34
    @sveltejs/kit: next => 1.0.0-next.306
    svelte: ^3.46.6 => 3.46.6
```

### Severity

annoyance

**Comment by spences10** [comment] 2022-04-05 08:12
So, using `index` in the route gives the desired outcome: `localhost:3000/products/index`

**Comment by GeForcez** [comment] 2022-04-05 09:55
Duplicate of #4521

**Closed** 2022-04-05 15:22 UTC
