### ISSUE TITLE
Injecting a style element through @html with Typescript causes an error

### ISSUE THREAD

**Issue by chanced** [sveltejs/kit#1796] opened 2021-07-01 19:16 UTC
**Describe the bug**
Attempting to inject styles through ``{ @html `<style>${styles}</style>` }`` with typescript causes an CssSyntaxError `Unknown word`

For example:
```svelte
<script>
	let styles = '.red { color: "red" }';
</script>

<main>
	{@html `<style>${styles}</style>`}
	<p class="red">temp</p>
</main>

```

**Logs**
```
/Users/chance/Projects/spike/style-inline/src/routes/index.svelte:1:3: Unknown word
CssSyntaxError: /Users/chance/Projects/spike/style-inline/src/routes/index.svelte:1:3: Unknown word
    at Input.error (/Users/chance/Projects/spike/style-inline/node_modules/postcss/lib/input.js:123:16)
    at Parser.unknownWord (/Users/chance/Projects/spike/style-inline/node_modules/postcss/lib/parser.js:518:22)
    at Parser.other (/Users/chance/Projects/spike/style-inline/node_modules/postcss/lib/parser.js:149:12)
    at Parser.parse (/Users/chance/Projects/spike/style-inline/node_modules/postcss/lib/parser.js:59:16)
    at parse (/Users/chance/Projects/spike/style-inline/node_modules/postcss/lib/parse.js:11:12)
    at new LazyResult (/Users/chance/Projects/spike/style-inline/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/chance/Projects/spike/style-inline/node_modules/postcss/lib/processor.js:36:12)
    at transformer (/Users/chance/Projects/spike/style-inline/node_modules/svelte-preprocess/dist/transformers/globalStyle.js:56:67)
    at Object.transform (/Users/chance/Projects/spike/style-inline/node_modules/svelte-preprocess/dist/autoProcess.js:37:12)
    at async style (/Users/chance/Projects/spike/style-inline/node_modules/svelte-preprocess/dist/autoProcess.js:177:33)
```

**To Reproduce**
```
git clone git@github.com:chanced/sveltekit-typescript-inline-style-sscce.git
npm i && npm run dev -- --open
```
**Expected behavior**
The variable `styles` content is properly inserted into the html through ``{ @html `<style>${ styles }</style>`}``

<details>
  <summary>Diagnostics</summary>

```

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 180.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    npm: 7.19.0 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Brave Browser: 79.1.1.23
    Chrome: 91.0.4472.114
    Firefox: 89.0
    Safari: 14.1.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.119
    svelte: ^3.38.3 => 3.38.3

```
</details>

**Severity**
Per Trisox & Kev on Discord:
Something like this will work in the interim: https://svelte.dev/repl/94a169e8063d4c9999dc257b310a9e5c?version=3.38.3

**Comment by adamjkb** [comment] 2021-07-01 19:57
I ran into this issue just a few days ago... But looking at your logs I realized that it is an issue with svelte-preprocess. Without it the code compiles fine, works as expected.

**Comment by chanced** [comment] 2021-07-01 20:19
@adamjkb i should have mentioned it works fine without typescript.

**Comment by dummdidumm** [comment] 2021-07-02 07:41
As @adamjkb points out, this is an issue with preprocessing. But the issue is not `svelte-preprocess`, it's the function which extracts the the script/style contents out of the whole markup. Closing as duplicate of https://github.com/sveltejs/svelte/issues/5292 which also contains some workarounds.

**Closed by dummdidumm** 2021-07-02 07:41 UTC
