### ISSUE TITLE
Vercel: Support image optimization

### ISSUE THREAD

**Issue by mquandalle** [sveltejs/kit#2564] opened 2021-10-06 19:15 UTC
### Describe the problem

Next.js on Vercel supports optimizing images by using the `next/image` React component. This is used to generation multiple versions of the image with different size, pixel density, and file format. This can also happen after the app is build since the optimization is run on the Vercel Edge Network.

The feature is described in more details here : https://vercel.com/docs/concepts/next.js/image-optimization

It is currently not easy to benefit from this feature with a Svelte Kit application hosted on Vercel

### Describe the proposed solution

Create a Svelte version of the `<Image />` component ([documentation](https://nextjs.org/docs/basic-features/image-optimization#image-imports) [source](https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx)). With Svelte it should be possible to implement it entirely as a compiler transformation without the need to use JavaScript at runtime.

### Importance

would make my life easier

**Comment by bluwy** [comment] 2021-10-07 08:20
Duplicate of #241. I'm not sure if kit should support a vendor locked-in implementation of this. But maybe it makes sense to have an unofficial library that implements this. From the linked PR, there's [imagetools](https://github.com/JonasKruckenberg/imagetools) which does things at build time too.

**Closed as completed by bluwy** 2021-10-07 08:20 UTC
