### ISSUE TITLE
adapter-static build time fetching does not work when `export const prerender = true;` et al. are set

### ISSUE THREAD

**Issue by benthillerkus** [sveltejs/kit#2283] opened 2021-08-25 02:42 UTC
### Describe the bug

According to the [docs](https://kit.svelte.dev/docs#ssr-and-javascript-prerender), files that are being requested via `load` can be fetched once at build time.
This works, but only if flags such as
```JavaScript
export const ssr = false;
export const prerender = true;
```
have not been set.

If they are set, the resources will be requested via client side Javascript.
![image](https://user-images.githubusercontent.com/29630575/130717163-85436e9d-7ff0-45ad-9f7f-ec8c4d07bffe.png)

I don't know if this is expected behaviour or a bug, in the latter case I can create an example repository.

### Reproduction

```JavaScript
<script context="module">

  // The following break SSG:
  // export const prerender = true;
  // export const ssr = false;
  // export const hydrate = false;

  export async function load({ page, fetch }) {
    const fullscreen = await fetch("/shaders/fullscreen.vert");
    const processing = await fetch("/shaders/processing.frag");
    const display = await fetch("/shaders/display.frag");
    return {
      props: {
        vs_fullscreen: await fullscreen.text(),
        fs_processing: await processing.text(),
        fs_display: await display.text(),
      }
    }
  }
</script>

<script>
  import { onMount } from 'svelte';

  export let vs_fullscreen;
  export let fs_processing;
  export let fs_display;

// [...]
</script>
```

```JavaScript
import adapter from '@sveltejs/adapter-static';

export default {
  kit: {
    adapter: adapter(),
    target: '#svelte',
  },
}
```

### System Info

```shell
System:
  OS: Windows 10 10.0.19043
  CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz  
  Memory: 6.11 GB / 15.94 GB
Binaries:
  Node: 16.4.1 - C:\Program Files\nodejs\node.EXE        
  Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 7.20.5 - ~\AppData\Roaming\npm\npm.CMD
Browsers:
  Chrome: 92.0.4515.159
  Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)
npmPackages:
  @sveltejs/adapter-static: next => 1.0.0-next.17        
  @sveltejs/kit: next => 1.0.0-next.156 
  svelte: ^3.38.3 => 3.42.3
```

### Severity

annoyance

**Comment by si3nloong** [comment] 2021-11-26 13:22
@benthillerkus please provide a reproduction.

**Comment by benthillerkus** [comment] 2021-11-26 15:52
> ```js
> const fullscreen = await fetch("/shaders/fullscreen.vert");
> ```

Thinking about it, the behavior is somewhat understandable, because I explicitly disabled SSR. But I wouldn't have expected prerender to count as SSR

[benthillerkus/static-adapter-problem-example](https://github.com/benthillerkus/static-adapter-problem-example)

**Comment by bluwy** [comment] 2021-11-30 16:48
@benthillerkus Do you think there's something to fix in SvelteKit's code, or should this be documented?

**Comment by benthillerkus** [comment] 2021-11-30 17:15
Right now `export const ssr = true` overrides `export const prerender = true`. I would suggest doing the opposite.
Also giving warnings when your "wishes" can not be respected, similar to when you try to have a load function on a prerendered component would be good.

**Comment by Rich-Harris** [comment] 2022-04-26 16:04
Closing as out of date, since `export const ssr` is no longer a thing (use `ssr: false` in hooks)

**Closed by Rich-Harris** 2022-04-26 16:04 UTC
Labels: pkg:adapter-static, p3-edge-case
