### ISSUE TITLE
Allow adapters to pass in platform specific context

### ISSUE THREAD

**Issue by fezproof** [sveltejs/kit#3426] opened 2022-01-20 04:10 UTC
### Describe the problem

> Related #2844 #2807

As of #3384, hooks and endpoints receive a standard Request object. This simplified and standardised the API for adapters a lot, but also means that no custom context can be passed into the app for the developer to access.

As an example, when using the `adapter-cloudflare` and deploying to Cloudflare pages, you can pass in KV stores and Durable Objects to your functions. With the current Cloudflare adapter, you cannot access the env that is being passed in.
```ts
export default {
	async fetch(req, env) { // All context needed in env
		// ...
		if (url.pathname.startsWith(prefix)) {
			/** @type {Response} */
			const res = await env.ASSETS.fetch(req); // <-- env used to get static assets
	         // ...
		try {
			return await app.render(req); // <-- env not passed to the app
		} catch (e) {
                // ..
```

With the new `Request` `Response` type pattern implemented, it is now not possible to pass it in at all.

This would also be relevant to Netlify, Vercel, and any custom adapter for larger teams using something like Azure or AWS.

### Describe the proposed solution

The most straight forward way to solve this would be to pass in the request to `app.render` as part of an object, with the adapter environment passed in as another
```ts
return await app.render({ request, env });
```
This would be another breaking change for the adapter API, but shouldn't change anything for applications, as the request is already passed into handlers as part of an object
```ts
export async function post({ params, request, env }) {
  await env.TodoList.put("Task", "Clean Kitchen")
  const out = await env.TodoList.get("Task");
```

Another generic type should also be exposed to Handler and Hook functions to allow typing for the environment.

### Alternatives considered

There are possibilities of using globals, but this could cause issues in most environments.

### Importance

would make my life easier

### Additional Information

This is my first issue here, but am really impressed with how everything is amazing with svelte kit so far. Absolutely an inspiration <3
Am happy to create a PR for this if the changes make sense.
Hello from Perth Australia!

**Comment by benmccann** [comment] 2022-01-20 05:03
Agreed that this is needed :smile: Closing as duplicate of https://github.com/sveltejs/kit/issues/2426

**Closed by benmccann** 2022-01-20 05:03 UTC
Labels: enhancement, adapters - general

**Comment by tylerbrostrom** [comment] 2022-01-20 05:14
@benmccann possible to opt for this issue over #2426, as this issue better illustrates the problem and proposes a possible solution?
