### ISSUE TITLE
Sourcemap for "/.../...svelte" points to missing source files (if empty script tag)

### ISSUE THREAD

**Issue by iocron** [sveltejs/kit#2029] opened 2021-07-28 12:09 UTC
### Describe the bug

Warning/Error Message "Sourcemap for /.../...svelte points to missing source files" happens on a simple import in __layout.svelte, as long as the file contains only content, but if there is a <script> tag with code (e.g. <script>abc=123</script>), then the error message doesn't appear. 

### Reproduction

Add the following to __layout.svelte: 

```
<script>
import Footer from '$lib/footer/Footer.svelte';
</script>

<Footer />
```

and create the file lib/footer/Footer.svelte without any script tag and only text, e.g.: abc

Run `npm run dev`

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 121.87 MB / 1.94 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 7.20.1 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.138
    svelte: ^3.34.0 => 3.41.0
```

### Severity

annoyance

**Comment by Mlocik97** [comment] 2021-07-28 12:44
I got same problem when I had __layout.svelte file, but index.svelte was missing... do You have at least empty index.svelte file present?

**Comment by dominikg** [comment] 2021-07-28 13:08
additional context: #2001

**Comment by benmccann** [comment] 2021-07-28 16:24
Here's the warning I get:

>Sourcemap for "src/routes/index.svelte" points to missing source files
Sourcemap for ".svelte-kit/dev/components/layout.svelte" points to missing source files

Here's the sourcemap definitions:

```
SourceMap {
  version: 3,
  mappings: ';;;;;;;;',
  names: [],
  sources: [ 'src/routes/index.svelte' ]
}
SourceMap {
  version: 3,
  mappings: ';;;;;;;',
  names: [],
  sources: [ '.svelte-kit/dev/components/layout.svelte' ]
}
```

Those files definitely exist. This seems like a Vite bug

**Comment by benmccann** [comment] 2021-08-04 04:11
this should be fixed the next time a release of svelte is cut: https://github.com/sveltejs/svelte/pull/6598

**Closed by benmccann** 2021-08-04 04:11 UTC
Labels: bug, vite

**Comment by jdgamble555** [comment] 2022-04-09 00:28
The error is back in v1.0.0-next.310

**Comment by dominikg** [comment] 2022-04-09 10:26
caused by sourcemaps created by svelte-preprocess, fix pending here https://github.com/sveltejs/svelte-preprocess/pull/500

**Comment by jaskaransarkaria** [comment] 2022-04-11 17:53
I have the error too, not sure how to fix this:

```
The request url "/home/jaskaran/repos/website/static/fonts/CaviarDreams.ttf" is outside of Vite serving allow list.

- /home/jaskaran/repos/website/src/lib
- /home/jaskaran/repos/website/src/routes
- /home/jaskaran/repos/website/.svelte-kit
- /home/jaskaran/repos/website/src
- /home/jaskaran/repos/website/node_modules

Refer to docs https://vitejs.dev/config/#server-fs-allow for configurations and more details.

The request url "/home/jaskaran/repos/website/static/fonts/regular.ttf" is outside of Vite serving allow list.
Sourcemap for "/home/jaskaran/repos/website/src/routes/__layout.svelte" points to missing source files
Sourcemap for "/home/jaskaran/repos/website/src/routes/index.svelte" points to missing source files
```

**Comment by dummdidumm** [comment] 2022-04-14 07:36
Please install the latest version of `svelte-preprocess` which hopefully fixes this.
