### ISSUE TITLE
500 error on client-side render: devalue.stringify fails to generate valid JSON in utils.js:serialize_data_node()

### ISSUE THREAD

**Issue by ncoder** [sveltejs/kit#9371] opened 2023-03-09 00:56 UTC
### Describe the bug

a load() handler returns lots of strings, some of which contain extended characters.

in serialize_data_node(), svelte uses devalue to turn it into a json string.
```js
	const stringified = devalue.stringify(node.data);
```

later, on the client,  response.json() gets called and fails because the json is invalid.

### Reproduction

I have a 30k line payload causing the trouble... so its' a bit hard to pinpoint it, but you can get an idea of what can cause the problem with this toy snippet, which reproduces the basic problem:

```js
> JSON.parse(devalue.stringify(decoder.write(Buffer.from([0x00,0x11]))))

> const devalue = await import('devalue');
> const { StringDecoder } = require('node:string_decoder');
> const decoder = new StringDecoder('utf8');

// intentionally bad input string:
> devalue.stringify(decoder.write(Buffer.from([0x00,0x11])))
'["\\u0000\x11"]'
> JSON.parse(devalue.stringify(decoder.write(Buffer.from([0x00,0x11]))))
Uncaught SyntaxError: Unexpected token ◄ in JSON at position 8

// expected it would roundtrip fine like built-in:
> JSON.parse(JSON.stringify(decoder.write(Buffer.from([0x00,0x11]))))
'\x00\x11'
```
 

### Logs

```Shell
I get a variety of errors on the client, depending on which character is bad

Bad control character in string literal in JSON at position 18230
Uncaught SyntaxError SyntaxError: Unexpected token  in JSON at position 18168
```

### System Info

```Shell
node: 'v16.19.0'
devalue: "4.2.0",
svelte: "3.55.0",
```

### Severity

serious, but I can work around it

**Comment by ncoder** [comment] 2023-03-09 01:04
https://github.com/Rich-Harris/devalue/issues/6

**Comment by Conduitry** [comment] 2023-03-09 01:08
Are you serving your app in a way that it is not getting the appropriate `charset=utf-8` part of the `Content-Type` header? That was the situation I was trying to deal with in that devalue issue.

**Comment by gtm-nayan** [comment] 2023-08-22 07:02
This should've been fixed by https://github.com/Rich-Harris/devalue/pull/57, at least as far as devalue won't generate JSON with invalid characters, 

but your HTML of course needs to have the correct encoding set for the embedding HTML document to parse correctly as well

**Comment by eltigerchino** [comment] 2024-11-25 08:09
Closing this as I cannot reproduce the error from the code snippet using the latest version of devalue 5.1.1

**Closed by eltigerchino** 2024-11-25 08:09 UTC
