### ISSUE TITLE
Dynamic routes + shadow endpoints. Broken links.

### ISSUE THREAD

**Issue by bradleyg** [sveltejs/kit#3929] opened 2022-02-15 17:36 UTC
### Describe the bug

When navigating to/from dynamic routes (`/[something].svelte/`) the content of the page isn't updated (although the URL is updated).

### Reproduction

1. Navigate to https://sveltekit-bug.vercel.app/page/foo
2. Click "bar" and see the content remains "foo" although the URL shows "bar"
3. Refresh the page, content now shows "bar".

Full project code: 
https://github.com/bradleyg/sveltekit-bug/

Sample code:
```js
# src/routes/page/[page].js

export async function get({ params }) {
  return {
    body: { params },
  };
}
```
```svelte
# src/routes/page/[page].svelte

<script>
  export let params;
</script>

<a href={`/page/foo`}>foo</a>
<a href={`/page/bar`}>bar</a>
<h1>{params.page}</h1>
```

### System Info

```shell
Safari, Chrome
```

### Severity

serious, but I can work around it

**Comment by mrkishi** [comment] 2022-02-15 18:16
Duplicate of #3727 with fix #3925 incoming.

**Closed** 2022-02-15 18:24 UTC
