### ISSUE TITLE
Prettier formatting doesn't work when SvelteKit installed with pnpm

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#6060] opened 2022-08-19 05:31 UTC
### Describe the bug

After generating new SvelteKit project with pnpm, formatting of svelte files doesn't work.

### Reproduction

1. Generate new SvelteKit project, with prettier formatter
```bash
pnpm create svelte@latest kit-prettier
```
2. `cd kit-prettier`
3. `pnpm install`
4. `pnpx prettier src/**/*.svelte --write`
5. Error

What's more, VSCode with prettier plugin installed can't format Svelte files, failing with the following error:
```
Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser
```

### Severity

annoyance

### Additional Information

I recognize that the team is aware of this issue because in package.json, the "format" command includes a flag that makes formatting work:
`prettier --write --plugin-search-dir=. .`

However, this doesn't work for VSCode prettier plugin, which can't locate the svelte-prettier-plugin.

The solution would be to add the following lines in `.prettierrc`
```
"pluginSearchDirs": ["."],
"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
```

With this in place, the VSCode formatting would work and scripts in `package.json` won't need to have the `--plugin-search-dir` flag.

Related issue: https://github.com/sveltejs/prettier-plugin-svelte/issues/155

**Comment by dummdidumm** [comment] 2022-08-19 07:39
This is a duplicate of https://github.com/sveltejs/prettier-plugin-svelte/issues/155 . It's unrelated to SvelteKit, it would happen in all pnpm repos of this kind. The linked issue contains several workarounds, because unfortunately it's not in our hands to fix this, this is an upstream problem.

**Comment by ebeloded** [comment] 2022-08-19 08:21
This issue highlights that every new SvelteKit project initialized with pnpm doesn't have the formatting working, even though it can be fixed in this repo.
The frustration I have is that every time I create a new SvelteKit project, I have to update the `.prettierrc` file, to make the formatting of Svelte files work. This can be fixed in this repo by making the needed adjustments to the config file, no?

**Comment by dummdidumm** [comment] 2022-08-19 08:48
Oh I see, so this is like a feature request to add the solution to the starter template - reopening then.

**Closed** 2022-08-20 17:08 UTC
Labels: enhancement, pkg:create-svelte, p2-nice-to-have
