### ISSUE TITLE
What npm reports as the latest version of SvelteKit and adapter-node

### ISSUE THREAD

**Issue by nstuyvesant** [sveltejs/kit#2013] opened 2021-07-25 22:05 UTC
### Describe the problem

When typing `npm outdated` in a SvelteKit project, 
<img width="761" alt="Screen Shot 2021-07-25 at 5 58 38 PM" src="https://user-images.githubusercontent.com/5770938/126914755-8b7e7031-6f46-4ef9-8085-d050e5237feb.png">
npm reports the latest version of @sveltejs/kit and @sveltejs/adapter-node as 1.0.0-next.1 and 1.0.0-next.0 respectively.

My assumption is this is because there is not yet a 1.0 version.

### Describe the proposed solution

As SvelteKit is not yet released but getting close, would it make sense to make the latest version equate to the latest next (1.0.0-next.137 and 1.0.0-next.35 at the time of this writing)? Then whenever someone does an `npm outdated`, they won't get @sveltejs/adapter-node and @sveltejs/kit in the list if they're really up-to-date.

### Alternatives considered

Not change anything.

### Importance

nice to have

**Comment by benmccann** [comment] 2021-07-26 18:05
Duplicate of https://github.com/sveltejs/kit/issues/686

**Closed by benmccann** 2021-07-26 18:05 UTC
