### ISSUE TITLE
Load using url not rerun in +server.layout.js

### ISSUE THREAD

**Issue by MajorBreakfast** [sveltejs/kit#6353] opened 2022-08-28 17:25 UTC
### Describe the bug

Recently it was introduced that SvelteKit intelligently re-runs `load()` functions only when necessary.

- `load()` using `url` prop in a `+layout.js` is rerun after every navigation (this is correct)
- In `+layout.server.js` this behavior isn't working. Instead, it doesn't re-run after navigations

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-yiw4n9?file=src/routes/+layout.server.js

- open `src/routes/+layout.server.js`
- rename `src/routes/+layout.server.js` to `src/routes/+layout.js`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.67 
    @sveltejs/kit: next => 1.0.0-next.445 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.9
```

### Severity

serious, but I can work around it

### Additional Information

Not a blocker for me. I just wanted to report it with a reproduction so that it is tracked

**Comment by dummdidumm** [comment] 2022-08-28 17:45
Duplicate of #6349

**Closed by dummdidumm** 2022-08-28 17:46 UTC
