### ISSUE TITLE
Trouble with update or fresh install (/node_modules/sites/kit.svelte.dev/ not exist)

### ISSUE THREAD

**Issue by arjarn** [sveltejs/kit#7857] opened 2022-11-28 21:21 UTC
### Describe the bug

Hi, 

I'm having issue with updating my SK app, after 'npm run dev'  : 

_error when starting dev server:
Error: ENOENT: no such file or directory, open 'C:\Data\Svelte\fresh\node_modules\sites\kit.svelte.dev\scripts\types\special-types/$env+static+private.md'
    at Object.openSync (node:fs:586:3)
    at Object.readFileSync (node:fs:454:35)
    at read_description (file:///C:/Data/Svelte/fresh/node_modules/@sveltejs/kit/src/core/sync/write_ambient.js:17:21)
    at template (file:///C:/Data/Svelte/fresh/node_modules/@sveltejs/kit/src/core/sync/write_ambient.js:33:3)
    at write_ambient (file:///C:/Data/Svelte/fresh/node_modules/@sveltejs/kit/src/core/sync/write_ambient.js:58:3)
    at Module.init (file:///C:/Data/Svelte/fresh/node_modules/@sveltejs/kit/src/core/sync/sync.js:36:2)
    at dev (file:///C:/Data/Svelte/fresh/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:34:7)
    at configureServer (file:///C:/Data/Svelte/fresh/node_modules/@sveltejs/kit/src/exports/vite/index.js:543:17)
    at createServer (file:///C:/Data/Svelte/fresh/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:61815:30)
    at async CAC.<anonymous> (file:///C:/Data/Svelte/fresh/node_modules/vite/dist/node/cli.js:707:24)_

Same error with fresh install.
Directory 'node_modules\sites\kit.svelte.dev\' not exists.

### Reproduction

Simple ^^

npm create svelte@latest
npm install
npm run dev

### System Info

```Shell
Win11, node v17.9.0 and npm v8.17.0
```

### Severity

blocking an upgrade

**Comment by liborvanek** [comment] 2022-11-28 21:29
This is an issue with @sveltejs/kit@1.0.0-next.566, downgrading to 565 helps.

**Comment by kellenmace** [comment] 2022-11-28 22:06
I'm getting this error when trying to update a SvelteKit app from 528 -> 529 🤷‍♂️

**Comment by kellenmace** [comment] 2022-11-28 22:12
Duplicate of #7856

**Closed** 2022-11-28 22:57 UTC
