### ISSUE TITLE
SvelteKit imports browser version of a package for server side code

### ISSUE THREAD

**Issue by hgl** [sveltejs/kit#1657] opened 2021-06-09 04:31 UTC
**Describe the bug**
When a package offers both node and browser version (via `exports` in `package.json`, if I'm not wrong), SvelteKit favors the browser version at least in endpoints.

**Logs**
See stacktrace below.

**To Reproduce**
Create an endpoint at `routes/test.ts`:

```ts
import type { RequestHandler } from "@sveltejs/kit";
import * as crypto from "crypto"
import { SignJWT } from 'jose/jwt/sign'

export const get: RequestHandler = async (req) => {
    const buf = Buffer.from("8f881f5bdb0c0899bfed2dc4e3fc8d03dad54b2eae1839295e928b7c34be14cd", "hex")
    const key = crypto.createSecretKey(buf)
    const jwt = await new SignJWT({ a: 1 })
        .setProtectedHeader({alg: "HS256"})
        .setIssuedAt()
        .sign(key)
    return {
        status: 200,
        body: jwt
    }
}
```

Visit `/test`

**Expected behavior**
Display a signed jwt string in browser.

**Stacktraces**
<details>
  <summary>__vite_ssr_import_1__.default.btoa is not a function</summary>
<pre>
TypeError: __vite_ssr_import_1__.default.btoa is not a function
    at Module.encode (/node_modules/jose/dist/browser/runtime/base64url.js:13:37)
    at FlattenedSign.sign (/node_modules/jose/dist/browser/jws/flattened/sign.js:53:46)
    at CompactSign.sign (/node_modules/jose/dist/browser/jws/compact/sign.js:11:43)
    at SignJWT.sign (/node_modules/jose/dist/browser/jwt/sign.js:17:20)
</pre>
</details>
```

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>
<pre>
npmPackages:
    @sveltejs/kit: next => 1.0.0-next.113 
    svelte: ^3.34.0 => 3.38.2
</pre>
</details>

**Severity**
Very, it prevents the imported package from functioning.

**Additional context**
I'm not sure if this is SvelteKit or Vite bug.

**Comment by dummdidumm** [comment] 2021-06-09 06:28
Duplicate of #1616

**Closed by dummdidumm** 2021-06-09 06:28 UTC

**Comment by JBusillo** [comment] 2021-06-09 06:39
Try changing your import to `import { SignJWT } from 'jose/dist/node/cjs/jwt/sign'`

Although I get a typescript error, it seems to work for me.  I was just experimenting -- I can't explain why it worked.

**Comment by hgl** [comment] 2021-06-09 06:49
@JBusillo what's your svelte kit version? I still get
```
Error: Missing "./dist/node/cjs/jwt/sign" export in "jose" package
```

**Comment by JBusillo** [comment] 2021-06-09 06:53
Version 113.  I installed 'jose' as a dev dependency.  I do get an error in vscode -- Cannot find module 'jose/dist/node/cjs/jwt/sign' or its corresponding type declarations.  I'm using pnpm.

**Comment by hgl** [comment] 2021-06-09 06:59
Strange, I'm on the same version. I do get the type error, but I also get the previously mentioned runtime error (with npm or pnpm). I guess svelte kit just doesn't like me 😂, thanks for the tip though.

**Comment by JBusillo** [comment] 2021-06-09 07:02
I'll look into it more in the morning -- I've been digging into how VITE works for the past few weeks.  But, I just took a sleeping pill, and it's beginning to take effect.  Zzzz.

**Comment by JBusillo** [comment] 2021-06-09 22:17
@hgl Hey Glen -- I looked into it a little more.  Here's a repo which works for me.  Could you try it out and let me know?  Hopefully this can get you on your way.

My browser shows:
```
This is my header
The JWT is: eyJhbGciOiJIUzI1NiJ9.eyJhIjoxLCJpYXQiOjE2MjMyNzY5Mjd9.LUkbcaLoUc_3hOAhjjaGc7AfhS9kIetKQ7rax1E11cs
This is my footer
```
