### ISSUE TITLE
.mjs files are not supported on our CDN

### ISSUE THREAD

**Issue by rob-balfre** [sveltejs/kit#9174] opened 2023-02-22 23:10 UTC
### Describe the bug

```js
kit: {
  adapter: adapter({ fallback: 'index.html' }),
  prerender: { entries: [] }
}
```
We have a very simple SPA setup on our kit projects and we use an archaic corporate CDN to serve our sites.  Big B2B applications, no need for SSR etc.

Since the recent change to output .mjs files our sites no longer work as our CDN doesn't recognise .mjs files correctly...

![Screenshot 2023-02-23 at 9 35 23 am](https://user-images.githubusercontent.com/2623102/220783186-0f0b8063-7e94-4010-be92-5c7aee641f91.png)

Would it be possible to have an escape hatch so we can still generate .js files at build?

Thanks!

### Reproduction

See above

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 107.53 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 108.0.1
    Firefox Nightly: 106.0a1
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @sveltejs/adapter-static: ^2.0.0 => 2.0.1 
    @sveltejs/kit: ^1.5.0 => 1.8.3 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.4
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment] 2023-02-22 23:16
Duplicate of #9141.

**Closed by Conduitry** 2023-02-22 23:16 UTC

**Comment by ctm-balfre-robert** [comment] 2023-02-22 23:27
@Conduitry hehe Rich just asked me to open it on twitter. All good
