### ISSUE TITLE
Improve svelte:head logic, make it easier to understand and more convenient

### ISSUE THREAD

**Issue by codeinforest** [sveltejs/kit#2552] opened 2021-10-04 09:40 UTC
### Describe the problem

The problem is very clear here. I can't override <svelte:head> if I use a promise `{#await}` inside head or just normal component.
- If I use normal component, I can't override head.
- If I use `{#await}` inside `<svelte:head>`, the head will be duplicate when I change the route.

### Describe the proposed solution

My solution is: Allowed to override head component by levels as I mention below, it's will be more logical and easier to understand, improve development experience, SEO ...

- At `__layout.svelte`, create a mockup (or default) schema include title, description, robots,...
- At *.svelte, when `<svelte:head>` exist, override the default schema
- At [slug].svelte, when `<svelte:head>` exist, can be implement from parent or override parent schema.

Example:
`blog/posts.svelte`
```
<svelte:head name="blog">
    <title>Blog</title>
</svelte:head>
```

`blog/[slug].svelte`: Mode - Implement
```
<svelte:head template="blog" mode="implement">
    <title>Article title - {$template.title}</title> <!-- Get title from parent then render as: Article title - Blog -->
</svelte:head>
```

`blog/[slug].svelte`: Mode - Override
```
<svelte:head>
    <title>Article title</title> <!-- Title: Article title -->
</svelte:head>
```

### Importance

would make my life easier

**Comment by rmunn** [comment] 2021-10-04 19:14
Looking at https://github.com/sveltejs/svelte/pull/4250/files, it seems that you can have multiple components with a `<title>` element inside `<svelte:head>`, and the one that will "win" is the last one. (See the unit test in the linked PR for an example). Your issue report only shows `<title>` elements; is there any *other* part of `<svelte:head>` that you need to override besides title? Because as far as I can tell, `<title>` should be overridable just like you want it already.

If you want something that doesn't work, can you please follow the instructions on the issue report? They tell you to provide "A link to a repository that reproduces the issue. Explaining how to reproduce is generally not enough." Without a repository to reproduce the issue that you're facing, I can't figure out what it is that you need that doesn't already work.

**Comment by codeinforest** [comment] 2021-10-05 03:21
> ooking at https://github.com/sveltejs/svelte/pull/4250/files, it seems that you can have multiple components with a `<title>` element inside `<svelte:head>`, and the one that will "win" is the last one. (See the unit test in the linked PR for an example). Your issue report only shows `<title>` elements; is there any _other_ part of `<svelte:head>` that you need to override besides title? Because as far as I can tell, `<title>` should be overridable just like you want it already.

Yes. Title can be change but if you put it on `__layout.svelte` then other route can't change (replace) that title, so any route without `<svelte:head>` will not be set the title, the title will be url and look terrible.
If you use in `[slug].svelte` with dynamic content, the `svelte:head` not be clean/empty previous head, it's keep previous head and append new lines.

**Comment by Rich-Harris** [comment] 2022-04-26 19:08
Closing as no reproduction was provided.

`#await` should be avoided in `<svelte:head>`, however — it doesn't play well with SSR, which is synchronous in SvelteKit. All the async stuff should happen in `load` or in a page endpoint.

A useful pattern is to have a single `<svelte:head>` in the root layout and populate it with [`$page.stuff`](https://kit.svelte.dev/docs/loading#output-stuff).

**Closed by Rich-Harris** 2022-04-26 19:08 UTC
