### ISSUE TITLE
Allow typescript configuration files

### ISSUE THREAD

**Issue by Marr11317** [sveltejs/kit#4102] opened 2022-02-24 02:46 UTC
### Describe the problem

I'd like to use typescript configuration files. 

I've needed it twice in the past week, first to use a custom preprocessor located in the src directory, and second time to use another package in the same monorepo.

It would also enable intellisense and general better dx.

### Describe the proposed solution

This should be fairly easy to implement with [unconfig](https://github.com/antfu/unconfig). I've myself used it a few times. The package is reliable, small and efficient, although the documentation can also use these adjectives.

### Importance

nice to have

**Comment by bluwy** [comment] 2022-02-24 02:51
Duplicate of #2576

**Closed** 2022-02-24 02:51 UTC

**Comment by Marr11317** [comment] 2022-02-24 06:18
see #4105
