### ISSUE TITLE
Prerendering cause headers set in server hooks to disappear in production build

### ISSUE THREAD

**Issue by IslamZaoui** [sveltejs/kit#12715] opened 2024-09-25 13:48 UTC
### Describe the bug

when I set `export const prerender = true;` in the root `layout.ts` causes headers set in server hooks to disappear in production (both vercel and local preview) as discussed in #12691 

### Reproduction

I made a fresh sveltekit project in [this repo](https://github.com/IslamZaoui/svelte-headers-issue) with: 

headers set in `hooks.server.ts`
```ts
// /src/hooks.server.ts
import { sequence } from "@sveltejs/kit/hooks";
import type { Handle } from "@sveltejs/kit";

const handleSecurityHeaders: Handle = async ({ event, resolve }) => {
  const response = await resolve(event);

  response.headers.set("Access-Control-Allow-Origin", "*");
  response.headers.set("X-Frame-Options", "SAMEORIGIN");
  response.headers.set("X-Content-Type-Options", "nosniff");
  response.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  response.headers.set("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
  response.headers.set(
    "Content-Security-Policy",
    "base-uri 'self'; child-src 'self'; connect-src 'self' ws://localhost:* https://vercel.live; img-src https: 'self' data:; font-src 'self' data:; form-action 'self'; frame-ancestors 'self'; frame-src 'self' https://www.youtube-nocookie.com https://vercel.live; manifest-src 'self'; media-src 'self' https: data:; object-src 'none'; style-src 'self' 'unsafe-inline'; default-src 'self'; script-src https://vercel.live 'unsafe-eval' 'self' 'unsafe-inline'; worker-src 'self';"
  );

  return response;
};

export const handle = sequence(handleSecurityHeaders);
```

and root layout:
```ts
// /src/routes/+layout.ts
export const config = {
	runtime: 'edge'
};

export const prerender = true; //when true, headers will not be added
export const ssr = true;

```

then deployed in 2 way:
- prerender set to **True** in this [deployment](https://svelte-headers-issue-n75tffgth-meprojects.vercel.app/) with [securityheaders.com report](https://securityheaders.com/?q=https%3A%2F%2Fsvelte-headers-issue-n75tffgth-meprojects.vercel.app%2F&followRedirects=on)

- prerender set to **False** in this [deployment](https://svelte-headers-issue-r2dybfe62-meprojects.vercel.app/) with [securityheaders.com report](https://securityheaders.com/?q=https%3A%2F%2Fsvelte-headers-issue-r2dybfe62-meprojects.vercel.app%2F&followRedirects=on)

### Logs

```Shell
n/a
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 5.54 GB / 15.77 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\.bun\bin\yarn.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.3.0 - ~\.bun\bin\pnpm.EXE
    bun: 1.1.28 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (125.0.2535.79)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @sveltejs/adapter-vercel: ^5.4.4 => 5.4.4
    @sveltejs/kit: ^2.0.0 => 2.5.28
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.2
    svelte: ^4.2.7 => 4.2.19
    vite: ^5.0.3 => 5.4.7
```

### Severity

serious, but I can work around it

### Additional Information

the workaround is to disable prerendering or add headers to `vercel.json`

**Comment by Conduitry** [comment] 2024-09-25 13:52
Essentially a duplicate of #9408.

**Closed by Conduitry** 2024-09-25 13:52 UTC
