### ISSUE TITLE
PageData types don't update to reflect changes to load function(s)

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#5940] opened 2022-08-16 17:49 UTC
### Describe the bug

Having a `+page.server.ts` load function with no `+page.ts` load function results in `PageData` being `any`

Making changes to `+page.ts` load function means the `PageData` types lag and mismatch.

### Reproduction

Just add and remove some static props to the `load` function return object.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 1.56 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 104.0.5112.79
    Chrome Canary: 106.0.5243.0
    Firefox: 103.0.2
    Safari: 15.6
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.411 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

annoyance

**Comment by dummdidumm** [comment] 2022-08-16 18:12
What do you mean by "lag" - as in, until you save the file?

**Comment by CaptainCodeman** [comment] 2022-08-16 18:31
As in, I save the file but the types don't update, they still show what it was, once. A full build is often needed to get it to see the source changes.

**Comment by ollema** [comment] 2022-08-16 19:33
@CaptainCodeman running `npx svelte-kit sync` _should_ update this but it would be nice if this was automatic (if possible)

**Comment by accuser** [comment] 2022-08-16 19:33
Had similar experience today, but turned out that the response wasn’t sterilisable. Once I’d sorted that out, all was peachy. Not saying that is what is going on here, but thought it worth mentioning.

**Comment by CaptainCodeman** [comment] 2022-08-16 19:45
> running `npx svelte-kit sync` _should_ update this but it would be nice if this was automatic (if possible)

That's unrealistic, it should happen while you work.

**Comment by CaptainCodeman** [comment] 2022-08-16 19:46
> turned out that the response wasn’t sterilisable. Once I’d sorted that out, all was peachy. Not saying that is what is going on here, but thought it worth mentioning.

It's not that, it does it with the simplest props which are all definitely serializable (I added the dates while testing something else)

**Comment by AdrianGonz97** [comment] 2022-08-16 22:47
If it's any help, I've been reloading the vscode window via the command palette any time I've made changes to the returning data of the load function for `+page.ts` and `+layout.ts`. After a window reload, the types are updated to their expected types.

It's obviously not a solution to the problem, but it could be helpful in narrowing down where the problem is.

**Comment by stausmar** [comment] 2022-08-17 05:49
I have similar issues. Sometimes, the PageData type is even shown as `unknown`, although the correct types are imported.

`+page.svelte`

![grafik](https://user-images.githubusercontent.com/40742474/185043977-6f1c172f-9c62-44bf-81ae-99006b8d9064.png)

**Comment by sandstromdev** [comment] 2022-08-17 10:47
I've noticed the same thing with all exports of `./$types`. If you open the `./$types` file, all exports are typed correctly, but when importing them from a `+page.svelte`, they are typed as `any`, `unknown` or `never`. 

As @AdrianGonz97 mentioned, reloading vscode helps, so my guess is that the problem is in vscode not reading the files on each update.

`+page.server.ts`
<img width="389" alt="Screenshot 2022-08-17 at 12 42 51" src="https://user-images.githubusercontent.com/6277526/185099612-a285090b-5fb4-4bfa-b89e-0bb79aaceb9e.png">

`+page.svelte`
<img width="389" alt="Screenshot 2022-08-17 at 12 43 18" src="https://user-images.githubusercontent.com/6277526/185099697-4c03650e-af77-46fd-bd8f-d6d9a24dad8a.png">

**Comment by dummdidumm** [comment] 2022-08-17 12:19
This may be a problem in language-tools.

**Comment by dummdidumm** [comment] 2022-08-17 15:12
@CaptainCodeman could you check if your errors still persist? I'm having trouble to figure out if this is one or multiple issues. The "type doesn't update" issue should be resolved in the latest Svelte for VS Code extension version.

**Comment by CaptainCodeman** [comment] 2022-08-17 15:29
It seems better this morning, with all latest updates.

Still feels a little odd that things only update if you have the dev-server running, but the changes now appear to reflect when it is.

**Closed** 2022-08-17 16:25 UTC
Labels: bug
