### ISSUE TITLE
Invalid routing for trailing slash

### ISSUE THREAD

**Issue by RaeesBhatti** [sveltejs/kit#939] opened 2021-04-09 17:22 UTC
**Describe the bug**
Any request to `/something/` gets redirected to `/something` (trailing slash removed) and `/product` renders `routes/[category]/index.svelte` instead of `routes/product.svelte`.

**Logs**

**To Reproduce**

Demo repo: https://github.com/RaeesBhatti/svelte-routing

Create two files `routes/[product].svelte` and `routes/[category]/index.svelte`. When I go to `/some-product` in the browser, I expect  the page at `routes/[product].svelte` to be rendered, instead `routes/[category/index.svelte]` does.

**Expected behavior**
When I go to `/some-product` in the browser, I expect  the page at `routes/[product].svelte` to be rendered, instead `routes/[category/index.svelte]` does.

**Stacktraces**
<details>
  <summary>Diagnostics</summary>

```
  System:
    OS: macOS 11.2.3
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 5.25 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Edge: 89.0.774.75
    Firefox: 84.0.1
    Safari: 14.0.3
    Safari Technology Preview: 14.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.1.5 
```

- Your browser
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.2 Safari/605.1.15`

- Your adapter: Dev
</details>

**Severity**
Blocking move to Svelte Kit.

**Additional context**

**Comment by Conduitry** [comment] 2021-04-09 17:24
This sounds like a duplicate of #733.

**Comment by RaeesBhatti** [comment] 2021-04-09 17:27
I think there are two issues here. One `/product/` being redirect to `/product` and other being that `/product` renders `routes/[category]/index.svelte`

**Comment by Conduitry** [comment] 2021-04-10 16:03
If you have two routes like `/[foo].svelte` and `/[bar]/index.svelte`, these have equal precedence, and I'm not sure it's well-defined which would be tried first. You should be using [fallthrough routes](https://kit.svelte.dev/docs#routing-advanced-fallthrough-routes) if you don't want a particular page to handle a particular URL.

I don't think we want to distinguish between `/something` and `/something/` as being different URLs, although specifying that the one with the trailing slash is the preferred canonical URL sounds like a reasonable feature, and this can be discussed in #733.

**Closed by Conduitry** 2021-04-10 16:03 UTC
Labels: router

**Comment by RaeesBhatti** [comment] 2021-04-11 05:24
While I honor your choice on this matter, I don't think an open-source router should be strongly opinionated like that. `/something` and `/something/` are two different URLs and forcing them one way or the other means that a lot of websites won't be able to use Svelte Kit because it would break their existing URL structure and hurt SEO.
I think there should be at least an option to disable this behavior.
