### ISSUE TITLE
Allow endpoints to respond with a route instead and pass along a POJO to that route

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#2531] opened 2021-09-30 21:31 UTC
### Describe the problem

Doing any form of SSR friendly form validation / error handling is currently unnecessarily complex and difficult to do. 

 Take this simple form...
```svelte
<!-- src/routes/foo/bar/form.svelte -->
<form action="/foo/bar/form" method="post">
    <input name="email" id="email" />
    <input name="password" id="password" /> 
    <button type="submit">Submit</button>
</form>
```
... that POSTs to this simple endpoint for example:
```javascript
// src/routes/foo/bar/form.js
/** @type {import('@sveltejs/kit').RequestHandler} */
export async function post({ body })
{
    const email = body.get( 'email' )
    const password = body.get( 'password' )

    // Redirect the client back to the form if a field is not filled in correctly
    if ( !email || email.endsWith('@fake-mail.com') || !password ) {
        return { 
            status: 303,
            headers: {
                location: '/foo/bar/form'
            }
        }
    }
    
    // Redirect the client to `/good-job-kiddo`. 
    return {
        status: 303,
        headers: {
            location: '/good-job-kiddo'
        }
    }
}
```

When the endpoint redirects the client back to the form, the user gets no feedback at all on what they did wrong. The form does not display any error messages to inform the user that they need to fill in both fields correctly in order to be redirected to the `/good-job-kiddo` route.

If you dislike redirects to/or large URLs filled with encoded data as much as I do, I have some bad news for you. _There is no other way to ship those error messages back to the form route through a redirect_. At least not that I am aware of.

### Describe the proposed solution

When an endpoint handle `return { status: 303 }` svelte-kit should look at `headers.location` and respond with / return that  route instead. You should also be able to pass a POJO to the route's load function. That POJO should be able to contain whatever you want (form errors, entity data, whatever you find useful).

For lack of a better name the above mentioned POJO is named `feedback` in the example below. `feedback` is passed to the page's load function as `endpointFeedback`.

```javascript
// src/routes/foo/bar/form.js
/** @type {import('@sveltejs/kit').RequestHandler} */
export async function post({ body })
{
    const email = body.get('email')
    const password = body.get('password')

    if ( !email || !password )
    {
        return { 
            status: 303, // Setting status 303 makes the endpoint respond with route: this.headers.location
            headers: {
                location: '/foo/bar/form'
            },
            feedback: { // This will be passed on to the route's load function this endpoint returns instead
                errors: {
                    email: 'Please fill in your email address',
                    password: 'Please fill in your super duper secret password',
                },
                funnyGif: 'https://tenor.com/view/monkey-chango-monkey-phone-monkey-using-phone-monkeymeme-gif-20807050'
            }
        }
    }
    
    return {
        status: 303,  // Setting status 303 makes the endpoint respond with route: this.headers.location
        headers: {
            location: '/good-job-kiddo'
        }
    }
}
```

```svelte
<!-- src/routes/foo/bar/form.svelte -->
<script context="module">
    export async function load({ endpointFeedback })
    {
        return {
            props: {
                errors: endpointFeedback?.errors,
                funnyGif: endpointFeedback?.funnyGif
            }
        }
    }
</script>

<script>
    export let errors
    export let funnyGif
</script>

<form action="/foo/bar/form" method="post">
    <label for="email">Email</label>
    <input name="email" id="email"/>
    { #if errors?.email }<span style="color:red;">{errors.email}</span>{/if}
    
    <label for="password">Password</label>
    <input name="password" id="password"/>
    { #if errors?.password }<span style="color:red;">{errors.password}</span>{/if}
    { #if funnyGif }<img src={funnyGif}" alt="Funny gif"/>{/if}

    <button type="submit">Submit</button>
</form>
```

During the client side hydration step svelte-kit adds a `submit` event listener to `window`. When a form submits, the event handler checks if the form does not have any other submit event listeners. If so, we `preventDefault` and instruct the client side router navigate to the endpoint. Depending on the form `method=""` attribute the client side router's fetch http `method` changes and stuff like relevant `FormData` and such is attached.

### Alternatives considered

None that I haven't mentioned already.

### Importance

would make my life easier

### Additional Information

High chance this is a breaking change, but I'm not sure. Today was my first day poking around svelte-kit's codebase but I still have practically zero idea how svelte-kit works under the hood.  I don't know how difficult this feature request is to realize. 

---
 
Maybe this deservers its own issue, but imma drop this here anyways as it is kinda related:

If svelte-kit's server side router could automatically point paths/urls like `/endpoint/post`, `/endpoint/put`, `/endpoint/del` to the correct endpoint handle, then svelte-kit could detect the method suffix and override the request method. This would make the method attribute entirely neglectable for both javascript and no-javascript clients.

**Comment by UltraCakeBakery** [comment] 2021-09-30 21:33
Any suggestions for a better title and/or way to explain what I want exactly would be highly appreciated 🙏

**Comment by justingolden21** [comment] 2021-10-01 04:46
+1 to this

**Comment by benmccann** [comment] 2021-10-01 05:17
Are you saying you want a way to render a page directly from an endpoint? So in your proposal, using `feedback` and a 303 response code would mean nothing is in the query string and the response body is the HTML of the form submit success page (`'/good-job-kiddo'`)?

**Comment by UltraCakeBakery** [comment] 2021-10-01 06:41
> Are you saying you want a way to render a page directly from an endpoint?

Yes.

> So in your proposal, using feedback and a 303 response code would mean nothing, is in the query string and the response body is the HTML of the form submit success page ('/good-job-kiddo')?

Not sure if I understand your question correctly. 
I'll try to clarify what I want with a different more simplified example:

```javascript
// src/routes/blog/comments.js
/** @type {import('@sveltejs/kit').RequestHandler} */
export function post({ body })
{
    return {
        status: 303,
        feedback: {
            message:  body.get('comment').length ? 'Good job!' : 'Your comment may not be empty'
        },
        headers: {
            location: '/blog/comments'
        }
    }
}
```
```svelte
// src/routes/blog/comments.svelte
<script context="module">
    export function load({ feedback })
    {
        return {
            props: {
                feedback
            }
        }
    }
</script>

<script>
    export let feedback
</script>

{ #if feedback }
    {feedback.message}
{/if}

<form action="/blog/comments" method="post">
    <input name="comment" />
    <button type="submit">Post comment</button>
</form>
```

What should happen is that if you set status to `303` the endpoint should respond with the route you specified in the location header. If you also set `feedback` it should make that available inside the route's `load` function.

**Comment by rmunn** [comment] 2021-10-01 08:06
Is this a duplicate of #1711? And the request in the final paragraph for overriding the request method looks like a dupe of #1046.

**Comment by UltraCakeBakery** [comment] 2021-10-01 09:21
> Is this a duplicate of #1711? And the request in the final paragraph for overriding the request method looks like a dupe of #1046.

Oh, I was not aware of both issues. Not being familiar with all the terminology used makes it hard to find related issues.

I guess this issue could be considered a suggestion for how something like #1711 could be implemented. I don't know if this issue should be closed in favor of continuing the discussion over at #1711. I'll leave that up to maintainers to decide. 

Same story for #1046. Though [I mostly disagree with Rich-Haris](https://github.com/sveltejs/kit/issues/1046#issuecomment-821853716), I don't feel like sharing my two cents in that issue. I've encountered in the past that If I even dare to suggest something that Rich Harris suggested the opposite of, I will be ignored and shamed for at least a month. Rich Harris already has 9 upvotes on the comment I linked. I will virtually die in this community if I dare respond to that comment. I included that last paragraph here to offer a more complete implementation and make sure that technical aspect is kept in mind.

**Comment by benmccann** [comment] 2021-10-01 13:47
I will close this one as a duplicate

**Closed by benmccann** 2021-10-01 13:47 UTC

**Comment by dummdidumm** [comment] 2021-10-01 14:57
> Same story for #1046. Though [I mostly disagree with Rich-Haris](https://github.com/sveltejs/kit/issues/1046#issuecomment-821853716), I don't feel like sharing my two cents in that issue. I've encountered in the past that if I even dare to suggest something that Rich Harris suggested the opposite of, I will be ignored and shamed for at least a month. Rich Harris already has 9 upvotes on the comment I linked. I will virtually die in this community if I dare respond to that comment. I included that last paragraph here to offer a more complete implementation and make sure that technical aspect is kept in mind.

I'm sorry that you feel that way, this certainly isn't the way we want to make people feel if they have a different opinion. Getting ignored can easily happen just because so much else is going on, getting actively shamed shouldn't happen.
