### ISSUE TITLE
bug: vercel adapter tries to import unrelated json file from root

### ISSUE THREAD

**Issue by TorstenDittmann** [sveltejs/kit#5150] opened 2022-06-03 12:38 UTC
### Describe the bug

For example:

If you have a file called `cookie.json` in the root folder of your project and try to import a node module with the same name (in this case `cookie`) from a file located under `$lib/` into a Svelte Route/Component - for some reason the Vercel adapter is trying to import `cookie.json` instead of the node module.

It works fine with `npm run dev` or the static adapter.

```ts
// src/lib/file.ts
export { parse } from 'cookie';
```
```svelte
// src/routes/index.svelte
<script>
   import { parse } from '$lib/file';
</script>
```
```json
// cookie.json
{
    "hello": "world"
}
```

This will work with any import, so it also happens with `import ... from 'appwrite'` and `appwrite.json` and so on.

### Reproduction

https://github.com/TorstenDittmann/svelte-import-bug-repro

### Logs

```shell
➜  repo-fail git:(main) npm run build

> repo-fail@0.0.1 build
> svelte-kit build

vite v2.9.9 building for production...
✓ 17 modules transformed.
.svelte-kit/output/client/_app/immutable/manifest.json                    1.14 KiB
.svelte-kit/output/client/_app/immutable/layout.svelte-8187eef2.js        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/start-5bbfc15c.js                23.66 KiB / gzip: 8.97 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-3d406494.js   0.71 KiB / gzip: 0.49 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-61066a60.js         1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-c3650d4a.js         6.84 KiB / gzip: 2.79 KiB
vite v2.9.9 building SSR bundle for production...
✓ 12 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                        1.09 KiB
.svelte-kit/output/server/index.js                             74.03 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js   0.24 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js    0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js        0.25 KiB
.svelte-kit/output/server/chunks/index-5f038599.js             2.31 KiB
.svelte-kit/output/server/chunks/hooks-1c45ba0b.js             0.00 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-vercel
✘ [ERROR] No matching export in "cookie.json" for import "parse"

    .svelte-kit/output/server/entries/pages/index.svelte.js:2:9:
      2 │ import { parse } from "cookie";
        ╵          ~~~~~

> Build failed with 1 error:
.svelte-kit/output/server/entries/pages/index.svelte.js:2:9: ERROR: No matching export in "cookie.json" for import "parse"
.svelte-kit/output/server/entries/pages/index.svelte.js:2:9: ERROR: No matching export in "cookie.json" for import "parse"
    at failureErrorWithLog (/Users/torstendittmann/Documents/GitHub/repo-fail/node_modules/esbuild/lib/main.js:1611:15)
    at /Users/torstendittmann/Documents/GitHub/repo-fail/node_modules/esbuild/lib/main.js:1257:28
    at runOnEndCallbacks (/Users/torstendittmann/Documents/GitHub/repo-fail/node_modules/esbuild/lib/main.js:1170:65)
    at buildResponseToResult (/Users/torstendittmann/Documents/GitHub/repo-fail/node_modules/esbuild/lib/main.js:1255:7)
    at /Users/torstendittmann/Documents/GitHub/repo-fail/node_modules/esbuild/lib/main.js:1364:14
    at /Users/torstendittmann/Documents/GitHub/repo-fail/node_modules/esbuild/lib/main.js:674:9
    at handleIncomingPacket (/Users/torstendittmann/Documents/GitHub/repo-fail/node_modules/esbuild/lib/main.js:771:9)
    at Socket.readFromStdout (/Users/torstendittmann/Documents/GitHub/repo-fail/node_modules/esbuild/lib/main.js:640:7)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 87.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    npm: 8.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Chrome Canary: 104.0.5100.0
    Firefox: 100.0.1
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.58 => 1.0.0-next.58 
    @sveltejs/kit: next => 1.0.0-next.347 
    svelte: ^3.46.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment] 2022-06-23 16:46
Does this work with other adapters like adapter-node or adapter-static? I'm guessing this might be an esbuild error. Can you reproduce this with a simple non-SvelteKit project using esbuild? If so, it'd be best to file this in the esbuild repo as that's where it would need to be fixed

**Comment by TorstenDittmann** [comment] 2022-06-23 16:54
> Does this work with other adapters like adapter-node or adapter-static? I'm guessing this might be an esbuild error. Can you reproduce this with a simple non-SvelteKit project using esbuild? If so, it'd be best to file this in the esbuild repo as that's where it would need to be fixed

iirc it was working using node or static. I'll try later 👍

**Comment by benmccann** [comment] 2022-06-24 04:51
Yes, it does work with `adapter-node` and I noticed `esbuild` in the stacktrace both of which confirm this is an esbuild issue. Since there's nothing we can do about it, I'm going to go ahead and close this one. Please file an issue at https://github.com/evanw/esbuild/issues

**Closed by benmccann** 2022-06-24 04:51 UTC
