### ISSUE TITLE
Failure serializing Error

### ISSUE THREAD

**Issue by ncoder** [sveltejs/kit#10523] opened 2023-08-10 15:23 UTC
### Describe the bug

This just looks like svelte-kit throws an applicaiton error, tries to serialize it. then fails trying to tell me what my error is.

![image](https://github.com/sveltejs/kit/assets/1332278/53b7cb4f-3c2d-461a-ad22-a76eeffa61bd)

### Reproduction

```js
import { error } from '@sveltejs/kit'

export const load = async ({ params }) => {
	try {	
		const post = await import(`../../../lib/posts/${params.post}.md`)

		return {
			PostContent: post.default,
			meta: { ...post.metadata, slug: params.post } 
		}
	} catch(err) {
		throw error(404, err)
	}
}
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900KF
    Memory: 39.72 GB / 63.86 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22000.120
```

### Severity

serious, but I can work around it

**Comment by ncoder** [comment] 2023-08-10 15:25
ah, right. this code is responsible:
```js
import { error } from '@sveltejs/kit'

export const load = async ({ params }) => {
	try {	
		const post = await import(`../../../lib/posts/${params.post}.md`)

		return {
			PostContent: post.default,
			meta: { ...post.metadata, slug: params.post } 
		}
	} catch(err) {
		throw error(404, err)
	}
}
```

the import fails.

**Comment by benmccann** [comment] 2023-08-10 16:09
Issues without a reproduction will be closed

**Comment by ncoder** [comment] 2023-08-10 18:31
> Issues without a reproduction will be closed

Oh, but please read it. You have everything you need here.

But i made it easier for you to scan..

In any event, this issue is more of a debuggability and API clarity thing. Do what you wish with it.

**Comment by eltigerchino** [comment] 2024-11-14 10:34
Closing due to a lack of a minimal reproduction.

**Closed by eltigerchino** 2024-11-14 10:34 UTC
