### ISSUE TITLE
Vercel Adapter: Edge function settings per route

### ISSUE THREAD

**Issue by enyo** [sveltejs/kit#7927] opened 2022-12-03 11:26 UTC
### Describe the problem

At the moment, the Vercel adapter only has one setting to make all end points run on edge functions.

### Describe the proposed solution

It would be great if this could be done on a route level instead.

### Importance

would make my life easier

**Comment by mquandalle** [comment] 2022-12-03 12:29
Duplicate of #6808

**Closed** 2022-12-03 13:40 UTC
Labels: enhancement, pkg:adapter-vercel
