### ISSUE TITLE
class in svelte applied two times

### ISSUE THREAD

**Issue by mieaw** [sveltejs/kit#10387] opened 2023-07-15 09:47 UTC
### Describe the bug

prod:
![image](https://github.com/sveltejs/kit/assets/133277280/17b4f847-111f-4ef0-8888-eda9164f512c)

dev:
![image](https://github.com/sveltejs/kit/assets/133277280/eba1a2b7-be01-46a8-b3e2-e2307b75d0a1)

### Reproduction

https://github.com/mieaw/class-in-svelte-applied-two-times

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-CPU @ 1.80GHz
    Memory: 17.88 GB / 31.89 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - C:\Windows\system32\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.22.3
    svelte: ^4.0.5 => 4.0.5
    vite: ^4.4.2 => 4.4.4
```

### Severity

blocking an upgrade

### Additional Information

i can work with this issue :/

**Comment by Renkas** [comment] 2023-07-15 10:46
Seems to be duplicate of #10379

**Comment by tcc-sejohnson** [comment] 2023-07-15 20:34
Closed as duplicate 🙂

**Closed** 2023-07-15 20:34 UTC
