### ISSUE TITLE
Infinite loop when accessing certain routes directly

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/kit#1346] opened 2021-05-05 18:47 UTC
**Describe the bug**
I was made aware of a user of my website that there is a nasty infinite loop occuring: https://github.com/mhatvan/markushatvan.com/issues/17

The infinite loop ONLY occurs on the pages /blog, /tags and /categories when accessing it directly on markushatvan.com
For example: markushatvan.com/tags fails while markushatvan.com/about works.

If you check the screenshot that I attached, these are exactly the three url slugs that are outputted from `@sveltejs/adapter-static` which get processed to do a 301.

**To Reproduce**
I was not able to reproduce this locally with a dev or prod build, it seems to occur in combination with Netlify deployment on actual production.

**Expected behavior**
All pages are working without infinite loop.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- Your browser: Brave Browser 1.23.75

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): `adapter-static`
</details>

**Severity**
Bad, since users can't acess certain links.

**Additional context**
<img width="720" alt="Screenshot 2021-05-05 at 20 35 31" src="https://user-images.githubusercontent.com/16797721/117192200-b7ede480-ade1-11eb-8f8b-a4a71fa32841.png">

**Comment by babichjacob** [comment] 2021-05-05 18:57
Possibly related to https://github.com/sveltejs/kit/issues/733

**Comment by benmccann** [comment] 2021-05-05 23:58
It's hard to know what might be occurring here without a reproduction. Do you have code that you can share?

**Comment by mhatvan** [comment] 2021-05-06 12:30
The whole repo is open source, this is one of the routes: https://github.com/mhatvan/markushatvan.com/tree/master/src/routes/categories

I could imagine what happens is that SvelteKit removes the trailing slash while Netlify wants to add a trailing slash, ending up in an endless redirect.

**Comment by benmccann** [comment] 2021-05-06 14:39
Ah, yeah, it looks like Netlify adds a trailing slash: https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash. You might try turning off their Pretty URLs feature to see if it fixes it for you

I'll close as a duplicate of https://github.com/sveltejs/kit/issues/733

**Closed by benmccann** 2021-05-06 14:39 UTC
Labels: router
