### ISSUE TITLE
[vite-plugin-svelte-kit] Cannot read properties of undefined (reading 'paths') error during build

### ISSUE THREAD

**Issue by justingolden21** [sveltejs/kit#5487] opened 2022-07-13 02:43 UTC
### Describe the bug

When running `npm run build` this appears:

`[vite-plugin-svelte-kit] Cannot read properties of undefined (reading 'paths')
error during build`

The cause is having a file with the same name and `.js` and .`ts` extensions in the same directory.

This took me **three hours** of my time to figure out, and I could not find a single answer anywhere online. I had to switch branches, stash, manually cut and paste hundreds of files, all because this error message was shown.

If we could instead show something along the lines of `"Cannot have duplicate file names: {path/to/files}{filename} "`

### Reproduction

The cause is having a file with the same name and `.js` and .`ts` extensions in the same directory.

### System Info

```shell
Windows 10
```

### Severity

annoyance

**Comment by justingolden21** [comment] 2022-07-13 02:47
Worth noting that when loading a page, it loads forever, and shows no error in console or terminal.

How I got this: I created a `.js` utility in an old branch, then created a similar utility as a `.ts` file in another branch and merged the `ts` branch intot the older `js` branch without realizing the duplicate file names. I tried killing the server, clearing cookies, local storage and cache, incognito, clearing svelte kit and other build directories, changing branches and checking diffs, and removing individual files. I tried building and found a very very long error complaining about the netlify router (which took me down a very long half hour rabbit hole).

A simple error message for this edge case would have saved three frustrating hours of my life. I hope nobody else has to go through this, which is why I create this issue. Thank you in advance.

**Comment by justingolden21** [comment] 2022-07-13 02:54
So I removed the duplicate name file and it built perfectly, I added it back and it broke. I removed it and it was fixed, added it and it broke again. Then I added a single line to another file and it broke, and undoing the change it still broke. I still cannot figure out how to fix it. Here is the full error:

```
✓ 81 modules transformed.

> Using @sveltejs/adapter-netlify
[vite-plugin-svelte-kit] Cannot read properties of undefined (reading 'paths')
error during build:
TypeError: Cannot read properties of undefined (reading 'paths')
    at create_builder (file:///C:/Users/justi/Documents/GitHub/rgbstudios.github.io/node_modules/@sveltejs/kit/dist/chunks/index2.js:52:48)
    at adapt (file:///C:/Users/justi/Documents/GitHub/rgbstudios.github.io/node_modules/@sveltejs/kit/dist/chunks/index2.js:204:18)
    at Object.closeBundle (file:///C:/Users/justi/Documents/GitHub/rgbstudios.github.io/node_modules/@sveltejs/kit/dist/vite.js:3104:11)
    at async Promise.all (index 0)
    at async C:\Users\justi\Documents\GitHub\rgbstudios.github.io\node_modules\rollup\dist\shared\rollup.js:23693:13
    at async catchUnfinishedHookActions (C:\Users\justi\Documents\GitHub\rgbstudios.github.io\node_modules\rollup\dist\shared\rollup.js:23174:20)
    at async rollupInternal (C:\Users\justi\Documents\GitHub\rgbstudios.github.io\node_modules\rollup\dist\shared\rollup.js:23682:5)
    at async doBuild (C:\Users\justi\Documents\GitHub\rgbstudios.github.io\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41710:24)
    at async build (C:\Users\justi\Documents\GitHub\rgbstudios.github.io\node_modules\vite\dist\node\chunks\dep-c9998dc6.js:41552:16)
    at async CAC.<anonymous> (C:\Users\justi\Documents\GitHub\rgbstudios.github.io\node_modules\vite\dist\node\cli.js:738:9)
```

**Comment by justingolden21** [comment] 2022-07-13 02:55
It seems like there's one result on google, and it's that imported style sheets are the issue?

https://github.com/sveltejs/kit/issues/5472

If mine is duplicate, feel free to close.

**Comment by legowhales** [comment] 2022-07-13 09:13
I am having the same problem, but the problem was a wrong import in a page that the builder was trying to prerender. I think the problem is coming from the builder itself. If there is an error somewhere during prerender, this error is thrown instead (because prerender is undefined in the create_builder function).

Maybe it has to do with this fix #5439 ?

**Comment by mvanhalen** [comment] 2022-07-13 12:25
Have the same issue, but only when building to/for vercel.

**Comment by stolinski** [comment] 2022-07-13 14:44
> I am using adapter-node. For me the issue started after I changed name of a folder. Just to make sure, I installed everything, the problem persists, npm run dev works just fine. But npm run build does not output and crashes with
> 
> vite-plugin-svelte-kit] Cannot read properties of undefined (reading 'paths') error during build:

This is what we are experiencing as well. Only shows up on build, using adapter-node. reading ('paths')

**Comment by Webdut** [comment] 2022-07-13 15:59
The problem resolved. The issue was caused by a wrong redirect making some pages inaccessible. Perhaps this made prerenderer undefined. I would suggest those facing similar problems to ensure that **all** pages are accessible in dev.

**Comment by Fractal-Tess** [comment] 2022-07-13 16:13
Well while digging in the package's code, I found out that like before, I'm able to build perfectly fine if I leave the `vite.config.js` file as standard, but the moment I touch the `outDir` option the `writeBundle` function in kit>dist>vite never gets called.

**Comment by AlexRMU** [comment] 2022-07-13 16:42
In my case, there was a non-closed comment in one file

Possibly related to #5413

**Comment by Suyashtnt** [comment] 2022-07-13 16:44
> In my case, there was a non-closed comment in one file
> 
> Possibly related to #5413

most likely related to, I realized my fix was that I forgot to add a css file

**Comment by justingolden21** [comment] 2022-07-13 18:05
Seems like a myriad of different problems. I still haven't figured out the cause on my end. Someone else mentioned a module not installed and another one mentioned an import.

**Comment by jonellwood** [comment] 2022-07-13 19:00
Everything was fine in dev env for me. Build command locally worked fine as well. Build on Netlify failed. Finally found an import statement starting with a capital letter but the actual file didn't start with with a capital letter. Mac file system isn't case sensitive which is why I suspect it worked fine locally. Thats my guess anyway. Fixed import and build is good to go.

**Comment by justingolden21** [comment] 2022-07-13 22:20
To add to this, I changed an import that had the wrong file extension and it works for me now, although my friend still has this same error and we can't figure out why.

**Comment by justingolden21** [comment] 2022-07-14 16:08
I believe I had a bad import path somewhere else that fixed it as well.

**Comment by Mopholo** [comment] 2022-07-14 18:19
It seems like there a number of causes for this message, but basically it's just hiding the details that were displayed properly extra-vite integration 

As far as imports 

`import {someFunction} from 'someFile' ` 

It gets that message if import `someFunction` is not exported in `someFile`
It gets that message if `someFile` ( or the path ) is not correct or missing 

Oddly it won't throw an error on build when `someFunction`  is not in `someFile`

There are other odd ones this error catches I have not been able to explain.

**Comment by gtm-nayan** [comment] 2022-07-14 23:54
Closing because of #5536, the actual error should show up if you use the upcoming release. Open a new issue with a proper repro if the error has something to do with SvelteKit.

**Closed by gtm-nayan** 2022-07-14 23:54 UTC
Labels: bug

**Comment by justingolden21** [comment] 2022-07-16 05:37
So will be PR resolve this issue? Awesome profile pic by the way gtm-nayan

**Comment by gtm-nayan** [comment] 2022-07-16 06:49
No, it'll just show you the actual error that's causing the build to fail instead of the error *caused by the failed build*, it's been released.

**Comment by piotrpdev** [comment] 2022-08-11 01:28
Just spent 40 mins diagnosing this, turns out I didn't get the casing right when importing an SVG. Error only happened when trying to deploy to Netlify, worked fine when building locally. **Make sure to triple check every path and maybe even try rewriting them.**

~~_Sorry for the ping, just hoping to save someone time._~~

https://github.com/piotrpdev/website/commit/897858a7944ace6831991b5acf0052eb2ef48cc0
