### ISSUE TITLE
svelte adapter build as module

### ISSUE THREAD

**Issue by andykais** [sveltejs/kit#3226] opened 2022-01-07 01:34 UTC
### Describe the problem

I have several resources I want to initialize before opening the svelte web app. Things like reading config, connecting to a database, downloading remote assets. Currently these things need to be done in the `src/hook.ts` file. The logic has to look something like this:
```
let config = new Config('config.yml')
let database
let initialized = false
export async function handler(request, resolve) {
  if (!initialized) {
    await config.load()
    database = new Database(config.database_path)
    initialized = true
  }
  request.locals.db = database
  request.locals.config = config
  await resolve(request)
}
```
this is less than ideal because:
1. fatal errors (e.g. database is invalid) will not stop the app from running
2. fatal errors are not caught right away
3. the first page load will be very slow

I am building a local web app, so there are other issues which are possibly specific to that. For instance, there not a good mechanism for parsing command line arguments for a cli sveltekit app. The best we have right now is environment variables, but those are less than ideal because they arent self discoverable with something like `--help`. Again, you cant get immediate feedback on invalid args either, theres no way to exit the app until at least a request has been made, and even then only using `process.exit(1)`.

### Describe the proposed solution

I would like to see an adapter, or ideally a parameter for all adapters to export a module with lifecycle events rather than a process that starts right away. The config might look something like:
```js
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: [preprocess({})],

  kit: {
    adapter: adapter({ module: true }),

    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
  },
}

export default config
```

this would build the app with the following available:
```ts
class SvelteApp {
  // context could map directly to request.locals or to request.locals.context
  async start(context?: any) {}
  async stop() {}
}
```

### Alternatives considered

the alternative is to continue using `src/hooks.ts`, and relying on process.exit(1) calls to exit on fatal startup errors. This is still not ideal though, since it requires the client hitting an endpoint before the app will exit.

### Importance

would make my life easier

### Additional Information

I am building a local web app, ideally published to npm, and ran on the command line. I want to be able to give users an interface like:
```bash
forager --config <config_file>
```

**Comment by Conduitry** [comment] 2022-01-07 01:58
For the Node adapter, duplicate of #927.

For other adapters, I don't think stuff you need to start when the process starts is going to be particularly applicable, because you're going to be running on a lambda or something similar.

**Comment by benmccann** [comment] 2022-01-10 13:50
Closing as a duplicate of the #927

**Closed by benmccann** 2022-01-10 13:50 UTC
