### ISSUE TITLE
bug: sveltekit handleFetch server hook does not work on cloudflare workers

### ISSUE THREAD

**Issue by f5io** [sveltejs/kit#7447] opened 2022-10-31 10:44 UTC
### Describe the bug

Unfortunately, I'm not sure who to raise this issue with. Cloudflare's `Request` object does not implement the `mode` specification which is being leveraged by the fetch implementation that is passed to the `handleFetch` hook.

```
Error: Failed to get the 'mode' property on 'Request': the property is not implemented.
```

This obviously makes this hook completely unusable on cloudflare workers, and therefore, i'm assuming the same is the case on vercel edge functions.

### Reproduction

Implement the `handleFetch` server hook.

### System Info

```Shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 29.72 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 103.0.2
    Safari: 15.4
```

### Severity

serious, but I can work around it

### Additional Information

The `mode` property is checked in the following places...

https://github.com/sveltejs/kit/blob/87b3037bb6fcf574d5d50c91f42cc91d3b97286c/packages/kit/src/runtime/server/fetch.js#L34

https://github.com/sveltejs/kit/blob/87b3037bb6fcf574d5d50c91f42cc91d3b97286c/packages/kit/src/runtime/server/fetch.js#L59`

**Comment by dummdidumm** [comment] 2022-10-31 10:53
Duplicate of #6739

**Closed by dummdidumm** 2022-10-31 10:53 UTC
