### ISSUE TITLE
(Svelte 5) `$effect` depending on `$page` runs twice

### ISSUE THREAD

**Issue by Fruup** [sveltejs/kit#11460] opened 2023-12-24 13:31 UTC
### Describe the bug

This concerns the early access version of Svelte 5.

I have a page with a dynamic route parameter (`/docs/[...path]/+page.svelte`) that listens for the parameter (in `$page.params.path`) to change with an `$effect`. When initially loading the page, the effect is run twice instead of once.

This issue is not limited to dynamic route parameters.

### Reproduction

Put this in a `+page.svelte` file somewhere:

```svelte
<script lang="ts">
  import { page } from '$app/stores'

  // This is for some reason needed to prevent the effect below from running twice.
  // $effect(() => {
  //   $page
  // })

  $effect(() => {
    console.log('This should run once, but runs twice.', new Date().valueOf())

    // Do something with `$page`...
    $page
  })
</script>
```

### Logs

```Shell
This should run once, but runs twice. 1703424477666
This should run once, but runs twice. 1703424477667
```

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 13.42 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.9.0 - ~/Library/pnpm/pnpm
    bun: 1.0.19 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.129
    Edge: 115.0.1901.188
    Safari: 17.2.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.1 
    @sveltejs/kit: ^2.0.0 => 2.0.6 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^5.0.0-next.1 => 5.0.0-next.26 
    vite: ^5.0.3 => 5.0.10
```

### Severity

annoyance

### Additional Information

Weirdly, inserting another `$effect` depending on `$page` solves this issue:

```svelte
$effect(() => {
  $page
})
```

Now the effect only runs once.

**Comment by jhs512** [comment] 2024-01-04 06:41
me too.

**Comment by deeerwin** [comment] 2024-07-10 05:15
Does anyone know why this happens? My $effect runs twice also when console.log() an update on my state.

**Comment by ndom91** [comment] 2024-07-11 11:49
I'm running into this as well. I want to register a page view with  my analytics library, so I have somethign like this:

```svelte
onMount(() => {
  if (!dev) {
    analytics.init(env.PUBLIC_PROJECT_ID, { apiURL: env.PUBLIC_API_HOST })
  }
})

$effect(() => {
  const url = $page.url.pathname
  if ($page.url.searchParams.toString() !== "") {
    url += `?${$page.url.searchParams.toString()}`
  }
  
  if (!dev) {
    analytics.trackPageview(url)
  }
})
```

However, I end up getting 2x page views for each navigation, i.e. that `trackpageView` in nthe effect (which depends on `$page.url.pathname`) seems to be called twice :thinking: 

Using the following versions:

```
"@sveltejs/kit": "2.5.18",
"svelte": "5.0.0-next.175",
```

**Comment by dummdidumm** [comment] 2024-08-26 20:52
I'm not able to reproduce this. Does this still occur in the latest version? If so, please provide a reproduction link (Stackblitz or github repo)

**Comment by Fruup** [comment] 2024-08-27 15:55
@dummdidumm Seems to be fixed. Can't reproduce either (https://stackblitz.com/edit/sveltejs-kit-template-default-yd5fgs?file=src%2Froutes%2F%2Blayout.svelte).

**Comment by dummdidumm** [comment] 2024-08-27 15:56
Closing as fixed then 👍

**Closed by dummdidumm** 2024-08-27 15:56 UTC
Labels: awaiting submitter, svelte 5

**Comment by yellowby** [comment] 2024-11-15 20:52
It looks like the issue remains with shallow routing. Calling `pushState` is fine, but navigating with back/forward buttons will trigger the effect twice. 
Demo: https://stackblitz.com/~/github.com/yellowby/sveltekit-shallow-routing-effect

**Comment by orangecoloured** [comment] 2025-06-18 13:37
I started to face this issue. I'm also using `$effect` in my main layout accessing `page.url.pathname`. And recently it started to fire twice.

```
"svelte": "^5.34.3",
"@sveltejs/kit": "^2.21.5",
```

For now I managed to fix it like this:
```typescript
let previousRoute: string | null = null;

$effect(() => {
  if (page.url.pathname !== previousRoute) {
    previousRoute = page.url.pathname;

    onRouteChange(page.url.pathname);
  }
});
```
