### ISSUE TITLE
Base path doesn't work with Cloudflare Pages

### ISSUE THREAD

**Issue by chientrm** [sveltejs/kit#10296] opened 2023-07-01 02:36 UTC
### Describe the bug

When setting `kit.paths.base` to `/subfolder`, the app run correctly at local but when deploy to Cloudflare Pages, the built `css` and `js` cannot be load. Thus, no style or hydration is available.

### Reproduction

1. Create project

```sh
npm create svelte@latest
```

2. Add style `src/lib/app.css`:

```css
h1 {
  color: green;
}

```

3. Add `src/routes/foo/+page.svelte` route:

```svelte
<script>
  import { base } from "$app/paths";
</script>

<h1>Foo</h1>
<a href={`${base}/`}>Back</a>
```

4. Add `src/routes/+page.svelte` route:

```svelte
<script>
  import { base } from "$app/paths";
</script>

<h1>Home</h1>
<a href={`${base}/foo`}>Foo</a>
```

5. Add style to `src/routes/+layout.svelte`:
```svelte
<script>
  import "$lib/app.css";
</script>

<slot />
```

6. Set base path in `svelte.config.js`:

```ts
import adapter from "@sveltejs/adapter-auto";

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter(),
		paths: { base: "/subfolder" },
	},
};

export default config;
```

The reproduction repo: [chientrm/sk-cf-bug](https://github.com/chientrm/sk-cf-bug)

## Expectation

Both `<h1`> tag are green and `js` preloading when clicking on `<a>` tags.

## Actual

The color is default and `<a>` tags is not hydrated.

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (4) x64 Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
    Memory: 1.99 GB / 3.51 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.4.0 - ~/.nvm/versions/node/v18.15.0/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.21.0 
    svelte: ^4.0.0 => 4.0.1 
    vite: ^4.3.6 => 4.3.9
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I deployed to Cloudflare Pages with `SvelteKit` preset and `NODE_VERSION` set to `16`: https://sk-cf-bug.pages.dev/subfolder/

**Comment by ghostdevv** [comment] 2023-07-03 12:17
Closing as duplicate of #10290

**Closed by ghostdevv** 2023-07-03 12:17 UTC
