### ISSUE TITLE
__layout.reset.svelte for __error.svelte

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#3949] opened 2022-02-16 09:08 UTC
### Describe the problem

I don't want to display the layout when I display the error page.

### Describe the proposed solution

A `__error` directory that can have its own `__layout.reset.svelte`.
This can be multi-level.
For the first level:
`routes/__error/index.svelte` - error page
`routes/__error/__layout.reset.svelte` - layout reset page

The file `/routes/__error/index.svelte`, is equivalent to `/routes/__error.svelte` - so it works on all subpages e.g. on `routes/about` also this error works.

Of course this should also work:
`routes/todos/__error/index.svelte` - error page
`routes/todos/__error/__layout.reset.svelte` - layout reset page

Then the `/routes/todos/__error/index.svelte` file is equivalent to `/routes/todos/__error.svelte`.

### Alternatives considered

Redirect to a separate subpage that is supposed to pretend to be the error page and has `__layout.reset.svelte`.

### Importance

nice to have

**Comment by bluwy** [comment] 2022-02-17 06:03
Duplicate of #2694

**Closed by bluwy** 2022-02-17 06:03 UTC
