### ISSUE TITLE
[Issue] Cannot redefine property: crypto

### ISSUE THREAD

**Issue by N-NeelPatel** [sveltejs/kit#10252] opened 2023-06-26 09:16 UTC
### possible solution

https://github.com/sveltejs/kit/issues/10252#issuecomment-1611483919

### Describe the bug

When I create a new project in svelte using these commands:
```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```
I get this issue
|
![image](https://github.com/sveltejs/kit/assets/29038590/e2bf17fa-ba8c-441d-aac1-ad5267d3ff8e)

### Reproduction

When I create a new project in svelte using these commands:
```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 829.25 MB / 7.36 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.20.5
    svelte: ^4.0.0 => 4.0.0
    vite: ^4.3.6 => 4.3.9
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment] 2023-06-26 10:02
I cannot reproduce it with the default template with Node 16.15.0. We'll need a complete reproduction if you've made any modifications to the template.

**Comment by N-NeelPatel** [comment] 2023-06-26 10:19
No, I didn't make any modification to the template

**Comment by N-NeelPatel** [comment] 2023-06-26 10:23
@gtm-nayan - these options I selected
![image](https://github.com/sveltejs/kit/assets/29038590/ca6f869b-a730-4d60-a663-20a6d284541b)

**Comment by chrisflatley** [comment] 2023-06-26 10:29
I also have this same error, but only after adding few dependencies to the template and on existing projects with templates. 

When I remove the dependencies I've added, the error stays (even after delete package locks, node_modules and .sveltekit dir). Which makes no sense to me.

My stack is different pnpm (or npm), Node 18, MacOS, with Typescript.

I'm trying to figure  which dependencies it is - perhaps multiple version sof sveltekit being pulled in.

**Comment by dagthomas** [comment] 2023-06-26 10:58
I suddenly got this error too - was working on friday, not working today. Also persists through deletion of package-lock and node_moduls

**Comment by AntonPavlenkov** [comment] 2023-06-26 11:03
have same issue with node 16 but Fixed this by updating to lates node v20.3.1.

**Comment by N-NeelPatel** [comment] 2023-06-26 11:14
@AntonPavlenkov - Thank you very much. The latest node v20.3.1 resolved the issue for me.

**Comment by dikshantrajput** [comment] 2023-06-26 16:43
@gtm-nayan Is there any update on this one? I can not rely on updating version to 20.3.1 Other things might break.

**Comment by AntonPavlenkov** [comment] 2023-06-26 16:48
You update only your local machine for development with node 20. Build with version 16 is fine and deploying to docker with node 16 is also working fine. 

Although you are correct that it needs to be resolved properly.

**Comment by drewbitt** [comment] 2023-06-26 19:36
Also broken on node 18.15

**Comment by gtm-nayan** [comment] 2023-06-26 22:55
Unfortunately I cannot reproduce the problem myself and I can't really investigate the problem with being able to recreate it. If you can't change the major version see if an upgrade or downgrade within the same major helps.

**Comment by Conduitry** [comment] 2023-06-26 23:09
I can't reproduce this either. I've installed Node 16.15.0 on a fresh Windows 11 sandbox, and I'm not getting this error with the default template.

**Comment by DoisKoh** [comment] 2023-06-27 01:22
Broken on node v18.14.0 for me.

**Comment by Conduitry** [comment] 2023-06-27 04:51
I'm unable to reproduce this on Node 18.14.0 on Windows 11 either.

**Comment by dikshantrajput** [comment] 2023-06-27 05:11
@DoisKoh @dagthomas @AntonPavlenkov Have you freshly installed the node on your system or it was previously installed?

**Comment by dagthomas** [comment] 2023-06-27 05:20
> @DoisKoh @dagthomas @AntonPavlenkov Have you freshly installed the node on your system or it was previously installed?

I had an ongoing project, everything was previously installed. Happened from Friday to Monday where it didn't work anymore, unless I installed node 20

**Comment by AntonPavlenkov** [comment] 2023-06-27 05:24
> @DoisKoh @dagthomas @AntonPavlenkov Have you freshly installed the node on your system or it was previously installed?

It was installed before and was working fine until Monday. Although I use nvm on Mac m1 for that matter.

**Comment by vnphanquang** [comment] 2023-06-27 07:53
This happened to me today as well. Deleting `node_modules` and reinstalling resolved the error.

This is on Mac 13.0.1 (22A400). The steps taken were hard track. I can provide the `package.json` and more env details if someone needs that.

**Comment by chrisflatley** [comment] 2023-06-27 07:56
This is hard to reproduce I’ve failed even though I’ve hit it on several projects (starting from clean and from existing). 

Whilst it’s not addressing the issue should the install polyfill check if crypto etc is already defined?

It currently just overwrites everything on globalThis as far as I can see.

**Comment by Holf** [comment] 2023-06-27 08:28
Have had exactly the same experience on Windows 11, WSL2 (`Ubuntu 20.04.6`).

* Node `v18.14.2`
* SvelteKit `1.20.4`

Working fine last night (approx 21:00 BST).
Fails this morning (09:00 BST).

Vaguely relevant further info:
* A major Windows 11 update was attempted last night, but _failed_.
* There was an anti-virus definitions update.

**Comment by nostrorom** [comment] 2023-06-27 09:03
I and other collaborators are having the same issue 

```
  "turbo": " "1.10.6",
  "@sveltejs/kit": "^1.15.8",
   "vite": "^4.2.1",
   
   node 16.18.1
   Ubuntu 22.04.2 LTS
```

Some on the same OS/stack are not having it so it's a weird case to reproduce or not.

Switching to node `20.3.1` solved the issue - though I can't go in production with it, we're still on 18.x

**Comment by jnath** [comment] 2023-06-27 09:10
this post related the same issue 

https://stackoverflow.com/questions/76557205/why-wont-vite-server-start

**Comment by SaidBahaDev** [comment] 2023-06-28 02:27
same error on node v18.16.1

**Comment by dummdidumm** [comment] 2023-06-28 14:08
To everyone affected by this: Do you have the "Console Ninja" extension installed by any chance? If so, this might be the culprit, [as hinted by this related issue](https://github.com/wallabyjs/console-ninja/issues/160). If so, try updating the extension to the latest version which hopefully fixes this.

**Comment by AntonPavlenkov** [comment] 2023-06-28 14:47
> 
Actually I do have it "Console Ninja" installed. So after uninstalling it and trying again it did not work. Also from trying to start it from pure terminal without IDE it also does not work.

**Comment by gtm-nayan** [comment] 2023-06-28 15:22
@AntonPavlenkov can you try it after removing the node_modules and doing a force install?

**Comment by AntonPavlenkov** [comment] 2023-06-28 15:33
@gtm-nayan yes! So after uninstalling Console Ninja and removing node_module and package.lock and .svelte-kit and running fresh install. The error goes away. But it is enough to just install Console Ninja again and error comes back!

**Comment by Holf** [comment] 2023-06-28 19:14
I am using Console Ninja, yes.

I have upgraded it to `v0.0.167`, released today.

I am now able to start Vite Server just fine on Node `v18.14.2` again.

Thank you for identifying this resolution so quickly.

**Comment by nostrorom** [comment] 2023-06-29 08:00
Same here, upgrading to the latest Console Ninja `v0.0.169` has solved my issue (without having to remove `node_modules`, `package-lock` etc.) :+1:

**Comment by chanmathew** [comment] 2023-06-29 15:28
> To everyone affected by this: Do you have the "Console Ninja" extension installed by any chance? If so, this might be the culprit, [as hinted by this related issue](https://github.com/wallabyjs/console-ninja/issues/160). If so, try updating the extension to the latest version, then delete your node modules folder in the offending project and reinstall the packages, which hopefully fixes this.

Wow great find! Just updated Console Ninja to v0.0.170 and removed my node_modules and did a fresh install. Seems to be resolved now, thank you!

**Comment by tcc-sejohnson** [comment] 2023-07-01 20:33
Closing this since the issue was external and is now fixed. For future googlers -- upgrade Console Ninja, remove `node_modules`, and reinstall.

**Closed** 2023-07-01 20:33 UTC
