### ISSUE TITLE
svelte-kit package is not replacing all instances of $lib with the relative path

### ISSUE THREAD

**Issue by chanced** [sveltejs/kit#2034] opened 2021-07-29 15:58 UTC
### Describe the bug

Running `svelte-kit package` does not replace all instances of `$lib` with the appropriate relative path.

### Reproduction

```bash
git clone git@github.com:chanced/filedrop-svelte.git
cd filedrop-svelte
npm install
npm run package
grep -r "\$lib" ./package
```
Altenative:
visit this REPL https://svelte.dev/repl/caa3a71563d5480dbd9f55dcf8466073?version=3

> Invalid package name "$lib" (name can only contain URL-friendly characters)

### Logs

```shell
~/Projects/filedrop  main ✔                                                                                                                                                        0m  
▶ npm run package                                     

> filedrop-svelte@0.0.2 package
> svelte-kit package


~/Projects/filedrop  main ✔                                                                                                                                                        0m  
▶ grep -r "\$lib" ./package                           
./package/components/FileDrop/FileDrop.svelte:<script lang="ts">import filedrop from "$lib/actions/filedrop";
./package/components/FileDrop/FileDrop.svelte:import { isString, isArrayOfStrings } from "$lib/util";
./package/actions/filedrop.js:import { getFilesFromEvent, extractFilesFromEvent, isEventWithFiles, isNode } from "$lib/event";
./package/actions/filedrop.js:import useragent from "$lib/useragent";
./package/actions/filedrop.d.ts:import type { FileDropOptions } from "$lib/options";
```

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 2.77 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.1/bin/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v14.17.1/bin/npm
  Browsers:
    Brave Browser: 79.1.1.23
    Chrome: 92.0.4515.107
    Firefox: 89.0
    Safari: 14.1.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.138
    svelte: 3.40.1 => 3.40.1
```

### Severity

blocking all usage of SvelteKit

**Comment by ignatiusmb** [comment] 2021-07-29 16:12
Duplicate of #1950

**Comment by chanced** [comment] 2021-07-29 16:13
Ugh, I'm horrible at this. I searched through the issues and didn't see that one.

I'm sorry. Thank you.

**Closed** 2021-07-29 16:13 UTC
