### ISSUE TITLE
data returned from +layout.server.ts is null or undefined after first render.

### ISSUE THREAD

**Issue by ofeenee** [sveltejs/kit#5954] opened 2022-08-16 22:02 UTC
### Describe the bug

1. `+layout.server.ts` returns `data` that's necessary for the pages using that particular layout.
2. `data` is linked to layout, each layout (only using one at the moment) returns a unique `data`.
3. `data` returned on the first render works as expected.
4. `data` returned after navigating pages using the layout is `null` or `undefined`.

`//layout.server.ts`
`export async function load() {
	return { app: 'MAIN TITLE' };
}
`

### Reproduction

Reproduction here: [github repo](https://github.com/ofeenee/sveltekit-layout-data-undefined) (npm run dev and check console/browser)

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 48.79 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.16.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Edge: 103.0.1264.77
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.413 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

annoyance

### Additional Information

to make the bug even clearer, I've added `+page.server.ts` that also returns `data`, which shows that it works as expected, but not with `+layout.server.ts` (`parent`).

**Comment by Conduitry** [comment] 2022-08-16 22:06
Duplicate of #5904 / #5921.

**Closed by Conduitry** 2022-08-16 22:06 UTC

**Comment by ofeenee** [comment] 2022-08-16 22:12
Thank you.
