### ISSUE TITLE
executing `npm init svelte@next` command result in error

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#3447] opened 2022-01-20 15:14 UTC
### Describe the bug

executing `npm init svelte@next` command result in error

### Reproduction

It seems to be problem of latest version of svelte-create

### Logs

```shell
npm init svelte@next
Need to install the following packages:
  create-svelte@next
Ok to proceed? (y) y
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/mlocik97/.npm/_npx/bbf9a9d70dc325b0/node_modules/create-svelte/index.js' imported from /home/mlocik97/.npm/_npx/bbf9a9d70dc325b0/node_modules/create-svelte/bin.js
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:308:11)
    at moduleResolve (internal/modules/esm/resolve.js:731:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm notice 
npm notice New patch version of npm available! 8.3.0 -> 8.3.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.1
npm notice Run npm install -g npm@8.3.1 to update!
npm notice 
npm ERR! code 1
npm ERR! path /mnt/sda1/Programovanie/HTTP/test2
npm ERR! command failed
npm ERR! command sh -c create-svelte

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mlocik97/.npm/_logs/2022-01-20T15_11_12_631Z-debug-0.log
```

### System Info

```shell
Need to install the following packages:
  envinfo
Ok to proceed? (y) 

  System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 1.37 GB / 15.45 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment] 2022-01-20 15:16
Duplicate of #3443.

**Closed by Conduitry** 2022-01-20 15:16 UTC
