### ISSUE TITLE
Load 'load' function only once

### ISSUE THREAD

**Issue by jdgamble555** [sveltejs/kit#7822] opened 2022-11-27 02:22 UTC
### Describe the problem

Let's say I have this:

```
post
  [slug]
    +page.server.ts
    +page.svelte
```
Every time I click a route change, the load function (+page.server.ts) gets reloaded.  While this can be desired in most use cases, it is not desirous in all use cases.

This is great in order for the first page load to get the data from the server, and keep good SEO.  However, after that, I am running a pure client application.  It may be easier to refresh my page from the client (if I use Firebase or Supabase I don't need the server), i.e. by calling an api endpoint from the client.

I realize this is what caching is also for, but I should have more control over that.

____

Let's say I have a `posts-lists` component. If I click the `post-detail` component from the list, I could simply pass the post information to the post-detail component instead of refetching the data.  However, if I am loading the data for the first time from a URL, I won't have that information, and I will need to run the load component.

Here is the original conversation:

https://github.com/sveltejs/kit/discussions/7816#discussioncomment-4244717

### Describe the proposed solution

In the `+layout.(server).ts` and `+page.(server).ts` files, have the ability to export a variable like:

```js
export const load_once = true;
```
Which will only load the `load` functions of that particular route one time.  Any route changes will not load the load function again.

### Alternatives considered

You could create a `cookie` to track this or some kind of `variable`, but you still need to export something in your load function.

It should be noted, that in Angular, for example, the `resolvers` are only ran one time, and then not again. While this is problematic as well, it does not force you to have to use the load function. Yes, I still use Angular Universal for some things :) --- moving over to SvelteKit now.

### Importance

would make my life easier

### Additional Information

I also like the idea of running the load function when I want to, kind of the the [next 13 fetching](https://nextjs.org/blog/next-13#data-fetching). I just need more control over when I am using the load function. Sometimes I will need to rerun it, sometimes I will already have the data from somewhere else.

J

**Comment by tcc-sejohnson** [comment] 2022-11-27 03:25
I think in this case your solution is just to use a `load.ts` instead of a `load.server.ts`. If the data you need is fetchable from the client already (i.e. there aren't secrets involved), the `load` will run on the server for full reloads or direct navigations to the link, but it will run on the client for client navigations (eg. clicking an anchor tag).

**Comment by jdgamble555** [comment] 2022-11-27 03:30
I don't think you can have a `load.ts` or a `load.server.ts` file in the latest SvelteKit.  I'm not sure what you mean, as this does not fit the [specs](https://kit.svelte.dev/docs/routing).

Also, if I use redis, for example, this does not solve the problem.

If I've already fetched the relevant information, I don't want to reload the `load` function as in my use case above.  

J

**Comment by s3812497** [comment] 2022-11-27 07:31
> I don't think you can have a `load.ts` or a `load.server.ts` file in the latest SvelteKit.  I'm not sure what you mean, as this does not fit the [specs](https://kit.svelte.dev/docs/routing).

I think what he meant is to use a shared load function (+page.ts) rather than a server-only load function.

Also, I'm in support of the idea where we would have more fine-grained control of when a load function runs. I'm not sure if this already exists (does setting cache control prevent a load function from re-running?). 

In my experience, it can be difficult to understand at times when a load function automatically re-runs, although the rules have been specified in the documentation.

**Comment by jdgamble555** [comment] 2022-11-28 04:01
@s3812497 - I need to load my data from the server, but even if I didn't, it would still load the server function EVERY time there is a route change. The `params` variable ensures that.

There needs to be a way to load data ONLY ONCE when the app loads, but before a component is rendered (server or browser).

J

**Comment by Rich-Harris** [comment] 2022-11-29 13:16
`load` functions only re-run when they are invalidated: https://kit.svelte.dev/docs/load#invalidation. Can you describe your case in more detail? It sounds like the system is working as intended.

**Comment by jdgamble555** [comment] 2022-11-29 15:15
Thanks Rich. I know you appreciate repos, but I feel this is more of a conceptual issue, so I will try to be as clear as possible.

# Situation 1:

I have a blog with posts on different slugs:
```
post
  [slug]
    +page.ts
    +page.svelte
home
   +page.ts
```

On my home page, I load a list of posts.  Each list of posts contain ALL the post information.  If I click on a specific post, It will display the post detail information (perhaps the contents is shown instead of summary, but all the post information is already in memory).

However, when I click on the specific page `post/[slug]`, the post information would be re-downloaded and over fetched, even though I already have the information in memory. This can be costly if I am using a database like Firebase that charges per read.  I want to read on the server, not the client, to support SSR, so I do need the load function.  Because the load function in `post/[slug]` is based on the `slug`, it would need to be reloaded the way that it currently works.

I only need to load the load function if my FIRST load is at `post/[slug]`, not on route changes. It would be more efficient to just reload that specific post information, which is already in memory, than to refetch the content in the load function.

This is even more evident if I am using `+page.server.ts`.

# Situation 2

I load a GraphQL endpoint (say from Hasura) within the `+page.ts` file, or `+page.server.ts` file, again, for SSR purposes.  Again, perhaps I load the data into a client GraphQL cache, and I don't need to refresh the load function.  The same example above applies, but with GraphQL you can get even more control of unique queries. Perhaps the author of a post is already in the cache, and I visit the author page. There is no need to refetch the author information. Anything that has already been cached can fall into this category, but with more nuances when using GraphQL.

# Situation 3

I want to show a different page or content for a logged in user.  While there are workarounds, and this is the weakest example, I may not want to load the same information in the load function for a logged in user or regular user who has already entered the site.  The sessions can get complicated as there is no way to pass information BACK to the load function.  I believe this is still possible.

# Situation 4

I want to show a loading spinner when while the load function is running. There is no way to prevent the load function from running, and there are no hooks for before and after that I know of.  The only work around I have found is to put this in the `+layout.svelte` at the root level. However, this technically tracks the navigation, not the loading function itself, and it is not customizable.

```ts
beforeNavigate(() => loading.set(true));
afterNavigate(() => loading.set(false));
```

I know there are plenty of examples, but these come to mind. If anything is not clear, please let me know and I will edit this post.

Again, I think the simplest fix would be to add a

 ```js
export const load_once = true;
````
variable.

Thanks,

J

**Comment by dummdidumm** [comment] 2022-11-29 15:23
Situation 1+2 sound like you would want to use `src/routes/+layout.ts` + `await parent()` in `src/routes/[slug]/+page.ts`. There's also an issue about opting out of tracking what makes a load function rerun, which you could use to opt out of everything, making it run only once.

Situation 3 sounds like you want to either use a global variable (that is controlled on the client only, not on the server, because that would have side effects for other calls) or a cookie

Situation 4 isn't possible today with anything that's given by the framework, but here you could again use an outer global variable that is only mutated on the client.

**Comment by jdgamble555** [comment] 2022-11-30 16:01
What is a shared `load.ts` file that you guys keep referring to? I don't see anything in the docs.  Load files are named `+page.(server).ts` or `+layout.(server).ts` unless I am missing something?

The problem is that the server version will always get run, considering the `params` or `routes` or `urls` will be different as in the above examples.  There is no way to check a browser cache to prevent a load function from being run on the server first.  There is no way to prevent the load function from being run at all, from what I have seen, if the route is new.  

Sure, I can create an endpoint using `+server.ts`, but the `fetch` function would get called within the load function, so that doesn't solve the issue.

J

**Comment by jdgamble555** [comment] 2022-11-30 16:03
The `navigating` does help btw, so thanks for that clarity.

J

**Comment by s3812497** [comment] 2022-12-01 00:11
> What is a shared `load.ts` file that you guys keep referring to? I don't see anything in the docs.  Load files are named `+page.(server).ts` or `+layout.(server).ts` unless I am missing something?

You can omit the server keywords from the filename so that the load function runs both server side and client side. e.g. +page.ts

**Comment by jdgamble555** [comment] 2022-12-01 03:28
@s3812497 - I was adding the server keyword to show you could run it either way. 

I think the key to get this to work was adding another endpoint within the load function (so that it can be called both server / browser without revealing db info).

**Comment by jdgamble555** [comment] 2022-12-01 03:31
@s3812497 - I was adding the server keyword to show you could run it either way. 

I think the key to get this to work was adding another endpoint within the load function (so that it can be called both server / browser without revealing db info).

https://stackblitz.com/github/jdgamble555/sveltekit-load

@Rich-Harris @tcc-sejohnson I still don't know what a `load.ts` file is, but I'm assuming both of you guys were referring to a `+page.ts` file.

There could still be some work done to have more control over the load function IMO, but I figured out my needs for now.

Thanks for the help,

J

**Comment by dummdidumm** [comment] 2022-12-12 19:03
Closing because the needs have been adressed, and "load load function only once" is discussed in https://github.com/sveltejs/kit/discussions/6912

**Closed by dummdidumm** 2022-12-12 19:03 UTC
