### ISSUE TITLE
@sveltejs/adapter-vercel not working anymore at vercel.com

### ISSUE THREAD

**Issue by seppegadeyne** [sveltejs/kit#3143] opened 2021-12-30 19:34 UTC
### Describe the bug

I have several SvelteKit websites hosted at vercel.com using @sveltejs/adapter-vercel. Since today (30/12/2021) deploys are not working anymore. If you run "npm run build" locally it works fine. Not on vercel itself. 

![Screenshot from 2021-12-30 20-31-11](https://user-images.githubusercontent.com/18264851/147782648-2a494059-1b52-4372-b1df-86287e6fafa5.png)

### Reproduction

Try to deploy on vercel.

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 42.46 GB / 62.71 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.9
  npmPackages:
    @glidejs/glide: ^3.5.2 => 3.5.2 
    @sveltejs/adapter-vercel: next => 1.0.0-next.32 
    @sveltejs/kit: next => 1.0.0-next.201 
    @tailwindcss/aspect-ratio: ^0.4.0 => 0.4.0 
    @tailwindcss/forms: ^0.4.0 => 0.4.0 
    @types/glidejs__glide: ^3.4.1 => 3.4.1 
    @typescript-eslint/eslint-plugin: ^4.31.1 => 4.33.0 
    @typescript-eslint/parser: ^4.31.1 => 4.33.0 
    autoprefixer: ^10.4.0 => 10.4.0 
    cssnano: ^5.0.6 => 5.0.12 
    eslint: ^7.32.0 => 7.32.0 
    eslint-plugin-svelte3: ^3.2.0 => 3.2.1 
    motion: ^10.4.0 => 10.4.0 
    postcss: ^8.4.5 => 8.4.5 
    postcss-load-config: ^3.1.0 => 3.1.0 
    sanitize-html: ^2.5.3 => 2.6.0 
    storyblok-js-client: ^4.1.5 => 4.1.5 
    svelte: ^3.38.2 => 3.44.2 
    svelte-check: ^2.2.6 => 2.2.10 
    svelte-preprocess: ^4.7.3 => 4.9.8 
    tailwind-scrollbar-hide: ^1.0.3 => 1.1.6 
    tailwindcss: ^3.0.2 => 3.0.2 
    tslib: ^2.3.1 => 2.3.1 
    typescript: ^4.5.2 => 4.5.2
```

### Severity

blocking all usage of SvelteKit

**Comment by seppegadeyne** [comment] 2021-12-30 19:37
please check below....

![Screenshot from 2021-12-30 20-37-19](https://user-images.githubusercontent.com/18264851/147783009-aae47b29-be0f-4a48-ad1e-2b9941b45f53.png)

**Comment by Rich-Harris** [comment] 2021-12-30 19:38
Investigating

**Comment by Rich-Harris** [comment] 2021-12-30 20:40
Can you try with `@sveltejs/adapter-vercel@1.0.0-next.34`?

**Comment by seppegadeyne** [comment] 2021-12-30 20:49
same error message with version 34... 

![Screenshot from 2021-12-30 21-48-37](https://user-images.githubusercontent.com/18264851/147787102-c99e2f34-6511-4f6b-9ffc-e913a6a22359.png)

**Comment by HeritagePalms** [comment] 2021-12-30 20:55
> Can you try with `@sveltejs/adapter-vercel@1.0.0-next.34`?

This got me back in working order.

**Comment by Rich-Harris** [comment] 2021-12-30 20:56
Oh, hang on — you're referencing `$page.path`. That won't work any more: https://github.com/sveltejs/kit/pull/3126

The error that would have told you that is only printed in dev mode. Perhaps we should add it to prod mode too.

**Comment by Rich-Harris** [comment] 2021-12-30 20:57
(Change `$path.path` to `$page.url.pathname` and `$page.query` to `$page.url.searchParams`, and the same for any uses of `page.path` and `page.query` in `load` functions, or `request.path`/`request.query` in endpoints)

**Comment by HeritagePalms** [comment] 2021-12-30 20:58
> (Change `$path.path` to `$page.url.pathname` and `$page.query` to `$page.url.searchParams`, and the same for any uses of `page.path` and `page.query` in `load` functions, or `request.path`/`request.query` in endpoints)

Even though it seems he is using older version?

    @sveltejs/adapter-vercel: next => 1.0.0-next.32 
    @sveltejs/kit: next => 1.0.0-next.201

**Comment by Rich-Harris** [comment] 2021-12-30 21:00
> Even though it seems he is using older version?

In all likelihood a newer version is being installed on Vercel. This would explain why it works locally

**Comment by HeritagePalms** [comment] 2021-12-30 21:02
> > Even though it seems he is using older version?
> 
> In all likelihood a newer version is being installed on Vercel. This would explain why it works locally

There i go thinking and typing at different timings...

**Comment by seppegadeyne** [comment] 2021-12-30 21:36
url and params are not available in $app/stores like described in "...and the page store has been replaced with url and params stores" #3126 

![Screenshot from 2021-12-30 22-32-09](https://user-images.githubusercontent.com/18264851/147789486-17065c65-5384-419a-9c3f-78b0f172eae0.png)

page store doesn't contain url see console.log ...

![Screenshot from 2021-12-30 22-33-11](https://user-images.githubusercontent.com/18264851/147789542-47058bd2-434e-450e-b7bd-3aef391d148c.png)

**Comment by Rich-Harris** [comment] 2021-12-30 21:38
Consult the docs, not the PR (things changed between the initial comment and what ended up getting shipped). You're looking for the `page` store

**Comment by Rich-Harris** [comment] 2021-12-30 21:38
https://kit.svelte.dev/docs#modules-$app-stores

**Comment by seppegadeyne** [comment] 2021-12-30 21:41
Now I can see it in dev mode too when I change "@sveltejs/kit": "next"  to "@sveltejs/kit": "1.0.0-next.209". Bummer....

**Comment by Rich-Harris** [comment] 2021-12-30 21:42
You should be getting an error message that tells you how to fix it?

**Comment by seppegadeyne** [comment] 2021-12-30 21:48
Yes now it does when I put 1.0.0-next.209 version active :-) , with next version it's not. 

![Screenshot from 2021-12-30 22-46-29](https://user-images.githubusercontent.com/18264851/147790145-e17f3107-d269-4ea2-8501-e231a230a911.png)

**Comment by Rich-Harris** [comment] 2021-12-30 21:54
`next.209` _is_ the `next` version (or at least it was, I just released `next.210`), you just weren't up to date locally. You should keep `"next"` in your package.json, otherwise you'll be stuck on 209 forever.

Looks like the issue is resolved — we okay to close this?

**Comment by netaisllc** [comment] 2021-12-30 21:56
BTW, using simply `next` does render the error in the browser as well as the CLI...

```
Error: request.path has been replaced by request.url.pathname
    at Object.get (file:///Users/kevinm/Projects/Strongcloud/app-zero/node_modules/@sveltejs/kit/dist/ssr.js:1750:11)
    at Object.handle (//Users/kevinm/Projects/Strongcloud/app-zero/src/hooks:7:52)
    at respond (file:///Users/kevinm/Projects/Strongcloud/app-zero/node_modules/@sveltejs/kit/dist/ssr.js:1760:30)
    at svelteKitMiddleware (file:///Users/kevinm/Projects/Strongcloud/app-zero/node_modules/@sveltejs/kit/dist/chunks/index.js:4577:28)
```

**Comment by seppegadeyne** [comment] 2021-12-30 22:05
@Rich-Harris yes okay to close. Thanks for the support. Best wishes for the New Year! ;-)

**Closed** 2021-12-30 22:14 UTC
Labels: bug, pkg:adapter-vercel
