### ISSUE TITLE
Typed ParamMatcher (convert params from string to type)

### ISSUE THREAD

**Issue by adiguba** [sveltejs/kit#11654] opened 2024-01-17 06:37 UTC
### Describe the problem

Hello,

The route matching feature is great, but it lacks the ability to convert the param.

For example if we take the code from the docs : https://kit.svelte.dev/docs/advanced-routing#matching
```typescript
import type { ParamMatcher } from '@sveltejs/kit';

export const match: ParamMatcher = (param) => {
	return /^\d+$/.test(param);
};
```

With a route like `src/routes/archive/[page=integer]`, `params.page` will be a `string` and not a `number`.
We need to convert it in order to use it as a number...

It would be great if the ParamMatcher could handle this, as verifying a value is similar to convert it.

### Describe the proposed solution

Define a new type TypedParamMatcher like this :
```typescript
export type ParamResult<T> = { valid: boolean; value?: T };
export type TypedParamMatcher<T> = (param: string) => ParamResult<T>;
```

So we can write a param matcher like this :

```typescript
import type { TypedParamMatcher} from '@sveltejs/kit';

export const match: TypedParamMatcher<number> = (param) => {
        // Convert the value
	const value= Number(param);
        // accept only valid integer
        const valid = !Math.isNan(value) && Math.trunc(value) === value;

	return { valid, value };
};
```

And `params.page` will be correctly typed as a `number`.

### Alternatives considered

Convert the value on each page's load function.

### Importance

nice to have

**Comment by Conduitry** [comment] 2024-01-17 06:49
Duplicate of #10407, although I do like that this API is more explicit. Could you leave this as a comment on that issue?

**Closed by Conduitry** 2024-01-17 06:49 UTC

**Comment by adiguba** [comment] 2024-01-17 08:09
Sorry I didn't found this issue...
