### ISSUE TITLE
server functions

### ISSUE THREAD

**Issue by huseeiin** [sveltejs/kit#12631] opened 2024-08-31 09:34 UTC
### Describe the problem
I'm always frustrated when i call an endpoint from client and all the typesafety goes away

```svelte
<button
  on:click={async () => {
    const res = await fetch("/api/data");
    const data = await res.json();
    // const data: any
  }}>Get stuff</button
>
```

### Describe the proposed solution

like astro, and solidstart, i want a feature that enables me to call server-side functions safely:
```ts
<script>
  // $lib/server/index.ts

  function getStuff() {
    return { hello: "world" };
  }

  import { getStuff } from "$lib/server";
</script>

<button
  on:click={() => {
    getStuff();
    // getStuff(): { hello: string; }
  }}>Get stuff</button
>
```

### Importance

would make my life easier

**Comment by eltigerchino** [comment] 2024-08-31 15:24
closing as duplicate of https://github.com/sveltejs/kit/issues/9579

**Closed by eltigerchino** 2024-08-31 15:24 UTC

**Comment by huseeiin** [comment] 2024-09-02 11:53
> closing as duplicate of #9579

the issue you mentioned argues to remove form actions. are you sure my issue aligns with that?

**Comment by eltigerchino** [comment] 2024-09-02 15:37
> > closing as duplicate of #9579
> 
> the issue you mentioned argues to remove form actions. are you sure my issue aligns with that? that is a huge breaking change that i don't support.

Sorry, I linked the wrong issue. At the back of my ahead I knew there was an existing issue but I couldn't find it.
I believe this is the one https://github.com/sveltejs/kit/issues/647 . You might also be interested in https://github.com/sveltejs/kit/pull/11108 which is draft PR implementing this feature.
