### ISSUE TITLE
Cannot get props in errors returned by shadowed route

### ISSUE THREAD

**Issue by ItalyPaleAle** [sveltejs/kit#4303] opened 2022-03-12 02:02 UTC
### Describe the bug

When a shadowed (get) route returns an error, the `load` method does not receive anything from the body of the response of the shadowed route. See repro for example.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-euapgy

Navigate (manually) to the `/err` page and you'll notice that `message` is `undefined`.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 99.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.2 - ~/Library/Caches/fnm_multishells/67621_1646621511738/bin/node
    npm: 7.20.3 - ~/Library/Caches/fnm_multishells/67621_1646621511738/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Edge: 97.0.1072.55
    Firefox: 99.0
    Firefox Developer Edition: 98.0
    Safari: 15.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.295 
    svelte: ^3.46.4 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment] 2022-03-14 20:20
This is a duplicate of #3715 — the solution is being worked on in #4032

**Closed by Rich-Harris** 2022-03-14 20:20 UTC
