### ISSUE TITLE
TypeScript example for params file in Routing docs

### ISSUE THREAD

**Issue by ndbroadbent** [sveltejs/kit#5806] opened 2022-08-04 02:18 UTC
### Describe the problem

I am reading through the docs and trying to understand a demo SvelteKit app. I'm on the Routing page: https://kit.svelte.dev/docs/routing

It has this example for: `src/params/integer.js`

```
/** @type {import('@sveltejs/kit').ParamMatcher} */
export function match(param) {
  return /^\d+$/.test(param);
}
```

I'm trying to figure out how to create the `.ts` version of this file.

### Describe the proposed solution

 It would be nice if these was a code switcher here so you could toggle between JS Doc and TS examples.

Is this correct? `src/params/integer.ts`

```
import type { ParamMatcher } from '@sveltejs/kit';

export const match: ParamMatcher = (param) => {
	return /^\d+$/.test(param);
};
```

### Importance

nice to have

**Comment by benmccann** [comment] 2022-08-04 02:54
Duplicate of https://github.com/sveltejs/kit/issues/4452

**Closed by benmccann** 2022-08-04 02:54 UTC
Labels: documentation
