### ISSUE TITLE
<svelte:element this={"script"}>{@html str}</svelte:element> crashes due to persistent HTML_TAG_START

### ISSUE THREAD

**Issue by samijaber** [sveltejs/kit#11225] opened 2023-12-07 21:47 UTC
### Describe the bug

- add `<svelte:element this={"script"}>{@html "console.log(\"hello world\")"}</svelte:element>` to your code
- inspect the SSR'd HTML: it is `<script><!-- HTML_TAG_START -->console.log("hello world")<!-- HTML_TAG_END --></script>`
- the script does not run as a result of crashing (due to the invalid syntax inside of it)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-4aozhb?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte&title=SvelteKit%20Default%20Template

resulting URL: https://sveltejskittemplatedefault4aoz-01al--5173--d3416dfd.local-credentialless.webcontainer.io/ (inspect response to see SSR source)

### Logs

```Shell
Resulting SSR'd HTML:


<!doctype html>
<html lang="en">
	<head><script src="/.localservice@runtime.d3416dfd.js"></script>
		<meta charset="utf-8" />
		<link rel="icon" href="./favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		
	</head>
	<body data-sveltekit-preload-data="hover">
		<div style="display: contents">  <div class="app"><main><script><!-- HTML_TAG_START -->console.log("hello world")<!-- HTML_TAG_END --></script></main></div> 
			
			<script>
				{
					__sveltekit_dev = {
						base: new URL(".", location).pathname.slice(0, -1),
						env: {}
					};

					const element = document.currentScript.parentElement;

					const data = [null,null];

					Promise.all([
						import("/node_modules/@sveltejs/kit/src/runtime/client/start.js"),
						import("/@fs/home/projects/sveltejs-kit-template-default-4aozhb/.svelte-kit/generated/client/app.js")
					]).then(([kit, app]) => {
						kit.start(app, element, {
							node_ids: [0, 2],
							data,
							form: null,
							error: null
						});
					});
				}
			</script>
		</div>
	</body>
</html>
```

### System Info

```Shell
N/A
```

### Severity

blocking an upgrade

### Additional Information

I work on a Svelte SDK that needs to provide a script that will execute immediately on the client-side. This approach is the only way that I am aware off to try and accomplish that.

NOTE: I had the same issue with `<style>` tags, however in that case I was able to workaround it by including the tag itself inside of `@html`:

```svelte
{@html `<style>${styles}</style>`}
```

However, this same solution doesn't work with `script`s

**Comment by samijaber** [comment] 2023-12-07 22:15
I did some more testing, and this is a bit more complciated. Given the two approaches I am aware of:

- #1: have the entire tag inside `@html`:
```
{@html "<script>console.log(\"hello 1\")</script>"}
```

- #2: use `<svelte:element>` and only put the inner contents in `@html`
```
<svelte:element this={"script"}>{@html "console.log('hello 2')"}</svelte:element>
```

#1 works in Sveltekit SSR but not in a plain CSR'd svelte app.
#2 works in a CSR svelte app but not in Sveltekit SSR.


As a library author, I would like whatever approach I use to work in both scenarios, hence this issue still being valid IMHO.

**Comment by eltigerchino** [comment] 2024-11-25 05:49
Closing this because I can't reproduce the crash using Svelte 5 and the latest version of SvelteKit. Note however there is a hydration mismatch warning produced by Svelte in the browser logs.
```
[svelte] hydration_mismatch
Hydration failed because the initial UI does not match what was rendered on the server
```

**Closed by eltigerchino** 2024-11-25 05:49 UTC
