### ISSUE TITLE
Option to render page before PageLoadData has been received

### ISSUE THREAD

**Issue by TheRealThor** [sveltejs/kit#9080] opened 2023-02-17 02:06 UTC
### Describe the problem

Hello guys, 
is there a way  to optionally tell SvelteKit to not wait for the Page Load Data and start rendering the page?
Especially in areas with slow internet connection or with a big load data response I'd like to show a loading spinner after page has initially rendered but is waiting for the Page Load Data to arrive, because this is helpful to motivate users to keep waiting. Otherwise the page might look like freezing when navigating. Even pages that have been previously been rendered will look like freezing if internet is slow and the user returns to that page and page data needs some secs to arrive.

### Describe the proposed solution

Allow page to render without first receiving Page Data, for example with a flag in +page.svelte.
There should be available two variables or readable stores i.e. isLoading and isValid (to know if there was a error) to allow for different handling like showing a spinner.

### Importance

would make my life easier

**Comment by Conduitry** [comment] 2023-02-17 02:33
Duplicate of #7213.

**Closed by Conduitry** 2023-02-17 02:33 UTC
