### ISSUE TITLE
$page.stuff doesn't exist, according to TypeScript

### ISSUE THREAD

**Issue by tcc-sejohnson** [sveltejs/kit#3332] opened 2022-01-14 02:27 UTC
### Describe the bug

Using the latest version of Kit, the following is mistyped:

```typescript
import { page } from '$app/stores';

let stuff = $page.stuff; // TypeScript still thinks page contains only url and params
```

I can't for the life of me figure out where this is typed, or I'd open a pull request to add it in.

### Reproduction

Pretty simple, listed in the code block above.

### System Info

```shell
System:
    OS: Linux 5.15 Pop!_OS 21.10
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 17.18 GB / 31.32 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 7.15.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Chromium: 83.0.4103.116
    Firefox: 95.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.10 
    @sveltejs/kit: next => 1.0.0-next.229 
    svelte: ^3.44.0 => 3.46.1
```

### Severity

annoyance

**Comment by ignatiusmb** [comment] 2022-01-14 03:04
It's typing properly for me

![image](https://user-images.githubusercontent.com/8156777/149444455-83b1f3f2-c7aa-4daf-93e4-1db1ea5db4b6.png)

**Comment by Conduitry** [comment] 2022-01-14 03:39
It's typed in https://github.com/sveltejs/kit/blob/master/packages/kit/types/ambient-modules.d.ts. I also can't reproduce this.

**Comment by Mlocik97** [comment] 2022-01-14 15:12
Can't reproduce, try `npm update`.

**Comment by dummdidumm** [comment] 2022-01-14 15:20
Closing as this is no reproducible by multiple people. Maybe the editor just needs (needed) a reload because it cached the previous typings.

**Closed by dummdidumm** 2022-01-14 15:20 UTC
Labels: pending clarification

**Comment by tcc-sejohnson** [comment] 2022-01-14 23:00
@dummdidumm 

Yep, it fixed itself. It's weird, because I deleted `node_modules` and my lockfile, reloaded my window, and eventually restarted my computer with no fix. Today, get on after work, and it works fine.

*Shrug*

Appreciate the quick responses.
