### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by PingTouG** [sveltejs/kit#655] opened 2021-03-25 03:04 UTC
**Describe the bug**
[vite] Error when evaluating SSR module /node_modules/gray-matter/index.js: ReferenceError: require is not defined

**Logs**
```
11:13:27 ├F10: AM┤ [vite] Error when evaluating SSR module /node_modules/gray-matter/index.js:
ReferenceError: require is not defined
    at /node_modules/gray-matter/index.js:3:12
    at instantiateModule (D:\learn\svelte\svelte-kit-demo\node_modules\vite\dist\node\chunks\dep-efe32886.js:68893:166)
11:13:51 ├F10: AM┤ [vite] Error when evaluating SSR module /node_modules/highlight.js/lib/index.js:
ReferenceError: require is not defined
    at /node_modules/highlight.js/lib/index.js:1:12    
    at instantiateModule (D:\learn\svelte\svelte-kit-demo\node_modules\vite\dist\node\chunks\dep-efe32886.js:68893:166)
11:13:51 ├F10: AM┤ [vite] Error when evaluating SSR module /node_modules/gray-matter/index.js:
ReferenceError: require is not defined
    at /node_modules/gray-matter/index.js:3:12
    at instantiateModule (D:\learn\svelte\svelte-kit-demo\node_modules\vite\dist\node\chunks\dep-efe32886.js:68893:166)
ReferenceError: require is not defined
    at /node_modules/highlight.js/lib/index.js:1:12    
    at instantiateModule (D:\learn\svelte\svelte-kit-demo\node_modules\vite\dist\node\chunks\dep-efe32886.js:68893:166)
```

**To Reproduce**
Svelte: `^3.29.0`
SvelteKit: `^1.0.0-next.55`

repository：https://github.com/PingTouG/svelte-kit-demo

**Comment by devrnt** [comment] 2021-03-25 10:09
Probably related to https://github.com/vitejs/vite/issues/2579

**Comment by benmccann** [comment] 2021-03-29 15:31
Can you try adding this to `devDependencies"? And also try adding it to `exclude` inside `optimizeDeps`?

**Comment by devrnt** [comment] 2021-03-29 16:22
Yes tried these already, both don't seem to work. What does work is dropping `gray-matter` from `ssr.noExternal`

**Comment by devrnt** [comment] 2021-03-29 16:35
Maybe worth mentioning when you "fix" it, by removing it from `noExternal`, then undo the changes and try and reproduce this issue it does work

**Comment by benmccann** [comment] 2021-03-29 16:49
> What does work is dropping gray-matter from ssr.noExternal

Should this be considered solved then? Or is there a reason you need to use `ssr.noExternal`?

If this still doesn't work, can you see if you can reproduce it in a plain Vite app? (`npm init @vitejs/app`)

**Comment by devrnt** [comment] 2021-03-29 17:09
The SvelteKit starter comes with this line `noExternal: Object.keys(pkg.dependencies || {})`, so I think it's there with a reason

**Comment by devrnt** [comment] 2021-03-29 20:21
@benmccann 

> Both suggestions don't to work. What does work is dropping gray-matter from ssr.noExternal

Moving these deps do `devDepedencies` does actually work, still trying to figure why [Does this also need to be done for other client dependencies? Yes, it does.](https://github.com/sveltejs/kit/pull/486#issue-590911238) is true

**Comment by benmccann** [comment] 2021-03-29 21:07
It's because Vite will try to optimize `dependencies` but not `devDependencies`: https://github.com/vitejs/vite/issues/826#issuecomment-694776869

It's also possible that https://github.com/sveltejs/kit/pull/759 would have fixed this

I'm going to close this since it sounds like putting them in `devDependencies` is working

**Closed by benmccann** 2021-03-29 21:07 UTC
Labels: support, vite

**Comment by devrnt** [comment] 2021-03-29 21:57
FYI Still having the same issue after #759. It's good the have the follow-up in #581, thanks. Also SvelteKit is awesome

**Comment by resurge** [comment] 2021-03-29 22:14
I was following this issue because because I was getting the same error.

```
ReferenceError: require is not defined
    at /node_modules/@prisma/client/index-browser.js:1:16
    at instantiateModule (/home/jeroen/repos/competencies-svelte/node_modules/vite/dist/node/chunks/dep-efe32886.js:68893:166)
ReferenceError: require is not defined
    at /node_modules/@prisma/client/index-browser.js:1:16
    at instantiateModule (/home/jeroen/repos/competencies-svelte/node_modules/vite/dist/node/chunks/dep-efe32886.js:68893:166)
```

I moved everything of Prisma (prisma, @prisma/client) to devDependencies and am only using it from an endpoint, but the error stays.

**Comment by Rastavich** [comment] 2021-04-03 07:17
I'm not sure if this is right place to comment and please correct me if I have done this wrong but I am having a very similar issue. 

If I don't include "cookie" in my noExternal in svelte.config.cjs and I try and run a npm run build to Vercel, I get errors on build as below;

![image](https://user-images.githubusercontent.com/10542931/113471477-e35a7800-949f-11eb-95cf-c0c14b7ef49c.png)

It makes no difference if cookie is in package.json as either a dependencies or devDependencies.

If I have "cookie" in my noExternal then I can run a successful Vercel build but when pnpm run dev on my local I get errors from vite as below;

![image](https://user-images.githubusercontent.com/10542931/113471525-4b10c300-94a0-11eb-803c-4ea0f490e275.png)

**Comment by benmccann** [comment] 2021-04-03 13:06
I believe issues with the `cookie` library would be due to https://github.com/vitejs/vite/issues/2579

**Comment by BetaConnector** [comment] 2021-04-04 20:28
```
rror when evaluating SSR module /node_modules/faunadb/index.js:
ReferenceError: require is not defined
```

**Comment by BetaConnector** [comment] 2021-04-04 20:30
Same problem with faunadb - the database of netlify.
It's needed within the dependency - moving this to devDependencies is not an option, since it's needed within a function.

This issue should not be considered as closed.

**Comment by benmccann** [comment] 2021-04-04 21:07
Issues with loading various modules should generally be filed over at https://github.com/vitejs/vite since that's where the issue is coming from and there's not much we can do within SvelteKit to address it
