### ISSUE TITLE
Node adapter build works differently for node build vs npm run preview

### ISSUE THREAD

**Issue by aburymichael** [sveltejs/kit#1921] opened 2021-07-16 13:30 UTC
### Describe the bug

When building a project with `npm run build` using the `@sveltejs/adapter-node` adapter it predefines the routes according to its initial attempt at hitting them. When it hits private routes which return a 401, it throws an error. So I removed this auth checker function from the hooks.js file in order to have the build run successfully, but now whenever I'm fetching page on initial load (SSR) it comes back with /undefined and thus sveltekit throws a 404 for /undefined route. 

The web app works fine once hydrated, so going to links on browser works as expected but refreshing that page or going directly to a route shows the same /undefined 404 error. 

I pasted a little bit of logs, as it finishes building it runs through all the routes, just put a console log there to show it hitting each page and predetermining the outcome beforehand. So each page now becomes undefined and the only page that works is the only non-private routes to sign in etc.

The reason I'm raising this issue is that it works using `npm run build && npm run preview` and in development using `npm run dev` but when running `npm run build && node build` - which is what will happen in production - it doesn't work. This is happening both locally and on Google Cloud Run.

### Reproduction

Got a lot of private keys and database connections required for my application, so will need to create a side repo that hopefully can replicate if required.

### Logs

```shell
✓ 167 modules transformed.
.svelte-kit/output/server/app.js   433.86kb

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-node
Tables defined
Tables relationships defined
---
---
logging from hooks handle: Not authenticated, removing cookies
---
---
logging from hooks getSession: isAuthenticated:  false
---
---
logging from hooks handle: Not authenticated, removing cookies
---
---
logging from hooks getSession: isAuthenticated:  false
---
---
```

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 77.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 7.14.0 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
    Safari: 14.1.1
    Safari Technology Preview: 15.0
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.32 => 1.0.0-next.32 
    @sveltejs/kit: ^1.0.0-next.123 => 1.0.0-next.123 
    svelte: ^3.34.0 => 3.38.2
```

### Severity

blocking all usage of SvelteKit

**Comment by aburymichael** [comment] 2021-07-20 20:34
@Conduitry I've set aside some time to hopefully best demonstrate the issue, you can test it using [this reproduction repo.](https://github.com/aburymichael/ssr-node)

This isn't exactly the same way Im doing it on my other project but you'll see the same outcome is happening as described.

**Comment by benmccann** [comment] 2021-07-23 17:23
This is a very complicated reproduction and I don't think anyone would have time to dig through and understand it. `build` uses adapters while `preview` and `dev` don't, so I expect that's the difference. If you think there's some bug in `adapter-node` you'd need to make a clearer case of what that might be

**Comment by aburymichael** [comment] 2021-07-24 11:50
I'll try figure out exactly what's going on with `adapter-node` to pick up a clearer bug.

Devs will be testing with `dev` and `preview` and then when you actually deploy its going to work differently, which is a problem in my mind.

I don't want to repeat myself too much but the repro I made is using the demo app from `npm init svelte@next`, the only change is that it redirects in `hooks.js` if no session cookie is found on the `/todos` route. This works fine in `dev` and `preview` but not `node build`.

**Comment by aburymichael** [comment] 2021-07-24 13:03
I dug into the build folder that is generated and I _think_ the `prerendered` folder that gets generated may be what's causing the issue. If I look at all the protected routes that I have set up on my project, the following meta tag exists:
`<meta http-equiv="refresh" content="0;url=/auth/signin">`

Some deeper nested "pages" that are only linked on the application through its parent (not in navigation of entire app) return this:` <meta http-equiv="refresh" content="0;url=undefined">` and I think that's because its parent is protected 🙈

If you look at the [repro](https://github.com/aburymichael/ssr-node) build folder at /todos its `<meta http-equiv="refresh" content="0;url=/signin">`.

I changed the `hooks.js` to rather do a 401 status than a 302 to see if that would help, it did, although throwing 401 errors on the console when building:
```
> Using @sveltejs/adapter-node
session cookie at handle func:  undefined
session cookie at handle func:  undefined
session cookie at handle func:  undefined
session cookie at handle func:  undefined
> 401 /todos (linked from /about)
Error: 401 /todos (linked from /about)
    at error (file:///Users/michaelatterbury/Code/iWIN/ssr-undefined/node_modules/@sveltejs/kit/dist/chunks/index6.js:94:11)
    at visit (file:///Users/michaelatterbury/Code/iWIN/ssr-undefined/node_modules/@sveltejs/kit/dist/chunks/index6.js:176:5)
    at async visit (file:///Users/michaelatterbury/Code/iWIN/ssr-undefined/node_modules/@sveltejs/kit/dist/chunks/index6.js:236:6)
    at async prerender (file:///Users/michaelatterbury/Code/iWIN/ssr-undefined/node_modules/@sveltejs/kit/dist/chunks/index6.js:245:5)
    at async Object.prerender (file:///Users/michaelatterbury/Code/iWIN/ssr-undefined/node_modules/@sveltejs/kit/dist/chunks/index6.js:312:5)
    at async adapt (file:///Users/michaelatterbury/Code/iWIN/ssr-undefined/node_modules/@sveltejs/adapter-node/index.js:82:4)
    at async adapt (file:///Users/michaelatterbury/Code/iWIN/ssr-undefined/node_modules/@sveltejs/kit/dist/chunks/index6.js:338:2)
    at async file:///Users/michaelatterbury/Code/iWIN/ssr-undefined/node_modules/@sveltejs/kit/dist/cli.js:905:5
```
It didn't add the item to the prerendered folder enabling it to work on SSR load.

You can decide how to proceed with this issue - I think this is more by design but you may want to consider ignoring certain status codes from being added to the prerendered folder

**Comment by andreasnuesslein** [comment] 2021-11-28 13:44
I have the same issue. Just built everything over to use hooks-`handle` only to run in a bunch of
`<meta http-equiv="refresh" content="0;url=/accounts/login/">` .html files in my build folder.

**Comment by Rich-Harris** [comment] 2022-04-23 21:40
We can close this issue now, as the behaviour is consistent in newer versions of SvelteKit — `svelte-kit preview` uses prerendered pages instead of always dynamically rendering them.

The underlying issue here is that during prerendering, 3xx responses will result in the `<meta http-equiv>` page being written out. Normally, this only happens for pages that are marked as prerenderable (if the page isn't prerenderable, the server responds with a 204 which means 'don't save this response'), but since the 302 is coming straight from `handle` there's no place for SvelteKit to apply that logic. The solution is to either a) just do the redirect in the page itself, or b) check the [`prerendering`](https://kit.svelte.dev/docs/modules#$app-env-prerendering) flag in the hook.

**Closed by Rich-Harris** 2022-04-23 21:40 UTC
