### ISSUE TITLE
Finding Corresponding Route ID Based on Given Pathname

### ISSUE THREAD

**Issue by mehdikhody** [sveltejs/kit#11899] opened 2024-02-26 07:21 UTC
### Describe the problem

I have a -guard.ts file in some of my routes, responsible for determining whether a user can access a route or not. However, when checking in my sidebar whether a user can access a certain route, I need the corresponding route ID to access the -guard.ts for that route.

### Describe the proposed solution

I would like to have a feature that allows me to find the route ID for various pathnames within my application. For example, given the pathname "/account/sessions", the corresponding route ID might be "(panel)/account/sessions", or for "/users/32", the route ID might be "/users/[id]".

### Alternatives considered

Right now, I'm doing things the old-fashioned way with lots of if statements to check each route individually. It gets the job done, but it's not exactly cutting-edge or flexible. Having a feature that automatically figures out the route ID based on the pathname would be way cooler and save me a ton of time and hassle.

### Importance

would make my life easier

### Additional Information

N/A

**Comment by dummdidumm** [comment] 2024-02-26 08:44
This would be the inverse of https://kit.svelte.dev/docs/modules#$app-paths-resolveroute

**Comment by mehdikhody** [comment] 2024-02-26 09:09
Yes, right now I tried something that works for now. While my approach to solving my problem works, it may lead to some inefficiencies and complexities. Still, it would be a good idea to have this feature so I can find the route IDs much faster and reliable.

**Comment by gtm-nayan** [comment] 2024-03-24 12:24
Closing as duplicate of #11746

**Closed by gtm-nayan** 2024-03-24 12:24 UTC
Labels: feature request
