### ISSUE TITLE
Post request in load function is sent at least twice when using page parameter

### ISSUE THREAD

**Issue by a6h-s** [sveltejs/kit#2132] opened 2021-08-08 12:17 UTC
### Describe the bug

Hi. I need to make a post request on page load. Because I'm using the `page` parameter in the `load` function, the request is being sent twice. Is this by design?

Not sure if I'm just doing something wrong. 

```
export async function load({ fetch, page }) {
    // `code` in the URL is here because of an OAuth2 redirect
    const code = page.query.get("code"); 

    // This request is sent twice. The code can only be used once
    const res = await fetch({
        method: "POST",
        url: "https://example.com",
        body: JSON.stringify({ code }),
    });

    const aProp = await res.json();

    return {
        props: { aProp },
    };
}
```

### Reproduction

Don't have a link to a repo, but my project is just a brand new SvelteKit project. Code very similar to the above is in `index.svelte`.

### System Info

```shell
  System:
    OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 4.88 GB / 15.53 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 92.1.27.111
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.142 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment] 2021-08-09 00:36
This sounds like a bug, but we'd really need a repo to reproduce

**Comment by datasushi** [comment] 2021-08-23 14:53
I have the same issue, it seems to happen regardless of which request method, where it's called from and what params are used. I am issuing a vanilla fetch from a standard page and am debugging all requests in my golang API. 
I see three requests coming in, first one from node, followed by two from the frontend (CORS, first OPTIONS then PUT). The two requests coming from the frontend make sense, but the one coming from the backend (User-Agent: node-fetch) puzzles me. 

I have created a repo with the request dump in the readme, you can grab it here: https://github.com/datasushi/skfetchtest

Let me know if you need anything else.

**Comment by benmccann** [comment] 2021-08-23 17:14
@datasushi you should call `fetch` in `load`: https://kit.svelte.dev/docs#loading

Right now, your fetch call will be getting called once during SSR and once during CSR. If you call `fetch` in `load` then SvelteKit will send the response from the server to the client for hydration to avoid calling `fetch` again

You code doesn't use `page` so it seems completely unrelated to the report here

**Comment by datasushi** [comment] 2021-08-23 17:31
Okay, I have update the repo to reflect your comment, the behaviour remains unchanged.

**Comment by benmccann** [comment] 2021-08-23 17:37
now the issue is that you're not doing anything with `response`. try calling `await response.text()` or similar

**Comment by datasushi** [comment] 2021-08-23 17:46
Okay now only the node request is there, with POST too. This definitely works. Thanks a ton!

**Comment by benmccann** [comment] 2021-08-23 18:33
@a6h-s I'm going to close this since there's no reproduction. We can reopen if you provide one

**Closed by benmccann** 2021-08-23 18:33 UTC
Labels: pending clarification
