### ISSUE TITLE
unexpected behavior when run `npm run dev` after set config.paths.base in svelte.config.js

### ISSUE THREAD

**Issue by xcao38** [sveltejs/kit#2465] opened 2021-09-20 21:21 UTC
### Describe the bug

After set config as following in svelte.config.js:
```		
/** @type {import('@sveltejs/kit').Config} */
import node from '@sveltejs/adapter-node';

const config = {
	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		adapter: node({
			// default options are shown
			out: 'build',
			precompress: false,
			env: {
				host: 'HOST',
				port: 'PORT'
			}
		}),
		paths: {
			assets: '',
			base: '/testdir'
		}
	}
};

export default config;
```
1. Run `npm run dev`:
In `http://localhost:3000/testdir`, I got the following:
```
Error: Not found: 
    at resolve (file:///Users/xiaofengcao/projects/svelte/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1728:13)
    at async Object.handle (//Users/xiaofengcao/projects/svelte/my-app/src/hooks:13:19)
    at async respond (file:///Users/xiaofengcao/projects/svelte/my-app/node_modules/@sveltejs/kit/dist/ssr.js:1675:10)
    at async svelteKitMiddleware (file:///Users/xiaofengcao/projects/svelte/my-app/node_modules/@sveltejs/kit/dist/chunks/index.js:4531:22)
```
2. Run `npm run build` & `npm run preview`:
- app was successfully built
- after npm run preview, a lot of js and css file did not picked up, please see the errors in the web console.
![image](https://user-images.githubusercontent.com/47402095/134076749-ee9754b2-5c47-43aa-b406-2f87516f15cd.png)

### Reproduction

Step 1: start a sveltekit app: https://kit.svelte.dev/
```
npm init svelte@next my-app
cd my-app
npm install
npm run dev -- --open
```

Step 2: change `svelte.config.js` to following:
```
/** @type {import('@sveltejs/kit').Config} */
import node from '@sveltejs/adapter-node';

const config = {
	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		adapter: node({
			// default options are shown
			out: 'build',
			precompress: false,
			env: {
				host: 'HOST',
				port: 'PORT'
			}
		}),
		paths: {
			assets: '',
			base: '/testdir'
		}
	}
};

export default config;

```

Step 3: install @sveltejs/adapter-node
```
npm i -D @sveltejs/adapter-node@next
```

Then run `npm run dev` or `npm run build` and `npm run preview`. 

### System Info

```shell
npx: installed 1 in 1.189s

  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 11.10 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.49 => 1.0.0-next.49 
    @sveltejs/kit: next => 1.0.0-next.170 
    svelte: ^3.34.0 => 3.42.6 
```

### Severity

blocking all usage of SvelteKit

### Additional Information

We are trying to release a sveltekit app under a sub url. This is seriously blocking our deployment.

**Comment by Karlinator** [comment] 2021-09-20 22:01
This is only an issue in preview, right? I think this is just #2409 showing up?

Does it run correctly with `npm run dev` and when using the node adapter (`node build` after `npm run build`)? If it does, then this should be fixed by #2409

**Comment by xcao38** [comment] 2021-09-20 22:22
> This is only an issue in preview, right? I think this is just #2409 showing up?
> 
> Does it run correctly with `npm run dev` and when using the node adapter (`node build` after `npm run build`)? If it does, then this should be fixed by #2409

I

**Comment by Karlinator** [comment] 2021-09-20 22:29
@xcao38 #2409 isn't merged yet, so you won't get it even with upgrading. It'll probably be live soon-ish though. If your `package.json` has explicit version names (say, `1.0.0-next.169`) you can just change that and run `npm i`. Also `npm i -D @sveltejs/kit@1.0.0-next.170` will do the trick. If you have the version just specified as `next` then a simple `npm update` (or `npm update @sveltejs/kit` I think) will update.

**Comment by benmccann** [comment] 2021-09-20 22:38
> This is only an issue in preview, right?

Not according to the issue report which says its an issue in dev and preview:

> Then run `npm run dev` or `npm run build` and `npm run preview`.

**Comment by Karlinator** [comment] 2021-09-20 22:50
Ugh, my eyes betray me.

There might be a similar issue in the dev server, I haven't looked. I'm not as familiar with Vite and all that, but that would be my guess.

There is  this line: https://github.com/sveltejs/kit/blob/7dec53ecc66793841cf7702cb8d7453bb5cb5bad/packages/kit/src/core/dev/index.js#L296

Maybe assets are rejected at that point?

**Comment by Karlinator** [comment] 2021-09-20 23:23
@xcao38 do you have the full path of the files the browser is requesting? Is it requesting all assets in the correct locations (`/testdir/_app/whatever`) in both dev and preview (and are the paths the same in dev and preview)?

If those paths are all correct then I think we have one bug in preview (already known) and a separate but similar bug in dev (manifests the same, but caused differently since dev and preview servers are quite different internally, what with Vite etc).

**Comment by xcao38** [comment] 2021-09-20 23:28
> @xcao38 do you have the full path of the files the browser is requesting? Is it requesting all assets in the correct locations (`/testdir/_app/whatever`) in both dev and preview (and are the paths the same in dev and preview)?
> 
> If those paths are all correct then I think we have one bug in preview (already known) and a separate but similar bug in dev (manifests the same, but caused differently since dev and preview servers are quite different internally, what with Vite etc).

I could show you my file structure. Not sure where to find the files... Let me know if you need anything :) 

![image](https://user-images.githubusercontent.com/47402095/134089587-3820b2c8-3326-45bd-872b-74789ae71f74.png)

**Comment by Karlinator** [comment] 2021-09-20 23:37
I meant the network log from the browser 😅 I want to see if the links and source urls embedded into the page are correct. In your devtools 'Network' tab you can click on the requests and just see if the Request URLs all have '/testdir/' in them. They should look like `localhost:3000/testdir/_app/pages/whatever`. If tehy look like `localhost:3000/_app/pages/whatever` (without 'testdir' in tehm) then we have a different problem.

**Comment by xcao38** [comment] 2021-09-20 23:44
> I meant the network log from the browser 😅 I want to see if the links and source urls embedded into the page are correct. In your devtools 'Network' tab you can click on the requests and just see if the Request URLs all have '/testdir/' in them. They should look like `localhost:3000/testdir/_app/pages/whatever`. If tehy look like `localhost:3000/_app/pages/whatever` (without 'testdir' in tehm) then we have a different problem.

Here you go: 
![image](https://user-images.githubusercontent.com/47402095/134091153-d5b41736-c2f2-4e14-a21f-50acae8b67c4.png)

**Comment by xcao38** [comment] 2021-09-22 14:55
Hi @Karlinator thanks for the quick turnaround! Just curious, is there a timeline on releasing the new updates on `paths.base`?

**Comment by benmccann** [comment] 2021-09-22 15:43
The dev mode change is in 170 and the preview mode change is in 171: https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md

**Comment by Karlinator** [comment] 2021-09-22 15:53
I don't think 170 or 171 actually fixes the dev mode issue here. 170 fixed an issue in pre-rendering, 171 fixed an issue in the preview server. I haven't had time to reproduce and go digging, but it looks like there's a separate issue in the dev server.

**Comment by xcao38** [comment] 2021-09-22 16:56
@benmccann @Karlinator Thanks both for your time! FWIW, I upgraded my sveltekit to 171 with following:
`npm add -D @sveltejs/kit@1.0.0-next.171`. 

Then I run `npm run build` and `npm run preview`, the problem with assets not found is gone. What I can see on my screen and console is as following:

### Broswer: 
![image](https://user-images.githubusercontent.com/47402095/134387604-02196daf-cecc-4f6a-9f70-74df05d33406.png)

### Console:
![image](https://user-images.githubusercontent.com/47402095/134387736-b548e2cb-c63f-40d7-816f-fff10816a13c.png)
![image](https://user-images.githubusercontent.com/47402095/134387795-79db9aa0-587e-450f-b41f-7681b86b2a1e.png)

### Terminal:
```
(base) Xiaofengs-MacBook-Pro:my-app xiaofengcao$ npm run preview

> my-app@0.0.1 preview /Users/xiaofengcao/projects/svelte/my-app
> svelte-kit preview


  SvelteKit v1.0.0-next.171

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network

```

**Comment by Karlinator** [comment] 2021-09-22 17:33
I believe you need the trailing slash, so `localhost:3000/testdir/`.

**Comment by xcao38** [comment] 2021-09-22 18:02
> I believe you need the trailing slash, so `localhost:3000/testdir/`.

Thank you! very helpful. Yeah it did the trick:)

**Comment by maiertech** [comment] 2021-09-29 20:48
This is still an issue in 177. Once you revert to Vite for previewing, will this fix the issue when there is no trailing `/`?

**Comment by benmccann** [comment] 2021-09-29 21:21
I don't think we'll use Vite for preview mode actually. What they do for their `preview` mode is too different (e.g. it doesn't do SSR at all)

**Comment by benmccann** [comment] 2022-01-20 19:32
Closing this as a duplicate of https://github.com/sveltejs/kit/issues/2958

**Closed by benmccann** 2022-01-20 19:32 UTC
Labels: bug
