### ISSUE TITLE
`import {readFile} from 'fs/promises';` ESM syntax fails trying to import from a file

### ISSUE THREAD

**Issue by georgecrawford** [sveltejs/kit#1689] opened 2021-06-14 15:00 UTC
**Describe the bug**
A page component that imports promisified `fs` methods like this
```
<script context="module">
    import {readFile} from 'fs/promises';
</script>
```
...fails with the error `Failed to resolve import "fs/promises" from "index.svelte". Does the file exist?`:
<details>
  <summary>Stacktrace</summary>

```
500
Failed to resolve import "fs/promises" from "index.svelte". Does the file exist?

Error: Failed to resolve import "fs/promises" from "index.svelte". Does the file exist?
    at formatError (/app/server/node_modules/vite/dist/node/chunks/dep-e9a16784.js:44070:46)
    at TransformContext.error (/app/server/node_modules/vite/dist/node/chunks/dep-e9a16784.js:44066:19)
    at normalizeUrl (/app/server/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68952:26)
    at async TransformContext.transform (/app/server/node_modules/vite/dist/node/chunks/dep-e9a16784.js:69080:57)
    at async Object.transform (/app/server/node_modules/vite/dist/node/chunks/dep-e9a16784.js:44268:30)
    at async transformRequest (/app/server/node_modules/vite/dist/node/chunks/dep-e9a16784.js:58540:29)
    at async instantiateModule (/app/server/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68145:10)
```
</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,@sveltejs/adapter-node,@sveltejs/adapter-static,@sveltejs/adapter-begin,@sveltejs/adapter-netlify,@sveltejs/adapter-vercel vite --binaries --browsers`
```
  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.36 GB / 7.77 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.24
    @sveltejs/kit: ^1.0.0-next.115 => 1.0.0-next.115
    svelte: ^3.38.2 => 3.38.2
```
</details>

**Severity**
I can work around this like so:
```
<script context="module">
    import {promises as fsPromises} from 'fs';
    const {readFile} = fsPromises;
</script>
```

**Comment by georgecrawford** [comment] 2021-06-14 15:28
I've had a follow-up from @GrygrFlzr in Discord that my use-case would be better written as an endpoint rather than a page, but this import failure does still seem like a bug, or at least a limitation which needs to be documented.

**Comment by georgecrawford** [comment] 2021-06-14 15:31
And to add to my initial report - this same issue seems to affect endpoints as well.

**Comment by benmccann** [comment] 2021-06-14 15:36
I've never had any issue using ESM syntax in SvelteKit. I expect there's some usage issue or usage with the library you're using

I notice that the Node 16 docs have an example of using ESM syntax for fs promises: https://nodejs.org/api/fs.html#fs_promise_example
But the Node 14 docs do not: https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_promise_example

If you try on Node 16 does it work? (You can use nvm to switch between versions of Node)

**Comment by georgecrawford** [comment] 2021-06-14 16:17
Thanks Ben - I'll try on Node 16 and let you know.

**Comment by mdynnl** [comment] 2021-06-16 15:17
same error with node 16

**Comment by benmccann** [comment] 2021-06-16 15:32
Can you provide a repo where this code fails in an endpoint?

**Comment by mdynnl** [comment] 2021-06-18 12:17
A repro-repo is probably not necessary. Just a fresh `svelte-kit` + node `v16.3.0` and `import fs from 'fs/promises'; console.log(fs)` is enough. But for the sake of repro. Here's the repro-repo => https://github.com/mdynnl/svelte-kit-issue-1689

**Comment by benmccann** [comment] 2021-06-26 21:41
This is surprising. I'm afraid I have no idea what's going on

**Comment by raythurnevoid** [comment] 2021-06-30 03:56
I'm quite sure this is an issue caused by the fact that Vite uses this package to determine built-in node modules: https://github.com/sindresorhus/builtin-modules
I've opened two issues about this: https://github.com/sindresorhus/builtin-modules/issues/13, https://github.com/vitejs/vite/issues/4037

**Comment by benmccann** [comment] 2021-07-23 17:27
Thanks for the investigation! I'm going to close this in favor of the `builtin-modules` and `vite` issues.

**Closed by benmccann** 2021-07-23 17:27 UTC
