### ISSUE TITLE
Vite thinks I'm using JSX when I use JS in markup

### ISSUE THREAD

**Issue by kwangure** [sveltejs/kit#1654] opened 2021-06-08 17:46 UTC
**Describe the bug**
When I write JS in a component `<slot/>`, Vite complains that the compiled output is using JSX even though it's not.

```svelte
<script>
    import Code from "./Code.svelte";
</script>

<Code>
    const product = 1 * 1;

    console.log({"{"}product{"}"});

    export default product;
</Code>

<-- Code.svelte -->
<code><slot/></code>
```

**Expected behavior**
Vite should treat JS in markup as normal HTML text.

**Repro**
https://github.com/kwangure/sveltekit-javascript-repro

Note in the stacktrace that issue https://github.com/sveltejs/kit/issues/1653 persists in the repro.

<details>
  <summary>Stack trace</summary>

```
7:41:30 PM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /sveltekit-javascript-repro/src/routes/issue-2.svelte
  38 |                          t2 = text("product");
  39 |                          t3 = text(t3_value);
  40 |                          t4 = text(");\n\n    import * as ___SVELTE_HMR_HOT_API from '/sveltekit-javascript-repro/node_modules/svelte-hmr/runtime/hot-api-esm.js';import { adapter as ___SVELTE_HMR_HOT_API_PROXY_ADAPTER } from '/sveltekit-javascript-repro/node_modules/svelte-hmr/runtime/proxy-adapter-dom.js';if (import.meta && import.meta.hot) { if (false) import.meta.hot.accept(); product = ___SVELTE_HMR_HOT_API.applyHmr({ m: import.meta, id: "/sveltekit-javascript-repro/src/routes/issue-2.svelte", hotOptions: {"preserveLocalState":false,"noPreserveStateKey":["@hmr:reset","@!hmr"],"preserveAllLocalStateKey":"@hmr:keep-all","preserveLocalStateKey":"@hmr:keep","noReload":false,"optimistic":true,"acceptNamedExports":true,"acceptAccessors":true,"injectCss":false,"cssEjectDelay":100,"native":false,"importAdapterName":"___SVELTE_HMR_HOT_API_PROXY_ADAPTER","noOverlay":true}, Component: product, ProxyAdapter: ___SVELTE_HMR_HOT_API_PROXY_ADAPTER, acceptable: true, preserveLocalState: false, emitCss: true, }); }
     |^
  41 |  export default product;
  42 |
      at formatError (/sveltekit-javascript-repro/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:44553:46)
      at TransformContext.error (/sveltekit-javascript-repro/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:44549:19)
      at TransformContext.transform (/sveltekit-javascript-repro/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:69512:22)
      at async Object.transform (/sveltekit-javascript-repro/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:44751:30)
      at async transformRequest (/sveltekit-javascript-repro/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:59118:29)
      at async viteTransformMiddleware (/sveltekit-javascript-repro/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:59256:32)
```
</details>

<details>
  <summary>SvelteKit Installation Information</summary>

System:
OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Memory: 1.56 GB / 3.05 GB
Container: Yes
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 16.2.0 - /usr/bin/node
npm: 7.13.0 - /usr/bin/npm
npmPackages:
@sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.13
@sveltejs/kit: ^1.0.0-next.113 => 1.0.0-next.113
svelte: ^3.38.2 => 3.38.2
Browser: Chrome 91
</details>

**Severity**
It's not severe, but it it annoying. It's possible to work around it by escaping/HTML-encoding the JS text.

I'm not sure whether this is something to be solved at the vite-plugin-svelte or Vite level. I can move the issue to the appropriate repro as needed.

**Comment by Conduitry** [comment] 2021-06-08 18:00
I'd suggest using `&#123;` instead of `{"{"}` anyway (and then just using `}` as-is), which is going to be more efficient anyway.

This looks like the same issue as #1653. You can see in the stack trace that what Vite is getting has HMR code getting injected into the string, and is syntactically incorrect. (It has unescaped `"`s inside a string enclosed by `"`s.) So, Vite's correct in not being able to parse this. The error message is just trying to be helpful - I don't think Vite thinks you're using JSX.

Closing as duplicate of #1653.

**Closed by Conduitry** 2021-06-08 18:00 UTC
