### ISSUE TITLE
@fontsource/roboto not working after upgrading from vite 4 to vite 5

### ISSUE THREAD

**Issue by xxxhussein** [sveltejs/kit#11121] opened 2023-11-24 14:46 UTC
### Describe the bug

roboto-latin-500-normal.8Xcd2lzs.woff2:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
roboto-latin-500-normal.3Jvq4Vhd.woff:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)

### Reproduction

in `+layout.svelte`:

```js
import '@fontsource/roboto/500.css'
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 2.47 GB / 3.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.10.5 - ~/.bun/bin/pnpm
    bun: 1.0.13 - ~/.bun/bin/bun
  npmPackages:
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1
    @sveltejs/kit: ^1.27.6 => 1.27.6
    svelte: ^4.2.7 => 4.2.7
    vite: ^5.0.2 => 5.0.2
```

### Severity

serious, but I can work around it

### Additional Information

Serious but i *can't* work around it without using google fonts cdn :D

**Comment by xxxhussein** [comment] 2023-11-24 14:49
related to https://github.com/sveltejs/kit/issues/11062

**Comment by eltigerchino** [comment] 2023-11-24 16:30
Duplicate of https://github.com/sveltejs/kit/issues/11085

**Closed by eltigerchino** 2023-11-24 16:30 UTC
