### ISSUE TITLE
A way to detect module load failure.

### ISSUE THREAD

**Issue by andreivreja** [sveltejs/kit#1861] opened 2021-07-09 03:07 UTC
Currently, navigating to a route when the route’s module is no longer available results on a `500` with the default error created by v8 (or the browser?).  This makes it hard to accurately detect module load failures in the `load` function for `__error.svelte` since browsers will show different error messages (and checking for a string isn’t really reliable anyway). 

**Describe the solution you'd like**
An extra property passed to `load`, like `moduleError` boolean, or even attaching an extra property to the returned error.

**Describe alternatives you've considered**
Reading the error message but it’s up to the browser to chose that message (or v8?). In my use case, Desktop Chrome and iOS browser show different errors.

**How important is this feature to you?**
Pretty important, and should be straight forward to implement.

**Additional context**
Upon a new build, old build files get deleted in my case, so being on the app during a new build results in module load failures (well, they are gone). A flag like the suggested one makes it easy to determine when to show a message to the user asking to reload the page (or force reload or whatever). A service worker can solve this issue but I feel it should be part of kit.

**Comment by andreivreja** [comment] 2021-07-09 09:16
More context - it gets ugly (I've actually got it all in a try catch block in my use case because there's no guarantee the error will have a message, that the message will be a string etc).

```js
<script context="module">
	export async function load({ error, status }) {
		return { props: { errorMessage: error.message, status } };
	}
</script>

<script>
	export let errorMessage, status;

	$: moduleLoadFailed =
		status === 500 &&
		(errorMessage.toLowerCase().includes('failed to fetch dynamically imported module') ||
			errorMessage.toLowerCase().includes('importing a module script failed'));
</script>

{#if moduleLoadFailed}
	Error loading module, please refresh
{:else}
	Other error
{/if}
```

**Comment by dummdidumm** [comment] 2021-07-09 15:44
Possibly related (maybe a superset of this issue): #1857

**Comment by andreivreja** [comment] 2021-07-09 16:09
Checked that out like an hour ago and it doesn't really have anything to do with it - but definitely another error reporting improvement. Error handling over all should be more descriptive.

**Comment by andreivreja** [comment] 2021-07-09 16:18
Though now that I looked at the `error handling` label, seems like this is a duplicate of https://github.com/sveltejs/kit/issues/1678

**Comment by dummdidumm** [comment] 2021-07-09 16:20
Good find, thanks. Closing as duplicate of #1678

**Closed by dummdidumm** 2021-07-09 16:20 UTC
