### ISSUE TITLE
`+layout.server.ts` is called on every client side navigation to nested routes

### ISSUE THREAD

**Issue by pilcrowOnPaper** [sveltejs/kit#6035] opened 2022-08-18 13:22 UTC
### Describe the bug

Assuming a route folder like so:

```
+layout.server.ts
+layout.ts
+page.ts
/foo
    +page.ts
```

`+layout.server.ts` is called again when navigating `/` → `/foo` (client side). However, if the user were to change `+layout.server.ts` to `+layout.ts`, it won't be called on the same navigation. The expected behavior is `+layout.server.ts` should only run on initial page load.

### Reproduction

repo: https://github.com/pilcrowOnPaper/layout-load-issue

### Steps:
1. Check consoles
2. Navigate `/` → `/foo`
3. Check consoles
4. Navigate `/foo` → `/foo/bar`
5. Check consoles

#### Logs (combined client and server):

```bash
load: /+layout.server.ts

goto: /foo
load: /+layout.server.ts
load: /foo/+layout.ts

goto: /foo/bar
load: /+layout.server.ts
```

#### Expected logs:

```bash
load: /+layout.server.ts

goto: /foo
load: /foo/+layout.ts

goto: /foo/bar
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz
    Memory: 150.23 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.420 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

serious, but I can work around it

### Additional Information

With the removal of `session`, `/+layout.server.ts` was the provided as an alternative to `getSession()` in #5883 but has different behaviors.

**Comment by CaptainCodeman** [comment] 2022-08-18 13:48
Duplicate of https://github.com/sveltejs/kit/issues/5960 ?

**Comment by Conduitry** [comment] 2022-08-18 13:52
Yup. Duplicate of #5960.

**Closed by Conduitry** 2022-08-18 13:52 UTC
