### ISSUE TITLE
`.svelte-kit/tsconfig.json` should be be populated with `config.kit.vite.resolve.alias`

### ISSUE THREAD

**Issue by martinszar** [sveltejs/kit#4530] opened 2022-04-05 16:31 UTC
### Describe the problem

Basically self-describing. Since SvelteKit generates an `tsconfig.js` it should be pretty easy to automatically populate it's `compilerOptions.paths` based on the vite config object.

### Describe the proposed solution

Adding a simple for loop at [`write_tsconfig.js`](https://github.com/sveltejs/kit/blob/c803cc07c037cee19a078fc212ca44c91a0d73df/packages/kit/src/core/sync/write_tsconfig.js#L62)  should be sufficient.

### Alternatives considered

Obviously manually adding aliases to `jsconfig.json` is fine, even though there are a couple of issues with it, since, for instance, you can't forget to add `"$lib": [ "src/lib" ]` and `"$lib/*": [ "src/lib/*" ]` to `compilerOptions.paths` because it overwrites `"extends": "./.svelte-kit/tsconfig.json"`.

### Importance

nice to have

### Additional Information

By the way [the FAQs](https://kit.svelte.dev/faq#aliases) do not contain `"extends": "./.svelte-kit/tsconfig.json"` in the `jsconfig.json` example.

**Comment by dummdidumm** [comment] 2022-04-05 16:45
Duplicate of #4496

**Closed by dummdidumm** 2022-04-05 16:45 UTC
