### ISSUE TITLE
Can we have something like useFetcher in Remix 🙏 ?

### ISSUE THREAD

**Issue by juniorforlife** [sveltejs/kit#10382] opened 2023-07-14 02:51 UTC
### Describe the problem

Even though we already have `load` function for page data loading, sometimes you want to call `load` outside of navigation, or call an action (and get the routes to reload) but you don't want the URL to change.
This is useful when you need to:
 - fetch data not associated with UI routes (popovers, dynamic forms, etc.)
 - submit data to actions without navigating (shared components like a newsletter sign ups)
 - handle multiple concurrent submissions in a list (typical "todo app" list where you can click multiple buttons and all be pending at the same time)
 - infinite scroll containers
 
 Unfortunately, we don't have a convenient way to achieve this in SvelteKit currently

### Describe the proposed solution

In Remix you can do this with [useFetcher](https://remix.run/docs/en/main/hooks/use-fetcher). 
It would be great if we can have something similar

### Importance

would make my life easier

**Comment by hackape** [comment] 2023-07-14 04:22
I don’t think `load` function is comparable to Remix `useFetch`.

To me it’s unclear what your feature request really is. It sounds to me you can just use `fetch` JS API to archive thing you described. Or maybe you just want a nice wrapper around it?

If I get it wrong, perhaps you can propose an imaginary API that works for you, so to make your point clear.

**Comment by juniorforlife** [comment] 2023-07-14 10:42
I didn’t compare `load` function with `useFetcher`. Remix has `loader` which is the same as `load` but they still provide `useFetcher` because of the benefits I listed above

**Comment by tcc-sejohnson** [comment] 2023-07-14 22:07
@hackape the problem he's outlining is that you have to use a special `fetch` when loading data inside a `load` function. This means any data fetching that happens through other SDKs (for example, contentful or s3) has to have this `fetch` passed in as an initialization argument. This can be kind of annoying. Ideally, we'd just be able to use `fetch` wherever and have it work. This isn't simple, but would be a great feature if there were a non-footgun-y way to do it.

**Comment by hackape** [comment] 2023-07-15 01:17
@juniorforlife How about for all scenarios “beyond `load`”, I setup a `src/api/foo/+server.ts` API-only endpoint, and then I can use the standard `fetch("/api/foo")` API on client side or server side from within other routes, even within a `load` function.

I think this solution covers them all. It’s just plain AJAX that we used to do alot in SPA era. What am I missing?

**Comment by hackape** [comment] 2023-07-15 01:24
@tcc-sejohnson I don’t think he’s talking about the special `fetch` you get in `load`. But if that bothers you, the API-only endpoint solution can also take care of your need. You put all things dependent on a normal `fetch` into the endpoint,  handle them there. And if your `load` need the data, fetch from that endpoint instead.

**Comment by juniorforlife** [comment] 2023-07-15 04:01
@hackape Ryan Florence made a really nice video explaining the use case of `useFetcher` [here](https://www.youtube.com/watch?v=vTzNpiOk668). 

> how about for all scenarios “beyond load”, I setup a src/api/foo/+server.ts API-only endpoint, and then I can use the standard fetch("/api/foo") API on client side or server side from within other routes, even within a load function.


Yes this is doable but then you have to manually manage data, loading and error state. Also `useFetcher` allows Optimistic UI, you can display data before the response actually comes back from the BE

**Comment by fehnomenal** [comment] 2023-07-15 06:28
You should look into tanstack query. They have a svelte integration.

**Comment by juniorforlife** [comment] 2023-07-15 06:37
> You should look into tanstack query. They have a svelte integration.

yes but since SvelteKit is a battery-included framework so I think this pretty common feature should be built-in.
 
Also Tanstack has a [quirkiness](https://tanstack.com/query/latest/docs/svelte/ssr)  when integrate with SvelteKit

> SvelteKit defaults to rendering routes with SSR. Because of this, you need to disable the query on the server. Otherwise, your query will continue executing on the server asynchronously, even after the HTML has been sent to the client.

**Comment by hackape** [comment] 2023-07-16 15:52
So it’s still a nice wrapper around fetch API that you want. To me this is sth better done by a 3rd party lib, and not in the scope of sveltekit. But that’s my opinion.

**Comment by eltigerchino** [comment] 2024-11-22 09:42
Closing as duplicate of https://github.com/sveltejs/kit/issues/11847

**Closed by eltigerchino** 2024-11-22 09:42 UTC
Labels: feature request
