### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#9427] opened 2023-03-15 16:13 UTC
### Describe the bug

I am seeing the memory usage of my SvelteKit app, running with the Node adapter, going up and up. I'm not sure how the server's memory usage can keep increasing, all the svelte stores for example are only used in the browser, and other than that the server requests should be stateless, right?

![Screenshot_2023-03-05_at_11 47 49](https://user-images.githubusercontent.com/229384/225367472-1c5c27a1-7771-4587-8446-1707fc9cce38.png)

![Screenshot 2023-03-16 at 09 12 14](https://user-images.githubusercontent.com/229384/225554848-c8b8871d-1a0c-44a5-9f6f-4c4a494eead0.png)

See https://discord.com/channels/457912077277855764/1081891569390583898 for a discussion about this.

### Reproduction

As far as I know, any project will show this problem.

Create a new skeleton project. No need to add TypeScript, Prettier, ESLint or anything else.

```
npm create svelte@latest repro
cd repro
npm i
npm run build
npm run preview
```

Open http://127.0.0.1:4173/, open the activity monitor (on macOS) or `top` or whatever else to see memory usage of the Node process, and refresh the webpage a whole bunch of times. You'll see the memory go up. It's slow to increase with such a simple skeleton project so you might need to refresh a whole bunch of times, but it does go up.

In my moderately popular website it goes up by about 300 MB per day.

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 274.47 MB / 32.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: 110.0.1587.69
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.11.0
    svelte: ^3.54.0 => 3.56.0
    vite: ^4.0.0 => 4.1.4
```

### Severity

serious, but I can work around it

### Additional Information

I have to restart my Node server once in a while or the server just runs out of memory.

**Comment by kevinrenskers** [comment] 2023-03-24 18:34
Is that being tracked in their repo somewhere?

**Comment by vhscom** [comment] 2023-03-24 19:07
> Is that being tracked in their repo somewhere?

Until the SK team triages the issue it's not clear (to me at least) if it's an upstream issue in the dependency. But I have seen videos showing GC is able to reclaim space if `fetch` is replaced with calls using another Node-friendly client such as Axios.

**Comment by kevinrenskers** [comment] 2023-04-11 14:46
I've deployed a new version, will keep an eye on the memory usage and report back.

**Comment by machycek** [comment] 2023-04-14 04:45
@kevinrenskers we are having the same issue actually

**Comment by gtm-nayan** [comment] 2023-04-14 07:44
@kevinrenskers 
Was this using the default server that's provided by the adapter or using just the handler in a custom server?

**Comment by gtm-nayan** [comment] 2023-04-14 07:46
And this also happens with npm run preview?

**Comment by kevinrenskers** [comment] 2023-04-14 07:58
I don't know, I don't want to run my production website that way to find out 😅 I'll try it locally, see what happens.

**Comment by dominikg** [comment] 2023-04-14 12:14
can you please confirm the exact versions of operating system, node, @sveltejs/kit, @sveltejs/adapter-node and undici where you are observing this behavior?

**Comment by kevinrenskers** [comment] 2023-04-15 09:43
> can you please confirm the exact versions of operating system, node, @sveltejs/kit, @sveltejs/adapter-node and undici where you are observing this behavior?

  System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 AMD EPYC Processor
    Memory: 4.68 GB / 7.58 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.19.1 - /usr/bin/node
    npm: 8.19.3 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0 => 1.2.3
    @sveltejs/kit: ^1.0.0 => 1.15.4
    svelte: ^3.54.0 => 3.58.0

undici: 5.20.0

**Comment by kevinrenskers** [comment] 2023-04-15 09:46
> And this also happens with npm run preview?

Yes

**Comment by kevinrenskers** [comment] 2023-04-19 14:37
I'm already using undici 5.20.0 though, but sure I'll try. Where do I put these overrides?

**Comment by stalkerg** [comment] 2023-04-19 14:57
on the same level as `"devDependencies": {` also, very important to downgrade `adapter-node` as well (undici bundling by bable)

**Comment by kevinrenskers** [comment] 2023-04-19 15:29
So far it seems improved, but I'll know for sure in a day or so. I'll report back.

**Comment by dummdidumm** [comment] 2023-04-20 09:28
@stalkerg am I seing this correctly that undici has released the fix for the memory leak in https://github.com/nodejs/undici/releases/tag/v5.21.1 so we can bump to latest undici again?

**Comment by stalkerg** [comment] 2023-04-21 01:02
@dummdidumm yes! Now it's fixed without a timeout breakage. My small local tests are working well.

**Comment by kevinrenskers** [comment] 2023-04-24 17:06
This fix isn't released yet, right? Because I updated all my dependencies, removed the `overrides`, and the problem is back in full force.

**Comment by s3812497** [comment] 2023-04-24 17:07
> This fix isn't released yet, right? Because I updated all my dependencies, removed the `overrides`, and the problem is back in full force.

No, it's not released yet.

**Comment by kevinrenskers** [comment] 2023-04-24 17:17
Is there an ETA on a release? So I can decide if I should revert my change or just wait a bit.

**Comment by s3812497** [comment] 2023-04-25 01:38
> Is there an ETA on a release? So I can decide if I should revert my change or just wait a bit.

It's out now! :) https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%401.15.8

**Comment by stalkerg** [comment] 2023-04-25 01:56
@s3812497 it's not enough; we also must update the node adapter because of bundling (this issue is not in direct dependencies)

**Comment by s3812497** [comment] 2023-04-25 01:57
> @s3812497 it's not enough; we also must update the node adapter because of bundling (this issue is not in direct dependencies)

Ah, sorry about that. I didn't know.

**Comment by stalkerg** [comment] 2023-04-25 01:59
@s3812497 `@sveltejs/adapter-node/files/shims.js` still includes old undici and the node adapter will use it.

**Comment by stalkerg** [comment] 2023-04-25 02:00
@dummdidumm we must update `adapter-node` as well, just sveltekit is not enough.

**Comment by itssumitrai** [comment] 2023-04-26 14:46
Can we fix this asap ? Our production server capacity is lost by more than 100%. Basically we need to have more than twice the servers and the perf has become really bad as well. We have no choice other than to pin down adapter node. Can this issue get more traction ?

**Closed** 2023-04-27 04:29 UTC
Labels: bug

**Comment by kevinrenskers** [comment] 2023-04-28 11:20
I've updated all dependencies to their latest versions, and the memory leak is not fixed. [This workaround](https://github.com/sveltejs/kit/issues/9427#issuecomment-1514838718) worked fine, but after removing the overrides and updating all packages, the leak is back in full force.

**Comment by kevinrenskers** [comment] 2023-04-28 11:38
Never mind, the deploy to my server didn't work as expected due to `pnpm-lock.yaml` changes after updating pnpm on my server but not locally. That causes a local change which prevented `git pull` from completing.

**Comment by henryson** [comment] 2024-11-29 07:59
About 1.5 years later I experience this same problem. I thought this thread would help me but since I run svelte-kit 2.5.4 I guess the above fix should already be there. Maybe a similar problem has arised again? Or should I continue look elsewhere?

**Comment by henryson** [comment] 2024-11-29 08:29
Hi, thanks for quick response.

No I am not sure at all. But our app hangs after less than a day (in production) and I am trying to look for all ways to fix this.

We were running node 21.7 but I downgraded to 20.18.1 because some other post said it could work. But it didn’t.

Cheers, Josef

Från: Yury Zhuravlev ***@***.***>
Datum: fredag, 29 november 2024 09:15
Till: sveltejs/kit ***@***.***>
Kopia: Josef Henryson ***@***.***>, Mention ***@***.***>
Ämne: Re: [sveltejs/kit] Memory leak? (Issue #9427)

@henryson<https://github.com/henryson> did you use latest stable nodejs? Also, are you sure you have totally same issue? You can go to undici tracker than.

**Comment by stalkerg** [comment] 2024-11-29 10:08
You should isolate your issue and make small reproduction demo. Without it, any suggest will not too different from random advice.

**Comment by dominikg** [comment] 2024-11-29 10:12
this specific issue has been resolved. it makes no sense to discuss all possible memory leaks in the comments here and notify participants in the process. - locking it now, please file a new one with a reproduction and downloadable heap snapshots for comparison that show it is actually sveltekit causing the memory leak.

If you are unsure how to do this, please join https://svelte.dev/chat and ask for help in `#help-svelte-and-kit`
