### ISSUE TITLE
@s3812497 Hello Tee Thanks for your help, i tried this and it worked locally but unfortunately it failed on vercel again and this is the error:

### ISSUE THREAD

**Issue by oxneat** [sveltejs/kit#10601] opened 2023-08-22 15:05 UTC
@s3812497 Hello Tee Thanks for your help, i tried this and it worked locally but unfortunately it failed on vercel again and this is the error: 
`Error: ENOENT: no such file or directory, open './_app/immutable/assets/FuturaPTCondBold.35d3f580.otf'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at PDFFontFactory.open (/var/task/vercel/path0/node_modules/@foliojs-fork/pdfkit/js/pdfkit.js:3384:16)
    at PDFDocument.font (/var/task/vercel/path0/node_modules/@foliojs-fork/pdfkit/js/pdfkit.js:3454:33)
    at FontProvider.provideFont (/var/task/vercel/path0/node_modules/pdfmake/src/fontProvider.js:62:58)
    at /var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:326:27
    at Array.forEach (<anonymous>)
    at measure (/var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:298:13)
    at TextTools.buildInlines (/var/task/vercel/path0/node_modules/pdfmake/src/textTools.js:32:17)
    at DocMeasure.measureLeaf (/var/task/vercel/path0/node_modules/pdfmake/src/docMeasure.js:235:28) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './_app/immutable/assets/FuturaPTCondBold.35d3f580.otf'
}`

_Originally posted by @oxneat in https://github.com/sveltejs/kit/issues/10594#issuecomment-1688225029_

**Comment by s3812497** [comment] 2023-08-22 15:24
duplicate of https://github.com/sveltejs/kit/issues/10594

**Closed by s3812497** 2023-08-22 15:24 UTC
