### ISSUE TITLE
Canceled Response

### ISSUE THREAD

**Issue by razshare** [sveltejs/kit#11751] opened 2024-01-28 04:45 UTC
### Describe the bug

When dealing with streams or large amount of data in general, I need a way to detect when a client has disconnected, otherwise I'll be wasting I/O time on emitting data to a stream that nobody's ever going to read.

Here's an example

```js
export function GET() {
  const stream = new ReadableStream({
    async start(controller) {
      for (const chunk of someLargeAmountOfData) {
        controller.enqueue(chunk)
      }
      controller.close()
    }
  })

  return new Response(stream, {
    headers: {
      'Cache-Control': 'no-store',
      'Content-Type': 'application/octet-stream',
      'Connection': 'keep-alive',
    },
  })
}
```

That readable stream will continue to enqueue data until it's done, even if the client has aborted the connection (e.g. closed the tab).

From our side, in user-land, there's currently no way to detect when a client has disconnected, and it looks like the cancel event on the readable stream is also not triggered, so this also doesn't work:

```js
export function GET() {
  const stream = new ReadableStream({
    async start(controller) {
      for (const chunk of someLargeAmountOfData) {
        controller.enqueue(chunk)
      }
      controller.close()
    },
    cancel(){ // this doesn't work
      manageCancelation()
    }
  })
  
  return new Response(stream, {
    headers: {
      'Cache-Control': 'no-store',
      'Content-Type': 'application/octet-stream',
      'Connection': 'keep-alive',
    },
  })
}
```

### Reproduction

https://github.com/tncrazvan/sveltekit-canceled-response-issue-reproduction

- Run with `npm run dev`
- Open the website in your browser\
  At this point you should see a bunch of string chunks logging in your console, that means the website is downloading the data\
  Something like this\
  ![image](https://github.com/sveltejs/kit/assets/6891346/bcc33ce1-fac6-4382-b4a7-be7966759f14)

- Close the tab to abruptly cancel the connection
- Take a look back at your console, it's still emitting data to a closed connection because the `cancel` event did not trigger\
  The server should invoke `cancel` on the stream and trigger this part https://github.com/tncrazvan/sveltekit-canceled-response-issue-reproduction/blob/7bb48bf507273af48db78e7cbe4e5826de53cdc7/src/routes/test/%2Bserver.js#L39

### System Info

```Shell
System:
    OS: Linux 6.5 Zorin OS 17 17
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 27.18 GB / 31.23 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    bun: 1.0.25 - ~/.bun/bin/bun
```

### Severity

blocking an upgrade

### Additional Information

When the content of the response is indeed a ReadableStream and the client aborts the http connection, sveltekit should invoke the `cancel` method on the stream.

If you point me into the right direction, I'm happy to give it a shot a fixing this myself, I just need some general indications.

**Comment by t1u1** [comment] 2024-07-25 15:25
If `ReadableStream` is used for SSE, then this is even more problematic, because the stream never closes, as there is no way to know whether the client has disconnected. If for example, an implementation keeps enqueuing status data to the controller in a interval timer, there is no end to the timer nor the data!

**Comment by t1u1** [comment] 2024-07-25 15:44
Perhaps this will be useful for debugging:

The request object's signal is not aborted after closing the connection.

`console.log(request.signal.aborted)` always prints `false`.

**Comment by t1u1** [comment] 2024-07-26 06:54
I was able to pin down the issue in my case. I was using port forwarding from a container and accessing the SSE API through the forwarded port. In this case the client side closure doesn't trigger the closure on the server side.

However, if I `curl` from the remote host's shell to the server's local port, then closing the connection by killing `curl` works perfectly and the stream's `cancel` handler is called. So I guess the problem is somewhere in the port forwarding mechanism.

**Comment by razshare** [comment] 2024-10-06 09:22
A quick update, the `cancel` handler seems to trigger fine in NodeJs now.
The issue seems to be just with Bun now, see https://github.com/razshare/sveltekit-sse/issues/58#issuecomment-2395363406

**Comment by eltigerchino** [comment] 2024-10-29 03:29
I've tested this and it does indeed cancel after a few seconds of disconnection (refreshing the page, navigating away from the page, etc.). I'll close this issue for now

**Closed by eltigerchino** 2024-10-29 03:29 UTC
Labels: pkg:adapter-node
