### ISSUE TITLE
Changeable lib/server folder

### ISSUE THREAD

**Issue by AndreiSoroka** [sveltejs/kit#12021] opened 2024-03-22 22:41 UTC
### Describe the problem

1. https://kit.svelte.dev/docs/project-structure
1. https://github.com/sveltejs/kit/blob/main/packages/kit/src/exports/vite/graph_analysis/index.js#L37

During documentation and code, you can't change server folder

<img width="332" alt="image" src="https://github.com/sveltejs/kit/assets/6079139/255959af-b839-4733-8697-f20fcf24456f">

### Describe the proposed solution

Make a solution to provide configuration

For example, I want to change the folder to 
```
my-project/
├ src/
│ ├ lib/
│ │ └ [your lib files]
│ │    └ server/
│ │      └ [your server-only lib files]
```

Like each lib can have server folder

### Importance

would make my life easier

### Additional Information

I use FSD methodology with SvelteKit, and want to make `./sever` folder as a `segment`

At the moment Svelte is not friendly to FSD

FSD: https://feature-sliced.design/docs/get-started/overview

**Comment by AndreiSoroka** [comment] 2024-03-23 08:42
Workaround from discord:

https://kit.svelte.dev/docs/server-only-modules#your-modules

use `.server.ts` extension

**Comment by eltigerchino** [comment] 2024-11-20 07:49
closing as duplicate of https://github.com/sveltejs/kit/issues/12477

**Closed by eltigerchino** 2024-11-20 07:49 UTC
