### ISSUE TITLE
Cloudflare Pages' Deployment Failing

### ISSUE THREAD

**Issue by effen1337** [sveltejs/kit#6651] opened 2022-09-07 17:10 UTC
### Describe the bug

Hello, I decided to upgrade my project to latest and move it from CF Workers to CF Pages (with the help of functions). Locally, everything works just fine but when trying to have the project on Cf Pages, the build fails with this error:

```
16:23:13.985 | Cloning repository...

...


16:24:30.937 | ✓ 2231 modules transformed.
16:24:30.938 | [vite:load-fallback] Could not load /opt/buildhome/repo/src/lib/PageComponents/HomePage/ExamplesAutomod.svelte (imported by src/lib/PageComponents/HomePage/Features.svelte): ENOENT: no such file or directory, open '/opt/buildhome/repo/src/lib/PageComponents/HomePage/ExamplesAutomod.svelte'
16:24:30.938 | error during build:
16:24:30.938 | Error: Could not load /opt/buildhome/repo/src/lib/PageComponents/HomePage/ExamplesAutomod.svelte (imported by src/lib/PageComponents/HomePage/Features.svelte): ENOENT: no such file or directory, open '/opt/buildhome/repo/src/lib/PageComponents/HomePage/ExamplesAutomod.svelte'
16:24:31.001 | Failed: build command exited with code: 1
16:24:32.274 | Failed: an internal error occurred
```

`./lib/PageComponents/HomePage/Features.svelte` has:
```js
	import ExamplesAutomod from '$lib/PageComponents/HomePage/ExamplesAutomod.svelte';
```
and `ExamplesAutomod.svelte` is indeed in same directory `./lib/PageComponents/HomePage/ExamplesAutomod.svelte`

Same error happens if I use 
```js
	import ExamplesAutomod from './ExamplesAutomod.svelte';
```

Note: `./lib/PageComponents/HomePage/Features.svelte` is dynamically imported in `./routes/+page.svelte`

### Reproduction

https://github.com/effen1337/sk-cf-build-fail

i guess fork -> use in CF Pages -> watch the build fail

### Logs

```shell
..........
18:04:11.613	> vite build
18:04:11.613	
18:04:12.632	vite v3.1.0 building for production...
18:04:12.663	transforming...
18:04:15.402	
18:04:15.402	[35m🌼 daisyUI components 2.18.1[0m [0m https://github.com/saadeghi/daisyui
18:04:15.542	  [32m✔︎ Including:[0m [0m base, components, themes[8], utilities
18:04:15.542	  
18:04:18.350	✓ 461 modules transformed.
18:04:18.351	[vite:load-fallback] Could not load /opt/buildhome/repo/src/lib/PageComponents/HomePage/ExamplesAutomod.svelte (imported by src/lib/PageComponents/HomePage/Features.svelte): ENOENT: no such file or directory, open '/opt/buildhome/repo/src/lib/PageComponents/HomePage/ExamplesAutomod.svelte'
18:04:18.351	error during build:
18:04:18.351	Error: Could not load /opt/buildhome/repo/src/lib/PageComponents/HomePage/ExamplesAutomod.svelte (imported by src/lib/PageComponents/HomePage/Features.svelte): ENOENT: no such file or directory, open '/opt/buildhome/repo/src/lib/PageComponents/HomePage/ExamplesAutomod.svelte'
18:04:18.440	Failed: build command exited with code: 1
18:04:19.241	Failed: an internal error occurred
```

### System Info

```shell
Cloudflare Pages


Build command:
npm run build

Build output directory:
/.svelte-kit/cloudflare

Root directory:
/

Environment variables:
Variable name	Value
NODE_VERSION	16
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment] 2022-09-08 04:18
I can reproduce this locally just by running `npm run build` on the provided repository. I'm not sure what the issue is. My best guess would be an issue in `vite-plugin-svelte` or Vite

**Comment by Rich-Harris** [comment] 2022-09-20 15:40
I needed to make some changes to the repro to get it to build...

1. install `vite`
2. rename `src/hooks.js` to `src/hooks.server.js`
3. remove the reference to a non-existent `favicon.ico` in `src/app.html`

...but once I'd done so, it built just fine. It seems likely that the bug, whatever it was, was fixed since this issue was opened, so I'll close this.

If you're still experiencing the problem, please open a new issue, but make sure that you include a lockfile (`package-lock.json` in your case, since you're using `npm`). Without it it's hard to know whether the issue is with a specific version, or something more environment-specific. (Also, please remove extraneous stuff like Tailwind, and any files in `src` that aren't directly related to reproducing the issue!)

**Closed by Rich-Harris** 2022-09-20 15:40 UTC
Labels: bug, vite
