### ISSUE TITLE
Firebase SDK 9 won't build with `adapter-static`

### ISSUE THREAD

**Issue by jquesada2016** [sveltejs/kit#1962] opened 2021-07-19 22:29 UTC
### Describe the bug

When trying to use Firebase SDK 9, as per the recommendations on SvelteKit docs, the library initially will not work. One can make it work by adding `vite.ssr.external: ["firebase"]`. However, this only works for `dev`, and trying to run `npm run build` with `adapter` set to `adapter-static`, gives the error described in the `logs` section below.

### Reproduction

To reproduce:
1. Initialize SvelteKit:
```
npm init svelte@next firebase-app
```

2. Add firebase 9 SDK
```
npm i firebase@9.0.0-beta.6
```

3. In any page or component, try the following:
```javascript
import { initializeApp, getApps } from 'firebase/app';
import { onAuthStateChanged, getAuth, signOut, signInWithPopup, GoogleAuthProvider } from 'firebase/auth';
```

Just importing these functions should produce the error, though I'll continue just a bit.

```javascript
const firebaseConfig = /* config file */

const firebaseApp = initializeApp(firebaseConfig);

const auth = getAuth(firebaseApp);
signInWithPopup(auth, new GoogleAuthProvider());
```

4. Try in development...should work, unless I made a silly mistake somewhere above...;)
```
npm run dev
```

5. Try building, should fail.
```
npm run build
```

### Logs

```shell
> Using @sveltejs/adapter-static
> Named export 'GoogleAuthProvider' not found. The requested module 'firebase/auth' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'firebase/auth';
const { getAuth, signOut, signInWithPopup, GoogleAuthProvider, onAuthStateChanged } = pkg;

file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:3
import { getAuth, signOut, signInWithPopup, GoogleAuthProvider, onAuthStateChanged } from "firebase/auth";
                                            ^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'GoogleAuthProvider' not found. The requested module 'firebase/auth' is a CommonJS module, which may not support all module.exports as named exports.        
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'firebase/auth';
const { getAuth, signOut, signInWithPopup, GoogleAuthProvider, onAuthStateChanged } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async prerender (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/chunks/index6.js:80:14)
    at async Object.prerender (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/chunks/index6.js:312:5)
    at async adapt (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/adapter-static/index.js:17:4)
    at async adapt (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/chunks/index6.js:338:2)
    at async file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/cli.js:905:5
```

### Special Note
Trying to follow the advice proviced by the error message doesn't help either:

import * as app from 'firebase/app';
const { initializeApp, getApps } = app;
import * as authPkg from 'firebase/auth';
const { onAuthStateChanged, getAuth, signOut, signInWithPopup, GoogleAuthProvider } = authPkg;
```

Gives the following:
```
> Using @sveltejs/adapter-static
TypeError: getApps is not a function
    at file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:324:23      
    at Object.$$render (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:85:18)
    at file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:384:52      
    at Object.$$render (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:85:18)
    at file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:158:78      
    at $$render (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:85:18)
    at Object.render (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:93:20)
    at render_response (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/ssr.js:379:28)
    at async respond$1 (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/ssr.js:1187:10)
    at async render_page (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/ssr.js:1230:20)
TypeError: getApps is not a function
    at file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:324:23      
    at Object.$$render (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:85:18)
    at file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:384:52      
    at Object.$$render (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:85:18)
    at file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:158:78      
    at $$render (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:85:18)
    at Object.render (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/.svelte-kit/output/server/app.js:93:20)
    at render_response (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/ssr.js:379:28)
    at async respond_with_error (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/ssr.js:980:10)
    at async respond$1 (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/ssr.js:1199:10)
> 500 /
Error: 500 /
    at error (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/chunks/index6.js:94:11)
    at visit (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/chunks/index6.js:176:5)
    at async prerender (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/chunks/index6.js:245:5)
    at async Object.prerender (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/chunks/index6.js:312:5)
    at async adapt (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/adapter-static/index.js:17:4)
    at async adapt (file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/chunks/index6.js:338:2)
    at async file:///C:/Dev/Commercial/Importadora%20Queara/system/app-web-desktop/node_modules/@sveltejs/kit/dist/cli.js:905:5
```
```

### System Info

```shell
Using the latest version of everything:
- `SvelteKit: next`
- `svelte-adapter: 1.0.0-next.13`
- `node: v16.5.0`
- `npm: 7.19.1`
```

### Severity

blocking an upgrade

### Additional Information

Marked as `blocking an upgrade` because without being able to build, cannot test on deployments or other platforms.

**Comment by Conduitry** [comment] 2021-07-19 22:37
Duplicate of #1850.

**Closed by Conduitry** 2021-07-19 22:37 UTC

**Comment by jquesada2016** [comment] 2021-07-19 22:57
@Conduitry 
This is actually not the same issue. I didn't include the `@firebase/...` in the code above, but doing so still doesn;t solve the problem

**Comment by abdo643-HULK** [comment] 2021-07-22 08:35
> @Conduitry
> This is actually not the same issue. I didn't include the `@firebase/...` in the code above, but doing so still doesn;t solve the problem

Changing everything form "firebase/" to "@firebase/" should solve the problem because I am working with the same components and it did work for me like I mentioned in #1850

**Comment by jquesada2016** [comment] 2021-07-22 14:07
@abdo643-HULK 
It would be amazing if it did, but unfortunately it does not. Only one component is currently using firebase, and I'll attach the code below, unfortunately, I am not allowed to share the entire repo. I _did_, however, find a workaround, that did involve changing all the imports to `@firebase/...`, though, the exception was `auth`. What I had to do for `auth` to work, was as follows:

```javascript
import * as authPkg from '@firebase/auth'; // Gets around Firebase Vite issue

```

and then

```javascript
const { /* auth functions */ } = authPkg;
```

Once again, just in case, I am using `adaptor-static`, I don't know if other adapters would work differently in this case, and I am guessing yes, because I am able to `npm run dev` just fine, only when I `npm run build`, I have issues.

The full component code is below:

```javascript
// Backend.svelte

<script lang="ts">
	// Env
	import { dev, browser } from '$app/env';

	// Stores
	import { session } from '$app/stores';

	// Events
	import { createEventDispatcher } from 'svelte';

	// Firebase
	import { initializeApp, getApps } from '@firebase/app';
	import * as authPkg from '@firebase/auth'; // Gets around Firebase Vite issue
	import { useFirestoreEmulator, getFirestore } from '@firebase/firestore';
	import { firebaseConfig } from '$lib/firebaseConfig';
	import { getFunctions, useFunctionsEmulator } from '@firebase/functions';
	import { getStorage, useStorageEmulator } from '@firebase/storage';
	const {
		onAuthStateChanged,
		getAuth,
		signOut,
		signInWithPopup,
		signInWithEmailAndPassword,
		createUserWithEmailAndPassword,
		GoogleAuthProvider,
		useAuthEmulator,
		setPersistence,
		inMemoryPersistence
	} = authPkg;

	// Context
	import { setContext } from 'svelte';

	// Types
	import { FIREBASE_CTX_KEY, BACKEND_CTX_KEY } from '.';
	import type { BackendContext, Session } from '.';

	const firebaseApp = getApps()[0] ? getApps()[0] : initializeApp(firebaseConfig);

	// Get the SDK's
	const auth = getAuth(firebaseApp);
	const firestore = getFirestore(firebaseApp);
	const functions = getFunctions(firebaseApp);
	const storage = getStorage(firebaseApp);

	// Set up emulators
	dev && useEmulators();

	// Listen to user auth changes
	browser &&
		onAuthStateChanged(auth, (user) => {
			if (user) {
				const userSession = {} as Session;

				userSession.name = user.displayName;
				userSession.uid = user.uid;
				userSession.profilePicture = user.photoURL;

				$session.user = userSession;
			} else {
				$session.user = null;
			}
		});

	const cypress = browser && (window as any).Cypress ? true : false;

	const backendCtx: BackendContext = {
		signOut: () => signOut(auth),
		signIn: () => {
			signInWithPopup(auth, new GoogleAuthProvider());
		},
		cypress
	};

	setContext(FIREBASE_CTX_KEY, {});
	setContext(BACKEND_CTX_KEY, backendCtx);

	function useEmulators() {
		useAuthEmulator(auth, 'http://localhost:9099', { disableWarnings: true });
		useFirestoreEmulator(firestore, 'localhost', 8000);
		useFunctionsEmulator(functions, 'localhost', 5001);
		useStorageEmulator(storage, 'localhost', 9199);
	}

	async function signInCypress(email: string, password: string) {
		// Make sure persistence is set to NONE
		await setPersistence(auth, inMemoryPersistence);

		try {
			await signInWithEmailAndPassword(auth, email, password);
		} catch {
			await createUserWithEmailAndPassword(auth, email, password);
		}
	}

	if (cypress) {
		(window as any).signInCypress = signInCypress;
	}
</script>

<slot />

```

**Comment by abdo643-HULK** [comment] 2021-07-22 16:13
> @abdo643-HULK
> It would be amazing if it did, but unfortunately it does not. Only one component is currently using firebase, and I'll attach the code below, unfortunately, I am not allowed to share the entire repo. I _did_, however, find a workaround, that did involve changing all the imports to `@firebase/...`, though, the exception was `auth`. What I had to do for `auth` to work, was as follows:
> 
> ```js
> import * as authPkg from '@firebase/auth'; // Gets around Firebase Vite issue
> ```
> 
> and then
> 
> ```js
> const { /* auth functions */ } = authPkg;
> ```
> 
> Once again, just in case, I am using `adaptor-static`, I don't know if other adapters would work differently in this case, and I am guessing yes, because I am able to `npm run dev` just fine, only when I `npm run build`, I have issues.
> 
> The full component code is below:
> 
> ```js
> // Backend.svelte
> 
> <script lang="ts">
> 	// Env
> 	import { dev, browser } from '$app/env';
> 
> 	// Stores
> 	import { session } from '$app/stores';
> 
> 	// Events
> 	import { createEventDispatcher } from 'svelte';
> 
> 	// Firebase
> 	import { initializeApp, getApps } from '@firebase/app';
> 	import * as authPkg from '@firebase/auth'; // Gets around Firebase Vite issue
> 	import { useFirestoreEmulator, getFirestore } from '@firebase/firestore';
> 	import { firebaseConfig } from '$lib/firebaseConfig';
> 	import { getFunctions, useFunctionsEmulator } from '@firebase/functions';
> 	import { getStorage, useStorageEmulator } from '@firebase/storage';
> 	const {
> 		onAuthStateChanged,
> 		getAuth,
> 		signOut,
> 		signInWithPopup,
> 		signInWithEmailAndPassword,
> 		createUserWithEmailAndPassword,
> 		GoogleAuthProvider,
> 		useAuthEmulator,
> 		setPersistence,
> 		inMemoryPersistence
> 	} = authPkg;
> 
> 	// Context
> 	import { setContext } from 'svelte';
> 
> 	// Types
> 	import { FIREBASE_CTX_KEY, BACKEND_CTX_KEY } from '.';
> 	import type { BackendContext, Session } from '.';
> 
> 	const firebaseApp = getApps()[0] ? getApps()[0] : initializeApp(firebaseConfig);
> 
> 	// Get the SDK's
> 	const auth = getAuth(firebaseApp);
> 	const firestore = getFirestore(firebaseApp);
> 	const functions = getFunctions(firebaseApp);
> 	const storage = getStorage(firebaseApp);
> 
> 	// Set up emulators
> 	dev && useEmulators();
> 
> 	// Listen to user auth changes
> 	browser &&
> 		onAuthStateChanged(auth, (user) => {
> 			if (user) {
> 				const userSession = {} as Session;
> 
> 				userSession.name = user.displayName;
> 				userSession.uid = user.uid;
> 				userSession.profilePicture = user.photoURL;
> 
> 				$session.user = userSession;
> 			} else {
> 				$session.user = null;
> 			}
> 		});
> 
> 	const cypress = browser && (window as any).Cypress ? true : false;
> 
> 	const backendCtx: BackendContext = {
> 		signOut: () => signOut(auth),
> 		signIn: () => {
> 			signInWithPopup(auth, new GoogleAuthProvider());
> 		},
> 		cypress
> 	};
> 
> 	setContext(FIREBASE_CTX_KEY, {});
> 	setContext(BACKEND_CTX_KEY, backendCtx);
> 
> 	function useEmulators() {
> 		useAuthEmulator(auth, 'http://localhost:9099', { disableWarnings: true });
> 		useFirestoreEmulator(firestore, 'localhost', 8000);
> 		useFunctionsEmulator(functions, 'localhost', 5001);
> 		useStorageEmulator(storage, 'localhost', 9199);
> 	}
> 
> 	async function signInCypress(email: string, password: string) {
> 		// Make sure persistence is set to NONE
> 		await setPersistence(auth, inMemoryPersistence);
> 
> 		try {
> 			await signInWithEmailAndPassword(auth, email, password);
> 		} catch {
> 			await createUserWithEmailAndPassword(auth, email, password);
> 		}
> 	}
> 
> 	if (cypress) {
> 		(window as any).signInCypress = signInCypress;
> 	}
> </script>
> 
> <slot />
> ```

Here is the link to the project I am working on right now https://github.com/abdo643-HULK/LA-MEDITERRANEE

**Comment by DenomDev** [comment] 2021-10-10 23:21
Maybe it's cause of es2015 ? (Saw in your svelte.config.js
