### ISSUE TITLE
$page.url.hash not updating after navigating to the same page without hash

### ISSUE THREAD

**Issue by G2N** [sveltejs/kit#11046] opened 2023-11-15 16:09 UTC
### Describe the bug

I have a layout conditionnally showing a dialog depending on `$page.url.hash`.
Using `<a href="#dialog">` to show it and `<a href="/">`  to hide it works fine. The first time.

After navigating to `/#dialog`, followed by `/`, the next click on the `#dialog` link won't trigger a navigation and `$page.url.hash` isn't updated (unless i navigate to another page.

Adding another hash to the close dialog link (`<a href="#top">`) works fine, but it feels hacky :)

### Reproduction

[Reproduction on StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-5cum3w?file=src%2Froutes%2F%2Blayout.svelte)

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 1.14 GB / 15.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.18.2 - /usr/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 9.8.1 - /usr/bin/npm
    pnpm: 8.8.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 104.0.5112.101
    Chromium: 119.0.6045.123
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
    @sveltejs/kit: ^1.27.4 => 1.27.6 
    svelte: ^4.0.5 => 4.2.3 
    vite: ^4.4.2 => 4.5.0
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2023-11-15 17:07
closing as duplicate of https://github.com/sveltejs/kit/issues/10234

**Closed by eltigerchino** 2023-11-15 17:07 UTC
