### ISSUE TITLE
Filesystem-based hooks

### ISSUE THREAD

**Issue by moshe5745** [sveltejs/kit#11215] opened 2023-12-07 09:54 UTC
### Describe the problem

In the current situation if we use sequence helper function for hooks. We need to check the route in the beginning of every hook if we want them to apply only for specific routes. 

### Describe the proposed solution

Like all the parts of the framework that are filesystem-based for the route, maybe we can apply this to hooks too.

### Importance

would make my life easier

**Comment by DoubleMalt** [comment] 2023-12-07 10:12
I was about to suggest something similar.

My current idea is to implement a solution that uses hooks.server to call all `+server.ts` files along the path and execute the exported `middleware` methods with the `Request` object as parameter.

**Comment by Conduitry** [comment] 2023-12-07 11:08
Duplicate of #6731.

**Closed by Conduitry** 2023-12-07 11:08 UTC
