### ISSUE TITLE
.svelte files can import from $env/*/private

### ISSUE THREAD

**Issue by ssbm-oro** [sveltejs/kit#6001] opened 2022-08-17 20:50 UTC
### Describe the bug

I'm able to import private environment variables and expose them in client code. I made a repo but it's pretty simple to see it working with this +page.svelte:

```ts
<script lang="ts">
    import { PUBLIC_MY_NAME } from "$env/static/public";
    import { MY_LUGGAGE_COMBO } from "$env/static/private";
</script>

<h1>Welcome to SvelteKit</h1>
<p>My name is {PUBLIC_MY_NAME} and don't tell anyone {MY_LUGGAGE_COMBO}</p>
```

Trying to import `MY_LUGGAGE_COMBO` here should result in an error, right?

### Reproduction

https://github.com/ssbm-oro/svelte-private-env-vars

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 86.38 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    npm: 8.13.2 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 103.0.1
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.418 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.2
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment] 2022-08-17 20:51
Duplicate of #6000.

**Closed by Conduitry** 2022-08-17 20:51 UTC
