### ISSUE TITLE
Error: Dynamic require of "crypto" is not supported

### ISSUE THREAD

**Issue by CoolOppo** [sveltejs/kit#4367] opened 2022-03-17 03:07 UTC
### Describe the bug

I'm getting this error on my Cloudflare Pages site but can't reproduce locally. I am feeding in 'esnext' to the adapter because I have to for anything to compile. Might be part of the problem, idk, but if that's the cause then I have another question: why am I not supposed to use ECMA from the last 2 years? ;)

from my svelte config:
```ts
adapter: adapter({
			target: "esnext",
			minify: false,
			logLevel: "error",
		})
```

I believe it's caused by this line:
https://github.com/sveltejs/kit/blob/827d1623d64a9886032c8bfc8e2315420d1599d0/packages/kit/src/runtime/server/page/csp.js#L24

### Reproduction

I am not trying to be a dick, I am very busy and don't have the time right now to reproduce. I've explained all steps necessary to reproduce; it's an extremely simple setup. Just want to report this bug. Sorry if that isn't allowed; I know you're all busy too.

### System Info

```shell
Cloudflare Workers node version 17.5.0
```

### Severity

blocking all usage of SvelteKit

**Comment by CoolOppo** [comment] 2022-03-17 03:09
Oh I think it may be caused by this line, just added a service worker so that may be it!

https://github.com/sveltejs/kit/blob/27a9888161b86bcc8418f87f93ed54959c631079/packages/kit/src/runtime/server/page/render.js#L276

**Comment by benmccann** [comment] 2022-03-17 03:11
Looks like this might get fixed when AWS gets off their asses to implement Node 16 support, so that we can drop Node 14

https://github.com/sveltejs/kit/blob/827d1623d64a9886032c8bfc8e2315420d1599d0/packages/kit/src/runtime/server/page/csp.js#L23

**Comment by CoolOppo** [comment] 2022-03-17 03:34
Just fixed it...using [this ESBuild plugin](https://github.com/sinnaj-r/esbuild-plugin-node-polyfills) in the meantime.

Instructions:

*svelte.config.js*
```js
import ESBuildNodePolyfillsPlugin from 'esbuild-plugin-node-polyfills'

// ...

adapter: adapter({
			target: "esnext",
			minify: true,
			logLevel: "error",
			plugins: [ESBuildNodePolyfillsPlugin]
		}),
```

**Comment by CoolOppo** [comment] 2022-03-17 03:35
This is a very ratchet way of doing this of course...iirc the changelog for adapter-cloudflare actually said that support for ESbuild options was removed, lol. But when you put in the options, they get in there. :p

**Comment by Rich-Harris** [comment] 2022-05-14 00:42
@bhvngt please create new issues rather than piggybacking on existing ones, unless it's exactly the same issue. Things are liable to get lost in the mix otherwise. I've opened #4915 which works around the issue you found by preventing esbuild trying to bundle Node's built-in `crypto` module.

@CoolOppo unfortunately since I can't reproduce this I have to close this issue. It's not at all clear why it would be happening (`crypto` should be available in the [worker environment](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/), so SvelteKit shouldn't be trying to dynamically import Node's `crypto` module), so there's no realistic chance of fixing it without a reproduction. Feel free to open a new issue if you're able to create a repro.

**Closed by Rich-Harris** 2022-05-14 00:42 UTC
Labels: pkg:adapter-cloudflare
