### ISSUE TITLE
files prefixed with + can not be found (404) on azure

### ISSUE THREAD

**Issue by stephane-vanraes** [sveltejs/kit#6156] opened 2022-08-22 08:46 UTC
### Describe the bug

Sveltekit build generates files with `+` in the name, these files cause a 404 when loaded.

works: _app/immutable/assets/AccessControl-892d59d4.css  
does not work: _app/immutable\assets\+page-adb28a0b.css

### Reproduction

demo app, deployed to azure would do

### System Info

```shell
Azure
@sveltejs/kit@1.0.0-next.428
@sveltejs/adapter-static@1.0.0-next.39
```

### Severity

blocking all usage of SvelteKit

### Additional Information

file structure on server
![image](https://user-images.githubusercontent.com/13446670/185879305-2352610c-0631-4d8a-8424-71ab16a6cb78.png)

loading stylesheets in browser
![image](https://user-images.githubusercontent.com/13446670/185879544-679f4124-b90f-4b1b-b705-c8d879391fc9.png)

**Comment by Conduitry** [comment] 2022-08-22 08:51
Duplicate of #5843.

**Closed by Conduitry** 2022-08-22 08:51 UTC
