### ISSUE TITLE
Circular dependencies cause `svelte-kit dev` to freeze

### ISSUE THREAD

**Issue by cibernox** [sveltejs/kit#992] opened 2021-04-13 07:40 UTC
I'm building a custom plugin to do some AST transforms on some files in sveltekit for i18n.
It seems to work fine when I run `npm run build` followed by `npm run start`, but when I run `npm run dev` (which runs `svelte-kit dev`) the app never loads and yet I see no errors, neither in the browser nor in the console, so it's hard to track what's not working.

To reproduce it, just clone https://github.com/cibernox/sveltekit-bug-with-plugin, checkout commit #9fcf85eecaa, install dependencies and run `npm run dev`. You can also run `npm run build && npm run start` for comparison, as that works fine.

Something might be failing during SSR but not being rescued nor logger properly.

I wish I could give stacktraces, but the error I'm reporting here is precisely the lack of logging and stacktraces to track whatever the bug in my code might be.

**Comment by cibernox** [comment] 2021-04-13 15:42
Update: I noticed that just importing anything from  'precompile-intl-runtime` is enough to make the server freeze

**Comment by benmccann** [comment] 2021-04-14 05:17
Can you reproduce this with https://github.com/sveltejs/vite-plugin-svelte/tree/main/packages/playground/vite-ssr ? I'm wonder if this is a SvelteKit or Vite issue

**Comment by ignatiusmb** [comment] 2021-04-14 10:39
This is _most likely_ Vite (or the plugin) problem with handling circular dependency. I encountered this too when creating a certain package. The problem is hard to debug because it doesn't log anything to the console, but I tried it with Sapper (using Rollup) and it prints out the `circular dependecy` problem.

It occurs when, say, `utils.js` imports from `helper.js` and `helper.js` also imports from `utils.js`. This creates the circular dependency of `utils -> helper -> utils`, even when the imports aren't used or used but not in the same functions.

Current workaround is to self-contain at least one of them, either `utils` or `helper` to not have any imports from each other.

**Comment by cibernox** [comment] 2021-04-14 15:00
@ignatiusmb I confirm this is happening in vite and it was indeed because there was a couple cycles between imports on a few files in the library I was importing. I was able to fix it (and break other stuff, but that's a different story 😄 ) by removing the cycles.

Still while my library is fixed, I think this should be fixed in sveltekit/vite so at least we get a warning about cyclic dependencies and we know what's going on.

**Comment by GrygrFlzr** [comment] 2021-04-14 15:06
Known vite issue from last month: vitejs/vite#2491

**Comment by benmccann** [comment] 2021-04-14 15:20
Closing in favor of the Vite issue. Thanks for the details about the issue @ignatiusmb and @GrygrFlzr

**Closed by benmccann** 2021-04-14 15:20 UTC
Labels: vite
