### ISSUE TITLE
ReferenceError: BASE_ENV is not defined

### ISSUE THREAD

**Issue by surajchhetry** [sveltejs/kit#3441] opened 2022-01-20 14:03 UTC
### Describe the bug

I did following 
`npm init svelte@next my-app
cd my-app
npm install
npm i -D @sveltejs/adapter-static@next
 
// svelte.config.js
import adapter from '@sveltejs/adapter-static';

export default {
	kit: {
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null,
			precompress: false
		})
	}
};
npm run build 
node build/index.js
`
Getting ReferenceError: BASE_ENV is not defined

### Reproduction

npm init svelte@next my-app
cd my-app
npm install
npm i -D @sveltejs/adapter-static@next
 
// svelte.config.js
import adapter from '@sveltejs/adapter-static';

export default {
	kit: {
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null,
			precompress: false
		})
	}
};
npm run build 
node build/index.js
`

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 167.69 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Edge: 97.0.1072.62
    Firefox: 96.0.1
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.13 
    @sveltejs/adapter-node: ^1.0.0-next.64 => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.234 
    svelte: ^3.44.0 => 3.46.2
```

### Severity

annoyance

**Comment by Conduitry** [comment] 2022-01-20 14:05
Duplicate of #3424, will be released shortly.

**Closed by Conduitry** 2022-01-20 14:05 UTC

**Comment by surajchhetry** [comment] 2022-01-20 14:10
Thank @Conduitry
