### ISSUE TITLE
Getting 404 error during "npm run build", but not "npm run dev" (simple static adapter website)

### ISSUE THREAD

**Issue by BobSchnatt** [sveltejs/kit#2962] opened 2021-12-01 21:09 UTC
### Describe the bug

After a recent npm update (which I'm assuming updated Svelte, but correct me if I'm wrong), I've started getting a 404 error when attempting to do a release build. It doesn't happen when I do a preview build (see attached image).

My site is a very simple static webpage (using adapter-static). No stub routing, no spaces in image filenames, etc.

<img width="810" alt="Screenshot 2021-12-01 154845" src="https://user-images.githubusercontent.com/33637106/144312020-d4b957f4-e5e3-400d-acac-2395e9e02c3f.png">

### Reproduction

See files I've attached here. Since this error occurs at build time (and not during website usage), I'm not sure how to respond to this.

My website is proprietary and thus not on Github.  I can send the full repository to a Svelte maintainer via ProtonMail if necessary. Please advise.

<img width="258" alt="tsconfig json" src="https://user-images.githubusercontent.com/33637106/144314055-93dc345e-a093-4126-9ac1-9066e9ef039c.png">

<img width="295" alt="svelte config js" src="https://user-images.githubusercontent.com/33637106/144314082-0569a4c7-466c-40c1-a016-55e5951de2a4.png">

<img width="190" alt="package json" src="https://user-images.githubusercontent.com/33637106/144314101-d792a283-5364-4fed-8dde-4f55765bff20.png">

<img width="260" alt="jsconfig json" src="https://user-images.githubusercontent.com/33637106/144314122-be45535b-dd7b-45ac-9c95-39112df6b877.png">

### Logs

```shell
I'm not sure what logs to include. If you need any, please advise. Thank you in advance for your help...
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 3.90 GB / 6.08 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.4.1 - ~/.nvs/node/16.4.1/x64/bin/node
    npm: 7.18.1 - ~/.nvs/node/16.4.1/x64/bin/npm
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.21
    @sveltejs/kit: next => 1.0.0-next.201
    svelte: ^3.34.0 => 3.44.2
```

### Severity

blocking an upgrade

**Comment by BobSchnatt** [comment] 2021-12-01 21:11
An addendum: I'm not using TypeScript, so the config file for that is unused (?)

**Comment by bluwy** [comment] 2021-12-04 08:54
There's not much info here for us to debug, please provide a repro on github or stackblitz. The repro should be minimal and created from scratch so proprietary shouldn't be an issue, it would also help narrow the cause too.

**Comment by BobSchnatt** [comment] 2021-12-04 23:28
Working on it...

**Comment by BobSchnatt** [comment] 2021-12-05 21:16
Ok, I built a demo test site which very closely mirrors my actual site. It has all the basic functionality: all the routes, the image gallery, the nav bar, the header and footer that appears on every page, the ability to make the footer disappear when you click on it, etc.  Page for page and feature for feature, it's the same website, just with my company stuff left out (and it uses smaller pages - fewer paragraphs and images).  And I can use "npm run build" without error.

The only way I can help you resolve this is to send you both my test site repository (zipped up) and my official repository so you can compare. So, my question is: what non-identifying files & folders can I send you from my official repository that you can use to do this comparison?

Clearly, something changed and/or got corrupted at some point in my official build setup.  I'm way too dumb to be able to figure that out, so you're gonna have to do it for me!  In the meantime, I'm gonna make a copy of the demo site folder and copy my REAL files into it and see if I can resolve the problem on my end that way.

Thanks

**Comment by BobSchnatt** [comment] 2021-12-06 00:02
One thing I've found is my site builds fine when I use adapter-auto, but not adapter-static. Pulling my hair out...

**Comment by BobSchnatt** [comment] 2021-12-06 00:46
Ok, I was able to finally reproduce the problem. When I changed the demo site's adapter to adapter-static, the problem reared it's head. Included below. (I omitted the node_modules directory, but kept everything else.) Let me know if you need anything else. Than
[DemoSite.zip](https://github.com/sveltejs/kit/files/7657158/DemoSite.zip)
ks

**Comment by nikitaiavdeev** [comment] 2021-12-06 18:04
I had the identical issue. I found that it's happening when routing folder doesn't have index.svelte. You could fix your error by creating /Support/FAQ/index.svelte.

**Comment by BobSchnatt** [comment] 2021-12-06 18:08
Thanks, but I have other routes that work (or, at least, used to work) without index.svelte. My website ran fine for several months, and then builds stopped working for some reason, even though I only make cosmetic changes for the most part.  Is index.svelte now a requirement?

**Comment by bluwy** [comment] 2021-12-06 18:16
The `index.svelte` file shouldn't be necessary, but I don't remember anything that would cause that behaviour. I'll take a deeper look at this tomorrow, but since you've mentioned that this only happen after an update in sveltekit/static, you can also try downgrading them and see which version breaks it. The changelog may help with it too.

**Comment by nikitaiavdeev** [comment] 2021-12-06 18:23
> e `index.svelte` file shouldn't be necessary, but I don't remember anything that would cause that behaviour. I'll take a deeper look at this tomorrow, but since you've mentioned that this only happen after an update in sveltekit/static, you can also try downgrading them and see which version breaks it. The changelog may help with it too.

Yes, my project worked fine without index.svelte before as well. Unfortunately, I haven't noticed from what sveltekit version it happened.

**Comment by BobSchnatt** [comment] 2021-12-06 18:45
Ok, I downgraded SvelteKit to "1.0.0-next.195" and that fixed the problem, so I started incrementing upwards, and the problem reappeared in "1.0.0-next.200", so the "200" update broke something (or exposed a flaw in my website)...

**Comment by bluwy** [comment] 2021-12-08 09:52
Sorry, got a lot busy recently, but thanks for tracking this down! That means something in v200 failed, which is likely #2832. If someone wants to help out, feel free to debug that PR.

**Comment by joenano** [comment] 2021-12-09 07:04
The path to static files in release build with adapter-static has been an unresolved issue for at least 50 versions it seems.

**Comment by daevid66** [comment] 2021-12-14 22:41
I also got problems after  #2832, in my case it is a combination of the following:
- my static site is not hosted the root of my domain, let's say it in `www.domain.com/test`. I have added `/test` as base path and page/asset paths in svelte-config.
- I have a 302 redirect that need to point to `/test/page1`
- After updating svelte-kit (including #2832) the build process tries to crawl the redirected url (`/test/page1`), but it cannot find it, since it's actually positioned at `/page1` during the build process.

I added a work-around, by adding an extra empty route at `/test/page1`, which 'works' but it would be preferable if either:
1. Svelte-kit accounts for base path when crawling redirects.
2. You can somehow flag that you don't want to crawl your redirects.

**Comment by pavelloz** [comment] 2022-01-05 17:44
I think this issue proves something I've been struggling with in my short sveltekit journey - error messages are not pointing where to look for issue, a lot of the times.

**Comment by mhkeller** [comment] 2022-01-17 02:21
Same here. I downgraded to `"@sveltejs/kit": "1.0.0-next.200"` and also `"@sveltejs/adapter-static": "1.0.0-next.22"` and exports started working properly again. 

I made a repro on [this branch](https://github.com/mhkeller/layercake/tree/no-exports). `npm run build` completes without an error but it fails to build three routes. In the `docs` folder there should be an `examples` folder containing three pages: Line, CirclePackNested and SyncedBrush. Instead there is no `examples` folder.

**Comment by gkankanh** [comment] 2022-03-13 01:59
I get the same error too on any image links.
svelte-kit/output/server/manifest.json                       1.26 KiB
.svelte-kit/output/server/index.js                            64.88 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js    24.62 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js   0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js       8.06 KiB
.svelte-kit/output/server/entries/pages/about.svelte.js       1.30 KiB
.svelte-kit/output/server/chunks/index-d82f9bb9.js            6.71 KiB
> **_404 /src/content/images/home/Cloud.svg (linked from /)_**
    at file:///D:/gopal/projects/svcrrs/node_modules/@sveltejs/kit/dist/chunks/index2.js:975:11
    at save (file:///D:/gopal/projects/svcrrs/node_modules/@sveltejs/kit/dist/chunks/index2.js:1194:4)
    at visit (file:///D:/gopal/projects/svcrrs/node_modules/@sveltejs/kit/dist/chunks/index2.js:1085:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by raphet** [comment] 2022-04-03 15:37
I am also impacted by this error with same resolution: downgrading to "@sveltejs/kit": "1.0.0-next.199" resolves the issue. The issue was definitely introduced by https://github.com/sveltejs/kit/pull/2832 and is reproduced in conjunction with using adapter-static.
As others stated there is no issue with npm run dev. 
But the build process failes during `npm run build` with a 404 error, in my case > 404 /blog (linked from /blog/my-first-article). That site has no index but it also doesn't need to have any. Worse yet: It's not even linked from within the article. So the error is actually misleading.

**Comment by Rich-Harris** [comment] 2022-04-28 19:18
Both repros work correctly with the current version of SvelteKit, so whatever the bug was we can regard it as fixed — closing

**Closed by Rich-Harris** 2022-04-28 19:18 UTC
Labels: help wanted, pkg:adapter-static, p3-edge-case

**Comment by quintesse** [comment] 2022-06-13 11:04
I have a brand new repo that shows this problem as well: https://github.com/quintesse/comix-sense
It's the SvelteKit demo app where the only changes that have been made are configuring it with the static adapter.
You can see the error in the GH Action log: https://github.com/quintesse/comix-sense/runs/6859572148
Am I doing something wrong?

**Comment by Eric-ASCE** [comment] 2022-11-16 06:05
I had the same error and I found the error, is simple when you run "npm run build" as static it start to compile the project and svelte verify all routes used as local routes, as you are using "/support/FAQ/..." in some href, svelte is trying to find this route but it is not defined in your project may be because a typo or you just wrote any route to fill the atribute when testing

**Comment by maximeoger** [comment] 2023-03-18 10:53
Hello, i know that this issue have been closed already, but i would like to share a similar problem i had with my project using static-adapter on @sveltejs/kit: ^1.11.0 

When i build the project in my local computer, the files are generated correctly and the build works fine. But i get the same error on my github actions CI. 
[Here the link of the failing job](https://github.com/maximeoger/portfolio_2023/actions/runs/4437285939/jobs/7786777261)
 [and my project repository](https://github.com/maximeoger/portfolio_2023)

The problem is about a 404 error on the "/" path. And i can't have more ideas about how this could fail on CI...

Thanks in advance for any help. 

regards

**Comment by P00HB33R** [comment] 2023-10-12 07:25
Adding the following in the head of my app.html fixed the error for me:
`<base href="/" />`

**Comment by faelisrex** [comment] 2024-01-01 21:31
im having this problem too. svg files load in npm run dev but not during build. im using `"@sveltejs/adapter-auto": "^3.0.0"` and ` "@sveltejs/kit": "^2.0.0"` ill likely not want to downgrade as far back as 1.11.0

**Comment by bradphelan** [comment] 2025-01-06 20:46
Same here.

http://localhost:5173/blog/first-post

works when in dev mode but during build

```

node:internal/event_target:1101
  process.nextTick(() => { throw err; });
                           ^
Error: 404 /blog/first-post (linked from /blog)
To suppress or handle this error, implement `handleHttpError` in https://svelte.dev/docs/kit/configuration#prerender
    at file:///C:/Users/brad/code/existanz/node_modules/@sveltejs/kit/src/core/config/options.js:204:13
    at file:///C:/Users/brad/code/existanz/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:73:25
    at save (file:///C:/Users/brad/code/existanz/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:439:4)
    at visit (file:///C:/Users/brad/code/existanz/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:261:3)

Node.js v22.12.0
```
