### ISSUE TITLE
`Goto` not working

### ISSUE THREAD

**Issue by migbash** [sveltejs/kit#6663] opened 2022-09-08 06:49 UTC
### Describe the bug

When working in `dev` everything is working fine with no errors. But when deploying to `prod` `(npm start / preivew)` the applciation crashes.

I thought it was a third-party dependency `npm package` but upon removing pages and components, I noticed it pointed to `import { goto } from '$app/navigation';` 

Once removing it from the `imports` it fixed the issue and the app loaded normally.

---

Error with `import { goto } from '$app/navigation';`

```
Uncaught TypeError: Cannot read properties of undefined (reading 'disable_scroll_handling')
```

### Reproduction

1. `npm create svelte@latest my-app`
2.
```
√ Which Svelte app template? » Skeleton project
√ Add type checking with TypeScript? » Yes, using TypeScript syntax
√ Add ESLint for code linting? ... No / [x] Yes
√ Add Prettier for code formatting? ... No / [x] Yes
√ Add Playwright for browser testing? ... No / [x] Yes
```

3. navigate into the **my-app** directory
4. install `vite-plugin-chunk-split` from: `npm i vite-plugin-chunk-split`

5. update the `vite.config.js` to:
```
import { sveltekit } from '@sveltejs/kit/vite';
import { chunkSplitPlugin } from 'vite-plugin-chunk-split'; // https://github.com/sanyuan0704/vite-plugin-chunk-split

/** @type {import('vite').UserConfig} */
const config = {
  plugins: [
    chunkSplitPlugin(),
    sveltekit()
  ]
};

export default config;
```

6. Then, do `npm run build` & `npm run preview` and check the `devTool` console. You should see no errors.
7. **Then** add: `import { goto } from '$app/navigation';` in the `+page.svelte` & re-run `npm run build` & `npm run preview`. You will then see the following error:

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'disable_scroll_handling')
```

---

# Repository with Error Explanation:

https://github.com/migbash/sveltekit-error

---

### Logs

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'disable_scroll_handling')
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 2.18 GB / 15.90 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.19041.1566
```

### Severity

annoyance

**Comment by dummdidumm** [comment] 2022-09-08 11:54
Please provide a minimum reproducible code repo, else we don't know how to reproduce this

**Comment by migbash** [comment] 2022-09-08 18:11
@dummdidumm not entirely directly a `svelte` / `wveltekit` issue.

Culprit identified with the use of `vite-plugin-chunk-split` for `npm run build` **explicitly** when making use of `import { goto } from '$app/navigation';` anywhere in the project inside `src/`

When `import { goto } from '$app/navigation';` is not used together with `vite-plugin-chunk-split` , it runs perfectly.

Otherwise, you get an `reading 'disable_scroll_handling'` error.

**Comment by Conduitry** [comment] 2022-09-08 18:21
You need to provide a repo that can be cloned. As it says in the issue template for bug reports:

> Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by migbash** [comment] 2022-09-08 18:45
@Conduitry here: https://github.com/migbash/sveltekit-error

**Comment by fcrozatier** [comment] 2022-09-11 09:05
I confirm I have the same error message since a few days (in dev also) 

> Uncaught TypeError: Cannot read properties of undefined (reading 'disable_scroll_handling')
    at navigation.js?v=ea1b0f2a:16:11

I don't have `vite-plugin-chunk-split` installed and tried to remove the `goto` calls as suggested but to no avail. I have not managed to make a minimal repro yet.

**Comment by fcrozatier** [comment] 2022-09-11 15:27
In the end it had something to do with an import it didn't like in `hooks.client.ts`. Redeclaring the thing in place fixed it.
I tried to replicate the behavior in a minimal way but couldn't, it was all fine 🤷‍♂️

**Comment by dummdidumm** [comment] 2022-09-14 09:41
The OP's error sounds like an issue with `vite-plugin-chunk-split`. It seems like `vite-plugin-chunk-split` does split at the wrong boundaries, breaking the singletons. From reading the README it sounds like you can customize the split behavior, but I don't know enough about it to tell how to configure it that it leaves SvelteKit things "alone"/bundles them as one.

I don't think there's much we can do here, so closing this.

**Closed by dummdidumm** 2022-09-14 09:41 UTC
Labels: awaiting submitter
