### ISSUE TITLE
Error trying to serialize Date or ObjectID

### ISSUE THREAD

**Issue by developedbyant** [sveltejs/kit#6210] opened 2022-08-23 21:39 UTC
### Describe the bug

Here is the input data from database using MongoDB
`{
  "_id":24323e2efwefw"
  "createdAt": {
      "$date": {
        "$numberLong": "1661208882758"
      }
    }
}`

Here is the error from SvelteKit
`data.assets[0].createdAt returned from 'load' in src/routes/admin/assets/+page.server.ts cannot be serialized as JSON`

### Reproduction

n/a

### System Info

```shell
macbook
```

### Severity

blocking all usage of SvelteKit

### Additional Information

thanks

**Comment by Conduitry** [comment] 2022-08-23 21:52
Duplicate of #6093. This is the intended behavior, currently. There is #6008 for supporting non-JSON responses.

**Closed by Conduitry** 2022-08-23 21:52 UTC
