### ISSUE TITLE
Can't SvelteKit app on Vercel

### ISSUE THREAD

**Issue by Sammy-Nyakabau** [sveltejs/kit#4755] opened 2022-04-26 21:15 UTC
### Describe the bug

Tried deploying on Vercel but the build part is failing because of output directory. 
Vercel is expecting `public` to be the output directory.

### Reproduction

Unfortunately I can't provide a link to the repo since it is a private project

### Logs

```shell
[02:37:12.273] Cloning github.com/Freelance-Gigs/college-finder-app (Branch: develop, Commit: c903ffe)
[02:37:12.865] Cloning completed: 591.79ms
[02:37:12.964] Installing build runtime...
[02:37:14.798] Build runtime installed: 1.834s
[02:37:15.941] No Build Cache available
[02:37:16.086] Detected package.json
[02:37:16.086] Installing dependencies...
[02:37:16.088] Detected `package-lock.json` generated by npm 7...
[02:37:22.433] 
[02:37:22.433] > college-finder-app@1.0.0 prepare
[02:37:22.433] > svelte-kit sync
[02:37:22.433] 
[02:37:22.577] 
[02:37:22.578] added 237 packages in 6s
[02:37:22.578] 
[02:37:22.578] 39 packages are looking for funding
[02:37:22.578]   run `npm fund` for details
[02:37:22.785] Detected `package-lock.json` generated by npm 7...
[02:37:22.785] Running "npm run build"
[02:37:23.065] 
[02:37:23.065] > college-finder-app@1.0.0 build
[02:37:23.065] > svelte-kit build
[02:37:23.065] 
[02:37:23.384] [36mvite v2.9.6 [32mbuilding for production...[36m[39m
[02:37:23.486] transforming...
[02:37:29.268] [32m✓[39m 208 modules transformed.
[02:37:29.445] rendering chunks...
[02:37:29.590] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[32mmanifest.json                                       [39m [2m2.11 KiB[22m
[02:37:29.591] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mpages/__layout.svelte-4032d3ea.js                   [39m [2m2.39 KiB / gzip: 1.16 KiB[22m
[02:37:29.594] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36merror.svelte-efb7648d.js                            [39m [2m1.56 KiB / gzip: 0.75 KiB[22m
[02:37:29.595] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mpages/index.svelte-afc64a48.js                      [39m [2m9.18 KiB / gzip: 3.37 KiB[22m
[02:37:29.595] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mchunks/index-e09e217c.js                            [39m [2m0.80 KiB / gzip: 0.49 KiB[22m
[02:37:29.595] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mchunks/singletons-d1fb5791.js                       [39m [2m0.05 KiB / gzip: 0.07 KiB[22m
[02:37:29.595] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mstart-54dcabb1.js                                   [39m [2m23.25 KiB / gzip: 8.65 KiB[22m
[02:37:29.595] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mchunks/navigation-73ae68f0.js                       [39m [2m1.06 KiB / gzip: 0.69 KiB[22m
[02:37:29.595] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mchunks/index-087532fe.js                            [39m [2m12.40 KiB / gzip: 5.06 KiB[22m
[02:37:29.596] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[35massets/pages/find-college/_id_.svelte-f29ff347.css  [39m [2m45.33 KiB / gzip: 6.79 KiB[22m
[02:37:29.596] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[35massets/pages/__layout.svelte-251776ad.css           [39m [2m12.23 KiB / gzip: 3.35 KiB[22m
[02:37:29.601] [90m[37m[2m.svelte-kit/output/client/_app/[22m[90m[39m[36mpages/find-college/_id_.svelte-15bce451.js          [39m [2m252.70 KiB / gzip: 83.33 KiB[22m
[02:37:29.612] [36mvite v2.9.6 [32mbuilding SSR bundle for production...[36m[39m
[02:37:29.745] transforming...
[02:37:30.017] [32m✓[39m 14 modules transformed.
[02:37:30.018] [31m[rollup-plugin-dynamic-import-variables] Argument name clash (79:132)[39m
[02:37:30.018] file: [36m/vercel/path0/src/components/ProfileInformation.svelte:79:132[39m
[02:37:30.020] (node:442) UnhandledPromiseRejectionWarning: SyntaxError: Argument name clash (79:132)
[02:37:30.021]     at Parser.pp$4.raise (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:19680:13)
[02:37:30.021]     at Parser.pp$7.checkLValSimple (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:18353:18)
[02:37:30.021]     at Parser.pp$7.checkLValPattern (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:18398:10)
[02:37:30.021]     at Parser.pp$7.checkLValInnerPattern (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:18420:10)
[02:37:30.021]     at Parser.pp$5.checkParams (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:19533:10)
[02:37:30.021]     at Parser.pp$5.parseFunctionBody (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:19503:10)
[02:37:30.021]     at Parser.pp$5.parseArrowExpression (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:19467:8)
[02:37:30.021]     at Parser.pp$5.parseParenArrowList (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:19196:15)
[02:37:30.021]     at Parser.pp$5.parseParenAndDistinguishExpression (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:19162:19)
[02:37:30.021]     at Parser.pp$5.parseExprAtom (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:19014:41)
[02:37:30.021] (Use `node --trace-warnings ...` to show where the warning was created)
[02:37:30.022] (node:442) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[02:37:30.022] (node:442) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[02:37:30.695] Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) x64 Apple M1
    Memory: 38.69 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.39 
    @sveltejs/kit: next => 1.0.0-next.322 
    svelte: ^3.47.0 => 3.47.0
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment] 2022-04-26 21:41
We can't properly diagnose anything with a reproduction. It doesn't matter whether you can share the project you are having this issue with, because you should be providing a minimal, stripped-down reproduction anyway.

From the error message, it looks like there is some bad interaction between `rollup-plugin-dynamic-import-variables` and the contents of your `src/components/ProfileInformation.svelte` file.

**Comment by Conduitry** [comment] 2022-04-30 21:36
Closing due to lack of proper reproduction.

**Comment by frontycore** [comment] 2022-06-30 03:47
Hi, I have similar issue with Svelte Kit and Vercel. I migrated my app from Sapper to Svelte Kit, but now I am not able to publish it on Vercel, because the public directory is not created.
I tried to set public dir to `.svelte-kit`, in this case build ends successfully, but there is "Not found" error.
Then I tried to set `.svelte-kit/build` to public dir, deployed successfully, but there was raw JS code shown on production URL.
I also tried to set Vercel adapter rather than Auto, the result was the same. Lastly I cloned the default SvelteKit project with Vercel template to https://sveltekit-git-main-ondrej2.vercel.app/ and compare it's Vercel settings and svelte config, both are the same as in my project.
Both Dev and Preview mode works fine on localhost. 
Attaching build report.

What do I do wrong? Thanks for any advice or clue!


Cloning bitbucket.org/ondrejseliga/kvitkova-frontend (Branch: master, Commit: a43289c)
--
05:19:15.806 | Cloning completed: 1.620s
05:19:16.760 | Looking up build cache...
05:19:18.158 | Build cache downloaded [19.82 MB]: 1062.339ms
05:19:18.406 | Running "vercel build"
05:19:18.881 | Vercel CLI 25.2.2 build (beta) — https://vercel.com/feedback
05:19:18.964 | > Loaded env from ".env"
05:19:19.101 | Installing dependencies...
05:19:20.280 |  
05:19:20.280 | up to date in 985ms
05:19:20.281 |  
05:19:20.281 | 65 packages are looking for funding
05:19:20.281 | run `npm fund` for details
05:19:20.521 | Detected `package-lock.json` generated by npm 7...
05:19:20.521 | Running "npm run build"
05:19:20.816 |  
05:19:20.816 | > sveltheme-frontend@0.0.1 build
05:19:20.816 | > svelte-kit build
05:19:20.816 |  
05:19:21.519 | vite v2.9.13 building for production...
05:19:21.620 | transforming...
05:19:26.681 | ✓ 121 modules transformed.
05:19:26.853 | rendering chunks...
05:19:26.955 | Client build completed. Wrote 32 chunks and 13 assets
05:19:26.956 | Building server
05:19:26.967 | .svelte-kit/output/client/_app/immutable/manifest.json                                      9.28 KiB
05:19:26.974 | .svelte-kit/output/client/_app/immutable/pages/__error.svelte-e37688ae.js                   1.51 KiB / gzip: 0.85 KiB
05:19:26.974 | .svelte-kit/output/client/_app/immutable/pages/byty/index.svelte-528d80c7.js                12.15 KiB / gzip: 4.53 KiB
05:19:26.974 | .svelte-kit/output/client/_app/immutable/start-720e9f66.js                                  26.00 KiB / gzip: 8.98 KiB
05:19:26.974 | .svelte-kit/output/client/_app/immutable/pages/byty/_slug_.svelte-a944859e.js               15.50 KiB / gzip: 4.75 KiB
05:19:26.975 | .svelte-kit/output/client/_app/immutable/pages/_slug_.svelte-b00128e7.js                    2.41 KiB / gzip: 1.18 KiB
05:19:26.975 | .svelte-kit/output/client/_app/immutable/pages/patra/index.svelte-b6ef8fdf.js               0.22 KiB / gzip: 0.19 KiB
05:19:26.975 | .svelte-kit/output/client/_app/immutable/pages/hledat/_search_.svelte-9d5ea335.js           9.12 KiB / gzip: 3.41 KiB
05:19:26.975 | .svelte-kit/output/client/_app/immutable/pages/tirata_admin.svelte-86c49d89.js              0.25 KiB / gzip: 0.21 KiB
05:19:26.975 | .svelte-kit/output/client/_app/immutable/pages/patra/_slug_.svelte-a9abbd88.js              2.91 KiB / gzip: 1.34 KiB
05:19:26.975 | .svelte-kit/output/client/_app/immutable/chunks/preload-helper-37d74a8a.js                  1.34 KiB / gzip: 0.81 KiB
05:19:26.976 | .svelte-kit/output/client/_app/immutable/chunks/singletons-d1fb5791.js                      0.05 KiB / gzip: 0.07 KiB
05:19:26.976 | .svelte-kit/output/client/_app/immutable/chunks/Link-c28b6159.js                            1.36 KiB / gzip: 0.80 KiB
05:19:26.976 | .svelte-kit/output/client/_app/immutable/pages/__layout.svelte-3a1e64c8.js                  25.22 KiB / gzip: 9.33 KiB
05:19:26.976 | .svelte-kit/output/client/_app/immutable/chunks/navigation-fe373893.js                      0.19 KiB / gzip: 0.16 KiB
05:19:26.976 | .svelte-kit/output/client/_app/immutable/pages/index.svelte-a7905201.js                     24.70 KiB / gzip: 7.36 KiB
05:19:26.976 | .svelte-kit/output/client/_app/immutable/chunks/html-3a706857.js                            14.49 KiB / gzip: 5.25 KiB
05:19:26.978 | .svelte-kit/output/client/_app/immutable/chunks/Head-bb57bc87.js                            4.92 KiB / gzip: 1.91 KiB
05:19:26.978 | .svelte-kit/output/client/_app/immutable/chunks/api-97e42fa3.js                             0.34 KiB / gzip: 0.27 KiB
05:19:26.978 | .svelte-kit/output/client/_app/immutable/chunks/Content-4ecae4a6.js                         1.51 KiB / gzip: 0.89 KiB
05:19:26.978 | .svelte-kit/output/client/_app/immutable/chunks/index-5fcc941d.js                           13.77 KiB / gzip: 5.69 KiB
05:19:26.978 | .svelte-kit/output/client/_app/immutable/chunks/PageHeader-f9df1552.js                      1.75 KiB / gzip: 0.93 KiB
05:19:26.979 | .svelte-kit/output/client/_app/immutable/chunks/index-41cb2848.js                           0.21 KiB / gzip: 0.18 KiB
05:19:26.981 | .svelte-kit/output/client/_app/immutable/chunks/ContactForm-d071d62f.js                     8.54 KiB / gzip: 3.20 KiB
05:19:26.981 | .svelte-kit/output/client/_app/immutable/chunks/Image-10ee6886.js                           3.08 KiB / gzip: 1.52 KiB
05:19:26.981 | .svelte-kit/output/client/_app/immutable/chunks/msg-8e250072.js                             0.63 KiB / gzip: 0.38 KiB
05:19:26.981 | .svelte-kit/output/client/_app/immutable/chunks/search-52439ac6.js                          0.12 KiB / gzip: 0.11 KiB
05:19:26.981 | .svelte-kit/output/client/_app/immutable/chunks/appartment-3cbab68c.js                      1.23 KiB / gzip: 0.65 KiB
05:19:26.981 | .svelte-kit/output/client/_app/immutable/chunks/form-7160d3e5.js                            0.50 KiB / gzip: 0.34 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/chunks/StoreyTable-dddd304a.js                     13.87 KiB / gzip: 4.55 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/Content-a453a534.css                        3.97 KiB / gzip: 1.02 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/PageHeader-30a9babd.css                     0.79 KiB / gzip: 0.36 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/pages/byty/_slug_.svelte-3d7d7816.css       0.71 KiB / gzip: 0.25 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/ContactForm-1744c588.css                    1.58 KiB / gzip: 0.59 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/pages/byty/index.svelte-9c977832.css        1.40 KiB / gzip: 0.51 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/StoreyTable-43c8d0c5.css                    2.32 KiB / gzip: 0.66 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/pages/hledat/_search_.svelte-cd9417a4.css   0.34 KiB / gzip: 0.21 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/pages/patra/_slug_.svelte-e7f619b3.css      0.08 KiB / gzip: 0.09 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/StoreyPlan-0cc44fde.css                     1.63 KiB / gzip: 0.29 KiB
05:19:26.982 | .svelte-kit/output/client/_app/immutable/assets/pages/index.svelte-98ac8067.css             8.64 KiB / gzip: 2.10 KiB
05:19:26.983 | .svelte-kit/output/client/_app/immutable/chunks/glightbox.min-5144f092.js                   40.16 KiB / gzip: 11.79 KiB
05:19:26.983 | .svelte-kit/output/client/_app/immutable/assets/pages/__layout.svelte-d8eb1f57.css          54.10 KiB / gzip: 9.51 KiB
05:19:26.983 | .svelte-kit/output/client/_app/immutable/assets/guttenberg-cb1d187c.css                     53.80 KiB / gzip: 8.15 KiB
05:19:26.983 | .svelte-kit/output/client/_app/immutable/chunks/splide.esm-99cdbe39.js                      39.32 KiB / gzip: 16.12 KiB
05:19:26.996 | .svelte-kit/output/client/_app/immutable/chunks/StoreyPlan-1b145892.js                      244.20 KiB / gzip: 37.81 KiB
05:19:27.003 | vite v2.9.13 building SSR bundle for production...
05:19:27.184 | transforming...
05:19:29.062 | ✓ 117 modules transformed.
05:19:29.102 | Generated an empty chunk: "hooks"
05:19:29.115 | rendering chunks...
05:19:29.163 | .svelte-kit/output/server/manifest.json                             7.47 KiB
05:19:29.164 | .svelte-kit/output/server/index.js                                  73.58 KiB
05:19:29.164 | .svelte-kit/output/server/entries/endpoints/sitemap.xml.js          0.90 KiB
05:19:29.164 | .svelte-kit/output/server/entries/pages/__layout.svelte.js          127.12 KiB
05:19:29.164 | .svelte-kit/output/server/entries/pages/__error.svelte.js           0.98 KiB
05:19:29.165 | .svelte-kit/output/server/entries/pages/_slug_.svelte.js            1.69 KiB
05:19:29.165 | .svelte-kit/output/server/entries/pages/byty/_slug_.svelte.js       8.83 KiB
05:19:29.165 | .svelte-kit/output/server/entries/pages/byty/index.svelte.js        9.13 KiB
05:19:29.165 | .svelte-kit/output/server/entries/pages/hledat/_search_.svelte.js   6.86 KiB
05:19:29.165 | .svelte-kit/output/server/entries/pages/index.svelte.js             27.13 KiB
05:19:29.165 | .svelte-kit/output/server/entries/pages/patra/_slug_.svelte.js      2.36 KiB
05:19:29.165 | .svelte-kit/output/server/entries/pages/patra/index.svelte.js       0.30 KiB
05:19:29.165 | .svelte-kit/output/server/entries/pages/tirata_admin.svelte.js      0.35 KiB
05:19:29.165 | .svelte-kit/output/server/chunks/index-b60f7d7e.js                  7.23 KiB
05:19:29.165 | .svelte-kit/output/server/chunks/api-97e42fa3.js                    0.62 KiB
05:19:29.165 | .svelte-kit/output/server/chunks/html-0300acf0.js                   1.34 KiB
05:19:29.165 | .svelte-kit/output/server/chunks/stores-f0be75ae.js                 20.85 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/Link-feeb5af9.js                   1.13 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/Head-8555753a.js                   4.69 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/Content-4ac3e065.js                9.04 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/PageHeader-3d976e70.js             3.02 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/ContactForm-2a06d660.js            7.72 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/Image-85293e22.js                  3.91 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/StoreyPlan-ff1a9c8c.js             230.19 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/StoreyTable-0fb1a4f2.js            10.72 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/hooks-1c45ba0b.js                  0.00 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/msg-8e250072.js                    0.73 KiB
05:19:29.166 | .svelte-kit/output/server/chunks/form-7160d3e5.js                   0.60 KiB
05:19:29.167 | .svelte-kit/output/server/chunks/search-52439ac6.js                 0.15 KiB
05:19:29.167 | .svelte-kit/output/server/chunks/appartment-3cbab68c.js             1.59 KiB
05:19:29.167 | Prerendering
05:19:29.202 | Building service worker
05:19:29.212 | vite v2.9.13 building for production...
05:19:29.214 | transforming...
05:19:29.218 | ✓ 2 modules transformed.
05:19:29.222 | rendering chunks...
05:19:29.223 | .svelte-kit/output/client/service-worker.js   5.88 KiB / gzip: 1.63 KiB
05:19:29.223 |  
05:19:29.223 | Run npm run preview to preview your production build locally.
05:19:29.224 |  
05:19:29.224 | No adapter specified
05:19:29.224 | See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
05:19:29.312 | Error! No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
05:19:29.312 | Learn More: https://vercel.link/missing-public-directory
05:19:29.421 | Error: Command "vercel build" exited with 1

**Comment by oneezy** [comment] 2022-08-15 03:35
@frontycore similar case on this end. I had this working fine at one point and something changed. 

I created an issue on my repo i'll link here as well:
https://github.com/oneezy/monorepo/issues/1

@Conduitry can we reopen this? seems to be affecting a few people

**Comment by mahlm** [comment] 2022-08-17 19:52
This is due to github ignoring filename case. Try running `git config core.ignorecase false` to enable case sensitivity within your repository and push the changes to master.

**Comment by Zamiell** [comment] 2022-08-20 03:13
I started a brand new SvelteKit project and attempted to deploy it to Vercel, and I got the error that the OP describes about a missing `public` directory.

It turns out that the problem was because I had configured it to use the Node.js adapter, as specified in the [SvelteKit docs](https://kit.svelte.dev/docs/adapters) (for testing purposes).

So, if this is happening to you, the solution is to convert your project back to the `adapter-auto` and remove the `out` field from the `adapter` argument.

**Comment by oneezy** [comment] 2022-08-20 12:07
@Zamiell what do you mean when you say _"remove the `out` field from the `adapter` argument"_?

Still unable to resolve the issue on my end but I'm using Turborepo + Sveltekit.

**Comment by Zamiell** [comment] 2022-08-20 17:43
> what do you mean when you say "remove the out field from the adapter argument"?

Read Svelte docs and look what they say:

![image](https://user-images.githubusercontent.com/5511220/185759697-cfacc1ca-9886-4cd9-b248-ad2f27ef16a8.png)

They recommend making these two changes, which includes adding an "out" field.
You have to remember to revert these changes back to the hello-world default if you want Vercel to work.

**Comment by madeleineostoja** [comment] 2022-08-21 03:33
I'm also seeing this on Vercel from upgrading to the latest version of sveltekit, which is a regression from a successful deployment a few days ago. I feel like this issue should be reopened until the cause is pinned down

**Comment by madeleineostoja** [comment] 2022-08-23 21:26
FWIW my issue was that I was sharing vite config in a monorepo, and importing `{ sveltekit } from '@sveltejs/kit/vite'` from the shared config rather than the project caused the adapter to not run. Might be worth documenting that that has to be imported from the project root in a monorepo env.

**Comment by oneezy** [comment] 2022-08-23 21:50
that's likely what my issue is @madeleineostoja thanks for the tip. 
do you have that code in a repo anywhere? I'm about to give it a try

> _here's what my setup looks like_
![image](https://user-images.githubusercontent.com/7369575/186272551-b562c389-c66a-4941-8204-595bbca6aa19.png)

**Comment by madeleineostoja** [comment] 2022-08-23 22:55
FWIW all you need to do is pass the apps sveltekit plug-in to your shared config, no need to copy n paste the whole thing

**Comment by oneezy** [comment] 2022-08-23 23:08
> All you need to do is pass the apps sveltekit plug-in to your shared config, no need to copy n paste the whole thing

I actually tried that but didn't work on first go. like this right?
```js
import { viteConfig } from '@packages/config';
import { sveltekit } from '@sveltejs/kit/vite';


/** @type {import('vite').UserConfig} */
const config = {
  ...viteConfig,
  
  plugins: [
     sveltekit(),
  ],
};

export default config;
```

**Comment by dummdidumm** [comment] 2022-10-12 18:27
Closing again since it seems the issue is resolved/unrelated. Not sure where and how to document that monorepo caveat best (probably not inside the Vercel adapter, this is likely something more general) - ideas welcome.

**Closed by dummdidumm** 2022-10-12 18:27 UTC
Labels: pkg:adapter-vercel, awaiting submitter

**Comment by madeleineostoja** [comment] 2022-10-12 19:48
Could you have a “working with monorepos” section in the general docs under advanced? It’d be a small section but probably worthwhile

**Comment by oneezy** [comment] 2022-12-01 22:24
> _"Could you have a “working with monorepos” section in the general docs under advanced? 
> It’d be a small section but probably worthwhile"_

@madeleineostoja @dummdidumm I second that ! 

Would also be cool to see a **Svelte #monorepo** discord channel but not holding my breath. 
Looks like svelte discord has been downsizing.

There is a **[Turborepo #svelte](https://discord.com/channels/818588653005176832/920705710600388648)** discord channel but it doesn't get much love.

--- 

For anyone seeing this, we've made a ton of progress in our [Turborepo + Sveltekit + Tailwind + Histoire](https://github.com/oneezy/monorepo/) starter. 

Contributions and Issue fixin' are always welcome 😄

**Comment by coryvirok** [comment] 2023-04-26 22:07
Copying from https://github.com/oneezy/monorepo/issues/1#issuecomment-1441117634 in case anyone else is uring Turbo + Vercel + Sveltekit.

----->%-------

thought i'd just leave this here since i was having the same issue and this was the first result: if you're using turborepo, don't forget the .vercel/ directory in the build output!

```
"pipeline": {
  "build": {
    "dependsOn": [...]
-   "outputs": [..., ".svelte-kit/**"],
+   "outputs": [..., ".svelte-kit/**", ".vercel/**"],
    ...
  },
}
```

**Comment by braden-w** [comment] 2024-06-30 14:02
@coryvirok answer solved my issue! Just a heads up, now in Turborepo v2, pipeline has been renamed to "tasks", so the new `turbo.json` would be:

> ```diff
> - "pipeline": {
> + "tasks": {
>   "build": {
>     "dependsOn": [...]
> -   "outputs": [..., ".svelte-kit/**"],
> +   "outputs": [..., ".svelte-kit/**", ".vercel/**"],
>     ...
>   },
> }
> ```

**Comment by hugotox** [comment] 2024-07-10 03:10
I'm trying to update turborepo from 1.13.3 to 2.0.6 and started seeing this issue. My tasks config has the correct output, and the project in vercel is using default settings.

What seems confusing to me is in vercel the default settings say "public" so why is my project working fine with turbo 1 and the same output from turbo?

<img width="439" alt="image" src="https://github.com/sveltejs/kit/assets/1758062/4893d906-bb98-40f5-b678-c0a7b067f3e6">
