### ISSUE TITLE
<_layout> received an unexpected slot "default".

### ISSUE THREAD

**Issue by floratmin** [sveltejs/kit#4410] opened 2022-03-21 09:21 UTC
### Describe the bug

When using a `__layout.svelte` file for applying a navigation bar I get the error `<_layout> received an unexpected slot "default".` on loading the page `http://localhost:3000/en/inner/inner` in dev mode and the content of the page is not displayed. I set up a fresh repository to reproduce the error.

### Reproduction

[svelte-kit-unexpected-slot-default](https://github.com/floratmin/svelte-kit-unexpected-slot-default)

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 21.97 GB / 30.75 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 17.5.0 - ~/.nvm/versions/node/v17.5.0/bin/node
    npm: 8.4.1 - ~/.nvm/versions/node/v17.5.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.82
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33 
    @sveltejs/kit: next => 1.0.0-next.301 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

**Comment by ignatiusmb** [comment] 2022-03-21 09:40
> The only requirement is that the component includes a `<slot>` for the page content

See https://kit.svelte.dev/docs/layouts, the error is correct. Closing as this is not a bug because you did not include a `<slot>` in [your `__layout.svelte`](https://github.com/floratmin/svelte-kit-unexpected-slot-default/blob/2fb199e64295afcfd8ac7d77be4625bdbf9cacd4/src/routes/en/__layout.svelte)

**Closed by ignatiusmb** 2022-03-21 09:40 UTC
