### ISSUE TITLE
Disabling javascript in the todo example posts to the endpoint, but then stays there

### ISSUE THREAD

**Issue by treeder** [sveltejs/kit#1703] opened 2021-06-17 19:36 UTC
If I disable javascript and submit a new todo, it posts to the endpoint (/todos.json) then just stays there so you just see the JSON response. I've read why it does this, so forms will work without javascript if they can't be enhanced, but should it redirect back to the page automatically or something in that case?

**Comment by geoffrich** [comment] 2021-08-05 23:31
Hm, I can't seem to repro this. Steps followed:

1. Disable JS
2. Go to the deployed [todo example](https://netlify.demo.svelte.dev/todos)
3. Type in a todo and hit Enter to submit the form
4. The page reloads and the new todo is shown

Relevant code that redirects after a successful submission:
https://github.com/sveltejs/kit/blob/5538107377a6685ed78c666e8a77dd9a4184f5f0/packages/create-svelte/templates/default/src/routes/todos/_api.ts#L31-L42

Is there something I'm missing?

**Comment by ktsangop** [comment] 2021-10-03 09:39
Gave it a try too.
Could not reproduce it, at least on Chromium based browsers and Firefox (on Windows 10).
What kind of browser did you use? Did you have any extensions installed?

FYI : I 've had a few similar issues in the past with JSON prettifyer extensions modifying browser behavior.

**Comment by furstenberg** [comment] 2021-10-31 12:54
I just tried the same steps as @geoffrich did. I cannot reproduce this.

**Comment by bluwy** [comment] 2021-10-31 13:42
Closing this as no one was able to reproduce this. Thanks for checking this issue y'all!

**Closed by bluwy** 2021-10-31 13:42 UTC
Labels: help wanted, examples
