### ISSUE TITLE
The page store contains data from a previous page

### ISSUE THREAD

**Issue by mquandalle** [sveltejs/kit#6307] opened 2022-08-26 09:13 UTC
### Describe the bug

On a page I use both `+page.server.js` and `+page.js` with something like the following code to merge the two objects:

```js
// +page.server.js
export async function load() {
  return { title: "Title" }
}

// +page.js
export async function load({ data }) {
  return { ...data, extra: "hello" }
}
```

When I navigate out of this page, the `$page.data` isn't correctly updated and keep data from the previous page `load` function.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-f3vjkk?file=src/routes/+page.svelte

### System Info

```shell
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.06 GB / 15.39 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chromium: 104.0.5112.101
    Firefox: 103.0
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.68 
    @sveltejs/kit: next => 1.0.0-next.442 
    svelte: ^3.42.6 => 3.49.0 
    vite: ^3.0.0 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment] 2022-08-26 09:35
Duplicate of #6300 (will update the title, yours better describes the issue)

**Closed by dummdidumm** 2022-08-26 09:35 UTC
