### ISSUE TITLE
"Invalid request body" is not valid JSON

### ISSUE THREAD

**Issue by vfilatov** [sveltejs/kit#7410] opened 2022-10-27 18:43 UTC
### Describe the bug

POST requests fail before even reach the server

### Reproduction

npm create svelte@latest my-app
all defaults
pnpm i
pnpm dev --port 3000

navigate to http://localhost:3000/sverdle
type "qwert" <enter>

```text
Unexpected token 'I', "Invalid request body" is not valid JSON
SyntaxError: Unexpected token 'I', "Invalid request body" is not valid JSON
```

### System Info

```Shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel Core Processor (Haswell, no TSX, IBRS)
    Memory: 27.70 GB / 31.42 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.84 
    @sveltejs/kit: next => 1.0.0-next.525 
    svelte: ^3.46.0 => 3.52.0 
    vite: ^3.1.0 => 3.2.0
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment] 2022-10-27 18:56
Duplicate of #7409.

**Closed by Conduitry** 2022-10-27 18:56 UTC
