### ISSUE TITLE
Be able to pass the platform object to svelte.config.js

### ISSUE THREAD

**Issue by DanielHritcu** [sveltejs/kit#8397] opened 2023-01-08 11:05 UTC
### Describe the problem

When using adapters like cloudflare workers that export their proprietary `Platform`, it's difficult to manage it during local development.

There are workarounds, but it involves using hooks, and polyfills. 

It would be nice to be able to use Miniflare to define the platform without touching the app's source.

### Describe the proposed solution

Be able to pass the platform object to `svelte.config.js`

```
import { platform } from '...'
...
 kit: {
  ...
  platform: platform()
  ...
 }
 ...
```

### Alternatives considered

Use hooks.

### Importance

nice to have

### Additional Information

This can be done by changing two files:

Add platform to config validation
https://github.com/sveltejs/kit/blob/dd7b96e459a9db6dd996e3643cb07c191b9bb128/packages/kit/src/core/config/options.js#L173
```js
  platform: validate(null, (input, keypath) => {
    // if(... # Type check input
    return input;
  }),
```

Assign platform in vite dev
https://github.com/sveltejs/kit/blob/dd7b96e459a9db6dd996e3643cb07c191b9bb128/packages/kit/src/exports/vite/dev/index.js#L499
```
platform: svelte_config.kit.platform
```

**Comment by DanielHritcu** [comment] 2023-01-08 11:09
I'm currently using these changes to load the `env` from miniflare to access KV.

I can open a PR if this does not conflict with the current plans of the svelte-kit team.

In relation to other issues related, this implementation keeps the `adapter` specific implementation out of svelte-kit.

It would be nice to have the the implementation in the adapter packages, but that is another thing.

**Comment by DanielHritcu** [comment] 2023-01-08 11:15
I'm able to use local KV like this:

`svelte.config.js`
```

let platform;

const getPlatform = async () => {
	if (platform) {
		return platform;
	}

	const kvNamespaces = ["SESSION"]

	const mf = new Miniflare({
		kvNamespaces,
		kvPersist: true,
		cachePersist: true,
		globalTimers: true,
		globalRandom: true,
		globalAsyncIO: true,
		log: new Log(LogLevel.INFO, { prefix: 'Miniflare' }),
		script: `
				addEventListener("fetch", (event) => {
					event.waitUntil(Promise.resolve(event.request.url));
					event.respondWith(new Response(event.request.headers.get("X-Message")));
				});
				addEventListener("scheduled", (event) => {
					event.waitUntil(Promise.resolve(event.scheduledTime));
				});
				...
			`
	});

	/** @type {App.Platform} */
	const platform = {
		env: await mf.getBindings(),
	};

	return platform
};

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapter(),
		platform: await getPlatform(),
	}
};

export default config;

```

**Comment by Rich-Harris** [comment] 2023-01-08 16:05
This is very much something we want to add, but it will be the responsibility of adapters to set `platform` at dev time, not a new configuration option. Closing as dupe of #3535

**Closed by Rich-Harris** 2023-01-08 16:05 UTC
