### ISSUE TITLE
Vercel Deployments are erroring only in prod (not in dev, not in preview)

### ISSUE THREAD

**Issue by bent101** [sveltejs/kit#10918] opened 2023-10-25 01:48 UTC
### Describe the bug

see [this discussion](https://github.com/sveltejs/kit/discussions/10916) for more info

### Reproduction

[repro](https://github.com/bent101/sveltekit-test), just a skeleton project with a `routes/+page.svelte` and a `routes/+page.ts` loading dummy json
[failed vercel deployment](https://sveltekit-test-eight-jade.vercel.app/)

### Logs

```Shell
TypeError: Failed to parse URL from [object Request]
at Object.fetch (node:internal/deps/undici/undici:11576:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.fetch (file:///var/task/.svelte-kit/output/server/index.js:2372:12)
at async file:///var/task/.svelte-kit/output/server/index.js:740:20
at async file:///var/task/.svelte-kit/output/server/index.js:629:86
at async Promise.all (index 0)
at async unwrap_promises (file:///var/task/.svelte-kit/output/server/index.js:629:9)
at async load_data (file:///var/task/.svelte-kit/output/server/index.js:733:25)
at async file:///var/task/.svelte-kit/output/server/index.js:2106:18 {
[cause]: TypeError [ERR_INVALID_URL]: Invalid URL
at new NodeError (node:internal/errors:405:5)
at new URL (node:internal/url:637:13)
at new Request (node:internal/deps/undici/undici:7132:25)
at fetch2 (node:internal/deps/undici/undici:10715:25)
at Object.fetch (node:internal/deps/undici/undici:11574:18)
at fetch (node:internal/process/pre_execution:242:25)
at n (/var/task/___vc/__launcher/__launcher.js:14:5526)
at fetch (file:///var/task/.svelte-kit/output/server/index.js:2394:18)
at #options.hooks.handleFetch (file:///var/task/.svelte-kit/output/server/index.js:2919:79)
at Object.fetch (file:///var/task/.svelte-kit/output/server/index.js:2372:33) {
input: '[object Request]',
code: 'ERR_INVALID_URL'
}
}
```

### System Info

```Shell
vercel :D
```

### Severity

blocking all usage of SvelteKit

**Comment by lennart-jaervinen** [comment] 2023-10-25 06:58
I have the _exact_ same error since I deployed yesterday (nothing grave did really change within the code and reverting the changes and re-deploying didn't fix the error. I'm also using the adapter-vercel).

Glad I only pushed to staging yesterday, but this blocks all live deployments, which I will need to hold until the issue gets resolved.

**Comment by dummdidumm** [comment] 2023-10-25 08:48
It looks like the cause is https://github.com/nodejs/undici/issues/2374 . I suspect that Vercel bumped the Node 18 version recently, which includes this bug, and therefore all subsequent deployments fail. As a quickfix you can tell Vercel to deploy to Node 16 on the settings main page (scroll down to "Node.js version")

**Comment by KhafraDev** [comment] 2023-10-25 14:04
this was fixed in undici v5.26.4, upgrading undici will fix this

**Comment by dummdidumm** [comment] 2023-10-25 14:16
So it seems the linked issue was red herring, as it was closed as a duplicate of something else and that issue was fixed and released a few days ago - and I can reproduce this with the latest version of undici. I'm very confused now as to what could cause this.

**Comment by benmccann** [comment] 2023-10-25 14:29
Hmm. They edited the issue it was closed in favor of. They were previously saying https://github.com/nodejs/node/issues/50263. Perhaps this is caused by that issue?

**Comment by dummdidumm** [comment] 2023-10-25 14:37
Mhm okay. But why is the polyfill failing with a older versions of undici, too, then? It's very strange, and I'm tempted to add something to the polyfill code to check for specific node versions and not apply them there.

**Comment by benmccann** [comment] 2023-10-25 15:12
We only need to polyfill < Node 18.11: https://github.com/sveltejs/kit/blob/bfa2b6ec88a6d522d87c924d7c466c01e142e66e/packages/kit/src/exports/node/polyfills.js#L24

I'd be fine with removing the polyfill on older Node versions. Though it's unclear to me what Node versions are being affected by this bug and whether that would fix anything.

**Comment by dummdidumm** [comment] 2023-10-25 15:17
We can't completely, `crypto` is still `webcrypto` in node - but yeah, we could add a check for the node version and avoid it. In my local testing this fixes the issue.

**Comment by dummdidumm** [comment] 2023-10-25 17:17
Sveltekit 1.27.1 hopefully fixes this

**Comment by echocrow** [comment] 2023-10-25 18:06
Temporarily falling back to node16 on Vercel as suggested in https://github.com/sveltejs/kit/issues/10918#issuecomment-1778802619 circumvented the issue for us.

Just updated SvelteKit to `1.27.1` and reverted to node18; can confirm server-side fetches are working again. ✅

Thanks for the quick hotfix @dummdidumm!

**Comment by benmccann** [comment] 2023-10-25 18:28
Thanks for confirming the fix

**Closed by benmccann** 2023-10-25 18:28 UTC
Labels: pkg:adapter-vercel
