### ISSUE TITLE
Automatically encodeURIComponent for formaction

### ISSUE THREAD

**Issue by sergeypdev** [sveltejs/kit#9757] opened 2023-04-24 00:40 UTC
### Describe the problem

In formaction docs it says to use syntax like `?/actionName` to call a different action. That name is automatically mapped to the `actions` object in +page.server.js

The problem is that some api gateways and load balancers will reject the unescaped forward slash, while locally it works perfectly fine. I encountered this issue when deploying svelte kit to AWS Lambda, the request with `?/action` init failed with `x-amzn-ErrorType: InvalidQueryStringException` error before even reaching the app.

### Describe the proposed solution

`formaction` to be automatically url encoded. It would turn `?/action` into `?%2Faction`.
When using `use:enhance`, the `action` field passed in the callback should be automatically decoded too, to turn it back into the original string.

### Alternatives considered

There's a couple of alternatives

- Manually encoding the uri. Makes it harder to type and not as clear. Since it works without escaping most of the time and can fail in production is still kind of a footgun
- Use a different symbol instead of `/` to denote a different action. I'm not sure what it could be though.

### Importance

would make my life easier

**Comment by Conduitry** [comment] 2023-04-24 00:50
Duplicate of #7098 and #9057. This is something we've previously decided not to do, as there are valid workarounds.

**Closed by Conduitry** 2023-04-24 00:50 UTC
