### ISSUE TITLE
Duplicate css bundles (different name) in build assets

### ISSUE THREAD

**Issue by skiv71** [sveltejs/kit#10684] opened 2023-09-05 11:20 UTC
### Describe the bug

Basic sveltekit project, with config for an SPA and a +layout.svelte file for common css dependancy across different routes.

![image](https://github.com/sveltejs/kit/assets/13932724/67a8fa7f-4e50-49d5-bc4a-7aaa54bcfa4e)

However, when I look at the build artifacts, I see the same css in 2 different files (which are quite large, due to it being bootstrap.css).

![image](https://github.com/sveltejs/kit/assets/13932724/a5e7a4e5-627f-4d97-b0f6-0c58580e803b)

![image](https://github.com/sveltejs/kit/assets/13932724/83350119-a81a-424e-9bbc-7d1ddf7bb95a)

### Reproduction

1/. create a sveltekit app

2/. create a +layout.js with...

![image](https://github.com/sveltejs/kit/assets/13932724/a3ec46d4-d20a-419e-ac93-90bf9a1c9d39)

3/. create another route with a +page.svelte (and some content)

4/. create a +layout.svelte in src/routes with content: -

![image](https://github.com/sveltejs/kit/assets/13932724/44749325-0410-4fcd-8ac4-cd857df7698a)

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 5.13 GB / 14.00 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.config/nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.config/nvm/versions/node/v18.17.1/bin/yarn
    npm: 10.0.0 - ~/.config/nvm/versions/node/v18.17.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-static: ^2.0.3 => 2.0.3 
    @sveltejs/kit: ^1.20.4 => 1.24.0 
    svelte: ^4.0.5 => 4.2.0 
    vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

### Additional Information

total 464
-rw-r--r-- 1 skivy71 skivy71 233455 Sep  5 12:07 0.6fdf698b.css
-rw-r--r-- 1 skivy71 skivy71    577 Sep  5 12:07 3.d1a190f4.css
-rw-r--r-- 1 skivy71 skivy71 233308 Sep  5 12:07 _layout.7f0430da.css
-rw-r--r-- 1 skivy71 skivy71    577 Sep  5 12:07 _page.d1a190f4.css

Can't be good for distributing an SPA?

**Comment by s3812497** [comment] 2023-09-05 14:51
closed as duplicate of https://github.com/sveltejs/kit/issues/9161

**Closed by s3812497** 2023-09-05 14:51 UTC
