### ISSUE TITLE
Catching 404 errors on server side

### ISSUE THREAD

**Issue by L1xx3r** [sveltejs/kit#7101] opened 2022-09-30 20:25 UTC
### Describe the problem

Some code a while go worked perfectly:

`__error.js`

```javascript
import customFetch from '$lib/customFetch'
import { setCookie } from '$lib/helpers'

export async function load ({ url, error, status }) {
  if (status === 404 && !(url.pathname.substring(1)).includes('/')) {
    return await customFetch
      .service('api/redirects')
      .get(url.path.substring(1))
      .then(redirect => {
        if (redirect.cookie) {
          setCookie(redirect.cookieName, redirect.cookieValue)
        }
        return {
          status: redirect.status,
          redirect: redirect.location
        }
      })
      .catch(() => {
        return {
          props: {
            status: status,
            error: error.message
          }
        }
      })
  } else {
    return {
      props: {
        status: status,
        error: error.message
      }
    }
  }
}
```

but now none of this will work, and I cannot make it work in any way other than in a way that loads the whole site. 

This is used in 2 ways.

1) If you change the structure of your site, for SEO reasons, you want a 301 redirect.

2) I also use it for short links for affiliate forwarding using a 307 redirect.

The load function also doesn't have `error` or `status` so I cannot do it in `+layout.server.js`

### Describe the proposed solution

Allow `+error.js` or `+error.server.js` files, or have the error in `+layout.server.js`??

### Importance

would make my life easier

**Comment by dummdidumm** [comment] 2022-10-10 08:45
Duplicate of #6106

**Closed by dummdidumm** 2022-10-10 08:45 UTC

**Comment by L1xx3r** [comment] 2022-10-10 12:48
@dummdidumm this isn't a duplicate of #6106 at least not in the solution.

I am looking for a way to catch 404s that are not in the routes, having my function in the `+layout.server.js` will not know yet it is a 404 error, unless i am mistaken.

**Comment by dummdidumm** [comment] 2022-10-10 13:30
No, you won't find out if it's a 404 or not because the layout doesn't run until it's determined which route to go to (or none, in the case of 404). Adding something to layout which says "you're on a 404 route" isn't wanted in the current design.

What you can do for this specific problem is to create a catch-all route, from which you redirect:
```js
// src/routes/[...notFound]/+page.js
export function load() {
  // you end up here when no other route was matched, i.e. the 404 case
  throw redirect(301, 'somewhere/else');
}
```

**Comment by L1xx3r** [comment] 2022-10-10 13:33
I thought `+page.js` ran after the site was loaded?

I am unclear the difference between `+page.server.js` and `+page.js` for where to add the load and catch the 404s

**Comment by dummdidumm** [comment] 2022-10-10 13:43
you can place it in `+page.js` or `+page.server.js`, it doesn't make a difference. Both are run before the Svelte component/page is rendered.

**Comment by L1xx3r** [comment] 2022-10-10 22:57
Ummm... throwing redirect is not working.

However vite console prints this: 

`Redirect { status: 307, location: 'https://example.com' }`

The site doesn't redirect, page still loads as a 404.

I tried both `+page.js` and `+page.server.js`

**Comment by L1xx3r** [comment] 2022-10-11 20:03
@dummdidumm ?? Hello? Is this a new issue ? I don't want to create another unless I need to.

**Comment by dummdidumm** [comment] 2022-10-11 20:11
Just tried it out, works for me. 

```js
// [...notfound]/+page.js
import { redirect } from '@sveltejs/kit';

export function load() {
  throw redirect(307, '/docs'); // or whereever you want to redirect
}
```

**Comment by L1xx3r** [comment] 2022-10-11 20:32
Strange, it doens't work for me.

Do you see any reason it will not work with this:

```javascript
import env from '$lib/env'
import { error, redirect } from '@sveltejs/kit'
import got from 'got'

export async function load ({ url }) {
  let e404 = false

  const sitePage = await got(`${env.api}/site-pages/?pathname=${url.pathname}`)
    .then(response => {
      let obj = JSON.parse(response.body)
      obj = obj.data || obj
      if (obj[0]) {
        return obj[0]
      } else {
        e404 = true
        return null
      }
    })
    .catch((e) => {
      console.error(e)
      e404 = true
    })

  console.log('sitePage', sitePage)

  if (e404) {
    await got(`${env.api}/redirects/?linkName=${url.pathname}`)
      .then(response => {
        let obj = JSON.parse(response.body)
        obj = obj.data || obj
        if (obj[0]) {
          throw redirect(obj[0].status, obj[0].location)
        }
      })
      .catch((e) => {
        console.error(e)
        e404 = true
      })
  }

  if (e404) throw error(404, 'not-found')

  return {
    sitePage
  }
}
```

Considering all the data requests are working as expected (I have confirmed this with console logs)?

**Comment by L1xx3r** [comment] 2022-10-11 20:36
HAhaha wait a sec, I am catching the throw... lol My bad!

**Comment by dummdidumm** [comment] 2022-10-11 20:37
I can't tell from reading the code without context what is going on. Have you tried to throw out everything in that load function and just try to redirect to some url?

**Comment by L1xx3r** [comment] 2022-10-11 20:47
@dummdidumm the following works perfectly. Thanks for your help:

```javascript
import env from '$lib/env'
import { error, redirect } from '@sveltejs/kit'
import got from 'got'
import _ from 'lodash'

export async function load ({ url }) {
  let e404 = false
  let redirectObj = {}

  const sitePage = await got(`${env.api}/site-pages/?pathname=${encodeURI(url.pathname)}`)
    .then(response => {
      let obj = JSON.parse(response.body)
      obj = obj.data || obj
      if (obj[0]) {
        return obj[0]
      } else {
        e404 = true
        return null
      }
    })
    .catch((e) => {
      console.error(e)
      e404 = true
    })

  if (e404) {
    redirectObj = await got(`${env.api}/redirects/?pathname=${url.pathname}`)
      .then(response => {
        let obj = JSON.parse(response.body)
        obj = obj.data || obj
        if (obj[0]) {
          return obj[0]
        }
      })
      .catch((e) => {
        console.error(e)
        e404 = true
      })
  }

  if (!_.isEmpty(redirectObj)) throw redirect(redirectObj.status, redirectObj.location)
  if (e404) throw error(404, 'not-found')

  return {
    sitePage
  }
}
```

**Comment by nohea** [comment] 2022-10-13 23:37
> HAhaha wait a sec, I am catching the throw... lol My bad!

caught me too. 

I think this is a 'not good coding style' to have `throw redirect()` for normal flow control. A redirect may or may not be an error condition, so it should not require throw. Now we have to work around `throw redirect()` in *.server.ts try blocks.

**Comment by L1xx3r** [comment] 2022-10-13 23:39
@nohea I agree completely. Throwing it like an error when it is the wanted action is strange and confusing.
