### ISSUE TITLE
[bug] page destroyed during hydration if a file fails to load

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2699] opened 2021-10-28 16:35 UTC
### Describe the bug

The page from the reproduction loads during SSR and then fails during hydration during dev mode if you both have adblock on and are not using the new `experimental.prebundleSvelteLibraries` option (https://github.com/RobBrazier/svelte-awesome/issues/775).

This particular example is kind of an edge case, but the outcome is really bad and I'm not so sure how rare it is more generally. Per Rich's point, sometimes things fail to load because you live in NYC and take the subway and lose connectivity going into a tunnel. That the entire page would be wiped out eventhough SSR succeeded is quite a bad outcome. If we wrapped the whole hydration in a `try`/`catch` maybe you'd at least see the server-rendered page. Or perhaps if we had error boundaries the developer could do something smarter

### Reproduction

https://github.com/benmccann/500-import-failure

### Logs

I get a message in the browser:

```shell
Failed to fetch dynamically imported module: http://localhost:3000/src/routes/index.svelte
```

Screenshot:

![Screenshot from 2021-10-28 09-30-41](https://user-images.githubusercontent.com/322311/139297588-fdef2497-f2cf-4e90-a762-9142bf8e9791.png)

### System Info

This fails on `1.0.0-next.138` and newer all the way up to `master` since that's when we turned on `compilerOptions.hydratable`: https://github.com/sveltejs/kit/pull/2024

https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next138

### Severity

blocking all usage of SvelteKit

**Comment by Levyks** [comment] 2021-12-05 23:54
I'm having a similar issue, but it's on the client side, I have this component called AdSlot, and it gets blocked if you have an AdBlocker turned on, and, because of that, everything gets broken in my page, the css does not load properly and so on

**Comment by filmlovr** [comment] 2022-07-14 06:36
> I'm having a similar issue, but it's on the client side, I have this component called AdSlot, and it gets blocked if you have an AdBlocker turned on, and, because of that, everything gets broken in my page, the css does not load properly and so on
> 
> EDIT: I forgot to mention, the problem only happens when running a production build, with `npm run dev` it works fine

For reference, looks like my Ghostery is breaking my Sveltekit SPA when in production. 'npm run preview' is ok, and dev. If I host the SPA locally though from the build folder, I can reproduce the issue. Pausing Ghostery and the page hosts fine. 

Any ideas on how I can resolve  this - just spent 2 days learning SvelteKit and went to deploy for then this to happen :-(

**Comment by chcardoz** [comment] 2023-05-31 02:26
hey! i was wondering if this issue is still open because the milestone was set a long time ago.

**Comment by eltigerchino** [comment] 2024-12-04 07:19
Closing this because I can't reproduce this on the latest version of Svelte and SvelteKit with an adblocker on.

**Closed by eltigerchino** 2024-12-04 07:19 UTC
Labels: bug, help wanted, p2-nice-to-have

**Comment by itssumitrai** [comment] 2025-02-28 18:41
@benmccann @eltigerchino This is still an issue in real world. Can we introduce an option in kit to catch hydration error ? I am happy to contribute if someone can point me the right direction.
