### ISSUE TITLE
Replacing `GET` with `load` in `+page.server.js` creates issues with navigating back

### ISSUE THREAD

**Issue by TranscendentalRide** [sveltejs/kit#6573] opened 2022-09-05 01:28 UTC
### Describe the bug

Prior the `GET` function would return data in a very similar way to `load`, however, if a page was linked to via `sveltekit:reload` (in prior version) and the user navigated away from that page then clicked back, all was well.

Now with `load` function instead, clicking to another page and then using the back button triggers a call to `__data.js` even if `data-sveltekit-reload` is provided on the inbound link.

### Reproduction

To reproduce:

https://stackblitz.com/edit/sveltejs-kit-template-default-6rejvf?file=src%2Froutes%2Ftodos%2F%2Bpage.server.js,src%2Flib%2Fheader%2FHeader.svelte&terminal=dev

1. Click TODO
2. Click ABOUT
3. Right-click and choose "back"

Expected:

Behavior like with previous `GET` verb being available. After repeating this from step 1-3, click "back" would not fail. 

### System Info

```shell
MacOS 12.5, Chrome 104, SvelteKit 1.0.0-next.465
```

### Severity

blocking an upgrade

### Additional Information

This is part of a need for a route to only render SSR no matter how it is visited. Never call `__data`. At least bring back the old `GET` functionality; although not sure if that might have the same problem after some cache is invalidate.

**Comment by Rich-Harris** [comment] 2022-09-05 11:56
Pretty sure this behaviour hasn't changed since `load` was called `GET`, and that you're seeing something else. Regardless, this, like #6574, is effectively a duplicate of #5699

**Closed by Rich-Harris** 2022-09-05 11:56 UTC
