### ISSUE TITLE
Netlify deploy failing when trying to bundle functions

### ISSUE THREAD

**Issue by felixakiragreen** [sveltejs/kit#1859] opened 2021-07-09 00:41 UTC
**Describe the bug**
When trying to deploy to Netlify the build fails at the step: "2. Functions bundling"
`yarn dev`, `yarn build`, `yarn run preview`, `netlify dev` all work with no issues, it only happens when I try to deploy.

**Logs**
```
 2. Functions bundling                                         
8:27:53 PM: ────────────────────────────────────────────────────────────────
8:27:53 PM: ​
8:27:54 PM: Packaging Functions from functions directory:
8:27:54 PM:  - render/index.js
8:27:54 PM: ​
8:27:57 PM: ​
8:27:57 PM: ────────────────────────────────────────────────────────────────
8:27:57 PM:   Dependencies installation error                               
8:27:57 PM: ────────────────────────────────────────────────────────────────
8:27:57 PM: ​
8:27:57 PM:   Error message
8:27:57 PM:   A Netlify Function is using "bufferutil" but that dependency has not been installed yet.
8:27:57 PM: ​
8:27:57 PM:   By default, dependencies inside a Netlify Function's "package.json" are not automatically installed.
  There are several ways to fix this problem:
8:27:57 PM:     - Removing your Function's "package.json" and adding the dependencies to the project's top-level "package.json" instead. This is the fastest and safest solution.
8:27:57 PM:     - Running "npm install" or "yarn" inside your Netlify Function in your build command.
8:27:57 PM:     - Adding the following plugin to your "netlify.toml":
8:27:57 PM: ​
8:27:57 PM:   [[plugins]]
8:27:57 PM:   package = "@netlify/plugin-functions-install-core"
8:27:57 PM: ​​
8:27:57 PM:   In file "/opt/build/repo/frontend/functions/render/index.js"
8:27:57 PM:   Cannot find module 'bufferutil'
```

**To Reproduce**
I am using the latest versions: (hardcoded into package.json to prevent issues)
```
"@sveltejs/adapter-netlify": "^1.0.0-next.19",
"@sveltejs/kit": "^1.0.0-next.19",
```

**Expected behavior**
I expect it to deploy. I have deployed 3 svelte-kit  to netlify, so this isn't my first rodeo. However, they were with previous versions: `"@sveltejs/adapter-netlify": "1.0.0-next.12"` & "@sveltejs/adapter-netlify": "1.0.0-next.14"`

I tried adding the plugin, but it didn't help.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

8:27:57 PM:   Require stack:
8:27:57 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/node_dependencies/resolve.js
8:27:57 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/node_dependencies/index.js
8:27:57 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/main.js
8:27:57 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/index.js
8:27:57 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/commands/get.js
8:27:57 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/main.js
8:27:57 PM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/bin.js
8:27:57 PM: ​
8:27:57 PM:   Resolved config
8:27:57 PM:   build:
8:27:57 PM:     base: /opt/build/repo/frontend
8:27:57 PM:     command: yarn build
8:27:57 PM:     commandOrigin: config
8:27:57 PM:     environment:
8:27:57 PM:       - NODE_VERSION
8:27:57 PM:     publish: /opt/build/repo/frontend/build
8:27:57 PM:     publishOrigin: config
8:27:57 PM:   functionsDirectory: /opt/build/repo/frontend/functions
8:27:57 PM:   redirects:
8:27:57 PM:     - from: /*
      path: /*
      status: 200
      to: /.netlify/functions/render

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- System:
    OS: macOS 11.5
    CPU: (8) arm64 Apple M1
    Memory: 245.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 80.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.19 => 1.0.0-next.19
    @sveltejs/kit: ^1.0.0-next.19 => 1.0.0-next.123
    svelte: ^3.34.0 => 3.38.3

</details>

**Severity**
I'm completely blocked from being able to deploy my website. I was really hoping to get it done tonight, but now I'm stuck. I have a hard launch in a week, and I'm stuck.

**Comment by felixakiragreen** [comment] 2021-07-09 15:59
I finally got it working by just adding a bunch of packages to my `package.json`. It would complain a package was missing, I'd add it, and just repeat until I added all of them. It's weird because they were  ones I wasn't using directly, but some dependency was. Like `bufferutil`, `utf-8-validate`, ...

**Comment by auderer** [comment] 2021-07-15 02:38
@felixakiragreen Please reopen this issue, I believe its something that needs to be addressed. I'm getting the same issue. It appears the Netlify adapter is including some dependencies in the build output which are not being included in the output `package.json` file.

**Comment by austincrim** [comment] 2021-08-03 19:48
I'm getting this issue as well. The generated Netlify function (`render/index.js`) contains a `package.json` but it only includes this line: `{"type":"commonjs"}`. My build is failing on the `supports-color` dependency.

**Comment by brewhousedigital** [comment] 2021-08-12 01:25
These were all the packages I had to add to get Netlify to be happy

```json
"dependencies": {
    "@lukeed/uuid": "^2.0.0",
    "bufferutil": "^4.0.3",
    "cookie": "^0.4.1",
    "supports-color": "^9.0.2",
    "utf-8-validate": "^5.0.5"
  },
```

**Comment by robhicks** [comment] 2021-08-30 15:16
I'm having this issue as well, but the problem I'm seeing is different. I have have set the NODE_VERSION to 14. But it appears to be using Node 12 in Functions bundling:

```shell
8:54:49 AM: ────────────────────────────────────────────────────────────────
8:54:49 AM:   2. Functions bundling                                         
8:54:49 AM: ────────────────────────────────────────────────────────────────
8:54:49 AM: ​
8:54:49 AM: Packaging Functions from .netlify/functions-internal directory:
8:54:49 AM:  - __render.js
8:54:49 AM: ​
8:54:51 AM: ​
8:54:51 AM: ────────────────────────────────────────────────────────────────
8:54:51 AM:   Internal error during "Functions bundling"                    
8:54:51 AM: ────────────────────────────────────────────────────────────────
8:54:51 AM: ​
8:54:51 AM:   Error message
8:54:51 AM:   Error: readdirp: root argument is required. Usage: readdirp(root, options)
8:54:51 AM: ​
8:54:51 AM:   Error location
8:54:51 AM:   During Functions bundling
8:54:51 AM:       at readdirp (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/readdirp/index.js:262:11)
8:54:51 AM:       at /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/readdirp/index.js:276:5
8:54:51 AM:       at new Promise (<anonymous>)
8:54:51 AM:       at Function.readdirpPromise [as promise] (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/readdirp/index.js:274:10)
8:54:51 AM:       at hasFunctionRootFile (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/error.js:119:32)
8:54:51 AM:       at lacksNodeModules (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/error.js:111:12)
8:54:51 AM:       at getModuleNotFoundMessage (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/error.js:50:43)
8:54:51 AM:       at getModuleNotFoundErrorObject (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/error.js:41:25)
8:54:51 AM:       at getModuleNotFoundErrorFromZISI (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/error.js:91:10)
8:54:51 AM:       at getModuleNotFoundError (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/error.js:27:31)
```

**Comment by outerlook** [comment] 2021-08-31 16:58
I'm getting the same error as @robhicks, and it doesn't seem to be the same error as the others. Should we open another issue?

**Comment by hakimmazouz** [comment] 2021-09-03 09:06
Can confirm I'm getting the same issue. Build is failing with a `supports-color` dependency that is unresolved. The `package.json` in `functions-internal` just contains `{"type":"commonjs"}`.

I tried switching the `NODE_VERSION` env variable in Netlify to 12.20 but no dice.

**Comment by stordahl** [comment] 2021-09-04 16:22
I'm having the same issue as mentioned above

**Comment by swgn** [comment] 2021-09-21 23:13
I'm now facing the same issue. After many successful deploys, my site is now failing due to missing deps for `.netlify/functions-internal`. Tried downgrading `kit` and `adapter-netlify` etc, nothing seemed to work.

Temporary workaround is to manually install the 'missing' deps until it succeeds, per @felixakiragreen; hardly ideal tho 😏

**Comment by brewhousedigital** [comment] 2021-10-14 01:06
To anyone still subscribed to this issue, I got in touch with netlify support and they recommended me add this to my `netlify.toml` file.

```toml
[build]
  command = "npm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild"
```

that last part, `node_bundler = "esbuild"` fixed all of my issues. You can read more about their esbuild thing here:
[https://www.netlify.com/blog/2021/04/02/modern-faster-netlify-functions/](https://www.netlify.com/blog/2021/04/02/modern-faster-netlify-functions/)

Hope this helps!

**Comment by benmccann** [comment] 2022-01-21 22:27
The Netlify adapter has changed a lot since this issue was originally opened. There are several comments on this thread, but no clear way to reproduce the issue. As a result, I'm going to go ahead and close this. If you're still having problem, please file a new issue and provide a GitHub repository of a failing project and I'll take a look.

**Closed by benmccann** 2022-01-21 22:27 UTC
Labels: pkg:adapter-netlify
