### ISSUE TITLE
Dev server hangs for 1-2min+ when lots of small files in project directory

### ISSUE THREAD

**Issue by deepmouse** [sveltejs/kit#1278] opened 2021-04-29 23:42 UTC
**Is your feature request related to a problem? Please describe.**
I added ~80mb worth of tiny files (small icon .pngs and .jsons) to my static assets paths. When dev server started, the first request took ~2 minutes to complete. After that it was usually ok for a while, but sometimes this 2min delay reoccurred, making developing on the `npm run dev` very difficult

I am not 100% sure what the cause of this problem was. ~~I suspect it is the file watcher of the dev server, but it could be something else. I read some source code and it seems like `cheap-watch` is being used to watch files on the disk. I never found a reference to this watcher in the documentation, and there is no way to configure it from `svelte.config.cjs`. There is the Vite config, which in turn passes some options to a `chokidar` package (which is the watcher that Vite uses), and some people in the Discord seemed to think that I should change my Vite config to add the files to the ignore list. When I played around with these configs, it seemed to have no effect at all, and me finding out about `cheap-watch` seems to support my theory that `cheap-watch` is indeed the one watching my files.~~

I solved the problem by moving my static assets outside my project root, to a sibling directory.

**Describe the solution you'd like**
~~Watch files based on a `watched_dirs` glob whitelist (do not watch anything unless explicitly told so) in `svelte.config.cjs` along with sane defaults, or watch everything in the local directory, but add user configurable `ignored` list of globs to ignore.~~

Also, as a sidenote, it would be nice to have some kind of `--verbose` option for the dev server, so when you're running it you'd know what's taking so long for it to respond.

**Describe alternatives you've considered**
~~One solution is to completely ignore the configured assets path on dev server, although this would of course have the side effect of not triggering the watcher when static assets are modified. But since no one solution fits everyone, I'd like this to be configurable with a configuration option.~~

~~Or, just optimize the file watcher so well that it can easily handle tens of thousands of small files without the server hanging.~~

**How important is this feature to you?**
For now, I can make do with moving my static assets to a sibling directory of the project directory, so I am able to move on, but I spent plenty of hours debugging this, so improvements would be very good in order to attract people who don't want to dive into source code to debug.

**Comment by babichjacob** [comment] 2021-04-29 23:44
Can you share the repository or give us reproduction instructions, including how to generate a suitable set of files that causes the problem?

**Comment by deepmouse** [comment] 2021-04-29 23:47
Sure.

Get directories `items-icons` and `items-json` from here:

https://github.com/osrsbox/osrsbox-db/tree/master/docs

I guess you can download them as a zip and extract them into your `static`. That should do it

**Comment by JBusillo** [comment] 2021-04-30 18:19
FWIW, I've been looking over the kit/vite code over the past couple of days, and observed the following:

Vite watches all files in the the project root folder.  
Kit only watches files in the /src/routes folder.

Vite has an option (undocumented): server.watch.ignored that takes an array of directories to add to its ignore list, which includes '**/node_modules/**' and '**/.git/**'.  Example: 
```
server: {
	watch: {
	       ignored: ['directory-1', 'directory-2']		// undocumented in vite
}
```
But, I don't believe this issue has to do with the file watchers.  Is there anything else required to reproduce (imports, etc.) other than just copying the icons into the static folder?  I don't see any network requests for the png or json files in my test.  I'm using the example app.

I've seen this behavior before, I think it was in svelte-feather-icons.

Note:  I'm not a contributor -- I just thought you might be interested in my observations.

**Comment by deepmouse** [comment] 2021-04-30 20:30
> Vite has an option (undocumented): server.watch.ignored that takes an array of directories to add to its ignore list, which includes '**/node_modules/**' and '**/.git/**'. Example:

This is documented in Vite, by proxy:
>File system watcher options to pass on to chokidar.
https://vitejs.dev/config/#server-watch

So this `ignored` option is part of the `watch` configuration object that is passed from Vite to chokidar, which I described in the first post.

>But, I don't believe this issue has to do with the file watchers. Is there anything else required to reproduce (imports, etc.) other than just copying the icons into the static folder? I don't see any network requests for the png or json files in my test. I'm using the example app.

Yes, you need to start the dev server and then make any request with a browser. The initial HTTP request to e.g. the root `http://localhost:3000/` will hang and block the whole dev server. Seems to have nothing to do with making requests for the static files themselves.

If it's not the file watcher, then what is it?

**Comment by JBusillo** [comment] 2021-04-30 20:56
I did start the dev server -- loading was practically immediate.  Here's my repo.  I simply copied all the .png and .json files to the static directory -- nothing else:  [https://github.com/JBusillo/testing-kit](https://github.com/JBusillo/testing-kit ) 

In the past, I've seen slow behavior (loading many resources) due to vite's 'module graph' -- but this only traverses node-modules.  I'm at a loss here, since I can't reproduce the problem.  I'm using Linux Ubuntu 21.04.

**Comment by deepmouse** [comment] 2021-04-30 21:12
I'm running on Windows 10, I'll get your repo and see if I can reproduce and get back to you as soon as I can.

**Comment by JBusillo** [comment] 2021-05-01 01:05
I have a dual boot system -- tried it on Windows -- took about 25 seconds to load the page, while it was more or less immediate on Linux.  I had to reboot several times -- I don't know how to kill the service worker -- it was getting in the way.    I had expected additional network activity, but there was none.  I have my test system (with kit and vite) on Linux, but not on Windows.  At this point, I'm at a complete loss.

**Comment by JBusillo** [comment] 2021-05-01 05:58
Ok -- I think I found the bottleneck.  Kit creates a manifest which, among other things, recursively traverses files in the 'static' directory.  In src/core/dev/index.js, the update() function calls create_manifest_data().  In /src/dev/core/create_manifest_data, the return statement (around line 221) is:
```
return {
		assets: fs.existsSync(assets_dir) ? list_files(assets_dir, '') : [],
		layout,
		error,
		components,
		routes
	};
```
I'm not sure of the manifest's purpose in regard to assets.  But this is where most of the startup time is being spent, especially noticeable when there are 40K+ static files.  The difference between our timings (Linux vs. Windows) might be due to how node.js implements its file functions with Windows as opposed to Linux, or differences in our hardware (SSD vs. hard drives, processor speed, etc.).

Here's the timing when I ran my repo on Windows 10:

![Screenshot_2021-04-30_234803](https://user-images.githubusercontent.com/3159776/116771245-645d4e80-aa0f-11eb-9ad5-60586385105d.png)

So, I'm not sure where to go from here.  After a cursory glance, it seems that the assets list might only be needed for the 'build', and possibly not needed for 'dev'.  You might want to check whether your build also seems to pause for a couple minutes.

**Comment by deepmouse** [comment] 2021-05-01 11:44
> So, I'm not sure where to go from here. After a cursory glance, it seems that the assets list might only be needed for the 'build', and possibly not needed for 'dev'. You might want to check whether your build also seems to pause for a couple minutes.

Indeed this only happens on the dev server, not on production build.

**Comment by JBusillo** [comment] 2021-05-02 01:41
@deepmouse I'm getting results and timings that are all over the place.  My testing set-up in windows might be totally messed up.  I'm going to shelve this for the time being.  I was just trying to be helpful.  Feel free to email me if you want to discuss this further.  I don't want to post again to this thread until I'm sure I know what I'm talking about :)

**Comment by JBusillo** [comment] 2021-05-02 06:43
@deepmouse Could you check if you made your config changes as below?  For me, it appears to have fixed the problem:
```
kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		vite: {
			server: {
				watch: {
					ignored: ['**/static/**']
				}
			}
		}
	}
```

**Comment by JBusillo** [comment] 2021-05-04 01:51
Not seeing a response from @deepmouse, I think this issue should be closed.  For the life of me, I cannot find the issue in Chokidar (or possibly in Vite), which says that the way to handle an ignored directory is by specifying '**/static/**' in chokidar's watch config -- see my previous post for the proper config.
This solution seems to solve the issue in my testing in a Windows environment.  It really isn't a SvelteKit issue -- it's more of a documentation shortcoming in chokidar.  To me, this isn't the best workaround, in case a folder is named 'static' exists under the lib or routes folder.  But, the issue has already been raised and closed in chokidar, without providing a better solution.
I don't know how to trigger someone to close this, or to have a collaborator evaluate this issue for closure. Perhaps I'll ping one of the collaborators on Discord if I don't get a response within a couple days. [I've seen people chided for @'ing people in github messages. so I'm doing my best not to get under anyone's skin]

**Comment by babichjacob** [comment] 2021-05-04 01:58
> Perhaps I'll ping one of the collaborators on Discord if I don't get a response within a couple days. [I've seen people chided for @'ing people in github messages. so I'm doing my best not to get under anyone's skin]

Correct, (please) do not do that. I'll optimistically close this and let it be reopened if needed.

**Closed by babichjacob** 2021-05-04 01:58 UTC

**Comment by deepmouse** [comment] 2021-05-10 08:59
> @deepmouse Could you check if you made your config changes as below? The ignored directory is specified as a glob. For me, it appears to have fixed the problem:
> 
> ```
> kit: {
> 		// hydrate the <div id="svelte"> element in src/app.html
> 		target: '#svelte',
> 		vite: {
> 			server: {
> 				watch: {
> 					ignored: ['**/static/**']
> 				}
> 			}
> 		}
> 	}
> ```
> 
> I believe that my previous timings and observations were side-effects of chokidar flooding the file system interface, and the syncronous nature of kit, vite, etc.

Upgraded to latest svelte-kit release and tried it, did not fix the problem. Hangs for >1min

**Comment by deepmouse** [comment] 2021-05-10 09:18
Also, to reiterate, it would be really helpful if the dev server had a `--verbose` option so I would know what it is doing that's taking so long, instead of guessing which config options to change and see if it worked.

**Comment by deepmouse** [comment] 2021-05-10 09:27
This is getting even more weird. I now moved the static assets back to the sibling repo, and this time it didn't help.. My dev server is now doing this even when the assets outside the project directory.

**Comment by deepmouse** [comment] 2021-05-10 09:55
Should I open a separate issue about the `--verbose` flag? It would really help me debug this problem.
