### ISSUE TITLE
`adapter-auto`  Default to Node.js adapter when no adapter is detected

### ISSUE THREAD

**Issue by yassinrais** [sveltejs/kit#10133] opened 2023-06-10 15:37 UTC
### Describe the problem

When setting up a SvelteKit project, if no adapter is specified, the project fails to run. It requires manual adapter configuration, which is time-consuming.

### Describe the proposed solution

Automatically default to the Node.js adapter if no adapter is detected in the SvelteKit project setup. This simplifies the setup process and allows developers to start quickly without worrying about explicit adapter configuration.

### Alternatives considered

[adapter-auto/adapters.js](https://github.com/sveltejs/kit/blob/master/packages/adapter-auto/adapters.js)

```js
// List of adapters to check for. `version` is used to pin the installed adapter version and should point
// to the latest version of the adapter that is compatible with adapter-auto's current peerDependency version of SvelteKit.
export const adapters = [
	{
		name: 'Vercel',
		test: () => !!process.env.VERCEL,
		module: '@sveltejs/adapter-vercel',
		version: '2'
	},
	{
		name: 'Cloudflare Pages',
		test: () => !!process.env.CF_PAGES,
		module: '@sveltejs/adapter-cloudflare',
		version: '2'
	},
	{
		name: 'Netlify',
		test: () => !!process.env.NETLIFY,
		module: '@sveltejs/adapter-netlify',
		version: '2'
	},
	{
		name: 'Azure Static Web Apps',
		test: () => process.env.GITHUB_ACTION_REPOSITORY === 'Azure/static-web-apps-deploy',
		module: 'svelte-adapter-azure-swa',
		version: '0.13'
	},
	{
		name: 'AWS via SST',
		test: () => !!process.env.SST,
		module: 'svelte-kit-sst',
		version: '2'
	},
	{
		name: 'Node.js',
		test: () => true,
		module: '@sveltejs/adapter-node',
		version: '2'
	}
];
```

### Importance

would make my life easier

**Comment by gtm-nayan** [comment] 2023-06-10 15:42
Duplicate of #8197

**Closed by gtm-nayan** 2023-06-10 15:42 UTC
