### ISSUE TITLE
Endpoint page with named layout doesn't render

### ISSUE THREAD

**Issue by coryvirok** [sveltejs/kit#4703] opened 2022-04-22 20:43 UTC
### Describe the bug

It appears that when an endpoint page is created, (both .js and .svelte) with a named layout, the page is never rendered and only the endpoint server response shows up in the browser.

### Reproduction

Link to repro: https://github.com/coryvirok/svelte-named-layout-bug

Steps to repro:
1. `git clone https://github.com/coryvirok/svelte-named-layout-bug.git`
2. `cd svelte-named-layout-bug && npm i`
3. `npm run dev`
4. `open http://localhost:3000/endpoints/foo`

You should see the foo@root.svelte template rendered. Instead, you see the JSON response from the endpoint.

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 206.98 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.5.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.37
    @sveltejs/kit: next => 1.0.0-next.320
    svelte: ^3.44.0 => 3.47.0
```

### Severity

serious, but I can work around it

### Additional Information

In order to get the foo@root.svelte template to render using the root layout, you need to:

1. Remove layout name from foo template: `mv foo@root.svelte foo.svelte`
2. Add a layout in `/routes/endpoints/__layout@root.svelte` with `<slot/>`

**Comment by mrkishi** [comment] 2022-04-22 21:01
Duplicate of #4647. Please note that this will be a duplicate route definition error. If you _do_ want a page endpoint for `foo@root.svelte`, it needs to be named `foo@root.js`.

**Closed by mrkishi** 2022-04-22 21:01 UTC
