### ISSUE TITLE
Need CI to check template projects

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#4938] opened 2022-05-16 03:33 UTC
### Describe the bug

I created a new project and `pnpm check` is currently failing with nine errors

### Reproduction

I chose "SvelteKit demo app" and then

1. Typescript
2. ESLint: Yes
3. Prettier: Yes
4. Playwright: Yes

If it makes a difference, I develop with pnpm.   (With pnpm v7, `pnpm init svelte` appears broken though.)

```
cd my-app
pnpm install
pnpm build
pnpm check
```

`pnpm build` is necessary to create `.svelte-kit/tsconfig.json`, which is extended by `tsconfig.json`.

### System Info

```shell
latest
```

### Severity

serious, but I can work around it

**Comment by delhanty** [comment] 2022-05-16 11:27
Note to future self when searching - also to get email updates on this PR:

The text in this PR was written by me in comment [#4805#issuecomment-1126938274](https://github.com/sveltejs/kit/issues/4805#issuecomment-1126938274), at Ben's request so "I" is actually me rather than Ben.  Also, there is another comment that I wrote that I would like to link now but, irritatingly, I can't because it's been marked as "off-topic".

**Comment by jhubbardsf** [comment] 2022-05-19 19:35
I just tried to reproduce this bug locally and couldn't. Tried with both `pnpm create` (pnpm v7.1.0) and `npm init` (npm v8.5.1). Selected demo, typescript, eslint, prettier, and playwright. Used pnpm to install, build, and check. 0 errors or warnings.

**Comment by benmccann** [comment] 2022-05-20 04:54
The errors have been fixed for new projects since this issue was filed. You can create a project from a few days ago and see the failure that was occurring with `npm init svelte@2.0.0-next.135 myapp`

I'm leaving this open since the issue is really about running these checks on the CI to prevent bad releases in the future

**Comment by jhubbardsf** [comment] 2022-05-20 05:49
Thanks for the clarification!

**Comment by LucasSegersFabro** [comment] 2022-06-15 02:52
heyy @benmccann 
could you check [this](https://github.com/sveltejs/kit/compare/master...LucasSegersFabro:chore/create-svelte-tests?expand=1) out?  

An approach to testing `create-svelte` on CI.  
we `npm install`, `npm build` and `npm check` a newly created project

upsides:
* should work on current CI (maybe I'd need some pointers to test it out)

downsides: 
* could be slow, as we install/build/check everytime
* assumes CI has npm installed

If it's all good I can work more on it (test different create configs, etc)

Thanks :)

**Comment by benmccann** [comment] 2022-06-15 11:42
This ticket is talking about running `pnpm check` (i.e. `tsc`) to prevent type errors rather than talking about running any sort of integration tests

**Comment by andyliuhaowen** [comment] 2022-06-29 07:02
I can work on this. But before I start, I just want to clarify: what kind of coverage are we targeting? Testing every binary combination of Yes/No choice during `init` obviously isn't feasible, plus we have both the skeleton and the demo app. Because the demo app is probably way more prune to those warnings, I want to test:

1. Add nothing to the demo
2. Add everything to the demo
3. Add every component by themselves to the demo
4. Plus the skeleton with everything

That gives us 1 + 2 (JSDoc + TypeScript) + 3 (ESLint, prettier, playwright) + 1 + 1 = 8 test cases. What do you think of this list?

**Comment by benmccann** [comment] 2022-06-29 15:35
We can check everything. We just need to check the files that live in these directories:
https://github.com/sveltejs/kit/tree/master/packages/create-svelte/templates
https://github.com/sveltejs/kit/tree/master/packages/create-svelte/shared

**Comment by andyliuhaowen** [comment] 2022-06-29 19:36
I'm not too familiar with how `svelte-check` work, but I think it can only check full svelte projects. Correct me if I'm wrong, I think the templates will pass those tests alright, but I don't think the "patch files" in `create-svelte/shared` will pass those tests in any meaningful way.

**Comment by benmccann** [comment] 2022-06-29 21:09
I'm not sure what "patch files" you're thinking of? It looks like there aren't any `.svelte` files in `create-svelte/shared` anyway, so we don't need to worry about that one

**Comment by andyliuhaowen** [comment] 2022-06-30 00:03
Looking more closely at the `create-svelte` code, my previous comment was wrong. I used to think the code that transforms code among TS, JS, and JS with JSDoc is under the shared folder but they turned out to live under `create-svelte/scripts/build-templates.js`. And further I realized that the TS, JS, JS with JSDoc choice is the only choice that actually impacts `.svelte` files. So to amend, we will need to check the default and skeleton template with all of the three options, giving us 6 test cases total. Does that sound right?

**Closed** 2022-07-05 21:14 UTC
Labels: bug, types / typescript, help wanted, p1-important
