### ISSUE TITLE
Multiple slots

### ISSUE THREAD

**Issue by mydracula** [sveltejs/kit#9024] opened 2023-02-13 07:27 UTC
### Describe the problem

I have such a layout， the content in the two places `header` and `main` is different，but `+layout.svelte` only supports one `< slot/>`，I'm at a loss
```
<header />
<div>common</div>
<main />
<footer>footer</footer>
```
You might say, you can create a component`Frame.svelte`
```
<header>
  <slot name="header" />
</header>
<div>common</div>
<main>
  <slot name="main" />
</main>
<footer>footer</footer>
```
Write this in `+layout.svelte`
```
<slot />
```
Write this in `+page.svelte`
```
<Frame>
  <div slot="header">this is header slot.</div>
  <div slot="main">this is main slot...</div>
</Frame>
```

Although this can be achieved, I don't want the common part to be loaded repeatedly. Maybe my common part is CSS animation, svg or even video. If you write the common part like this, it will look like the first time it is loaded. 

It's not what I want

### Describe the proposed solution

`+layout.svelte`

```
<header>
  <slot />
</header>
<div>common</div>
<main>
  <slot />
</main>
<footer>footer</footer>
```

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment] 2023-02-13 07:31
Duplicate of #627

**Closed by dummdidumm** 2023-02-13 07:31 UTC
