### ISSUE TITLE
Status code 204 is not accepted as a valid construct when throwing an error

### ISSUE THREAD

**Issue by mrbu-solutions** [sveltejs/kit#7023] opened 2022-09-25 14:53 UTC
### Describe the bug

Status code 204 is not accepted as a valid construct when throwing an error. See Reproduction section.

### Reproduction

```
import { error } from '@sveltejs/kit';

export async function load(event: ServerLoadEvent<Http.GetParams>) {

  if (context.length) {
    //
  }

 // 204 is a NO_CONTENT status and I want to throw a no content error when there is no record found
  throw error(204, 'I throw Response constructor: Invalid response status code.');
}
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 32.04 GB / 63.64 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @smui/button: ^6.1.0 => 6.1.0
    @smui/checkbox: ^6.1.0 => 6.1.0
    @smui/chips: ^6.1.0 => 6.1.0
    @smui/data-table: ^6.1.0 => 6.1.0
    @smui/icon-button: ^6.1.0 => 6.1.0
    @smui/layout-grid: ^6.1.0 => 6.1.0
    @smui/linear-progress: ^6.1.0 => 6.1.0
    @smui/tab: ^6.1.0 => 6.1.0
    @smui/tab-bar: ^6.1.0 => 6.1.0
    @sveltejs/adapter-auto: next => 1.0.0-next.71
    @sveltejs/kit: next => 1.0.0-next.464
    @typescript-eslint/eslint-plugin: ^5.27.0 => 5.36.1
    @typescript-eslint/parser: ^5.27.0 => 5.36.1
    atoa: ^1.0.0 => 1.0.0
    autoprefixer: ^10.4.8 => 10.4.8
    eslint: ^8.16.0 => 8.23.0
    eslint-config-prettier: ^8.3.0 => 8.5.0
    eslint-plugin-svelte3: ^4.0.0 => 4.0.0
    http-status-codes: ^2.2.0 => 2.2.0
    lowdb: ^3.0.0 => 3.0.0
    postcss: ^8.4.16 => 8.4.16
    prettier: ^2.6.2 => 2.7.1
    prettier-plugin-svelte: ^2.7.0 => 2.7.0
    smui-theme: ^6.1.1 => 6.1.3
    svelte: ^3.44.0 => 3.50.0
    svelte-check: ^2.7.1 => 2.9.0
    svelte-dnd-action: ^0.9.20 => 0.9.20
    svelte-forms: ^2.3.1 => 2.3.1
    svelte-preprocess: ^4.10.7 => 4.10.7
    svelte-splitpanes: ^0.7.3 => 0.7.3
    tailwindcss: ^3.1.8 => 3.1.8
    tslib: ^2.3.1 => 2.4.0
    typescript: ^4.7.4 => 4.8.2
    vite: next => 3.1.0-beta.2
```

### Severity

serious, but I can work around it

**Comment by david-plugge** [comment] 2022-09-25 21:33
Because 200-299 are success codes. You send a 204 if the request is valid and you for example saved some data to the database but don´t want to send anything back to the client.
Take a look at [this list](https://de.wikipedia.org/wiki/HTTP-Statuscode#Liste_der_HTTP-Statuscodes).
In your case it´s most likely a 404 status code.

**Comment by dummdidumm** [comment] 2022-09-26 07:12
As David points out this works as designed, therefore closing

**Comment by yousufiqbal** [comment] 2022-09-26 07:12
Status code of 2xx are for success. 3xx for redirections, 4xx for client errors, 5xx for server errors. Plz use 4xx codes.

**Closed by dummdidumm** 2022-09-26 07:12 UTC
