### ISSUE TITLE
Append Page title to +page.svelte  because +page.svelte is confusing 

### ISSUE THREAD

**Issue by CordialGit** [sveltejs/kit#12468] opened 2024-07-13 05:17 UTC
### Describe the problem

SvelteKit is a Directory based file routing system.

We use the +page.svelte to signify that.

But in time, it gets confusing to identify which +page.svelte file is doing what, if we have many sub routes.

Suppose I have Home Page, Contact Page, About Page, Form Page, All Users Page, Posts Page, and so on.

It gets quite confusing with all the sub +page.svelte files opened in VS Code at the same time.

FEATURE REQUEST

It should be done in such a way that the route name is appended to the +page.svelte file, for the sake of developer experience--  so that at development stage, the developer is able to identify which +page.svelte file is which, if they are all opened in tabs at the same time in VS Code.

So I should be able to have something like:

-- Home+page.svelte

--Contact+page.svelte

-- About+page.svelte

--Form+page.svelte

--Posts+page.svelte

The Page name, appended to +page.svelte, will help me identify which +page.svelte file is opened.

Can this request be considered, for the sake of good Developer Experience?? 

Regards.

### Describe the proposed solution

The Page name should be appended to the +page.svelte file extension.

### Alternatives considered

There are no alternatives because this is something that would have to come from the Svelte Core.

### Importance

would make my life easier

**Comment by James3UK** [comment] 2024-07-13 07:01
Duplicate of #10331

**Closed** 2024-07-13 08:28 UTC
