### ISSUE TITLE
[@adapter-static] In dev: Setting ssr: false doesn't render pages

### ISSUE THREAD

**Issue by omar2205** [sveltejs/kit#3101] opened 2021-12-24 04:36 UTC
### Describe the bug

Creating `test.svelte`, and setting `ssr: false` doesn't render test.svelte in dev

### Reproduction

1. npm init svelte@next my-app
2. cd my-app
3. npm install
4. npm i -D @sveltejs/adapter-static@next
4. update svelte.config.js to use @sveltejs/adapter-static
5. npm run dev

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 4.59 GB / 7.77 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    npm: 8.1.2 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.4
    @sveltejs/adapter-static: ^1.0.0-next.22 => 1.0.0-next.22
    @sveltejs/kit: next => 1.0.0-next.202
    svelte: ^3.44.0 => 3.44.3
```

### Severity

blocking an upgrade

**Comment by omar2205** [comment] 2021-12-24 06:26
* for **1** you don't even need to use `adapter-static`

**Comment by ignatiusmb** [comment] 2021-12-24 07:26
There is no correlation between dev mode and adapter used, setting `ssr: true` in the config properly render any pages defined in routes. There's no creating `test.svelte` in your reproduction, hence why it doesn't render. Closing as there is no issue.

**Closed by ignatiusmb** 2021-12-24 07:26 UTC

**Comment by omar2205** [comment] 2021-12-24 07:32
I forgot to add it to the reproduction list, but when running npm run dev, navigating to /test result in 404 not found.

**Comment by ignatiusmb** [comment] 2021-12-24 07:45
Tried that as well, works properly on my end. Please provide a minimal reproducible example that we can clone instead so the problem is contained.

**Comment by omar2205** [comment] 2021-12-24 07:58
https://github.com/omar2205/static-ssr-off
A codesandbox: https://codesandbox.io/s/misty-tdd-r3lsg
visiting https://r3lsg.sse.codesandbox.io/dev results in a 404

**Comment by omar2205** [comment] 2021-12-24 08:46
I tried running on a different machine, it worked correctly, i.e., test page rendered. 

Is there a way to debug this further? On why this isn't working on my main machine? I've removed the whole dir and redid the whole thing with the same problem.
