### ISSUE TITLE
[feat] helper for creating stores

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#7105] opened 2022-10-01 03:01 UTC
### Describe the problem

You can't just blindly create a store in SSR or it'll end up being a global store shared by all users (https://github.com/sveltejs/kit/discussions/4339). We should provide a helper that ties it to the request.

### Describe the proposed solution

At the very least we can make it part of the Svelte context. SvelteKit does this internally with its own stores.

I wonder if we couldn't make it available earlier. If we only make it part of the Svelte context then you can't use it in `load`. If we additionally tied it to the request it would be available throughout the rendering of the request.

We could have an API like:
```
export const getStore = function(key, request) {
  return request ? WEAK_MAP.get(request).get(key) : getContext(key);
};
```

When we're going to start rendering the templates we could populate the context from the map.

We could also have a method to create a store. Being able to call it in `handle` would solve https://github.com/sveltejs/kit/issues/7107:
```
createStore(request, 'whatever', request.locals.whatever);
```

There are a couple things we might make optional. E.g. we could potentially look for `'whatever'` in `locals` automatically. Or we could make the request optional - if it's not provided the store would only be available in the template (at least on the server).

### Alternatives considered

The user could create the store themselves if we just want it available in the template. That starts getting cumbersome if they want it available either as a singleton in the browser or tied to the request on the server. It's impossible if they want to populate it from `locals`

Some of the APIs I've proposed here may be open for debate on the actual details

### Importance

would make my life easier

**Comment by williamviktorsson** [comment] 2022-10-01 05:34
Great idea. Would it make sense to provide different options of how and when the store should be created and populated. Such as ”once on first page load” or ”for every page load” or 

I Imagine this might be useful for the large amount of people who enjoy integrating client side stores with responsive backend functionality such as firebase authentication / snapshot listeners.

Not sure what it would look like though or if it makes sense, or if these types of behaviors would have to be solved by each developer.

**Comment by dummdidumm** [comment] 2022-10-02 07:53
The idea sounds good, I'm not fully sure on the details yet. I think this only makes sense in the context of the shared load function, so it runs on the server on first render and is updated within the client afterwards. So locals would be the shared thing on the server and this would be the shared thing in the shared load (basically the same split as with session previously). Also, is `handle` the best place for this? `handle` runs for _every_ request, but this would only be available inside the shared load function. Something like `getSession` makes more sense to me.

Another thing I'm not sure about is if this should be reserved for stores only, or if you could place arbitrary things in there. You could place arbitrary things _inside_ stores though, and having it a non-store only makes sense for things that never update, which shouldn't live inside this anyway - so, probably fine?

**Comment by PatrickG** [comment] 2022-10-02 09:28
Instead of `createStore(request, 'whatever', request.locals.whatever);` I think it would make more sense to add or set a store to the request.
Something like:
```ts
import type { Readable } from 'svelte/store';
function set/addStore<T extends Readable = Readable>(key: any; store: T): void;
function getStore<T extends Readable = Readable>(key: any): T;
```

**Comment by david-plugge** [comment] 2022-10-05 11:09
If it´s just about using something shorter than `$page.data.user` this helper can be used:

```ts
import type { Page } from '@sveltejs/kit';
import { browser } from '$app/environment';
import { page } from '$app/stores';
import { derived, type Readable } from 'svelte/store';

function derivedFromPage<T>(fn: (page: Page) => T): Readable<T> {
	let store: Readable<T>;

	return {
		subscribe(run, invalidate?) {
			if (!browser || !store) store = derived(page, fn);
			return store.subscribe(run, invalidate);
		}
	};
}

export const user = derivedFromPage<{ name: string }>(($page) => $page.data.user);
```

**Comment by dummdidumm** [comment] 2022-10-11 18:49
Copying my Discord-thoughts into here:

What became clear to me that getSession was used for multiple things at once.

1. pass data from server to client load functions
2. make cross-cutting data easily available across all client load functions
3. trigger a load function to rerun when data changes (e.g. $session.user = null)
4. a convenient writable store that is somewhat global

Because it had so many use cases in once, it became somewhat confusing what runs when, because people may only think about 4 and then wonder about 3. So I think removing it in its form was correct, but we need some features that bring back the mentioned points in a easy-to-use way. Right now we have this situation:
1. pass data ->  can do this now by having a +layout.server.js and passing whatever you want to the client
2. cross-cutting data -> use await parent() -> this introduces a waterfall because you can't tell "hey I'm only interested in the data from parent X, don't wait on the 3 other layout loads after that". Something like locals for the client side would help with this.
3. trigger rerun -> there's nothing built-in for this right now. Rich shared a pattern somewhere about creating a custom state which triggers a unique invalidate function under the hood. Maybe it's enough to make this a blessed pattern and/or tidy it up a little and provide a wrapper around it.
4. convenient writable store -> again, nothing built-in, this would be this issue
3+4. It's not clear to me how to achieve a combination of these two in a nice API. session made it possible because it was on both sides.

--> I feel like we need to add recipes and/or APIs to ease this

**Comment by david-plugge** [comment] 2022-10-18 20:38
An issue i´ve run into a few times now is not beeing able to update `$page.data` client side.

Example:

You display some database rows in your app and add another row.
You call `fetch` and post the data to a `+server` endpoint or make use of the form actions.
The only option (that i know of) to get the added row is to call `invalidate` and reload **all** page related data.
This will obviously result in twice the network calls compared to just adding the newly created data to `$page.data`.

One way i´ve solved this:
```ts
import { invalid } from '@sveltejs/kit';
import type { PageServerLoad, Actions } from './$types';

export const load: PageServerLoad = async () => {
	return {
		// just some random test data
		posts: [{ title: 'Post 1' }, { title: 'Post 2' }, { title: 'Post 3' }]
	};
};

export const actions: Actions = {
	async addPost({ request }) {
		const data = await request.formData();
		const title = data.get('title') as string;

		if (!title) {
			return invalid(400, {
				titleMissing: true
			});
		}
		return {
			newPost: { title }
		};
	}
};
```
make it a store in `+page.ts`
```ts
export const load: PageLoad = ({ data }) => {
	return {
		posts: writable(data.posts)
	}
}
```
and update that store inside `+page.svelte`
```html
<script lang="ts">
	import { applyAction, enhance, type SubmitFunction } from '$app/forms';
	import type { PageData, ActionData } from './$types';

	export let form: ActionData;
	export let data: PageData;

	$: posts = data.posts;

	const handleAddPost: SubmitFunction<{ newPost: { title: string } }> =
		() =>
		async ({ result, update }) => {
			if (result.type === 'success') {
				await applyAction(result);

				posts.update(($posts) => {
					$posts.push(result.data!.newPost);
					return $posts;
				});
				return;
			}
			update();
		};
</script>

<ul>
	{#each $posts as item}
		<li>{item.title}</li>
	{/each}
</ul>

<form action="?/addPost" method="post" use:enhance={handleAddPost}>
	{#if form?.titleMissing}
		<p class="error">Please enter a title</p>
	{/if}
	<input name="title" type="text" placeholder="Title" />
	<button type="submit">Submit</button>
</form>
```

I´m just curious if this api/helper, if it´s going to be a thing, will provide an easier way to get writable stores from the client to the server in such use cases.

**Comment by Rich-Harris** [comment] 2022-11-07 16:20
One of the lessons of `session` was that stores as _inputs_ to `load` is problematic. But we can _return_ stores from `load`:

```js
// src/routes/+layout.js
export function load() {
  return {
    count: writable(0)
  };
}
```

```svelte
<!-- src/routes/+page.svelte -->
<script>
  import { page } from '$app/stores';

  $: count = $page.data.count;
</script>

<button on:click={() => $count += 1}>clicks: {$count}</button>
```

We can use this pattern for user-specific data, for app-wide data, and so on. It's easy to vary the type of store based on whether we're in a server or browser environment (e.g. get a snapshot of chat messages on the server, upgrade to a real time subscription in the client, etc).

Is there anything that isn't covered by this pattern, especially that needs to be resolved before 1.0?

**Comment by david-plugge** [comment] 2022-11-07 20:23
I think this pattern is very powerful and covers most if not all use cases i can think of.
We just need some examples that make clear how and when to use this.

**Comment by Tal500** [comment] 2022-11-08 13:05
> One of the lessons of `session` was that stores as _inputs_ to `load` is problematic. But we can _return_ stores from `load`:
> 
> ```js
> // src/routes/+layout.js
> export function load() {
>   return {
>     count: writable(0)
>   };
> }
> ```
> 
> ```svelte
> 
> <script>
>   import { page } from '$app/stores';
> 
>   $: count = $page.data.count;
> </script>
> 
> <button on:click={() => $count += 1}>clicks: {$count}</button>
> ```
> 
> We can use this pattern for user-specific data, for app-wide data, and so on. It's easy to vary the type of store based on whether we're in a server or browser environment (e.g. get a snapshot of chat messages on the server, upgrade to a real time subscription in the client, etc).
> 
> Is there anything that isn't covered by this pattern, especially that needs to be resolved before 1.0?

A problem with this design is that you assume the root layout to never get invalidated? (since invalidating calls the `load` function again. E.g. with `invalidateAll()`).

You might suggest the following hack: Since invalidating happens only on the browser and never on the server, you may use a global singelton on the browser for the specific store, and on the server just do what you suggested now.

But I think that the request might be deeper in some sense. I think that the core missing feature is to have global request context shared:
* On the server, from the begging of the request until the the end of the response computation.
* On the browser, from the initialization until infinity.

By design, this "shared context" is only a memory allocation in some sense(or a whiteboard you write stuff on), it shares no information between the server and the browser, for simplicity.

**Comment by dummdidumm** [comment] 2022-11-08 13:15
The counter example is perhaps a bit misleading; you'd use that when you have something where the server is the source of truth, and for things like optimistic UI etc you'd update it so you don't have to trigger a load again - but if it is triggered, the value would still be correct.

That said, some way of hooking into "scoped to context on the server, global on the client" like the built-in stores could still be valuable in some contexts - but we need to see more real use cases which are not (or only weirdly) solveable with the existing solutions already.

**Comment by david-plugge** [comment] 2022-11-08 13:36
Regarding the `context`, i remember back in the days of sapper there was  a request about a function that gives you access to the load parameters. I´ve been playing around with `node:async_hooks` (nextjs uses that for some context stuff aswell) which works on the server, but i don´t think there is anything like that for the browser. But as already suggested we can easily make it global there.

This is what i´ve tried :
```ts
// src/hooks.server.ts
import { setRequestContext } from 'my-lib';

export const handle = ({ resolve, event }) => {
	return runWithRequestContext(event, () => resolve(event));
}

// src/lib/api.ts
import { getLoadContext } from 'my-lib';

export function post() {
	const { fetch } = getRequestContext();
	return fetch(...);
}

// src/routes/+page.ts
export const load = async () => {
	const data = await post();
}
```
This work pretty well with some dynamic imports so we only use the context when on the server. However, i can´t access the event on the client, therefore i cannot make use of the custom fetch that reuses the initial data from the server.
If there was something like `handle` for the client the event could be stored in a global store.

Curious if this is a pattern that would fit into the sveltekit stack.

**Comment by dummdidumm** [comment] 2022-11-08 13:43
From the code snippet I don't understand how this would prevent simultaneous but separate requests from interfering with each other.

**Comment by david-plugge** [comment] 2022-11-08 15:24
> From the code snippet I don't understand how this would prevent simultaneous but separate requests from interfering with each other.

The [`AsyncLocalStorage`](https://nodejs.org/api/async_context.html#class-asynclocalstorage) class exported from `node:async_hooks` makes it possible to hook into the context of javascript functions.

```ts
import type { RequestEvent } from '@sveltejs/kit';
import { AsyncLocalStorage } from 'node:async_hooks';

export const requestContext = new AsyncLocalStorage<RequestEvent>();

export const handle = ({ event, resolve }) => {
	return requestContext.run(event, () => resolve(event));
};

export const load = async () => {
	const eventFromContext = requestContext.getStore();

	console.log(eventFromContext);
};
```
It basicly works like svelte context.

**Comment by Conduitry** [comment] 2022-11-08 16:21
`async_hooks` is a Node-only thing. We can't rely on it being there for in all production environments. I don't know whether our other current adapter targets automatically split out global variables per request. But even if they did, it probably wouldn't be a good idea to assume that every environment someone wants to deploy to will support either a `AsyncLocalStorage`-like feature or will automatically have separate global variables per each request.

**Comment by david-plugge** [comment] 2022-11-08 16:55
Yeah that´s what i expected, very unfortunate. So i guess i can completely get rid of the context idea?

**Comment by Rich-Harris** [comment] 2022-11-08 17:37
> A problem with this design is that you assume the root layout to never get invalidated? (since invalidating calls the `load` function again. E.g. with `invalidateAll()`).

If the root layout gets invalidated, you have a choice — return a fresh store (with data from the server, if appropriate), or (if you're in the browser) return the existing one:

```js
// src/routes/+layout.js
import { browser } from '$app/environment';
import { writable } from 'svelte/store';

let store;

export function load() {
  return {
    count: browser ? (store || (store = writable(0))) : writable(0)
  };
}
```

That could be abstracted into a helper if you wanted:

```js
// src/lib/cache.js
import { browser } from '$app/environment';

const cache = new Map();

export function createCachedValue(key, fn) {
  if (cache.has(key)) return cache.get(key);
  const value = fn();
  if (browser) cache.set(key, value);
  return value;
}
```

```js
// src/routes/+layout.js
import { createCachedValue } from '$lib/cache';
import { writable } from 'svelte/store';

export function load() {
  return {
    count: createCachedValue('count', () => writable(0))
  };
}
```

I'll close this issue as I think returning stores from `load` basically covers all the bases. If we need to add helpers or document these patterns in future then we can, but for now I don't think there's anything we need to do

**Closed by Rich-Harris** 2022-11-08 17:37 UTC
Labels: enhancement

**Comment by brendanmatkin** [comment] 2023-03-30 00:51
Hey I know this is closed but I'm having a hard time finding a better place - I'd just like to add that it _seems_ like returning stores from load is exactly what I needed but that is still not very clear in the "State Management" section of the docs. @dummdidumm - assuming that it was you who wrote that section, is this intentional? Is there another discussion that found using context only is the way to go?

`svelte/store` is such a core part of what makes svelte awesome and it has been really difficult to understand how to replace it in sveltekit in a secure way - _easily_ the hardest part of moving from vanilla svelte to sveltekit. Searching for other answers usually suggests to either use the now removed session, or like 50 lines of boilerplate across multiple files (exaggerating a bit but that's how it feels compared to the vanilla `$storeVariable = "I love this"`), so it seems I'm not the only one confused.

Maybe I'm actually just over-using stores and this is more by design but I think I'm not. 

If it's just a question of updating the docs I'd be up for contributing, but want to make sure I understand it before I try!

**Comment by brendanmatkin** [comment] 2023-05-08 20:43
I wrote an article that clarifies why I still think this problem isn't totally solved and maybe how the docs can be clarified. Take a look if you are interested! https://dev.to/brendanmatkin/safe-sveltekit-stores-for-ssr-5a0h
