### ISSUE TITLE
+error.svelte isn't utilized when in layout group

### ISSUE THREAD

**Issue by ttofis** [sveltejs/kit#9113] opened 2023-02-18 17:03 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/8685248/219878143-634877b8-8875-4977-a94d-6e8bab9301d8.png)
In a formation like that, the root directory of the webpage will follow +page.svelte that exists in the (design) directory, but an error will fail to detect +error.svelte in that same directory and will display the generic one.
Curiously so, even if the error is happening in a subdirectory of (design) like posts, it will still fail to detect (design)/+error.svelte and display that.

### Reproduction

[Stackblitz test](https://stackblitz.com/edit/sveltejs-kit-template-default-m5z9bl?file=src/routes/(a)/+error.svelte)

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 6.27 GB / 7.70 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 19.6.1 - ~/.nvm/versions/node/v19.6.1/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v19.6.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.91 
    @sveltejs/adapter-netlify: ^1.0.0-next.64 => 1.0.5 
    @sveltejs/kit: next => 1.7.1 
    svelte: ^3.44.0 => 3.55.1
```

### Severity

blocking an upgrade

### Additional Information

I cannot utilize advanced layouts with groups while still having my error page designed with one of them because of this.

**Comment by dummdidumm** [comment] 2023-02-20 14:08
In your reproduction there's a link to a page that does not exist, resulting in a 404. A 404 error will always invoke the root `+error.svelte`. The question now is whether or not it's expected that the `(a)/+error.svelte` file isn't used. I'd say it's expected because
- You can _also_ have a `+error.svelte` at the root in this situation
- SvelteKit can't know whether or not the route in question would lead down the `(b)` or `(b)` path, so it needs the common ancestor, and that's only the `src/routes/+error.svelte` file

Therefore closing as "works as designed".

**Closed by dummdidumm** 2023-02-20 14:08 UTC

**Comment by ttofis** [comment] 2023-02-20 14:14
Hello @dummdidumm, the issue wasw opened precisely for the question that you posed, and the repoduction was to show the issue I believe there is. So yes, I knowingly redirect you to a page that does not exist.

I don't think it works as designed, and please let me explain why.
Just like with a root +page.svelte inside a (a) path will be treated as the root page (explained here https://kit.svelte.dev/docs/advanced-routing#advanced-layouts ), I believe that the +error.svelte should also have the same treatment.
Why having a +error.svelte at my root would not be a good solution has to do with design. I believe that since we have a system to have advanced layouts, I should also be able to utilize a layout for my error page and not have to repeat all of my layout properties to it. That's just useless code repetion.

I hope I have made my question/issue clearer.

**Comment by dummdidumm** [comment] 2023-02-20 15:27
There can be only one `+page.svelte` pointing to a specific URL across groups, but there can be multiple `+layout.svelte` and `+error.svelte` files across groups. What you propose would mean that we would have to make the same "there can only be one `+error.svelte` across groups" restriction, which is a breaking change. It is also incorrect if your error is coming from within another group: you wouldn't want to show `(b)/+error.svelte` if the error happened within the `(a)/..` tree. The 404 case is a special case because it happened from no tree at all, but even then there's no way for the 404 page to decide which of the groups it should look into to use a `+error.svelte` (should it pick the first it sees? etc).

In your case that might mean some repetition but I'm sure it can be diminished through reusable components.

**Comment by ttofis** [comment] 2023-02-20 15:39
Ok those are very valid points and thank you for following up on this.
I have updated this Stackblitz test [here](https://stackblitz.com/edit/sveltejs-kit-template-default-m5z9bl?file=src/routes/(a)/about/+page.svelte) though to show something else. You say we can have multiple +error.svelte in the layout groups. All right, so, when you enter the about page which is under the about dictory (so clearly below the a layout group), and then click the link for the 404 I've set up which redirects you to /about/test, that should've given you the (a)/+error.svelte right? But it doesn't.
I realize this can be because Sveltekit cannot know if /about/test would've been inside (a) or no, but still that kinda makes error pages in root folders of layout groups not respond like you would expect, essentially requiring you to make a new error file in the root folder.

Thanks again!

**Comment by dummdidumm** [comment] 2023-02-22 09:33
404 is a special case, because there's no routing tree to walk up and find the nearest error boundary, which is why it always uses the root error page. Walking up from the last tree before the link is clicked would lead to inconsistent results - if you visit the 404 page directly it would be a different error page than if you click on a link from within the app.
If you would have an error inside a load function inside `(a)/something`, it would use `(a)/+error.svelte` because there's a routing tree now that can be walked up.

**Comment by ttofis** [comment] 2023-02-22 12:28
Ah thank you, got it now. Thanks for clarifying it to me!
