### ISSUE TITLE
Possibility to create a script per component

### ISSUE THREAD

**Issue by Hattorius** [sveltejs/kit#9679] opened 2023-04-16 10:30 UTC
### Describe the problem

Whenever you create a `+page.svelte` file, you can create a `+page.server.js` or `+page.js` in the same directory to make a script run on the client or server when rendering the page. There is (for as far as I know) no such thing for components. If you create a component, let's say `Header.svelte` you'll need to make a file called `/api/header/+server.js`, and handle an API request there and give information to the Header through there.
OR you'll need to create a `+page.server.js` for every route that implements the `Header` component, and send the dynamic information in the header from the `+page.svelte` to the component.

### Describe the proposed solution

The possibility to create (server side) scripts per component. So next to `Header.svelte` being able to create a `Header.js` or `Header.server.js`. I could imagine a project directory looking like this then:
```
├── src
│   ├── components
│   │   ├── Header
│   │   │   ├── Header.svelte
│   │   │   └── Header.server.js
│   │   ├── Button.svelte
│   │   └── CTA.svelte
│   ├── routes
│   │   ├── +page.svelte
│   │   │   ├── user
│   │   │   │   ├── +page.svelte
│   │   │   │   └── +page.js
│   └── app.html
```
Something like that. When there is a `Header.js` or `Header.server.js` in the same directory as a `Header.svelte` (or any other component name), it should handle it as `+page.js` or `page.server.js` being in the same directory as `+page.svelte`

### Alternatives considered

As written at describe the problem, till now I've made separate API endpoints per component which kinds of makes a mess, you don't have a full overview of which component uses which endpoint anymore. The other way around is making a `+page.server.js` for each page that uses the component and run the server sided things there, in order to follow the DRY principle you'll need need to create a function somewhere and call that function from every server sided script. In which case you also lose overview.

### Importance

would make my life easier

**Comment by gtm-nayan** [comment] 2023-04-16 11:49
Duplicate of #9527

**Closed by gtm-nayan** 2023-04-16 11:49 UTC
