### ISSUE TITLE
ESLint v9 config type error

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#12109] opened 2024-04-12 01:44 UTC
### Describe the bug

- https://github.com/sveltejs/kit/pull/12268
- https://github.com/sveltejs/kit/pull/12089

<img width="1112" alt="image" src="https://github.com/sveltejs/kit/assets/47051820/900bac44-855e-407b-ba93-50104e8961de">

```
Type '({ readonly rules: Readonly<RulesRecord>; } | { plugins: { readonly svelte: Plugin; }; files?: undefined; languageOptions?: undefined; rules?: undefined; processor?: undefined; } | ... 4 more ... | Config)[]' is not assignable to type 'FlatConfig<RulesRecord>[]'.
  Type '{ readonly rules: Readonly<RulesRecord>; } | { plugins: { readonly svelte: Plugin; }; files?: undefined; languageOptions?: undefined; rules?: undefined; processor?: undefined; } | ... 4 more ... | Config' is not assignable to type 'FlatConfig<RulesRecord>'.
    Type '{ files: string[]; languageOptions: { parser: any; }; rules: { 'no-inner-declarations': string; 'no-self-assign': string; 'svelte/comment-directive': string; 'svelte/system': string; }; processor: string; plugins?: undefined; }' is not assignable to type 'FlatConfig<RulesRecord>'.
      The types of 'rules['svelte/comment-directive']' are incompatible between these types.
        Type 'string' is not assignable to type 'RuleEntry<SvelteCommentDirective> | undefined'.ts(2322)
```

### Reproduction

```shell
pnpm create svelte@latest

# create-svelte version 6.1.0
# 
# ┌  Welcome to SvelteKit!
# │
# ◇  Where should we create your project?
# │  - create-svelte@6.1.0
# │
# ◇  Which Svelte app template?
# │  - Skeleton project
# │
# ◇  Add type checking with TypeScript?
# │  - Yes, using TypeScript syntax
# │
# ◇  Select additional options (use arrow keys/space bar)
# │  - Add ESLint for code linting, Add Prettier for code formatting
# │
# └  Your project is ready!
```

### System Info

```Shell
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 178.81 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.12.2 - ~/.volta/tools/image/node/20.12.2/bin/node
  npm: 10.5.0 - ~/.volta/tools/image/node/20.12.2/bin/npm
  pnpm: 8.15.6 - ~/.volta/bin/pnpm
Browsers:
  Chrome: 123.0.6312.122
  Edge: 123.0.2420.81
  Safari: 17.4.1
npmPackages:
  @sveltejs/adapter-auto: ^3.0.0 => 3.2.0 
  @sveltejs/kit: ^2.0.0 => 2.5.5 
  @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.0 
  svelte: ^4.2.7 => 4.2.13 
  vite: ^5.0.3 => 5.2.8
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment] 2024-04-12 15:29
This seems like something that would have to be fixed on the eslint side. It's probably best to file an issue there about it

**Comment by benmccann** [comment] 2024-05-30 03:14
It looks like `@types/eslint-config-prettier` needs to be installed

I only get all those red squiggles if installing `@types/eslint__js`. By default it just says the types for `@eslint/js` are missing, which is a bit better

**Comment by hyunbinseo** [comment] 2024-05-30 04:29
I can confirm. Recreating a new project, I get the following errors:

> Could not find a declaration file for module '@eslint/js'. 
> Could not find a declaration file for module 'eslint-config-prettier'.

I still can't get remove the squiggles on an existing project that was upgraded.

It seems to be importing the correct type definition from the identical file.

<img width="650" alt="image" src="https://github.com/sveltejs/kit/assets/47051820/2a872f50-d0bb-470d-9cac-8b4a3f28f48d">

`@types/eslint__js` is not installed in this pnpm workspace.

**Comment by hyunbinseo** [comment] 2024-06-02 10:19
@benmccann The out-of-the box SvelteKit template gives squiggles. Can you check again?

Here is the full reproduction video. Happens on both `pnpm` and `npm`.

https://github.com/sveltejs/kit/assets/47051820/23e35703-a14d-4397-b5ad-df3df52dbe49

**Comment by benmccann** [comment] 2024-06-02 16:42
Well either way it seems like the issue is that the types upstream need to be updated. There's not much we can do about it here until then. You could try filing an issue upstream

**Closed** 2024-07-24 17:26 UTC
Labels: pkg:create-svelte, blocked by upstream
