### ISSUE TITLE
Error while trying to sync SvelteKit config on Netlify due to `sharp`

### ISSUE THREAD

**Issue by mcmxcdev** [sveltejs/kit#7430] opened 2022-10-29 08:57 UTC
### Describe the bug

I am trying for a while to get my Sveltekit project up-to-date again and always seem to be failing at another end.

The project is using `svimg` which depends on `sharp` and the issue only occurs on Netlify on the `svelte-kit sync` command it seems.

I have tried to remove `node_modules` and lockfile and reinstall, but doesnt fix it.
I have tried to install `sharp` as `devDependency` but doesn't fix it as well.

![Screenshot from 2022-10-29 10-51-16](https://user-images.githubusercontent.com/16797721/198822741-4ff733f6-a93f-48b7-a543-555b5a2982fe.png)

### Reproduction

-

### System Info

```Shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Memory: 9.33 GB / 15.61 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.volta/tools/image/node/16.17.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.16.0 - ~/.volta/tools/image/npm/8.16.0/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Firefox: 105.0.3
  npmPackages:
    @sveltejs/adapter-netlify: 1.0.0-next.82 => 1.0.0-next.82 
    @sveltejs/kit: 1.0.0-next.528 => 1.0.0-next.528 
    svelte: 3.52.0 => 3.52.0 
    vite: ^3.2.1 => 3.2.1
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment] 2022-10-29 21:51
I'm using `vite-imagetools` which uses Sharp and am deploying to Netlify and not encountering any issues. Maybe you'd have better luck with it? I documented my setup here: https://github.com/sveltejs/kit/issues/241#issuecomment-1274046866

**Comment by benmccann** [comment] 2022-11-08 20:58
I'm going to close this since no reproduction was provided. If you're able to put together a reproduction then we can reopen this

**Closed by benmccann** 2022-11-08 20:58 UTC

**Comment by mcmxcdev** [comment] 2022-11-09 18:54
I haven't had time yet to work on the project again and switch over to `vite-imagetools`, but I assume that will be the workaround to go with for now. 

Ideally, SvelteKit will offer a solution for image processing at some point like planned.
