### ISSUE TITLE
+server.js : "Content-Type: text/css" header set to "Content-Type: text/plain" in production, using Netlify-Adapter 

### ISSUE THREAD

**Issue by jymma** [sveltejs/kit#6412] opened 2022-08-30 00:54 UTC
### Describe the bug

In a `+server.js` file :

```
export async function GET() {
  return new Response(
   'body { background-color: green; }', 
   {
      headers: {
        'Content-Type': 'text/css'
      },
    }
  )
}
```
The "`Content-Type: text/css`" header seems to be changed to "`Content-type: text/plain`" in production, using Netlify-Adapter. (but it works in development mode)

### Reproduction

`git clone git@bitbucket.org:jymail/sveltekit-rendering-css.git`

### Logs

```shell
Response Headers :
  accept-ranges: bytes
  age: 19
  cache-control: public, max-age=0, must-revalidate
  content-length: 294
  content-type: text/plain; charset=UTF-8
  server: Netlify
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  ...
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 135.44 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.69 
    @sveltejs/adapter-netlify: ^1.0.0-next.75 => 1.0.0-next.75 
    @sveltejs/kit: next => 1.0.0-next.449 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment] 2022-08-30 03:15
It would be interesting to know if this also happens with `adapter-node` or is specific to `adapter-netlify`

**Comment by jymma** [comment] 2022-08-30 15:12
It seems it works in production, with `adapter-node`
See here (if _render.io_ wants to work well ;-) ) : [https://sveltekit-rendering-css.onrender.com/css](https://sveltekit-rendering-css.onrender.com/css)

**Comment by jymma** [comment] 2022-08-30 15:15
Here is the repo : [https://github.com/jymma/sveltekit-rendering-css.git](https://github.com/jymma/sveltekit-rendering-css.git)

**Comment by Nickersoft** [comment] 2022-09-24 00:36
Interestingly, I just encountered a similar issue when querying my GraphQL endpoint from a load function: I had URQL using SvelteKit's server-side `fetch` function, and randomly it started returning a content type of `text/plain` for my queries, which URQL understood as an error and crashed my app. All GQL queries are expected to be `application/json`. Running the same queries on the client side doesn't result in this issue, so I think it may be an issue with how Svelte's fetch works.

**Comment by eikaramba** [comment] 2022-09-29 21:46
this! I also experienced that my API calls from withing my load functions are not working anymore because i am checking the header and do `req.json()` resp. `req.text()` depending on the header. however all requests now return text/plain and thus i never get json back from the request. This is only happening on the Server side however during SSR, on the client the load function works. i am using the fetch method from the load function.

**Comment by eikaramba** [comment] 2022-10-01 22:48
i created its own issue for that https://github.com/sveltejs/kit/issues/7112

**Comment by dummdidumm** [comment] 2023-01-11 10:09
No longer reproducible given the repository, therefore closing.

**Closed by dummdidumm** 2023-01-11 10:09 UTC
Labels: bug, pkg:adapter-netlify
