### ISSUE TITLE
Files in static cannot be accessible in both local development server and production when paths.base and paths.assets are set

### ISSUE THREAD

**Issue by ghing** [sveltejs/kit#2282] opened 2021-08-25 02:32 UTC
### Describe the bug

When running the local development server, it appears that files in `static` are served from the root of the server. When building a static site using the static adapter, files in `static` get copied to the build directory. These differing behaviors make it impossible to reference files in the `static` directory in HTML templates in such a way that they will be accessible in both the local development server and production.

Consider this HTML inside `src/routes/index.svelte`:

```
<svelte:head>
	<style>
		/* Typography */

		@font-face {
			font-family: 'roboto';
			src: url('./fonts/roboto-v27-latin-regular.woff2') format('woff2');
		}

    p {
      font-family: 'roboto';
    }
  </style>
</svelte:head>  
```

When `paths.base` and `paths.assets` are configured and the app is baked to a static site using the static adapter, this HTML will work because the file `fonts/roboto-v27-latin-regular.woff2` is copied alongside the generated `index.html`.

However, this won't work in the local development server, because the font file is served from the root, i.e. http://localhost:3000/fonts/roboto-v27-latin-regular.woff2.

For the font file to be accessible in the local development version, one would have to use this HTML:

```
<svelte:head>
	<style>
		/* Typography */

		@font-face {
			font-family: 'roboto';
			src: url('/fonts/roboto-v27-latin-regular.woff2') format('woff2');
		}

    p {
      font-family: 'roboto';
    }
  </style>
</svelte:head>  
```

However, this will break in the production static site because the font file isn't deployed to the root of the webserver, it will be in a subdirectory, as configured by `paths.base` and `paths.assets`. 

This is only a problem when serving the static site from a subdirectory.

So, there is no way to reference files in `static` in such a way that they are accessible in both the local development server and production.

It's possible that this is related to https://github.com/sveltejs/kit/issues/1154.

### Reproduction

https://github.com/ghing/sveltekit-bug-repro is a simple project, created with `npm init svelte@next ...`. It has example HTML that references files in `static` and a configuration of `paths.base` and `paths.asset` that lead to the problem described in the "Describe the bug" section. Page can be viewed at http://localhost:3000/some-prefix/

### Logs

```shell
roboto-v27-latin-regular.woff2:1 Failed to load resource: the server responded with a status of 404 (Not Found)
client.ts:22 [vite] connecting...
client.ts:52 [vite] connected.
index.mjs:1983 <Routes> received an unexpected slot "default".
validate_slots @ index.mjs:1983
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 159.75 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nodenv/versions/14.16.1/bin/node
    npm: 6.14.12 - ~/.nodenv/versions/14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.17 => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.156
    svelte: ^3.34.0 => 3.42.3
```

### Severity

serious, but I can work around it

**Comment by ghing** [comment] 2021-09-11 14:24
@ArrowBaZ, unfortunately, my workaround isn’t great. I just pushed my font files to a central place, outside of this SvelteKit project, essentially like a self-hosted CDN, and referenced them with a full URL in the CSS.

**Comment by tv42** [comment] 2021-11-18 22:50
Isn't this what `$app/paths` `assets` is for?

https://kit.svelte.dev/docs#modules-$app-paths

**Comment by ghing** [comment] 2021-11-19 18:17
> Isn't this what `$app/paths` `assets` is for?
> 
> https://kit.svelte.dev/docs#modules-$app-paths

Let me try this and see if this addresses the issue. It's been a while since I ran into this, so I can't remember if I tried that approach or not.

**Comment by benmccann** [comment] 2022-01-20 19:34
This sounds like a duplicate of https://github.com/sveltejs/kit/issues/3267 and https://github.com/sveltejs/kit/issues/3232

It should hopefully be fixed now by https://github.com/sveltejs/kit/pull/3346

**Closed by benmccann** 2022-01-20 19:34 UTC
