### ISSUE TITLE
auto-import

### ISSUE THREAD

**Issue by Bradley-H** [sveltejs/kit#4861] opened 2022-05-10 09:02 UTC
### Describe the problem

In some of the projects, I've come to notice that sometimes it can get a little messy (for lack of a better term), seeing 20+ imports statements, plus a maybe a few lifeCycle hooks, plus maybe importing stores, additional packages it becomes very messy as the project grows in scale.

I think have all routes to all stores, lifecycle hooks and all components have access to everything. But I'm sure some will point out the bundle would be insane. you're probably correct.  But, hate to point out the obvious, on build let's take out all that isn't being used out to reduce bundle size.

Furthermore, I fully acknowledge that this is probably in terms QoL (quality of life) at is bottom of the priority list. But I think it would be a great addition to Sveltekit

### Describe the proposed solution

I'm not particularly great at describing things. But I think the best I can describe it is like this.

in each component will automatically have access to all lifecycle hooks, Stores, Components, and other packages from the get-go without the need for an import statement. When it's time to build, everything that isn't being used, svelte can stripe that out the build cycle.
Take for example
`
onMount(() => {
    setTimeOut(() => {
$globalStore.count++, 2000)
})
`

but no `import {Onmount} from 'svelte` and `import {globalStore} from '../stores/globalStore.ts`

### Importance

nice to have

**Comment by bluwy** [comment] 2022-05-10 09:26
Duplicate of #4845

**Closed** 2022-05-10 09:26 UTC
