### ISSUE TITLE
More then one / give a error with stacktrace.

### ISSUE THREAD

**Issue by Trackhe** [sveltejs/kit#6323] opened 2022-08-26 19:12 UTC
### Describe the bug

At first, i tried the configs trailingSlash ignore and never, and i tried it in dev mode and i build and preview it. In the Preview mode is the error message not styled as the hmr does ^^.

If i try to reach the site with more then / then the error appears
```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:564:9)
    at new URL (node:internal/url:644:5)
    at file:///Users/.../node_modules/@sveltejs/kit/src/vite/preview/index.js:70:25
    at call (file:///.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46150:7)
    at next (file:///.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46094:5)
    at /Users/.../node_modules/sirv/build.js:176:28
    at call (file:///.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46150:7)
    at next (file:///..../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46094:5)
    at file:///.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:39543:28
```

i guess that should be. 

### Reproduction

Reach your sveltkit site with more then one /, i tried it with a clean new "empty" project on the version 1.0.0-next.443

Example repository: https://github.com/Trackhe/sveltkit-url-issue
start with "npm run dev" or build "npm run build" and preview it "npm run preview"
then try to reach 'http://localhost:5173//'

### Logs

```shell
8:58:04 PM [vite] Internal server error: Invalid URL
      at new NodeError (node:internal/errors:387:5)
      at URL.onParseError (node:internal/url:564:9)
      at new URL (node:internal/url:644:5)
      at viteServeRawFsMiddleware (file:///Users/.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:39645:21)
      at call (file:///Users/.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46150:7)
      at next (file:///Users/.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46094:5)
      at viteTransformMiddleware (file:///Users/.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:57588:9)
      at call (file:///Users/.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46150:7)
      at next (file:///Users/.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46094:5)
      at next (file:///Users/.../node_modules/vite/dist/node/chunks/dep-88cc3a4f.js:46072:14) (x2)

```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (20) arm64 Apple M1 Ultra
    Memory: 3.96 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.18.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.66 => 1.0.0-next.66 
    @sveltejs/kit: ^1.0.0-next.443 => 1.0.0-next.443 
    svelte: * => 3.49.0 
    vite: * => 3.0.6
```

### Severity

blocking all usage of SvelteKit

### Additional Information

handle and handleError are not called.

**Comment by benmccann** [comment] 2022-08-26 20:25
It's impossible to understand this. You need to provide a repository that reproduces this per the instructions and give the exact URL to visit or else this issue will be closed

**Comment by Trackhe** [comment] 2022-08-27 10:57
@benmccann i ve added a repo and the url. 

> Example repository: https://github.com/Trackhe/sveltkit-url-issue
start with "npm run dev" or build "npm run build" and preview it "npm run preview"
then try to reach 'http://localhost:5173//'

**Comment by benmccann** [comment] 2022-08-27 18:51
I can't reproduce this. It works just fine for me

**Comment by Trackhe** [comment] 2022-08-28 10:11
Ok i cant understand why you don't cant reproduce it. i have test it now on a new windows system. i installed the newest version of npm, downloaded the repo, then 'npm i' after that 'npm run dev' and open the url add a second / and the error appears. tested now on 2 diffrent systems. I ran sveltkit with webstorm and on the windows pc with vscode, tested with chrome, edge, firefox. do i need to create a video?

**Comment by Rich-Harris** [comment] 2022-08-30 02:20
I can reproduce it. But this appears to be a Vite error — the request is never reaching SvelteKit

**Comment by benmccann** [comment] 2022-08-30 02:55
Oh, I somehow missed that there were two `/` at the end of the URL the first time around. Yes, this does appear to be a bug in Vite, so I'm going to close this and suggest you file the issue at https://github.com/vitejs/vite/issues. Thanks for the report!

**Closed by benmccann** 2022-08-30 02:55 UTC
Labels: vite
