### ISSUE TITLE
CSS property with "image-set" value is silently removed from inline style

### ISSUE THREAD

**Issue by Lootwig** [sveltejs/kit#5581] opened 2022-07-17 13:46 UTC
### Describe the bug

A "background-image" property as described above is completely removed from the output. No warnings or error messages.

### Reproduction

See the modified "h2" tag in index.svelte and compare to generated HTML. background-image is completely gone. Attribute is kept if just set to url("...").

https://stackblitz.com/edit/sveltejs-kit-template-default-r4ppju?file=src%2Froutes%2Findex.svelte&terminal=dev

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.61 
    @sveltejs/kit: next => 1.0.0-next.377 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.0
```

### Severity

blocking an upgrade

**Comment by gtm-nayan** [comment] 2022-07-17 14:26
![Screenshot of MDN web docs highlighting image-set needs a vendor prefix](https://user-images.githubusercontent.com/50981692/179402966-e14c3a7e-219b-4df1-a6eb-d8a5c320d913.png)

**Comment by Lootwig** [comment] 2022-07-17 14:31
Are you saying Chrome modifies the source code during load and removes the attribute?

**Comment by gtm-nayan** [comment] 2022-07-17 14:34
I don't see where you're getting the "removes the attribute" from, for me it's still applied. 

![Screenshot of browser dev tools showing the property intact](https://user-images.githubusercontent.com/50981692/179403277-c9482034-5dbd-4f08-9e30-57a3488a502a.png)

In both the SSR'd and the hydrated html.

**Comment by Lootwig** [comment] 2022-07-17 14:42
You are correct, I didn't notice the behavior changed when simplifying my project code.
Only occurs when the property value is inserted as a variable - I updated the fork correspondingly.

**Comment by gtm-nayan** [comment] 2022-07-17 14:46
> Only occurs when the property value is inserted as a variable

Nope still there.

**Comment by Lootwig** [comment] 2022-07-17 14:55
wow. When you switch the value from being defined inline **TO** inserting the variable value and the app automatically hot-reloads, the field is missing for me - however, fully restarting does insert it back in. Is this some sort of optimizing voodoo?

https://user-images.githubusercontent.com/39827040/179404101-cbca017b-8690-4792-a8a7-2572b805adf6.mov

**Comment by gtm-nayan** [comment] 2022-07-17 15:28
Okay, now that I can reproduce

What it boils down to is again the browser lacking support for image-set, it doesn't allow setting invalid property values through javascript, when the page initially loads the SSR'd html already has the style and the set_style in hydration is just ignored by the browser.

In subsequent HMR updates, the component is reevaluated and the dom nodes are recreated. But this time the style isn't set on the newly created nodes, and set_style with an invalid value can't add the style back.

Anywho this is standard JS behaviour, we can't do anything about it and since the property wouldn't have been rendered anyway it doesn't really affect you. Going to close this.

**Closed by gtm-nayan** 2022-07-17 15:28 UTC
