### ISSUE TITLE
Enable service worker on development mode 

### ISSUE THREAD

**Issue by sharmapukar217** [sveltejs/kit#5846] opened 2022-08-08 03:33 UTC
### Describe the problem

It's difficult to test my service worker by running build and preview each time i change something

### Describe the proposed solution

🤷🏼‍♂️

### Importance

nice to have

**Comment by benmccann** [comment] 2022-08-08 17:23
Duplicate of https://github.com/sveltejs/kit/issues/5479

**Closed by benmccann** 2022-08-08 17:23 UTC
