### ISSUE TITLE
Expose a configurable beforeunload api from the router.

### ISSUE THREAD

**Issue by samccone** [sveltejs/kit#344] opened 2021-01-24 17:52 UTC
When building an application that has page state (such as uploads), it can be powerful to be able to prompt the user before they leave the page. In traditional web apps we are able to use `beforeunload` in order to warn / prompt the user.

In SPA land however we need to implement something similar for in app navigation. Currently the router https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/internal/router/index.js does not expose hooks like this 

Looking at prior art react-router has a concept of a Prompt
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Prompt.md

Ember has a concept of a route willTransition
https://guides.emberjs.com/release/routing/preventing-and-retrying-transitions/

Backbone has the ability to return false from execute 
https://backbonejs.org/#Router-route

**Comment by benmccann** [comment] 2021-03-16 21:22
I transferred the other issue to this repo so that we don't lose the conversation history. Closing this one as a duplicate of the other: https://github.com/sveltejs/kit/issues/552

**Closed by benmccann** 2021-03-16 21:22 UTC
Labels: enhancement
