### ISSUE TITLE
The `load` function works in the local environment, but not in the production environment using vercel

### ISSUE THREAD

**Issue by takurinton** [sveltejs/kit#1518] opened 2021-05-22 05:14 UTC
**Describe the bug**

I'm blogging on my personal project.  
This is the repository ( https://github.com/takurinton/blog.takurinton.com )

More details here ( https://github.com/takurinton/blog.takurinton.com/blob/6ed2312ae425560644947f104011e2ccbcbcc4a6/src/routes/index.svelte#L6-L9 )

I'm using the load function for server-side rendering and its argument page works fine locally but not in production.

**Logs**

This is what I do when I search for an article called graphql.  
The content of the Response of `?category=graphql` in the Network tab of chrome developer tools.

local

```html
<script type="module">
			import { start } from "/./_app/start-c18586c9.js";
			start({
				target: document.querySelector("#svelte"),
				paths: {"base":"","assets":"/."},
				session: {},
				host: "localhost:3000",
				route: true,
				spa: false,
				trailing_slash: "never",
				hydrate: {
					status: 200,
					error: null,
					nodes: [
						import("/./_app/pages/__layout.svelte-5e737a0f.js"),
						import("/./_app/pages/index.svelte-6af4efe6.js")
					],
					page: {
						host: "localhost:3000", // TODO this is redundant
						path: "/",
						query: new URLSearchParams("category=graphql"),
						params: {}
					}
				}
			});
		</script>
```

production

You can see that page is not working.

```html
<script type="module">
			import { start } from "/./_app/start-b910e839.js";
			start({
				target: document.querySelector("#svelte"),
				paths: {"base":"","assets":"/."},
				session: {},
				host: location.host,
				route: true,
				spa: false,
				trailing_slash: "never",
				hydrate: {
					status: 200,
					error: null,
					nodes: [
						import("/./_app/pages/__layout.svelte-5e737a0f.js"),
						import("/./_app/pages/index.svelte-ae8a0cf9.js")
					],
					page: {
						host: location.host, // TODO this is redundant
						path: "/",
						query: new URLSearchParams(""),
						params: {}
					}
				}
			});
		</script>
```

**To Reproduce**

The local environment can be reproduced by clone my [repository](https://github.com/takurinton/blog.takurinton.com). You can check the production environment at this [link](https://blog.takurinton.com).  
Specifically, there is a function to narrow down by category on the post list screen, but it does not work if it is in the production environment.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

 - System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 86.09 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
 - Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
 - Browsers:
    Chrome: 90.0.4430.212
    Safari: 13.1.2
 - npmPackages:
    @sveltejs/kit: next => 1.0.0-next.108
    svelte: ^3.34.0 => 3.38.2
- adapter
   "@sveltejs/adapter-vercel": "^1.0.0-next.19"
</details>

**Severity**

I'm in trouble because I can't get the page, it's serious.

**Comment by benmccann** [comment] 2021-05-22 18:17
Closing as duplicate of https://github.com/sveltejs/kit/issues/1218

**Closed by benmccann** 2021-05-22 18:17 UTC
