### ISSUE TITLE
sveltekit alias does not resolve

### ISSUE THREAD

**Issue by TadasV1** [sveltejs/kit#9547] opened 2023-03-28 15:54 UTC
### Describe the bug

// svelte.config.js

kit: {  
 ...   
 alias: {     
   '$helpers' : './helpers'   
 } 
}

### Reproduction

1. create folder helpers at root dir.
2. add any function.
3. add alias to svelte config
4. npm run dev
5. get error vite cannot resolve

### Logs

```Shell
Cannot find package '$helpers' imported from C:\wamp64\www\project\vite.config.js.timestamp-1680018796869.mjs
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 17.76 GB / 31.85 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/adapter-node: ^1.2.3 => 1.2.3
    @sveltejs/kit: ^1.13.0 => 1.13.0
    svelte: ^3.57.0 => 3.57.0
    vite: ^4.2.1 => 4.2.1
```

### Severity

annoyance

**Comment by Shyam-Chen** [comment] 2023-03-29 05:49
```svelte
<script lang="ts">
  import { foo } from '$lib/helpers';
</script>
```

**Comment by dummdidumm** [comment] 2023-03-29 11:48
I can't reproduce this. If I have `helpers/foo.js` and reference it as `$helpers/foo`, Vite tells me that this file is outside of the allowlist, and lists the allowed folders. If I then adjust the Vite config accordingly, it works

```diff
// vite.config.js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
+	server: {
+		fs: {
+			allow: ['.']
+		}
+	}
});

```

Please provide a proper reproduction repository if the issue persists for you.

**Comment by TadasV1** [comment] 2023-03-29 12:08
yes this seems to work with Sveltekit. But... 

I have folder at root level ./websockets. There are a lot of functions who share helpers at root.

But  I cannot use

```
// at root level /websockets/fileA.js
import helper1 from '$helpers/helper1.js'
```

[vite] Cannot find package '$helpers' imported from C:\wamp64\www\project\vite.config.js.timestamp-1680091642639.mjs

**Comment by koodeau** [comment] 2023-04-08 15:42
> I can't reproduce this. If I have `helpers/foo.js` and reference it as `$helpers/foo`, Vite tells me that this file is outside of the allowlist, and lists the allowed folders. If I then adjust the Vite config accordingly, it works
> 
> ```diff
> // vite.config.js
> import { sveltekit } from '@sveltejs/kit/vite';
> import { defineConfig } from 'vite';
> 
> export default defineConfig({
> 	plugins: [sveltekit()],
> +	server: {
> +		fs: {
> +			allow: ['.']
> +		}
> +	}
> });
> ```
> 
> Please provide a proper reproduction repository if the issue persists for you.

Yes, this only grans access to the project root, you should usually do this if you have to import something for example that isn't inside `src` folder but in root

**Comment by koodeau** [comment] 2023-04-08 15:45
You can also check Vite config documentation because they also support this, so you can do the same in your `vite.config.*` btw luckily we don't have to deal with it in `tsconfig.json` anymore, because sveltekit now takes a good care of that

**Comment by koodeau** [comment] 2023-04-08 15:53
Hold on, you're trying to use that alias you created in `svelte.config.js` but you're trying to use it to import modules inside the `vite.config.js`. So for example if I have to import something to my config I'd specify the path like that:

```js
import pkg from "./package.json"
```

So I don't think it's related to svelte-kit.

**Comment by dummdidumm** [comment] 2023-04-13 09:17
Good find, the error message reads as if the alias is used (indirectly) in the `vite.config.js`, which is not possible since Vite first needs to load itself and determine all this stuff before aliases are available - therefore closing.

**Closed by dummdidumm** 2023-04-13 09:17 UTC
Labels: awaiting submitter
