### ISSUE TITLE
Shadow endpoints don't invalidate on navigation when component stays mounted

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#3802] opened 2022-02-09 20:31 UTC
### Describe the bug

File `[slug].svelte` receives data from a `get()` endpoint in `[slug].ts` without explicit `load` function. When the route changes but the new route is also handled by `[slug].svelte`, the page does not update. Only a full page reload renders fresh data.

### Reproduction

Navigate from

https://studenten-bilden-schueler.de/standorte/aachen

via nav to

https://studenten-bilden-schueler.de/standorte/augsburg.

Code at https://github.com/sbsev/svelte-site.

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 178.88 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 98.1.35.100
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26 
    @sveltejs/kit: ^1.0.0-next.260 => 1.0.0-next.260 
    svelte: 3.46.4 => 3.46.4 
    vite: ^2.7.13 => 2.7.13
```

### Severity

blocking an upgrade

### Additional Information

I tried to invalidate the page with

```ts
import { afterNavigate, invalidate } from '$app/navigation'

afterNavigate(() => invalidate(slug))
```

but that has no effect.

**Comment by Conduitry** [comment] 2022-02-09 21:02
This sounds like a duplicate of #3727.

**Comment by janosh** [comment] 2022-02-09 21:10
@Conduitry You're right, somehow I didn't find that issue.

**Closed** 2022-02-09 21:10 UTC
