### ISSUE TITLE
Using pushState does not refresh $page.url and $page.params

### ISSUE THREAD

**Issue by yehiaabdelm** [sveltejs/kit#12014] opened 2024-03-21 23:21 UTC
### Describe the bug

When I do shallow routing `$page.url` and `$page.params` stay the same. So for example if I'm on /d and I pushState('/d/1', $page.state). `$page.url` and `$page.params` don't update.

$page before pushState
{
    "error": null,
    "params": {},
    "route": {
        "id": "/(authed)/d/[[id]]"
    },
    "state": {},
    "status": 200,
    "url": "http://localhost:5173/d",
    "form": null
}

After pushState
{
    "error": null,
    "params": {},
    "route": {
        "id": "/(authed)/d/[[id]]"
    },
    "state": {},
    "status": 200,
    "url": "http://localhost:5173/d",
    "form": null
}

### Reproduction

/src/routes/d/[[id]]/+page.svelte
```html
<script lang="ts">
  import { pushState } from '$app/navigation';
  import { page } from '$app/stores'
  $: console.log($page.url.pathname);
</script>

<button on:click={()=> { pushState(`/d/1`, $page.state)}}>Click me</button>
```

### System Info

```Shell
System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 157.95 MB / 18.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Safari: 17.1
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-03-22 16:39
closed as duplicate of https://github.com/sveltejs/kit/issues/11492

**Closed by eltigerchino** 2024-03-22 16:39 UTC
