### ISSUE TITLE
Allow conditionally adding/removing sveltekit:prefetch on links

### ISSUE THREAD

**Issue by nisarhassan12** [sveltejs/kit#2346] opened 2021-09-01 19:23 UTC
### Describe the problem

I have a NavItem component which when the href value is pointing to an external resource should not have sveltekit:prefetch set this is how the markup for the component looks like:

```svelte
<a
  class:active={isActivePage && !isExternal}
  class:highlighted={isHighlighted}
  {href}
  on:click
  sveltekit:prefetch
>
  {label}
</a>
```

Hovering over any link pointing to an external resource results in the following error in the console:

![image](https://user-images.githubusercontent.com/46004116/131730159-d736a9b4-b205-44f1-a07d-0667d8ae3a92.png)

There should be a way to avoid this from happening. 

### Describe the proposed solution

A possible solution could be to conditionally add/remove the `sveltekit:prefetch` attribute via a boolean i.e by default it has a value of true when it is set to false it automatically gets removed. 

### Importance

would make my life easier

**Comment by nisarhassan12** [comment] 2021-09-01 19:27
As a workaround, if I do `sveltekit:prefetch={isExtenal ? undefined : ''}` it works but TypeScript is not happy about it. I get the following error: 

```
Type 'string' is not assignable to type 'true'.ts(2322)
```

**Comment by Mlocik97** [comment] 2021-09-01 22:03
>  `sveltekit:prefetch={isExtenal ? undefined : ''}`

I don't understand this part of code, can't it be just `sveltekit:prefetch={!isExtenal}`

**Comment by Conduitry** [comment] 2021-09-01 22:14
No, because that would add `sveltekit:prefetch="false"` as the attribute, since this isn't a real boolean attribute, and that would be picked up as the attribute being present, and the router would still prefetch.

**Comment by ignatiusmb** [comment] 2021-09-02 02:11
I believe you can do `sveltekit:prefetch={isExtenal ? undefined : true}`

**Comment by nisarhassan12** [comment] 2021-09-02 05:12
> I believe you can do `sveltekit:prefetch={isExtenal ? undefined : true}`

Thanks @ignatiusmb It works when the ternary expression is inline but TypeScript becomes unhappy If I take it to the script block as shown below:

```svelte
<script>
  let isPrefetchAble = isExternal ? undefined : true;
</script>

<a 
  sveltekit:prefetch={isPrefetchAble}
  {href}
>
  {label}
</a>
```

I get this error: 

```
Type 'boolean' is not assignable to type 'true'.ts(2322)
```

Not sure why is that ? and What difference does it makes when the ternary is moved to the script block.

**Comment by ignatiusmb** [comment] 2021-09-02 05:27
That's cause you're using `let`, that will loosen `true` into `boolean`. Either change them to `const` or write explicit type annotations for it, I recommend the former.

I will also close this issue as it's not a bug or feature request and has been resolved, please come to our [Discord chat room](https://svelte.dev/chat) for further support questions.

**Closed by ignatiusmb** 2021-09-02 05:27 UTC

**Comment by nisarhassan12** [comment] 2021-09-02 05:32
Thanks, @ignatiusmb while it works like this fine. I think it would still be nice to have it work just like the `class` directive, does i.e based on a true or false value I could add/remove the class from an element. 

Doing `class:isActive={isActivePage}` reads better and is less code to right then `sveltekit:prefetch={isExtenal ? undefined : true}`.

**Comment by dummdidumm** [comment] 2021-09-02 06:54
This issue is somewhat of a subset of #2346 . If #2346 is tackled, we also need a way to turn prefetching off, at which point passing `false` to disable it would be good.
