### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'request'):undefined when building for production

### ISSUE THREAD

**Issue by dslingr** [sveltejs/kit#3901] opened 2022-02-14 19:09 UTC
### Describe the bug

After upgrading sveltekit to the latest version, when I run `npm run build`, it ends with the following output:

```
> Using @sveltejs/adapter-node
Error TypeError: Cannot read properties of undefined (reading 'request'):undefined
```

I've update my hooks.js file and all of my API endpoints as suggested [here](https://github.com/sveltejs/kit/pull/3384), however same issue.

I did notice that if I comment out the `handle` function in my hooks.js file, it builds just fine, so maybe I'm doing something wrong there.
```
import cookie from 'cookie';

export async function handle({ event, resolve }) {
	const headers = event.request.headers;

	const cookies = cookie.parse(headers.get('cookie') || '');

	if (cookies.token) {
		event.locals.token = cookies.token;
	}

	if (cookies.cookie_consent_status) {
		event.locals.cookie_status = cookies.cookie_consent_status;
	}

	const response = await resolve(event);

	return response;
}

export async function handleError({ error, event }) {
	console.log('Error', `${error}:${event}`);
}

export async function getSession(event) {
	// console.log('Hooks', event);
	return {
		token: event.locals.token,
		cookie_status: event.locals.cookie_status
	};
}
```
Also, everything runs just fine in dev (`npm run dev`).

### Reproduction

Not even sure.  I ran `npm update`, made the necessary changes to my hooks.js file and API endpoints, pushed to my repo, pulled on the server, ran 'npm run build` and got the error.

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (1) x64 DO-Regular
    Memory: 1.07 GB / 1.94 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.56 
    @sveltejs/kit: next => 1.0.0-next.202 
    svelte: ^3.42.6 => 3.44.3
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment] 2022-02-14 21:08
Please provide a project that reproduces this or the issue will be closed

**Comment by babichjacob** [comment] 2022-02-14 21:09
You're on an outdated version of SvelteKit that predates `event`'s introduction (and the other changes related to it).

**Comment by dslingr** [comment] 2022-02-14 21:14
> You're on an outdated version of SvelteKit that predates `event`'s introduction (and the other changes related to it).

Are you referring to `svelte: ^3.42.6 => 3.44.3`?

If so, how do I update it besides running npm update?

**Comment by benmccann** [comment] 2022-02-14 21:31
I always just run `rm -rf node_modules package-lock.json && npm install`, which updates everything. I'm sure there's a more targeted way to do it, but for me it's easier not to have to learn a new command

I'm going to go ahead and close this since it's not a big in SvelteKit

I'm going to close

**Closed by benmccann** 2022-02-14 21:31 UTC
Labels: pending clarification

**Comment by dslingr** [comment] 2022-02-14 21:38
> I always just run `rm -rf node_modules package-lock.json && npm install`, which updates everything. I'm sure there's a more targeted way to do it, but for me it's easier not to have to learn a new command
> 
> I'm going to go ahead and close this since it's not a big in SvelteKit
> 
> I'm going to close

That command fixed it!.  Thank you.
