### ISSUE TITLE
Color inputs always log a format error

### ISSUE THREAD

**Issue by flatpickles** [sveltejs/kit#10501] opened 2023-08-07 23:20 UTC
### Describe the bug

When creating color inputs in a SvelteKit project, I now always see this error, regardless of the value I'm using for the input:
<img width="584" alt="image" src="https://github.com/sveltejs/kit/assets/507484/061bae43-75d4-497e-9887-b0ef914b4e3f">

This happens with static values, with value bindings, and with no value specified.

### Reproduction

The example above is from a fresh skeleton project via `npm create svelte@latest`. After creating the project, I added this line in +page.svelte:

```
<input type="color" value="#00ff00" />
```

The input renders as expected, but I see the error above logged in the console. This isn't happening with static HTML pages in the same browser/etc, so I think it must be a Svelte(Kit) error. Thanks!

### Logs

```Shell
+page.svelte:2 The specified value "" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
(anonymous)	@	dom.js:701
(anonymous)	@	dom.js:701
(anonymous)	@	dom.js:640
claim_node	@	dom.js:674
claim_element_base	@	dom.js:688
claim_element	@	dom.js:715
claim	@	+page.svelte:2
claim_component	@	Component.js:38
claim	@	root.svelte:44
claim	@	layout.svelte?v=fd8f4d27:29
claim_component	@	Component.js:38
claim	@	root.svelte:43
claim	@	root.svelte:50
init	@	Component.js:144
Root	@	root.svelte:20
createProxiedComponent	@	svelte-hooks.js?v=fd8f4d27:341
ProxyComponent	@	proxy.js?v=fd8f4d27:242
Proxy<Root>	@	proxy.js?v=fd8f4d27:349
initialize	@	client.js?v=fd8f4d27:285
_hydrate	@	client.js?v=fd8f4d27:1809
await in _hydrate (async)		
start	@	start.js:22
(anonymous)	@	(index):27
Promise.then (async)		
(anonymous)	@	(index):26
```

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 179.42 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    npm: 9.6.6 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.22.4
    svelte: ^4.0.5 => 4.1.2
    vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

**Comment by geoffrich** [comment] 2023-08-07 23:32
Duplicate of https://github.com/sveltejs/svelte/issues/8446

**Closed by geoffrich** 2023-08-07 23:32 UTC
