### ISSUE TITLE
Change port 24678

### ISSUE THREAD

**Issue by kennylajara** [sveltejs/kit#2229] opened 2021-08-17 22:06 UTC
### Describe the problem

You can't run 2 SvelteKit apps at the same time on development mode without having a Port's conflict.

### Describe the proposed solution

An option to change the port 24678 when starting the app on development mode.

### Alternatives considered

Cry in Spanish.

### Importance

would make my life easier

**Comment by benmccann** [comment] 2021-08-17 22:48
Duplicate of https://github.com/sveltejs/kit/issues/2020

Use the `--port` option

**Closed by benmccann** 2021-08-17 22:48 UTC

**Comment by Conduitry** [comment] 2021-08-17 23:36
Not really a duplicate of that issue, as that's about the port that the main app is served on. But you can use the https://vitejs.dev/config/#server-hmr configuration to control the port the HMR server lives on.

**Comment by kennylajara** [comment] 2021-08-20 11:40
@benmccann This is not duplicated. #2020 is about port 3000, this one is about port 24678

**Comment by benmccann** [comment] 2021-08-20 14:51
The option already exists. Did you see the comment just above yours? Look at https://vitejs.dev/config/#server-hmr
