### ISSUE TITLE
navigation broken on 404 error page

### ISSUE THREAD

**Issue by helbling** [sveltejs/kit#784] opened 2021-03-30 20:11 UTC
**Describe the bug**
On the hn.svelte.dev example, navigating from a 404 error page to a nav link does not work.

**Logs**
```
Uncaught (in promise) TypeError: this.current.page is null
```

**To Reproduce**
```
git clone https://github.com/sveltejs/kit.git
cd kit/
pnpm i
pnpm -r build
cd examples/hn.svelte.dev/
pnpm dev
open http://localhost:3000/invalidpage
click the "top" link on top
```

404 page stays, url changes to http://localhost:3000/top/1

**Expected behavior**
I expect the /top/1 page to be shown with the hn articles and the "top" link in the navigation underlined.

**Stacktraces**

<details>
  <summary>Stack trace</summary>

  GEThttp://localhost:3000/invalidpage
[HTTP/1.1 404 Not Found 0ms]

GEThttp://localhost:3000/global.css
[HTTP/1.1 404 Not Found 0ms]

[vite] connecting... client:180:9
[vite] connected. client:202:21
Uncaught (in promise) TypeError: this.current.page is null
    notify http://localhost:3000/.svelte/dev/runtime/internal/start.js:435
    _navigate http://localhost:3000/.svelte/dev/runtime/internal/start.js:185
    init http://localhost:3000/.svelte/dev/runtime/internal/start.js:110
    init http://localhost:3000/.svelte/dev/runtime/internal/start.js:69
    start http://localhost:3000/.svelte/dev/runtime/internal/start.js:865
    async* http://localhost:3000/invalidpage:35
start.js:435:6

</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`

  System:
    OS: Linux 5.11 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
    Memory: 3.63 GB / 7.48 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 15.12.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.7.3 - /usr/bin/npm
  Browsers:
    Firefox: 87.0
  npmPackages:
    @sveltejs/kit: workspace:* => 1.0.0-next.64
    svelte: ^3.35.0 => 3.35.0

- Your browser
	Firefox

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
	Node

**Severity**
Annoying. Not highest priority as my users hopefully should not see error pages too often.
But still something that worked with sapper.

**Comment by sw-yx** [comment] 2021-03-30 20:35
duplicate of #604

**Closed** 2021-03-30 20:36 UTC
