### ISSUE TITLE
adapter-static: Placing media before srcset in a <source> tag will prevent srcset from being crawled

### ISSUE THREAD

**Issue by JackPriceBurns** [sveltejs/kit#2742] opened 2021-11-04 14:27 UTC
### Describe the bug

If the attributes in a `<source>` tag appear like so `<source media="(max-width: 400px)" srcset="/myimage.jpg">` the srcset won't be crawled and the image won't be downloaded.

When arranged like this `<source srcset="/myimage.jpg" media="(max-width: 400px)">` it works as expected.

### Reproduction

Add a `<source>` tag as mentioned above and run a SvelteKit build with adapter-static configured. Images will not be downloaded as expected.

### System Info

```shell
System:
    OS: Linux 5.10 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.01 GB / 7.77 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21
    @sveltejs/kit: next => 1.0.0-next.183
    svelte: ^3.43.1 => 3.43.2
```

### Severity

serious, but I can work around it

**Comment by rmunn** [comment] 2021-11-07 00:29
The way the regex is written in https://github.com/sveltejs/kit/blob/e664d90f1dfa548881b32b0d900ed2a50f192020/packages/kit/src/core/adapt/prerender.js#L43 will only match if the `srcset` attribute is first. I don't have time to build a better regex right now, but that's definitely the cause of this behavior.

**Comment by Conduitry** [comment] 2021-11-07 00:52
I've wondered whether it would be a good idea to give up on regexes here and just use something like parse5 to parse the HTML and walk the AST ourselves to find stuff more robustly. If this only ever happens at build time, I guess I see less of a cost to doing this with a bigger slower library.

**Comment by alecvision** [comment] 2021-11-07 05:10
> If this only ever happens at build time, I guess I see less of a cost to doing this with a bigger slower library.

Considering projects such as eldersjs, nextjs (with hybrid mode), etc, and considering the desire for SvelteKit to be a 'write-once deploy any*how*' famework, I would call back to one of Rich's arguments about the perils of "convenient escape hatches".

I've got a fair bit of regex deep-dive in me. Per the discord discussions about [compositional regex, lookaround assertions, etc](https://discord.com/channels/457912077277855764/781266015601295360/906314943241019392), I'd like to take a swing at a full refactor of the regex in prerender.js to address all related issues (there seem to be many).

Would it be possible to get a clearer definition of the objectives by aggregating the related issues somehow? It may also help to review/merge from PRs any valid tests related to regex in this file. Would help me during the refactoring process to validate as I go.

Of course, maintainability will remain a top concern - but I don't think it has to be sacrificed here in favor of a dependency-free solution.

**Comment by si3nloong** [comment] 2021-11-07 09:10
@Conduitry I prefer to use parse5 way instead of the regexes.

**Comment by rmunn** [comment] 2021-11-13 08:43
> I've wondered whether it would be a good idea to give up on regexes here and just use something like parse5 to parse the HTML and walk the AST ourselves to find stuff more robustly. If this only ever happens at build time, I guess I see less of a cost to doing this with a bigger slower library.

I think I'm in favor of a proper parser instead of regexes, too. Two recent Svelte bug reports —https://github.com/sveltejs/svelte/issues/6844 and https://github.com/sveltejs/svelte/issues/6923 — were both caused (I'm 95% certain) by an imprecision in the regexes Svelte uses to detect opening & closing `<script>` or `<style>` tags. A proper parser wouldn't suddenly produce incorrect results because a comment was added or because attributes were reordered.

**Comment by Rich-Harris** [comment] 2022-01-11 19:09
fixed by https://github.com/sveltejs/kit/pull/3288

**Closed by Rich-Harris** 2022-01-11 19:09 UTC
Labels: bug, p2-nice-to-have
