### ISSUE TITLE
Rest Route Params "Stealing" Previous Dynamic Segment Param

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#918] opened 2021-04-07 17:52 UTC
**Describe the bug**
Adding rest route params appears to steal some of previous dynamic segment parameter

This would prevent [the route shown in the docs](https://kit.svelte.dev/docs#routing-advanced-rest-parameters) from working

`/[org]/[repo]/tree/[branch]/[...file]` would only get the first character for the `[branch]` param.

Example:

Given a route structure containing:

/fixed/index.svelte

```
<script>
  import { page } from '$app/stores'
</script>

<p>/fixed</p>
<pre>{JSON.stringify($page, null, '  ')}</pre>
```

/fixed/[dynamic]/index.svelte

```
<script>
  import { page } from '$app/stores'
</script>

<p>/fixed/[dynamic]</p>
<pre>{JSON.stringify($page, null, '  ')}</pre>
```

/fixed/[dynamic]/[...rest].svelte

```
<script>
  import { page } from '$app/stores'
</script>

<p>/fixed/[dynamic]/[...rest]</p>
<pre>{JSON.stringify($page, null, '  ')}</pre>
```

... works as expected until the rest route is reached, for example:

http://localhost:3000/fixed
```
/fixed

{
  "host": "localhost:3000",
  "path": "/fixed",
  "query": {},
  "params": {}
}
```

http://localhost:3000/fixed/one
```
/fixed/[dynamic]

{
  "host": "localhost:3000",
  "path": "/fixed/one",
  "query": {},
  "params": {
    "dynamic": "one"
  }
}
```

http://localhost:3000/fixed/one/two/three
```
/fixed/[dynamic]/[...rest]

{
  "host": "localhost:3000",
  "path": "/fixed/one/two/three",
  "query": {},
  "params": {
    "dynamic": "o",
    "rest": "ne/two/three"
  }
}
```

Note the "dynamic" parameter which is now `o` with the rest parameter stealing the `ne`

I also tried using `/[...rest]/index.svelte` as well (same result)

**To Reproduce**
Example repo: https://github.com/CaptainCodeman/svelte-kit-rest-routing

**Expected behavior**
I expected the final route to produce:

```
{
  "host": "localhost:3000",
  "path": "/fixed/one/two/three",
  "query": {},
  "params": {
    "dynamic": "one",
    "rest": "/two/three"
  }
}
```

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 1.25 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 7.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 83.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.1.5 

- Your browser
Chrome 89

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
- Node
</details>

**Severity**
No immediate urgency

**Additional context**
The dynamic segment is the context for a selected project, the rest parameters are a folder path in the context of the app.

**Comment by CaptainCodeman** [comment] 2021-04-07 18:03
Looking at the routes it generated:

```js
export const routes = [
	// src/routes/index.svelte
[/^\/$/, [components[0]]],

// src/routes/fixed/index.svelte
[/^\/fixed\/?$/, [components[1]]],

// src/routes/fixed/[dynamic]/index.svelte
[/^\/fixed\/([^/]+?)\/?$/, [components[2]], (m) => ({ dynamic: d(m[1])})],

// src/routes/fixed/[dynamic]/[...rest].svelte
[/^\/fixed\/([^/]+?)\/?(.*)\/?$/, [components[3]], (m) => ({ dynamic: d(m[1]), rest: d(m[2])})]
];
```

... the lazy match in the last route is what makes it give up, maybe it should be something like:
```js
[/^\/fixed\/([^\/]+)\/?(.*)\/?$/, [components[3]], (m) => ({ dynamic: d(m[1]), rest: d(m[2])})]
```

**Comment by rmunn** [comment] 2021-04-15 06:50
For what it's worth, I took the current state of the `master` branch (commit 59bc85d4d0c3e9def990c3bfefeb6718186d7964) and edited the route-generating code to produce `([^/]+)` instead of `([^/]+?)`. This caused three unit test failures because the tests were comparing the output of the routes to an expected value that included `([^/]+?)` in it. I adjusted the expected value of the route output in those three tests to expect `([^/]+)`, and with that change all unit tests were passing (by running `pnpm test` at the root of the repo). I don't know if any tests are testing routing functionality instead of just checking for expected output, but if they are, then those tests continued to pass when removing the `?` from the regex to make the dynamic-segment match greedy instead of lazy.

I'll report back when I do a functionality test with that change.

**Comment by rmunn** [comment] 2021-04-15 07:18
Did a functionality test, and it almost works with that change, but there are still some issues. I created a `src/routes/[dynamic]/[...rest].svelte` route with the following contents:

```svelte
<script context="module">
    export function load({ page }) {
        console.log(page);
        return {
            props: { params: page.params }
        }
    }
</script>

<script>
    export let params;
</script>

<p>Dynamic: {params.dynamic}<br/>
Rest: {params.rest}</p>
```

Going to `localhost:3000/one/two/three` gave me what I expected: "Dynamic: one" and "Rest: two/three". So far, so good. :heavy_check_mark: 

Then I changed the route to be `src/routes/[dynamic]-foo/[...rest].svelte` to see if the regex would get *too* greedy and swallow up the `-foo` part. Going to `localhost:3000/one-foo/two-foo/three` gave me "Dynamic: one" and "Rest: two-foo/three". Again, so far so good. :heavy_check_mark: 

But then on a whim I tried `localhost:3000/one-food/two-foo/three`, and that didn't work. I was expecting a 404, but instead I got "Dynamic: one" and "Rest: d/two-foo/three". :x:

Here the culprit is the `?` in `\/?` between the dynamic and rest params. That's important for the last URL segment, because you want to be able to match `/foo` and `/foo/` both... but it's wrong as a separator between segments. Because it allows matching either `/` or an empty string, it let the URL `one-food/two` match as `one-foo` followed by `d/two`. Which is wrong.

It looks like this change was made in #768 as part of a fix for #751. The idea was to allow `foo/[...rest]/bar` to be matched by the route `foo/bar` (in which case the value of the `rest` param would be the empty string). But #768 allows that to also be matched by the route `food/bar` and having the value of `rest` be `d`, which I think is not what was expected.

**Comment by rmunn** [comment] 2021-04-16 05:18
The `localhost:3000/one-food/two-foo/three` bug is present in the `master` branch, BTW. It was not caused by my experimental change where I changed the lazy match in the dynamic route to a greedy match. Which means that it might be a different (although related) bug, so I've opened #1049 to track the issue of "rest" route params matching in the middle of a word. I'm about 80% certain that solving #1049 will also solve this issue, but just in case I'm wrong about that, I figure it's good to have two issues tracking the two different problems that "rest" params are currently having.

**Comment by rmunn** [comment] 2021-04-16 05:20
https://github.com/rmunn/bug-repro-svelte-kit-routing-spread-segments may be useful (with minor tweaks) as a repro for this issue as well.

**Comment by Rich-Harris** [comment] 2021-04-19 12:08
closed via #1128, thanks

**Closed by Rich-Harris** 2021-04-19 12:08 UTC
Labels: bug, router

**Comment by djatwood** [comment] 2021-04-19 15:27
Are we sure this is fixed? I'm running `SvelteKit v1.0.0-next.83` and I still have the issue

**Comment by dummdidumm** [comment] 2021-04-19 15:34
Not released yet. When this one is merged https://github.com/sveltejs/kit/pull/1129 , it will be.

**Comment by rmunn** [comment] 2021-04-20 01:26
It's been released now, and I can confirm that it fixes the bug. I took my bug reproduction project, ran `pnpm update` in it to pull in Svelte-Kit version `1.0.0-next.84` and the `localhost:3000/one-food/two-foo/three` route now returns a 404 as it should.
