### ISSUE TITLE
Autocomplete API routes

### ISSUE THREAD

**Issue by FortyGazelle700** [sveltejs/kit#11036] opened 2023-11-14 00:12 UTC
### Describe the problem

I would love to see autocompleted API routes.

### Describe the proposed solution

One great example of this is how NuxtJS 3 shows you autocompleted API routes when you use their `useFetch` hook, and shows you a list of API routes you have at hand. This makes sure that you don't have a URL that goes no where, and can warn the developer before an insight is overlooked, or a typo happen and spending hours on 1 typo.

### Importance

would make my life easier

**Comment by eltigerchino** [comment] 2023-11-14 10:50
Closed as duplicate of https://github.com/sveltejs/kit/issues/647

**Closed by eltigerchino** 2023-11-14 10:50 UTC
