### ISSUE TITLE
Generate Production package.json when building

### ISSUE THREAD

**Issue by tylkomat** [sveltejs/kit#5849] opened 2022-08-08 13:36 UTC
### Describe the problem

It's not always clear which packages should go into dependencies and which ones into devDependencies. There are regular new questions about this topic. 

### Describe the proposed solution

The compiler has all the information about which packages can be inlined and which can't. It can create a minimal production package.json file which only inludes the necessary packages.

### Importance

would make my life easier

### Additional Information

I already implemented the changes in kit and adapter-node, but I'm waiting for the big update until doing the PR.

**Comment by benmccann** [comment] 2022-08-08 17:30
This sounds like a duplicate of https://github.com/sveltejs/kit/issues/3176

**Closed by benmccann** 2022-08-08 17:30 UTC

**Comment by tylkomat** [comment] 2022-08-09 07:25
@benmccann It's not the same. I don't propose bundling the dependencies as not all can be bundled. My proposal merely converts this (example from my current project):
```json
{
  ...
  "devDependencies": {
    "@felte/reporter-svelte": "1.1.2",
    "@felte/validator-vest": "1.0.9",
    "@playwright/test": "1.24.2",
    "@prisma/client": "4.1.1",
    "@sveltejs/adapter-node": "1.0.0-next.85",
    "@sveltejs/kit": "1.0.0-next.401",
    "@tailwindcss/forms": "0.5.2",
    "@tailwindcss/typography": "0.5.4",
    "@types/nodemailer": "6.4.4",
    "@typescript-eslint/eslint-plugin": "5.31.0",
    "@typescript-eslint/parser": "5.31.0",
    "autoprefixer": "10.4.8",
    "eslint": "8.21.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-svelte3": "4.0.0",
    "felte": "1.2.2",
    "form-data": "4.0.0",
    "got": "12.3.0",
    "mdsvex": "0.10.6",
    "nodemailer": "6.7.7",
    "paseto": "3.1.0",
    "postcss": "8.4.14",
    "postcss-load-config": "4.0.1",
    "prettier": "2.7.1",
    "prettier-plugin-svelte": "2.7.0",
    "promise-retry": "2.0.1",
    "soap": "0.45.0",
    "svelte": "3.49.0",
    "svelte-check": "2.8.0",
    "svelte-preprocess": "4.10.7",
    "tailwindcss": "3.1.7",
    "tslib": "2.4.0",
    "typescript": "4.7.4",
    "vest": "4.5.0",
    "vite": "3.0.4"
  },
  ...
}
```
to this:
```json
{
  ...
  "dependencies": {
    "@felte/validator-vest": "1.0.9",
    "@prisma/client": "4.1.1",
    "form-data": "4.0.0",
    "got": "12.3.0",
    "nodemailer": "6.7.7",
    "paseto": "3.1.0",
    "soap": "0.45.0",
    "vest": "4.5.0"
  }
  ...
}
```

I tried using `ssr.noExternal` and then for example prisma is missing. So I have to go back an tweak the call. I didn't try further, but I may end up with the same list of dependencies.
My proposal is a straight forward solution.

**Comment by benmccann** [comment] 2022-08-09 13:06
> I don't propose bundling the dependencies as not all can be bundled

Why can't they? How do you figure out which can and can't?

**Comment by benmccann** [comment] 2022-08-09 23:30
> I tried using `ssr.noExternal` and then for example prisma is missing

Can you file an issue with a reproduction for this? It seems like we should fix this bug in Vite rather than work around it in SvelteKit

**Comment by tylkomat** [comment] 2022-08-10 09:02
I don't understand the fixation on `ssr.noExternal`. If vite can bundle the packages, it will, even without this setting.
If it can't, it won't. Forcing it with the setting `ssr.noExternal` may have side effects.

One year ago it was a default in createSvelte and has been removed (see [#1016](https://github.com/sveltejs/kit/issues/1016)) because of issues.
