### ISSUE TITLE
An empty stylesheet is appended to the head every time an element with a transition directive is mounted

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#3866] opened 2022-02-12 11:22 UTC
### Describe the bug

I have not checked all of the different transitions, but i've set up a minimal project required to reproduce the behaviour.

### Reproduction

https://github.com/MathiasWP/sveltekit-transition-stylesheet-bug

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 47.91 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.100
    Chrome: 98.0.4758.80
    Edge: 98.0.1108.43
    Firefox: 95.0.2
    Safari: 14.1.1
```

### Severity

annoyance

**Comment by georgecrawford** [comment] 2022-02-12 11:52
This is a duplicate of https://github.com/sveltejs/kit/issues/3854

**Comment by rmunn** [comment] 2022-02-12 11:55
Closing in favor of #3854.

**Closed by rmunn** 2022-02-12 11:55 UTC

**Comment by MathiasWP** [comment] 2022-02-12 11:57
Sorry for re-posting this post. I thought my other one did not go through. My bad!
