### ISSUE TITLE
trouble with <svelte:head> and adapter-static

### ISSUE THREAD

**Issue by chovy** [sveltejs/kit#2049] opened 2021-07-31 14:42 UTC
### Describe the bug

My titles are not updating when I navigate the site.

### Reproduction

I have a component for meta tags:

```
<script>
	export let title = 'chovy\'s boondocking guide';
	export let path = '/';
</script>

<title>{title} - chovy's boondocking guide</title>
```

I use it like this on a page:

```
<script>
	import Meta from '$components/meta.svelte';
	const title = 'Mobile Internet Access for Boondocking';
	const path = '/guides/mofi';
</script>

<svelte:head>
	<Meta {title} {path} />
</svelte:head>
```

If I refresh the page the title is correct, but navigation via links without refresh does not update the title.

### Logs

```shell
nothing relevant here
```

### System Info

```shell
System:
    OS: Linux 5.11 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 1.55 GB / 15.39 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chromium: 92.0.4515.107
    Firefox: 90.0.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.13 
    @sveltejs/kit: next => 1.0.0-next.139 
    svelte: ^3.34.0 => 3.41.0 
```
```


### Severity

annoyance

### Additional Information

_No response_

**Comment by chovyprognos** [comment] 2021-08-03 02:43
bump

**Comment by benmccann** [comment] 2021-08-04 17:17
This is unrelated to `adapter-static` and prerendering. You need to put the component that renders the title in the layout

Duplicate of https://github.com/sveltejs/kit/issues/1540

**Closed by benmccann** 2021-08-04 17:17 UTC

**Comment by chovy** [comment] 2021-08-05 09:56
my component handles the data.
