### ISSUE TITLE
Sluggish routing switch

### ISSUE THREAD

**Issue by DanaCoding** [sveltejs/kit#2799] opened 2021-11-14 16:15 UTC
### Describe the bug

![menu1](https://user-images.githubusercontent.com/93444868/141689390-473a3dc5-6e6a-4b6f-aefc-6fb1e69a081d.gif)

### Reproduction

`npm run dev` Display page in Chrome

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    Memory: 6.82 GB / 15.89 GB
  Binaries:
    Node: 14.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196
    svelte: ^3.34.0 => 3.44.1
```

### Severity

annoyance

**Comment by bluwy** [comment] 2021-11-14 16:43
That's because a fetch is ran in `load()` when rendering the todos page, and we wait for the load to finish before rendering. For a snappier experience, use [prefetch](https://kit.svelte.dev/docs#anchor-options-sveltekit-prefetch) or skip fetching in load on the client-side. Closing as this is expected behaviour.

**Closed by bluwy** 2021-11-14 16:43 UTC

**Comment by DanaCoding** [comment] 2021-11-14 16:45
> 那是因为在`load()`渲染 todos 页面时会运行 fetch ，我们在渲染之前等待加载完成。为了获得更快速的体验，请在客户端的负载中使用[预取](https://kit.svelte.dev/docs#anchor-options-sveltekit-prefetch)或跳过提取。关闭，因为这是预期的行为。

i see, thx, I can add a loading animation to it
