### ISSUE TITLE
Routes with umlauts are not found in node builds

### ISSUE THREAD

**Issue by noahsalvi** [sveltejs/kit#2166] opened 2021-08-11 13:15 UTC
### Describe the bug

When you create a route that has an umlaut in it, for example "über-uns" and you reload the page, you get a 404 Not found. This only happens when you run the build created by the adapter-node, preview and dev work as expected.

### Reproduction

https://github.com/noahsalvi/kit-umlaut-repro

install deps; npm run build; node build/

### Logs

```shell
http://localhost:3000/hell%C3%B6 404 (Not Found)
```

### System Info

```shell
System:
    OS: macOS 11.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 58.57 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Edge: 91.0.864.71
    Firefox: 82.0.3
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.39 
    @sveltejs/kit: next => 1.0.0-next.146 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

serious, but I can work around it

### Additional Information

The problem is that the adapter-node parses the url which encodes the umlaut characters, resulting in the route not being found.

Meaning `const parsed = new URL(......)` should be removed and replaced with just using `req.path` and `new URLSearchParams(req.query)`

I could make a pull request if needed.

**Comment by noahsalvi** [comment] 2021-08-13 11:39
Can this be reopened since this issue isn't fixed in "@sveltejs/adapter-node" 1.0.0-next.40 or do I need to make a new issue?
![image](https://user-images.githubusercontent.com/46045829/129351846-e62c300a-87c2-496f-ac1c-1715ced01658.png)

```
System:
    OS: macOS 11.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 747.07 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Edge: 91.0.864.71
    Firefox: 82.0.3
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.40 => 1.0.0-next.40 
    @sveltejs/kit: next => 1.0.0-next.146 
    svelte: ^3.34.0 => 3.42.1 
    ```

**Comment by benmccann** [comment] 2021-08-13 16:03
I think there's something weird going on here with npm. It kept giving me old versions of the packages. I had to manually specify the versions:
```
  "devDependencies": {
    "@sveltejs/adapter-node": "1.0.0-next.40",
    "@sveltejs/kit": "1.0.0-next.147",
```

After doing that, I'm getting a new error, which looks like a Vite bug

**Comment by noahsalvi** [comment] 2021-08-13 16:16
> After doing that, I'm getting a new error, which looks like a bug in `sirv`

But does this error result in the same result as on my screenshot or does the project not even run?

**Comment by benmccann** [comment] 2021-08-13 16:18
I get this:

![Screenshot from 2021-08-13 09-17-45](https://user-images.githubusercontent.com/322311/129389196-daac8eaa-6797-4339-a838-00d5ae9fb6ab.png)

**Comment by noahsalvi** [comment] 2021-08-13 16:26
> I get this:
> 
> ![Screenshot from 2021-08-13 09-17-45](https://user-images.githubusercontent.com/322311/129389196-daac8eaa-6797-4339-a838-00d5ae9fb6ab.png)

I got the same error using @sveltejs/kit 147

kit 146 gives me the other

**Comment by benmccann** [comment] 2021-08-13 17:44
The Polka bug is here: https://github.com/lukeed/sirv/issues/82#issuecomment-898618504

Vite worked around it here https://github.com/vitejs/vite/issues/1426

**Comment by benmccann** [comment] 2021-08-13 18:06
@noahsalvi can you test https://github.com/sveltejs/kit/pull/2191 and confirm it fixes the issue for you?

**Comment by noahsalvi** [comment] 2021-08-13 18:13
> @noahsalvi can you test #2191 and confirm it fixes the issue for you?

It works 🎉

**Comment by benmccann** [comment] 2021-08-13 22:59
@noahsalvi thanks for helping with this! I just released the fix. It changed a bit since you last tested, so you may want to test once again just to confirm

**Comment by noahsalvi** [comment] 2021-08-13 23:15
> @noahsalvi thanks for helping with this! I just released the fix. It changed a bit since you last tested, so you may want to test once again just to confirm

I just tested it with my repro with kit 148 and adapter-node 41 and sadly i'm getting the same error as before:
`Failed to fetch dynamically imported module: http://localhost:3000/_app/pages/hell%C3%B6.svelte-2ea1f198.js`

btw Glad that i was/am helpful. Also a big "thanks" to you for doing so much for this awesome project

**Comment by benmccann** [comment] 2021-08-13 23:26
okay :cry: :gun:  let me see what's going on. glad I told you to test again at least

**Comment by benmccann** [comment] 2021-08-13 23:34
@lukeed it seems that `sirv` still isn't working with unicode characters in SvelteKit, but I'm not sure what's going on this time. Any ideas? (my previous workaround no longer helps - not that I'd expect it to now)

You can use https://github.com/noahsalvi/kit-umlaut-repro to test and set the latest versions in `package.json`:
```
    "@sveltejs/adapter-node": "1.0.0-next.41",
    "@sveltejs/kit": "1.0.0-next.148",
```

**Comment by lukeed** [comment] 2021-08-13 23:39
Cache maybe? I haven't downloaded or cloned any of this before – so this is all my first time:

```sh
git clone git@github.com:noahsalvi/kit-umlaut-repro.git
cd kit-umlaut-repro
# make ben's dependency changes
rm yarn.lock
yarn
yarn build
yarn preview
```

<img width="776" alt="Screen Shot 2021-08-13 at 4 39 50 PM" src="https://user-images.githubusercontent.com/5855893/129427350-ad4d0b9f-dedf-4015-ac5a-9c1222c00b50.png">

**Comment by benmccann** [comment] 2021-08-13 23:47
You're not quite testing the same thing. After doing `yarn build` you should run `node build` for the adapter to be invoked. That being said `preview` is also failing for me, so it's weird that's working for you. I have "Disable cache" checked on the Network tab in Chrome, so I have no idea why it'd work for you and not us

**Comment by lukeed** [comment] 2021-08-13 23:49
I'll try that too, but I meant local/node_modules cache. Make sure you delete the `yarn.lock` if you havent already

**Comment by lukeed** [comment] 2021-08-13 23:50
Ok so `node build` fails. Unrelated, but wtf why would it be different? That defeats the purpose of a "preview" command.

**Comment by noahsalvi** [comment] 2021-08-13 23:52
> You're not quite testing the same thing. After doing `yarn build` you should run `node build` for the adapter to be invoked. That being said `preview` is also failing for me, so it's weird that's working for you. I have "Disable cache" checked on the Network tab in Chrome, so I have no idea why it'd work for you and not us

preview works for me. Make sure to also delete the build folder before running the build command.

**Comment by benmccann** [comment] 2021-08-13 23:52
It does a production build of your JS, etc. But it can't actually run in production on all the various platforms. I don't know how you'd mirror the Vercel, Netlify, platforms, etc. Maybe integrating with their dev tools. But thus far that's been a TODO

**Comment by lukeed** [comment] 2021-08-14 00:00
Ok so what I'm hearing is that `preview` is not very useful for debugging purposes.

And `node build` is failing consistently & I know why: the combo-check is working correctly, but because the request has passed thru `@polka/url`, there's a cached object in there. Right now, that un-decoded cache object is being returned from sirv's `parse(req, true).pathname` step. Easy fix, will publish after my computer forced-restart is done 😆

**Comment by lukeed** [comment] 2021-08-14 00:28
Verified locally that the reproduction now works with `node build` (and preview still, lol)

**Comment by benmccann** [comment] 2021-08-14 03:28
Should be fixed with the latest version. Thanks again for the help, Luke

**Closed by benmccann** 2021-08-14 03:28 UTC
Labels: bug, p1-important

**Comment by noahsalvi** [comment] 2021-08-14 14:51
@benmccann 
I just noticed that umlauts don't work when nested in a dynamic route e.g. [variable]/ö
Repro: https://github.com/noahsalvi/kit-path-broken-repro

**Comment by benmccann** [comment] 2021-08-14 15:35
I made a new issue for that one since there was already a lot of discussion here that's not necessarily related: https://github.com/sveltejs/kit/issues/2201
