### ISSUE TITLE
Docs: Copy Button for some code samples has typescript errors copied to clipboard

### ISSUE THREAD

**Issue by RoryDuncan** [sveltejs/kit#12628] opened 2024-08-28 21:46 UTC
### Describe the bug

Within the sveltekit documentation there are some code samples that include typescript errors in the clipboard data. From my observation it primarily ones that have import statements—as it is the import statements that are erroring.

### Reproduction

1. Go to https://kit.svelte.dev/docs/adapter-static
2. Click the _Copy Button_ within the `svelte.config.js` code sample
3. Paste your clipboard somewhere
4. Observe the text

### Logs

```Shell
Not a log per-se, but this is the clipboard contents if you follow the reproduction steps:

import adapter from '@sveltejs/adapter-static';Cannot find module '@sveltejs/adapter-static' or its corresponding type declarations.2307Cannot find module '@sveltejs/adapter-static' or its corresponding type declarations.
export default {	kit: {		adapter: adapter({			// default options are shown. On some platforms			// these options are set automatically — see below			pages: 'build',			assets: 'build',			fallback: undefined,			precompress: false,			strict: true		})	}};
```
```


### System Info

```Shell
I only tested in Chrome Version 127.0.6533.120 (Official Build) (64-bit)
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-08-30 01:16
closed as duplicate of https://github.com/sveltejs/kit/issues/11247

**Closed by eltigerchino** 2024-08-30 01:16 UTC
