### ISSUE TITLE
https://kit.svelte.dev/docs 500s out with an "Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by bootsa** [sveltejs/kit#3859] opened 2022-02-11 21:23 UTC
### Describe the bug

Navigating to https://kit.svelte.dev/docs gives a 500 error: "Unexpected token < in JSON at position 0". Yikes indeed.

![image](https://user-images.githubusercontent.com/22413/153671038-b465c0b9-5b56-4f9b-a46c-e8d432da2443.png)

Also affects old navigation schema, for instance: https://kit.svelte.dev/docs#adapters

Looks like it's a combination of the new docs refactor and the new automatic shadow endpoint system thinking its going to receive a JSON file and getting something else instead...

### Reproduction

Go to https://kit.svelte.dev/docs or https://kit.svelte.dev/docs#adapters

### System Info

```shell
System:
    OS: Linux 5.13 Linux Mint 20.3 (Una)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 601.65 MB / 15.38 GB
  Browsers:
    Brave Browser: 98.1.35.101
    Chromium: 98.0.4758.80
    Firefox: 97.0
```

### Severity

annoyance

**Comment by geoffrich** [comment] 2022-02-11 21:59
The underlying cause is being tracked in #3848.

**Comment by MarcGuiselin** [comment] 2022-02-11 22:46
This can be temporarily fixed by using a client-rendered version of the site. Click "FAQ" in the upper right corner, then click "Docs" and voila!

**Comment by hyunbinseo** [comment] 2022-02-12 06:28
Seems to be a duplicate of https://github.com/sveltejs/kit/issues/3849.

> The second half of https://github.com/sveltejs/kit/issues/3848 — https://kit.svelte.dev/docs is failing at the moment because (AFAICT) it's attempting to server-render /docs.json which was (necessarily, because it uses the filesystem) prerendered during build.

Search results of [Docs • SvelteKit](https://kit.svelte.dev/docs) and [Read the docs](https://kit.svelte.dev/docs) are broken at the moment as well.

For the mean time, I am removing all `https://kit.svelte.dev/docs` histories from my synced web-browsers.

**Comment by geoffrich** [comment] 2022-02-12 16:20
Closed by https://github.com/sveltejs/kit/pull/3858.

**Closed by geoffrich** 2022-02-12 16:20 UTC
