### ISSUE TITLE
Can't return binary (Buffer) in ServerResponse.body because of auto ETags generation

### ISSUE THREAD

**Issue by dievardump** [sveltejs/kit#1232] opened 2021-04-26 17:49 UTC
https://github.com/sveltejs/kit/blob/92d33913e284e00fb20d882253ba5439eeafc407/packages/kit/src/runtime/server/index.js#L61-L73

Trying to return a Buffer PNG in a get endpoint, I have been welcomed with an error `str.charCodeAt is not a function`

After looking in the code, I found that the auto-etag generation is the culprit, because the `hash()` function isn't expecting this type of content.

From my understanding, we should still be able to set ETags on binary content, so I guess this goes in the "bug" section.

Reproducing:

```js
export async function get() {
	const buffer = Buffer.from(
		'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
		'base64'
	);

	return {
		headers: {
			'Content-Type': 'image/png',
			'Content-Length': buffer.length
		},
		body: buffer
	};
}
```

**Workaround for now**
setting 'Cache-control': 'no-store'` in the headers

**Comment by benmccann** [comment] 2021-04-26 18:11
Closing as duplicate of https://github.com/sveltejs/kit/issues/1136

**Closed by benmccann** 2021-04-26 18:11 UTC
