### ISSUE TITLE
Router on error route doesn't update the page

### ISSUE THREAD

**Issue by drzax** [sveltejs/kit#663] opened 2021-03-25 08:02 UTC
**Describe the bug**
When the `$error.svelte` route is rendered, links on the page change the URL but the page is not updated.

**Logs**
<details>
<summary>console.log</summary>

```

GET http://localhost:3000/not-here
[HTTP/1.1 404 Not Found 399ms]

[vite] connecting... client:180:9
[vite] connected. client:202:21
Uncaught (in promise) TypeError: this.current.page is null
    notify http://localhost:3000/.svelte/dev/runtime/internal/start.js:423
    _navigate http://localhost:3000/.svelte/dev/runtime/internal/start.js:185
    init http://localhost:3000/.svelte/dev/runtime/internal/start.js:112
    init http://localhost:3000/.svelte/dev/runtime/internal/start.js:73
    start http://localhost:3000/.svelte/dev/runtime/internal/start.js:812
    <anonymous> http://localhost:3000/not-here:16
start.js:423:5
    _navigate http://localhost:3000/.svelte/dev/runtime/internal/start.js:206
    init http://localhost:3000/.svelte/dev/runtime/internal/start.js:112
    (Async: EventListener.handleEvent)
    init http://localhost:3000/.svelte/dev/runtime/internal/start.js:73
    start http://localhost:3000/.svelte/dev/runtime/internal/start.js:812
    <anonymous> http://localhost:3000/not-here:16
    InnerModuleEvaluation self-hosted:2382
    evaluation self-hosted:2333
```
</details>

**To Reproduce**
1. Setup with `npm init svelte@next`
2. Create an `$error.svelte` route with a link to, say, "/"
3. Run the dev server (or build and start)
4. Hit a 404 say /not-here
5. Click the link and observe that the URL changes, but the page does not

Clone https://github.com/drzax/svelte-kit-app for a quick reproduction.
Deployed here: https://svelte-kit-app.netlify.app/not-there

**Expected behavior**
Clicking the link should display the home page. 

**Information about your SvelteKit Installation:**
```
 System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 154.45 MB / 32.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 14.15.1 - ~/.nave/installed/default/bin/node
    Yarn: 1.22.10 - ~/.nave/installed/default/bin/yarn
    npm: 7.6.3 - ~/.nave/installed/default/bin/npm
  Browsers:
    Chrome: 91.0.4455.2
    Edge: 89.0.774.57
    Firefox: 86.0.1
    Firefox Developer Edition: 79.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.59
    svelte: ^3.29.0 => 3.35.0
```
Seen in Firefox 86.0.1  on macOS

Seen on both adapter-node and adapter-netlify

**Severity**
A bit annoying. Links direct on the page can use `target="_self"` to avoid the router but links in modules used on the error page are more difficult to modify.

**Additional context**
Seems possibly related to https://github.com/sveltejs/kit/issues/643

**Comment by sw-yx** [comment] 2021-03-25 09:19
could be dupe of https://github.com/sveltejs/kit/issues/604 as well

**Comment by benmccann** [comment] 2021-03-26 02:21
Closing as duplicate

**Closed by benmccann** 2021-03-26 02:21 UTC
