### ISSUE TITLE
HTTPS mode and HMR reload loop

### ISSUE THREAD

**Issue by rockfreak** [sveltejs/kit#2582] opened 2021-10-10 21:34 UTC
### Describe the bug

Basic install of svelte kit with the only setting being changed is adding the `--https` flag to the dev server start command.

The HMR websocket connection fails to connect and you end up in a refresh loop.

```
$ npm init svelte@next .
npx: installed 5 in 0.886s

create-svelte version 2.0.0-next.82

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

If you encounter a problem, open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › Skeleton project
✔ Use TypeScript? … No / Yes
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
✔ Copied project files
```

### Reproduction

https://github.com/rockfreak/svelte-kit-https-issue

### Logs

```shell
From chrome dev tools

Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

Navigated to https://localhost:3000/

client.ts:22 [vite] connecting...

index.mjs:1983 <Routes> received an unexpected slot "default".
validate_slots @ chunk-FGZAEJVQ.js?v=6280bd82:1815
instance @ index.svelte:103
init @ chunk-FGZAEJVQ.js?v=6280bd82:1635
Routes @ index.svelte:116
createProxiedComponent @ svelte-hooks.js:245
ProxyComponent @ proxy.js:239
Proxy<Index> @ proxy.js:339
create_if_block_2 @ root.svelte:62
create_default_slot @ root.svelte:312
create_slot @ chunk-FGZAEJVQ.js?v=6280bd82:70
create_fragment @ layout.svelte:21
init @ chunk-FGZAEJVQ.js?v=6280bd82:1648
Layout @ layout.svelte:97
createProxiedComponent @ svelte-hooks.js:245
ProxyComponent @ proxy.js:239
Proxy<Layout> @ proxy.js:339
create_fragment @ root.svelte:502
init @ chunk-FGZAEJVQ.js?v=6280bd82:1648
Root @ root.svelte:690
createProxiedComponent @ svelte-hooks.js:245
ProxyComponent @ proxy.js:239
Proxy<Root> @ proxy.js:339
_init @ start.js:706
start @ start.js:569
async function (async)
start @ start.js:521
start @ start.js:1170
(anonymous) @ (index):15

client.ts:28 WebSocket connection to 'wss://localhost:3000/' failed: 
(anonymous) @ client:188

client.ts:224 [vite] server connection lost. polling for restart...
```

Page then refreshes

### System Info

```shell
npx: installed 1 in 0.942s

  System:
    OS: Linux 5.10 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 8.17 GB / 24.73 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.180
    svelte: ^3.42.6 => 3.43.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

This repo has been tested on WSL2 and from within a docker container.

Both work fine in http mode but when switching into https mode hmr fails to connect.

**Comment by benmccann** [comment] 2021-10-11 15:43
If you search the issue tracker there are other discussions about this that should help you get it working

**Comment by baseballyama** [comment] 2021-10-16 09:24
I tried to reproduce your issue but I couldn't.
I cloned your GitHub repository and run `npm i` and `npm run dev` on WSL2.
Surely, when I access `http://localhost:3000`, browser reloaded infinitely.
But when I access `https://localhost:3000`, browser reload didn't happen.

Could you please check it again?
I would like to know exact reproduction way.

**System info**
```
  System:
    OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.80 GB / 5.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 7.14.0 - /usr/local/bin/npm
```

**Comment by gyurielf** [comment] 2021-10-19 16:39
It's not only on https.
There is actual on http too.

I'm on a true SPA mode. All of the packages are the latest.

```
client.ts:28 WebSocket connection to 'ws://local.mydev.tld:24679/' failed: 
[vite] server connection lost. polling for restart...
```

I have found that it happens from this ``"@sveltejs/kit": "^1.0.0-next.169"``,
``168`` working fine.

**Comment by gyurielf** [comment] 2021-10-20 12:23
Maybe. Did you try it ?

**Comment by benmccann** [comment] 2022-03-18 21:07
This might be the same as https://github.com/vitejs/vite/issues/6068, which I expect will be fixed in Vite 2.9

**Comment by AlbertMarashi** [comment] 2022-04-02 12:44
My proxy was configured to send traffic to `http` instead of `ws` - just mentioning in case anyone finds useful coming from google

**Comment by dominikg** [comment] 2022-04-02 13:26
Can't reproduce the original report with kit version `1.0.0-next.304` (uses vite 2.9).  `svelte-kit dev --https` serves at `https://localhost:3000` the site loads after confirming cert trust and hmr updates work.
 
@rockfreak please update and let us know if it works.

**Closed** 2022-04-02 16:14 UTC
Labels: vite
