### ISSUE TITLE
Preload stops working if handle is in sequence() call

### ISSUE THREAD

**Issue by arackaf** [sveltejs/kit#8251] opened 2022-12-22 22:19 UTC
### Describe the bug

The following handle

```ts
export async function handle({ event, resolve }: any) {
  const response = await resolve(event, {
    preload: ({ type }: any) => PRELOAD.has(type)
  });

  return response;
}
```

works fine. But it stops preloading (e.g. font files) if it's embedded in a sequence call

```ts
export async function preload({ event, resolve }: any) {
  const response = await resolve(event, {
    preload: ({ type }: any) => PRELOAD.has(type)
  });

  return response;
}

export const handle = sequence(preload);
```

Font files in particular are no longer preloaded. 

### Reproduction

See code above - hoping that's sufficient 

### Logs

```Shell
n/a
```

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 183.12 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/yarn
    npm: 9.2.0 - ~/Documents/git/booklist/svelte-kit/node_modules/.bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.89 
    @sveltejs/kit: ^1.0.1 => 1.0.1 
    svelte: ^3.44.0 => 3.54.0 
    vite: ^4.0.1 => 4.0.1
```

### Severity

Very serious - would likely prevent someone from using an auth library

**Comment by dummdidumm** [comment] 2022-12-22 22:26
Duplicate of #8061

**Closed by dummdidumm** 2022-12-22 22:26 UTC

**Comment by arackaf** [comment] 2022-12-22 22:41
Oops - sorry!
