### ISSUE TITLE
scss ssr

### ISSUE THREAD

**Issue by basaran** [sveltejs/kit#2744] opened 2021-11-04 22:31 UTC
### Describe the bug

In an SSR enabled sveltekit project configured with scss preprocess, the rules do not make it to the SSR rendered output.

Only plain css files get rendered out during SSR.

### Reproduction

clone https://github.com/basaran/scss-ssr-issue.

pnpm instal the repository, and launch dev.
launch firefox, go to localhost:3000
you will see the `margin-top: 200px` that comes from app.scss. 
disable javascript from about:config
refresh the page
`margin-top:200px` is no more.
open app.scss, uncomment the import line.
refresh the page
you will see `margin-top:200px` back.

### System Info

```shell
System:
    OS: Linux 5.12 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 2.04 GB / 7.52 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /usr/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.20.2 - /usr/bin/npm
  Browsers:
    Chromium: 92.0.4515.107
    Firefox: 90.0.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.193
    svelte: ^3.42.6 => 3.44.1
```

### Severity

serious, but I can work around it

**Comment by babichjacob** [comment] 2021-11-05 02:29
This is a duplicate of https://github.com/sveltejs/kit/issues/915. This issue doesn't occur in production builds of the site.

**Closed by babichjacob** 2021-11-05 02:29 UTC
