### ISSUE TITLE
Cannot use import module statement outside a module when importing and using sveltestrap component on sveltekit

### ISSUE THREAD

**Issue by ahmadshiddiqn** [sveltejs/kit#4603] opened 2022-04-13 03:24 UTC
### Describe the bug

https://github.com/sveltejs/kit/issues/2161 happens to me too in the new skeleton project latest sveltekit after importing components from sveltestrap. the workaround is the same as the last workaround (import directly from sveltestrap/src/foo.svelte), but it really annoying for an already bigger project like mine.

### Reproduction

The error starts right after using sveltestrap component even with the new skeleton project:
1. Create sveltekit skeleton project
2. install sveltestrap npm package
3. Import and use at least one component on your .svelte file (in this reproduction repo, I use it in main index.svelte)

Using the link below, just clone it, and do standard npm setup:
`npm i`
`npm run dev` (it runs on port 1234)

And go to localhost:1234, the error should popup both on the screen and

https://github.com/ahmadshiddiqn/sveltekit-error-sveltestrap

PS: custom port did not affect the error

### Logs

```shell
The skeleton project creation

create-svelte version 2.0.0-next.127

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

Problems? Open an issue on https://github.com/sveltejs/kit/issues if none exists already.

√ Which Svelte app template? » Skeleton project
√ Add Playwright for browser testing? ... No / Yes

Your project is ready!
✔ Typescript
  Inside Svelte components, use <script lang="ts">
✔ ESLint
  https://github.com/sveltejs/eslint-plugin-svelte3
  https://prettier.io/docs/en/options.html
  https://github.com/sveltejs/prettier-plugin-svelte#options
✔ Playwright
  https://playwright.dev

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-adders
Next steps:
  1: cd adbus-dashboard
  2: npm install (or pnpm install, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C
```
The error:
```
(node:19040) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
Cannot use import statement outside a module
C:\Users\mioto\Documents\JavaScript\sveltekit-error-sveltestrap\node_modules\@popperjs\core\dist\esm\popper.js:1
import { popperGenerator, detectOverflow } from "./createPopper.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
```
```


### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 446.85 MB / 7.43 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.55)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34
    @sveltejs/kit: next => 1.0.0-next.311
    svelte: ^3.47.0 => 3.47.0
```

### Severity

annoyance

**Comment by benmccann** [comment] 2022-04-13 03:52
sveltestrap has been broken for a long time. I sent them a fix to their package https://github.com/bestguy/sveltestrap/pull/356 and am still waiting for it to be merged

**Closed by benmccann** 2022-04-13 03:52 UTC

**Comment by lovasoa** [comment] 2022-04-13 08:47
@benmccann : If it worked before, and the latest release of sveltekit broke it, then maybe it can be fixed on sveltekit's side ?

**Comment by benmccann** [comment] 2022-04-13 23:44
It looks like this is a duplicate of https://github.com/sveltejs/kit/issues/4504
