### ISSUE TITLE
Error at class with divider

### ISSUE THREAD

**Issue by git-no** [sveltejs/kit#4336] opened 2022-03-15 18:32 UTC
### Describe the bug

Error at class with divider
```html
class:bg-gray-900/10={messageHasValue}
```

**What version of SvelteKit are you using?**
Svelte 3.44.0
Sveltekit 1.0.0-next.297

**What version of Tailwind CSS are you using?**
v.3.0.23

**What version of Node.js are you using?**
v16.14

**What browser are you using?**
Safari Version latest (15.3 (17612.4.9.1.8))

**Describe your issue**
Problem in VSC `Expected >svelte(unexpected-token)`

```html
<script lang="ts">
let messageHasValue = true
</script>

<div class="bg-gray-900"
  <div class="text-gray-200" class:bg-gray-900/10={messageHasValue}
    some content
  </div>
</div>
```

### Reproduction

```html
<script lang="ts">
let messageHasValue = true
</script>

<div class="bg-gray-900"
  <div class="text-gray-200" class:bg-gray-900/10={messageHasValue}
    some content
  </div>
</div>
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 3.00 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33 
    @sveltejs/kit: next => 1.0.0-next.297 
    svelte: ^3.44.0 => 3.46.4
```

Escaping the slash does not work either.

### Severity

annoyance

**Comment by geoffrich** [comment] 2022-03-15 18:41
Duplicate of https://github.com/sveltejs/svelte/issues/4072.

**Closed by geoffrich** 2022-03-15 18:41 UTC
