### ISSUE TITLE
External script work with hydration

### ISSUE THREAD

**Issue by Andre7th** [sveltejs/kit#9001] opened 2023-02-11 15:29 UTC
The external scripts only load once in the first page, the rest pages require to reload the external script because hydration.

**Comment by Conduitry** [comment] 2023-02-11 15:53
This isn't a reproduction.

**Comment by Rich-Harris** [comment] 2023-02-11 16:09
It also sounds like it's working as expected. Of _course_ your external scripts don't reload when you navigate client-side. Why would you want them to?

**Comment by Andre7th** [comment] 2023-02-11 18:45
First i would like to thank for the response from the two most High Contributors!
The reason which i report that is because some ui libraries need to load external js, Flowbite ui is one of them, this project has two option to integrate to Sveltekit:
- From dedicated component(in progress)
- Second from external js script imported to body
I prefer the second option for more customizability, in this case they suggest:

_"If you are using Flowbite.js, you need to add rel="external" to the link tag for pages using Flowbite interactivities.

<a rel="external" href="path">Path</a>

By default, the SvelteKit runtime intercepts clicks on <a> elements and bypasses the normal browser navigation for relative (same-origin) URLs that match one of your page routes. — SvelteKit doc Adding a rel=external attribute to a link will trigger a browser navigation when the link is clicked."_

**Comment by dummdidumm** [comment] 2023-02-11 19:55
So you would like to run the script that is run once again after navigation because..? Flowbite does not notice that new elements are added and doesn't run again? How would it work for flowbite components who only render after some if-condition becomes true? Wouldn't they suffer from the same problem? If sounds like flowbite should notice that it should rerun whatever logic it has again

**Comment by Rich-Harris** [comment] 2023-02-12 19:12
> Adding a rel=external attribute to a link will trigger a browser navigation when the link is clicked

Oof, that is _horrible_ advice. Please don't do that! Flowbite really needs to offer an API for doing whatever initialization work currently requires the script to be re-executed (not just for SvelteKit, but for any integration that isn't already covered by a dedicated component library), though it sounds like `flowbite-svelte` is a better option.

I'm going to close this as it's very much a Flowbite issue rather than a SvelteKit issue — the framework is working as intended.

**Closed by Rich-Harris** 2023-02-12 19:12 UTC
Labels: awaiting submitter
