### ISSUE TITLE
Svelte HMR fails to reload page on Windows

### ISSUE THREAD

**Issue by asv7c2** [sveltejs/kit#871] opened 2021-04-04 18:25 UTC
**Describe the bug**
SvelteKit fails to reload page when navigate to page through address bar.

**Logs**
```
Failed to load resource: the server responded with a status of 404 (Not Found)
client:190 [hmr] Failed to reload D:\Dev\test\src\routes\page.svelte. This could be due to syntax errors or importing non-existent modules. (see errors above)
```

**To Reproduce**
1. npm init svelte@next
2. create any page in routes (ex. page.svelte)
3. navigate to this page through address bar
4. try modify page.svelte content
5. sveltekit throws error 404 and page is not refresh / reloading.

I am using windows. Maybe it only windows related issue. Someone need check on other os.

**Expected behavior**

**Stacktraces**
**Information about your SvelteKit Installation:**

**Severity**

**Additional context**

**Comment by benmccann** [comment] 2021-04-04 21:24
There's not enough info here to reproduce your error. E.g. what did you put in `page.svelte`?

Have you read the section about fallthrough routes? I wonder if that might be why you're seeing a 404. https://kit.svelte.dev/docs#routing-advanced-fallthrough-routes

**Comment by asv1** [comment] 2021-04-05 05:11
@benmccann 
[repo](https://github.com/asv1/svelte_bug_3)

steps:

1. npm run dev
2. open localhost:3000 (it must be opened first)
3. now in address bar enter localhost:3000/page
4. try modify page.svelte content
5. 404 error in console (hmr failed to update page)

If you go through link on index page, there no error will be.

**Comment by rmunn** [comment] 2021-04-06 04:38
Ran your https://github.com/asv1/svelte_bug_3 reproduction and followed those steps, and the HMR worked for me. I made sure to run "npm run dev" and open localhost:3000 first, and then type localhost:3000/page into the address bar. Then I edited page.svelte in VS Code and saved it, and when I looked back at my browser tab the new contents were there, with a message in the console that HMR had updated.

So I can't reproduce this with the repro in https://github.com/sveltejs/kit/issues/871#issuecomment-813186776

**Comment by pilt** [comment] 2021-04-06 06:57
First, thanks for Svelte kit!

I'm seeing the same thing on Windows. 

On `routes/index.ts` it works. The HMR websocket (?) receives 

```json
{"type":"update","updates":[{"type":"js-update","timestamp":1617691304457,"path":"/src/routes/index.svelte","acceptedPath":"/src/routes/index.svelte"}]}
```

followed by the browser fetching `http://localhost:3000/src/routes/index.svelte?import=&t=1617691793176` and a 200 OK response.
.

If I change a custom route in `routes/admin.svelte` and I visit `/admin` in the browser the websocket receives

```json
{"type":"update","updates":[{"type":"js-update","timestamp":1617691416531,"path":"C:\\Users\\SUBPATH_HERE\\src\\routes\\admin.svelte","acceptedPath":"C:\\Users\\SUBPATH_HERE\\src\\routes\\admin.svelte"}]}
```

followed by a GET on `http://localhost:3000/:/Users/SUBPATH_HERE/src/routes/admin.svelte?import&t=1617691416531` that 404s.

My guess is that the refresh path sent to the browser should be relative and that the component responsible for making paths relative is broken somehow. I presume there is special handling for `index.svelte` as it attaches to `/` versus other paths that attach to their relative path excluding extension (`admin.svelte` at `/admin`) but this is also a guess.

**Comment by rmunn** [comment] 2021-04-06 08:25
My failure to reproduce was on Linux, so I think it's a Windows-only thing. The `/:/` part of the URL that starts with `http://localhost:3000/:/Users/` looks like an invalid URL to me, and is probably what's causing the 404. So the thing to figure out is why/how that invalid URL is being constructed.

**Comment by DrewDaPilot** [comment] 2021-04-06 14:32
Interestingly I had a similar issue but it was solved through to use of `optimizeDeps: Object.keys(pkg.dependencies)`. Other users on the discord who encountered a similar error also said that this fixed it for them, though im not entirely sure how or why it fixes it. It cant hurt to give it a try.

**Comment by benmccann** [comment] 2021-04-06 16:16
@asv1 could you confirm if you're running on Windows? (this is exactly why we ask users to provide the output of ``npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`` in the issue template. It's a bit annoying that you didn't bother to fill it out)

**Comment by asv1** [comment] 2021-04-06 16:20
@benmccann 
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 12.91 GB / 15.93 GB
  Binaries:
    Node: 14.16.0 - d:\portable\node\node.EXE
    npm: 6.14.11 - d:\portable\node\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.771
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.64 => 1.0.0-next.71
    svelte: ^3.36.0 => 3.37.0
    vite: ^2.1.4 => 2.1.5
```

**Comment by DrewRidley** [comment] 2021-04-09 18:19
My solution I used last time no longer seems to work and I have the same bug. Any further investigations would be appreciated.

**Comment by bailletced** [comment] 2021-04-30 08:46
```
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 917.75 MB / 15.84 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE      
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Edge: Spartan (44.19041.1.0)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5
```

Adding `optimizeDeps: Object.keys(pkg.dependencies || {})` in the config under vite solved the issue for me.

**Comment by GrygrFlzr** [comment] 2021-04-30 09:06
@bailletced both kit and vite are quite outdated in your example, can you still replicate the issue on `@sveltejs/kit 1.0.0-next.93` and `vite 2.2.3`?

**Comment by bailletced** [comment] 2021-04-30 09:21
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 722.20 MB / 15.84 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE      
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1.0)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.93 => 1.0.0-next.93
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.2.3 => 2.2.3
```
I can still replicate the issue. 
From what I am noticing, if I run `npm run dev` on a already opened page, it will be reloaded by the HMR. However, all the other ones will trigger a 404 error. 
If no page are opened, only the main index page will be refreshed by the HMR.
It might seems kinda weird by this is what I am noticing.

**Comment by jasonlyu123** [comment] 2021-05-07 02:13
The problem I encounter only happens to the routes files. Those with dynamic parameters are most likely to reproduce. 

Don't know if this is the core problem. But when I replace the windows path separator with `/` in this line: https://github.com/sveltejs/kit/blob/d31eb667115f3bd1058a24eac8410a41f2e69c6f/packages/kit/src/core/dev/index.js#L194
It seems to solved the problem I encountered.

**Comment by jasonlyu123** [comment] 2021-05-13 05:18
The problem I encounter is mostly with route components. Most consistently reproducible with those `[slug].svelte` routes.

Don't know if this is the core cause. But when I replace the `url` with `id` in these two lines
https://github.com/sveltejs/kit/blob/d965557112136a6ee4fce7c149c329a39758dbfd/packages/kit/src/core/dev/index.js#L197-L198

It seems to resolve the problem I encounter. The example on the documentation of vite also doesn't use the full system path with this method. Maybe vite doesn't handle the full system path in the method on windows very well.

**Comment by mschuepbach** [comment] 2021-08-08 10:40
I am able to reproduce this issue on Linux if I add the new page **after** the dev server has been started. It works if I restart the dev server.
```
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 10.13 GB / 15.62 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.5.0 - /usr/bin/node
    npm: 7.20.2 - /usr/bin/npm
  Browsers:
    Firefox: 90.0.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.142 
    svelte: ^3.34.0 => 3.42.1
```

**Comment by jasonlyu123** [comment] 2021-08-09 14:42
I think the problem I am encountering at the time is fixed. I can't reproduce it in the latest version. vite seems to prefix the file system path with `fs`. vite also would force a full-page reload while error in the HMR. So it's at least not that confusing as before. 
Is anyone still experiencing this?

**Comment by benmccann** [comment] 2021-08-09 21:18
Ok, I'll close this then since most of the reports are from months ago

**Comment by Middlerun** [comment] 2021-08-10 08:24
This is still an issue. I was looking into it last night but I think it will require an understanding of Vite and HMR which I don't have.

All I was able to determine is that the error is happening [here](https://github.com/vitejs/vite/blob/5c0f0a362f669e3d38ddc51bfdd9d424a7c08feb/packages/vite/src/client/client.ts#L334). The code is assuming the file path is Unix-style and begins with a `/`, so it removes the first character and appends it to the URL base to create a URL. But under certain circumstances, the path is absolute. So a path in Windows e.g. `D:/Code/svelte/kit/examples/hn.svelte.dev/src/routes/mycomponent.svelte` has the first character removed and is turned into a URL like `http://localhost:3000/:/Code/svelte/kit/examples/hn.svelte.dev/src/routes/mycomponent.svelte?import&t=1628582387459`.

If I try the same thing in WSL it also uses absolute file paths in some requests, but they work fine. So it's not necessarily wrong that it's doing that, it could just be that the code in `client.ts` isn't handling Windows-style paths properly.

I found it hard to reliably reproduce the issue with the steps above, but I came up with the following steps that seem to work every time (using the `hn.svelte.dev` example app):

- Create new route component with some markup but no style tag
- Start app with pnpm dev
- Navigate to the route
- Add a style tag with a style in it and save the file
- The failed request will appear in the network tab

**Comment by jasonlyu123** [comment] 2021-08-10 13:50
@Middlerun Are you using the latest commit and dependencies? I can reproduce the problem with your repro steps with an old build of kit on my pc. But after pulling the latest commit and updating dependencies I no longer can reproduce it.

**Comment by Middlerun** [comment] 2021-08-11 09:26
I was on a commit that was a couple of days old, but I just pulled the latest version and it's still happening for me. Did you create a new component when you tried it again? For whatever reason it only seems to happen with newly-created files.

**Comment by benmccann** [comment] 2021-08-11 13:33
The newly created file thing might be a separate issue. It be good to test that on non-Windows machines as well. I think people have mentioned that before. I can't remember if there's an open issue for it or not

**Comment by tonborzenko** [comment] 2021-08-18 18:50
It is still an issue! Broken hmr for windows.
in terminal:
`[vite] hmr update C:\Users\anstak\job\projects\linkphone\src\routes\gen\youtube.svelte`
in browser: 
```
client.ts:334 GET http://localhost:3000/:/Users/anstak/job/projects/linkphone/src/routes/gen/youtube.svelte?import&t=1629312502947 net::ERR_ABORTED 404 (Not Found)

client.ts:36 [hmr] Failed to reload C:\Users\anstak\job\projects\linkphone\src\routes\gen\youtube.svelte. This could be due to syntax errors or importing non-existent modules. (see errors above)
```

**Comment by tonborzenko** [comment] 2021-08-18 18:54
@benmccann maybe change status to 'Opened'? Because the bug has existed for a long time and has not been resolved

**Comment by fjdumont** [comment] 2021-08-18 20:15
I can confirm the behavior on Windows. Does it help if I publish a (bloated) repo and reproduction steps or do we have sufficient details?

I could also try to get my feet wet myself, but be aware I'm not familiar with Svelte internals, nor vite. Somebody will have to guide me into a direction.

**Comment by jasonlyu123** [comment] 2021-08-18 22:56
Turn out that I said about the `fs` prefix only applies to CSS. And about the route component, it seems to only happen to a new route.  

After some digging, I presume it's the same as the original issue. It seems like the route files have been loaded by the dev server twice. One with a full system path like `C:\\path\\to\\src\\routes\\a.svelte` and one with an absolute URL to the workspace like `/src/routes/a.svelte`. The latter is presumably imported by the generated manifest file, and the other is by the `load_component` method.  If the windows path one was loaded later, the problem would happen. So maybe the original issue isn't fixed. It is just being hidden by a race condition in my case. It might still happen to someone else in the existing routes. Don't know, since there might be a race condition.  

That being said. I did found a workaround for this problem, We can normalize the `node.url` ourselves with `'/' + id` after this line
https://github.com/sveltejs/kit/blob/9c8f0741cce5b909adf24d34d5c65cdfc4dd6655/packages/kit/src/core/dev/index.js#L401

 I tried it and, unlike my previous workaround, all the tests still passed. Though it's not a clean solution. I think workaround it by now and if vite fix it in their side. We can remove the workaround.

**Comment by jasonlyu123** [comment] 2021-08-28 04:34
@benmccann I don't think that's related. From my understanding, the problem isn't the module cache not being updated in the server. But rather an update did being send to the client, but the URL is a windows path. Then the vite client made a false [assumption](https://github.com/sveltejs/kit/issues/871#issuecomment-895833258) that the URL always started with a `/`, so it slices the URL and sends a dynamic import to the server with something like this: `http://localhost:3000/:/some/path/to/the/module`. 

And in the `load_component` method, we use a windows path in the `ssrLoadModule` to load the module. the path would be passed to the `ModuleNode` class in vite. Resulting in the windows path being passed to HMR update. 

So the easiest way to fix it is probably we just don't use a full system path in the [`load_component`](https://github.com/sveltejs/kit/blob/e21892b6f1a31e80910971a32a149caf0361435b/packages/kit/src/core/dev/index.js#L400) method. Now I look into it again, I found that the test failure I had before it's just me being dumb, and port 3000 is occupied by another process. We can just use the url absolute to the current work directory to load the module. i.e. ``/${id}`` in the `load_component` method. 
```diff
load_component: async (id) => {
-	const url = path.resolve(cwd, id);
+	const url = `/{id}`;
```

@benmccann What do you think? should we just change it like this? Or do you prefer to solve it on the vite side? 
Also, Would be appreciated if anyone can try if the change I proposed fixed your problem.

**Comment by benmccann** [comment] 2021-08-28 14:24
I think the issue is probably on our side. I see down below in `load_component` that we have:
```
let entry = `/${id}`;
```

So making it so that we also call `ssrLoadModule` in a way that Vite expects as you've suggested sounds like a good fix to me

**Closed** 2021-08-29 05:10 UTC
Labels: help wanted, windows

**Comment by secretgspot** [comment] 2022-10-01 22:32
don't know if it will help further isolation of the problem but for me it was:

SomeComponent.svelte  in libs folder, and by mistake I imported it as such;
```js
import SomeComponent from '$lib/someComponent.svelte';
```
my IDE didn't say anything and component appeared as it should, but anytime I made changes to it, none were reflected unless I terminated npm run dev and ran it again.  the moment I imported it correctly is when issue resolved itself.
