### ISSUE TITLE
Is it possible to exclude +page.test.ts ?

### ISSUE THREAD

**Issue by frck006** [sveltejs/kit#7121] opened 2022-10-02 11:18 UTC
### Describe the problem

Sveltkit fails with this message:

error when starting dev server:
Error: Files prefixed with + are reserved (saw src/routes/**+page.test.ts**)
    at analyze (file:///C:/_app/frontend/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:383:10)

### Describe the proposed solution

Possibility to exclude some files

### Importance

nice to have

### Additional Information

Not really important, it's just to have 
+page.svelte
+page.test.ts
close together in explorer.
![image](https://user-images.githubusercontent.com/10244725/193451204-66305e47-94d1-4d12-9726-61734cf43016.png)

**Comment by madeleineostoja** [comment] 2022-10-03 20:51
I think sveltekit should continue treating all files with the + prefix as special route files and throw this error. The whole point of having runes in route file names was to delineate them as special for sveltekit, this would undo that and at that point why have a weird prefix for files at all

**Comment by frck006** [comment] 2022-10-04 07:57
@madeleineostoja so what you suggest to call file name for tests of "+page.svelte" ? Simply like "page.test.ts ?
Do you have recommendations ?

**Comment by gterras** [comment] 2022-10-17 10:55
By simply removing `+` and adding a `test` or `spec` suffix to any file you would get a comprehensive structure. I'm not sure where the problem is here. Keeping `+` for non-router files would be incredibly confusing.

**Comment by madeleineostoja** [comment] 2022-10-18 23:13
agree, dunno why this is still open

**Comment by dummdidumm** [comment] 2022-10-19 13:25
Closing as we reached consensus that we don't want to make an exception for tests here.

**Closed by dummdidumm** 2022-10-19 13:25 UTC
