### ISSUE TITLE
error rendering +layout.js does not work at page root (and weird behaviours)

### ISSUE THREAD

**Issue by schen96** [sveltejs/kit#12034] opened 2024-03-25 03:59 UTC
### Describe the bug

Hello, 

I am experiencing some unexpected behavior with svelte and its not clear to me at the moment if its just gaps in my knowledge or legitimate unexpected behavior. 

I am on sveltekit 

I am creating a SPA with the following project structure

```
src\
    routes\
        +error.svelte
        +layout.js
        +layout.svelte
        +page.svelte
```
 
 In `+layout.js` I have this
 
 ```javascript
import {error} from "@sveltejs/kit";

export const ssr = false;

export const load = async () => {
    // try to get context
    console.log("throwing error")
    throw error(400, {message: "test"})
  }
}
 ```
 
 My +page.svelte is
 
 ```javascript
 <h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
 ```
 
 My +layout.svelte is
 ```javascript
 <h1>Layout</h1>
<slot/>
 ```
 
 What I expect is my +error.svelte page to display, but nothing happens. 
 I also notice that layout.js is actually called twice when error is thrown.  
 
 Am I missing something or is this unexpected behavior?

### Reproduction

repo
https://github.com/schen96/sveltekit-error-demo

### System Info

```Shell
System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 38.79 GB / 62.73 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 122.0.6261.128
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
    @sveltejs/kit: ^1.5.0 => 1.30.4 
    svelte: ^3.54.0 => 3.59.2 
    vite: ^4.3.0 => 4.5.3 

```
```


### Severity

serious, but I can work around it

### Additional Information

_No response_

**Comment by rmunn** [comment] 2024-03-25 04:48
This is expected behavior, and you're simply not quite understanding the process yet. https://kit.svelte.dev/docs/routing#error says:

> If the error occurs inside a `load` function in `+layout(.server).js`, the closest error boundary in the tree is an `+error.svelte` file _above_ that layout (not next to it).

Since the error was thrown in your root layout function, there's no `+error.svelte` page that is able to handle it. Therefore, Svelte-Kit renders the fallback error page, as mentioned in this part of the docs just above the part I cited:

> ... if the error was thrown from the `load` function of the root `+layout`, which sits 'above' the root `+error`, SvelteKit will bail out and render a static fallback error page, which you can customise by creating a `src/error.html` file.

I hope I've helped you understand the documentation a little better. Closing this issue as this is not a bug, but feel free to open a new issue if it turns out there's something actually wrong.

**Closed by rmunn** 2024-03-25 04:48 UTC
