### ISSUE TITLE
Woocommerce plugin import error

### ISSUE THREAD

**Issue by Chandima-R** [sveltejs/kit#4537] opened 2022-04-06 05:18 UTC
Good day to all,

### Since I have tried to intergrate  woocommerce api to my sveltekit application it shows the following error.

> 500
Cannot read properties of undefined (reading 'from')
TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/.pnpm/safe-buffer@5.1.2/node_modules/safe-buffer/index.js (http://localhost:3000/node_modules/.vite/deps/@woocommerce_woocommerce-rest-api.js?v=79c5c096:1064:16)
    at __require2 (http://localhost:3000/node_modules/.vite/deps/chunk-UVCHOOE4.js?v=79c5c096:32:50)
    at node_modules/.pnpm/create-hmac@1.1.7/node_modules/create-hmac/legacy.js (http://localhost:3000/node_modules/.vite/deps/@woocommerce_woocommerce-rest-api.js?v=79c5c096:1469:18)
    at __require2 (http://localhost:3000/node_modules/.vite/deps/chunk-UVCHOOE4.js?v=79c5c096:32:50)
    at node_modules/.pnpm/create-hmac@1.1.7/node_modules/create-hmac/browser.js (http://localhost:3000/node_modules/.vite/deps/@woocommerce_woocommerce-rest-api.js?v=79c5c096:5406:18)
    at __require2 (http://localhost:3000/node_modules/.vite/deps/chunk-UVCHOOE4.js?v=79c5c096:32:50)
    at http://localhost:3000/node_modules/.vite/deps/@woocommerce_woocommerce-rest-api.js?v=79c5c096:6070:34

I tried multiple other plugins which communicate with WooCommerce and they all give this error. But other plugins like lodash works.

### Reproduction

*https://github.com/Chandima-R/svelte-test-project*
When I trying to import the woocommerce-rest-api library it shows the above error that 'Cannot read properties of undefined (reading 'from')' . After several tries I found that error was origin from the import statement.

### System Info

```shell
>System:
    OS: Linux 5.15 Ubuntu Jammy Jellyfish (development branch) 22.04 (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 8.56 GB / 15.53 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.60
    Firefox: 99.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.307 
    svelte: ^3.44.0 => 3.46.6
```

### Severity

blocking all usage of SvelteKit

**Comment by bluepuma77** [comment] 2022-04-06 06:51
Where is the import statement in your code? 

You make it way easier for others when you provide a version with [node.new/sveltekit](https://node.new/sveltekit).

Should the package only be used within the backend server? I would recommend to check that you import the WooCommerce package within a .js/.ts file that is only used in the backend or use <script context="module"> in a .svelte file.

**Comment by Rich-Harris** [comment] 2022-04-06 15:57
I'm sorry but the maintainers aren't going to investigate a repro like that. Repros must be [short, self-contained and correct](http://sscce.org/) — it's unfair to just paste a link to your project and expect overworked maintainers to do the detective work of narrowing it down to the actual problem. When I open that link the first thing I see is stuff like Tailwind and PostCSS config, and the `src` folder contains a bunch of different components that aren't relevant.

Side-note: a file like [src/routes/MainCarousel.svelte](https://github.com/Chandima-R/vishwarekha/blob/main/src/routes/MainCarousel.svelte) will create a route called `/MainCarousel`; I'm fairly sure that's not what you want. Use [lib](https://kit.svelte.dev/docs/modules#$lib) or [private modules](https://kit.svelte.dev/docs/routing#private-modules).

Feel free to open a new issue once you've prepared a useful reproduction.

**Comment by Chandima-R** [comment] 2022-04-07 09:41
@Rich-Harris,
I’m really sorry about the link. It was my mistake. I did tried to update the issue with the link to my minimal repo showing the error but it haven’t gone through. I’m really sorry. Just updated the issue. I think I found the problem! Will update the issue as soon as I confirm it.

**Comment by dummdidumm** [comment] 2022-04-07 16:32
Reopening because the repro is now the required minimum.

**Comment by bluwy** [comment] 2022-04-11 06:14
On Safari, I get a nicer error message:

```
500
undefined is not an object (evaluating 'Buffer.from')
```

The error comes from the `safe-buffer` dep which `@woocommerce/woocommerce-rest-api` uses, which in turns uses the nodejs `buffer` module, which doesn't exist in the browser. Please open an issue [there](https://github.com/woocommerce/woocommerce-rest-api-js-lib) to avoid using nodejs modules as newer bundlers are starting to avoid polyfilling them too.

You can check this [discussion](https://github.com/vitejs/vite/discussions/2785) for workarounds for now. Closing as it's a Vite issue.

**Closed by bluwy** 2022-04-11 06:14 UTC

**Comment by saroroce** [comment] 2024-12-26 04:05
I don't know if you need it but i found fix

npm install buffer stream-browserify events

import { defineConfig } from 'vite';

export default defineConfig({
  resolve: {
    alias: {
      buffer: 'buffer/',
      stream: 'stream-browserify',
      events: 'events/',
    },
  },
});
