### ISSUE TITLE
Custom Server - Using helmet cause page refresh on each page navigation

### ISSUE THREAD

**Issue by slier81** [sveltejs/kit#4766] opened 2022-04-28 03:39 UTC
### Describe the bug

clicking on any link causing full page reload

Create this folder structure `tree Demo`
├───client
└───server

`cd client && npm init svelte .` ( and choose skeleton demo app )
`npm install` (install dependency)
`npm install @sveltejs/adapter-node` (install node adapter)

Edit `svelte.config.js` (use below code)

```
import adapter from '@sveltejs/adapter-node';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter({
			out: 'build'
		}),

		// Override http methods in the Todo forms
		methodOverride: {
			allowed: ['PATCH', 'DELETE']
		}
	}
};

export default config;
```

Run `npm run build`  there will be `build` folder created

## Now onto server part

`cd .. && cd server`
`npm init -y && npm i express helmet`
`touch app.js` and put following code

```
import helmet from "helmet";
import express from "express";

import { handler } from "./../client/build/handler.js";

const app = express();

app.use(helmet());
app.use(express.json());

app.use("/health", (req, res) => {
  res.send("ok");
});

app.use(handler);

app.listen(3000, () => {
  console.log("server running on port 3000");
});

```

Set `type:module` in package.json

```
{
  "name": "server",
  "version": "1.0.0",
  "dependencies": {
    "express": "^4.18.0",
    "helmet": "^5.0.2"
  },
  "type": "module"

}
```

Run `node app.js`
Try navigate between home and about page

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 8.56 GB / 19.88 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.50)
    Internet Explorer: 11.0.19041.1566
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment] 2022-04-28 05:30
Please provide a complete minimum reproduction. The code snippet is not enough, you didn't say where to put it and when/how it's used.

**Comment by slier81** [comment] 2022-04-28 06:24
@dummdidumm sorry about that.. i have updated my first post to provide you with minimum reproducible code

**Comment by tcc-sejohnson** [comment] 2022-04-28 07:18
@dummdidumm 

[Here's a complete repro.](https://github.com/tcc-sejohnson/kit-helmet-repro)

Reading the Helmet docs, this line:

```ts
app.use(helmet());
```

is the same as this:

```ts
app.use(helmet.contentSecurityPolicy());
app.use(helmet.crossOriginEmbedderPolicy());
app.use(helmet.crossOriginOpenerPolicy());
app.use(helmet.crossOriginResourcePolicy());
app.use(helmet.dnsPrefetchControl());
app.use(helmet.expectCt());
app.use(helmet.frameguard());
app.use(helmet.hidePoweredBy());
app.use(helmet.hsts());
app.use(helmet.ieNoOpen());
app.use(helmet.noSniff());
app.use(helmet.originAgentCluster());
app.use(helmet.permittedCrossDomainPolicies());
app.use(helmet.referrerPolicy());
app.use(helmet.xssFilter());
```

Using process of elimination, I figured out that this line is the one actually causing the hard reloads:

```ts
app.use(helmet.contentSecurityPolicy());
```

You can comment that line out, rerun the app, and hard-reload-clear-cache on the site, and it'll work as expected (with non-full-page reloads). Put it back, clear cache and reload, and it fully refreshes. I don't have time to dig in further right now. @slier81, please take some time to play around with the options object for `helmet.contentSecurityPolicy` and see if you can narrow down which option(s) are causing this behavior.

**Comment by tcc-sejohnson** [comment] 2022-04-28 07:51
Turns out I couldn't go to sleep before solving the issue. Stupid brain.

The problem child is the `Content-Security-Policy` header value `script-src`, which is set to `'self'`, and is blocking the loading of an inline script at `client/build/prerendered/index.html:55`. Setting `script-src` to `["'self'", "'unsafe-inline'"]` fixes the issue and allows the client-side router to initialize and navigation to occur.

This is the helmet config that works:
```ts
app.use(
  helmet({
    contentSecurityPolicy: {
      directives: {
        ...helmet.contentSecurityPolicy.getDefaultDirectives(),
        "script-src": ["'self'"],
      }
    },
  })
)
```

Is this an issue? Is there anything to be fixed on the Kit end? I'm not really sure.

**Comment by dominikg** [comment] 2022-04-28 08:33
please check out https://kit.svelte.dev/docs/configuration#csp  
My guess would be that once you set the csp config for kit and disable/remove helmet csp handling it works.

In general you want to avoid using `unsafe-inline` as that defeats the main purpose of having a csp in the first place.

**Comment by Rich-Harris** [comment] 2022-04-28 12:28
Yep, this is expected behavior. Thanks for the repro @tcc-sejohnson

**Closed by Rich-Harris** 2022-04-28 12:28 UTC
