### ISSUE TITLE
preloadData does not report errors from server files

### ISSUE THREAD

**Issue by carmas123** [sveltejs/kit#12472] opened 2024-07-14 13:53 UTC
### Describe the bug

When using the `preloadData` function to preload page data, errors occurring in `+page.server.ts` or `+layout.server.ts` files are not correctly reported in the function's result.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-7retxz?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```Shell
System:
    OS: macOS 13.6.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 3.23 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    pnpm: 9.4.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.4.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.2.2 => 3.2.2 
    @sveltejs/adapter-node: ^5.2.0 => 5.2.0 
    @sveltejs/kit: ^2.5.18 => 2.5.18 
    @sveltejs/vite-plugin-svelte: ^3.1.1 => 3.1.1 
    svelte: ^4.2.18 => 4.2.18 
    vite: ^5.3.2 => 5.3.2
```

### Severity

blocking an upgrade

**Comment by eltigerchino** [comment] 2024-07-14 15:52
closing this in favour of https://github.com/sveltejs/kit/issues/12399 since it has started a discussion for a potential solution. Thank you for creating a reproduction! Do you mind posting it in the other issue?

**Closed by eltigerchino** 2024-07-14 15:52 UTC
Labels: error handling
