### ISSUE TITLE
SSR load function include anchor portion of url

### ISSUE THREAD

**Issue by andykais** [sveltejs/kit#1676] opened 2021-06-11 19:55 UTC
**Is your feature request related to a problem? Please describe.**
I have some data that I want to ssr based on the anchor tag of a url. (In reality, this is a file browser in the browser, and some file paths include `'#'` in them, which are interpreted as anchors.

The load function is passed an arg containing an object `params`, which looks like this:
```js
{
  page: {
    host: 'localhost:3000',
    path: '/display/media/path/to/file',
    query: URLSearchParams {},
    params: { filepath: 'media/path/to/file' }
}
```
where the full url might look like `localhost:3000/display/media/path/to/file#something.jpg` (and the full file path looks like `/media/path/to/file#something.jpg`). I have no way to render any data on the server for this file since the anchor portion of the url is getting chopped off.

**Describe the solution you'd like**
If the `params` object also included an anchor field, this would cover my use case. E.g.
```js
{
  page: {
    host: 'localhost:3000',
    path: '/display/media/path/to/file',
    query: URLSearchParams {},
    params: { filepath: 'media/path/to/file' },
   anchor: 'something.jpg
}
```
alternatively, the anchor could be included on the `params.path` variable, though I imagine this would break some existing projects.

**Describe alternatives you've considered**
move all my rendering to the client. This is an option, but it completely defeats the purpose of using svelte kit. The power (in my opinion) is in rendering as many things before they reach the client as possible. It means less loading states, and less incomplete data states.

Urls could also be escaped (`#` -> `%23`) but this makes urls much less readable as file paths

**How important is this feature to you?**
Important, but not crucial. I can move this logic to the client, or leave a note to users to escape any file urls before hitting them manually. It seems like a win for svelte without much harm though, so I will advocate for it.

**Additional context**
N/A

**Comment by Conduitry** [comment] 2021-06-11 20:00
Duplicate of #1182. This is impossible.

**Closed by Conduitry** 2021-06-11 20:00 UTC
