### ISSUE TITLE
Please notice warning/error in develop mode.

### ISSUE THREAD

**Issue by und3fined** [sveltejs/kit#7381] opened 2022-10-25 01:50 UTC
### Describe the problem

Svelte is blaze fast for new front end. I have big problem after work with Svelte Kit. I work hard ~4 hours per day for re-write my website from Hugo, React to full Svelte Kit (kit).

In develop mode, i have warning for un-use css and it's not problem. 
But my story start when go to Production mode. With Redux-Toolkit. Svelte Kit compiler show error with esm moule. redux not support ESM?. No, compiler can't map redux-rtk to esm module. I need create a wrapper to `@reduxjs/toolkit/dist`
Next, i start enable legacy mode in vite. And `.svelte-kit/output/client/vite-manifest.json` is not found. I can't change any options with svelte.config.js `compilerOptions` :(

After ~7 days for re-write. I back to Next.js with Layout RFC.

### Describe the proposed solution

Please alert any problem with build early. In my case, i can't wait for fixed it

### Importance

would make my life easier

**Comment by benmccann** [comment] 2022-10-25 02:13
Can you share some log messages showing what the error or warning was that you encountered? It would also be helpful if you could provide a repository that reproduces this

**Comment by und3fined** [comment] 2022-10-25 02:25
@benmccann 
```
transforming (572) node_modules/.pnpm/date-fns@2.29.3/node_modules/date-fns/esm/locale/en-US/_lib/match/index.js'default' is not exported by 'node_modules/.pnpm/@reduxjs+toolkit@1.8.6/node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js'
✓ 653 modules transformed.
[vite-plugin-svelte-kit] ENOENT: no such file or directory, open '<PRJECT DIR>/.svelte-kit/output/client/vite-manifest.json'
error during build:
Error: ENOENT: no such file or directory, open '<PRJECT DIR>/.svelte-kit/output/client/vite-manifest.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at client_build_info (file://<PRJECT DIR>/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.525_svelte@3.52.0+vite@3.1.8/node_modules/@sveltejs/kit/src/exports/vite/index.js:173:7)
    at Object.handler (file://<PRJECT DIR>/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.525_svelte@3.52.0+vite@3.1.8/node_modules/@sveltejs/kit/src/exports/vite/index.js:394:20)
    at file://<PRJECT DIR>/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:22710:40
    at async PluginDriver.hookParallel (file://<PRJECT DIR>/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:22632:17)
    at async file://<PRJECT DIR>/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:23763:13
    at async catchUnfinishedHookActions (file://<PRJECT DIR>/node_modules/.pnpm/rollup@2.78.1/node_modules/rollup/dist/es/shared/rollup.js:23088:20)
    at async doBuild (file://<PRJECT DIR>/node_modules/.pnpm/vite@3.1.8_terser@5.15.1/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45826:26)
    at async build (file://<PRJECT DIR>/node_modules/.pnpm/vite@3.1.8_terser@5.15.1/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45662:16)
    at async CAC.<anonymous> (file://<PRJECT DIR>/node_modules/.pnpm/vite@3.1.8_terser@5.15.1/node_modules/vite/dist/node/cli.js:748:9)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by und3fined** [comment] 2022-10-25 02:27
This is my wapper for redux-rtk
```


import * as rtkQuery from '@reduxjs/toolkit/dist/query/index.js';

export const { fetchBaseQuery, retry, createApi, QueryStatus } = ((rtkQuery as any).default ?? rtkQuery) as typeof rtkQuery;
```

```
import * as toolkitRaw from '@reduxjs/toolkit';

export const { createSlice, nanoid, configureStore, createDraftSafeSelector } = ((toolkitRaw as any).default ??
	toolkitRaw) as typeof toolkitRaw;

```

**Comment by und3fined** [comment] 2022-10-25 02:30
@benmccann U can help me fix build with `@vitejs/plugin-legacy`?
I'll wait about 1 day, before moving all the code to Next.js

**Comment by Conduitry** [comment] 2022-10-25 02:40
If you can't provide an actual actionable feature request or a minimal reproduction of something that's throwing an error that you'd like to be more helpful, you might as well start moving all your code to Next.js right now.

**Comment by und3fined** [comment] 2022-10-25 03:01
@Conduitry i can invite me to my project. if can, i'll invite me

**Comment by benmccann** [comment] 2022-10-25 03:14
I'm going to close this as a duplicate of https://github.com/sveltejs/kit/issues/7154. Please try the solution mentioned there: https://github.com/sveltejs/kit/issues/7154#issuecomment-1276404576

**Closed by benmccann** 2022-10-25 03:14 UTC
Labels: awaiting submitter
