### ISSUE TITLE
HTML rendered from the server is cut off

### ISSUE THREAD

**Issue by kristjanmar** [sveltejs/kit#10400] opened 2023-07-17 20:43 UTC
### Describe the bug

Suddenly today I started having an issue with some pages on my site where the HTML delivered from the server is cut off at some random place. This causes the footer of my site to not render and some scripts not to load, so javascript powered features like my search form are not working.

When I do "View Page Source" it shows that the HTML delivered isn't complete. It's missing a big part of the footer and all the code that shows below it.

The site is hosted on Vercel. I already tried updating to the latest SvelteKit and latest Vite. The site is part of a Turborepo monorepo if that matters.

It is only affecting some pages on my site, not all. Here is an example page on my site that is currently affected by this: https://stockanalysis.com/stocks/aapl/dividend/

![image](https://github.com/sveltejs/kit/assets/22234692/d78f883d-85d2-408f-84e2-ac65dc0c45ab)

Navigating away from the page and then back to it via client-side navigation works fine. The HTML is only cut off when visiting the page directly or refreshing it.

If anyone has any ideas of how to fix this then I would be very grateful. This is affecting my production site, on pages that are constantly getting traffic.

### Reproduction

I don't think I can reproduce this, it is happening on my production site that has been running SvelteKit for a very long time without problems. The site is hosted on Vercel.

### Logs

```Shell
There are no console errors and no errors in the network tab.
```

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 851.04 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 9.6.5 - /usr/local/bin/npm
    pnpm: 8.6.7 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 103.1.40.107
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @sveltejs/adapter-vercel: ^3.0.2 => 3.0.2 
    @sveltejs/kit: ^1.22.3 => 1.22.3 
    svelte: ^3.59.2 => 3.59.2 
    vite: ^4.4.4 => 4.4.4
```

### Severity

blocking all usage of SvelteKit

**Comment by kristjanmar** [comment] 2023-07-17 20:46
This is what the footer is supposed to look like: 
![image](https://github.com/sveltejs/kit/assets/22234692/d5999e86-833b-4079-8f08-53491eacf0da)

This is what it looks like now, although sometimes it doesn't render at all if the HTML gets cut off before the footer starts:
![image](https://github.com/sveltejs/kit/assets/22234692/eb502ce5-d02a-423c-a99b-3b4ecc062fc9)

**Comment by ghostdevv** [comment] 2023-07-17 22:07
Hey, we need a minimal reproduction in order to help/fix this issue!

**Comment by timfeid** [comment] 2023-07-18 02:58
i have the same problem today. it randomly works sometimes when i refresh (even in example above)

**Comment by kristjanmar** [comment] 2023-07-18 08:29
> Hey, we need a minimal reproduction in order to help/fix this issue!

I don't know if that is even possible, this only happens to random pages when running on Vercel. My local build works fine. Replicating the pages this is happening on would be very far from a minimal reproduction.

**Comment by kristjanmar** [comment] 2023-07-18 11:10
It's almost as if the function rendering the HTML on the server has a character limit. When I remove something from the HTML, such as tailwind classes or inline svg, then on the next deploy the html reaches further down.

**Comment by timfeid** [comment] 2023-07-18 12:37
hey @kristjanmar, i know this isn't the place but have you figured something out? i see your example works now. just removed some more data?

**Comment by kristjanmar** [comment] 2023-07-18 13:34
> hey @kristjanmar, i know this isn't the place but have you figured something out? i see your example works now. just removed some more data?

The problem is still there, I just figured out a hack to work around it.

What I did was move some tailwind classes into app.css and then moved my header logo's inline svg into a logo.svg file. This reduced the amount of characters in the HTML so now all my main pages are able to render the full HTML file.

I also noticed that some bigger data.json files were getting cut off during client-side navigation, causing app crashes. Reducing the amount of data from those endpoints by adding pagination got them to work again.

I've also sent a support request to Vercel. I have the Pro plan so I should get a response although it may take a while.

> You tested your local build with `vite preview`? How big is the html you are returning?

Yes, I tested it locally with "build" and then "preview". The html files are not massive, most of them in the range of 12-20 KB.

**Comment by bartosjiri** [comment] 2023-07-18 15:20
I have the same issue with a deployment on Vercel.

It is seemingly random when the issue occurs, page load/refresh sometimes works and sometimes not. Was unable to reproduce it locally.

From what I've been able to observe, when the page does not fully load, it does not even try to load the `start.<random>.js`.

Not fully loading:
<img width="1215" alt="image" src="https://github.com/sveltejs/kit/assets/24203905/3ec88158-9dc2-4bc1-a0ff-7245a054c967">

Loading fine:
<img width="1179" alt="image" src="https://github.com/sveltejs/kit/assets/24203905/7954d19c-408e-4fe4-8565-0a2a689cea0a">

**Comment by timfeid** [comment] 2023-07-18 16:11
still looking for a resolution. multiple people have filed a case with vercel. seems like keeping HTML/server data under 50kb is the only reliable solution, so far.

**Comment by tcc-sejohnson** [comment] 2023-07-18 17:41
I'm working with some internal resources at Vercel -- will update here as I get information.

**Comment by jamesv-menklab** [comment] 2023-07-18 17:46
We are seeing this issue here as well.  If there is anything we can do to help with testing please let us know.

**Comment by tcc-sejohnson** [comment] 2023-07-18 18:54
This should be fixed on the Vercel side -- redeploying your site should fix the issue!

**Comment by julian-amaya** [comment] 2023-07-18 19:38
I can confirm it's working now!

**Comment by kristjanmar** [comment] 2023-07-18 20:08
Same here, also working on my end.

**Closed** 2023-07-18 20:30 UTC
Labels: awaiting submitter
