### ISSUE TITLE
Docs take over 10 seconds to load the first time

### ISSUE THREAD

**Issue by Kinrany** [sveltejs/kit#1067] opened 2021-04-17 14:17 UTC
**Describe the bug**
Sometimes it takes between 10 and 30 seconds for https://kit.svelte.dev/docs to load without cache.

It gets faster (~0.6s) if you do that repeatedly.

I noticed it when the "Learn SvelteKit" on https://kit.svelte.dev/ changed the URL but seemed to have no effect otherwise.

Not sure how common the problem is: I managed to reproduce it a few times, then the timing dropped under 1s.

**Expected behavior**
Some options:
 - load the docs in the background
 - load the first page of the docs first, then load the rest in the background
 - add a spinner

**Information about your SvelteKit Installation:**
<details>
  <summary>Diagnostics</summary>

- Firefox Developer Edition 88.0b9

- Windows 10, build 19041
</details>

**Severity**
Zero impact for me personally. Might confuse or give a bad impression to new users.

**Comment by samccone** [comment] 2021-04-17 17:58
Hi @Kinrany thanks for filing this! For me in my manual tests I was unable to reproduce this problem on a non-4g connection. To try to reproduce I used webpagetest.org and was also unable to reproduce this performance issue that you are pointing out. https://www.webpagetest.org/result/210417_AiDcWK_17c155baa92adff5f4f5564ebd2a315a/ (on a 4g connection I am seeing 10~ for a cold load but I do not think this is the situation you were reporting)

If possible could you capture a chrome performance trace or lighthouse test of the poor performance and share it? Without this root causing the problem is going to be difficult and as such is not reproducible at the moment.

Thank you.

**Comment by Kinrany** [comment] 2021-04-17 20:31
All of the time was spent in the "Waiting" stage (like in the image below, but over 10s), so shouldn't be a connection issue.

![image](https://user-images.githubusercontent.com/1634186/115125838-81d3f680-9fd3-11eb-8409-3cb01801749a.png)

It feels like some server-side cache only kicked in after a few tries. I don't think it can be reliably reproduced client-side. Changing VPN address or incognito didn't help reproduce.

So yeah, probably not actionable. Just sharing in case someone else runs into this!

**Comment by GreenRobot777** [comment] 2021-04-18 22:18
Nope. 2.91 sec.

Maybe this is need to close for now.

**Comment by benmccann** [comment] 2021-04-19 04:46
I've never hit this either. I'll go ahead and close it for now, but if more people report encountering it we can reopen

**Closed by benmccann** 2021-04-19 04:46 UTC
