### ISSUE TITLE
TODO item trash buttons in the svelte-kit init demo app become unresponsive

### ISSUE THREAD

**Issue by gwk** [sveltejs/kit#2518] opened 2021-09-28 17:04 UTC
### Describe the bug

Following the first-timer instructions, I ran `npm init svelte@next <my-app>` and launched the app using `npm run dev -- --open`. The demo looks very nice, but I noticed some flaky behavior with the todo item trash buttons. They seem to work at first, but after creating a couple of items and clicking around a bit, they appear to become nonfunctional. I experimented with this a bit on Mac, both Safari 15.0 and Chrome 94.0.4606.61, and in both browsers it appears to be mostly broken.

I have easily reproduced this several times. If it turns out that this is less obvious than it seems, I'm happy to attempt a more detailed reproduction.

### Reproduction

```
npm init svelte@next my-app
cd my-app
npm install
npm run dev -- --open
```

Navigate to the TODO section.
Create several todo items, then attempt to delete them and/or check/uncheck completion. After playing around for a few clicks I find that the trash buttons stop working.

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 1.51 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    npm: 7.24.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Safari: 15.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.176 
    svelte: ^3.34.0 => 3.43.0
```

### Severity

serious, but I can work around it

**Comment by baseballyama** [comment] 2021-09-28 17:09
I think this is duplicate of https://github.com/sveltejs/kit/issues/1564

**Closed** 2021-09-28 18:24 UTC
