### ISSUE TITLE
Cookies and locals stay undefined in +server.js

### ISSUE THREAD

**Issue by TomFevrier** [sveltejs/kit#7697] opened 2022-11-16 23:54 UTC
### Describe the bug

While implementing OAuth2 authentication, I am setting `cookies` and `locals` at a given endpoint (i.e. `/login`), but I am unable to access neither of them from another endpoint (i.e. `/callback`) after redirecting to it. Both are `undefined`, even though cookies are set correctly in my browser's dev tools and `path` is set to `'/'`.

Surely I must be missing something. I am still fairly new to SvelteKit, especially with the recent API overhaul, and the docs are not really exhaustive about this. Can anyone help me through this?

### Reproduction

https://stackblitz.com/edit/sveltekit-locals-cookies-example

### System Info

```Shell
System:
  OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Memory: 7.21 GB / 15.57 GB
  Container: Yes
  Shell: 5.8.1 - /usr/bin/zsh
Binaries:
  Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
  npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
  Watchman: 4.7.0 - /usr/local/bin/watchman
Browsers:
  Chromium: 107.0.5304.110
  Firefox: 107.0
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment] 2022-11-17 13:37
In your repro, you have `cookies.set('bar', ...)` but `cookies.get('foo')` (if you fix it it'll still seem broken in Stackblitz because cookies don't work properly there AFAICT, but it does work).

When you return a redirect, the browser makes a second request for the URL it was redirected to. `locals` doesn't persist between requests, it needs to be recreated.

Closing as everything works as intended

**Closed by Rich-Harris** 2022-11-17 13:37 UTC

**Comment by TomFevrier** [comment] 2022-11-17 15:04
Thank you for your reply, @Rich-Harris. However:
- I fixed the typo and the simple reproducable example now works...
- ...BUT with an actual OAuth2 flow (Twitter), it doesn't. Something very weird happens: accessing the cookie from the load function in `+page.server.js` returns `undefined`... until I restart Vite, then it returns the cookie... but returns `undefined` on each subsequent reload of the page.
I feel like I am going crazy...

On another note, if `locals` doesn't persist between request, what can you use it for? And if not in `locals`, where are you supposed to store, let's say, code challenges (in memory, without using some kind of Redis-like database)?

Sorry if my questions seem naive, as I said I am still new to SvelteKit and SSR in general, and the docs are not really helpful to grasp the concepts.

Thank you for your time, but more importantly thank you for the amazing work on Svelte!

**Comment by Rich-Harris** [comment] 2022-11-20 23:13
> * Something very weird happens: accessing the cookie from the load function in `+page.server.js` returns `undefined`... until I restart Vite, then it returns the cookie... but returns `undefined` on each subsequent reload of the page.

If you can create a repro of this in a new issue, please do!

> On another note, if `locals` doesn't persist between request, what can you use it for?

Anything that persists for the duration of the request. For example:

```js
export async function handle({ event, resolve }) {
  event.locals.user = await getUser(event.cookies.get('sessionid'));
  return resolve(event);
}
```

If you want something to persist between requests then you either need to use a database or store data in cookies.

**Comment by TomFevrier** [comment] 2022-11-21 15:27
@Rich-Harris FYI, I've figured out what the issue was. I was setting the cookies with the `SameSite` attribute set to `'strict'`, but since my `/callback` endpoint is redirected to from a third-party website (Twitter), the cookies were not being sent with the redirection request to my root page. Setting the `SameSite` attribute set to `'lax'` did the trick.

Thank you for your help!
