### ISSUE TITLE
Error resolving module specifier “.prisma/client/index-browser”.

### ISSUE THREAD

**Issue by wvhulle** [sveltejs/kit#4444] opened 2022-03-24 11:25 UTC
### Describe the bug

I have the following error message in my browser upon using sveltekit (adaptor-node) and the command  "`npm run preview`":

`Uncaught TypeError: Error resolving module specifier “.prisma/client/index-browser”. Relative module specifiers must start with “./”, “../” or “/”.`

It references a piece of code that was compiled with "`npm run build`" in `localhost:3000/_app/start-b07b1607.js`:

`...s-d1fb5791.js";import".prisma/client/index-browser";let Be="",et="";function ...`

However, it is unclear why this piece of code was inserted by npm run build. Is there a way to remove it?

### Reproduction

I have tried reproducing this error with using older versions of Prisma, the adaptor and Svelte, switching from pnpm to npm, but nothing helps. I have a MWE repository that comes close to reproducing the error but doesn't actually reproduce it at [https://github.com/wvhulle/prisma-sveltekit-bug-report](https://github.com/wvhulle/prisma-sveltekit-bug-report). 

### Logs

```shell
`Uncaught TypeError: Error resolving module specifier “.prisma/client/index-browser”. Relative module specifiers must start with “./”, “../” or “/”.`
```

### System Info

```shell
System:
    OS: Linux 5.14 Linux Mint 20.3 (Una)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 4.41 GB / 15.37 GB
    Container: Yes
    Shell: 3.4.0 - /usr/bin/fish
  Binaries:
    Node: 17.8.0 - /usr/bin/node
    npm: 8.5.5 - /usr/bin/npm
  Browsers:
    Chromium: 99.0.4844.82
    Firefox: 98.0.2
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.73 
    @sveltejs/kit: next => 1.0.0-next.303 
    svelte: ^3.46.4 => 3.46.4 
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment] 2022-03-24 12:10
What does "comes close" mean? We'll need a reproduction of what you're seeing in order to investigate anything.

**Comment by wvhulle** [comment] 2022-03-24 12:20
I understand, I am still trying to reproduce in the MWE what I am seeing in the actualy build.

**Comment by wvhulle** [comment] 2022-03-24 20:09
Okay I found it, there is a problem when you are using Prisma and import an `enum` type.

The code that was the problem was not in the MWE, but was contained in the fragment 

```
import { Configuration } from '@prisma/client';
export function toObject(formData) {
	// console.log("formData", formData)
	const object: any = {};
	formData.forEach((value, key) => {
		console.log(`key: ${key}, value: ${value}`);
		if (value === "series") {
			object[key] = Configuration["series"]
		} else if (value === "parallel") {
			object[key] = Configuration["parallel"]
		} else if (!isNaN(Number(value)) && Number(value) !== undefined) {
			object[key] = Number(value)
		} else if (value !== "undefined" && value !== undefined && value !== "") {
			object[key] = value
		}
	}
	);
	return object
}
```

and more specifically  `import { Configuration } from '@prisma/client';`.

**Comment by Rich-Harris** [comment] 2022-04-23 13:38
Closing as there's nothing we can do here - vite doesn't support enums, because esbuild doesn't. Libraries generally shouldn't be distributing code with enums IMHO

**Closed by Rich-Harris** 2022-04-23 13:38 UTC
Labels: awaiting submitter

**Comment by DeepDoge** [comment] 2022-05-24 13:53
`.prisma` is a generated dir, and `index-browser` is a `js` file. 
`index-browser` doesn't have real enums in it, just have objects mapping the enums.
the problem is `.prisma` is not being included on build

And on build we get this warning or message:`transforming (25) node_modules/@prisma/client/index-browser.js'.prisma/client/index-browser' is imported by .prisma/client/index-browser?commonjs-external, but could not be resolved – treating it as an external dependency`
perhaps its a rollup issue?
not sure how to fix it.

**Comment by DeepDoge** [comment] 2022-05-24 16:18
this is not an `enum` issue, `node_modules/.prisma` contains generated js files. `index.js` and `index-browser.js` doesn't have real enums, they only have objects mapping the enums.

**My not too elegant solution:** https://github.com/prisma/prisma/issues/12504#issuecomment-1136126199

**Comment by VitaliiBlack** [comment] 2024-09-22 20:11
Uncaught TypeError: Failed to resolve module specifier "@prisma/client". Relative references must start with either "/", "./", or "../".

**Comment by fjodorsch** [comment] 2025-02-16 17:22
> this is not an `enum` issue, `node_modules/.prisma` contains generated js files. `index.js` and `index-browser.js` doesn't have real enums, they only have objects mapping the enums.
> 
> **My not too elegant solution:** [prisma/prisma#12504 (comment)](https://github.com/prisma/prisma/issues/12504#issuecomment-1136126199)

https://github.com/prisma/prisma/issues/12504#issuecomment-2505171223
This worked for me

**Comment by tajbowness** [comment] 2025-05-01 04:49
> Add `'.prisma/client/index-browser': './node_modules/.prisma/client/index-browser.js',` as a Vite Alias

Like to note, at some point for me, this line caused my builds to fail. It did initially solve the problem discussed here, but for some reason now, having this caused my builds to fail.
