### ISSUE TITLE
SvelteKit CLI weird behavior

### ISSUE THREAD

**Issue by mattcroat** [sveltejs/kit#9321] opened 2023-03-05 14:04 UTC
### Describe the bug

When you run the updated SvelteKit CLI and go through the options it produces this weird behavior.
 
https://user-images.githubusercontent.com/38083522/222964861-368ea902-faec-4c9f-901b-8a13aa85cbc3.mp4

### Reproduction

Run `npm create svelte@latest` or `pnpm create svelte`.

### System Info

```Shell
System:
    OS: Linux 5.15 Manjaro Linux
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 9.4.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Firefox: 110.0
```

### Severity

serious, but I can work around it

**Comment by ignatiusmb** [comment] 2023-03-05 14:42
Duplicate of #9231

**Closed by ignatiusmb** 2023-03-05 14:42 UTC
