### ISSUE TITLE
Navigating between /route and /route#hash breaks intermittently.

### ISSUE THREAD

**Issue by whataboutpereira** [sveltejs/kit#10524] opened 2023-08-10 15:24 UTC
### Describe the bug

When navigating between a route and the same route with hash link, sometimes navigation breaks.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ysligc

When alternating TEST (/test) and ONE (/test#one) links, navigating to ONE (#one) stops working eventually.

It seems to me as if some of the time SvelteKit thinks it's still on /test#one after navigating to /test.

You can unstuck navigation by navigating either once more to /test or navigating to another hash (any except #one).

### Logs

```Shell
No errors in browser logs.
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.22.4 
    svelte: ^4.0.5 => 4.1.2 
    vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

### Additional Information

Sometimes navigating from /test#hash back to /test triggers a full page reload, but I couldn't replicate it on Stackblitz.

**Comment by ollyde** [comment] 2023-08-22 15:55
I also face the same issue, Sveltekit is broken it seems :-/

I noticed it only happens on the root url, or root page.

**Comment by whataboutpereira** [comment] 2023-08-29 13:14
I notice `$page.url.hash` and `window.location.hash` are also going out of sync.
Tested with Chrome in Windows.

**Comment by s3812497** [comment] 2023-10-08 08:40
closed as duplicate of https://github.com/sveltejs/kit/issues/10550

**Comment by s3812497** [comment] 2023-10-08 14:38
closed as duplicate of https://github.com/sveltejs/kit/issues/10234

**Closed by s3812497** 2023-10-08 14:38 UTC
Labels: bug, router

**Comment by whataboutpereira** [comment] 2023-10-10 15:54
I see it's still broken in v1.25.2.

https://stackblitz.com/edit/sveltejs-kit-template-default-utndzs?file=package.json

> When alternating TEST (/test) and ONE (/test#one) links, navigating to ONE (#one) stops working eventually.

I see when it breaks and you click twice on /test, then clicking on /test#one works again (once).

**Comment by scosman** [comment] 2024-07-28 21:03
+1
