### ISSUE TITLE
Import from typescript end point script is resolved to use "browser" export

### ISSUE THREAD

**Issue by damischa1** [sveltejs/kit#1616] opened 2021-05-31 14:59 UTC
**Describe the bug**
When I import a module that has exports of type "browser", "import", "require" in typescript file (endpoint). The browser version gets imported

**To Reproduce**
For example the jwt library @panva/jose has this kind of structure. You can include it in your package.json and test.

**Comment by dummdidumm** [comment] 2021-05-31 15:15
Please provide a more complete reproduction with code snippets.
Likely an upstream issue with Vite.

**Comment by damischa1** [comment] 2021-05-31 19:45
Hello,

I created a test app to verify here:
https://github.com/damischa1/svelte-kit-conditional-export

It was created with:
**npm init svelte@next my-app**
**npm install**

Then I created **node_modules/test_exports** module with conditional exports. The module function **whereami** is imported and executed in **hooks.ts**

Just run **npm run dev** and navigate to localhost:3000

Node is printing **I am in BROWSER**. Expected **I am in NODE**.

I am not sure if the conditional exports are something optional to support and should the support be in Vite or how...

I tried also changing the order of conditionals in **node_modules/test_exports/package.json** and the first options seems to be picked.

**Comment by benmccann** [comment] 2021-06-01 05:48
You should probably also add something at the top level of the `package.json` like:
```
          "browser": "./dist/browser.js",
          "main": "./dist/node.js",
          "module": "./dist/esm.js"
```

**Comment by hgl** [comment] 2021-06-09 07:18
@benmccann packages like `jose` use such `package.json`:

```json
"exports": {
  "./jwt/sign": {
      "browser": "./dist/browser/jwt/sign.js",
      "import": "./dist/node/esm/jwt/sign.js",
      "require": "./dist/node/cjs/jwt/sign.js"
    }
}
```

And `import { SignJWT } from 'jose/jwt/sign'` in an endpoint still imports the browser version.

**Comment by benmccann** [comment] 2021-06-10 05:29
@hgl I expected Vite to look at the top level. I'm not sure whether it would also look in an `exports` map like this. In any case, it's probably best to file this as an issue in the Vite repo. You can use [this project](https://github.com/sveltejs/vite-plugin-svelte/tree/main/packages/playground/vite-ssr) as the base of a project to reproduce the issue without SvelteKit involved

**Comment by JBusillo** [comment] 2021-06-10 06:04
I had replied to the closed duplicate issue #1657 with a possible workaround.  Here's some excerpts:
Change your import to import { SignJWT } from 'jose/dist/node/cjs/jwt/sign'
Here's a [repo](https://github.com/JBusillo/test-1657) which works for me.

My browser shows:
```
This is my header
The JWT is: eyJhbGciOiJIUzI1NiJ9.eyJhIjoxLCJpYXQiOjE2MjMyNzY5Mjd9.LUkbcaLoUc_3hOAhjjaGc7AfhS9kIetKQ7rax1E11cs
This is my footer
```

**Comment by JBusillo** [comment] 2021-06-10 20:09
Before opening up an issue with Vite, let me confirm where/why this error is being generated.  From the debug logs, I see:
```
2021-06-10T19:53:03.616Z vite:vite-plugin-svelte resolveId jose/jwt/sign
2021-06-10T19:53:03.617Z vite:vite-plugin-svelte resolveId did not resolve jose/jwt/sign
2021-06-10T19:53:03.617Z vite:vite-plugin-svelte resolveId /node_modules/.pnpm/jose@3.12.3/node_modules/jose/dist/browser/jwt/sign.js
2021-06-10T19:53:03.617Z vite:transform 1ms   src/routes/mytest/jwttest.js
2021-06-10T19:53:03.618Z vite:vite-plugin-svelte resolveId /node_modules/.pnpm/jose@3.12.3/node_modules/jose/dist/browser/jwt/sign.js
2021-06-10T19:53:03.619Z vite:vite-plugin-svelte resolveId /node_modules/.pnpm/jose@3.12.3/node_modules/jose/dist/browser/jwt/sign.js
2021-06-10T19:53:03.619Z vite:vite-plugin-svelte resolveId /node_modules/.pnpm/jose@3.12.3/node_modules/jose/dist/browser/jwt/sign.js
```
It appears that vite-plugin-svelte might be the culprit -- but I'd like to confirm if any incoming parameters are incorrect.  I'll research further this evening.

**Comment by benmccann** [comment] 2021-06-10 20:35
I don't believe there's anything in `vite-plugin-svelte` that chooses browser vs non-browser implementation. I believe that comes from Vite

https://github.com/sveltejs/vite-plugin-svelte/blob/673cf61b3800e7a64be2b73a7273909da95729d2/packages/vite-plugin-svelte/src/index.ts#L133

**Comment by JBusillo** [comment] 2021-06-10 21:58
You're right, of course.  I was just looking at the log, not where the message was coming from, which was immediately upon entry to the function in `vite-plugin-svelte`.  I'll do a little more investigating, then I'll open the issue in Vite with any updated information (unless someone else beats me to the punch).

**Comment by hgl** [comment] 2021-06-11 06:44
@JBusillo I tried your test repo, and it worked flawlessly for me. I also found out why I initially couldn't get it to work: listing `jose` as a dev dependency was vital, which I missed. This is pretty strange, considering it shouldn't make any difference once the package is installed on the file system. Maybe Vite won't consider browser version for dev dependencies? But if so, it doesn't explain why importing `jose/jwt/sign` still fails in this case.

**Comment by JBusillo** [comment] 2021-06-12 06:54
I filed a vite issue for this -- https://github.com/vitejs/vite/issues/3772

**Comment by hgl** [comment] 2021-06-15 04:56
@benmccann It's probably a silly question, but I wonder why would endpoints go trough vitejs? I believe the code in vitejs pertaining to this issue is at:

https://github.com/vitejs/vite/blob/ce459e3ffee95bac4fbf79d204c8cf65f25c9924/packages/vite/src/node/plugins/resolve.ts#L641

It seems to make sense that vitejs only wants the browser version since the bundled code is meant to be run in browsers.

**Comment by dummdidumm** [comment] 2021-09-17 08:53
The related Vite issue was closed by a PR a while ago, so the original issue should be resolved - closing.

**Closed by dummdidumm** 2021-09-17 08:53 UTC
Labels: vite
