### ISSUE TITLE
Named slots for layouts

### ISSUE THREAD

**Issue by TheHadiAhmadi** [sveltejs/kit#4913] opened 2022-05-13 21:36 UTC
### Describe the problem

svelte has the ability to have named slots for components, sveltekit's layouts doesn't support this feature and only supports `default` slot

```svelte
<!-- /src/routes/__layout.svelte -->
<div>
  <div class="sidebar">
    <slot name="sidebar" />
  </div>
  <slot/>
</div>
```
```svelte
<!-- /src/routes/foo.svelte -->
<div>
  foo Main content
</div>

<div slot="sidebar">sidebar content</div>
```
```svelte
<!-- /src/routes/bar.svelte -->
<div>
  bar Main content
</div>

<div slot="sidebar">different sidebar</div>
```
I know named slots only works when they are direct child of Components, I think sveltekit's structure is same and routes are direct child of layout components

```svelte
<Layout> <!-- /src/routes/__layout.svelte -->
  <Foo/> <!-- /src/routes/foo.svelte -->
</Layout>
```

and implementing something like this is technically possible and I would like to see this feature in sveltekit

### Describe the proposed solution

I don't have any solution for this feature request now, we can discuss about this and would like to know how other frameworks implemented this.

### Alternatives considered

I need to write my layouts in separate component and use that component as a Layout

```svelte
<MyPageLayout>
  <div>
    this is main
  </div>
  <div slot="sidebar">sidebar</div>
</MyPageLayout>
```

### Importance

nice to have

### Additional Information

thanks for creating this awesome project :rose:

**Comment by chvanam** [comment] 2022-05-14 11:56
This resembles twig's block-based `{% block sidebar %}` templating system if I'm not mistaken where you define named blocks in your layout, and can then extend this layout and overwrite those blocks. It is indeed quite extensible.

It can imagine some use cases where it would be nice to have two named slot tags in a `__layout.svelte` file, but you would then have to specify where parts of a given file under that layout go, resulting in two separate 'chunks' that could maybe go in two separate files.

**Comment by Mlocik97** [comment] 2022-05-14 13:41
duplicate of https://github.com/sveltejs/kit/issues/627

**Closed** 2022-05-14 15:00 UTC
