### ISSUE TITLE
Changing the error response code in hooks.server

### ISSUE THREAD

**Issue by beganovich** [sveltejs/kit#9402] opened 2023-03-11 02:00 UTC
### Describe the problem

As of this moment, it's not possible to change the status code of the error in the hooks.server (at least I don't see it, the `Error` interface contains only the `message`).

I understand, that this is "technically" part of [unexpected errors](https://kit.svelte.dev/docs/errors#unexpected-errors), but I still think if I am providing custom logic to "handle my error" I should be at least able to control the status code.

An example of this can be Zod with validation errors. 

+page.server.ts:

```ts
export const load: PageServerLoad = async ({ params }) => {
  const uuid = z.string().uuid().parse(params.uuid);

  // ..
};
```

At this point, Zod will throw `ZodError` and it'd be amazing if we can handle the error with custom response code, which is definitely not 500.

+hooks.server.ts

```ts
export const handleError: HandleServerError = ({ error }) => {
  if (error instanceof ZodError) {
    return { message: 'Whoops, validation issue', code: 422 };
  }

  return { message: 'Whoops, something really bad went wrong.' };
};
```

### Describe the proposed solution

Accept `code` in `Error` interface, so the HTTP response status code isn't hardcoded to 500.

**Comment by aolose** [comment] 2023-03-18 03:14
https://kit.svelte.dev/docs/load#errors
>If an unexpected error is thrown, SvelteKit will invoke [handleError](https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror) and treat it as a 500 Internal Error.

so, try to wrap you error:
```js
import { error } from '@sveltejs/kit';
export const handleError: HandleServerError = ({ error:er }) => {
  if (er instanceof ZodError) {
  throw error(422,'Whoops, validation issue')
  }
  throw error(500, 'Whoops, something really bad went wrong.)
};
```

**Comment by beganovich** [comment] 2023-03-18 14:00
Not sure if I am doing something wrong, but that doesn't work for me.

![image](https://user-images.githubusercontent.com/13711415/226110655-2b7fa9a3-ee22-466d-b2ab-41ec8d0b3b64.png)

**Comment by dummdidumm** [comment] 2023-09-12 18:49
Closing as duplicate of #9188

**Closed by dummdidumm** 2023-09-12 18:49 UTC
Labels: error handling
