### ISSUE TITLE
Seems adapter-node@1.3.0 handler.js does not load in express

### ISSUE THREAD

**Issue by NormandoHall** [sveltejs/kit#10299] opened 2023-07-01 13:16 UTC
### Describe the bug

Upgrading from adapter-node@1.2.4 to 1.3.0, handler.js not runs in expressjs middleware.

### Reproduction

Upgrade to adapter-node@1.3.0 and do `npm run build`

### Logs

```Shell
No error logs
```

### System Info

```Shell
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (4) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 777.02 MB / 15.51 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.20.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.5 - /usr/bin/npm
    pnpm: 8.6.5 - /usr/bin/pnpm
  npmPackages:
    @sveltejs/adapter-node: ^1.3.0 => 1.3.0 
    @sveltejs/kit: ^1.21.0 => 1.21.0 
    svelte: ^4.0.1 => 4.0.1 
    vite: ^4.3.9 => 4.3.9
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment] 2023-07-01 13:23
It works fine for me. Please provide a proper minimal reproduction. "Upgrade to adapter-node@1.3.0 and do `npm run build`" is not a reproduction.

**Comment by NormandoHall** [comment] 2023-07-01 15:29
```js
import { handler } from './build/handler.js';
import express from 'express';
const app = express();

console.log(1);

// add a route that lives separately from the SvelteKit app
app.get('/healthcheck', (req, res) => {
  res.end('ok');
});

// let SvelteKit handle everything else, including serving prerendered pages and static assets
app.use(handler);

app.listen(13030, '127.0.0.1', () => {
  console.log('listening on port 13030');
});
```

With the above code, there is no `1` console output nor `listening on port 13030`

Commenting `import { handler } from './build/handler.js';` and `app.use(handler);` express runs and get the console output 1 and  `listening on port 13030`

**Comment by Conduitry** [comment] 2023-07-01 15:35
That works for me using the default starter `create-svelte` app. We need a reproduction as a minimal clonable repository that demonstrates the issue.

**Comment by NormandoHall** [comment] 2023-07-01 16:11
@Conduitry you are right, with `create-svelte` runs ok. I am investigating why happens this issue, only with 1.3.0. vite and svelte config are ok. Strange. There is no error, nothing. Only no load the custom server.

**Comment by NormandoHall** [comment] 2023-07-01 16:53
Well, I was deleted node_modules, package-lock.json, reinstall npms, delete .svelte-kit a build folders, and still the same issue.

Rolling back to adapter-node@1.2.4 fixes the issue.

I can give you private access to our dev VM to connect your vscode through remote ssh credentials if this can help with the reproduction.

**Comment by ollema** [comment] 2023-07-01 18:13
I'm sorry in advance - but I am in a hurry and I can't provide a better reproduction right now.

With this package.json, I can reproduce the error described by @NormandoHall:
```json
{
	"name": "portal",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write .",
		"generate-schema": "ts-node --esm ./tools/generate-schema.ts && prettier --plugin-search-dir . --write ./src/lib/schema.ts"
	},
	"devDependencies": {
		"@auth/core": "latest",
		"@auth/sveltekit": "latest",
		"@skeletonlabs/skeleton": "^1.8.0",
		"@sveltejs/adapter-node": "^1.3.0",
		"@sveltejs/kit": "^1.21.0",
		"@tailwindcss/forms": "^0.5.3",
		"@types/node": "^20.3.3",
		"@typescript-eslint/eslint-plugin": "^5.60.1",
		"@typescript-eslint/parser": "^5.60.1",
		"autoprefixer": "^10.4.14",
		"eslint": "^8.44.0",
		"eslint-config-prettier": "^8.8.0",
		"eslint-plugin-svelte": "^2.32.2",
		"json-schema-to-zod": "^0.6.3",
		"postcss": "^8.4.24",
		"prettier": "^2.8.8",
		"prettier-plugin-svelte": "^2.10.1",
		"svelte": "^4.0.1",
		"svelte-check": "^3.4.4",
		"tailwindcss": "^3.3.2",
		"ts-node": "^10.9.1",
		"tslib": "^2.6.0",
		"typescript": "^5.1.6",
		"vite": "^4.3.9",
		"zod": "^3.21.4"
	},
	"type": "module",
	"pnpm": {
		"overrides": {
			"@auth/core": "latest",
			"@auth/sveltekit": "latest"
		}
	},
	"dependencies": {
		"simple-git": "^3.19.1"
	}
}
```
when I instead pin `adapter-node` to `1.3.0` I can once again deploy our app:
```json
{
	"name": "portal",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write .",
		"generate-schema": "ts-node --esm ./tools/generate-schema.ts && prettier --plugin-search-dir . --write ./src/lib/schema.ts"
	},
	"devDependencies": {
		"@auth/core": "latest",
		"@auth/sveltekit": "latest",
		"@skeletonlabs/skeleton": "^1.8.0",
		"@sveltejs/adapter-node": "1.2.4",
		"@sveltejs/kit": "^1.21.0",
		"@tailwindcss/forms": "^0.5.3",
		"@types/node": "^20.3.3",
		"@typescript-eslint/eslint-plugin": "^5.60.1",
		"@typescript-eslint/parser": "^5.60.1",
		"autoprefixer": "^10.4.14",
		"eslint": "^8.44.0",
		"eslint-config-prettier": "^8.8.0",
		"eslint-plugin-svelte": "^2.32.2",
		"json-schema-to-zod": "^0.6.3",
		"postcss": "^8.4.24",
		"prettier": "^2.8.8",
		"prettier-plugin-svelte": "^2.10.1",
		"svelte": "^4.0.1",
		"svelte-check": "^3.4.4",
		"tailwindcss": "^3.3.2",
		"ts-node": "^10.9.1",
		"tslib": "^2.6.0",
		"typescript": "^5.1.6",
		"vite": "^4.3.9",
		"zod": "^3.21.4"
	},
	"type": "module",
	"pnpm": {
		"overrides": {
			"@auth/core": "latest",
			"@auth/sveltekit": "latest"
		}
	},
	"dependencies": {
		"simple-git": "^3.19.1"
	}
}
```

with `1.3.0` - I got zero output from my node container. none whatsoever.

maybe this is not very helpful - but at least another data point.

**Comment by NormandoHall** [comment] 2023-07-01 18:23
Thanks @ollema for your report. I pasted here my package.json if this can help

```json
{
  "name": "minerva",
  "version": "1.0.0",
  "author": "Normando Hall",
  "private": true,
  "scripts": {
    "private": "DEBUG='telegraf:main' nodemon bots/private",
    "channels": "DEBUG='telegraf:main' nodemon bots/channels",
    "tasks": "nodemon libs/Tasks",
    "be": "nodemon backend",
    "dev": "vite dev",
    "build": "vite build",
    "package": "svelte-kit package",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json --watch",
    "lint": "eslint ."
  },
  "nodemonConfig": {
    "ignore": [
      "logs/*",
      "build/**",
      ".svelte-kit/**",
      ".vscode/**",
      "node_modules/**",
      "vite.config.js.timestamp-**"
    ]
  },
  "type": "module",
  "dependencies": {
    "@googlemaps/google-maps-services-js": "^3.3.32",
    "@zxing/library": "^0.20.0",
    "ajv": "^8.12.0",
    "ajv-formats": "^2.1.1",
    "axios": "^1.4.0",
    "cookie": "^0.5.0",
    "cookie-signature": "^1.2.1",
    "croner": "^6.0.5",
    "dayjs": "^1.11.9",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "html-to-text": "^9.0.5",
    "imapflow": "^1.0.131",
    "lodash": "^4.17.21",
    "mailparser": "^3.6.4",
    "mediainfo.js": "^0.1.9",
    "mime-types": "^2.1.35",
    "mongodb": "^5.6.0",
    "nodemailer": "^6.9.3",
    "outdent": "^0.8.0",
    "pdfmake": "^0.2.7",
    "qrcode": "^1.5.3",
    "rate-limiter-flexible": "^2.4.1",
    "redis": "^4.6.7",
    "sharp": "^0.32.1",
    "socket.io": "^4.7.1",
    "socket.io-client": "^4.7.1",
    "telegraf": "^4.12.2",
    "telegraf-throttler": "^0.6.0",
    "winston": "^3.9.0",
    "winston-daily-rotate-file": "^4.7.1"
  },
  "devDependencies": {
    "@iconify/json": "^2.2.85",
    "@sveltejs/adapter-node": "^1.3.0",
    "@sveltejs/kit": "^1.21.0",
    "@tailwindcss/forms": "^0.5.3",
    "@tiptap/core": "^2.0.3",
    "@tiptap/extension-bold": "^2.0.3",
    "@tiptap/extension-bubble-menu": "^2.0.3",
    "@tiptap/extension-character-count": "^2.0.3",
    "@tiptap/extension-code": "^2.0.3",
    "@tiptap/extension-document": "^2.0.3",
    "@tiptap/extension-hard-break": "^2.0.3",
    "@tiptap/extension-italic": "^2.0.3",
    "@tiptap/extension-link": "^2.0.3",
    "@tiptap/extension-paragraph": "^2.0.3",
    "@tiptap/extension-placeholder": "^2.0.3",
    "@tiptap/extension-strike": "^2.0.3",
    "@tiptap/extension-text": "^2.0.3",
    "@tiptap/extension-underline": "^2.0.3",
    "@unocss/preset-icons": "^0.53.0",
    "@zerodevx/svelte-toast": "^0.9.4",
    "autoprefixer": "^10.4.14",
    "dompurify": "^3.0.4",
    "eslint": "^8.44.0",
    "eslint-plugin-svelte": "^2.32.2",
    "filepond": "^4.30.4",
    "filepond-plugin-file-validate-size": "^2.2.8",
    "filepond-plugin-file-validate-type": "^1.2.8",
    "filepond-plugin-image-exif-orientation": "^1.0.11",
    "filepond-plugin-image-preview": "^4.6.11",
    "filepond-plugin-media-preview": "^1.0.11",
    "filepond-plugin-pdf-preview": "^1.0.4",
    "flowbite": "^1.6.6",
    "flowbite-svelte": "^0.39.1",
    "howler": "^2.2.3",
    "inputmask": "^5.0.8",
    "leaflet": "^1.9.4",
    "leaflet-extra-markers": "^1.2.2",
    "medium-zoom": "^1.0.8",
    "nodemon": "^2.0.22",
    "postcss": "^8.4.24",
    "print-js": "^1.6.0",
    "rfdc": "^1.3.0",
    "svelte": "^4.0.1",
    "svelte-check": "^3.4.4",
    "svelte-filepond": "^0.2.0",
    "svelte-heros": "^3.12.1",
    "svelte-preprocess": "^5.0.4",
    "svelte-tippy": "^1.3.2",
    "svoast": "^2.2.1",
    "tailwind-merge": "^1.13.2",
    "tailwindcss": "^3.3.2",
    "tippy": "^0.0.0",
    "unocss": "^0.53.4",
    "validator": "^13.9.0",
    "vanillajs-datepicker": "^1.3.3",
    "vest": "^4.6.11",
    "vite": "^4.3.9"
  }
}
```

**Comment by ollema** [comment] 2023-07-01 18:51
Okay, so there is somethings strange going on for sure. Without changing package.json, I managed to get it working by removing routes/hooks/other things from my reproduction repo.

I will try to "bisect" to pin down what is needed to make it _not_work again

**Comment by NormandoHall** [comment] 2023-07-01 19:23
Found it. Thanks for the help Ollema

With this hooks.server.js does not runs:

```js
import { error } from '@sveltejs/kit';

export const handle = async ({ event, resolve }) => {
  return await resolve(event);
};
```

But if commented the import, does runs!

```js
// import { error } from '@sveltejs/kit';

export const handle = async ({ event, resolve }) => {
  return await resolve(event);
};
```

**Comment by ollema** [comment] 2023-07-01 19:42
**Reproduction:**
https://github.com/ollema/node-adapter-repro

Should be able to:
1. Clone the repo
2. Run `docker build -t node-adapter-repro . && docker run --rm -it node-adapter-repro`
3. Notice how the container exits without printing anything

Can you confirm @NormandoHall?

**Comment by NormandoHall** [comment] 2023-07-01 19:57
@ollema yes, there is no output:

```
docker build -t node-adapter-repro . && docker run --rm -it node-adapter-repro
[+] Building 367.1s (14/14) FINISHED
 => [internal] load .dockerignore                                                                                                                                                                                                       0.2s
 => => transferring context: 2B                                                                                                                                                                                                         0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                    0.3s
 => => transferring dockerfile: 711B                                                                                                                                                                                                    0.1s
 => [internal] load metadata for docker.io/library/node:18-bullseye                                                                                                                                                                     2.5s
 => [1/9] FROM docker.io/library/node:18-bullseye@sha256:68682a082afb25f72c4941f2d6f5c063344af02901ee555902869a67461dc391                                                                                                             315.4s
 => => resolve docker.io/library/node:18-bullseye@sha256:68682a082afb25f72c4941f2d6f5c063344af02901ee555902869a67461dc391                                                                                                               0.0s
 => => sha256:de52b24628074d91c1b6455a6b891cdfd3ec71ec8916dda61a73356f4a36f43f 2.00kB / 2.00kB                                                                                                                                          0.0s
 => => sha256:93c2d578e4211e82e47e7ada9ed05d1869a2362c6f7509f2ee8d91ccebfb7fbd 55.06MB / 55.06MB                                                                                                                                      122.2s
 => => sha256:c87e6f3487e1d7e61ee7a415e0ced4eb6f0b3484eb1e15a4339d110d3cadf899 15.76MB / 15.76MB                                                                                                                                       24.8s
 => => sha256:65b4d59f9abaeb4efe1c66ff2176044e93912966342d76d025b6d1a2a37dde7a 54.59MB / 54.59MB                                                                                                                                      137.3s
 => => sha256:68682a082afb25f72c4941f2d6f5c063344af02901ee555902869a67461dc391 1.21kB / 1.21kB                                                                                                                                          0.0s
 => => sha256:c40e0caabcca77b360307e9515d00d9308001f93c12a37c5cc641b17f222b6c6 7.24kB / 7.24kB                                                                                                                                          0.0s
 => => sha256:d7edca23d42bd7903919d8184b978cfe282dbac5a142296e26b4dd53367425f4 196.85MB / 196.85MB                                                                                                                                    303.7s
 => => sha256:25c206b29ffe0e98ff5e9c6359450d67d3691017999f2cc1175c48b941f7c053 4.20kB / 4.20kB                                                                                                                                        122.7s
 => => extracting sha256:93c2d578e4211e82e47e7ada9ed05d1869a2362c6f7509f2ee8d91ccebfb7fbd                                                                                                                                               2.4s
 => => sha256:bdf1a95618f675b55822c42e7c4d84070d68e251e2759e0fa3b07ed6749bcd3d 45.53MB / 45.53MB                                                                                                                                      227.3s
 => => extracting sha256:c87e6f3487e1d7e61ee7a415e0ced4eb6f0b3484eb1e15a4339d110d3cadf899                                                                                                                                               0.5s
 => => sha256:b4675c226ed38d0c140fe99ae1f5c56ae86470cb817ee6d57b4614fe6f19fe42 2.28MB / 2.28MB                                                                                                                                        141.6s
 => => extracting sha256:65b4d59f9abaeb4efe1c66ff2176044e93912966342d76d025b6d1a2a37dde7a                                                                                                                                               2.7s
 => => sha256:dfbe26d2f5fc2fb463c361af023945b654a303ca568d94853e3ac473680bfcee 449B / 449B                                                                                                                                            141.8s
 => => extracting sha256:d7edca23d42bd7903919d8184b978cfe282dbac5a142296e26b4dd53367425f4                                                                                                                                               8.2s
 => => extracting sha256:25c206b29ffe0e98ff5e9c6359450d67d3691017999f2cc1175c48b941f7c053                                                                                                                                               0.1s
 => => extracting sha256:bdf1a95618f675b55822c42e7c4d84070d68e251e2759e0fa3b07ed6749bcd3d                                                                                                                                               2.4s
 => => extracting sha256:b4675c226ed38d0c140fe99ae1f5c56ae86470cb817ee6d57b4614fe6f19fe42                                                                                                                                               0.2s
 => => extracting sha256:dfbe26d2f5fc2fb463c361af023945b654a303ca568d94853e3ac473680bfcee                                                                                                                                               0.0s
 => [internal] load build context                                                                                                                                                                                                       1.7s
 => => transferring context: 101.68MB                                                                                                                                                                                                   1.7s
 => [2/9] WORKDIR /usr/src/app                                                                                                                                                                                                          1.5s
 => [3/9] RUN npm install -g pnpm@8.5.1                                                                                                                                                                                                 5.6s
 => [4/9] COPY pnpm-lock.yaml ./                                                                                                                                                                                                        0.1s
 => [5/9] RUN pnpm fetch                                                                                                                                                                                                               21.0s
 => [6/9] COPY . ./                                                                                                                                                                                                                     1.5s
 => [7/9] RUN pnpm install --offline                                                                                                                                                                                                    2.7s
 => [8/9] RUN pnpm svelte-kit sync                                                                                                                                                                                                      2.8s
 => [9/9] RUN pnpm build                                                                                                                                                                                                               10.6s
 => exporting to image                                                                                                                                                                                                                  2.5s
 => => exporting layers                                                                                                                                                                                                                 2.5s
 => => writing image sha256:7f0f71bc2bb17883f071b8f4eb069ae33080cc237b3a304c38acdeb5cafaa9bc                                                                                                                                            0.0s
 => => naming to docker.io/library/node-adapter-repro                                                                                                                                                                                   0.0s
WARNING: buildx: failed to read current commit information with git rev-parse --is-inside-work-tree
[root@vm-desarrollo node-adapter-repro]#
```

**Comment by gtm-nayan** [comment] 2023-07-02 00:21
Someone on discord said it was stuck on the `await server.init()` line, I'm guessing the bundling probably introduces a circular import between the handler chunk and the hooks file which is dynamically imported inside server.init leading to a deadlock on the await.

Last time me and @dominikg ran into this we used manualChunks to put everything from a dependency into its own chunk. I don't know which one(s) we'd do that for here, so probably need a better way.

**Comment by tiptenbrink** [comment] 2023-07-02 11:18
I'm having the exact same issue. After a whole bunch of debugging, for me it indeed hangs on the server.init. Note that below is generated code, so it might differ per project, but hopefully it will help further pinning the issue down:

The server `init` function (inside the handler chunk file):
```javascript
async init({ env }) {
    ... // omitted
    if (!this.#options.hooks) {
      try {
        const module = await get_hooks(); // ❗ <-- it hangs at this await 
        ... // omitted
      } catch (error2) {
        {
          throw error2;
        }
      }
    }
  }
```

The `get_hooks` imports the `hooks.server-...` which is as follows:

```javascript
import { r as redirect, a as error } from './handler-c4b55a71.js'; // ❗ <-- as you can see it imports from the handler
import { e as env } from './env-82bfc5bc.js';

const handle = async ({ event, resolve }) => {
  // ... your server.hooks handler
};

export { handle };
```

However, those exports (the redirect and error function) are exported only at the very last line of the handler chunk file:
```javascript
export { /** omitted */ , error as a, /** omitted */  redirect as r, /** omitted */ };

But the `server.init` was awaited a few thousand lines above this, meaning those functions weren't exported yet. I assume that's what's causing the problem. Really annoying there are no logs whatsoever though, although that's probably a problem with Node.

**Comment by revers3ntropy** [comment] 2023-07-02 16:38
Just want to add that I've had this problem too (https://stackoverflow.com/questions/76599252), and found the same thing, with `await server.init` and the circular dependency...

**Comment by spy16** [comment] 2023-07-02 18:54
I am facing this issue too. I pinned the node adaptor to 1.2.4 for now and is working. (I have no other info to offer. there is no error, nothing shown. it just exits with 13 exit coe)

**Comment by yadoga** [comment] 2023-07-02 19:10
Same here. Just chiming in. Checked all logs available, no error codes to be had. Narrowed it down to adapter-node 1.3.0 in the end. Using 1.2.4 for now…

**Comment by ctiospl** [comment] 2023-07-03 11:43
Same here. In my case imports from external libs or any files with reference to them causes node to exit. Pinned the node adaptor to 1.2.4 for now...

**Comment by asmajlovicmars** [comment] 2023-07-03 14:42
Didn't work for me, even if I left only a default hook, but when I completely commented it out with 1.3.0, node started as expected:

Didn't work: 

app/src/lib/hooks/handleDefault.js
`
export async function handleDefault({ event, resolve }) {
	return resolve(event);
}
`

app/src/hooks.server.js
`
import { sequence } from '@sveltejs/kit/hooks';
import { handleDefault } from '$src/lib/hooks/handleDefault';
export const handle = sequence(handleDefault);
`

Worked:
app/src/hooks.server.js
`
//import { sequence } from '@sveltejs/kit/hooks';
//import { handleDefault } from '$src/lib/hooks/handleDefault';
//export const handle = sequence(handleDefault);
`

**Comment by Cluster2a** [comment] 2023-07-03 21:39
Same problem here - running an app within a docker container. I downgraded to 1.2.4 - now it's working again.

**Comment by CaptainCodeman** [comment] 2023-07-03 21:45
I am seeing the same thing. Start with a working app. Upgrade only the node adaptor v1.3.0 and the app no longer runs, giving "Command failed with exit code 13"

This isn't using Express, it's using the node "http" package to host the handler. But trying to launch the app using `node build` just exits back to the terminal with no message at all.

**Comment by kevpye-fabdata** [comment] 2023-07-05 09:43
I can also say 1.3.0 is broken to me too - not even using express.
I have a minimal repo here: https://github.com/kevpye-fabdata/svelte-adapternode130-error. The repo package versions are all at their latest versions as of yesterday.

Clone the repo and run the following checks: 
- npm install. 
- npm run dev works no problem, 
- npm run build builds without error (some warnings but nothing major). Note (just FYI) in the repo there is a post build script which just copies package and package lock to the build folder + installs dependancies.
- npm run preview works fine. 
- node build does nothing just exists. 

The issue is coming from hooks.server.ts in the src folder. The file is just there to demo the problem, the handle function does nothing except call return resolve(event). The offending line is actually the import from sveltekit:
```
import { redirect } from '@sveltejs/kit';
```
This import is not being used but just including it breaks the build, comment out this line and re-run npm build. node build will work.

**Comment by ollema** [comment] 2023-07-05 09:46
the issue is known - we have countless reports and reproductions in this thread. maybe we can use reactions instead of posting the same type of messages over and over again? I have notifications turned on so I get notified when there is a fix out - it’s slightly annoying to get notified for every message reporting the same issue.

thanks in advance

**Comment by dummdidumm** [comment] 2023-07-05 10:19
We reverted the change that caused this, 1.3.1 should not observe this issue. We'll try to land the change again in a way that does not break, if possible. The underlying problem is a Rollup bug.

**Comment by kevpye-fabdata** [comment] 2023-07-05 10:40
Many thanks @dummdidumm for the swift resolution. 
I have tested 1.3.1 on 2 separate repos including the one I shared above and 1.3.1 does not have the issue and the build runs as expected.
Many thanks again

**Comment by eltigerchino** [comment] 2024-03-06 16:45
closed by https://github.com/sveltejs/kit/pull/10314

**Closed by eltigerchino** 2024-03-06 16:45 UTC
Labels: bug, pkg:adapter-node
