### ISSUE TITLE
{@html string} loses content during client site hydration 

### ISSUE THREAD

**Issue by nisarhassan12** [sveltejs/kit#9774] opened 2023-04-26 18:15 UTC
### Describe the bug

In my svelte-kit project, the pages are generated via markdown files. 

The frontmatter sometimes includes fields that contain markdown like the text field [here](https://github.com/nisarhassan12/stackbit-sveltekit/blob/ad4051fa98f6b09ac795ce6fcd0231813873067f/src/content/pages/index.md?plain=1#L13) which is converted into an HTML string in `+page.server.ts` and then sent to `+page.svelte` and rendered inside the components via using `{@html text}` as done [here](https://github.com/nisarhassan12/stackbit-sveltekit/blob/ad4051fa98f6b09ac795ce6fcd0231813873067f/src/lib/components/hero-section.svelte#L29)

When I visit the page it first renders all the contents of the HTML string then later on when it hydrates some of the contents get hidden as shown in the video here: 

https://user-images.githubusercontent.com/46004116/234664846-95e3d58e-27ca-45bc-8ecc-3d6f5cbfd318.mov 

### Reproduction

~~Repo link: https://github.com/nisarhassan12/stackbit-sveltekit~~

Visit https://stackblitz.com/github/nisarhassan12/stackbit-sveltekit/tree/rendering-error-minimal-repro and the try reloading a several times and you'll see the issue/ 

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 316.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0.1
    Safari: 16.4
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment] 2023-04-26 18:56
Please provide a minimal reproduction, as requested in the issue template, and not a link to your whole project.

**Comment by nisarhassan12** [comment] 2023-04-27 20:28
Sorry @Conduitry for not doing that earlier I thought the links to the relevant files would suffice. 

You can view the minimal reproduction here https://stackblitz.com/github/nisarhassan12/stackbit-sveltekit/tree/rendering-error-minimal-repro try reloading the preview a few times and you'll see the issue.

**Comment by gtm-nayan** [comment] 2023-04-28 03:44
You are putting ul's inside of p elements which isn't allowed by the HTML spec https://www.w3.org/TR/html401/struct/text.html#h-9.3.1.

In classic web platform fashion, the behaviour is different depending on how you attach elements:

Using createElement and appendChild calls, firefox at least is perfectly happy to render it. Using innerHTML implicitly moves the ul as a sibling of the paragraph. I guess the html doesn't match Svelte's expectation because of that and it gets nuked.

**Comment by dummdidumm** [comment] 2023-04-28 07:30
Closing as duplicate of #8345 because the underlying reason is the same.

**Closed by dummdidumm** 2023-04-28 07:30 UTC
Labels: p3-edge-case
