### ISSUE TITLE
Pipedrive webform not working

### ISSUE THREAD

**Issue by tant2012** [sveltejs/kit#5585] opened 2022-07-18 05:53 UTC
### Describe the bug

Hey guys I've got a prob here.
So I'm going to include a Pipedrive web form on my landing page. This is the code snippet given by Pipedrive.

However, it's not rendering most of the time and it shows "canceled" in the console. So I tried to use iframe instead of div, and it renders properly every time. But one prob now is I wanna redirect to another page after the user submits the form. If I use an iframe to render out the webform, it only redirects to a new page in the iframe but not the whole page. I wonder if there's any way to solve this?

*The code works properly in svelte repl tho. I assume this is a sveltekit issue
![image](https://user-images.githubusercontent.com/63858197/179450474-044832f2-3a9b-4045-b9a9-23383c333dad.png)

### Reproduction

Code snippet given by pipedrive(not rendering)

``<div class="pipedriveWebForms" data-pd-webforms="https://webforms.pipedrive.com/f/c54Q8p5Xk9h2TKrTxhDcoEX6zKN0QOHuOAalQUIPiIh1UX31CXcpNgIijy1PAj8gHp"><script src="https://webforms.pipedrive.com/f/loader"></script></div>``

code snippet that's rendering but redirecting only in the iframe
``<iframe class="pipedriveWebForms" data-pd-webforms="https://webforms.pipedrive.com/f/c54Q8p5Xk9h2TKrTxhDcoEX6zKN0QOHuOAalQUIPiIh1UX31CXcpNgIijy1PAj8gHp"/><script src="https://webforms.pipedrive.com/f/loader"></script>``

if I include it in svelte:head it works as well
``````
<svelte:head>
<div class="pipedriveWebForms" data-pd-webforms="https://webforms.pipedrive.com/f/c54Q8p5Xk9h2TKrTxhDcoEX6zKN0QOHuOAalQUIPiIh1UX31CXcpNgIijy1PAj8gHp"><script src="https://webforms.pipedrive.com/f/loader"></script></div></svelte:head>
``````

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 296.08 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.50 
    @sveltejs/kit: next => 1.0.0-next.347 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

**Comment by dominikg** [comment] 2022-07-18 10:02
Please provide a full reproduction as required/asked to by our issue template

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by Rich-Harris** [comment] 2022-07-19 17:53
@kamerat then maybe you can provide a repro, in the absence of one from @tant2012?

**Comment by kamerat** [comment] 2022-07-20 10:05
I tried to create both a REPL and a stackblitz to reproduce the issue but have yet to be able to. It seems to work as expected on those sites. I have however just tried creating a "self-contained" example of the issue. The bug might be somewhere else in the setup. 

I am pretty sure the bug is a race-condition between the html and the Pipedrive loader script. I suspect this because it always seems to work on the next DOM update - _If I replace some text in the code while running "npm run dev", the form is rendered, but never on the first initial load._

I guess it's a shot in the dark for you guys until either me or @tant2012 manages to isolate the bug, but in regards of a race-condition or the info I provided, do you have any ideas to test out to make it load "synchronously"? Ideally, we would want to run the loader once the DOM is finished loading. I thought about using the on:load attribute on the script, but I didn't find a function to call at first glance in the minified loader script, so I think it's a dead end.

**Comment by dominikg** [comment] 2022-07-20 11:52
you could listen for  `sveltekit:start` emitted here https://github.com/sveltejs/kit/blob/d02f1f25ac8acb29e21a06b94418c333928fb9bb/packages/kit/src/runtime/client/start.js#L45

https://kit.svelte.dev/docs/events

that ensures hydration is done at this point but it requires clientside js. 

Alternatively make sure the form (or whatever dom structure is needed by that library) is available completely in the SSR output and append the script tag at the end of body instead of in head (or maybe (script defer)[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer].

**Comment by kamerat** [comment] 2022-07-20 12:42
Thank you for the reply, @dominikg. I don't think I fully understand the top part of your answer and it's use case here. Do you mean to listen for this event in the loader script? - If so, this is out of my hands as it is a third party script provided by Pipedrive. Have I misunderstood your answer?

Regarding the last part, the element is indeed in the output, but only the "anchor", it does not have the children generated by the third-party script.

<hr>

After some further investigation, it seems that the form gets loaded on the first load, but it gets removed so quick that you don't really see it(~.5s). It's possible to se some layout shift. When using the chrome debugger and adding a breakpoint to the third-party loader script -

<details>
<summary>Screenshot of devtools</summary>

![Screenshot 2022-07-20 at 14 17 55](https://user-images.githubusercontent.com/11461961/179979861-c51838de-0fe6-4420-94df-587adc705317.png)
![Screenshot 2022-07-20 at 14 20 38](https://user-images.githubusercontent.com/11461961/179980301-4015e7a0-1720-4e3f-a6d8-0193e18c7e07.png)

</details>

... You can see that the form is indeed loaded. However, the iframe element gets removed from the initial parent after some ms. 

I added a html breakpoint "break on > subtree modifications" to the element in question;
```html
<div class="pipedriveWebForms" data-pd-webforms="https://webforms.pipedrive.com/f/c54Q8p5Xk9h2TKrTxhDcoEX6zKN0QOHuOAalQUIPiIh1UX31CXcpNgIijy1PAj8gHp">
```

It then breaks as expected on the pipedrive loader script appendChild. When resuming script execution, it breaks on node removal here:

<details>
<summary>Screenshot of devtools</summary>

![Screenshot 2022-07-20 at 14 24 12](https://user-images.githubusercontent.com/11461961/179982462-e27909cf-f2a9-4418-b789-c87b9bd903bc.png)

</details>

**Comment by kamerat** [comment] 2022-07-20 13:57
I think I managed to reproduce the bug [here](https://stackblitz.com/edit/svelte-kit-gwp477?file=src%2Froutes%2Findex.svelte,src%2Flib%2FPipedriveFormEmbed.svelte). It seems it happenes when you use something async inside a module. 🤔

**Comment by dominikg** [comment] 2022-07-20 15:08
@kamerat: for some reason the sveltekit version in your stackblitz is really old (next.85).

The problem seems to boil down to the fact that you have to delay loading the loader script until svelte has hydrated the component that contains the dom element the form is attached to.

This can be achieved by using onMount:

```html
<script context="module">
	export const prerender = true;
</script>
<script lang="ts">
  import{onMount} from 'svelte';
  export let url; // "https://webforms.pipedrive.com/f/<your-form-id>"

  onMount(()=>{
   // shortened, you should make sure the script is only injected once and document exists etc.
    const script = document.createElement('script');
    script.setAttribute('src','https://webforms.pipedrive.com/f/loader');
    document.head.appendChild(script);
  })
</script>
<h1>form</h1>
<div class="pipedriveWebForms" data-pd-webforms={url}/>
````

you also have to make sure that the data-pd-webforms attribute is set before loading the loader script.

Note, if you have multiple forms on the same page the above may not work.

I don't think this is a bug in sveltekit or svelte, just some extra setup you have to do to ensure sveltekit and pipedrive don't collide.

**Comment by Rich-Harris** [comment] 2022-07-20 20:09
Yeah, delaying the script loading works. Feels _suuuper_ janky though — massive layout shift because the form isn't server-rendered, and it will only work for the first page load. If you have any say in the matter I would recommend avoiding this method of adding forms to your site.

Though I assume they have an SDK that lets you programmatically add forms to elements that are created after the script has loaded, which should help in the client-side navigation case.

Unclear why it's sensitive to hydration timing, but it feels very much like a Pipedrive issue rather than a SvelteKit issue so I'll close this.

**Closed by Rich-Harris** 2022-07-20 20:09 UTC
Labels: awaiting submitter
