### ISSUE TITLE
URI encoded path param handled differently in SPA and Server

### ISSUE THREAD

**Issue by ispyinternet** [sveltejs/kit#5477] opened 2022-07-12 16:14 UTC
### Describe the bug

If I have a route `/config/[id]` and the value of id is `encodeURIComponent('/test/a/path')` then the value of `$page.params.id` differs depending on if you are accessing it during SPA or from a server reload:

```
console.log($page.params.id)

%2Ftest%2Fa%2Fpath // within SPA
/test/a/path // Page reload from server
```

### Reproduction

Unfortunately my environment is limited to node 14 and I don't seem to be able to `npm create svelte@1.0.0-next.xxx`. If you could advise how to create a sveltekit app at a particular release I will provide a repo.

### System Info

```shell
System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz
    Memory: 1.21 GB / 16.73 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 14.18.3 - /usr/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.13.2 - ~/.npm-global/bin/npm
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment] 2022-07-12 16:20
Sounds like a duplicate of #4629. Going to close this one to keep the discussion in one place.

**Closed by gtm-nayan** 2022-07-12 16:20 UTC
