### ISSUE TITLE
sveltekit endpoint and form actions not work after deploy to vercel, always return 403.

### ISSUE THREAD

**Issue by ubay1** [sveltejs/kit#7239] opened 2022-10-11 22:04 UTC
### Describe the bug

i tried using sveltekit endpoint and form actions to login, when i use it on local everything works, but when i deploy to vercel it doesn't work and always returns error 403.

### Reproduction
- create a project with sveltekit (npm create svelte@latest).
- create a login page in the routes->project->cool folder.
- then I created a file +page.svelte:
- then i test at local it works.
- then I deploy to vercel, and test in production I get error 403.

![image](https://user-images.githubusercontent.com/33889018/195516168-f22d05af-06bb-46db-81f6-07ddb189b93f.png)

### my repo.
https://github.com/ubay1/learn-svelte-sveltekit

### Logs
![image](https://user-images.githubusercontent.com/33889018/195516279-f03ff1e5-dab9-4f5a-8b0d-0cbcdf0d99e0.png)

### System Info

```shell
System:
    OS: macOS Monterey 12.2.1
    CPU: Apple M1
    Memory: 8 GB
    Shell: /bin/zsh
  Binaries:
    Node: 16.17.0
    npm: 8.15.0
  Browsers:
    Brave Browser: 1.44.105
    Chrome: 106.0.5249.103
  npmPackages:
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "svelte": "^3.44.0",
    "vite": "^3.1.0",
```

### Severity

annoyance

**Comment by Conduitry** [comment] 2022-10-11 22:12
Please provide a minimal but complete reproduction as a link to a repo, as requested in the issue template.

**Comment by ubay1** [comment] 2022-10-11 22:35
my repo is private, i can't give it

**Comment by ubay1** [comment] 2022-10-12 14:22
@Conduitry help me.

**Comment by dummdidumm** [comment] 2022-10-12 14:26
you don't need to make your repo public, you need to provide a minimum reproducible. That means, remove everything from the code that is irrelevant for the bug, which means you probably end up with a `route` folder with one or two files in it. Then you upload that reproducible as a Github repo or create a Stackblitz project. The given snippets aren't helping because they are incomplete and don't work if copy-pasted, there's too much stuff going on that is left out and probably irrelevant to this issue.

**Comment by mustofa-id** [comment] 2022-10-13 04:15
The code is trying to make POST request, whereas the screenshot shows a GET request.

btw, in Vercel web UI, there is Realtime logs ...
![image](https://user-images.githubusercontent.com/25121822/195496170-9a0918c7-2418-4b56-bd31-c5689781ced4.png)

... in Function Logs in your project tab,
![image](https://user-images.githubusercontent.com/25121822/195496091-07ad2b26-343b-4217-8ce2-85b1284f934e.png)

it will log all requests in real time, so you may find details about the error there.

**Comment by ubay1** [comment] 2022-10-13 05:43
![image](https://user-images.githubusercontent.com/33889018/195510967-1943ec22-58cb-4aa9-8569-644d8fb5492d.png)
I have installed the log alert, but from the log alert it only returns 403 and no message..

sorry the error is not 500 but 403.

**Comment by ubay1** [comment] 2022-10-13 06:01
oke this my repo.
https://github.com/ubay1/learn-svelte-sveltekit

**Comment by dummdidumm** [comment] 2022-10-13 08:37
One more time: This isn't a minimum reproducible. You made your repo public - which you don't have to - and in that repo there's a ton of unrelated stuff. Create a new repository which _only_ contains what's needed to reproduce it - copy over your code into that repo and throw everything out that's irrelevant.

Furthermore, a 403 in `api/asik/auth` sounds like nothing we can help you with. It sounds like you try to access a url in that `+server.js` which you are not allowed to, some credentials are missing.

**Comment by ubay1** [comment] 2022-10-13 13:55
OK, fine thank you

**Comment by dummdidumm** [comment] 2022-10-19 08:39
Closing as no minimum reproducible was provided, and the 403 error hints at a problem within the app, rather a bug in SvelteKit

**Closed by dummdidumm** 2022-10-19 08:39 UTC
Labels: awaiting submitter
