### ISSUE TITLE
Safari issue when ssr is false

### ISSUE THREAD

**Issue by cge-taal** [sveltejs/kit#12406] opened 2024-06-27 19:13 UTC
### Describe the bug

In a simple SvelteKit skeleton project with a single library added and where SSR is disabled, Safari fails with `Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.`. Other browsers tested had no issues.

### Reproduction

Please refer to https://github.com/cge-taal/sveltekit-safari-ssr-example and run with `npm run dev`.

In `src/routes/+layout.ts`, when `export const ssr = false` is set, Safari fails with `Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.`

### System Info

```Shell
macOS, Safari 16.6
```

### Severity

blocking all usage of SvelteKit

**Comment by cge-taal** [comment] 2024-07-01 07:26
Given

- https://github.com/sveltejs/kit/issues/2889#issuecomment-1112512195
- https://github.com/sveltejs/svelte/issues/5501

It seems to be an old bug in SvelteKit that resurfaced, related to top-level await support on Safari.

This is pretty important for us to have fixed and stable (tested) in a framework we hope to use for our products.

Any idea of a likely fix soon would be much appreciated.

Thanks for all the efforts.

**Comment by MoonlightOffice** [comment] 2024-07-05 08:56
Create a file called `src/hooks.client.ts` and add this line to it:

```typescript
import { encodeBase58Address } from "@bitauth/libauth";
```

The code in `src/hooks.client.ts` is executed before the app starts. I guess the module you're using (@bitauth/libauth) requires some initialization before the node is rendered or mounted when you use safari.

For more information about hooks: https://kit.svelte.dev/docs/hooks

**Comment by cge-taal** [comment] 2024-07-05 09:30
Thanks @MoonlightOffice , to be honest I did not try to find workarounds yet, because I think it should work by default, as it does in non-Safari browsers. Given the issue is related to top-level await, I did consider trying to wrap all interaction with `@bitauth/libauth` inside async methods.

I could try your workaround when there is a moment, but I do believe it would be most useful if a framework like SvelteKit makes workarounds unnecessary for users.

**Comment by cge-taal** [comment] 2024-07-05 12:00
I can provide some extra feedback on your suggestion @MoonlightOffice.

It seems to work fine for the example repository I listed above, which is nice.

However, my real project is a pretty large monorepo (turbo) and I'm accessing `@bitauth/libauth` in a standard library `package` which I'm importing from my main application.

If I add all the same `@bitauth/libauth` imports I use in the package, to a `src/hooks.client.ts` file in my main application and also install `@bitauth/libauth` as a dependency for the main application, this workaround does not function anymore.

**Comment by cge-taal** [comment] 2024-07-05 12:01
Wrapping `@bitauth/libauth` usage inside async functions is infeasible, as I need synchronous behaviour for some use-cases.

**Comment by eltigerchino** [comment] 2024-07-05 16:47
closing as duplicate of https://github.com/sveltejs/kit/issues/8529
It's currently caused by a bug in Safari that prevents the use of top-level awaits client-side. Libraries (and even SvelteKit has before) refactored to avoid the use of top-level awaits in the browser.

**Closed by eltigerchino** 2024-07-05 16:47 UTC
