### ISSUE TITLE
`create-svelte` options duplicating

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#9300] opened 2023-03-03 03:12 UTC
### Describe the bug

https://user-images.githubusercontent.com/47051820/222621648-e2af4e70-01dc-45d1-a00f-0dc0973ac7a0.mov

### Reproduction

1. Open macOS terminal
2. Type `npm create svelte@latest my-app`
3. Press the down key on the first prompt.

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 75.63 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
```

### Severity

annoyance

### Additional Information

- `create-svelte version 3.1.0`
- Occurs on the first prompt only.

**Comment by Conduitry** [comment] 2023-03-03 03:53
Duplicate of #9231.

**Closed by Conduitry** 2023-03-03 03:53 UTC
