### ISSUE TITLE
creating +page.server.js without +page.svelte or +layout.server.js without +layout.svelte will throw error

### ISSUE THREAD

**Issue by mashanz** [sveltejs/kit#7117] opened 2022-10-02 02:47 UTC
### Describe the bug

error `node.component is not a function` on @sveltejs/kit/src/runtime/server/page/render.js:82:64

### Reproduction

create path that only have `+layout.server.js` without `+layout.svelte` or `+page.server.js` without `+page.svelte` it will throw error

### Logs

```shell
node.component is not a function
TypeError: node.component is not a function
    at file:///home/my-app/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:82:64
    at Array.map (<anonymous>)
    at render_response (file:///home/my-app/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:82:41)
    at render_page (file:///home/my-app/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:276:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///home/my-app/node_modules/@sveltejs/kit/src/runtime/server/index.js:232:17)
    at async respond (file:///home/my-app/node_modules/@sveltejs/kit/src/runtime/server/index.js:284:20)
    at async file:///home/my-app/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 AMD Ryzen 5 2400G with Radeon Vega Graphics
    Memory: 14.56 GB / 22.42 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 106.1.44.105
    Chrome: 106.0.5249.91
    Firefox: 105.0.1
```

### Severity

annoyance

### Additional Information

I though its a feature and made documentation PR #7115 but @Rich-Harris said its a bug

**Comment by Rich-Harris** [comment] 2022-10-02 15:26
Duplicate of #5967

**Closed by Rich-Harris** 2022-10-02 15:26 UTC
