### ISSUE TITLE
Endpoint routes missing

### ISSUE THREAD

**Issue by harjis** [sveltejs/kit#2827] opened 2021-11-18 08:32 UTC
### Describe the bug

Hi!

I noticed that the more recent version of kit seems to behave differently from earlier versions. The setup I have is this:

```
src
|-- app.html
|-- global.d.ts
`-- routes
    |-- index.svelte
    |-- redirect.js
    `-- test.svelte
```

```index.svelte
// index.svelte

<h1>Welcome to SvelteKit</h1>

<a href="/redirect">Redirect to Test Page</a>
```
```redirect.js
// redirect.js

export async function get() {
    return {
        status: 302,
        headers: {
            location: '/test'
        }
    };
}
```

```test.svelte
// test.svelte

<div>Test Page</div>
```

My expectation was that when I click the link on `index.svelte` browser would navigate to `/redirect` which would redirect me to `/test`. Instead I get a 404.

Installing a later version from kit (I used  1.0.0-next.151) behaves like expected.

Is it so that the behavior should be like it used to and redirect route should be found or am I missing something here?

### Reproduction

Repo: https://github.com/harjis/svelte-routes-test

`npx degit github:harjis/svelte-routes-test`

### Logs

```shell
404

Not found: /redirect

_get_navigation_result@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:801:11
update@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:619:38
handle_navigation@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:608:14
_navigate@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:285:23
init_listeners/<@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:168:9
EventListener.handleEvent*init_listeners@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:123:19
start@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:1210:10
async*@http://localhost:3000/:15:9
```
```


### System Info

```shell
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 4.00 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.asdf/installs/nodejs/16.3.0/bin/node
    Yarn: 1.22.11 - ~/.asdf/installs/nodejs/16.3.0/.npm/bin/yarn
    npm: 7.15.1 - ~/.asdf/installs/nodejs/16.3.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0.1
    Safari: 15.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196 
    svelte: ^3.42.6 => 3.44.1
```

### Severity

serious, but I can work around it

### Additional Information

I can use one of the earlier versions.

**Comment by ignatiusmb** [comment] 2021-11-18 08:49
Duplicate of #2719. Manually mark the links with [`rel="external"`](https://kit.svelte.dev/docs#anchor-options-rel-external).

**Closed by ignatiusmb** 2021-11-18 08:49 UTC
