### ISSUE TITLE
CSS is stacked instead of updated

### ISSUE THREAD

**Issue by asv7c2** [sveltejs/kit#718] opened 2021-03-27 10:53 UTC
**Describe the bug**
CSS is not updating correctly.

**Logs**

**To Reproduce**
[Repository](https://github.com/asv1/svelte_bug_2).

1. npm run dev
2. counter is hidden.
3. comment display: none in Counter.svelte
4. counter is still hidden.
5. in devtools display: hidden is applied from previous css, looks like they all stacked

**Expected behavior**
Just updating correctly.

**Stacktraces**

**Information about your SvelteKit Installation:**

**Additional context**

**Comment by lukasIO** [comment] 2021-03-27 11:24
Might be a duplicate of https://github.com/sveltejs/kit/issues/572, although I don't know if the CSS handling is a seperate issue.

As you already observed, with SSR enabled (which is the default case for the dev server) you effectively end up with all CSS being duplicated. Once from SSR and once from CSR.

Currently the SSR version of the CSS does not update with HMR (According to the above mentioned issue that could be because of vite caching issues).
Simply commenting out the property thus makes the SSR version apply, because the property is not set explicitly anymore on the client. 

While i know that it's not really a satisfying solution, a workaround for the time being: If you, instead of commenting `display: none` change the display property to something like `display: block` you should see it reflected immediately in the browser.
Alternative workaround is to restart the dev server.

**Comment by benmccann** [comment] 2021-03-29 15:20
Hi, can you please provide the output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers` as requested in the issue template? There are some environment-specific CSS issues and I've no idea whether you might be hitting them or this is a new issue. Thanks!

**Comment by asv1** [comment] 2021-03-29 15:26
@benmccann 
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 13.47 GB / 15.93 GB
  Binaries:
    Node: 14.16.0 - d:\portable\node\node.EXE
    npm: 6.14.11 - d:\portable\node\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.771
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.62
    svelte: ^3.29.0 => 3.35.0
```

**Comment by benmccann** [comment] 2021-03-29 15:57
There are some Windows-only issues, but I just tested your repo and this happens for me on Linux as well

**Comment by samccone** [comment] 2021-03-29 22:39
Confirmed I have also been observing this randomly where the CSS looks to be stacking instead of being replaced.

**Comment by asv1** [comment] 2021-03-30 06:42
I even tried disable ssr with latest svelte kit version. Not helped. Strange.

**Comment by Upsetmania** [comment] 2021-03-30 16:11
hello, for the moment I think we must use the css in a file works wonderfully

**Comment by Upsetmania** [comment] 2021-03-30 22:28
@asv1 

yes css external

**Comment by benaltair** [comment] 2021-03-31 21:07
I noticed this too. Seemed that Vite was just adding the updated rules lower in the styles so they override the previous settings. This works when _adding_ or _updating_ rules, but fails when _removing_ rules, since the previous rule is still present in the client's stylesheet. Refreshing does not help. Shutting down the dev server and running `npm run dev` once more fixes it immediately, since the history is not longer there.

Here's my setup in case it's helpful:
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 15.56 GB / 31.92 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.59 
    svelte: ^3.29.0 => 3.35.0 
```

## Example to reproduce
1. Execute `npm run dev` and open the preview
2. Edit a style in a component (it should update on save)
3. Delete that rule, or simply comment it out
Now the styling will revert back to the first value. You can see in devtools something similar to this:
![image](https://user-images.githubusercontent.com/17771229/113211403-480c9d00-922a-11eb-9709-da97b8c75fd4.png)
Notice that the first `h1` rule I have removed `margin` so it just reverts back to the previous phantom edit which is still there.

**Comment by simmo** [comment] 2021-04-07 18:02
Also seeing this.
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 227.90 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 89.0.4389.82
    Chrome Canary: 91.0.4443.0
    Edge: 89.0.774.68
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.71 => 1.0.0-next.71 
    svelte: ^3.29.0 => 3.37.0 
```

**Comment by ignatiusmb** [comment] 2021-08-21 12:15
I can't reproduce this in the latest version, commenting the `display: none` immediately shows the counter.

**Closed by ignatiusmb** 2021-08-21 12:15 UTC
