### ISSUE TITLE
docs: broken copied content on code block

### ISSUE THREAD

**Issue by codenoid** [sveltejs/kit#11948] opened 2024-03-07 17:05 UTC
### Describe the problem

![image](https://github.com/sveltejs/kit/assets/14269809/0c829372-a16d-4e4e-80da-c9697f371060)

paste output:
![image](https://github.com/sveltejs/kit/assets/14269809/856ccf69-2759-402e-92da-2f219ff681ee)

### Describe the proposed solution

formatted content

### Importance

would make my life easier

**Comment by Conduitry** [comment] 2024-03-07 17:07
Duplicate of https://github.com/sveltejs/site-kit/issues/254

**Closed by Conduitry** 2024-03-07 17:07 UTC
