### ISSUE TITLE
beforeNavigate does not fire after clicking link with `download` attribute

### ISSUE THREAD

**Issue by lukearray** [sveltejs/kit#9611] opened 2023-04-06 20:54 UTC
### Describe the bug

This application has two pages - a home page at `/` and an about page at `/about`.
You can click between the two pages using the links in the header, or the links that appear on each page. 
Each time you click, `BEFORE NAVIGATE IS RUNNING` logs to the console.
If you click the `PDF Url` link at the bottom, beforeNavigate runs as normal, logging `BEFORE NAVIGATE IS RUNNING` to the console.
The next link you click, `beforeNavigate` does not run.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-mgk5se?file=src/routes/+page.svelte

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.15.1 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.2.0 => 4.2.1
```

### Severity

serious, but I can work around it

**Comment by lukearray** [comment] 2023-04-06 22:00
@s3812497 This was the issue I was referring to here: https://github.com/sveltejs/kit/issues/9170#issuecomment-1446761061 that I wasn't able to reproduce at the time. We have a working reproduction for it now, forked with the latest SvelteKit.

**Comment by s3812497** [comment] 2023-04-08 08:37
Sorry for the late response! I have started looking into a fix for this last night. Thank you for reporting it again.

The issue is caused by what I explained previously https://github.com/sveltejs/kit/issues/9170#issuecomment-1446725050 so I just need to try out a fix and test it :)

**Closed** 2023-04-17 15:53 UTC
Labels: bug
