### ISSUE TITLE
static site generation of dynamic routes not working

### ISSUE THREAD

**Issue by iham** [sveltejs/kit#3665] opened 2022-02-01 19:27 UTC
### Describe the bug

According to the docs SSG is a thing in SvelteKit, but i can't get it working to also generate static html pages from dynamic routes.

a listing page using an api route (a faker list of users) linking to separate detail page.
for single users there is another api route (again faker, but on the params) used by the [user].svelte dynamic route.

both apis use fetch
both pages use the module load method
both work on npm run dev and on npm run preview

sadly the detail user pages are not generated as html pages and i can't find a solution how to make that work

### Reproduction

the easiest way would be to look at that repo: https://github.com/iham/sveltekit-ssg-dynroutes

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 95.57 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Firefox Developer Edition: 97.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26 
    @sveltejs/kit: next => 1.0.0-next.252 
    svelte: ^3.44.0 => 3.46.3
```

### Severity

annoyance

**Comment by geoffrich** [comment] 2022-02-01 19:48
Are the pages generated if you remove `sveltekit:prefetch` [from the links](https://github.com/iham/sveltekit-ssg-dynroutes/blob/b5833c4135dff6e4dde3cbc6069d943169fddba0/src/routes/index.svelte#L20)? If so, I think this is a duplicate of #3660.

**Comment by iham** [comment] 2022-02-01 19:51
i don’t get dynamic routs statically generated at all

not duplicate; i guess it is a problem in the same field of problems ;)

**Comment by Conduitry** [comment] 2022-02-01 20:41
There appear to be two things going on here. One is #3660.

The other is related to `/api` and `/api/SomeName` both being endpoints, which doesn't have a good way of being handled with SSG. If I remove the `sveltekit:prefetch` from the URLs, I see errors about being unable to create `build/api/SomeName`, which is happening because `build/api` is already a file. SvelteKit could perhaps give a more helpful error here.

**Comment by Conduitry** [comment] 2022-02-02 04:07
Closing as a duplicate of #3660.

When I upgrade to `1.0.0-next@256`, I no longer see what's described in the issue. I do, however, get an error which is the result of trying to have something that's both a file and a directory, which is expected. In order for this app to work as a statically generated site, you will need to rename the `/api` endpoint to something else.

**Closed by Conduitry** 2022-02-02 04:07 UTC
