### ISSUE TITLE
TypeORM - Circular dependency and one minor bug

### ISSUE THREAD

**Issue by gamelaster** [sveltejs/kit#1327] opened 2021-05-04 11:17 UTC
**Describe the bug**
Minor bug: After building a project, there is `require is not defined` error in compiled server `app.js`, for some reason, browser template gets compiled into the final app.js (This is not happening in Sapper). It should be just removed, it shouldn't affect functionality.

![image](https://user-images.githubusercontent.com/1665373/116995183-07e18400-acda-11eb-8bb8-cfbe48a50854.png)

After removing this, the primary problem occurs. 
```
ColumnTypeUndefinedError2: Column type for ProductImage#url is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
```
Well firstly, it looks like reflect-metadata doesn't work much good. Also I encountered various circular dependencies issues (Product.ts is referencing ProductImage.ts and vice-versa) (mainly in Sapper).

**To Reproduce**
[Reproduction repository](https://github.com/gamelaster/sveltekit-typeorm)
```
pnpm install
pnpm run build
```

**Expected behavior**
TypeORM should work just fine.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 15.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.7.6 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.96
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5
</details>

**Severity**
Because of this problem, I can't use TypeORM, and since it's not working also in Sapper, I can't use it at all with combination of Svelte SSR. 

Thanks.

**Comment by dummdidumm** [comment] 2021-05-04 12:25
I guess that the underlying problem is that you use Vite there, which uses ESBuild, which does not support the `emitDecoratorMetadata` setting. You need to find a Vite plugin that transpiles TS/JS files with the tsc compiler.

**Comment by benmccann** [comment] 2021-05-04 19:13
Please don't report two problems in a single ticket. It makes it very hard to manage

Since this ticket seems to be primarily about TypeORM, I'm closing as a duplicate of https://github.com/sveltejs/kit/issues/798

**Closed by benmccann** 2021-05-04 19:13 UTC
