### ISSUE TITLE
Regression in v2: parent() returns old data even after the parent was invalidated using invalidate()

### ISSUE THREAD

**Issue by kyngs** [sveltejs/kit#11696] opened 2024-01-20 21:29 UTC
### Describe the bug

This is hard to explain, but I'll do my best.
Imagine the following route structure:
```
routes/
├─ +page.svelte
├─ +layout.ts
├─ [id]/
│  ├─ +page.svelte
│  ├─ +page.ts
├─ add/
│  ├─ +page.svelte
```

The root page shows a basket of fruits, which is loaded from an API in the root +layout.ts. It also includes a button that links to the add page.
The add page includes a button that adds fruit to the basket by posting to the API. After doing so, it invalidates the root +layout.ts load function and then navigates to the root page. 
The [id] page only verifies whether a fruit with such an ID exists in the basket. It does that using the +page.ts load function, which fetches the parent using `await parent()` and then observes, whether a fruit with such an ID is in the parent data.

Now, let's imagine I do this:
- I navigate to the add page
- I press the button to add a fruit
- I get redirected to the root page, where the fruit is now listed.
- I click the fruit, which redirects me to /[id] with the fruit id.
- However, the page tells me that no such fruit exists.
- I click back and navigate to the root page, which now does not list the fruit at all.
- I refreshed the page, and now everything works.

Here's a video where I do that:

https://github.com/sveltejs/kit/assets/38181667/94c16d80-e20f-4be7-93ff-4b021ce0a507

However, when I downgrade to sveltekit v1, or use `invalidateAll()` instead of `invalidate()`, everything works correctly, and the `parent()` function returns correct data. 

### Reproduction

SvelteKit v2: https://stackblitz.com/edit/stackblitz-starters-dp4avt?file=src%2Froutes%2F%5Bid%5D%2F%2Bpage.ts
The issue here is easily reproducible as shown in the video

SvelteKit v1: https://stackblitz.com/edit/stackblitz-starters-et87cn?file=src%2Froutes%2F%5Bid%5D%2F%2Bpage.ts
The issue is not reproducible, everything works as expected. See the video:

https://github.com/sveltejs/kit/assets/38181667/40e82b40-cf75-469c-8987-c445eb25de53

And as a bonus, SvelteKit v2 using `invalidateAll()`:  https://stackblitz.com/edit/stackblitz-starters-4rh3gc?file=src%2Froutes%2Fadd%2F%2Bpage.svelte
The issue is also not reproducible, everything works as expected.

### Logs

```Shell
Not applicable
```

### System Info

```Shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 35.83 GB / 62.70 GB
    Container: Yes
    Shell: 3.7.0 - /usr/bin/fish
  Binaries:
    Node: 18.18.2 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.2.5 - /usr/bin/npm
    pnpm: 8.14.0 - /usr/bin/pnpm
    bun: 1.0.18 - /usr/bin/bun
  Browsers:
    Chromium: 120.0.6099.199
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1 
    @sveltejs/kit: ^2.0.0 => 2.4.1 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.9 
    vite: ^5.0.3 => 5.0.12
```

### Severity

blocking an upgrade

### Additional Information

PS: Even though using `invalidateAll` is a workaround, I've decided to use the "blocking an upgrade" severity as rerunning all the load functions is not acceptable.
**I hope I explained the issue well, if you have any questions, ask me.**

**Comment by gterras** [comment] 2024-01-22 10:33
This bug is very real but hasn't been acknowledged by the team yet, see https://github.com/sveltejs/kit/pull/11268#issuecomment-1894232508. 

And also : 

https://github.com/sveltejs/kit/issues/11663
https://github.com/sveltejs/kit/issues/11446
https://github.com/sveltejs/kit/issues/10209
https://github.com/sveltejs/kit/issues/10123
https://github.com/sveltejs/kit/issues/10457
https://github.com/sveltejs/kit/issues/10359

**Comment by kyngs** [comment] 2024-01-22 10:35
> This bug is very real but hasn't been acknowledged by the team yet, see [#11268 (comment)](https://github.com/sveltejs/kit/pull/11268#issuecomment-1894232508).
> 
> And also :
> 
> #11663 #11446 #10209 #10123 #10457 #10359

Thanks for the information! I hope they tackle this soon as this is a very severe issue for me.

**Comment by kyngs** [comment] 2024-01-22 10:37
I'm kinda spooked this is a half year old issue tho

**Comment by gterras** [comment] 2024-01-22 10:47
> I'm kinda spooked this is a half year old issue tho

Partial invalidation has never been fully functional in SvelteKit, even pre 1.0. I suspect none of the maintainers know how to fix it.

**Comment by kyngs** [comment] 2024-01-22 10:48
> > I'm kinda spooked this is a half year old issue tho
> 
> Partial invalidation has never been fully functional in SvelteKit, even pre 1.0. I suspect none of the maintainers know how to fix it.

Hasn't it? Tbh I've never had any issues with it in v1

**Comment by kyngs** [comment] 2024-01-22 11:17
> This bug is very real but hasn't been acknowledged by the team yet, see [#11268 (comment)](https://github.com/sveltejs/kit/pull/11268#issuecomment-1894232508).
> 
> And also :
> 
> #11663 #11446 #10209 #10123 #10457 #10359

@Rich-Harris I'm sorry for mentioning you, as I'm sure you have a lot of work. But you're the author of the original PR  which @gterras suspects to be the culprit. Unfortunately, the issues with invalidating have been here for almost half a year, and they seem to progressively get worse. Could you please take a look into this?

**Comment by kyngs** [comment] 2024-01-23 19:55
> This bug is very real but hasn't been acknowledged by the team yet, see [#11268 (comment)](https://github.com/sveltejs/kit/pull/11268#issuecomment-1894232508).
> 
> And also :
> 
> #11663 #11446 #10209 #10123 #10457 #10359

I can confirm that the PR is causing the issue, removing the `invalidated.length = 0;` does fix my issue, but it might cause a new one.

**Comment by kyngs** [comment] 2024-01-23 20:20
@stalkerg hey! Seeing that you liked the issue, do you have the same problem?

**Comment by stalkerg** [comment] 2024-01-24 04:19
@kyngs  not yet; I did it to improve visibility. Unfortently I have no time now to go deeper and fix it. If nobody fixes it next week, I will try to help.

**Comment by hmnd** [comment] 2024-02-07 04:31
I'm experiencing the same issue. In my case, I have a page that calls `parent()` and an invalidate call in the layout that redirects to `/login` when an auth check fails. Previously that worked just fine, but now it gets stuck showing the same page, but loaded with `/login`'s page data.

**Comment by denjpeters** [comment] 2024-02-08 15:45
Is there any movement on this?  This is a fairly serious regression, and is preventing us from moving to SK v2.  

I did create a simple GitHub project that demonstrates the problem, if that helps... https://github.com/denjpeters/SK2Test

**Comment by kyngs** [comment] 2024-02-08 16:38
> Is there any movement on this? This is a fairly serious regression, and is preventing us from moving to SK v2.
> 
> I did create a simple GitHub project that demonstrates the problem, if that helps... https://github.com/denjpeters/SK2Test

Unfortunately, there is no movement on this.

**Comment by gterras** [comment] 2024-02-09 15:54
Tried to start something here https://github.com/sveltejs/kit/pull/11819

**Comment by dummdidumm** [comment] 2024-02-19 10:37
Closing as duplicate of #11446

**Closed by dummdidumm** 2024-02-19 10:37 UTC
Labels: bug, p1-important
