### ISSUE TITLE
500: Module "stream" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by BigBoulard** [sveltejs/kit#2411] opened 2021-09-12 14:54 UTC
### Describe the bug

I'm trying to setup a authenticated connection to Firebase using WebKit.

The below code "works" in a sense that I receive the data from Firebase Realtime Database as expected.

### Reproduction

Here's a sample code in which you need to provide your Google credentials

[](https://gist.github.com/BigBoulard/b851aa20c110b1b8c57d0fa4460cdbbd)

### Logs

```shell
500: Module "stream" has been externalized for browser compatibility
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 965.53 MB / 16.00 GB
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 16.4.2 - ~/.nvm/versions/node/v16.4.2/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.4.2/bin/npm
  Browsers:
    Brave Browser: 91.1.25.70
    Chrome: 93.0.4577.63
    Firefox: 89.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.165 
    svelte: ^3.34.0 => 3.42.5
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I can't continue to develop my project.

**Comment by BigBoulard** [comment] 2021-09-13 16:10
Important remark, I've created this simple SSR project with sveltekit but maybe this bug is tied to Vite. Maybe there's a misconfiguration in sveltekit / vite for ssr so that I would need to recreate my project using one of the 2 repos quoted in the sveltekit readme (svelte-ssr-d3 and svelte-ssr) under the section bug report... I'm gonna try soon

**Comment by benmccann** [comment] 2021-09-14 04:56
closing as duplicate of https://github.com/sveltejs/kit/issues/2412

**Closed by benmccann** 2021-09-14 04:56 UTC

**Comment by benmccann** [comment] 2021-09-14 14:15
Do you have `node-fetch` 3.0 final in your project somehow? Did you include it directly or did it get pulled in via another library? If via another library, which library?

**Comment by BigBoulard** [comment] 2021-09-14 14:53
Hi Ben!

I don't see any _**node-fetch**_ package in my **_node_modules_** folder and nothing by running `npm list`

**Comment by benmccann** [comment] 2021-09-14 18:28
Hmm. I wonder whether this is the same as the other issue then. Can you share a repository to reproduce this?

**Comment by BigBoulard** [comment] 2021-09-14 20:29
Here's the gist, sorry https://gist.github.com/BigBoulard/b851aa20c110b1b8c57d0fa4460cdbbd but I can build a repo too

**Comment by BigBoulard** [comment] 2021-09-14 20:34
Sorry, I just realized I have a node-fetch package in my node_modules folder. It's node-fetch 2.6.1 actually. (Sorry I got mixed-up with another project )

**Comment by BigBoulard** [comment] 2021-09-14 20:51
Here's a public repo but you'll still need a firebase project and an API key to test it :/

[SvelteFirebaseFetchError](https://github.com/BigBoulard/SvelteFirebaseFetchError)
