### ISSUE TITLE
Allow per page `trailingSlash` configuration

### ISSUE THREAD

**Issue by kdheepak** [sveltejs/kit#4053] opened 2022-02-22 15:52 UTC
### Describe the problem

Currently, the `trailingSlash` configuration allows for `always`, `never` or `ignore`. 

In my opinion, users would almost always want to use either `always` or `never`, but may want to special case just a few pages. Dropping to using `ignore` seems like a hassle just to change one page's configuration.

For example, a blog have a `blogpost.svelte` that resolves at `/blogpost` to link to `/blogpost.html` when using `trailingSlash: 'never'` for all the blog posts, but may want to use `categories.svelte` or `tags.svelte` to resolve at `/categories/` or `/tags/`, i.e. link to `/categories/index.html` or `/tags/index.html`. Here, a user may want to use a trailing slash to resolve `/tags/` because they may also want the page resolved by `/tags/svelte` to be based on a dynamic page e.g. `/tags/[tag].svelte` that links to `/tags/svelte.html`.

Currently,  if a user uses `trailingSlash: 'never'`, then `/tags/` resolves to an error, and someone would need to type `/tags` instead, even though `/tags/svelte` may exist. 

This is not intuitive in my opinion.

See examples in my personal blog here:

- <https://blog.kdheepak.com/tags/> 
    - I have code in a script tag to do a client side `goto` when there's a trailing slash to remove the trailing slash: https://github.com/kdheepak/blog/blob/d941cae788acde0aaeaf25934e8b10a50d8205f7/src/routes/404.svelte#L5-L13 
- <https://blog.kdheepak.com/tags>
- <https://blog.kdheepak.com/tags/svelte>

I can imagine similar issues when a user wants to use `trailingSlash: 'always'` but wants an endpoint such as `/downloads/filename`. With `trailingSlash: 'always'`, this endpoint becomes `/downloads/filename/`.

### Describe the proposed solution

I would like to see `export trailingSlash = true` or `return { props: { trailingSlash: true } }` for pages and endpoints respectively for allowing a per page configuration.

If per page `trailingSlash` configuration is provided, perhaps `trailingSlash: 'ignore'` can be removed.

### Alternatives considered

Implement 302 redirects for `/tags/` to `/tags` when `trailingSlash: 'never'`. This is all particularly relevant for `adapter-static`.

### Importance

nice to have

**Comment by Rich-Harris** [comment] 2022-04-23 19:58
Closing this as a duplicate of #1405. Note that #4699 proposes changing the behaviour such that `/downloads/filename` would _never_ have a trailing slash if it's an endpoint

**Closed by Rich-Harris** 2022-04-23 19:58 UTC
