### ISSUE TITLE
[BUG] yarn test file extension error on fresh install

### ISSUE THREAD

**Issue by willuhmjs** [sveltejs/kit#9531] opened 2023-03-27 15:16 UTC
### Describe the bug

The test command fails on a fresh install with Playwright installed.

### Reproduction

```
yarn create svelte
yarn
yarn test
````

### Logs

```Shell
TypeError: Unknown file extension ".ts" for /workspaces/printstimate/playwright.config.ts
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:74:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:114:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:597:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:449:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:472:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:426:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
    Memory: 2.27 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 19.7.0 - ~/nvm/current/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - ~/nvm/current/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.14.0 
    svelte: ^3.54.0 => 3.57.0 
    vite: ^4.2.0 => 4.2.1
```

### Severity

annoyance

### Additional Information

This problem can be fixed by adding `NODE_OPTIONS=--loader=esm-loader-typescript` to the test script.

```json
"test": "NODE_OPTIONS=--loader=esm-loader-typescript playwright test"
```

**Comment by LeoDog896** [comment] 2023-03-27 15:39
Optionally, this can also use some implicit typescript config system, similar to the likes of `vite.config.ts`.

**Comment by LeoDog896** [comment] 2023-03-30 11:27
Interesting. I have some interest in the feature, so I'll see if I can backtrace this to some `yarn` feature request.

**Comment by willuhmjs** [comment] 2023-03-31 15:33
> This sounds like a `yarn` problem which is not under our control. It works just fine using `npm` or `pnpm`

That is strange because `npm run test` results in the same error for me.

**Comment by madeleineostoja** [comment] 2023-04-07 06:53
FWIW I also just saw this error in a monorepo using pnpm after upgrading all my deps, haven't finished debugging it my end yet but there does seem to be something fragile somewhere

**Comment by madeleineostoja** [comment] 2023-04-07 13:08
Okay my debugging hasn't gotten very far, the only additional context I can offer atm:

- Only effects stuff like vite dev server and local tests, I don't see any issues in build or CI
- Happens for me during SSR of routes that import a local `ts` file
- Thrown by Vite when it's resolving an `@fs/....` path
- Stacktrace comes from Node ESM loader:
``` at new NodeError (node:internal/errors:377:5)
      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
      at defaultGetFormat (node:internal/modules/esm/get_format:122:38)
      at defaultLoad (node:internal/modules/esm/load:21:20)
      at ESMLoader.load (node:internal/modules/esm/loader:431:26)
      at ESMLoader.moduleProvider (node:internal/modules/esm/loader:350:22)
      at new ModuleJob (node:internal/modules/esm/module_job:66:26)
      at #createModuleJob (node:internal/modules/esm/loader:369:17)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:328:34)
      at async Promise.all (index 0)
```

**Comment by madeleineostoja** [comment] 2023-04-20 10:28
Any thoughts on what could be behind this? I'm still seeing it for vite's dev server in my sveltekit pnpm monorepo after updating vite + sveltekit to their latest versions, without any other changes

**Comment by isaacfink** [comment] 2023-05-15 16:32
@madeleineostoja have you ever figured it out? I am running into the same exact issue now, and it's only happening on server side navigation, when going to the page through a link it works fine

**Comment by madeleineostoja** [comment] 2023-05-16 01:32
@isaacfink nope and it’s incredibly annoying. It only effects dev server for me so it’s manageable but painful

**Comment by isaacfink** [comment] 2023-05-16 01:48
@madeleineostoja did you manage to narrow it down to which tool is responsible? I will try to fix it if I can

**Comment by madeleineostoja** [comment] 2023-06-22 01:13
@isaacfink sorry for the radio silence, changed job and haven't been working on my side hustle (which is affected by this) — I haven't narrowed it down further since then, only that it seems to be coming from vite's dev server and/or esbuild, and feels like something to do with resolving symlinks since it only happens on imports of other packages in my monorepo. Building the app and running preview doesn't trigger the error.

It's an incredibly frustrating error, since it means I can't run a dev server and have to keep rebuilding the app to see anything in dev. 

Did you make any progress?

**Comment by eltigerchino** [comment] 2024-11-21 08:31
Closing this as I can't reproduce this on Yarn 1.22.22 and a new SvelteKit project created with `npx sv create` but installed with yarn and tested with `yarn test`.

**Closed by eltigerchino** 2024-11-21 08:31 UTC
