### ISSUE TITLE
Error: Request body must be a string or TypedArray when using fetch in page.server.js action

### ISSUE THREAD

**Issue by smart** [sveltejs/kit#9420] opened 2023-03-13 20:46 UTC
### Describe the bug

I have a situation where I am posting form data to an external API in a server side route. I may refactor this to not go to the server and use the client directly but I stumbled upon this issue. I passed in the fetch object to my action so I could forward along my auth headers, it results in this error being thrown. If I do not pass it it and use standard fetch things work fine (but I have to manually set the auth header). After looking at the code it seems like there is a todo related to this.  My usecase isn't super traditional (posting form data to serverside action, then forwarding that to external api) and I can work around it, but wanted to raise it with the team.

### Error
```
Error: Request body must be a string or TypedArray
    at fetch (/@fs/Users/smartocci/Projects/SuppleCo/web/node_modules/@sveltejs/kit/src/runtime/server/fetch.js:120:12)
```

### Source in sveltekit 
https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/fetch.js
```js
				if (request_body && typeof request_body !== 'string' && !ArrayBuffer.isView(request_body)) {
					// TODO is this still necessary? we just bail out below
					// per https://developer.mozilla.org/en-US/docs/Web/API/Request/Request, this can be a
					// Blob, BufferSource, FormData, URLSearchParams, USVString, or ReadableStream object.
					// non-string bodies are irksome to deal with, but luckily aren't particularly useful
					// in this context anyway, so we take the easy route and ban them
					throw new Error('Request body must be a string or TypedArray');
				}
```
### Reproduction

I do not have a repo but this snippet from a page.server.js and easy to reproduce
```js
export const actions = {
	create: async ({event, request, locals, fetch}) => {
 
        const formData = await request.formData();

        const response = await fetch(`${PUBLIC_API_URL}/intake_logs`, {
            method: 'POST',
            body: formData,
            headers: {
                'Authorization': `Bearer ${locals.userToken}`,
            }
        });
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.06 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.2
```

### Severity

annoyance

**Comment by dummdidumm** [comment] 2023-03-15 08:21
Is the public URL on the same origin? Else that method should've returned earlier already.
(A minimum reproducible is really helpful because of clarification questions like this, would be great if you could add one)

**Comment by smart** [comment] 2023-03-19 00:03
Here's a repro repo. Yes it is coming from the same origin, in my development environment I am proxying /local-api to the backend to avoid cors issues. So while the domains are the same the request ends up going to my backend. In this example I don't have the proxy setup but you can see it happens when using the same domain:port.

https://github.com/smart/sveltekit-repro

**Comment by schibrikov** [comment] 2023-03-25 14:18
I'm trying to do somewhat the same, as I need to upload files to external API and I don't quite understand why the comment says `non-string bodies ... aren't particularly useful in this context`.
What's the actual reasoning behind this restriction?

**Comment by pankaspe** [comment] 2023-04-02 19:49
same issue for me, just put backend behind proxy on remote server, from local machine works great but for the same origin not work, and i have no idea, i just replace the adapter with @sveltejs/adapter-node to work with deta space, but nothing

**Comment by PeytonHanel** [comment] 2023-04-28 16:20
I'm having the same problem, you can see it in the duplicate issue I created mentioned above. Can we get insight on this from anybody familiar with the code base? This seems like a really easy fix if we just delete the two lines of code.

Accordingly, the special fetch should actually act the same as the native fetch as described in the documentation.

**Comment by PeytonHanel** [comment] 2023-05-05 00:04
this should be closed because the aformentioned issue was merged

**Closed** 2023-05-08 15:17 UTC
