### ISSUE TITLE
Streaming client request in api endpoints

### ISSUE THREAD

**Issue by quentincaffeino** [sveltejs/kit#2992] opened 2021-12-06 09:23 UTC
### Describe the problem

Request streaming comes handy where you have very large requests and you don't want to clutter your ram with whole request and wait for it to fully upload, this way you can start processing it right away.

I found this example for nodejs http server which might give you a better idea of how this could be used:

```js
http.createServer(function(r, s) {
    console.log(r.method, r.url, r.headers);
    var body = "";
    r.on('readable', function() {
        body += r.read(); // here instead of concatenation we could start processing data
    });
    r.on('end', function() {
        console.log(body);
        s.write("OK"); 
        s.end(); 
    });
}).listen(42646);
```

This could be useful for any non-static adapter.

This would also allow creating proxy endpoints where body is streamed to another fetch request (related: https://github.com/sveltejs/kit/issues/2227). This is helpful because application could have handful of services and you might want to hide and open only one (in this case the sveltekit) which does some processing (maybe authentication) and then passes that request to another service.

### Describe the proposed solution

Obvious one is to pass request stream to endpoint. But I'm not sure how it would work with current solution where you have for example FormData parsing which expects for request to be fully loaded and only then endpoint can start doing it's thing.

### Importance

would make my life easier

**Comment by Conduitry** [comment] 2021-12-06 14:41
Duplicate of #1563.

**Comment by quentincaffeino** [comment] 2021-12-06 14:52
> Duplicate of #1563.

@Conduitry Is it? Maybe I've missed something there but it seems that that issue is about streaming response where my is about streaming request.

**Comment by Rich-Harris** [comment] 2022-04-24 14:27
#3419 covers both requests and responses — closing

**Closed by Rich-Harris** 2022-04-24 14:27 UTC
