### ISSUE TITLE
Usage of streams causing file descriptor leak

### ISSUE THREAD

**Issue by Hirevo** [sveltejs/kit#12173] opened 2024-04-29 18:25 UTC
### Describe the bug

I am attempting to make a SvelteKit API endpoint that makes a request to another backend API and streams the response body of its own response body, using `fetch` and `response.body`, like so:

```javascript
// `filterHeaders` is simply a function to filter only some desired headers.

/** @type {import('./$types').RequestHandler} */
export async function GET(event) {
    const requestHeaders = filterHeaders(event.request.headers, ['range']);
    const response = await fetch('http://example.com/some/example/endpoint', {
        signal: event.request.signal,
        headers: requestHeaders,
    });
    const responseHeaders = filterHeaders(
        response.headers,
        ['content-length', 'content-type', 'content-range', 'accept-ranges'],
    );
    return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers: responseHeaders,
    });
}
```

While this code works, it seems to leak a file descriptor each time it is requested, especially in the context of HTTP range requests while playing video content.

I have tried many variations of this code, like using `pipeThrough` or `pipeTo`, using the `pipeline` function from the `node:stream/promises` module, or using `axios` to make the request and converting the body back to a `ReadableStream`, but all of them demonstrated the issue, which prompts to me that maybe its the `@sveltejs/adapter-node` that doesn't close the response stream properly.

After some time, this issue leads to my app being unable to fulfil new requests, and the node process must be restarted.

### Reproduction

I have made a minimal demo app to demonstrate the issue here:

<https://github.com/Hirevo/sveltekit-stream-issue>

The index page has steps of how to observe the issue, using `lsof`.

### System Info

```Shell
System:
  OS: macOS 14.4.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 411.48 MB / 16.00 GB
  Shell: 0.1.0 - /Users/nicolaspolomack/.cargo/bin/psh
Binaries:
  Node: 22.0.0 - ~/.local/state/fnm_multishells/18305_1714256923846/bin/node
  Yarn: 1.22.22 - /usr/local/bin/yarn
  npm: 10.5.1 - ~/.local/state/fnm_multishells/18305_1714256923846/bin/npm
Browsers:
  Chrome: 124.0.6367.91
  Safari: 17.4.1
  Safari Technology Preview: 17.4
npmPackages:
  @sveltejs/adapter-node: ^5.0.1 => 5.0.1
  @sveltejs/kit: ^2.0.0 => 2.5.7
  @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.0
  svelte: ^4.2.7 => 4.2.15
  vite: ^5.0.3 => 5.2.10
```

### Severity

annoyance

### Additional Information

From some of my research on this, I am aware that `undici`, which implements `fetch` in Node, does [not release connection resources upon garbage collection](https://undici.nodejs.org/#/?id=garbage-collection).

I made multiple attempts to close it myself, but I was unsuccessful.

**Comment by hanszoons** [comment] 2024-04-29 19:34
Perhaps related to #11617?

**Comment by t1u1** [comment] 2024-07-25 16:16
Could be also related to https://github.com/sveltejs/kit/issues/11751

When streaming, the request channel doesn't seem to get closed ever. Not sure at which layer (socket FD or some node abstraction).

**Comment by eltigerchino** [comment] 2024-10-29 06:33
I'm closing this since I'm unable to reproduce the issue with the latest SvelteKit and Vite running on Noda 20.18.0

**Closed by eltigerchino** 2024-10-29 06:33 UTC
Labels: pkg:adapter-node
