### ISSUE TITLE
adapter-node return "application/javascript" for mjs instead "text/javascript"

### ISSUE THREAD

**Issue by stalkerg** [sveltejs/kit#11393] opened 2023-12-19 02:38 UTC
### Describe the bug

For all mjs file adapter node return wrong mime type, because of this Cloudflare can't properly cache it. 

### Reproduction

Just check header from SvelteKit adapter-node. 

### Logs

```Shell
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Vary: Accept-Encoding
  cache-control: public,max-age=31536000,immutable
  Content-Length: 31277
  Content-Type: application/javascript
  Last-Modified: Mon, 18 Dec 2023 14:45:58 GMT
  ETag: W/"31277-1702910758672"
  Date: Tue, 19 Dec 2023 02:26:36 GMT
  Connection: keep-alive
  Keep-Alive: timeout=5
```

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (1) x64 AMD EPYC 7542 32-Core Processor
    Memory: 395.87 MB / 861.39 MB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.13.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: 1.3.1 => 1.3.1 
    @sveltejs/kit: 1.30.3 => 1.30.3 
    @sveltejs/svelte-virtual-list: github:sveltejs/svelte-virtual-list => 3.0.1 
    svelte: 4.2.8 => 4.2.8 
    vite: 4.5.0 => 4.5.0
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment] 2023-12-19 21:54
Likely coming from here: https://github.com/jshttp/mime-db/blob/a76e5a824c228e2e58363c9404e42a54ee1d142f/src/iana-types.json#L9942

It looks to me like `text/javascript` is correct and changing it to `application/javascript` would not be: https://stackoverflow.com/questions/21098865/text-javascript-vs-application-javascript

I think we should probably close this issue and you should file one at Cloudflare

**Comment by benmccann** [comment] 2023-12-19 21:55
Oh, I misread this. You're saying it's returning `application/javascript` now. Hmm. I wonder where that's coming from...

**Comment by benmccann** [comment] 2023-12-19 22:00
```
node_modules/.pnpm/mrmime@1.0.1/node_modules/mrmime/index.js:  "js": "application/javascript",
node_modules/.pnpm/mrmime@1.0.1/node_modules/mrmime/index.js:  "mjs": "application/javascript",
```

**Comment by benmccann** [comment] 2023-12-19 22:02
Caused by https://github.com/lukeed/mrmime/issues/8

**Comment by stalkerg** [comment] 2023-12-20 01:24
@benmccann I tried to update mrmime manually and it didn't help. Anyway, thanks.

**Comment by benmccann** [comment] 2023-12-20 15:59
Thanks @lukeed. We'll need `sirv` to use the latest version of `mrmime`, so I just sent you a PR for that: https://github.com/lukeed/sirv/pull/156

**Closed** 2023-12-20 17:31 UTC
Labels: bug, blocked by upstream

**Comment by stalkerg** [comment] 2023-12-21 03:55
Thanks, @benmccann and @lukeed !!!
