### ISSUE TITLE
Resolve builds with commonjs

### ISSUE THREAD

**Issue by puchesjr** [sveltejs/kit#622] opened 2021-03-24 03:58 UTC
I am a huge fan of svelte and love the community.  While attempting to use Kit, I have experienced some serious pain points when attempting to install packages like Firebase and pdf-kit.  The packages will work when you run `npm run dev`; however, when you attempt to build `npm run build` you will encounter a build error  ```Directory import '/Users/DOE/Projects/****/node_modules/firebase/app' is not supported resolving ES modules imported from /Users/DOE/Projects/****/.svelte/output/server/app.js
Did you mean to import firebase@8.3.1/node_modules/firebase/app/dist/index.cjs.js?```

We have worked around this by using dynamic imports but it is not the best dev experience.

While firebase and pdfkit may not be developed with best practices, these two packages will not be the only ones to cause pain points and issues for users of svelte-kit.

Ideally, I would like to see svelte-kit resolve the issue internally at build time- and remove the pain from the developer/user having to configure multiple configs in the `svelte.config.cjs`.

**Comment by benmccann** [comment] 2021-03-24 04:56
This sounds like a duplicate of https://github.com/sveltejs/kit/issues/612

**Closed by benmccann** 2021-03-24 04:56 UTC
