### ISSUE TITLE
Simple POST Action with redirect gives an empty screen

### ISSUE THREAD

**Issue by ciscoheat** [sveltejs/kit#6003] opened 2022-08-17 21:48 UTC
### Describe the bug

I'm testing the routing update, with the simplest possible form I can make, but when redirecting after POST, the screen goes completely white after a moment. Changing the return value of the action to anything else, for example `{ status: 403 }`, doesn't produce the white screen.

### Reproduction

**src/routes/+page.svelte**
```html
<h1>Welcome to SvelteKit</h1>

<form method="POST">
  <button>Submit</button>
</form>
```

**src/routes/+page.server.ts**
```typescript
export async function POST() {
  return {
    location: '/'
  }
}
```

### Logs

```shell
Request:
POST / HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,sv;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 0
Content-Type: application/x-www-form-urlencoded
Host: 127.0.0.1:5173
Origin: http://127.0.0.1:5173
Referer: http://127.0.0.1:5173/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

Response:
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
location: /
Date: Wed, 17 Aug 2022 21:44:03 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 50.24 GB / 63.93 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64
    @sveltejs/kit: next => 1.0.0-next.418
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.8
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment] 2022-08-17 21:58
Duplicate of #5976, which has been fixed on `master` but not released yet.

**Closed by Conduitry** 2022-08-17 21:58 UTC
