### ISSUE TITLE
Error when evaluating SSR module (Unexpected token 'export') in DEV

### ISSUE THREAD

**Issue by livehtml** [sveltejs/kit#2914] opened 2021-11-25 13:02 UTC
### Describe the bug

When I run `pnpm run dev` and load some page I've got an error in console:

```
3:53:23 PM [vite] Error when evaluating SSR module /.svelte-kit/dev/runtime/internal/singletons.js:
SyntaxError: Unexpected token 'export'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (/home/www/sources/node_modules/.pnpm/vite@2.6.14_sass@1.43.5/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66543:28)
3:53:23 PM [vite] Error when evaluating SSR module /.svelte-kit/dev/runtime/app/navigation.js:
SyntaxError: Unexpected token 'export'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (/home/www/sources/node_modules/.pnpm/vite@2.6.14_sass@1.43.5/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66543:28)
3:53:23 PM [vite] Error when evaluating SSR module /src/lib/Components/Base/LoginPopup.svelte:
SyntaxError: Unexpected token 'export'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (/home/www/sources/node_modules/.pnpm/vite@2.6.14_sass@1.43.5/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66543:28)
3:53:23 PM [vite] Error when evaluating SSR module /src/routes/__layout.svelte:
SyntaxError: Unexpected token 'export'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (/home/www/sources/node_modules/.pnpm/vite@2.6.14_sass@1.43.5/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66543:28)
Unexpected token 'export'
SyntaxError: Unexpected token 'export'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (/home/www/sources/node_modules/.pnpm/vite@2.6.14_sass@1.43.5/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66543:28)
```

But if I reload the page — no more errors until I again restart dev.

### Reproduction

I can't tell exaclty why and when in happens, but looks like it's an error from packages. Probably after updating dependencies few days ago.

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (2) x64 DO-Regular
    Memory: 249.28 MB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/bin/node
    npm: 8.1.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.55 => 1.0.0-next.55 
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21 
    @sveltejs/kit: next => 1.0.0-next.200 
    svelte: ^3.44.2 => 3.44.2
```

### Severity

serious, but I can work around it

**Comment by bluwy** [comment] 2021-11-25 17:31
I created a skeleton app and run in dev but I'm not getting the errors. Please provide a reproduction so we can track this down. Thanks!

**Comment by livehtml** [comment] 2021-11-25 19:37
Sorry, it was my mistake. But the reason of this error output totally unclear. I've just put image with wrong path (missed file):
```img(src="images/default-ava.svg", alt="ava")```
(I'm using svelte preprocess Pug)

So, it's really strange error output. And there is even no file where I'm put this missed image. Totally confused 🤷‍♂️

**Comment by jrmoynihan** [comment] 2021-11-25 20:25
Having the same types of issues here.  Valid Vite imports of functions in my .ts files are just failing.  Seems really random.

**Comment by dominikg** [comment] 2021-11-25 20:33
Without a proper reproduction there is nothing we can do to analyze this further. Please provide the required information.

**Comment by Rich-Harris** [comment] 2022-04-28 18:59
The issue in the reproduction is caused by `echarts` exposing native JS modules without having `"type": "module"` in its package.json. This is a bug in that library; it should either add `"type": "module"` and use `.cjs` for the CommonJS files, or use `.mjs` for the modules. Either way, it should add an `"exports"` field to package.json. Otherwise, it won't work correctly in Node.

It can be worked around by including it in Vite's processing:

```js
// svelte.config.js
export default {
  kit: {
    vite: {
      ssr: {
        noExternal: ['echarts']
      }
    }
  }
};
```

No idea what's going on with the original issue but since there's no repro there's no way for us to investigate — closing.

**Closed by Rich-Harris** 2022-04-28 18:59 UTC
Labels: vite, p3-edge-case

**Comment by csjh** [comment] 2022-07-15 07:57
> The issue in the reproduction is caused by `echarts` exposing native JS modules without having `"type": "module"` in its package.json. This is a bug in that library; it should either add `"type": "module"` and use `.cjs` for the CommonJS files, or use `.mjs` for the modules. Either way, it should add an `"exports"` field to package.json. Otherwise, it won't work correctly in Node.
> 
> It can be worked around by including it in Vite's processing:
> 
> ```js
> // svelte.config.js
> export default {
>   kit: {
>     vite: {
>       ssr: {
>         noExternal: ['echarts']
>       }
>     }
>   }
> };
> ```
> 
> No idea what's going on with the original issue but since there's no repro there's no way for us to investigate — closing.

This workaround isn't working anymore after the switch to Vite 3, reproduction in https://github.com/csjh/broken_kit
