### ISSUE TITLE
Setting BODY_SIZE_LIMIT to 0 in node adapter causes error

### ISSUE THREAD

**Issue by NormandoHall** [sveltejs/kit#11534] opened 2024-01-07 17:27 UTC
### Describe the bug

Documentation says setting `BODY_SIZE_LIMIT` to zero, disables this options (I think check), but get a 413 error 

https://kit.svelte.dev/docs/adapter-node#environment-variables-bodysizelimit

### Reproduction

Set the env variable `BODY_SIZE_LIMIT` to zero

.env file:

`BODY_SIZE_LIMIT=0`

### Logs

```Shell
SvelteKitError: Content-length of 717078 exceeds limit of 0 bytes.
    at Object.start (file:///opt/minerva/devel/build/handler.js:975:19)
    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2342:23)
    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2375:3)
    at new ReadableStream (node:internal/webstreams/readablestream:286:7)
    at get_raw_body (file:///opt/minerva/devel/build/handler.js:972:9)
    at getRequest (file:///opt/minerva/devel/build/handler.js:1044:9)
    at Array.ssr (file:///opt/minerva/devel/build/handler.js:1194:24)
    at handle (file:///opt/minerva/devel/build/handler.js:1259:23)
    at file:///opt/minerva/devel/build/handler.js:1259:40
    at Array.<anonymous> (file:///opt/minerva/devel/build/handler.js:1187:4) {
  status: 413,
  text: 'Payload Too Large'
}
```

### System Info

```Shell
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (4) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 1.69 GB / 15.51 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 18.18.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.5 - /usr/bin/npm
    pnpm: 8.6.5 - /usr/bin/pnpm
  npmPackages:
    @sveltejs/adapter-node: ^2.0.2 => 2.0.2 
    @sveltejs/kit: ^2.0.6 => 2.0.6 
    @sveltejs/vite-plugin-svelte: ^3.0.1 => 3.0.1 
    svelte: ^4.2.8 => 4.2.8 
    vite: ^5.0.11 => 5.0.11
```

### Severity

annoyance

**Comment by Conduitry** [comment] 2024-01-07 17:33
Duplicate of #11381,

**Closed by Conduitry** 2024-01-07 17:33 UTC
