### ISSUE TITLE
Prerendering with dynamic parameters using `adapter-static` not working after PR #1743

### ISSUE THREAD

**Issue by truumahn** [sveltejs/kit#1977] opened 2021-07-21 09:29 UTC
### Describe the bug

I think #1743 might have resulted in [dynamic parameters as directory names](https://kit.svelte.dev/docs#routing-advanced-rest-parameters) not picked up correctly when prerendering dynamic routes (with `adapter-static` at least).

I'm using this [template project for rendering markdown](https://github.com/jakobbouchard/sveltekit-netlifycms) and since it's using an older version of SvelteKit prerender works properly.

After some debugging I've found that the issue is with the regex modifications introduced in #1743, once you update to 118+ the pages are no longer prerendered on dynamic routes.

### Reproduction

Steps to reproduce:

1. `git clone https://github.com/jakobbouchard/sveltekit-netlifycms`
2. `npm install`
3. `npm run build`
4. `cat build/blog/test-file/index.html` ~ pages on dynamic routes are prerendered in `build` directory
5. `rm -rf .svelte-kit build`
6. `npm upgrade`
7. `npm run build`
8. `cat build/blog/test-file/index.html` ~ no file = no prerender

After directly editing `node_modules/@sveltejs/kit/dist/chunks/index6.js` and removing the regex parts added in #1743 prerender works again.

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 21.94 GB / 24.57 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    npm: 7.18.1 - ~/.nvm/versions/node/v14.17.1/bin/npm
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.13
    @sveltejs/kit: next => 1.0.0-next.132
    svelte: ^3.34.0 => 3.38.3
    vite: ^2.2.3 => 2.4.2
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment] 2021-07-21 23:24
Closing as duplicate of https://github.com/sveltejs/kit/issues/1918

**Closed by benmccann** 2021-07-21 23:24 UTC
Labels: bug
