### ISSUE TITLE
Skeleton SvelteKit app crashed in Netlify

### ISSUE THREAD

**Issue by jymma** [sveltejs/kit#6759] opened 2022-09-12 20:48 UTC
### Configuration :

When creating a new SvelteKit project with the following options :

✔ Which Svelte app template? › **Skeleton project**
✔ Add type checking with TypeScript? › **Yes, using JavaScript with JSDoc comments**
✔ Add ESLint for code linting? … **No** / Yes
✔ Add Prettier for code formatting? … **No** / Yes
✔ Add Playwright for browser testing? … **No** / Yes

### Error :

The deployment to Netlify succeeds, but the app crashes accessing to the homepage, with the following error :

`Error - No "exports" main defined in /var/task/node_modules/devalue/package.json`

### Stack trace :

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /var/task/node_modules/devalue/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/task/.netlify/server/index.js:50:22)
```

### Reproduction

See the online app [here](https://lucent-elf-e5ce1f.netlify.app/)

### Logs

```shell
Failed to load resource: the server responded with a status of 502 ()
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 307.15 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72 
    @sveltejs/kit: next => 1.0.0-next.480 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.0
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment] 2022-09-12 20:53
Duplicate of #6462.

**Closed by Conduitry** 2022-09-12 20:53 UTC
