### ISSUE TITLE
$env/dynamic/private does not work in edge functions 

### ISSUE THREAD

**Issue by arackaf** [sveltejs/kit#8859] opened 2023-02-02 18:43 UTC
### Describe the bug

This seems related to https://github.com/sveltejs/kit/issues/7556 but I don't think it's the same.

When using edge deployments, it appears as though 

```js
import { env } from "$env/dynamic/private";
```

no longer works. `env` is not just an empty object, while valid keys off of it are now undefined. Replacing with 

```js
import { KEY } from "$env/static/private";
```

does seem to work, and is probably better, but this does feel like a bug. 

### Reproduction

n/a - not sure how to share a project / Vercel logs for any project we don'g jointly own. 

### Logs

```Shell
n/a
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 26.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/yarn
    npm: 9.3.0 - ~/Documents/git/booklist/svelte-kit/node_modules/.bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.2 => 1.0.2 
    @sveltejs/adapter-vercel: ^1.0.6 => 1.0.6 
    @sveltejs/kit: ^1.3.3 => 1.3.3 
    svelte: ^3.55.0 => 3.55.1 
    vite: ^4.0.3 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment] 2023-02-03 12:04
You're saying "no longer works" - so did it work for you at some point? If not, this sounds like a duplicate of #7556 to me

**Comment by Rich-Harris** [comment] 2023-02-03 13:25
It's a dupe, yeah. The limitation is covered in the docs https://kit.svelte.dev/docs/adapter-vercel

**Closed by Rich-Harris** 2023-02-03 13:25 UTC
Labels: pkg:adapter-vercel, awaiting submitter

**Comment by arackaf** [comment] 2023-02-03 15:08
@dummdidumm ambiguous wording on my part - I meant just "do not work with edge set"

7556 seemed different, but it sounds like this is a known issue / by design so sorry for the interruption
