### ISSUE TITLE
Named layouts for +error.svelte

### ISSUE THREAD

**Issue by madeleineostoja** [sveltejs/kit#6014] opened 2022-08-18 03:53 UTC
### Describe the problem

I'm in the middle of migrating a very large Sveltekit project to the new routing system, and I'm trying to take advantage of sibling layout inheritance, by putting low level stuff (data loading, base metadata, auth guards, etc) that was previously duplicated between layouts in a default `layout` and then using named layouts for the layouts I had.

This was working great until I came to `+error.svelte`, when I try to use my new named layout (`layout` → `layout-root`) kit throws an error about `+` being a reserved character.

### Describe the proposed solution

`+error` should be able to use named layouts, eg: `+error@root`.

### Alternatives considered

Go back to sharing data loading etc with a higher order function, rather than the "sveltekit" way with layout inheritence.

### Importance

nice to have

**Comment by dummdidumm** [comment] 2022-08-18 08:25
Duplicate of #4582

**Closed by dummdidumm** 2022-08-18 08:25 UTC
