### ISSUE TITLE
+page.server.ts function load can't use fetch('/api/target/') without getting error: "Failed to parse URL" (either a documentation issue or a bug?)

### ISSUE THREAD

**Issue by RocketDerp** [sveltejs/kit#7231] opened 2022-10-11 16:44 UTC
### Describe the bug

The documentation on Advanced Routing doesn't show that fetch('/api/target/') URL style doesn't work on +page.server.ts/+page.server.js file load function.

Is this a bug or is it a documentation issue?

### Reproduction

fetch('http://localhost:3000/api/target/') URL works.

fetch('/api/target/) generates server-side error: "Failed to parse URL" on node console.

### Logs

```shell
TypeError: Failed to parse URL from /api/target/
    at fetch (../node_modules/undici/index.js:105:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async load (../src/routes/target/+page.server.ts:12:25)
    at async load_server_data (../node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:31:17)
    at async file:../node_modules/@sveltejs/kit/src/runtime/server/page/index.js:142:13
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
    Memory: 11.68 GB / 19.45 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 105.0.3
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment] 2022-10-11 16:48
If you are not using the `fetch` function passed to `load` that's expected, the built-in `fetch` does only accept absolute URLs / URLs with an origin. If you are using the provided `fetch` function, please provide a reproducible.

**Comment by dummdidumm** [comment] 2022-10-11 18:41
`fetch` in `+page/layout.server.js` is relatively new. It's documented here: https://kit.svelte.dev/docs/load#input-methods-fetch - we want to look into expanding the details on that a little more in the future.

Closing as the issue is solved.

**Closed by dummdidumm** 2022-10-11 18:41 UTC
Labels: awaiting submitter
