### ISSUE TITLE
Load() function in +page.js and +page.svelte content is not SSR'ing

### ISSUE THREAD

**Issue by GuillermoCasanova** [sveltejs/kit#7236] opened 2022-10-11 19:44 UTC
### Describe the bug

Both my layout.svelte and page.svelte have their corresponding .js counterparts with their own load functions. Content from layout.svelte is SSR'd and built in server as expected, however, content from page.js is fetched and built client-side. I know this because 1. Only my nav and footer and content in layout.svelte is visible when clicking "page source" and 2. Disabling JS only shows my footer and header, not the content of the page itself. 

### Reproduction

The repo as it stands is here: https://github.com/GuillermoCasanova/maison-matador 

It's a basic SvelteKit project using latest structure and Node Adapter. nothing beyond the basic setup. 

Spinning up the project and going to any page via browser URL (not from clicking a link) should display the issue immediately. This is because no page content will display as non-cors-approved urls will fail to fetch the page content (but the nav/footer successfully build out, even though they are fetched from Sanity), or content will display (with cors-approved urls) but it's not visible in page source (evidence of SSR) 

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 28.57 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.n/bin/node
    npm: 8.15.0 - ~/.n/bin/npm
  Browsers:
    Brave Browser: 106.1.44.108
    Safari: 15.3
```

### Severity

serious, but I can work around it

### Additional Information

A huge reason that I've sold clients on SvelteKit is the ease of SSR-rendering. I might be doing something wrong with the latest updates (and the lack of docs doesn't help) and that's why it's  not working as expected, but if there is a bug this needs to be fixed soon.

**Comment by dummdidumm** [comment] 2022-10-11 19:47
accessing the link gives me 404 not found

**Comment by GuillermoCasanova** [comment] 2022-10-11 19:54
> accessing the link gives me 404 not found

Just made it public, my bad!

**Comment by dummdidumm** [comment] 2022-10-11 20:07
Please provide a minimum reproducible. This project has way too many moving parts to see if this is really a bug inside SvelteKit or something else not working correctly.

**Comment by GuillermoCasanova** [comment] 2022-10-13 20:58
Thanks for telling me to make a reproducible, I actually ended up accidentally finding partly the  culprit. 

 Here's what I found: 

After taking out bit by bit of any extra stuff, I found out having this in my +page.svelte: 

```
<script>
	onDestroy(() => {
		ready = false;
	});

	onMount(() => (ready = true));
</script>
```

And then a {#if ready} wrapped around my page's content, this would prevent it from being delivered to client already built out. I noticed this because pages that had this wouldn't have their content SSR'd, but pages that didn't have it would actually SSR (evidenced by viewing page source). It appears {ready} would wait for the client-side CMS call to be made and then it'd show the content client-side only and not build it in the server? 

Hopefully this helps anybody that runs into this trying to hide/show animate their page. This isn't really needed for animation as one can just use:

```
	in:fade="{{ duration: 500, delay: 150, easing: cubicOut }}"
	out:fade="{{ duration: 150, easing: cubicOut }}"
```

on the page's content. 

But, that said, my <svelte:head> content inside of the +page.svelte still doesn't appear to be SSR'D. Does <svelte:head> need to be inside of +layout.svelte for SSR of SEO to work then? Or is there something I'm doing wrong and they can't be placed in each +page.svelte? It'd be a bummer if so, as some pages have unique ways to access their SEO from the CMS. 

Trimmed down repo: 
[](https://github.com/GuillermoCasanova/ssr-reproducible-svelte-kit-test
)

Repo deployed on Heroku (content SSrs, but not the SEO data): 
[https://ssr-reproducible.herokuapp.com/our-work/honor-the-gift]

**Comment by dummdidumm** [comment] 2022-10-19 08:00
The `MetaTags` component you use already wraps everything inside `<svelte:head>`, so your code wrapping it in `<svelte:head>` may have something to do with that. Also, I see that the `<title>` tag is SSR'd in the `<head>`, so _something_ seems to work there, which makes me think that this may not be a SvelteKit issue. Also, the page you linked does have the head content commented out.

Closing since I don't think this is something to fix on our side. But if you think otherwise we can reopen.

**Closed by dummdidumm** 2022-10-19 08:00 UTC
Labels: awaiting submitter
