### ISSUE TITLE
Update wrangler dependency used by `@sveltejs/adapter-cloudflare` 

### ISSUE THREAD

**Issue by jasongitmail** [sveltejs/kit#12639] opened 2024-09-02 16:34 UTC
### Describe the bug

I discovered that the `@sveltejs/adapter-cloudflare` adapter makes a wrangler binary available in the project, which will be invoked for commands used in package.json. Currently this creates some weirdness/headaches due to wrangler version mismatch vs a version that a dev will likely have installed globally.

The adapter loads wrangler ~v3.3. Current wrangler version is 3.73.0

When starting an app using a package.json command of `wrangler pages dev...`, these versions give very different results:

Output from v3.3 (unexpected resources listed for local env)
```yaml
- KV Namespaces:
  - KV: b733bcb3ad23FAKE4b24b3081f9b8091
  - KV: KV
- D1 Databases:
  - D1: mysite-prod (D1), Preview: (D1)
  - D1: local-D1 (D1)
- R2 Buckets:
  - R2: mysite-preview
  - R2: R2
```

Output from wrangler v3.73.0 (expected)
```yaml
- KV Namespaces:
  - KV: KV
- D1 Databases:
  - D1: local-D1 (D1)
- R2 Buckets:
  - R2: R2
```

Wrangler is the cause of this, but updating it in the adapter will reduce other devs encountering similar.

Workaround: install wrangler as a `devDependency`, so this more recent binary is used for commands in `package.json`, instead of the wrangler binary from the adapter.

### Reproduction

.

### System Info

```Shell
System:
    OS: macOS 14.5
  Binaries:
    Node: 22.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
    pnpm: 9.0.6 - /opt/homebrew/bin/pnpm
    bun: 1.1.26 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 126.1.67.123
    Chrome: 128.0.6613.113
    Safari: 17.5
  npmPackages:
    @sveltejs/adapter-cloudflare: ^4.7.2 => 4.7.2 
    @sveltejs/enhanced-img: ^0.2.0 => 0.2.0 
    @sveltejs/eslint-config: ^7.0.1 => 7.0.1 
    @sveltejs/kit: ^2.5.7 => 2.5.7 
    @sveltejs/vite-plugin-svelte: ^3.1.0 => 3.1.0 
    svelte: ^5.0.0-next.123 => 5.0.0-next.123 
    vite: ^5.2.11 => 5.2.11
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-09-04 18:18
Which package manager are you using? I couldn't reproduce this locally (I'm using pnpm).

**Comment by jasongitmail** [comment] 2024-09-04 18:43
Bun. 

But it's dependent on which version of wrangler is executed for package.json scripts (`echo $(which wrangler)` in a package.json script).

That said, OK to close this issue imo if you don't want to update wrangler just yet.

When using the new-ish `platformProxy`, I was able to remove `wrangler pages dev ...` commands from my project and there is actually no such output visible, so devs using that won't be confused at least.

**Comment by eltigerchino** [comment] 2024-09-05 11:56
I'm not sure how to reproduce with Bun so I'm going to close this for now. If you can provide a minimal reproduction, I'll open this again and try to reproduce it.

**Closed by eltigerchino** 2024-09-05 11:56 UTC
Labels: awaiting submitter
