### ISSUE TITLE
Svelte Kit's `fetch` and the Browser's `fetch` Produce Inconsistent Results

### ISSUE THREAD

**Issue by Acmion** [sveltejs/kit#2802] opened 2021-11-14 23:47 UTC
### Describe the bug

Calling `await fetch(url)` from Svelte Kit `load` produces different results than when calling from the browser.

In a nutshell, given at least one special case, Svelte Kit's `fetch` will be able to retrieve a file, even if the browser's `fetch` will not.

While the special case given in the reproducing repo is not a very common use case, it may still shed some light on other inconsistencies in the custom implementation of `fetch`.

### Reproduction

https://github.com/Acmion/svelte-kit-fetch-bug

### Logs

```shell
(node:1560) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /#bug.html
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at new Request (file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5543:16)
    at file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5753:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5751:9)
    at loadBrowser (/src/routes/index.svelte:24:24)
    at eval (/src/routes/index.svelte:28:2)
    at Object.$$render (D:\Acmion\Temp\svelte-kit-fetch-bug\node_modules\svelte\internal\index.js:1684:22)
    at Object.default (/D:\Acmion\Temp\svelte-kit-fetch-bug\.svelte-kit\dev/generated/root.svelte:57:127)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an a
sync function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandle
d_rejections_mode). (rejection id: 2)
(node:1560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
(node:1560) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: /#bug.html
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at new Request (file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5543:16)
    at file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5753:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Acmion/Temp/svelte-kit-fetch-bug/node_modules/@sveltejs/kit/dist/install-fetch.js:5751:9)
    at loadBrowser (/src/routes/index.svelte:24:24)
    at eval (/src/routes/index.svelte:28:2)
    at Object.$$render (D:\Acmion\Temp\svelte-kit-fetch-bug\node_modules\svelte\internal\index.js:1684:22)
    at Object.default (/D:\Acmion\Temp\svelte-kit-fetch-bug\.svelte-kit\dev/generated/root.svelte:57:127)
(node:1560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an a
sync function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandle
d_rejections_mode). (rejection id: 4)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
    Memory: 1.09 GB / 7.97 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.53)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196
    svelte: ^3.42.6 => 3.44.1
```

### Severity

annoyance

**Comment by rmunn** [comment] 2021-11-15 00:45
Changing the URL from `/#bug.html` to `/%23bug.html` lets the browser retrieve the file\*. So the difference here is that Svelte-Kit's `fetch` can handle some characters that aren't URL-encoded. Whereas the browser's `fetch` treats that as retrieving the `/` URL with a hash of `bug.html`, and `/` maps to `/src/routes/index.html`.

\* I did have to edit the browser example as follows:

```js
    import { browser } from '$app/env';
    async function loadBrowser() { /* ... */ }
    if (browser) loadBrowser();
```

That allows it to run *only* on the browser, instead of during server-side rendering. If I allowed the `loadBrowser` function from your reproduction to run during SSR, Node was throwing `TypeError [ERR_INVALID_URL]: Invalid URL` because the URL wasn't complete (no host, no protocol). (Svelte-Kit's `fetch` has an extra feature where you can write relative URLs and it will expand them based on the base URL you've specified in the config).

IMHO this is a feature, not a bug, but I won't close this issue as I'd like to let a core team member weigh in in case they think this really is a bug.

**Comment by Acmion** [comment] 2021-11-16 16:33
Yeah, I was just thrown off by the fact that I did not have to escape the hash (#) character.

**Closed** 2022-09-03 22:03 UTC
Labels: bug, p3-edge-case, breaking change, low hanging fruit
