### ISSUE TITLE
Lates sveltekit demo app doesn't work with typescript on case-sensitive volumes

### ISSUE THREAD

**Issue by reskume** [sveltejs/kit#13017] opened 2024-11-16 18:32 UTC
### Describe the bug

Sveltekit demo project (latest version) with Typescript has a lot of "Cannot find name 'svelteHTML'" errors in .svelte files and during build is also not able to resolve $lib aliases. This happens for me on MacOS with an encrypted case-sensitive APFS volume. I tried renaming and moving the project folder around on the volume but it always shows the same behavior. 

As soon as the folder is moved to a case-insensitive volume, the errors are gone and everything works as expected. This behavior can also be reproduced in different editors - I tested it with VSCode and the latest Webstorm.

All other typescript (non-svelte/sveltekit) project on the case-sensitive volume work flawlessly.

### Reproduction

Create a demo project using `npx sv create svelte-app`. Select ` SvelteKit demo`, `Typescript syntax`, `prettier, eslint, vitest`and `npm`. Move the complete folder to APFS case-sensitive volume. Restart the LSP (I used VSCode).
A high number of errors pop up in the editor.

### System Info

```Shell
System:
    OS: macOS 15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 902.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.6.0 - ~/.asdf/installs/nodejs/22.6.0/bin/node
    npm: 10.8.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 18.1
```

### Severity

annoyance

**Comment by dummdidumm** [comment] 2024-11-16 20:22
Closing as duplicate of https://github.com/sveltejs/language-tools/issues/2584 - thanks for the hint with case-sensitive volumes. This might hint at what the culprit is (which I haven't found yet).

**Closed by dummdidumm** 2024-11-16 20:22 UTC
