### ISSUE TITLE
vite build static assets are inlined

### ISSUE THREAD

**Issue by tanhauhau** [sveltejs/kit#461] opened 2021-03-07 02:29 UTC
**Describe the bug**

Because of how svelte kit is passing the entry file as `lib:` in vite build

https://github.com/sveltejs/kit/blob/5416bd7ea935a9db22d95b0c57ae6e119869c002/packages/kit/src/core/build/index.js#L58-L62

all static files, ie: `*.png`, `*.mp4` are inlined in the build, due to this logic in vite:

https://github.com/vitejs/vite/blob/5d4e82d90238b0d52ded1eea6359947eefc5e054/packages/vite/src/node/plugins/asset.ts#L200-L207

**Expected behavior**
Honour `assetsInlineLimit` in `vite.config.js` and emit as a separate assets if it exceeds the inline limit.

I can understand why vite is implemented that way, at the same time, I'm not sure what other apis / ways we could do on svelte kit side alone. I believe this requires changes on both sides

**Comment by aloker** [comment] 2021-03-27 13:43
I just stumbled upon this issue. All assets are inlined - images, fonts, etc. For example, I was trying to use a @fontsource package and the font files referenced by the css file in the package were all inlined into the generated css files. Images that are referenced from components are inlined in the respective javascript (and html in case of adapter-static) files.

I'd very much like to explicitly import assets from js/css to benefit from hashed file names (infinitely cachable) and maybe other pipeline steps (e.g. image optimizations).

**Comment by aloker** [comment] 2021-03-27 13:56
The problem is actually not the assetsInlineLimit, but rather the fact the build.lib configuration option is set by Svelte Kit:

https://github.com/sveltejs/kit/blob/17bb699a4f4fc6e9331d8874bc7d56c8c81babbe/packages/kit/src/core/build/index.js#L122-L129

If that is set, assets are never exported as files. Without the lib option, the compiler runs into an issue with the dynamic import polyfill as mentioned in the comments.

**Comment by aloker** [comment] 2021-03-28 20:58
I found that disabling lib mode and explicitly disabling the dynamic import polyfill gives practically identical results, but causes imported assets to be properly emitted.

**Comment by Rich-Harris** [comment] 2021-03-29 02:34
closed via #741

**Closed by Rich-Harris** 2021-03-29 02:34 UTC
