### ISSUE TITLE
`esbuild` causes import errors with `adapter-node`

### ISSUE THREAD

**Issue by AlexRMU** [sveltejs/kit#6440] opened 2022-08-30 17:49 UTC
### Describe the bug

Same issue as https://github.com/sveltejs/kit/issues/2400

After https://github.com/sveltejs/kit/pull/6372, I get:

```js
var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
}) : x)(function (x) {
    if (typeof require !== "undefined")
        return require.apply(this, arguments);
    throw new Error('Dynamic require of "' + x + '" is not supported');
});

...

var crypto_1 = __importDefault(__require("crypto"));
```
Perhaps the problem is https://github.com/evanw/esbuild/issues/1921

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-sczcqj?file=README.md

### System Info

```shell
any
```

### Severity

blocking all usage of SvelteKit

**Comment by AlexRMU** [comment] 2022-08-30 17:49
@benmccann

**Comment by Rich-Harris** [comment] 2022-08-30 19:07
This is happening because now bundle your `devDependencies`, so that they don't need to be installed alongside your deployment.

Your app contains some dependencies that _can't_ be bundled. I was able to get your repro to build and run by moving `mongoose` and `html-minifier` from `devDependencies` to `dependencies`.

**Comment by oneserv-heuser** [comment] 2022-08-31 05:17
Having the same issue after upgrading to the newest versions of kit and adapter-node. But in my case it says `Error: Dynamic require of "tty" is not supported` when trying to run in production mode.
So unfortunately I cannot just move any `devDependency` to `dependency` to fix the issue.
Or am I missing something here?

**Comment by AlexRMU** [comment] 2022-08-31 05:21
How do I find out which dependencies can't be bundled? Just because such errors appear?
For example, if I build only mongoose, everything will work: https://stackblitz.com/edit/sveltejs-kit-template-default-gikzvb?file=README.md
And uglify-js contains the following code:
```js
exports.FILES = [
    require.resolve("../lib/utils.js"),
    require.resolve("../lib/ast.js"),
    require.resolve("../lib/transform.js"),
    require.resolve("../lib/parse.js"),
    require.resolve("../lib/scope.js"),
    require.resolve("../lib/compress.js"),
    require.resolve("../lib/output.js"),
    require.resolve("../lib/sourcemap.js"),
    require.resolve("../lib/mozilla-ast.js"),
    require.resolve("../lib/propmangle.js"),
    require.resolve("../lib/minify.js"),
    require.resolve("./exports.js"),
];
```
which for some reason cannot be bundled at the moment. Maybe esbuild needs to add a shim for require.resolve (https://www.npmjs.com/package/@chialab/esbuild-plugin-require-resolve, https://github.com/evanw/esbuild/issues/1311#issuecomment-849144027).

**Comment by AlexRMU** [comment] 2022-08-31 05:26
@oneserv-heuser 
Can you show your vite.config.js?

**Comment by oneserv-heuser** [comment] 2022-08-31 06:42
@AlexRMU Yes, i could but there is nothing spectacular to see, just adds the sveltekit plugin 😀 

Solved my issue, I referenced my tailwindconfig in my src code which has led to the bundling of tailwindcss and all its dependencies in the production build. The module `picocolors` (dependency of tailwindcss) needed `tty` which led to the error. Removed the import of values from the tailwindconfig and everything is working now.

**Comment by AlexRMU** [comment] 2022-08-31 07:22
Without mongoose and html-minifier, the same `Dynamic require` appears. Solved by adding require.

**Comment by Rich-Harris** [comment] 2022-09-01 00:05
> Solved by adding require.

What does this mean?

**Comment by chintan-infiniteshopping** [comment] 2022-09-01 04:01
Having a similar issue after updating to adapter-node 1.0.0-next.88
`Error: Dynamic require of "fs" is not supported`
not sure if its got to do with ant devdependencies
`"devDependencies": {
		"@sveltejs/adapter-auto": "1.0.0-next.71",
		"@sveltejs/adapter-node": "1.0.0-next.88",
		"@sveltejs/kit": "1.0.0-next.460",
		"@tailwindcss/forms": "^0.5.2",
		"@tailwindcss/line-clamp": "^0.4.0",
		"@tailwindcss/typography": "^0.5.4",
		"@types/cookie": "^0.5.1",
		"@typescript-eslint/parser": "^5.36.1",
		"autoprefixer": "^10.4.8",
		"dotenv": "^16.0.2",
		"env-cmd": "^10.1.0",
		"eslint": "^8.23.0",
		"postcss": "^8.4.16",
		"postcss-load-config": "^4.0.1",
		"prettier": "^2.7.1",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.49.0",
		"svelte-check": "^2.9.0",
		"svelte-drawer-component": "^1.2.2",
		"svelte-popperjs": "^1.3.2",
		"svelte-preprocess": "^4.10.7",
		"svelte-table": "^0.5.0",
		"tailwindcss": "^3.1.8",
		"tslib": "^2.4.0",
		"type-fest": "^2.19.0",
		"typescript": "^4.8.2",
		"vite": "3.1.0-beta.1"
	},
	"dependencies": {
		"@fontsource/fira-mono": "^4.5.9",
		"@popperjs/core": "^2.11.6",
		"@rgossiaux/svelte-headlessui": "^1.0.2",
		"@supercharge/fs": "^3.4.0",
		"cookie": "^0.5.0",
		"daisyui": "^2.24.0",
		"date-fns": "^2.29.2",
		"date-fns-tz": "^1.3.7",
		"deep-object-diff": "^1.1.7",
		"knex": "^2.3.0",
		"mysql": "^2.18.1",
		"njwt": "^1.2.0",
		"svelecte": "^3.9.2",
		"svelte-command-palette": "^1.2.0"
	}`

**Comment by AlexRMU** [comment] 2022-09-01 07:05
@Rich-Harris 
As it is written in the readme in the reproduction, you need to add
```js
import { createRequire } from "module";
const require = createRequire(import.meta.url);
```
to the build before `var __require = ...`

**Comment by AlexRMU** [comment] 2022-09-01 07:08
@chintan-infiniteshopping 
If you move all `devDependencies` to `dependencies`, this error will not occur, but the dependencies will not be bundled and they will need to be installed before running

**Comment by spheenik** [comment] 2022-09-05 10:30
@Rich-Harris 

> > Solved by adding require.
> 
> What does this mean?

I am wrestling with this problem for quite a while now. The code that @AlexRMU mentioned is in a chunk file, in my case
`build/server/chunk-BHN6OJC3.js`

```javascript
var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
}) : x)(function (x) {
    if (typeof require !== "undefined")
        return require.apply(this, arguments);
    throw new Error('Dynamic require of "' + x + '" is not supported');
});
```

If you manually patch this file, and add the following directly above the above mentioned code
```javascript
import { createRequire } from "module";
const require = createRequire(import.meta.url);
```

then this issue seems to be solved (it is on my side). Seems to be difficult to patch though. That code is generated by esbuild. I tried to patch the adapter-node to by using esbuilds's `banner` configuration, that however adds the banner to every generated chunk, not just the one. Maybe there's some other nice fix.

**Comment by dlebech** [comment] 2022-09-07 10:33
From @spheenik in https://github.com/sveltejs/kit/issues/6440#issuecomment-1236823838

> If you manually patch this file, and add the following directly above the above mentioned code
> 
> ```js
> import { createRequire } from "module";
> const require = createRequire(import.meta.url);
> ```
> 
> then this issue seems to be solved (it is on my side).

I can confirm this *fixed the issue in my build*. I happen to have a chunk with exactly the same name `server/chunk-BHN6OJC3.js` (probably not a coincidence?), and adding the above code made the build work with `node build` afterwards.

My particular case:
- My specific error is `Error: Dynamic require of "stream" is not supported`
- It looks like it appears during a bundled `node-fetch`
  - which in turn is imported from a bundled `@firebase/auth`
    - which in turn is imported via a `_layout.svelte`
- I have everything that needs to run on the server in `dependencies`, including firebase, so I'm unsure why this gets included in the chunks.

Downgrading to adapter node next.87 for now solves the issue.

**Comment by Anyass3** [comment] 2022-09-08 14:28
I had a similar issue too.
Thanks @dlebech 
> Downgrading to adapter node next.87 for now solves the issue.

This worked for me

**Comment by dlebech** [comment] 2022-09-09 15:54
@theetrain 

> What vite/esbuild config worked for you?

In my case, we're still on sveltekit next.471 and adapter node next.87, i.e. before the introduction of esbuild for including dependencies.

**Comment by theetrain** [comment] 2022-09-09 17:45
@dlebech thanks for the suggestion; I went with the workaround you suggested and downgraded to node-adapter 87. Since my project is built as a docker image, I'll have to include all dependencies instead of the leaner production serve `npm i --production && node build` until this is resolved upstream.

I can tell that node-adapter is marking its dependencies as external:

https://github.com/sveltejs/kit/blob/70e3c34928b4acf408770a0a3bbce08081a92073/packages/adapter-node/index.js#L48-L60

Perhaps it needs to be bundled in, or all dependencies' dependencies should be recurisvely bundled; I'm not too sure.

**Comment by chintan-infiniteshopping** [comment] 2022-09-11 02:55
`Error: Dynamic require of "fs" is not supported`

got this error resolved by using $env/static/private instead of dotenv for environment variables.

**Comment by icalvin102** [comment] 2022-09-12 14:30
@oneserv-heuser can you elaborate on how you solved the issue with tailwind? I'm not sure if I understand your solution correctly.

I'm also running into the `Dynamic require of "tty" is not supported` error that is caused by `tailwind` > `picocolor`. I never imported `tailwind.config.cjs` from any of my project files though.

**Comment by theetrain** [comment] 2022-09-12 16:10
I updated my post above (https://github.com/sveltejs/kit/issues/6440#issuecomment-1242126133), noting a `require` error with the bundled unidici module calling `__require("assert")`.

Here's a work in progress reproduction: https://github.com/theetrain/sveltekit-issue-6440
except unidici won't bundle with `npm run build`. In my main project, it does. While I try to reproduce the issue, can anyone lend me a hint on how undici would or could get bundled?

**Comment by dlebech** [comment] 2022-09-12 16:51
@theetrain Quick note, your reproduction repository looks like it has some issues, for example you're trying to access `fetch` in page.server.js and layout.server.js from the server load event, but `fetch` is not available in server load events -- so it gives a warning and eventually leads to a runtime error "fetch is not a function", even when running the dev server (I'm on Node 16.15)

**Comment by dlebech** [comment] 2022-09-12 17:44
@Rich-Harris it's not enough to move dependencies from `devDependencies` to `dependencies`.

Here's a reproduction of the issue with a single dependency `firebase` and it doesn't matter if it's included in `dependencies` or `devDependencies`: https://github.com/dlebech/sveltekit-6440

The manual workaround [mentioned above](https://github.com/sveltejs/kit/issues/6440#issuecomment-1239210420) solves the issue in this repo as well, but is not feasible to include in automated pipelines.

The `banner` trick also doesn't work, but I assume it's because [adapter-node esbuild config is hardcoded](https://github.com/sveltejs/kit/blob/ec88a709c6f22d84e3c3f80d336f8d55cc072cf2/packages/adapter-node/index.js#L52-L62) and doesn't accept any config parameters.

**Comment by oneserv-heuser** [comment] 2022-09-13 06:55
> @oneserv-heuser can you elaborate on how you solved the issue with tailwind? I'm not sure if I understand your solution correctly.
> 
> I'm also running into the `Dynamic require of "tty" is not supported` error that is caused by `tailwind` > `picocolor`. I never imported `tailwind.config.cjs` from any of my project files though.

I got the issue when using `import tailwindConfig from '$lib/tailwind.config'`. I used variables from the config file in my source code, e.g. passing colors to libraries to not hardcode colors in thge source code again, when all colors are configured in the tailwind config file. Normally the tailwindconfig resides in the root, but vite won't bundle it then correctly so I had to move it to the lib directory.
Importing something from the tailwindconfig caused the bundling of the entire tailwind package and all of it's dependencies in the production code as in my tailwindconfig I imported all the colors like this: `import colors from 'tailwindcss/colors.js'`.
This then led to the error as described because of the usage of `tty` in the browser which is not possible.

I solved the issue with moving the tailwindconfig back to where it belongs, to the root directory of my project. I then wrote a little rollup plugin which takes the config file, extracts all the parameters I use in my production code and then writes it into a new file residing in `src/lib`. So whenever the applicaton is rebuild I get a minimum file with all the values I need without the import of anything from tailwind as everything gets resolved in the build step.

```JS
import tailwindConfig from '../tailwind.config.js'
import * as fs from 'fs'
import { pick } from 'lodash-es'

/* All keys which are needed in the application from the tailwind configuration. */
const requiredKeys = ['screens', 'colors', 'extend', 'spacing']

/**
 * This takes the tailwind config file, prepares it and writes it to src/lib so values from the configuration can be
 * used in components.
 */
export default function bundleTailwindConfig () {
  return {
    name: 'tailwind-config-bundler',
    buildStart () {
      let configObject = tailwindConfig.theme
      configObject = pick(configObject, requiredKeys)
      const content = `/* this file is generated — do not edit it! */ export default ${JSON.stringify(configObject)}`
      fs.writeFile('./src/lib/tailwind.config.js', content, 'utf8', (error) => {
        if (error) throw error

        console.log('Tailwind config file successfully processed.')
      })
    }
  }
}

```

Hope this explanation is sufficient. But I cant help you with the issue that you get the same error as me without importing anything from tailwind :/

**Comment by AlexRMU** [comment] 2022-09-22 08:06
So, https://github.com/sveltejs/kit/pull/6896 appeared and I think the problem with `Dynamic require` is solved.

---
When I try to build all the dependencies, it appears:
A lot of `Circular dependency: ...` and
```
<--- Last few GCs --->

[7236:000002396E15EFC0]   108147 ms: Scavenge 4009.4 (4096.6) -> 4008.8 (4107.3) MB, 6.4 / 0.0 ms  (average mu = 0.338, current mu = 0.329) allocation failure
...

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6FC137A1F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114207
...
```
It was solved by changing the max-old-space-size, but this is not always possible.
Apparently, this is not a rollup problem, you need to wait for ebuild to solve their problems.

**Comment by theetrain** [comment] 2022-09-23 20:19
> So, https://github.com/sveltejs/kit/pull/6896 appeared and I think the problem with Dynamic require is solved.
> — @AlexRMU 

Same here; after upgrading to `@sveltejs/adapter-node@1.0.0-next.95` my issue above (https://github.com/sveltejs/kit/issues/6440#issuecomment-1242282652) went away for me! I can now run a built application after installing production modules only via `npm i --production && node build`.

**Comment by bluwy** [comment] 2022-09-26 07:35
adapter-node now uses `rollup` (#6896) which I believe solved the issue here

**Comment by sw-yx** [comment] 2022-09-29 18:01
@bluwy btw i am also seeing this in adapter-auto on Netlify as well

https://github.com/sw-yx/swyxkit/pull/117

![image](https://user-images.githubusercontent.com/6764957/193107705-3d68ca7c-a2c4-4720-99c8-b4dbbfdc6e08.png)

i am not sure how to fix.

**Comment by bluwy** [comment] 2022-09-30 08:17
@sw-yx Seems like it's happening for `adapter-netlify` (which `adapter-auto` picks) which is still using esbuild. But the original cause #6372 only changes `adapter-node`, so something else might have caused it between v480 to v505. I'm not sure of a workaround too.

**Comment by sw-yx** [comment] 2022-10-06 03:53
agree. i'll just pin my version for adapter-netlify right now, but this continuing to be a bug/problem for netlify as far as i'm aware.

cc @brittneypostma  fyi

**Comment by sw-yx** [comment] 2022-10-06 04:10
issue dates back to adapter auto v74 as far as i can tell https://github.com/sw-yx/swyxkit/pull/117; last working version is v72

**Comment by sw-yx** [comment] 2022-11-28 05:53
I am still seeing this issue today, preventing any upgrade of sveltekit adapter netlify version https://github.com/sveltejs/kit/issues/7839

**Comment by benmccann** [comment] 2022-11-28 06:22
`adapter-node` doesn't use `esbuild` currently, so I'm going to close this in favor of the issue you just filed

**Closed by benmccann** 2022-11-28 06:22 UTC
Labels: bug, pkg:adapter-node, p1-important

**Comment by danez** [comment] 2022-12-12 15:23
We are currently also rolling [out a fix](https://github.com/netlify/zip-it-and-ship-it/pull/1257) that should fix the issue in the bundling on Netlify when using `esbuild` as bundler.

**Comment by sw-yx** [comment] 2022-12-14 14:44
ah wonderful, thank you!
