### ISSUE TITLE
Make title deduplication optional

### ISSUE THREAD

**Issue by vwkd** [sveltejs/kit#2148] opened 2021-08-09 18:14 UTC
### Describe the problem

Currently, title deduplication is the only deduplication of elements that is going on under the hood. But there is consideration to deduplicate more elements, like `<meta>` elements. See https://github.com/sveltejs/kit/issues/2009#issuecomment-886740203

The only reason for this is apparently SEO. Not everyone cares about SEO. I don't care. Yes, it's true.

So what's the issue? Well, how do you know which title is used at the end? Well, you look at the documentation. There is no documentation. But that isn't the issue. Deduplication in a tree structure (component tree) is hard. How hard? Well, currently it's supposed to take the title from the deepest child component. When in fact it doesn't https://github.com/sveltejs/kit/issues/2146

But even if the deduplication did work, changing your component tree structure now might change your title without you wanting it. Now, with every change you need to be aware how it affects this title deduplication. Is this title being filtered out? Which one will win? What happens if there are two child components at the same depth? (Haven't tested that one out actually...)

Title deduplication makes it much harder to reason about my code. And that is when the algorithm doesn't have bugs...

And all of that just because I apparently care about SEO?

All of this is just a perfect example of "Special Cases Are a Code Smell". More special cases, more hidden transformations, more magic. Harder to reason about, more bugs, more wasted time.

### Describe the proposed solution

I'd like to propose making title deduplication (and any future element deduplication) an opt-in option.

Not everyone cares about SEO. I prefer my code to be reasonable and predictable. I don't want to hunt down missing or incorrect `<title>` elements. I don't care if there are two `<title>` elements resulting in my SEO decreasing by 1%.

Those who do care about SEO are welcome to turn on that option.

---

I'd also propose a different algorithm for deduplication. Taking the element from the deepest node tree is difficult and prone to changes in the tree.

A much simpler solution would be to take the first element in the resulting markup. Scan the resulting markup, take the first element that is found, and filter out the rest. This is what browsers do anyway. They take the first `<title>` and ignore the rest. This is what SEO crawlers arguably should do. Scan until the first element and that's it. No need for deduplication.

An additional benefit of this approach is, that you can decide if a child's or a parent's title should be used, depending if you put the child component tag before or after the parent's title tag.

```html
<Child />

<svelte:head>
  <title>Child wins</title>
</svelte:head>
```

```html
<svelte:head>
  <title>Parent wins</title>
</svelte:head>

<Child />
```

### Importance

would make my life easier

**Comment by benmccann** [comment] 2021-08-09 20:25
Duplicate of https://github.com/sveltejs/kit/issues/1540

**Closed by benmccann** 2021-08-09 20:25 UTC
