### ISSUE TITLE
I want to visit my (on production) project like an online website on my phone

### ISSUE THREAD

**Issue by babakfp** [sveltejs/kit#816] opened 2021-04-01 07:54 UTC
**Is your feature request related to a problem? Please describe.**
I want to check out my project how looks and feels on my phone device. Browser dev tools aren't what I want. I want to visit my (on production) project like an online website on my phone.

**Describe the solution you'd like**
This is what Vite.js offers: [Vite Getting Started](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
![Screenshot 2021-04-01 003126-min](https://user-images.githubusercontent.com/44144724/113259236-c0527d00-9281-11eb-8f94-f2dc5fd997a6.png)

**How important is this feature to you?**
Life and death! It's a must.
Right now the only way to see how my project looks on mobile is the browser dev tools. But it doesn't feel right to just loot at the website on smaller screen size. I want to feel my website, I want to know how it going to be for an actual user, I want to touch every button, dropdown, link to see how it is...

**Additional context**
It's just nonsense to not have it!!.
We don't have it in Sapper. I tried to simulate my node.js code on Sapper but it didn't work!.
![Screenshot 2021-03-30 103451](https://user-images.githubusercontent.com/44144724/113260501-33a8be80-9283-11eb-84c3-a66c4668d2f4.png)
I'm not looking for a tutorial or hacks or something like that. I'm looking for a built-in solution. I want to be able to use it when I run `yarn run dev`. Exactly like the Vite.js.

**Comment by dummdidumm** [comment] 2021-04-01 08:00
Possibly duplicate of #688

**Closed** 2021-04-01 14:09 UTC
