### ISSUE TITLE
SSR hides a real error message

### ISSUE THREAD

**Issue by vfilatov** [sveltejs/kit#1028] opened 2021-04-14 20:28 UTC
**SvelteKit v1.0.0-next.74**

**Describe the bug**
SSR doesn't show a real error, which is in my case "ReferenceError: fetch is not defined"
instead of that I get error from ".svelte/dev/components/error.svelte:15:41"

**Logs**
```
TypeError: Cannot read property 'message' of undefined
    at eval (/tmp/tmp/.svelte/dev/components/error.svelte:15:41)
    at Object.$$render (/tmp/tmp/node_modules/svelte/internal/index.js:1369:22)
    at Object.default (//tmp/tmp/.svelte/dev/generated/root.svelte:57:127)
    at eval (/tmp/tmp/src/routes/$layout.svelte:11:41)
    at Object.$$render (/tmp/tmp/node_modules/svelte/internal/index.js:1369:22)
    at eval (//tmp/tmp/.svelte/dev/generated/root.svelte:55:122)
    at $$render (/tmp/tmp/node_modules/svelte/internal/index.js:1369:22)
    at Object.render (/tmp/tmp/node_modules/svelte/internal/index.js:1377:26)
    at render_response (file:///tmp/tmp/node_modules/@sveltejs/kit/dist/ssr.js:377:28)
    at async respond_with_error (file:///tmp/tmp/node_modules/@sveltejs/kit/dist/ssr.js:2572:10)
```
**To Reproduce**
```
npm init svelte@next
npm install
cat <<EOF > src/routes/f.svelte
<script>
  fetch('/');
</script>
<div>Ok</div>
EOF
npm run dev
```
in browser navigate to http://localhost:3000/f

**Comment by Conduitry** [comment] 2021-04-14 20:37
Duplicate of #996, and should get fixed by #1021.

**Closed by Conduitry** 2021-04-14 20:37 UTC
