### ISSUE TITLE
SSR cache control breaks rendering of buffers from endpoints

### ISSUE THREAD

**Issue by antony** [sveltejs/kit#1177] opened 2021-04-22 22:41 UTC
**Describe the bug**
You can render other types of thing than a json payload or string from a SvelteKit endpoint, such as the contents of a buffer. It looks like the caching mechanism for SSR prevents rendering unless you explicitly turn cache control off, due to the way it hashes the payload.

**Logs**
```sh
TypeError: str.charCodeAt is not a function
    at hash (file:///home/ant/Projects/social-share/node_modules/@sveltejs/kit/dist/ssr.js:1511:37)
    at render (file:///home/ant/Projects/social-share/node_modules/@sveltejs/kit/dist/ssr.js:1475:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ssr (file:///home/ant/Projects/social-share/node_modules/@sveltejs/kit/dist/ssr.js:1456:10)
    at async Immediate.<anonymous> (file:///home/ant/Projects/social-share/node_modules/@sveltejs/kit/dist/chunks/index.js:3301:23)
```

**To Reproduce**
Create an endpoint which renders its content as a buffer:

```js
import { createCanvas } from 'canvas'

export async function get() {
  const canvas = createCanvas(10, 10)
  const context = canvas.getContext('2d')

  return {
    headers: {
      // 'cache-control': 'no-store',
      'Content-Type': 'image/png'
    },
    body: canvas.toBuffer('image/png')
  }
}
```

**Expected behavior**
If you try to hit the above endpoint, you will get the error shown above.

To skip the cache and render the canvas contents, uncomment the `cache-control` line to disable caching.

**Information about your SvelteKit Installation:**

<details>
  <summary>
System:
      OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
      CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
      Memory: 8.35 GB / 30.85 GB
      Container: Yes
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.20.1 - ~/.volta/tools/image/node/12.20.1/bin/node
      Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
      npm: 7.5.2 - ~/.volta/tools/image/npm/7.5.2/bin/npm
    Browsers:
      Chrome: 90.0.4430.72
      Firefox: 87.0
    npmPackages:
      @sveltejs/kit: next => 1.0.0-next.85 
      svelte: ^3.29.0 => 3.37.0 
      vite: ^2.1.0 => 2.2.1 
</summary>
</details>

**Severity**
High - buffers should be renderable.

**Comment by benmccann** [comment] 2021-04-22 23:22
Duplicate of https://github.com/sveltejs/kit/issues/1136

**Closed by benmccann** 2021-04-22 23:22 UTC
Labels: bug, straightforward

**Comment by antony** [comment] 2021-04-23 10:01
duh, thanks Ben :)
