### ISSUE TITLE
High delay in navigating when using +page.js

### ISSUE THREAD

**Issue by AxewBoTX** [sveltejs/kit#10791] opened 2023-09-27 05:02 UTC
### Describe the problem

I have been learning svelte and sveltekit for the past 3 to 4 months now and last month I decided to start working on a simple todo app by using pocketbase for Authentication and database. 

Everything was going fine and I was using +page.js files to load data from pocketbase, there is a little lag between making a request to the pocketbase and getting the data from pocketbase which is not that much of an issue, the issue is when that lags turns into a few seconds on the browser.

The data is fetched on the `/base` route and if I go to that route straight then there is no problem, but If I try to  navigate to that route from say `/login` route then the page just stays stuck at `/login` route for 2 to 4 seconds and then the `/base` page is loaded. 
This is alot annoying because it happens for every page on which I use +page.js file to fetch data.

I can use {#await} for fetching data on the client side but then I have to give up SSR.
I just want it like whenever I visit a page, the page is loaded instantly like it would using `{#await}` and wait for the `+page.js` file to laod the data for the page while I can show some skeleton loading animation or stuff like that.

I have noticed that many people have had the same problem as me but till now I have not been able to find a correct and concise solution for this. 

Any help regarding this situation would be really helpfull.

### Describe the proposed solution

I don't really have that much experience to think a really good solution to this problem, but while searching regarding this problem I got to know that the react framework, NextJS, introduced `loading.js` and `fallback` options for routes and components respectively, I really like the idea of the `fallback` option.

while loading data for a page, if the page takes time to load data for a component then that component switches to another component like a loading UI etc that is provided as a prop to original component.

These two seems the best to me but I have one another idea of a solution to this problem; while fetching data in `+page.js` there can be a var like `loaded` etc that is returned with the values to the page which checks whether the data for the page is loaded or not.

Using that var we can make a condition in the `+page.svelte` for checking whether to load the page or the loading UI.

Thanks!

### Importance

would make my life easier

**Comment by rmunn** [comment] 2023-09-29 02:18
It sounds like you want https://kit.svelte.dev/docs/load#streaming-with-promises, which allows you to render the page before all the `load` data is available, then use `{#await}` blocks on the page to show a loading indicator until the rest of the data arrives. See the example in the docs.

**Comment by AxewBoTX** [comment] 2023-09-29 04:22
> It sounds like you want https://kit.svelte.dev/docs/load#streaming-with-promises, which allows you to render the page before all the `load` data is available, then use `{#await}` blocks on the page to show a loading indicator until the rest of the data arrives. See the example in the docs.

thanks alot. It kinda solve most of the problem. Thanks!

**Comment by s3812497** [comment] 2023-09-29 06:36
closing as duplicate of https://github.com/sveltejs/kit/issues/7213 which was closed by https://github.com/sveltejs/kit/pull/8901

**Closed by s3812497** 2023-09-29 06:36 UTC
