### ISSUE TITLE
Error line number is wrong in hooks.server.js

### ISSUE THREAD

**Issue by lzdetourer** [sveltejs/kit#10579] opened 2023-08-18 08:51 UTC
### Describe the bug

I need a function that runs regularly.
I called it from ```hooks.server.js```.

However, if an error occurs, the location is not correct.
In stackblitz reproduction, the location of the error is line 4, but it is output to line 6.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-wsaice?file=src%2Fhooks.server.js

hooks.server.js:
```
console.log('run: hooks.server.js');

setTimeout(() => {
	throw new Error();
}, 5000);

setTimeout(() => {
	console.log('error soon');
}, 4000);
```

### Logs

```Shell
run: hooks.server.js
error soon
Error
    at Timeout.eval (/home/projects/sveltejs-kit-template-default-wsaice/src/hooks.server.js:6:8)
    at listOnTimeout (node:internal/timers:62:4448)
    at processTimers (node:internal/timers:62:5285)
    at <anonymous> (https://sveltejskittemplatedefaultwsai-dctb-401tc7qf.w-credentialless.staticblitz.com/blitz.ba0db7b1.js:334:285414)
    at <anonymous> (https://sveltejskittemplatedefaultwsai-dctb-401tc7qf.w-credentialless.staticblitz.com/blitz.ba0db7b1.js:334:285713)
```

### System Info

```Shell
Reproduced in the stackblitz environment.

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    svelte: ^4.0.5 => 4.2.0
```

### Severity

annoyance

**Comment by ghostdevv** [comment] 2023-08-18 18:43
is this a duplicate of #10579 ?

**Comment by lzdetourer** [comment] 2023-08-19 03:00
> 

It is the same URL.

**Comment by PixelPete36** [comment] 2023-09-07 20:13
You by chance ever figure this out?
I just started using stackblitz and it seems like whenever it catches and error, and then throws it in the console, the line number is wrong... I had one that said the error was on line 117, when in fact it was on line 160.

**Comment by lzdetourer** [comment] 2023-09-19 00:23
> You by chance ever figure this out? I just started using stackblitz and it seems like whenever it catches and error, and then throws it in the console, the line number is wrong... I had one that said the error was on line 117, when in fact it was on line 160.
I am still suffering from this.

**Comment by lzdetourer** [comment] 2023-09-19 00:24
> You by chance ever figure this out? I just started using stackblitz and it seems like whenever it catches and error, and then throws it in the console, the line number is wrong... I had one that said the error was on line 117, when in fact it was on line 160.

I am still suffering from this.

**Comment by s3812497** [comment] 2023-09-23 18:15
closed as duplicate of https://github.com/sveltejs/kit/issues/10138

**Closed by s3812497** 2023-09-23 18:15 UTC
