### ISSUE TITLE
throw redirect(303, '/route') does not redirect & shows 500 page @ 1.8.7 & 1.8.6 in prod (not local)

### ISSUE THREAD

**Issue by sense-then-love** [sveltejs/kit#9240] opened 2023-02-28 08:01 UTC
### Describe the bug

- Only broken in prod (aka post build) but not locally
- throws a 500 error & does not redirect
- downgraded to 1.8.5 & redirects work in prod

### Reproduction

"@sveltejs/kit": "^1.8.7", 
"@sveltejs/adapter-cloudflare-workers": "^1.0.6",
+page.server.ts > throw redirect(303, '/route')
build
500 page

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 204.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: ^1.0.6 => 1.0.6 
    @sveltejs/kit: ^1.8.7 => 1.8.7 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.1.4 => 4.1.4
```

### Severity

blocking an upgrade

**Comment by thenbe** [comment] 2023-02-28 08:41
Related #9234

**Comment by dummdidumm** [comment] 2023-02-28 08:42
Please provide a proper minimum reproducible

**Comment by dummdidumm** [comment] 2023-02-28 10:06
Closing as duplicate of #9234

**Closed by dummdidumm** 2023-02-28 10:06 UTC
Labels: awaiting submitter
