### ISSUE TITLE
Scroll region to utilize in page navigation to persist scroll position of a div element

### ISSUE THREAD

**Issue by ravinila** [sveltejs/kit#11522] opened 2024-01-05 14:15 UTC
### Describe the problem

While redirecting to the previous page, the default page scrollTo takes care of persisting the scroll position of that page and the scrolling is happening on the `window` object. but in my case, the entire page is inside a div and that div has overflow-y auto. that means the window scrolling will not work for me to persist the page scroll position. 

### Describe the proposed solution

It would be better if we had a scroll-region option where we could set the div element to scroll on-page navigation. 
I'm not sure if this is implemented currently in Svelte-kit, but in InertiaJs it's implemented where it uses Svelte. 
REF: https://inertiajs.com/scroll-management

### Importance

i cannot use SvelteKit without it

**Comment by eltigerchino** [comment] 2024-01-05 16:00
See https://github.com/sveltejs/kit/pull/8723#issuecomment-1423522635 for a workaround. Closing this as a duplicate of https://github.com/sveltejs/kit/issues/2733

**Closed by eltigerchino** 2024-01-05 16:00 UTC
