### ISSUE TITLE
Invalidate does not re-run load function if page is visited directly

### ISSUE THREAD

**Issue by kjell0w** [sveltejs/kit#5260] opened 2022-06-24 13:01 UTC
### Describe the bug

When visiting a page containing a `load` function directly, for example by entering the route manually or refreshing the page, `invalidate` does not work as expected on this page. The `load` function is not executed again. However if you navigate from a different page to the page with the `load` function via a `<a>` tag, it works correctly.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-4trm7x?file=devices.json

I created 2 API endpoints `routes/devices/[userId].ts` and `routes/devices/[id]/delete.ts` to retrieve and delete devices. The data comes from `devices.json` located in the root directory. I also created the page `routes/user/[id]/devices.svelte`. This page contains a `load` function that retrieves the data from `routes/devices/[userId].ts`. I created a component in `$lib/DeviceItem` that contains a function `deleteDevice`. It calls the endpoint `routes/devices/[id]/delete.ts` and on success also `await invalidate($page.url.pathname)`.

If you navigate from the `Home` menu item to `User Devices` and delete a device, `invalidate` works as expected and the `load` function is called again. Data is being updated and reflected in the UI. However, if you now reload the page and then delete a device, the `load` function is not executed. The same happens if you open `User Devices` in a new tab. If you then navigate once to e.g. `Home` and then back again, `invalidate` works correctly again.

### System Info

```shell
System:
   OS: Linux 5.17 Artix Linux
   CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
   Memory: 365.92 MB / 7.64 GB
   Container: Yes
   Shell: 5.9 - /bin/zsh
 Binaries:
   Node: 18.2.0 - /usr/bin/node
   Yarn: 1.22.19 - /usr/bin/yarn
   npm: 8.5.5 - /usr/bin/npm
 Browsers:
   Brave Browser: 101.1.38.119
   Firefox: 100.0.1
 npmPackages:
   @sveltejs/adapter-auto: next => 1.0.0-next.33
   @sveltejs/adapter-node: ^1.0.0-next.68 => 1.0.0-next.73
   @sveltejs/adapter-vercel: ^1.0.0-next.51 => 1.0.0-next.51
   @sveltejs/kit: 1.0.0-next.354 => 1.0.0-next.354
   svelte: ^3.44.0 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by kjell0w** [comment] 2022-06-27 10:53
If you need more information on this, please let me know

**Comment by gtm-nayan** [comment] 2022-06-28 02:57
Thanks. There was a flaw in your example that might have uncovered a different unintended behavior. You should be invalidating the resource that you fetched in the load function, so instead of `invalidate("/devices")` it should be `invalidate("/api/devices")`. Seems to work as expected after the change.

Your repro partially working with `invalidate("/devices")` feels like some implementation detail leaking through so going to keep this open for further investigation.

**Comment by bdanoit** [comment] 2022-07-04 05:05
> Thank you. In my personal case, the `load` function does not fetch data from a SvelteKit endpoint, but from Supabase. So in this case, according to the documentation, I would have to `invalidate` the page, right? This is the reason why I did it this way in my example

You can add a dependency to the load function
`export const load = ({ fetch }) => { return {
  dependencies: ['/devices']
}
}`
Then invalidate it
`invalidate('/devices')`

Or call the external API using the fetch provided by load
`export const load = ({ fetch }) => { fetch('/api/devices') }`
And invalidate the that specific uri
`invalidate('/api/devices')`

**Comment by Rich-Harris** [comment] 2022-09-20 20:47
I updated the repro to use the latest version of SvelteKit and everything is working correctly, so I'll close this

**Closed by Rich-Harris** 2022-09-20 20:47 UTC
Labels: load / layout
