### ISSUE TITLE
Stores get reset on page change/reloads starting on kit v.1.0.0-next.398

### ISSUE THREAD

**Issue by Layendan** [sveltejs/kit#6166] opened 2022-08-22 17:49 UTC
### Describe the bug

When building a sveltekit app using the static adapter plugin, Tauri, and sveltekit version next.398+, navigating between pages triggers a full page reload, resetting stores in the app, and rerendering the whole page.

### Reproduction

Sorry for linking the whole project, but I have no idea where the point of failure is.

1. Clone or Fork - https://github.com/Layendan/NineAnimator-Tauri
2. Have Rust, Node, and Yarn installed
3. Run `yarn build` to build the application
4. Open the app and go to the *settings* tab on the top right
5. Scroll down until the theme selection and choose `dark` or `light` (whichever one you are not currently using)
6. Navigate back to any other tab using <kbd>Cmd</kbd> / <kbd>Alt</kbd> + <kbd>Left</kbd> or by clicking another tab in the navigation bar
7. The theme, which is saved in a store, should be reset to the default theme.

Using `svelte dev` instead of `svelte build` will not reciprocate this problem and will render pages correctly.

### Logs

```shell
No logs are created
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 473.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: 1.0.0-next.428 => 1.0.0-next.428 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9 


Tauri Info:
Environment
  › OS: Mac OS 12.5.0 X64
  › Node.js: 18.0.0
  › npm: 8.6.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: asset 'https://asset.localhost';
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ Misc
  ├─ target
  ├─ node_modules
  ├─ static
  ├─ .github
  ├─ src-tauri
  ├─ .svelte-kit
  ├─ build
  ├─ .git
  └─ src
```

### Severity

serious, but I can work around it

### Additional Information

I can currently work around this issue using LocalStorage/SessionStorage; however, I would much rather not have to use those for a smoother user experience and fewer system calls.

I have also talked about this in discord and am willing to continue with it over there: [Discord Thread](https://ptb.discord.com/channels/457912077277855764/1005630446702436452)

**Comment by Layendan** [comment] 2022-08-26 00:32
I created a new repository using the svelte quick start.
I then changed the counter on the main page to use a store.
Then I copy pasted my settings files and tested them (works as intended, the store does not get reset)
Then I copy pasted my tauri files and tested using `npm run svelte:build && npm run preview` (works as intended, the store does not get reset)
Then I tested with `npm run build` which calls `npm run tauri build` which in turn calls `npm run vite build` after building I tried it and it gets reset just like my app.

I know that this is a sveltekit issue since it did not appear in next.397- but did appear in next 398+ and no new tauri updates were released within that time frame.

If you wish to test it, I have published the repository to test here: https://github.com/Layendan/svelte-tauri-error-example

**Comment by Conduitry** [comment] 2022-08-26 00:52
Do you have access to some sort of browser console in the Tauri app? I'm guessing the full page reload is caused by a JS error that prevents the client-side router from starting, and I'm guessing the JS error is caused by a new JS feature that's not supported in whatever browser Tauri is using.

**Comment by Layendan** [comment] 2022-08-26 15:56
My bad, I just pushed a change to [this](https://github.com/Layendan/svelte-tauri-error-example) repo which should be able to have dev tools open on the build version. Right-click a part of the app and then choose the inspect element option to open the dev tools.
Tauri should be using my version of safari: 15.6.1 at the moment; however, running the preview in the browser does not reciprocate the same error.

**Comment by Kalsyc** [comment] 2022-09-26 15:42
This problem is also breaking my electron app for me... :(

**Comment by dummdidumm** [comment] 2022-09-28 15:53
Closing as duplicate of #6496

**Closed by dummdidumm** 2022-09-28 15:53 UTC
