### ISSUE TITLE
__data.js opt-out / SSR always no matter how visited on some routes

### ISSUE THREAD

**Issue by TranscendentalRide** [sveltejs/kit#6574] opened 2022-09-05 01:34 UTC
### Describe the problem

There is a need to only render some routes as SSR. The workaround started breaking

https://github.com/sveltejs/kit/issues/6573

What we really want is a feature to always render a page SSR and never call __data (even block calls to __data).

### Describe the proposed solution

`export let alwaysSSR = true;` 

or

`export let clientRouting = false;`

in `+page.server.js`

### Alternatives considered

Workaround in link above, breaking in latest version. Blocker otherwise.

### Importance

i cannot use SvelteKit without it

### Additional Information

This is a different request than no JS on the page, ie, `export let csr = false`. In other words we want Client Side Rendering but not Client Side Routing for some routes.

Food for thought: if a particular route needs `data-sveltekit-reload` when going TO the route, then it should be respected if going back to that same link via back-navigation.

1. Click link with `reload`
2. Click to a different page
3. Go back (should still be "reload" and not make a call to `__data.js`!)

**Comment by Rich-Harris** [comment] 2022-09-05 11:52
Duplicate of #5699

**Closed by Rich-Harris** 2022-09-05 11:52 UTC
