### ISSUE TITLE
Ability to avoid using JS import in production for non-recent browsers ("Legacy" support for ES2015)

### ISSUE THREAD

**Issue by Tal500** [sveltejs/kit#2458] opened 2021-09-19 14:42 UTC
### Describe the problem

Following [my question in StackOverflow](https://stackoverflow.com/questions/69070188/why-sveltekit-basic-example-build-output-use-the-very-modern-import-keyword), I'm asking for support for ES2015 target, i.e. that the production output for the client will be able to be with no import keywords nor JavaScript modules, only bundled JS.

### Describe the proposed solution

Vite compiler does support ES2015, so I think Svelte should be able to support it as well with no too much effort(again, only for production).

Probably Svelte output code should be modified to support no JavaScript modules in production, but I don't know for how much.

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment] 2021-09-19 14:46
Duplicate of #12 . This isn't supported yet, but is on the roadmap post-1.0

**Closed by dummdidumm** 2021-09-19 14:46 UTC
