### ISSUE TITLE
Components are rendered twice within sveltekit.head

### ISSUE THREAD

**Issue by aubergene** [sveltejs/kit#6216] opened 2022-08-24 12:58 UTC
### Describe the bug

I have a component `Meta.svelte` which is rendered within `+layout.svelte`. On page load (and SSR) the tags are rendered correctly, but on JS page navigation the tags are duplicated (which in Chrome means the second `<title>` is ignored)

```+layout.svelte
<svelte:head>
	<Meta />
</svelte:head>
```

```Meta.svelte
<script>
	import { page } from '$app/stores';

	let title;
	let description;

	$: {
		$page;
		title = Math.random();
		description = Math.random();
	}
</script>

<title>{title}</title>
<meta name="description" content={description} />

```

### Reproduction

Made a demo app

https://github.com/aubergene/svelte-kit-head-bug

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 126.55 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 92.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65
    @sveltejs/kit: next => 1.0.0-next.431
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.4 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by aubergene** [comment] 2022-08-24 13:04
Sorry, further investigation, it might be this https://github.com/sveltejs/svelte/pull/7745 will test

**Comment by aubergene** [comment] 2022-08-24 15:14
Also seems related to https://github.com/sveltejs/svelte/issues/6463

**Comment by aubergene** [comment] 2022-08-24 15:16
In my trivial test repo, it appends on hydrate and then continues to update the second set of DOM elements. However in the real big hairy project I'm working on it appends the entire component output each time, but I haven't yet worked out how to reproduce that behaviour

**Comment by benmccann** [comment] 2022-08-26 03:05
I'm going to close this as a duplicate of the bugs in the Svelte repo

**Closed by benmccann** 2022-08-26 03:05 UTC
