### ISSUE TITLE
Typed API Routes

### ISSUE THREAD

**Issue by bobbymannino** [sveltejs/kit#12645] opened 2024-09-03 20:56 UTC
### Describe the problem

Trpc sucks, it takes way too much setup and SvelteKit is very clever and types a lot of things already. Parameters are typed already for pages and I don’t think it is too far fetched an idea to think api routes could be typed too, my self - I do not have the knowledge to create such a thing. I might just be dreaming and this is impossible but typed APIs out of the box would be an awesome headline feature of sveltekit

### Describe the proposed solution

The syntax to use it would look something like this;

```ts
// /src/routes/api/test/+server.ts
import type { RequestHandler } from './$types';
import { json } from '@sveltejs/kit';

export const GET: RequestHandler = async ({ request }) => {
 //Logic

  if (Math.random() > 0.5) return json({ message: "success" });
  return json({ message: 'failed' }, { status: 500 });
}
```

```svelte
<!-- /src/routes/+page.svelte -->
<script>
  import { api } from '@sveltejs/kit/api';

  async function get() {
    const res = await api("/api/test").get();
    // res = { status: 500, body: { message: "failed" } } | { status: 200, body: { message: "success" } }


    // if there was a body or headers they can go in the method function
    // const res = await api("/api/test").get({ body: {} }); 
  }
</script>

<button onclick={get}>Get</button>
```

### Importance

would make my life easier

**Comment by eltigerchino** [comment] 2024-09-04 18:39
duplicate of https://github.com/sveltejs/kit/issues/647

**Closed by eltigerchino** 2024-09-04 18:39 UTC
