### ISSUE TITLE
`process.env` in markup gets transformed into `{}`

### ISSUE THREAD

**Issue by TGlide** [sveltejs/kit#11112] opened 2023-11-23 12:03 UTC
### Describe the bug

When writing `process.env` into a Svelte component's markup, it gets hydrated into `{}`. This does not happen in the build step, but rather, only on hydration.

### Reproduction

https://github.com/TorstenDittmann/svelte-kit-repro-process-env/blob/main/src/routes/about/%2Bpage.svelte

Also happens in https://github.com/appwrite/website

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 473.28 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - ~/.nvm/versions/node/v20.7.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.7.0/bin/npm
    pnpm: 8.10.2 - ~/Library/pnpm/pnpm
    bun: 1.0.13 - ~/.bun/bin/bun
    Watchman: 2023.05.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 16.5
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1
    @sveltejs/kit: ^1.27.4 => 1.27.6
    svelte: ^4.2.7 => 4.2.7
    vite: ^4.4.2 => 4.5.0
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment] 2023-11-23 14:20
`process.env` doesn't exist on the client so Vite replaces it with `{}` there. It must just use a regex rather than AST traversal. You could probably work around it by escaping a character.

I'm going to close this since it's not a bug in kit itself. Feel free to refile in the Vite repo.

**Closed by benmccann** 2023-11-23 14:20 UTC
Labels: vite
