### ISSUE TITLE
Node adapter runs server-side code when building

### ISSUE THREAD

**Issue by tcc-sejohnson** [sveltejs/kit#1372] opened 2021-05-07 00:26 UTC
**Describe the bug**
When running `yarn build` with the Node adapter, the `handle` hook runs. It will even go so far as to call HTTP and database methods successfully (I've had an auth flow triggered during `yarn build`).

**To Reproduce**
1. [Clone my repo.](https://github.com/tcc-sejohnson/svelte-node-build-error)
2. `yarn`
3. `yarn build`
4. Check out your console for a nice banner that shouldn't be there.

**Expected behavior**
Creating the bundle should _not_ run `handle`.

**Severity**
Fair, but not critical.

**Comment by tcc-sejohnson** [comment] 2021-05-07 00:44
I found #1188, which seems to be the same or a related issue.

**Comment by babichjacob** [comment] 2021-05-07 01:44
Closing as duplicate of https://github.com/sveltejs/kit/issues/933 as mentioned on Discord and of #1188 as mentioned above. This is partially documented in https://kit.svelte.dev/docs#modules-$app-env but it would probably be a good idea to further explain this in there or an FAQ -- again, keep that discussion in #933.

**Closed by babichjacob** 2021-05-07 01:44 UTC
