### ISSUE TITLE
Hot Module replacement not working for newly created files in WINDOWS

### ISSUE THREAD

**Issue by smc181002** [sveltejs/kit#1651] opened 2021-06-08 11:07 UTC
**Describe the bug**
When I create a new file in the routes directory of the project of sveltekit while the hot reload server is running, the hot reloading is not working for that new route created and I had to reload the browser each time for the effects to take place

**Logs**
![image](https://user-images.githubusercontent.com/53662575/121172233-1ab91c80-c875-11eb-8889-f4a43f05761a.png)
![image](https://user-images.githubusercontent.com/53662575/121172300-2ad0fc00-c875-11eb-9d82-0aee7a663da8.png)

**To Reproduce**
node version - v14.17.0
npm version - 6.14.13
yarn version - 1.22.5
NOTE: THIS PROBLEM IS ONLY FOR WINDOWS AND I TRIED FOR WSL AND IT IS WORKING FINE
According to the docs I have executed the commands below
```sh
npm init svelte@next my-app
cd my-app
yarn install
yarn run dev
```
Now I went to my text editor and have created a new page called `newapp.svelte`
I have added content "**This is a new Application I created**" in h1 and then I navigated to the /newapp route to view the text
Now I appended new text and the new h1 content is "**This is a new Application I created and I want to have hot reload**" and I have saved the file but there is no change in the output

**Expected behavior**
The application should have been hot reloaded with h1 tag content as This is a new Application I created and I want to have hot reload

**Information about your SvelteKit Installation:**
These are the commands I have used for the installations
```sh
npm init svelte@next my-app
cd my-app
yarn install
yarn run dev
```

**Severity**
It is not an app crashing feature but fixing it to have a hot reload for newly created files will improve the developer experience by a lot

**Comment by gterras** [comment] 2021-06-09 07:52
Possibly related to https://github.com/sveltejs/kit/issues/871

**Comment by benmccann** [comment] 2021-07-22 15:53
Cl;osing as duplicate of #871

**Closed by benmccann** 2021-07-22 15:53 UTC
Labels: windows
