### ISSUE TITLE
Implement functionality to avoid fetching data twice in load function

### ISSUE THREAD

**Issue by synthXR** [sveltejs/kit#3892] opened 2022-02-13 20:34 UTC
### Describe the problem

The module=context "load function" fetches data twice, once on the server and once on the client. 

### Describe the proposed solution

Ideally, there should be an option to either cache data that was fetched server-side or to be able to configure the load function to not re-run on the client.

### Alternatives considered

https://github.com/sveltejs/kit/issues/3729
https://github.com/sveltejs/kit/issues/3731
https://stackoverflow.com/questions/69075449/cant-fetch-data-from-api-in-sveltekit
https://stackoverflow.com/questions/67921198/sveltekit-and-ssr
https://stackoverflow.com/questions/64055809/svelte-module-script-being-run-multiple-times

Seems like there are many issues around this. The main solution is to use the onMount function, however, it feels a bit hacky, if data could be loaded server-side, and passed to the client (without having the client to reload it).

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment] 2022-02-13 21:59
Duplicate of #3729 and #3731

**Closed by dummdidumm** 2022-02-13 21:59 UTC
