### ISSUE TITLE
Not found routes render root error page even when nested error pages exist.

### ISSUE THREAD

**Issue by brunobely** [sveltejs/kit#2866] opened 2021-11-22 20:02 UTC
### Describe the bug

An extension of #1393. From the [error pages docs](https://kit.svelte.dev/docs#layouts-error-pages):

> For example, if `src/routes/settings/notifications/index.svelte` failed to load, SvelteKit would render `src/routes/settings/notifications/__error.svelte` in the same layout, if it existed. If not, it would render `src/routes/settings/__error.svelte` in the parent layout, or `src/routes/__error.svelte` in the root layout.

In the example above, accessing localhost:3000/settings/notifications/unexisting_route would cause an error that _should_ be caught by `src/routes/settings/notifications/__error.svelte`, but is instead caught by `src/routes/__error.svelte`.

### Reproduction

Borrowed from #1393

1. Run:
```
degit  raprocks/error-repro error-repro && \
npm i && \
npm run dev -- --open
```

2. Navigate to `localhost:3000/level1/level2`, notice level 2 error page handles the 404 correctly.
3. Navigate to `localhost:3000/level1/level2/somepage`, notice **root error page** handles the error.

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 389.28 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.197
    svelte: ^3.34.0 => 3.44.2
```

### Severity

serious, but I can work around it

### Additional Information

I'd like to be able to redirect users to the "home" of each route if they try and navigate to a page that doesn't exist. For example, `/settings/notifications/funnygifs` should redirect back to `/settings/notifications`. Maybe there's a way to do that without error pages, but doing so with error pages proves to be harder than expected (instead of a single redirect per `__error.svelte`, I'll have to do some URL string processing in the root-level `__error.svelte` and take it from there).

**Comment by rmunn** [comment] 2021-11-23 07:59
Tracing through the Svelte-Kit code, I found that the [`_get_navigation_result`](https://github.com/sveltejs/kit/blob/1b021b528da0e0d0668b8bd20e476a83d96ccc37/packages/kit/src/runtime/client/renderer.js#L382) function is called with a `routes` array that's non-empty if the route matches, but if the route doesn't match any page or endpoint then `_get_navigation_result` is called with an empty routes array. The result is that it doesn't know any of the partial route matches (like `level1` followed by `level2`) and so it only has the fallback (root) error components to use.

Tracing it further back, I found that the root cause is in the [`parse` function](https://github.com/sveltejs/kit/blob/1b021b528da0e0d0668b8bd20e476a83d96ccc37/packages/kit/src/runtime/client/router.js#L184) of `router.js`, which tests each route of the app manifest to see if that route's regex matches the URL. Since `/level1/level2/nonexistent` doesn't match any routes in the manifest, `parse` returns an empty array.

So to make 404s return errors based on the closest error layout, `parse` would need to be able to match partial routes. Which is a little beyond my ability to code a PR for.

**Comment by brunobely** [comment] 2021-11-23 17:58
Thanks for doing some investigative work, that will give me the opportunity to dip my toes into the codebase without being overwhelmed by the amount of things to look at!

For anyone that wonders, I'm currently working around it by manually redirecting for each route I want redirection to happen from in the root error page, which isn't ideal but works well enough as long as I don't use dynamic routes which may clash and cause some unexpected behavior. Something like (in `src/routes/__error.svelte`):

```js
export function load({ error }) {
  if (error.message.includes('/level1/level2'))
    return {status: 302, redirect: '/level1/level2'};
  // handle other routes...
  return {status: 302, redirect: '/'};
}
```

**Comment by baseballyama** [comment] 2021-11-24 13:10
Is this related to https://github.com/sveltejs/kit/issues/2454 ?

**Comment by gyurielf** [comment] 2021-11-25 14:45
> Is this related to #2454 ?

Yep, seems to.

**Comment by Rich-Harris** [comment] 2022-04-05 02:01
Closing — this behaviour is intentional, per the explanation in https://github.com/sveltejs/kit/issues/2454#issuecomment-1004051345 (which also details how to get the behaviour you want)

**Closed by Rich-Harris** 2022-04-05 02:01 UTC
Labels: enhancement, error handling, router, p2-nice-to-have

**Comment by mrkishi** [comment] 2022-04-05 02:40
@Rich-Harris that trick doesn't work anymore without `fallthrough` though, right?

**Comment by mrkishi** [comment] 2022-04-05 15:49
Interesting, I assumed a 404 from a `[param]` would lead to the root error, but the intentional throw short-circuits it into the nested error page... Clever!
