### ISSUE TITLE
export const prerender = true not generating index.html

### ISSUE THREAD

**Issue by digidub** [sveltejs/kit#1866] opened 2021-07-09 12:42 UTC
I'm encountering an issue whereby no `index.html` file is being output to the `build` dir when I run `npm run build`. My main `/src/routes/index.svelte` contains `export const prerender = true` and my svelte.config.js file appears to contain the correct prerender settings. 

Here is a link to my repo: 

https://github.com/digidub/portfolio-site

Thanks

**Comment by ignatiusmb** [comment] 2021-07-09 13:56
Please make a small repo and not your entire site to pinpoint the issue. I'm guessing [this settings](https://github.com/digidub/portfolio-site/blob/5863d3a0297420bfaa0a0b2628536a7893a5a356/svelte.config.js#L7-L12) might be the cause, if not try to reproduce it with the skeleton template and all the default settings.

**Comment by johnnysprinkles** [comment] 2021-07-10 18:08
The `prerender = true` needs to go in a separate `<script context="module">` script block.

**Comment by dummdidumm** [comment] 2021-07-10 18:10
Thanks @johnnysprinkles for having a look. Closing.

**Closed by dummdidumm** 2021-07-10 18:10 UTC
