### ISSUE TITLE
Cookies not loading in the load/PageServerLoad from a redirect from an external site.

### ISSUE THREAD

**Issue by tvarwig** [sveltejs/kit#10318] opened 2023-07-04 13:56 UTC
### Describe the bug

I am writing a password reset page. The reset page where the end user enters their email saves a cookie. The customer gets an email with a link to the page to reset their password. In Gmail I will click on the button and it goes to the page. It shows the error page which is thrown by not having the cookie present. If I refresh the page while on the page the cookie loads without issue. 

### Reproduction

```typescript
// +page.server.ts
export const load = (async ({ params, url, request, getClientAddress, cookies }) => {
  const passwordString = url.searchParams.get('p')
  const key = url.searchParams.get('k')

  // verify cookie
  if (!cookies.get('p')) {
    console.log(cookies.getAll()) // shows [] on redirect from email client. when page is refreshed no issue
    throw error(400, 'Reset of Password Not Valid, Error Code 1')
  }
...
}) satisfies PageServerLoad
```

### Logs

```Shell
Console Log From Browser: GET http://localhost:5173/auth/reset-password?p=codegoeshere&k=codegoeshere

No Server Side Logs
```

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 717.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.21.0 
    svelte: ^4.0.0 => 4.0.1 
    vite: ^4.3.6 => 4.3.9
```

### Severity

annoyance

**Comment by dummdidumm** [comment] 2023-07-04 14:04
Please provide a proper minimum reproducible in the form of a link to either Stackblitz or a Github repo.

**Comment by pawelblaszczyk5** [comment] 2023-07-04 23:17
I guess it's because of SameSite Strict setting 😃

**Comment by tcc-sejohnson** [comment] 2023-07-09 02:07
Closing this as it does not have a complete reproduction and has been dead for days. If you're still having this issue, please open a new one with a full reproduction.

**Comment by pawelblaszczyk5** [comment] 2023-08-18 14:52
> i'm having the same issue trying to implement an oAuth calback, cookies will not be read until i do a page refresh

What is your cookie's `SameSite` setting?

**Closed** 2023-12-21 12:17 UTC
Labels: awaiting submitter
