### ISSUE TITLE
`sveltekit:prefetch` causes JS to be downloaded 2x, in some cases.

### ISSUE THREAD

**Issue by websocket98765** [sveltejs/kit#764] opened 2021-03-30 01:29 UTC
**Describe the bug**

Using `sveltekit:prefetch` causes js to be downloaded 2x, in some cases.

CSS is only downloaded 1x correctly.

**To Reproduce**

1. Create a link and add `sveltekit:prefetch` to it. 
2. Run `npm run build` and `npm run start`. (The issue does _not_ occur when using `npm run dev`. )
3. Open dev console network tab, clear it. Hover over your link from Step 1.
4. JS will be downloaded 2x. CSS will correctly be fetched only 1x.
(Exception: There's a file called `vendor-<hash>.js` which is correctly downloaded only 1x.

Example 1:
![1](https://user-images.githubusercontent.com/41795874/112920032-28fcf680-90d6-11eb-9d84-d0513b9bc492.png)

Example 2:
![2](https://user-images.githubusercontent.com/41795874/112920036-29958d00-90d6-11eb-9e54-e0ea4dbd6c9c.png)

**Information about your SvelteKit Installation:**

```
System:
    OS: macOS 11.2.2
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
 npmPackages:
    @sveltejs/kit: next => 1.0.0-next.64 
    svelte: ^3.35.0 => 3.35.0 
 Browsers:
    Chrome 89.0.4389.90
    Firefox: 86.0.1
```

Adapter: Node

**Severity**

Low

**Comment by websocket98765** [comment] 2021-03-30 01:37
Could this be a non-issue, just a poor display in FireFox's Network tab?

Because in Chrome, the HTTP requests happen only once, and it shows that one is initiated via the service worker.

![3](https://user-images.githubusercontent.com/41795874/112920434-f1427e80-90d6-11eb-94f3-1fd3116a0df6.png)

**Comment by Rich-Harris** [comment] 2021-04-02 21:53
There's no service worker in dev, which is why you're only seeing 1 request there. It looks like the double request is indeed caused by the service worker (in combination with a confusing Firefox UI) so I'll close this — thanks

**Closed by Rich-Harris** 2021-04-02 21:53 UTC
Labels: bug
