### ISSUE TITLE
500: Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by jakobsturm** [sveltejs/kit#3308] opened 2022-01-12 15:26 UTC
### Describe the bug

I am encountering some issues when deploying my project to vercel using the vercel-adapter. The project builds but then the deployed site I receive `500 Failed to fetch dynamically imported module: https://xxx.vercel.app/_app/undefined`

The vercel build is triggered by a new Gitlab commit.

Does someone have an idea what could cause this issue? The weird thing is that it works with `npm run build` but not on the deployed vercel site...

### Reproduction

This should be reproducable by using the same sveltekit + adapter versions

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 13.49 GB / 31.91 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.10
    @sveltejs/adapter-vercel: next => 1.0.0-next.36
    @sveltejs/kit: ^1.0.0-next.225 => 1.0.0-next.225
    svelte: ^3.46.0 => 3.46.0
```

### Severity

blocking all usage of SvelteKit

**Comment by mawoka-myblock** [comment] 2022-01-12 20:29
Having the same issue with cloudflare adapter, but just on reload.

**Comment by benmccann** [comment] 2022-01-12 21:26
> This should be reproducable by using the same sveltekit + adapter versions

I don't think this happens with all projects or we'd probably be getting a whole lot more bug reports. Can you make it happen with a brand new project? If not, can you provide a project that reproduces it?

**Comment by jakobsturm** [comment] 2022-01-13 08:29
Thanks, @benmccann! Yes, you are probably right - sorry for my assumption. 
I am trying to work out how to reproduce it and will update you further.

Additionally I have noticed, the first error I receive when loading the page is: `500: The "path" argument must be of type string or an instance of URL` and after that reload it is the error mentioned above.

But of course I understand that it is hard for you to reproduce it like that. I was just hoping that someone has already experienced the same issue and has a solution. I will keep you updated. Thank you!

**Comment by mawoka-myblock** [comment] 2022-01-13 14:45
Here is the repo: https://github.com/mawoka-myblock/svelte-cf-error
And I deployed it for testing reasons here (ofc with cf-pages): https://svelte-cf-error.pages.dev/blog/test
If you visit the link directly, you'll get a 500 document undefined (Any tips here are really appreciated), but if you go to https://svelte-cf-error.pages.dev/blog and then open the blog-post, it works until you reload. The first reload will produce a 500 document not defined error and the 2nd reload the error this issue is about.

**Comment by netaisllc** [comment] 2022-01-13 20:05
Just for a small bit of added context, we are deployed to our own VMs on Digital Ocean and see this error in the logs approximately 1-2 per week.  Still trying to gather enough of the situation to share. :(

**Comment by mawoka-myblock** [comment] 2022-01-14 06:18
@benmccann It also happens on/with the clodflare-pages adapter

**Comment by mawoka-myblock** [comment] 2022-01-15 16:06
Vercel works for me fine, but Cloudflare-Pages doesn't

**Comment by nikosgpet** [comment] 2022-01-20 09:09
Just hit the same error with Cloudflare pages. If you visit the link directly, you get a `500: Failed to fetch dynamically imported module: https://fef7dft46.*********.pages.dev/_app/undefined`. It only happens with some pages though, not all.

**Comment by nikosgpet** [comment] 2022-01-20 09:59
It turns out that in my case, it was because I was dynamically assigning a module to a component inside onMount.

**Comment by csell5** [comment] 2022-02-02 20:34
This is actually something we see daily and it's been driving me nuts because I can't seem to find the root cause. In one user session just a bit ago this happened. 

```
TypeError: Failed to fetch dynamically imported module: https://that.us/_app/pages/activities/__layout.svelte-f2da0de0.js

then

TypeError: Failed to fetch dynamically imported module: https://that.us/_app/pages/activities/create/__layout.svelte-64778a6f.js

then

TypeError: Failed to fetch dynamically imported module: https://that.us/_app/pages/activities/create/cfp.svelte-11144fe2.js

```

Which lead to the 500. I've long thought it was vercel just not rendering those files or an ad tracker but I would love to fix it. Any ideas on how to hunt down the why on this?

**Comment by mawoka-myblock** [comment] 2022-02-02 20:43
> This is actually something we see daily and it's been driving me nuts because I can't seem to find the root cause. In one user session just a bit ago this happened.
> 
> ```
> TypeError: Failed to fetch dynamically imported module: https://that.us/_app/pages/activities/__layout.svelte-f2da0de0.js
> 
> then
> 
> TypeError: Failed to fetch dynamically imported module: https://that.us/_app/pages/activities/create/__layout.svelte-64778a6f.js
> 
> then
> 
> TypeError: Failed to fetch dynamically imported module: https://that.us/_app/pages/activities/create/cfp.svelte-11144fe2.js
> ```
> 
> Which lead to the 500. I've long thought it was vercel just not rendering those files or an ad tracker but I would love to fix it. Any ideas on how to hunt down the why on this?

Change to another adapter! The problem may occur only with the vercel adapter, or just with the cloudflare adapter

**Comment by csell5** [comment] 2022-02-02 21:12
> Change to another adapter! The problem may occur only with the vercel adapter, or just with the cloudflare adapter

Well, I've used both the auto adapter and the vercel one. I'm not picking up and moving off of vercel, unless that's really the issue which means a huge infrastructure change. Now our vercel setup is behind cloudflare and set up the way they recommend.

**Comment by mawoka-myblock** [comment] 2022-02-02 21:24
> 

You can just deploy it as a test to cloudflare, shouldn't take long and if the issue is still there, it's probably in your code and if not, this issue is the right place!

**Comment by csell5** [comment] 2022-02-02 21:31
> You can just deploy it as a test to Cloudflare, shouldn't take long and if the issue is still there, it's probably in your code and if not, this issue is the right place!

I can't even consistently reproduce it, without being able to do that moving it doesn't make any sense. If I could repo or knew how to, I would know where to start looking. 

On top of that, it's never "just" a just and our site isn't small http://github.com/ThatConference/that.us

**Comment by nikosgpet** [comment] 2022-02-02 21:46
I think that this error might arise whenever you push a new update to the site, which causes a re-built of all modules. In the rebuilt, all files get a new name. If the user was already on the website and doesn't hit rephresh, navigating in the website will eventually try to load a module that is no longer there, causing an error.

**Comment by mawoka-myblock** [comment] 2022-02-02 21:49
> I think that this error might arise whenever you push a new update to the site, which causes a re-built of all modules. In the rebuilt, all files get a new name. If the user was already on the website and doesn't hit rephresh, navigating in the website will eventually try to load a module that is no longer there, causing an error.

Good point! I think we are having many different issues in this issue, which all lead to the sane error. For me, I fixed my website, by switching to vercel, away from cloudflare.

**Comment by benmccann** [comment] 2022-02-02 22:05
> I think that this error might arise whenever you push a new update to the site, which causes a re-built of all modules. In the rebuilt, all files get a new name. If the user was already on the website and doesn't hit rephresh, navigating in the website will eventually try to load a module that is no longer there, causing an error.

Yes, I think that's likely and could cause this error. That should be fixed by https://github.com/sveltejs/kit/pull/3412. Can folks report whether this issue is fixed by `1.0.0-next.254` or still occuring?

**Comment by netaisllc** [comment] 2022-02-03 02:01
> I think that this error might arise whenever you push a new update to the site, which causes a re-built of all modules. In the rebuilt, all files get a new name. If the user was already on the website and doesn't hit rephresh, navigating in the website will eventually try to load a module that is no longer there, causing an error.

That sounds plausible, but could be refuted by our experience. We see this error type ~ one a week and our sessions are incredibly short-lived, certainly much shorter than our deploy cycle. Also, we are using the `node` adaptor.

We will try to report findings once upgraded to `254`. Thanks!

**Comment by csell5** [comment] 2022-02-03 13:39
> Yes, I think that's likely and could cause this error. That should be fixed by #3412. Can folks report whether this issue is fixed by `1.0.0-next.254` or still occurring?

@benmccann looks like I am on 204

having said that I am working through updating 254. Just trying to make my way through some of the breaking changes. Hoping to get that out maybe this morning.

**Comment by ManuelDeLeon** [comment] 2022-02-03 19:16
@benmccann - I don't have the problem with the latest @sveltejs/kit (1.0.0-next.260) + @sveltejs/adapter-vercel (1.0.0-next.40). Don't get any errors and SSR works like it does locally.

**Comment by csell5** [comment] 2022-02-04 00:01
@benmccann and bumped to 260. Took me a bit longer to work through the breaking changes than I thought. We did see it a few times when testing, but things were in a crazy state of chaos. We will see what happens in the next 24.

just for reference for others that might be looking to see what changes we had to make - https://github.com/ThatConference/that.us/pull/1177

**Comment by mawoka-myblock** [comment] 2022-02-04 06:18
> > I think that this error might arise whenever you push a new update to the site, which causes a re-built of all modules. In the rebuilt, all files get a new name. If the user was already on the website and doesn't hit rephresh, navigating in the website will eventually try to load a module that is no longer there, causing an error.
> 
> Yes, I think that's likely and could cause this error. That should be fixed by #3412. Can folks report whether this issue is fixed by `1.0.0-next.254` or still occuring?

It didn't fix it for me...

**Comment by csell5** [comment] 2022-02-04 12:14
Unfortunately it happened again last night, and our night traffic is light. 

Only happened for one user and it appears to have happened a few times for them. 

We will see what happens today.

**Comment by nikosgpet** [comment] 2022-02-04 13:34
It may still happen for a few days, if users had left their tab open with a previous version of your app. Some users leave tabs open for days or weeks and this can sometimes be the case even for short lived pages such as forms or login pages.

A way to verify this sort of bugs, would be to include a variable containing the version of your app in your Sentry report.

**Comment by csell5** [comment] 2022-02-08 16:50
I'm sorry for the delay here, but I'm happy to report I haven't seen this error surface again. Over the past 72 hours, we've seen 8k page views and 47k requests.

@nikosgpet that was an excellent suggestion and one of which I will get added.

**Comment by benmccann** [comment] 2022-02-08 16:51
Thanks for the update! I think I'm going to consider this issue closed. If anyone's still running into it, please file an issue with steps to reproduce the error

**Closed by benmccann** 2022-02-08 16:51 UTC
Labels: pkg:adapter-vercel, p1-important, pkg:adapter-cloudflare

**Comment by jycouet** [comment] 2022-02-22 22:59
Sorry, that was not intentional to spam here.
I had an issue with that title.

It turns out that it was the usage of `pino-pretty` with vercel.
```json
{
  "adapter-vercel@next": "1.0.0-next.44",
  "@sveltejs/kit@next": "1.0.0-next.282"
}
```

After reading their doc, it's not recommended to use in production.
No problem then.

I put it here as it might help others.

**Comment by bitdom8** [comment] 2022-03-03 17:33
Hi got the latest sveltekit, got this error Failed to fetch dynamically imported module:

**Comment by RomanistHere** [comment] 2022-05-06 09:08
> Hi got the latest sveltekit, got this error Failed to fetch dynamically imported module:

Me too. After bump from 175 to 326 I got this error.

**Comment by lazharichir** [comment] 2022-06-08 13:49
For me, it was an adblocker blocking some resources (i.e., there was an "ads" somewhere in the URI).

**Comment by qk0106** [comment] 2022-09-19 04:01
Hey guys. 

I used to get this issue with ad blocker, and it was fixed with removing da extension. However it comes back now with latest chrome (Version 105.0.5195.125 (Official Build) (x86_64)) and without adblocker. 

Can someone confirm and tell us how to fix it? Appreciate it!

![image](https://user-images.githubusercontent.com/8155746/190947870-2893583f-554e-4b8c-9515-b6762d8760cf.png)

**Comment by magic-thomas** [comment] 2023-02-25 04:58
I found this thread after I got found solution, I guess. 

refer my case ( https://github.com/sveltejs/kit/discussions/9209 ) 

It could be related with connection limit in web servers .

**Comment by offeex** [comment] 2023-05-12 09:26
same issue. It occurs randomly in prod environment in Chrome-based browsers, and on few couple of quick "reload" presses in firefox
![image](https://github.com/sveltejs/kit/assets/64991049/c3457810-17d0-4f35-93bc-b89e9f5d444c)

**Comment by marius-jopen** [comment] 2023-06-27 10:35
> For me, it was an adblocker blocking some resources (i.e., there was an "ads" somewhere in the URI).

HOLY MOLY! That was it!

**Comment by vettloffah** [comment] 2023-07-13 20:06
For us, the issue was that we have the deployment hosted on vercel, and the proxy option turned on in our Cloudflare DNS, and Cloudflare wasn't aware when there was a new deployment. This was causing intermittent issues that resulted in errors described in this post.

This was really hard to narrow down, but once we turned off the proxy option in Cloudflare the issues immediately cleared up.

This Cloudflare issue is actually described right in the vercel docs here: https://vercel.com/guides/using-cloudflare-with-vercel

**Comment by Arro** [comment] 2023-08-09 17:08
> > For me, it was an adblocker blocking some resources (i.e., there was an "ads" somewhere in the URI).
> 
> HOLY MOLY! That was it!

For me, it was "metrics" in the filename.  Thank god I figured this out!

**Comment by cryptolit0** [comment] 2025-07-15 22:42
yeah so for me it started happening when i refactored dozens of imports to be dynamically loaded. 

turns out the users hadn't refreshed their tab in forever and the site code was trying to access old build files (with different hashes in the filename)
