### ISSUE TITLE
Support Vercel's includeFiles option in function config

### ISSUE THREAD

**Issue by acarl005** [sveltejs/kit#5999] opened 2022-08-17 20:39 UTC
### Describe the problem

My API route depends on a txt file in my repo, but that file isn't getting included in the build when I deploy to Vercel with `@sveltejs/adapter-vercel`. According to the [docs](https://vercel.com/docs/project-configuration#project/functions), there is a way to whitelist files in `vercel.json` to include in the build. However, my `vercel.json` seems to be ignored by SvelteKit. Here is my `vercel.json`.

```json
{
  "functions": {
    "render": {
      "includeFiles": [
        "./pg-server/func-allowlist.txt"
      ]
    }
  }
}
```

### Describe the proposed solution

Maybe a `includeFiles` prop can be passed into the adapter options in the `svelte.config.js`?

### Alternatives considered

Maybe there is a way to get Vite to just inline the contents of a txt file inside the JS bundle? I'm not sure if this is possible.

### Importance

i cannot use SvelteKit without it

### Additional Information

The files I want to include should not be publicly accessible, so they are not appropriate for placing in the `static` directory.

**Comment by Rich-Harris** [comment] 2022-08-17 22:24
> Maybe there is a way to get Vite to just inline the contents of a txt file inside the JS bundle?

This should work:

```js
import allow_list from './pg-server/func-allowlist.txt?raw';
```

There might well be some value in exposing `includeFiles`, though so far we've held off on the grounds that this would be better: https://github.com/sveltejs/kit/issues/4671 (`includeFiles` wouldn't work for edge functions, for example).

**Comment by acarl005** [comment] 2022-08-18 17:01
I was able to solve the issue using Vite's `import blah from './blah?raw'` and `import.meta.glob("foobar/*")`.

**Comment by robotpapier** [comment] 2023-03-02 11:21
Hi, Just wanted to share my solution here.

I was looking for a solution to include a attachment in the mail i'm sending with nodemailer.
works on local but not in vercel : it cannot find the file or directory

Using  `path.join(__dirname, '/static' + logoPath)` didn't work

And I couldn't make the solution above work.

But I found another solution : using vercel tmp folder to write import my files and write to this folder and then use the path to this folder. See https://vercel.com/guides/how-can-i-use-files-in-serverless-functions#using-temporary-storage

Here is my code for importing and writing a png
`import logo from '@src/assets/medias/mail/logo.png?raw'
fs.writeFile(`/tmp/logo.png`, logo, function (err) {
	if (err) throw err
})`

And options for the nodemailer sendMail function :
`const options= {
		from: MAIL_FROM,
		to: MAIL_TO,
		bcc: MAIL_BCC,
		subject: MAIL_SUBJECT,
		attachments: [
			{
				filename: 'logo.png',
				path: '/tmp/logo.png',
				cid: 'logo'
			}
		],
		html: emailHtml
	}`

**Comment by mpiorowski** [comment] 2023-03-28 06:10
@robotpapier You're solution was the only one that worked, thx :)

Tried eveyrhthing, with vercel config, trying to import / read, anything. Only specificly reading and writing to `tmp` helped.

**Comment by Bug-Reaper** [comment] 2023-08-14 11:27
After 5hrs and 13mins on this, I finally made it to this post. Though the rush of hope was nice while it lasted, neither of the above solutions worked for me. So instead, at around 6hrs in on my journey, I present the glorious fetch it from the public static endpoint solution :

```
export async function GET({ params, url }) {
  try {
    const satoshi = await fetch(`${url.origin}/fonts/Satoshi-Regular.ttf`)
      .then(res=>res.arrayBuffer());
    fs.writeFileSync("/tmp/satoshi.ttf",Buffer.from( new Uint8Array(satoshi) ));
    const cardOverlay = await fetch(`${url.origin}/images/share-card-templates/user-profile.png`)
      .then(res=>res.arrayBuffer())
```

A wide ecosystem of node-js libs rely on real files to be present. Look forward to see support for pass includeFiles up to vercel. (Even if it's incompatible w/edge or I have to include the assets in every cloud function or something). In the meantime, some type of warning on the router docs seems sensible.

---

Out of curiosity, what is `import blah from './blah?raw'` supposed to return? Comments made it sound like a buffer but instead I got links to the dynamic bundled assets still only avail through remote fetch. Would work if I just needed a link to shove into a div or something later, did not work for actual server-side file manipulation.

**Comment by homerjam** [comment] 2023-11-06 00:14
I have this issue because of MJML - internally it uses the filesystem for partials. Unfortunately I'm struggling to find a workaround. I thought (vite-plugin-static-copy)[https://github.com/sapphi-red/vite-plugin-static-copy] would save the day but it seems that using the documented `process.cwd()` trick on Vercel doesn't work as expected.

**Comment by eltigerchino** [comment] 2023-11-06 13:10
duplicate of https://github.com/sveltejs/kit/issues/10594

**Closed by eltigerchino** 2023-11-06 13:10 UTC
Labels: enhancement, pkg:adapter-vercel
