### ISSUE TITLE
Unable to navigate to non-root routes by links

### ISSUE THREAD

**Issue by PuruVJ** [sveltejs/kit#1359] opened 2021-05-06 17:29 UTC
**Describe the bug**
When navigating to a page that isn't `/`(e.g `/blog` and `/works`) using links, the page being rendered is the `$error` one. But you can navigate to `/` perfectly well.

Also, if this error shows up and you reload the page, the page renders fine, but then if you navigate to any non-`/` page and come back, its again `$error`

**Logs**
Screenshot 
![image](https://user-images.githubusercontent.com/47742487/117337297-d4aa1b00-aeba-11eb-9d33-550db5144ccc.png)

Text:
```txt
<$error> received an unexpected slot "default".
$error.svelte? [sm]:6 <$error> was created with unknown prop 'blogsList'
```

**To Reproduce**
Repro: https://github.com/PuruVJ/sveltekit-error-repro

Run `npm run dev`
Then visit `/` on localhost
Then click on the link.

You should see this

![image](https://user-images.githubusercontent.com/47742487/117339374-4a16eb00-aebd-11eb-9088-7ed119f2b8e9.png)

Reload: You'll see the page perfectly and the data will be logged to console. Go to Home by clicking on the link, then come back to `/blog` by clicking the link on home. Again the error will be there

**Expected behavior**
When I should navigate by links to any of these routes, the correct component should render and I should see the page, irrespective of which page I'm navigating from and how many times

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```txt
 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1000.34 MB / 7.86 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.100 => 1.0.0-next.100
    svelte: ^3.38.2 => 3.38.2
    vite: ^2.2.4 => 2.2.4

```

- Your browser - Brave

- Your adapter- @sveltejs/adapter-static
</details>

**Severity**
High severity. Unable to run Dev properly, plus it is breaking the prod build too(My assumption)

**Comment by benmccann** [comment] 2021-05-06 22:06
Hmm. This is weird and broken. The write up is a bit confusing, but clicking the link in the repro results in a 404 and then you refresh the page and get a 200. I have no explanation as to why that would happen

**Comment by PuruVJ** [comment] 2021-05-07 04:40
Yeah, I even tried it on WSL2 in case it ws a windows related problem but its still a problem

**Comment by pgalle** [comment] 2021-05-08 21:45
In `.svelte-kit\dev\runtime\internal\start.js:170` the regex fails.

Essentially we have this: `(new RegExp(/^\/blog\/?$/)).test('blog')` which returns `false`.
(new RegExp(/^\/blog\/?$/)).test('/blog') would return `true`

So might the solution be to prepend a slash the path?

**Comment by PuruVJ** [comment] 2021-06-09 18:08
is tthis fixed?

**Comment by ignatiusmb** [comment] 2021-06-10 15:46
It seems that passing only `/` to `paths.base` in the config without any path to follow is the problem. It could be fixed from kit's side, but it might be better to just make sure that the config is correct. Simply remove `base` property from `paths` in the config or just leave it as an empty string to fix it.

**Comment by PuruVJ** [comment] 2021-06-10 17:17
Holy crap it worked!! Thank you 🤗🤗🤗🤗

**Comment by PuruVJ** [comment] 2021-06-10 17:34
No it's not fixed. I dunno if it is related, but if you're on `/blog` page, and there's a link `/blog/:id` (:id is filled with a valid link), during `npm run build`, it will say it can't find `/blog/blog/:id`. But if I make it `/:id`, hoping that navigating from `/blog` will take us to the right place,, it says it can't find `/:id` page :(

Is this related to this, or should I open another issue?

**Comment by PuruVJ** [comment] 2021-06-10 17:35
Happening on build only, not dev. Dev is fine

**Comment by ignatiusmb** [comment] 2021-06-10 17:56
Seems unrelated, probably better to open a separate issue for it. Before you do that, it sounds like there's a rogue link somewhere in your code or content (I see your data is placed as static json files) that uses relative paths.

Make sure to start any links in anchor tags with leading slash `/`, and use the full path to point to the page. Making it as `/:id` is a step in the right direction, try adding blog between it (`/blog/:id`) and see if it fixes it. You can still use relative paths, but that usually leads to more confusion like this than benefits.

Also, we can keep this issue opened if anything related comes up again (hopefully none), or until #1666 is merged. If it does, try asking them on StackOverflow or in our [Discord chat room](https://svelte.dev/chat) first, might be more of a support/usage question rather than a bug.

**Comment by PuruVJ** [comment] 2021-06-10 18:16
I did that actually. I tried using `/blog/:id`, but that only works when this component is rendered on `/` path. When this component is used on `/blog` route, I use some logic to make the a href use it as `./:id`, because `/blog/:id` isn't working here. That gives the error that `/:id` couldn't be found 

Usage: 
![image](https://user-images.githubusercontent.com/47742487/121576376-f2344c80-ca45-11eb-8af7-a99ddb060d84.png)

Error for this `/blog` page case:
![image](https://user-images.githubusercontent.com/47742487/121576437-ff513b80-ca45-11eb-8102-b2cd9d304b0c.png)

If you can help pinpoint it, I'd be happy, otherwise will open another issue 😃

**Comment by PuruVJ** [comment] 2021-06-10 18:30
NVM  figured it out

**Closed** 2021-06-10 20:28 UTC
Labels: bug

**Comment by pranav-js** [comment] 2021-11-18 07:17
goto() is completely ignoring config.path.base in `svelte.config.js` (in my case it is not empty string - `/web/sdk`). 
instead of going to  `/web/sdk/myroute` it is going to `/myroute` and says 404 not found. Somebody help :/

**Comment by n1kk** [comment] 2022-01-09 15:16
I also have this issue, can't make relative links work, they all resolve to root path. I have `/blog` route and it has posts links inside and they resolve to root instead of relative blog path.
```html
<a href="post-1">  ->  Not found: /post-1
<a href="/post-1">  ->  Not found: /post-1
<a href="./post-1">  ->  Not found: /post-1
<a href="blog/post-1">  ->  works
```

How do I make relative links work?

Or is this behavior by design?

**Comment by benmccann** [comment] 2022-01-09 15:35
@n1kk that's how relative links in HTML work. It's nothing to do with SvelteKit

**Comment by n1kk** [comment] 2022-01-10 08:57
Oh, yeah, you're right, it's because of the absence of trailing slash. How foolish of me :D, sorry.
