### ISSUE TITLE
Invalid request body with node 21

### ISSUE THREAD

**Issue by RSWilli** [sveltejs/kit#11334] opened 2023-12-15 09:42 UTC
### Describe the bug

I get the following error shown in the browser after `npm run dev`:

```
Invalid request body
```

this seems to be related to https://github.com/sveltejs/kit/issues/5370

Downgrading sveltekit from 1.30.3 to 1.27.7 did not help. Downgrading nodejs to v20 helped.

### Reproduction

none yet, it works with the demo app in node 21

### System Info

```Shell
System:
    OS: Linux 6.1 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 21.72 GB / 31.21 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.4.0 - ~/.nvm/versions/node/v21.4.0/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.4.0/bin/npm
  Browsers:
    Chromium: 120.0.6099.71
    Firefox: 120.0.1
  npmPackages:
    @sveltejs/adapter-static: ^2.0.2 => 2.0.3 
    @sveltejs/kit: ^1.27.7 => 1.30.3 
    svelte: ^4.2.8 => 4.2.8 
    vite: ^4.5.1 => 4.5.1
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment] 2023-12-15 10:02
Uneven node versions are always somewhat of a roller coaster / unstable, might very well be a Node bug unrelated to SvelteKit

**Comment by jeroensmink98** [comment] 2023-12-15 11:05
Here I'm also receiving incompatiblty node issues

Running `pnpm i` gives me
```
❯ pnpm i
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "/@sveltejs/kit/2.0.0(@sveltejs/vite-plugin-svelte@3.0.1)(svelte@4.2.8)(vite@5.0.9)".

Expected version: >=18.13
Got: v18.1.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

But my node version is `v21.4.0` also tested with `v20.10.0` LTS

```
❯ nvm list
 v20.10.0
 v21.4.0

```

**Comment by SerbanTudor04** [comment] 2024-01-04 14:44
+1 for node v21.5.0
A workaround is to downgrade to node v20.10.0.
Also keep in mind that v21.x is an unstable version of NodeJS. That might be the issue.

**Comment by muhammad-zakir** [comment] 2024-01-05 10:43
I was having a similar issue, and the workaround for me was to set the `ORIGN` and `BODY_SIZE_LIMIT` environment variables when running the production server as stated in the documentation [here](https://kit.svelte.dev/docs/adapter-node#environment-variables).

**Comment by npmhieu** [comment] 2024-03-13 06:27
I get this error, too, I don't know how this can't be fixed ? this is a very very common and easy case.

**Comment by gbucar** [comment] 2024-05-06 14:12
I got this error when I changed ORIGIN to a different address but forgot to add https://

**Comment by faulander** [comment] 2024-10-08 11:24
i get this error with node18 or 20,
only after upgrading to svelte5.

What can i do to get my project back up?

**Comment by eltigerchino** [comment] 2024-10-16 07:32
I'll be closing this issue for now because of the lack of a minimal reproduction. I'll re-open the issue if someone can provide one.

**Closed by eltigerchino** 2024-10-16 07:32 UTC
Labels: awaiting submitter
