### ISSUE TITLE
adapter-node: Deleting old prerendered files during build process

### ISSUE THREAD

**Issue by jesseskinner** [sveltejs/kit#1378] opened 2021-05-07 14:38 UTC
**Describe the bug**
When a route is changed to no longer be prerendered, the old prerendered file remains in the build folder, leading to a challenging debugging process trying to understand why production wasn't showing my new changes, even though it worked fine in development.

**Logs**
N/A

**To Reproduce**
`export const prerender=true` in a route, build the project, change `true` to `false`, and build again. The static file remains in `build/prerendered/`.

**Expected behavior**
I'd expect the old prerendered file to disappear.

**Stacktraces**
N/A

**Severity**
Not a big deal, but annoying: it led to half an hour debugging process to understand why my changes weren't showing up in production.

I was able to workaround by deleting the build folder before running `npm run build` again.

**Additional context**
N/A

**Comment by benmccann** [comment] 2021-05-08 04:44
Related to (or possibly duplicate of) https://github.com/sveltejs/kit/issues/1044

**Comment by Conduitry** [comment] 2021-05-08 10:54
Even if supporting that Vite option isn't what we end up going with, I do think that #1044 can function as a place to have a conversation about this. Closing.

**Closed by Conduitry** 2021-05-08 10:54 UTC
