### ISSUE TITLE
Weird behavior between an old client and a new server

### ISSUE THREAD

**Issue by GauBen** [sveltejs/kit#10057] opened 2023-05-29 15:49 UTC
### Describe the bug

I'm observing weird interactions between a client and a newly deployed server instance.

Here's what I guess happens, with no absolute certainty:

- A user goes to example.com, a svelte-kit site with SSR and client-side router
- We deploy a new version of example.com
- The user clicks on a button that runs `invalidateAll()`
- Chaos ensues

The following "non errors" were captured on our Sentry:

> **Alert 1**
> ![image](https://github.com/sveltejs/kit/assets/48261497/3ac0381a-5b6d-46dd-9b0f-8cbd8d858a30)
> ![image](https://github.com/sveltejs/kit/assets/48261497/af65487d-bec1-4eb7-9a96-432c14ad9c06)

> **Alert 2**
> ![image](https://github.com/sveltejs/kit/assets/48261497/df381b55-05e1-4999-a4fb-2127b172d321)
> ![image](https://github.com/sveltejs/kit/assets/48261497/395e8aaf-4019-49f3-84d0-943087b9d306)

After investing both the minified and original code, this lead me to

https://github.com/sveltejs/kit/blob/10008b35e7194be1d9e54347731cab772b511ee4/packages/kit/src/runtime/client/client.js#L1813-L1817

This is the non-Error object with body and status keys that end up in Sentry

This is the only place in svelte-kit that returns 400 errors, and it's not JSON-formatted, which might explain why message ends up empty (see screenshots above)

https://github.com/sveltejs/kit/blob/10008b35e7194be1d9e54347731cab772b511ee4/packages/kit/src/runtime/server/respond.js#L78

I'm stopping my investigation here, but I can continue if need be

### Reproduction

Did not manage to create one yet

### Logs

```
Non-Error exception captured with keys: body, status
```

### System Info

```Shell
Svelte-kit 1.15.1
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-11-13 06:49
Closing this issue due to a lack of a reproduction

**Closed by eltigerchino** 2024-11-13 06:49 UTC
