### ISSUE TITLE
Adapter-static not putting CSS referenced assets in the right place

### ISSUE THREAD

**Issue by ptrxyz** [sveltejs/kit#4323] opened 2022-03-14 13:11 UTC
### Describe the bug

Resources linked to from CSS (i.e. `background-image: url(...)`) are not found after building a SvelteKit site with adapter-static.
The following works in vite (`npm run dev`) but not after building the site. One could work around it with absolute URLs, yet it's pretty annoying with many assets.

### Reproduction

Create these files:

- A random image at `static/wallpaper.jpg`

- A component `src/lib/components/something.svelte`:
```svelte
<div class="paper">something</div>

<style lang="postcss">
.paper {
    background-image: url(./wallpaper.jpg)
}
</style>
```

- Use the component in `src/routes/__layout.svelte`:
```svelte
<script>
import Something from "$lib/components/something.svelte"
</script>

<Something />

<slot />
```

- config (`svelte.config.js`):
```js
import preprocess from 'svelte-preprocess'
// import adapter from '@sveltejs/adapter-auto'
import adapter from '@sveltejs/adapter-static'
import path from 'path'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter(),
		prerender: { default: true },
	},

	preprocess: [preprocess({ postcss: true })]
}

export default config
```

- Build the app with adapter-static (`npm build`) and run a test HTTP server:
```sh
python3 -m http.server 9000 --directory build
```

- Observe in your browser's dev tools that the request to `wallpaper.jpg` is 404ing since it goes to `http://localhost/_app/assets/pages/wallpaper.jpg` instead of the 'http://localhost/wallpaper.jpg'

### System Info

```shell
System:
    OS: Linux 5.16 Arch Linux
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 50.72 GB / 62.78 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 17.7.1 - /usr/bin/node
    npm: 8.5.4 - /usr/bin/npm
  Browsers:
    Brave Browser: 99.1.36.112
    Firefox: 98.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.31 
    @sveltejs/adapter-static: ^1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: next => 1.0.0-next.295 
    svelte: ^3.46.4 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment] 2022-03-14 14:07
Please pay attention to the **Reproduction** section of the [issue template](https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml):

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by nichady** [comment] 2022-03-29 20:54
I have the same problem. Everything works fine in dev mode but when I deploy to Cloudflare pages, my image doesn't show up. When I view computed properties tab in the inspector, it tries to get the image from /_app/assets/pages/ instead of the right url.

**Comment by dominikg** [comment] 2022-03-30 11:45
note that `url()` values in style blocks of svelte components are not processed by default, see https://kit.svelte.dev/docs/assets#importing   

If you want to reference an asset placed in the static directory in css without additional processing, it should be done with an absolute path `/image.png` , not a relative one `./image.png`.

**Comment by Rich-Harris** [comment] 2022-04-25 18:26
I can't reproduce this, with or without postcss, so I'm going to close this issue. It's possible that it works now, but without a repro there's no way of knowing.

**Closed by Rich-Harris** 2022-04-25 18:26 UTC

**Comment by dominikg** [comment] 2024-01-12 15:43
> @dominikg you say `url()` values are not processed by default, but I'm not sure how to enable it? I'm having the issue described in this thread.

use `vitePreprocess` exported from `@sveltejs/vite-plugin-svelte` instead of svelte-preprocess
