### ISSUE TITLE
adapter-static can't build initial project

### ISSUE THREAD

**Issue by nosovk** [sveltejs/kit#3473] opened 2022-01-20 21:48 UTC
### Describe the bug

Current version of adapter-static broken from [1.0.0-next.24 version](https://github.com/MailCheck-co/mailcheck.site/commit/abecae86f209ffc9abdae02d59611bb406235472)
After that update adapter-static failing to build Kit template.
Current Skeleton App not compatible with svelte kit, or svelte kit is not compatible with static adapter.

### Reproduction

Create new kit project (npm init svelte@next my-app)
install @sveltejs/adapter-static@next
Add it to svelte.config.js as adapter instead of adapter-auto.
Try to build app.

### Logs

```shell
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> body used already for: 
    at consumeBody (file:///C:/proj/staticAdapterBroken/node_modules/@sveltejs/kit/dist/install-fetch.js:
4912:9)
    at Response.text (file:///C:/proj/staticAdapterBroken/node_modules/@sveltejs/kit/dist/install-fetch.j
s:4877:24)
    at visit (file:///C:/proj/staticAdapterBroken/node_modules/@sveltejs/kit/dist/chunks/index5.js:483:39
)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 13.38 GB / 31.88 GB
  Binaries:
    Node: 16.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.22.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.14
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26
    @sveltejs/kit: next => 1.0.0-next.236
    svelte: ^3.44.0 => 3.46.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Actually I was trying to fix https://github.com/MailCheck-co/mailcheck.site/commit/abecae86f209ffc9abdae02d59611bb406235472, but during debug I disabled everything in project with no luck. Then I tried to create new project, and found that new projects are broken from start.

**Comment by nosovk** [comment] 2022-01-21 10:15
Repo with reproduction
https://github.com/nosovk/sveltekit-broken-static-adapter

**Comment by kevtiq** [comment] 2022-01-21 13:06
Can conform this is happening for me as well. Dependencies from my package.json: `"@sveltejs/adapter-static": "^1.0.0-next.24", "@sveltejs/kit": "^1.0.0-next.236"`.

**Comment by dwsmart** [comment] 2022-01-21 14:01
also happens with `"@sveltejs/adapter-node": "^1.0.0-next.66"` if you set 
```
<script context="module">
	export const prerender = true;
	…
</script>
```
on a routes/ svelte file if there's also a `export const load = async ({ fetch }) => {`

**Comment by kevtiq** [comment] 2022-01-21 14:08
For the `static-adapter` I've tested it by removing the `export const prerender = true` and `export const hydrate = false` (which were both existing in my project). This does not solve the issues though.

**Comment by jormaj** [comment] 2022-01-21 16:22
Facing the same problem with my own SvelteKit project I also noticed that the default project also doesn't build.
It was a bit tricky to see which release introduced this bug, but from my experiments it looks like builds start to fail from `@sveltejs/kit@^1.0.0-next.234` (although that fails with a different error `request in handle has been replaced with event`).

I arrived at this conclusion by doing the following (which might not be the correct approach..)
`npm init svelte@2.0.0-next.94 my-app` (builds)
`npm i -D @sveltejs/adapter-static@next` (builds)
`npm install -D @sveltejs/kit@1.0.0-next.233` (builds)
`npm install -D @sveltejs/kit@1.0.0-next.234` (fails)

**Comment by russellgoldenberg** [comment] 2022-01-21 17:29
I'm finding a similar issue (though my build is failling silently, just not generating the index.html file. I pinned static-adapter on 1.0.0-next.26,  and tried rolling back kit versions and building until it worked. For me, [1.0.0-next.231](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next231) is where it stops working.

**Comment by kamholz** [comment] 2022-01-22 05:00
I don't entirely understand how this is happening but I've narrowed it down. Basically, `node-fetch` doesn't allow you to "consume" a response body more than once, i.e. you can't call `await response.text()` more than once on the same response. That's the immediate cause of the error.

It happens in [prerender's `visit()` method](https://github.com/sveltejs/kit/blob/a0b3be9902a9d251f207b436214c8616015edf5f/packages/kit/src/core/adapt/prerender/prerender.js#L132). It calls `app.render()` which populates the `dependencies` Map. The values of the map are Response objects. The body of these Response objects is [consumed in `load_node` here](https://github.com/sveltejs/kit/blob/ee906a3b2b103e4523eb1b6bb13f04d03eb35238/packages/kit/src/runtime/server/page/load_node.js#L211). Then, when `visit()` iterates through the dependencies, it tries to consume the body again [here](https://github.com/sveltejs/kit/blob/a0b3be9902a9d251f207b436214c8616015edf5f/packages/kit/src/core/adapt/prerender/prerender.js#L205). This fails for the reason described above.

I'm not sure what the right fix would be here because I don't understand the code well enough but I'm pretty sure this is the source of the error.

**Comment by nusendra** [comment] 2022-01-22 15:36
got this problem too

**Comment by nosovk** [comment] 2022-01-22 23:18
Unfortunately, I have no clue how to fix it now :(

**Comment by eba8** [comment] 2022-01-23 05:38
I'm facing this problem too, it's been an absolute nightmare.
Does anybody know if the team is working on a fix for this?

**Comment by bluwy** [comment] 2022-01-23 08:02
Reproducible on my end with demo app + adapter-static. According to https://github.com/node-fetch/node-fetch/issues/533#issuecomment-429261523, perhaps we can use `.clone()` internally for the prerenderer. The issue likely came up when we switch to using the `Response` object.

**Comment by moritzebeling** [comment] 2022-01-24 12:53
The `body used already for` also happens with the `adapter-netlify`.
SvelteKit `1.0.0-next.240`
Netlify Adapter `1.0.0-next.42`

**Comment by pavelloz** [comment] 2022-01-24 16:09
I just got this error as well.

```
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.26 
    @sveltejs/kit: next => 1.0.0-next.241 
```

I dont know if it helps but before svelte build there is this message:
```
17:07:24 [vite-plugin-svelte] vite-plugin-svelte was unable to find package.json of the following packages and wasn't able to resolve via their "svelte" field.
If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
- fs
```

I would contact the author of `fs` module but i have a weird feeling they wont be interested in my issue :-)

**Comment by sw-yx** [comment] 2022-01-25 03:22
confirmed @russellgoldenberg's observation that pinning dependency to `npm i -D @sveltejs/kit@1.0.0-next.231` worked.

**Comment by eba8** [comment] 2022-01-25 03:34
Where can one find a list of the versions available for static adapter and kit? @sw-yx suggestions didn't work on my end.

**Comment by eba8** [comment] 2022-01-25 03:41
Just tried rolling back versions and it looks like it doesn't work on my end. Tried going back a few months.

**Comment by pavelloz** [comment] 2022-01-25 10:54
@eba8 when you downgrade version remember also to clean npm cache and also write version explicitly in package.json. I got stuck for a while on this process because i forgot about the npm cache one day.

**Comment by skoontastic** [comment] 2022-01-25 14:35
Just ran into this and did what @sw-yx and @pavelloz suggested, and it worked.

**Comment by eba8** [comment] 2022-01-25 14:44
Maybe I'm doing this wrong?

I've updated package.json with `@sveltejs/adapter-static": "^1.0.0-next.24` and `@sveltejs/kit": "^1.0.0-next.231`.

Deleted svelte-kit files, build and node modules.

Ran `npm cache clean --force`

did `npm install`

`npm run build`

The error I still get: `body used already for`

**Comment by eba8** [comment] 2022-01-25 16:26
With the help of my amazing friend @octokatherine it's now working.

My mistake was having `^` in the versions.

Package.json with `@sveltejs/adapter-static": "1.0.0-next.24` and `@sveltejs/kit": "1.0.0-next.231` works

**Comment by pavelloz** [comment] 2022-01-25 21:58
Ah yes, the dirty `^` :-) Its not really freezing if its `^` :-)

**Closed** 2022-01-26 19:20 UTC
Labels: bug, pkg:adapter-static, p1-important

**Comment by vibhanshu909** [comment] 2022-03-05 19:26
I'm using `adapter-auto`.
Started getting this error from today on the release of `1.0.0-next.292`.
Using version `1.0.0-next.291` fixes this problem for me.

**Comment by 24jr** [comment] 2022-03-22 01:35
I'm having this problem right now. No index.html file is created in build folder using adapter-static 1.0.0-next.29 and svelte/kit next. Using versions @eba8 mentioned works but would like to use latest version. 

Is this bug and something that will be fixed or a new way of doing things. Causes my aws-amplify build to fail and caused capacitor build to fail

**Comment by iocron** [comment] 2022-04-04 20:56
This problem still exists with @sveltejs/kit@1.0.0-next.305

**Comment by yuliankarapetkov** [comment] 2022-04-07 08:57
Same issue for me 😕
