### ISSUE TITLE
page.server endpoints/server load functions can't trigger a layout.server rerun and refresh $page on the client

### ISSUE THREAD

**Issue by mostrecent** [sveltejs/kit#11415] opened 2023-12-20 13:36 UTC
### Describe the problem

Sometimes you need to refresh "a global object" which was passed from layout.server but the refresh needs to happen from an children server load function/page.server endpoint (or to be more precise: should be triggered when a children endpoint is called).

Now, you can do this only with a full page reload or not using layout.server but ensuring that the object is sent with every endpoint/sever load func.

### Describe the proposed solution

Option A, either some flag on the server load functions which let layout.server rerun

Option B, we can let hook.server pass stuff directly through the endpoints without manually passing stuff: locals.stuff in the server load func response

B should be actually covered by layouts (but, again, which do not rerun), so A might be more intuitive

### Importance

would make my life easier

**Comment by mostrecent** [comment] 2023-12-20 14:56
I found that I can let layout.server rerun with adding await parent(). But it does not change $page on the client in case the rerun gave new values. only those from the children endpoint are populated in $page

**Comment by mostrecent** [comment] 2023-12-21 05:04
Closed in favor of https://github.com/sveltejs/kit/issues/9355

**Comment by mostrecent** [comment] 2023-12-22 06:09
Reopening because of https://github.com/sveltejs/kit/issues/6315#issuecomment-1867281420 and https://github.com/sveltejs/kit/issues/9355#issuecomment-1867282304

**Comment by eltigerchino** [comment] 2024-10-29 08:16
closing as duplicate of https://github.com/sveltejs/kit/issues/9355

**Closed by eltigerchino** 2024-10-29 08:16 UTC
