### ISSUE TITLE
Service worker base path is not available in development

### ISSUE THREAD

**Issue by ttoino** [sveltejs/kit#11171] opened 2023-12-02 03:32 UTC
### Describe the bug

When developing a service worker in sveltekit, importing the `base` variable from the `$service-worker` produces an error when running in dev mode, but it works when running in production.

### Reproduction

https://github.com/ttoino/service-worker-dev-base

### Logs

```Shell
[vite] connecting...
service-worker.js:6 Uncaught SyntaxError: The requested module '/@id/__x00__virtual:$service-worker' does not provide an export named 'base' (at service-worker.js:6:10)
localhost/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('http://localhost:5174/') with script ('http://localhost:5174/service-worker.js'): ServiceWorker script evaluation failed
client.ts:150 [vite] connected.
```

### System Info

```Shell
System:
    OS: Linux 6.6 EndeavourOS
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 642.02 MB / 7.14 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.18.0 - /run/user/1000/fnm_multishells/780516_1701487367756/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.1.0 - /run/user/1000/fnm_multishells/780516_1701487367756/bin/npm
  Browsers:
    Chromium: 119.0.6045.159
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.1 => 2.1.1 
    @sveltejs/kit: ^1.27.6 => 1.27.6 
    svelte: ^4.2.8 => 4.2.8 
    vite: ^4.5.0 => 4.5.0
```

### Severity

annoyance

### Additional Information

The problem seems to be a difference between how this module is generated in `packages/kit/src/exports/vite/index.js:894` and `packages/kit/src/exports/vite/build/build_service_worker.js:40`. In the former, `base` is not generated.

**Comment by eltigerchino** [comment] 2023-12-21 12:38
closing this because I can't reproduce this using the given reproduction

**Closed by eltigerchino** 2023-12-21 12:38 UTC

**Comment by DoubleMalt** [comment] 2024-04-06 08:04
I have the same phenomenon

**Comment by eltigerchino** [comment] 2025-01-07 01:28
Can you open a new issue with a minimal reproduction?
