### ISSUE TITLE
no longer able to create adapter-static site where all pages are prerendered

### ISSUE THREAD

**Issue by rburgst** [sveltejs/kit#6480] opened 2022-08-31 17:02 UTC
### Describe the bug

as of [#6197](https://github.com/sveltejs/kit/pull/6197) it does not seem to be able to build a fully pre-rendered static site anymore.

We previously used `adapter-static` along with the 

```
	kit: {
		adapter:
			adapter(),
		        prerender: {
		              entries: allPageUris,
```

(note that not all pages are reachable via links).

Now I get the error 
```
➤ YN0000: [rb-links-frontend]: Error: config.kit.prerender.default has been removed. You can set it inside the top level +layout.js instead. See the PR for more information: https://github.com/sveltejs/kit/pull/6197
```

and

```
> Using @sveltejs/adapter-static
  @sveltejs/adapter-static: cannot have dynamic routes unless using the 'fallback' option. See https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode for more information
    - src/routes/[slug]
error during build:
Error: Encountered dynamic routes
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-cv4bx4?file=svelte.config.js

### Logs

```shell
> Using @sveltejs/adapter-static
  @sveltejs/adapter-static: cannot have dynamic routes unless using the 'fallback' option. See https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode for more information
    - src/routes/todos
error during build:
Error: Encountered dynamic routes
    at adapt@file:///home/projects/sveltejs-kit-template-default-cv4bx4/node_modules/ (sveltejs/adapter-static/index.js:50:12)
    at adapt@file:///home/projects/sveltejs-kit-template-default-cv4bx4/node_modules/ (sveltejs/kit/src/core/adapt/index.js:43:8)
    at handler@file:///home/projects/sveltejs-kit-template-default-cv4bx4/node_modules/ (sveltejs/kit/src/exports/vite/index.js:502:12)
    at <anonymous> (<anonymous>)
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 88.97 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 3.2.1 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 100.1.37.111
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.6.1
  npmPackages:
    @sveltejs/kit: 1.0.0-next.457 => 1.0.0-next.457
    vite: ^3.1.0-beta.1 => 3.1.0-beta.1
```

### Severity

blocking an upgrade

**Comment by rburgst** [comment] 2022-08-31 17:04
Note that if I add a fallback option and host the generated files on a normal web server, all I get is 404s obviously since no html pages are generated for `slug1.html` , etc.

**Comment by dummdidumm** [comment] 2022-08-31 17:12
You need to set `export const prerender = true` inside a `+layout.js` or `+layout.server.js`, not inside `+layout.svelte`

**Comment by Conduitry** [comment] 2022-08-31 17:14
This is essentially a duplicate of #6472. See the improved error message proposed in #6474.

**Closed by Conduitry** 2022-08-31 17:14 UTC

**Comment by rburgst** [comment] 2022-09-01 04:41
@Conduitry @dummdidumm  this gets rid of the error message however it still does not work. I need to specify a fallback option. If I do, then I still dont get the expected output `slug1.html`, `slug2.html`.
Basically it appears to me that it is no longer possible with `adapter-static` to generate a fully static website.

**Comment by rburgst** [comment] 2022-09-01 04:44
to be precise. I dont want a SPA. I want a fully rendered website.

**Comment by csjh** [comment] 2022-09-01 04:48
> @Conduitry @dummdidumm this gets rid of the error message however it still does not work. I need to specify a fallback option. If I do, then I still dont get the expected output `slug1.html`, `slug2.html`. Basically it appears to me that it is no longer possible with `adapter-static` to generate a fully static website.
> 
> <img alt="image" width="258" src="https://user-images.githubusercontent.com/22971/187833010-331d6eec-0b06-45e6-a5fb-6cee93afc3e3.png">

Chopping the mutative actions out of `todos/+page.server.js` and putting `export const prerender = true` in `/+layout.js` fixes your issue for me in the reproduction

**Comment by rburgst** [comment] 2022-09-01 04:52
I updated https://stackblitz.com/edit/sveltejs-kit-template-default-cv4bx4?file=svelte.config.js and deleted the whole `todos` folder. Still no `slug1.html`.

Here is the repro repo https://stackblitz.com/edit/sveltejs-kit-template-default-cv4bx4?file=svelte.config.js. 

Try and execute `npm run build` in a shell and check the output in the `build` folder.

Also note that I *have* to add a `fallback` option which enables SPA mode, even if I dont want it.
Can someone point me to a current working example (e.g. a blog) where full static prerendering works?

**Comment by csjh** [comment] 2022-09-01 04:54
> I updated https://stackblitz.com/edit/sveltejs-kit-template-default-cv4bx4?file=svelte.config.js and deleted the whole `todos` folder. Still no `slug1.html`.
> 
> Here is the repro repo https://stackblitz.com/edit/sveltejs-kit-template-default-cv4bx4?file=svelte.config.js.
> 
> Try and execute `npm run build` in a shell and check the output in the `build` folder.
> 
> Also note that I _have_ to add a `fallback` option which enables SPA mode, even if I dont want it. Can someone point me to a current working example (e.g. a blog) where full static prerendering works?

![image](https://user-images.githubusercontent.com/61282104/187834211-b9fa9ee4-e2bf-4cea-8c47-eafcc49844e6.png)


Again, you need to put `export const prerender = true` in `+layout.js`, not `+page.js`

**Comment by rburgst** [comment] 2022-09-01 04:57
sorry my bad, I had `layout.ts` not `+layout.ts`. Now it works! Thanks a lot.
So now there is only a single remaining thing. Since on my real site not all dynamic URLs are reachable via spidering, I am wondering whether there is a replacement for `kit.adapter.prerender.entries`.

**Comment by csjh** [comment] 2022-09-01 05:09
> sorry my bad, I had `layout.ts` not `+layout.ts`. Now it works! Thanks a lot. So now there is only a single remaining thing. Since on my real site not all dynamic URLs are reachable via spidering, I am wondering whether there is a replacement for `kit.adapter.prerender.entries`.

`kit.prerender.entries` is still a valid part of config

```js
const config = {
	kit: {
		adapter: adapter({ fallback: 'index.html' }),

		// Override http methods in the Todo forms
		methodOverride: {
			allowed: ['PATCH', 'DELETE']
		},

		prerender: {
			entries: [
				"*", "/slug3", "/slug4"
			]
		}
	}
};
```

**Comment by rburgst** [comment] 2022-09-01 05:35
hm, I guess then the documentation in https://kit.svelte.dev/docs/configuration#prerender needs a bit of an update since `prerender.default` is recommended but causes the initial error (and I understood the linked ticket that all `prerender` options were removed).
