### ISSUE TITLE
$env/dynamic/* does not work on Windows when running in `vite dev` mode on the server/nodejs.

### ISSUE THREAD

**Issue by DoisKoh** [sveltejs/kit#6361] opened 2022-08-29 08:18 UTC
### Describe the bug

The dynamic environment variables from `$env/dynamic/public` & `$env/dynamic/private` do not work when running on the server in Windows, in development mode. However, it works on the browser/client (for PUBLIC_ env vars), and it also works on the server as expected when run from a production build.

### Reproduction

Here's a link to a repro on StackBlitz - unfortunately, the StackBlitz environment is different from Windows - it works fine there but it doesn't work on Windows.

https://stackblitz.com/edit/sveltejs-kit-env-windows-issue?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Bpage.server.js%3AL5-L5

Running locally on Windows:
![image](https://user-images.githubusercontent.com/5701052/187157259-4abe1238-b4e1-4e26-9ddf-65f15852145a.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 9.27 GB / 31.90 GB
  Binaries:
    Node: 16.16.0 - C:\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.67
    @sveltejs/kit: next => 1.0.0-next.445
    svelte: ^3.46.0 => 3.49.0
    vite: ^3.0.8 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by StrawHatHacker** [comment] 2022-08-29 08:26
It's already here https://github.com/sveltejs/kit/issues/6152

Waiting for a fix as well

**Comment by dummdidumm** [comment] 2022-08-29 08:44
Duplicate of  #6152

**Closed by dummdidumm** 2022-08-29 08:44 UTC
