### ISSUE TITLE
An empty +page.server.js route file calls hooks.server.js

### ISSUE THREAD

**Issue by j4w8n** [sveltejs/kit#8686] opened 2023-01-24 00:03 UTC
### Describe the bug

Is this a bug or a feature?

If you create an empty `+page.server.js` file for a route, client-side navigation will call `hooks.server.js`. Of course, a page refresh or initial load will as well. I know this is supposed to be the behavior in general, but I assumed you'd at least need a `load` function in the file.

It's similar for `+page.js` files. An empty one will call `hooks.server.js` on a page refresh or initial load, but not on client-side navigation.

### Reproduction

Either in a new project or existing project, create an empty `+page.server.js` file for a route.
Log something like `console.log('handle called for', event.url.pathname)` to observe the behavior.
Navigate to the page.
Optionally, add an anchor tag to the page, from some other page, to test client-side navigation.

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 7.34 GB / 15.73 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.91
    @sveltejs/kit: 1.2.0 => 1.2.0
    svelte: ^3.55.1 => 3.55.1
    vite: 4.0.4 => 4.0.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment] 2023-01-24 07:32
possibly duplicate of #7967

**Comment by j4w8n** [comment] 2023-01-24 11:05
Indeed it is, thanks! Guess I was plugging in the wrong search terms to see if this already existed.

**Closed** 2023-01-24 11:06 UTC
