### ISSUE TITLE
Scrollbar is not scrolling the Page

### ISSUE THREAD

**Issue by CordialGit** [sveltejs/kit#12423] opened 2024-07-01 03:50 UTC
### Describe the bug

I am having a bad user experience on the SvelteKit Documentation Page.

The scroller here-- https://prnt.sc/XiJeEsjU0BP-

is not scrolling the Page. It's as if it responds to just mouse wheel.

Unfortunately, my mouse wheel is bad, so I'm struggling to scroll up and down on the Page.

Please, can this be worked on? -- so that it will be easy to scroll the Pages of the Documentation?

Regards.

### Reproduction

Just go to the SvelteKit page and try to scroll the page with the scrollbar

### System Info

```Shell
Windows 10
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-07-01 04:06
Hi Cordial, thanks for reporting this. May I know what browser you're using? The UI looks interesting but I would also like to try reproducing this on my windows machine too

**Comment by jasonlyu123** [comment] 2024-07-01 05:02
It should be the same reason with https://github.com/sveltejs/site-kit/issues/244 and https://github.com/sveltejs/site-kit/issues/276.

**Comment by CordialGit** [comment] 2024-07-01 05:29
@eltigerchino 

Now, for reasons I do not understand, Svelte sites, which are:
a.) https://svelte.dev

b.) https://kit.svelte.dev

Do not open in my Edge and Chrome and Mozilla Firefox browsers.

Even when I install a VPN, these Svelte and SvelteKit sites do not open.

So, I use Opera Mini Browser-- and it opens these sites, because it has an in-built VPN.

**Comment by sacrosanctic** [comment] 2024-07-01 12:58
![image](https://github.com/sveltejs/kit/assets/2974920/dcde052c-d84e-4bac-8b19-f110ff22e25c)

I also have the same problem, the aside is blocking the scrollbar

changing the `aside`'s `z-index from 2 to -1 fixes this

**Comment by eltigerchino** [comment] 2024-10-26 06:52
duplicate of https://github.com/sveltejs/kit/issues/10562

**Closed by eltigerchino** 2024-10-26 06:52 UTC
Labels: documentation
