### ISSUE TITLE
Layout with transition not unmounted on navigation

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#7405] opened 2022-10-27 03:08 UTC
### Describe the bug

When routing from `/b` to `/` using an anchor element, the `/b/+page.svelte` component does not get unmounted.

```svelte
<!-- /routes/b/+layout.svelte -->

<script>
  import { page } from '$app/stores';
  import { slide } from 'svelte/transition';

  $: isB = $page.url.pathname === '/b';
</script>

<slot />
{#if isB}
  <div transition:slide><a href="/">Home</a></div>
{/if}
```

```svelte
<!-- /routes/b/+page.svelte -->

<div><a href="/">Home</a></div>
```

- Expected behavior: all `/routes/b` related components should be unmounted.
- Actual behavior: the `<div><a href="/">Home</a></div>` component remains.

### Reproduction

Check [Stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-msgxqa?file=src/routes/a/+page.svelte)

**Instructions**
1. Press `/b`
2. Press `/a`

**Expected behavior**
```
/a

/b - /a/+page.svelte
```

**Actual behavior**
```
/a

/a - /b/+page.svelte
/b - /a/+page.svelte
```

### System Info

```Shell
System:
  OS: Windows 10 10.0.22621
  CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
  Memory: 3.79 GB / 15.32 GB

Binaries:
  Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
  npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

Browsers:
  Edge: Spartan (44.22621.675.0), Chromium (105.0.1343.53)
  Internet Explorer: 11.0.22621.1
```

### Severity

annoyance

### Additional Information

- https://github.com/sveltejs/kit/issues/3753#issue-1125425183

**Comment by s3812497** [comment] 2022-10-27 07:42
While waiting for a fix, you can workaround this by adding `local` to the transition:
```diff
<script>
  import { page } from '$app/stores';
  import { slide } from 'svelte/transition';

  $: isB = $page.url.pathname === '/b';
</script>

<slot />
{#if isB}
-   <li transition:slide><a href="/a"><code>/a</code></a> - <code>/b/+layout.svelte</code></li>
+  <li transition:slide|local><a href="/a"><code>/a</code></a> - <code>/b/+layout.svelte</code></li>
{/if}
```

But either way, a very interesting bug. I've had similar troubles with navigation and using transitions, but adding local usually fixes them. However, it's still annoying when it happens and you're new to Svelte.

**Comment by mglikesbikes** [comment] 2022-11-02 16:33
+1, but not using a transition. Seeing subsequent pages mount _under_ the previous page. Like, at the bottom of the page. The +layout _and_ +page of the child page is never unmounted.

<img width="335" alt="Screen Shot 2022-11-02 at 11 32 06 AM" src="https://user-images.githubusercontent.com/99897841/199547305-85b53259-f6c0-44cd-8610-f5254057fe10.png">
<img width="330" alt="Screen Shot 2022-11-02 at 11 32 16 AM" src="https://user-images.githubusercontent.com/99897841/199547308-781f6d18-b9d2-4eea-86fa-06b7b959ee0b.png">

**Comment by s3812497** [comment] 2022-11-02 16:35
> +1, but not using a transition. Seeing subsequent pages mount _under_ the previous page. Like, at the bottom of the page. The +layout _and_ +page of the child page is never unmounted.

Are you able to identify the cause?

**Comment by mglikesbikes** [comment] 2022-11-02 16:49
> Are you able to identify the cause? Personally curious

nope.

**Comment by Melkaz** [comment] 2022-11-09 18:54
I have made a reproducible example if you want to play with it: https://stackblitz.com/edit/sveltejs-kit-template-default-1fsbnb

**Comment by dummdidumm** [comment] 2022-11-17 10:37
I can't track this down to a recent kit version, going back as far as 450 still reproduces this.

**Comment by Tal500** [comment] 2022-11-29 12:19
possibly related - #7877

**Comment by jkrocks47** [comment] 2023-05-26 00:39
Pls fFix!

**Comment by benwoodward** [comment] 2023-06-01 08:52
ugh, just ran into this. very strange bug. pls fix!

**Comment by godmar** [comment] 2023-11-16 06:13
I also noticed that one of my pages took 500ms to disappear when navigating out. I tracked it to a [component](https://github.com/meigo/svelte-video-player/issues/20) I was using which was using a transition that was not `local`. In Svelte 3 and earlier, apparently, the default is global.  I think they must have recognized that this is a bad default. Svelte seems very ambitious, but somehow not quite there yet.

**Comment by eltigerchino** [comment] 2023-11-16 12:50
> I can't track this down to a recent kit version, going back as far as 450 still reproduces this. I think the issue lies in Svelte core. I can reproduce this with a simple variable that is updated every 10 miliseconds. My guess is that updating the value while transitioning out breaks things.
> 
> ```
> <script>
>   import { slide } from 'svelte/transition';
> 
>   let foo = {t:true}
>   setInterval(() => foo={t:true}, 10);
> </script>
> 
> <slot />
> {#if foo.t}
>   <li transition:slide><a href="/a"><code>/a</code></a> - <code>/b/+layout.svelte</code></li>
> {/if}
> ```
> 
> [stackblitz.com/edit/sveltejs-kit-template-default-8n1tyl?file=package.json,src%2Froutes%2F%2Blayout.svelte,src%2Froutes%2Fb%2F%2Blayout.svelte](https://stackblitz.com/edit/sveltejs-kit-template-default-8n1tyl?file=package.json,src%2Froutes%2F%2Blayout.svelte,src%2Froutes%2Fb%2F%2Blayout.svelte)

It seems to be fixed with Svelte 5. Here's an [updated repro](https://stackblitz.com/edit/sveltejs-kit-template-default-9vminq?file=src%2Froutes%2Fb%2F%2Bpage.svelte) I just updated all dependencies to their latest.

**Comment by godmar** [comment] 2023-11-16 16:25
While there may be multiple issues at play (see the many bug reports dealing with transitions), let me clarify what I believe I encountered.

If a Svelte 3 page/layout uses a third-party component (such as svelte-video-player in my case) which internally uses a non-local transition on any of its components, then this transition plays when the page contained the component is destroyed - this is probably as it should be, although likely the developer of the component didn't intend this, and it's creating problems for the user of the component because they have no way to override the transition (let alone that it's confusing and takes a long time to figure out).

But what's clearly a bug (in Svelte 3, probably) is this: not only does the transition play (and delay the hiding of the page that the component is in), but the new page that's being navigated to has already appeared even before all components in the old page have been transitioned out. It appeared under the previous one as described by @mglikesbikes. In my case, the old page/layout did eventually disappear after playing its transition (so this may not be quite the bug described here where the old page doesn't get destroyed at all).

I think the reason they made transitions local by default in Svelte 4 may be this, which is to avoid such unintended effects of components on the pages/layouts containing them.

**Comment by eltigerchino** [comment] 2024-11-12 09:56
Closing as fixed in svelte 5

**Closed by eltigerchino** 2024-11-12 09:56 UTC
Labels: bug, router, blocked by upstream
