### ISSUE TITLE
Page Refresh (F5) results in empty store value

### ISSUE THREAD

**Issue by faulander** [sveltejs/kit#8897] opened 2023-02-06 09:39 UTC
### Describe the bug

It has to do something with stores, on initial loading the store is set and can be subscribed, when i refresh the page, the same method results in an undefined:

```
const unsubscribe = userdata.subscribe(async (value) => {
		user = value;
	});
	console.log(user);

```
on first loading of the page (or when i navigate somewhere and then come back) the user variable holds the correct data. if i hit 
refresh, the user variable is empty.

### Reproduction

example REPL: https://svelte.dev/repl/9eae54c36485479b887af3bd6747bb36?version=3.55.1
(REPL is svelte, but since i cannot refresh in REPL anyway that shouldn't be in issue)

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 AMD EPYC 7282 16-Core Processor
    Memory: 4.35 GB / 7.74 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.91 
    @sveltejs/adapter-node: ^1.0.0-next.88 => 1.1.4 
    @sveltejs/kit: ^1.0.0 => 1.3.6 
    svelte: ^3.50.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

invalidate and invalidateAll does work like expected.
it only happens on pages, where i call that subscribe function.
it doesn't matter if i call the subscribe method synchronously or asyncronously.
It happens in all browsers.
it happens in dev and production (adapter node).
if i remove the subscribe method and fill the user variable with dummy data, it works.

**Comment by dummdidumm** [comment] 2023-02-06 09:59
I don't understand the issue from the reproduction. Please provide a SvelteKit reproducible with more context, for example using https://node.new/sveltekit

**Comment by faulander** [comment] 2023-02-06 13:40
I have narrowed it down:
in my +layout.svelte i have an onMount Section where i check if the user is logged in and if yes, i set it to the store userdata.
before that i have subscrived to that store:

1. Routine to subscribe to the store 'userdata'
2. in onMount section set the store 'userdata' to the user
3. out of onMount i try to read the content of the 'userdata'-story, it's always empty. 

I thought the subscribe method is reactive?
Example: https://stackblitz.com/edit/sveltejs-kit-template-default-kvr6bz?file=src/routes/+layout.svelte

**Comment by dummdidumm** [comment] 2023-02-06 16:07
In your referenced code you're invoking `console.log(user)`, which will run one time on startup. If you want to rerun that everytime `user` changes, you need to use a reactive statement:
```js
$: console.log(user);
```

Closing as this is not a bug or similar in SvelteKit.

**Closed by dummdidumm** 2023-02-06 16:07 UTC
Labels: awaiting submitter

**Comment by faulander** [comment] 2023-02-06 16:09
Sorry, but if one of my employees (i work as head of support in a big company) act like that, it would be their last day on the job.
The Problem is NOT that i want to rerun the console.log, but that the store is empty after refresh of the page while it is not when nagivation to another page and then coming back.

**Comment by dummdidumm** [comment] 2023-02-06 16:45
Your reproduction isn't very clear, which made me guess this is what you're getting at. This still sounds like a "user problem" because `onMount` hasn't been called yet when your `console.log(user)` runs, which is why it's empty.

**Comment by faulander** [comment] 2023-02-06 16:51
Ok, then i rephrase:
I need to do the job in the onMount section. How to i make sure that the store data is available in the rest of the  script section?

**Comment by dummdidumm** [comment] 2023-02-06 16:57
I don't know what exactly you mean by "available". You can't make it available on initialisation that way, but you would get notified of updates if it changes through reactive statements, and the UI would automatically rerender when the `user` value changes. In your reproducible (I think you updated it?) you're now running the console.log inside a reactive statement. You see it's running a second time after you update the value. Btw I would advise you to use the `$` syntax to autosubscribe to the store.

```svelte
<script>
	import { userdata } from '$lib/stores.js';
	import { onMount } from 'svelte';

	onMount(async () => {
		const userNew = {
			first_name: "John",
			last_name: "Doe"
		}
		$userdata = userNew
	});

	$: console.log('I rerun every time userdata is updated', $userdata);
</script>

<p>I'm rerendered everytime userdata is updated {JSON.stringify($userdata)}</p>
```

**Comment by faulander** [comment] 2023-02-06 17:01
i think i completely missunderstood the onMount functionality. I am coming from a backend education and the frontend part is a mystery ;) 
I moved my code out of onMount and now it works. The problem is exactly as you describe, onMount gets called after the complete DOM is rendered, as the complete script section is run. 

GERMAN: ich bin einfach ein frontend-trottel und habe jetzt einen ganzen tag verschissen, weil ich zwar die doku gelesen, aber nicht verstanden habe. Kannst schließen, Danke!

**Comment by vtulife** [comment] 2024-03-31 06:10
you can move your data to local storage if you want to persist data even after refreshing.
