### ISSUE TITLE
vite.config.ts: `Type 'Plugin<any>' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.`

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#13102] opened 2024-12-03 16:47 UTC
### Describe the bug

In a new SvelteKit (`npx sv create myapp`) app I'm getting this error from within the default `vite.config.ts`:

```ts
import { defineConfig } from 'vitest/config';
import { sveltekit } from '@sveltejs/kit/vite';

export default defineConfig({
	plugins: [sveltekit()],

	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	}
});
```

```
No overload matches this call.
  The last overload gave the following error.
    Type 'Promise<Plugin<any>[]>' is not assignable to type 'PluginOption'.
      Type 'Promise<Plugin<any>[]>' is not assignable to type 'Promise<false | Plugin<any> | PluginOption[] | null | undefined>'.
        Type 'Plugin<any>[]' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.
          Type 'Plugin<any>[]' is not assignable to type 'PluginOption[]'.
            Type 'Plugin<any>' is not assignable to type 'PluginOption'.
              Type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").Plugin<any>' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").Plugin<any>'.
                Types of property 'apply' are incompatible.
                  Type '"serve" | "build" | ((this: void, config: import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").UserConfig, env: import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").ConfigEnv) =...' is not assignable to type '"serve" | "build" | ((this: void, config: import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").UserConfig, env: import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").ConfigEnv) => boolean) | undefined'.
                    Type '(this: void, config: UserConfig, env: ConfigEnv) => boolean' is not assignable to type '"serve" | "build" | ((this: void, config: UserConfig, env: ConfigEnv) => boolean) | undefined'.
                      Type '(this: void, config: import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").UserConfig, env: import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").ConfigEnv) => boolean' is not assignable to type '(this: void, config: import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").UserConfig, env: import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").ConfigEnv) => boolean'.
                        Types of parameters 'config' and 'config' are incompatible.
                          Type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").UserConfig' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").UserConfig'.
                            Types of property 'plugins' are incompatible.
                              Type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").PluginOption[] | undefined' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").PluginOption[] | undefined'.
                                Type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").PluginOption[]' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").PluginOption[]'.
                                  Type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").PluginOption' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").PluginOption'.
                                    Type 'Plugin<any>' is not assignable to type 'PluginOption'.
                                      Type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").Plugin<any>' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").Plugin<any>'.
                                        Types of property 'apply' are incompatible.
                                          Type '"serve" | "build" | ((this: void, config: import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").UserConfig, env: import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").ConfigEnv) => boolean) | undefined' is not assignable to type '"serve" | "build" | ((this: void, config: import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").UserConfig, env: import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").ConfigEnv) =...'.
                                            Type '(this: void, config: UserConfig, env: ConfigEnv) => boolean' is not assignable to type '"serve" | "build" | ((this: void, config: UserConfig, env: ConfigEnv) => boolean) | undefined'.
                                              Type '(this: void, config: import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").UserConfig, env: import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").ConfigEnv) => boolean' is not assignable to type '(this: void, config: import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").UserConfig, env: import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").ConfigEnv) => boolean'.
                                                Types of parameters 'config' and 'config' are incompatible.
                                                  Type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").UserConfig' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").UserConfig'.
                                                    Types of property 'plugins' are incompatible.
                                                      Type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").PluginOption[] | undefined' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").PluginOption[] | undefined'.
                                                        Type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").PluginOption[]' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").PluginOption[]'.
                                                          Type 'import("C:/project/node_modules/.pnpm/vite@6.0.2_jiti@1.21.6_yaml@2.6.1/node_modules/vite/dist/node/index").PluginOption' is not assignable to type 'import("C:/project/node_modules/.pnpm/vite@5.4.11/node_modules/vite/dist/node/index").PluginOption'.
                                                            Type 'Promise<Plugin<any> | FalsyPlugin | PluginOption[]>' is not assignable to type 'PluginOption'.
                                                              Type 'Promise<Plugin<any> | FalsyPlugin | PluginOption[]>' is not assignable to type 'Promise<false | Plugin<any> | PluginOption[] | null | undefined>'.
                                                                Type 'Plugin<any> | FalsyPlugin | PluginOption[]' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.
                                                                  Type 'Plugin<any>' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.ts(2769)
config.d.ts(86, 18): The last overload is declared here.
```

### Reproduction

Just launch `npx sv create myapp` with pnpm and typescript options.

### System Info

```shell
-
```

### Severity

annoyance

**Comment by AdrianGonz97** [comment] 2024-12-03 17:40
As @dummdidumm mentioned, this is an issue of having multiple Vite versions. `vitest` just recently reverted their Vite 6 support in their [`v2.1.7` release](https://github.com/vitest-dev/vitest/releases/tag/v2.1.7), causing Vite 5 & 6 to be installed and the types to be mismatched

**Comment by dummdidumm** [comment] 2024-12-03 17:41
Closing since this is not a Svelte(Kit) issue

**Closed by dummdidumm** 2024-12-03 17:41 UTC

**Comment by baderj** [comment] 2024-12-04 09:43
> I can't reproduce this in a fresh project

I was able to reproduce the issue as follows:

```bash
~:> mkdir clean && cd clean
clean:> node --version
v22.12.0
clean:> npm --version
10.9.0
clean:> npx sv create
┌  Welcome to the Svelte CLI! (v0.6.6)
│
◇  Where would you like your project to be created?
│  ./
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  vitest
│
◇  Which package manager do you want to install dependencies with?
│  npm
│
◆  Successfully setup add-ons
│
◆  Successfully installed dependencies
│
◇  Project next steps ─────────────────────────────────────────────────────╮
│                                                                          │
│  1: git init && git add -A && git commit -m "Initial commit" (optional)  │
│  2: npm run dev -- --open                                                │
│                                                                          │
│  To close the dev server, hit Ctrl-C                                     │
│                                                                          │
│  Stuck? Visit us at https://svelte.dev/chat                              │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
└  You're all set!

clean:> npm run check

> clean@0.0.1 check
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json

If bundling, conditions should include development or production. If not bundling, conditions or NODE_ENV should include development or production. See https://www.npmjs.com/package/esm-env for tips on setting conditions in popular bundlers and runtimes.

====================================
Loading svelte-check in workspace: /home/user/clean
Getting Svelte diagnostics...

/home/user/clean/vite.config.ts:5:15
Error: No overload matches this call.
  The last overload gave the following error.
    Type 'Promise<Plugin<any>[]>' is not assignable to type 'PluginOption'.
      Type 'Promise<Plugin<any>[]>' is not assignable to type 'Promise<false | Plugin<any> | PluginOption[] | null | undefined>'.
        Type 'Plugin<any>[]' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.
          Type 'Plugin<any>[]' is not assignable to type 'PluginOption[]'.
            Type 'Plugin<any>' is not assignable to type 'PluginOption'.
            
            <cut>
```

The issue is tracked in the `cli` repo: https://github.com/sveltejs/cli/issues/341 

Everything works though including vitest, so just adding ``// @ts-nocheck`` to the `vite.config.ts` worked for me.

**Comment by opensas** [comment] 2024-12-20 16:29
what would be the recommended way to side step this issue unit vitest upgrades to vite 6?

adding a `// @ts-expect-error` in the vite.config and waiting for some package update to fix it???

**Comment by midirhee12** [comment] 2024-12-25 18:37
@opensas A number of options:
- remove vitest and import `defaultConfig` through `"vite"` instead
- revert vitest to when it still supported vite 6
- revert vite to vite 5
- cope until vitest support vite 6 again
- import `defaultConfig` through `"vite"` instead and comment out the `test` property from the config object in the meantime
- etc, etc

**Comment by midirhee12** [comment] 2024-12-25 18:52
After doing another clean install of sveltekit, it looks like the decision was to downgrade vite back to "^5.4.11" when vitest is also installed.

**Comment by Sija** [comment] 2025-03-27 00:17
Vitest 3.0.9 broke it again btw, 3.0.8 is good.
