### ISSUE TITLE
node.component... isn't a function

### ISSUE THREAD

**Issue by ghostdevv** [sveltejs/kit#7070] opened 2022-09-28 22:37 UTC
### Describe the bug

Occasionally I will get a `node.component isn't a function` error, I first found it when I had a layout group without a `+layout.svelte` but then later came across when I deployed a large project to netlify (haven't found the cause for that yet)

### Reproduction

Not been able to reliably reproduce yet, hoping this issue will provide visibility to others with the problem

### System Info

```shell
System:
    OS: Linux 5.19 undefined
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 3.11 GB / 15.55 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 105.1.43.89
    Chromium: 105.0.5195.125
    Firefox: 104.0.2
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.80 => 1.0.0-next.80 
    @sveltejs/kit: 1.0.0-next.504 => 1.0.0-next.504 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.4 => 3.1.4
```

### Severity

blocking an upgrade

**Comment by asv7c2** [comment] 2022-10-01 11:30
Have same problem, create nested +layout[.server].js without nested +layout.svelte and error is thrown: node.component is not a function.

**Comment by BiscuiTech** [comment] 2022-10-07 12:09
There seems to be an error on the file https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/page/render.js#L31, line 31:
```js
export async function render_response({
	branch,
	fetched,
	options,
	state,
	page_config,
	status,
	error = null,
	event,
	resolve_opts,
	action_result
}) {
// ...
}
```

branch is always value of `[]`, injected from here: https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/index.js#L213

```js
			if (state.prerendering?.fallback) {
				return await render_response({
					event,
					options,
					state,
					page_config: { ssr: false, csr: true },
					status: 200,
					error: null,
					branch: [],
					fetched: [],
					resolve_opts
				});
			}
```

**Comment by dummdidumm** [comment] 2022-11-11 19:09
SInce noone came up with a reproduction that isn't traceable back to a missing `+layout.svelte`, I'm closing this as a duplicate of #5967

**Closed by dummdidumm** 2022-11-11 19:09 UTC
Labels: awaiting submitter
