### ISSUE TITLE
Relative asset paths broke usage of imagetools

### ISSUE THREAD

**Issue by Amerlander** [sveltejs/kit#6326] opened 2022-08-26 21:10 UTC
### Describe the bug

The relative asset paths for the static adapter do not work when I use vite imagetools.

The resulting paths are always starting with `./_app/...`  instead of `/_app/...`. So the images are only working on the root path and don't load on any subpage.

I'm not sure whether this has to be adopted in image tools or if there should be an option in svelte kit to disable that behavior. Maybe both. In general, I think relative paths are great and would love to have this feature work with imagetools.

Breaking PR in Svelte Kit: https://github.com/sveltejs/kit/pull/4250
Coresponding Issue in imagetools: https://github.com/JonasKruckenberg/imagetools/issues/367

### Reproduction

1. clone https://github.com/Amerlander/image-import-test and npm i, npm run build:
2. Open /about-Page and check the source below the headline.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz    
    Memory: 11.75 GB / 31.93 GB
  Binaries:
    Node: 16.14.2 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD    
    npm: 8.5.0 - E:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.37) 
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/adapter-static: ^1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: next => 1.0.0-next.442 
    @sveltejs/vite-plugin-svelte: ^1.0.2 => 1.0.2 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by gyurielf** [comment] 2022-09-13 17:02
Maybe it's related: https://github.com/sveltejs/kit/pull/6769

**Comment by mquandalle** [comment] 2022-09-19 22:01
Do you know any workaround?

**Comment by intensr** [comment] 2022-09-20 14:15
this is a major issue since no image is working if we dont hardhack the baseurl (which then makes prerenders impossible)

**Comment by GauBen** [comment] 2022-09-20 20:05
Hey there, as a workaround you can do:

```svelte
<script>
	import image from './image.png';
</script>

<img src="/{image}" alt="image" />
```

**Comment by intensr** [comment] 2022-09-20 22:14
i got away with something like that as i serve my images locally from static folder

```
...
import { page } from '$app/stores';
import { prerendering } from '$app/environment';

export let src = undefined;

const origin = prerendering ? '' : $page.url.origin;

const imageUrl = `${origin}/images/{image}`
...
```
thanks for the help tho

**Comment by gyurielf** [comment] 2022-09-21 06:36
> i got away with something like that as i serve my images locally from an images folder within the static folder
> 
> ```
> ...
> import { page } from '$app/stores';
> import { prerendering } from '$app/environment';
> 
> export let src = undefined;
> 
> const origin = prerendering ? '' : $page.url.origin;
> 
> const imageUrl = `${origin}/images/{src}`
> ...
> ```
> 
> thanks for the help tho

But that's not preprocessed images.
The point of the issue is preprocess images with the `vite-imagetools`. so if you have 2000x1000 img in the static folder, you would use as 500x300, then it make an 500x300 img for you. (users do not need to load a large image)

**Comment by frankmayer** [comment] 2022-09-28 21:57
It seems to be an issue with imagetools after all. Can you pls check if your use case works with https://github.com/JonasKruckenberg/imagetools/pull/400?

**Comment by benmccann** [comment] 2022-10-04 19:35
I talked to @pzerelles, the author of https://github.com/JonasKruckenberg/imagetools/pull/400, and he clarified that the issue is that SvelteKit is passing the wrong value of `base` to Vite, so it is indeed a bug in SvelteKit

However, https://github.com/JonasKruckenberg/imagetools/pull/400 will provide a workaround by outputting everything as an absolute path rather than relative path so it won't matter that SvelteKit is providing an incorrect `base` value.

I had previously tried changing the value we're providing to Vite for the `base` path, but ran into a few problems and filed issues for those. We'll probably have to stick with the imagetools workaround until we can get those issues addressed in Vite

**Comment by benmccann** [comment] 2022-10-04 19:59
I talked to @pzerelles, the author of https://github.com/JonasKruckenberg/imagetools/pull/400, and he clarified that the issue is that Vite assets treats everything relative to Vite's basepath and not relative from where the asset is included, so Vite imagetools will need to use absolute paths rather than relative paths. Given that the issue is in imagetools and not Vite, I will go ahead and close this issue

**Closed by benmccann** 2022-10-04 19:59 UTC
Labels: bug, vite, p1-important, paths.base
