### ISSUE TITLE
Clicking the todos tab in the create svelte default template is janky

### ISSUE THREAD

**Issue by samal-rasmussen** [sveltejs/kit#5329] opened 2022-06-30 14:48 UTC
### Describe the bug

Clicking the todos tab in the `create-svelte` default template is janky. It doesn't transition to the todos page immediately when clicking on todos like it does with home and about. See the screen recording below.

This is surprising UX. For a split second it looks like the page just freezes with no indication.

https://user-images.githubusercontent.com/1503031/176706300-e7711381-8fa9-4337-b68d-f151f0657af3.mov

### Reproduction

* Select and install the default template when following the getting started guide: https://kit.svelte.dev/docs/introduction
* Specifically the install command is: `npm create svelte my-app`
* Keep following the guide to start the app.
* Click between the tabs after opening the app

Repo:
https://github.com/samal-rasmussen/create-svelte-janky-todos-reproduction

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 81.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.06.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 101.1.38.111
    Firefox: 102.0
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.53 
    @sveltejs/kit: next => 1.0.0-next.357 
    svelte: ^3.46.0 => 3.48.0
```

### Severity

annoyance

**Comment by gtm-nayan** [comment] 2022-06-30 15:24
Duplicate of #4264

Looks like someone [suggested](https://github.com/sveltejs/kit/issues/4264#issuecomment-1061699788) adding a loading indicator over there, but it didn't get anywhere, does sound like a nice middle ground

**Closed by gtm-nayan** 2022-06-30 15:24 UTC

**Comment by gtm-nayan** [comment] 2022-06-30 15:26
"not planned" sounds wrong
