### ISSUE TITLE
I need to change the `build` dir name

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#876] opened 2021-04-04 21:47 UTC
**Is your feature request related to a problem? Please describe.**
I need to change the `build` dir name.

**Describe the solution you'd like**
I wanna find how in docs page. I cannot now.

**Comment by benmccann** [comment] 2021-04-04 23:19
Is this for a specific adapter? What's the motivation?

**Comment by frederikhors** [comment] 2021-04-04 23:20
Adapter static, for now.

The motivation: to maintain compliance with other projects in the same team.

**Comment by babichjacob** [comment] 2021-04-05 02:13
Closing as duplicate of #868. Follow that issue for updates.

**Closed by babichjacob** 2021-04-05 02:13 UTC
