### ISSUE TITLE
(adapter-node) Set cache header for the `/static` files

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#11875] opened 2024-02-20 13:45 UTC
### Describe the problem

The Node.js adapter sets the `cache-control` to the `/_app/immutable` files only.

https://github.com/sveltejs/kit/blob/511126b51d4aaa770704491ff0890a76fa116205/packages/adapter-node/src/handler.js#L54-L56

Files in the `/static` directory - which are copied to the root of the `/_app` directory - are not cached by the client.

### Describe the proposed solution

- Provide an adapter option to set the `max-age` value.
- <strike>Set a default `cache-control` for the `/static` assets.</strike>

### Importance

nice to have

### Additional Information

- https://github.com/vitejs/vite/issues/15986

**Comment by brunnerh** [comment] 2024-02-20 13:57
Caching these by default is not a good idea because they have fixed paths so cache busting is not an option.
(Other assets automatically get a hash which makes their caching safe.)

**Comment by Conduitry** [comment] 2024-02-20 14:22
Duplicate of (part of) #3194.

**Closed by Conduitry** 2024-02-20 14:22 UTC

**Comment by hyunbinseo** [comment] 2024-02-20 14:31
My bad. I've actually 👍 one of the comments in that issue.

Note: With the `cache-control header` keyword, the issue is listed on the 4th page.
