### ISSUE TITLE
importing a ts file. probably should belong to FAQ

### ISSUE THREAD

**Issue by cognominal** [sveltejs/kit#1065] opened 2021-04-17 11:11 UTC
This is probably a common question and probably belongs to some FAQ.

I have successfully generated a repo supporting ts with svelte-kit.
I have some ts code that does not belong to any component.
I want to import it. If I use `import ... from ./utils.ts`, it does not
DWIM. If I use the `.js` suffix, I have to compile manually.
To get it to work there is probably some incantation to add in some config file.
I expect it to be added to sveltekit 1.0.
In the mean time, may be a small entry in sveltekit FAQ would help.

 <script lang="ts">
       ...
	import * as utils from from './utils.js';
       ...
  </script>

Clean and DRY Svelte and Sveltekit attract people like me who would not touch 
otherwise the js ecosystem
even with a ten foot pole. So expect naive questions from noobs like me.
Price of success.

Thx.

**Comment by dummdidumm** [comment] 2021-04-17 17:13
I cannot reproduce this given your code snippet. Some hints:
- When using TS, don't add the file endings. It should be `import .. from './utils'`, not `import .. from './utils.ts'` 
- `npm init svelte@next` will give you some promts to set up a new SvelteKit project, also asking whether or not you want TS support. Given your description I'm not sure you did that. If not, compare the outputs of that setup with your own.

I'm closing this for now since this is more of a usage question than a bug report or feature request.

**Closed by dummdidumm** 2021-04-17 17:13 UTC
