### ISSUE TITLE
Ability to specify where is the node server for dynamic routes

### ISSUE THREAD

**Issue by ktecho** [sveltejs/kit#9281] opened 2023-03-02 13:23 UTC
### Describe the problem

I have a SvelteKit app using `adapter-node`. Some routes are static, but others are in the form of `/dynamic_page/123`. That page with id=123 is built on the server (it has lots of `ifs` inside so it cannot be prerendered). All of this works fine in our production website.

Now, when using something like Capacitor, Electron or Tauri to build a native app, I've setup `prerender` for most of the pages, including the homepage. So now I have some `html` files that will be bundled in the app:

```
index.html
page1.html
admin/page1.html
admin/page2.html
```

Those files are inside the app, so they're accesed at `localhost`. So when the user is in `index.html` and he wants to go to `page1.html`, the webview of Capacitor/Electron/Tauri loads the file locally from `localhost` and that's it. It works.

The problem lies when you need to load one of the pages that don't have prerendering and need to be loaded from the server. It also tries to load that from `localhost`:

`http://localhost:3000/dynamic_page/123/__data.json?x-sveltekit-invalidated=__1`

But that page needs to be rendered in the `node server` that I have in `my_domain.com`. So is there a way to tell the SvelteKit router that the prerendered routes are in `localhost` but that the ones that are not prerendered are at `my_domain.com`?

### Describe the proposed solution

Maybe having a setup option like this:

```
const config = {
	kit: {
		adapter: adapter({
			out: 'build',
			host_prerender: 'localhost',
			host_node_server: 'my_domain.com/svelte_app',
		})
	},
}
```

So this would made the router aware of where to look for the files/requests it needs.

### Alternatives considered

I think this could be accomplished maybe by writting a new adapter.

### Importance

i cannot use SvelteKit without it

**Comment by Rich-Harris** [comment] 2023-03-02 15:12
Why aren't you running the server inside the app? Having part of your app prerendered but other parts hosted on the internet would break horribly the moment you deploy a new version.

**Comment by ktecho** [comment] 2023-03-02 15:50
> Why aren't you running the server inside the app? Having part of your app prerendered but other parts hosted on the internet would break horribly the moment you deploy a new version.

I don't think you can run a node server inside an Android/iOS app, right?

The thing is that Capacitor/Electron need some html to start showing something. So in our case it would be the homepage (and maybe FAQ, About, ...), then the rest of the app comes from the server.

If you don't provide any html and just point to `my-domain.com` you risk your app being rejected from the app stores because it's basically a website clone and doesn't work while offline.

**Comment by Rich-Harris** [comment] 2023-03-02 18:10
> I don't think you can run a node server inside an Android/iOS app, right?

[There's projects like this one](https://code.janeasystems.com/nodejs-mobile) that purport to allow it, though it's not something I'm overly familiar with. It doesn't need to be Node, it can be any JS runtime that supports the [web APIs SvelteKit needs](https://kit.svelte.dev/docs/web-standards). Integrating the server into your app will provide a much better user experience (version consistency, lower latency, better offline support etc).

Splitting the app up like this is just a recipe for pain caused by version mismatches, so it's definitely not something we want to bless with an official API. It sounds like the only reason for having any prerendered pages is to circumvent app store restrictions, in which case those HTML pages don't really need to be part of the same SvelteKit app, and probably shouldn't be. (I'm not condoning circumventing app store restrictions! If the app is really just a glorified webview with a splash page, it will probably get rejected sooner or later.)

**Comment by ktecho** [comment] 2023-03-02 20:25
I understand what you say, @Rich-Harris  Probably `nodejs-mobile` is not something that can be used easily, but I'll try it.

**Comment by Rich-Harris** [comment] 2023-03-02 22:03
Great — will close this, as it's not something that the framework can realistically do

**Closed by Rich-Harris** 2023-03-02 22:03 UTC
