### ISSUE TITLE
Route under multiple optional parameters is not matched correctly in every case

### ISSUE THREAD

**Issue by popapaul** [sveltejs/kit#10712] opened 2023-09-12 09:41 UTC
### Describe the bug

In case of the following route structure:

- /[[culture=culture]]/[[year=year]]/program      // Program route
- /[[culture=culture]]/[[year=year]]/[...content]   // Content route

The following links will go correctly to Program route:   

- /program   ✓
- /en/program  ✓
- /en/2022/program  ✓

But 
/2022/program  ✘ will instead go to Content route, practically turning the optional parameter culture into a required parameter when year is set which is not in my opinion the expected behaviour

1. Content route as rest parameter:

 ### Expected behaviour:  

- /2022/program   ->  Program route

### Actual behaviour:   

- /2022/program   ->  Content route

### Additionally 
When changing /[[culture=culture]]/[[year=year]]/[...content]  to  /[[culture=culture]]/[[year=year]]/[content],

The following links will go correctly to Content route:   

- /content ✓
- /en/content ✓
- /en/2022/content ✓

But 

- /2022/content ✘
- /2022/program  ✘     

will both be met by 404 Not Found.

2. Content route as parameter:

### Expected behaviour:   
/2022/program   ->  Program route
/2022/content     ->  Content route

### Actual behaviour:  
/2022/program   ->  404
/2022/content     ->  404

### Reproduction

[Stackblitz Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-jixbai?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=README.md,src%2Fparams%2Fculture.ts,src%2Fparams%2Fyear.ts,src%2Froutes%2F[[culture%3Dculture]]%2F[[year%3Dyear]]%2Fprogram%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte,src%2Froutes%2FHeader.svelte,src%2Froutes%2F[[culture%3Dculture]]%2F[[year%3Dyear]]%2F(index)%2F%2Bpage.svelte&title=SvelteKit%20Default%20Template)

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 17.48 GB / 31.93 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    svelte: ^4.2.0 => 4.2.0
```

### Severity

serious, but I can work around it

**Comment by allozaur** [comment] 2024-02-22 10:19
I've also encountered this issue in my project that's using `"@sveltejs/kit": "^2.0.0""` and `"svelte": "^4.2.7""`.

My structure looks like this:

```
src/

  routes/

  [[lang=lang]]/

      [explore=explore]/
        +page.server.js

          [offer_type=offer_type]/

              [[city=city]]/

                  [[district=district]]/

                      [[subdistrict=subdistrict]]/
                         +page.server.js

                          [view_mode=view_mode]/
                             +page.svelte
```

Routes that work for me are:

- `/en/explore/sale/map` — here `city`, `district` and `subdistrict` params are not present
- `/en/explore/sale/warszawa/srodmiescie/powisle/map` — here all 3 optional parameters are present

Routes that are returning 404:

- `/en/explore/sale/warszawa/map` — here we are missing `district` and `subdistrict` optional params
- `/en/explore/sale/warszawa/srodmiescie/map` — here we are just missing `subdistrict` optional param

**Comment by eltigerchino** [comment] 2024-12-03 06:00
Closing this one as I can no longer reproduce it after upgrading Kit to the latest version.

**Closed by eltigerchino** 2024-12-03 06:00 UTC
