### ISSUE TITLE
`svelte.config.ts` not recognized

### ISSUE THREAD

**Issue by notramo** [sveltejs/kit#12942] opened 2024-11-03 13:54 UTC
### Describe the bug

[Bun](https://bun.sh) can natively import TS files without any plugin needed. However, renaming `svelte.config.js` to `svelte.config.ts` makes the build (or dev server) fail.

### Reproduction

```sh
mv svelte.config.js svelte.config.ts
```

### Logs

```Shell
The logs contain import failures mentioning my project files which I don't disclose (but does not mention import failure of `svelte.config.ts`).
```

### System Info

```Shell
Running using Bun in Docker.

  System:
    OS: Linux 6.11 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    bun: 1.1.34 - /tmp/bun-node-5e5e7c60f/bun
  npmPackages:
    @sveltejs/adapter-node: ^5.2.8 => 5.2.9
    @sveltejs/enhanced-img: ^0.3.9 => 0.3.9
    @sveltejs/kit: ^2.7.2 => 2.7.2
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.0
    svelte: ^5.0.5 => 5.0.5
    vite: ^5.4.9 => 5.4.9
```

### Severity

annoyance

**Comment by polyzen** [comment] 2024-11-03 14:02
Duplicate of https://github.com/sveltejs/kit/issues/2576

**Closed** 2024-11-03 14:07 UTC
