### ISSUE TITLE
Support `handleFetch` for form actions.

### ISSUE THREAD

**Issue by accuser** [sveltejs/kit#6732] opened 2022-09-11 08:35 UTC
### Describe the problem

Calling `fetch` in a form action does not invoke `handleFetch`. It seems that this is because the platform implementation of `fetch` is being used, and not the Svelte Kit fetch proxy made available to `load`.

### Describe the proposed solution

I would like to see `fetch` method parameter added to `RequestEvent` or, perhaps even better, to introduce `ActionEvent` for actions, which include `fetch`.

### Importance

would make my life easier

**Comment by dummdidumm** [comment] 2022-09-11 08:49
Could you describe your use case for it?

**Comment by accuser** [comment] 2022-09-11 09:29
Certainly.

I'm building a SvelteKit app with an authentication service that requires a signed header. During development I want to use local functions. There are several places where a `fetch` request is made to the authentication service.

```ts
import type { Actions } from './$types';

export const actions: Actions = {
	default: async ({ request, url }) => {
		// stuff...

		try {
			fetch('https://auth.service.url/', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({ email })
			});
		} catch (e) {
			console.error(e);
		}

		// ...things
	}
};
```

```ts
import { AUTH_KEY } from '$env/static/private';
import { createHmac } from 'crypto';
import type { HandleFetch } from '@sveltejs/kit';
import { dev } from '$app/environment';

export const handleFetch: HandleFetch = ({ request, fetch }) => {
	if (request.url.startsWith('https://auth.service.url/')) {
		if (dev) {
			request = new Request(
				request.url.replace(
					'https://auth.service.url/',
					'http://localhost:9999/.netlify/functions/auth'
				),
				request
			);
		}

		const { host, pathname } = new URL(request.url);

		const date = new Date().toString();
		const signingString = `(request-target): post ${pathname}\nhost: ${host}\ndate: ${date}`;
		const signature = createHmac('sha1', AUTH_KEY).update(signingString).digest('base64');

		const authorization = `Signature keyId="${crypto.randomUUID()}",algorithm="hmac-sha1",headers="(request-target) host date",signature="${signature}"`;

		request.headers.set('authorization', authorization);
		request.headers.set('data', date);
	}

	return fetch(request);
};
```

**Comment by aradalvand** [comment] 2022-09-11 18:18
Probably duplicate of 6320

**Comment by benmccann** [comment] 2022-09-14 23:18
Closing as duplicate of https://github.com/sveltejs/kit/issues/6320

**Closed by benmccann** 2022-09-14 23:18 UTC
