### ISSUE TITLE
Incorrect data update detection in +page.svelte

### ISSUE THREAD

**Issue by sinbino** [sveltejs/kit#8548] opened 2023-01-16 10:45 UTC
### Describe the bug

https://github.com/sinbino/issue-sveltekit-reactive
See repository above

in src/routes/+page.svelte
```svelte
<script lang="ts">
  import type { PageData } from "./$types"
  import Select from "./Select.svelte"

  export let data: PageData
  $: console.log('change data', JSON.stringify(data))

  // valueA PATTERN
  // When valueA is changed, a change in data is detected (UNEXPECTED BEHAVIOR)
  let valueA: number
  $: { valueA = data.value }

  // valueB PATTERN
  // If valueB is changed, the change in data is not detected (EXPECTED BEHAVIOR)
  let valueB: number
  const setValueB = (v: number) => { valueB = v }
  $: { setValueB(data.value) }
</script>

<!-- valueA PATTERN -->
<Select bind:value={valueA}></Select><br>
valueA={JSON.stringify(valueA)}<br>

<!-- valueB PATTERN -->
<Select bind:value={valueB}></Select><br>
valueB={JSON.stringify(valueB)}<br>
```

When valueA is updated by the Select component, for some reason the update of data is detected.
This is a strange behavior because data is not actually updated at this time.

The code for valueB should be equivalent to the code for valueA.
However, if valueB is updated by the Select component, the update of data is not detected.
This is the expected behavior.

Why does this happen?

### Reproduction

https://github.com/sinbino/issue-sveltekit-reactive

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (10) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 5.52 GB / 9.90 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.1 
    @sveltejs/kit: ^1.0.0 => 1.1.1 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

**Comment by gtm-nayan** [comment] 2023-01-16 10:51
Duplicate of https://github.com/sveltejs/svelte/issues/7704

Also see https://github.com/sveltejs/svelte/issues/7416#issuecomment-1088075138

**Closed by gtm-nayan** 2023-01-16 10:51 UTC
