### ISSUE TITLE
Textfield is empty after form submit with use:enhance

### ISSUE THREAD

**Issue by Beiri22** [sveltejs/kit#9609] opened 2023-04-06 14:24 UTC
### Describe the bug

I am using a form to save some string into the db. When the form loads, the load function supplies the old string from db. After sending the form (with use:enhance) the textarea is empty.

What else:
-> without use:enhance it works as intended
-> the variable holds the correct content
-> an input type=text showed the same behaviour

### Reproduction

```svelte
<script lang="ts">
	import { enhance } from '$app/forms';

	export let data;
	let content = "";

	// When setting content directly, each keystroke triggers the content setting. You cannot type. This way, the reactive
	// statement does not know about content and thus only triggers with prop change.
	function setContent(s:string)
	{
		content = s
	}

	$: setContent(data.report?.content || '');
</script>

<form method="POST" use:enhance>
    <textarea name="content" cols="100" rows="20" bind:value={content} />
    <button type="submit">Absenden</button>
</form>

{JSON.stringify(data.report)} <- shows correct version of saved report

{content} <- is also updated correctly
```

### System Info

```Shell
System:
    OS: Linux 6.2 Manjaro Linux
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 22.83 GB / 31.27 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 19.8.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chromium: 111.0.5563.110
    Firefox: 111.0.1
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0 => 1.2.3 
    @sveltejs/kit: ^1.0.0 => 1.15.1 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.0.0 => 4.2.1
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment] 2023-04-13 09:59
The default behavior of `use:enhance` is to reset the field to be in conformance with how full page reloads would work (they also clear the fields). In your case however, you're re-setting the content through the binding, which works on a full page reload but not when using `use:enhance` because it empties it, not knowing about the two-way binding.

I'm not sure if there's a good way to solve this case, but in the meantime you can use the [`reset` option](https://kit.svelte.dev/docs/types#public-types-submitfunction) to not reset the form:
```svelte
<form method="POST" use:enhance={() => {
  return ({ update }) => update({ reset: false });
}}>
</form>
```

**Comment by diericx** [comment] 2023-04-29 07:16
So this is the most efficient way to implement form resets that bind values?

```
<script lang="ts">
export let formData = { name: "" };
</script>

<form method="POST" use:enhance={() => {
  return ({ update }) => {
    formData.name = '';
    update({ reset: false });
  }
}}>
		<input
			type="text"
			name="name"
			placeholder="Your name here"
			bind:value={formData.name}
		/>
</form>
```

**Comment by diericx** [comment] 2023-04-29 07:25
Maybe it is related to the typed fields I am using.
I am also finding that this completely wipes my input values as well, which is puzzling. Note there is no binding.
```
<script lang="ts">
export let formData = { weight: 0 };
</script>

<form method="POST" use:enhance>
	<input
	  type="number"
	  name="weight"
	  value={formData.weight}
	/>
</form>
```

Even this leads to completely blank input fields on submit for numbers and dates. Note the value is simply passed in.

```
<form method="POST" use:enhance>
	<input
	  type="number"
	  name="weight"
	  value={0}
	/>
</form>
```

**Comment by Beiri22** [comment] 2023-05-02 15:16
> The default behavior of `use:enhance` is to reset the field to be in conformance with how full page reloads would work (they also clear the fields). In your case however, you're re-setting the content through the binding, which works on a full page reload but not when using `use:enhance` because it empties it, not knowing about the two-way binding.

But, when a full page reset applies the data bindings, how can just resetting be in conformance with how full page reloads would work?

**Comment by tcc-sejohnson** [comment] 2023-05-09 23:51
> how can just resetting be in conformance with how full page reloads would work

He means how native form submits work -- submitting a POST form causes the page to reload and resets the form. In this case, however, Svelte is providing values to the form, but the `enhance` action doesn't have any way of knowing that (other than you telling it not to reset the form).

@dummdidumm did you mean to mark this as `ready to implement`? I'm not sure there's anything decided on right now (and I can't think of a good decision here).

**Comment by Beiri22** [comment] 2023-05-10 04:47
> but the `enhance` action doesn't have any way of knowing that

Is there really no way? Couldn't we use the compile step to add some marker to the form fields, so that enhance could read that information later?

**Comment by fs-99** [comment] 2023-06-08 12:27
Sounds similar to https://github.com/sveltejs/kit/issues/8513, only this time with `data` instead of `form`.

**Comment by mpost** [comment] 2023-10-19 16:05
Another approach to repopulate the form after submission from freshly `load`ed data is to reapply the data to a reactive variable:

```ts
<script lang="ts">
  import { enhance } from '$app/forms'

  export let form
  export let data

  $: settings = form?.errors ? form.settings : data.settings
</script>
```

Here we create a settings form. The `data.settings` provides the initial data and the data when the form is submitted successfully. The `form.settings` are used when the data is invalid, in which cases the `form.errors` flag is true and validation info is available in the `form`.

Now in the `<form>` declaration we can apply it:

```html
 <form
      method="POST"
      use:enhance={() =>
        async ({ update }) => {
          await update({ reset: false })
          settings = form?.errors ? form.settings : data.settings
        }}
    >
```

The key is to update the responsive `settings` variable which applies the changes to the form fields. Note that we still require `reset: false` as the form would be cleared otherwise, leading to a blinking of the data. Creating the value of `settings` should be put in its own method for reusability.

**Comment by sheijne** [comment] 2024-03-19 21:43
I might be missing something, and I haven't looked at the source (yet?), but it seems to me that `invalidateAll` is being called before the form is reset. Either that or the documentation is incorrect. When returning a function as such, and calling `invalidateAll` after `update` sets the input value as expected.

```
<form
  method="POST"
  use:enchance={() => {
    return async ({ update }) => {
      await update(); // Fields are reset
      await invalidateAll(); // Fields get their respective values from `$page.data`
    }
  }}
></form>
```

According to the docs:
> - update the form property, $page.form and $page.status on a successful or invalid response, but only if the action is on the same page you're submitting from. For example, if your form looks like <form action="/somewhere/else" ..>, form and $page will not be updated. This is because in the native form submission case you would be redirected to the page the action is on. If you want to have them updated either way, use [applyAction](https://kit.svelte.dev/docs/form-actions#progressive-enhancement-customising-use-enhance)
> - reset the <form> element
> - invalidate all data using invalidateAll on a successful response
> - call goto on a redirect response
> - render the nearest +error boundary if an error occurs
> - [reset focus](https://kit.svelte.dev/docs/accessibility#focus-management) to the appropriate element

This makes me assume that `invalidateAll` is called when `use:enhance` is used, in reality however it seems it is not, or at least not in the correct order (as calling it manually solves the issue.

**Comment by sheijne** [comment] 2024-03-19 21:52
It seems `invalidateAll` is call after resetting the form: https://github.com/sveltejs/kit/blob/35e46205b901083250ad333b650d39fe714c4bd1/packages/kit/src/runtime/app/forms.js#L96

Could `await tick()` in between the reset and the `invalidateAll()` call solve the issue? Or could another reset be caused by the `applyAction()` [later on](https://github.com/sveltejs/kit/blob/35e46205b901083250ad333b650d39fe714c4bd1/packages/kit/src/runtime/app/forms.js#L107)?

**Comment by eltigerchino** [comment] 2024-11-14 05:52
Closing this as resolved since I can't reproduce it on the latest version of Svelte and SvelteKit

**Closed by eltigerchino** 2024-11-14 05:52 UTC
Labels: bug, p3-edge-case, forms, ready to implement
