### ISSUE TITLE
Allow Vite import with query suffixes, which used to work previously in @sveltejs/kit@1.0.1 / Error: Cannot read properties of undefined

### ISSUE THREAD

**Issue by regnaio** [sveltejs/kit#9602] opened 2023-04-05 10:45 UTC
### Describe the problem

https://vitejs.dev/guide/features.html#import-with-query-suffixes
```js
import MyWorker from './worker?worker'

const worker = new MyWorker()
```

This used to work previously in `@sveltejs/kit@1.0.1`, but now building fails with the error: `[vite-plugin-sveltekit-compile] Cannot read properties of undefined (reading 'file')`

```bash
npm run build

...
rendering chunks (29)...The emitted file "vite-manifest.json" overwrites a previously emitted file of the same name.
[vite-plugin-sveltekit-compile] Cannot read properties of undefined (reading 'file')
✓ built in 5.02s
error during build:
TypeError: Cannot read properties of undefined (reading 'file')
    at file:///home/gbz/app/svelte/node_modules/@sveltejs/kit/src/exports/vite/build/build_server.js:74:83
    at Array.forEach (<anonymous>)
    at build_server_nodes (file:///home/gbz/app/svelte/node_modules/@sveltejs/kit/src/exports/vite/build/build_server.js:32:22)
    at Object.handler (file:///home/gbz/app/svelte/node_modules/@sveltejs/kit/src/exports/vite/index.js:683:5)
    at file:///home/gbz/app/svelte/node_modules/rollup/dist/es/shared/node-entry.js:24395:40
    at async PluginDriver.hookParallel (file:///home/gbz/app/svelte/node_modules/rollup/dist/es/shared/node-entry.js:24317:17)
    at async file:///home/gbz/app/svelte/node_modules/rollup/dist/es/shared/node-entry.js:25678:13
    at async catchUnfinishedHookActions (file:///home/gbz/app/svelte/node_modules/rollup/dist/es/shared/node-entry.js:24758:20)
    at async build (file:///home/gbz/app/svelte/node_modules/vite/dist/node/chunks/dep-79892de8.js:46246:22)
    at async CAC.<anonymous> (file:///home/gbz/app/svelte/node_modules/vite/dist/node/cli.js:813:9)
```

Broken on latest version:
`create-svelte@3.2.0`
`@sveltejs/kit@1.15.1`

### Describe the proposed solution

Maybe we need to find the regression

### Importance

i cannot use SvelteKit without it

**Comment by gtm-nayan** [comment] 2023-04-06 01:55
Please provide a proper reproduction for the issue as instructed by the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by bluwy** [comment] 2023-04-06 15:39
I think this is a duplicate of https://github.com/sveltejs/kit/issues/9528

**Closed by bluwy** 2023-04-06 15:39 UTC
Labels: awaiting submitter
