### ISSUE TITLE
SvelteKit RequestEvent.url.host(name) is undefined for https. This happens with the dev plugin.

### ISSUE THREAD

**Issue by ivandimitrov8080** [sveltejs/kit#4319] opened 2022-03-13 13:14 UTC
### Describe the bug

The `req.headers.host` in the code below found in `kit/packages/kit/src/core/dev/plugin.js` has a value of undefined when the server is https, but it works fine when it's http.

```
vite.middlewares.use(async (req, res) => {
    try {
        if (!req.url || !req.method) throw new Error('Incomplete request');

        const base = `${vite.config.server.https ? 'https' : 'http'}://${req.headers.host}`;
```

### Reproduction

Create a new skeleton project and run the server using the --https flag:
HTTPS:
![image](https://user-images.githubusercontent.com/80976541/158060915-27af1819-4c88-4be8-8324-58554eca8d16.png)
HTTP:
![image](https://user-images.githubusercontent.com/80976541/158060942-efa792af-3bea-4283-b583-c7f1a04985e5.png)

### System Info

```shell
System:
    OS: Linux 5.16 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 12.85 GB / 15.48 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.7.1 - /usr/bin/node
    npm: 8.5.4 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.31 
    @sveltejs/kit: next => 1.0.0-next.295 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

blocking an upgrade

### Additional Information

This propagates down to the `event.url` var on `handle`.

**Comment by benmccann** [comment] 2022-03-16 22:19
https://github.com/sveltejs/kit/issues/4362 was filed as a duplicate of this one. I'm going to keep that one though since it's had some more details added to it

**Closed by benmccann** 2022-03-16 22:19 UTC
