### ISSUE TITLE
Client-side router fails to remove title

### ISSUE THREAD

**Issue by vwkd** [sveltejs/kit#2144] opened 2021-08-09 16:16 UTC
### Describe the bug

When using client-side routing to navigate to a page without a title, the title from the previous page is used.

Instead, it should use the title from the layout component if present, or no title otherwise.

SSR uses the correct title.

This isn't breaking, but definitely annoying to show a wrong title.

### Reproduction

See https://github.com/vwkd/sveltekit-bugs/tree/persistent-title

No title

https://user-images.githubusercontent.com/33468089/128741981-e2f75d73-2b4f-43ca-91dd-75770db75355.mov

Title in layout component

https://user-images.githubusercontent.com/33468089/128741417-b7686908-3471-443a-a38a-8cd0082e2265.mov

### System Info

```shell
System:
    OS: macOS 11.5
  Binaries:
    Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
    npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.11 => 1.0.0-next.16 
    @sveltejs/kit: next => 1.0.0-next.142 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

annoyance

**Comment by manuel3108** [comment] 2021-08-09 16:37
Can reporoduce, but I dont know if this is a bug.

Once you add something like this to `index.svelte`:
```svelte
<svelte:head>
    <title />
</svelte:head>
```
It starts working as expected.

If you have a close look at your tab, you can see that when you first visit the page it displays something like `localhost:3000`. This is the default that is displayed by the browser if the title is not set.

Once you make the change suggested above, you can click to about, see about, and then click your index. After that it starts displaying the `localhost:3000` thing.

So in my opinion this works like what i expect. But what would be your expected behaviour?

PS: You might also try to export it with adapter static and see what happens if you have the refreshs between the two pages.

**Comment by benmccann** [comment] 2021-08-09 20:23
Duplicate of https://github.com/sveltejs/kit/issues/1540

**Closed by benmccann** 2021-08-09 20:23 UTC
