### ISSUE TITLE
Adapter-static: Check +page.server.js files

### ISSUE THREAD

**Issue by georges-g** [sveltejs/kit#10483] opened 2023-08-04 08:22 UTC
### Describe the problem

I am currently building a website with adapter-static and I have a few routes that use a `+page.server.js` file.

I can build those routes with the adapter easily if I have:
```
export let prerender = true;
```

For each of those `+page.server.js`.

I also need to have `export let ssr = true` at the root of my app to make sure the server functions are executed during the generation.

What I find frustrating currently is that, if I forget to have `export let prerender = true` in one of my `+page.server.js`, the build is successful, but the app does not work.

### Describe the proposed solution

I would like the adapter to check that, if there is a `+page.server.js` with a `load()` function, it should have a specific `export let prerender = true` and `export let ssr = true` should be also activated.

If not, it should raise an error or a warning.

### Alternatives considered

Manual checks

### Importance

would make my life easier

**Comment by dummdidumm** [comment] 2023-08-04 08:53
Closing as duplicate of #10332 . Btw you don't need `export let ssr = true` at the root, that's the default. And you can add `export let prerender = true` in your root `+layout.js` so you don't have to write it in each `+page.server.js`.

**Closed by dummdidumm** 2023-08-04 08:53 UTC

**Comment by georges-g** [comment] 2023-08-04 09:08
@dummdidumm I think you are mistaken. I have `export let prerender = true;` in my `src/routes/+layout.js` but it is not enough. I need to specifically turn it on for my `+page.server.js`.

**Comment by dummdidumm** [comment] 2023-08-04 09:43
That would be a bug, do you have a reproducible?

Note that `+server.js` will _not_ inherit the `export let prerender = true` setting - just in case we're talking about different things.

**Comment by georges-g** [comment] 2023-08-04 13:43
I was talking about `+page.server.js`, but I tried to recreate the bug in a simple settings and couldn't. Then I checked my main repo and could not reproduce the bug either.

I guess I was in the wrong here, sorry for the false alarm.
