### ISSUE TITLE
fetch in next.83 errors with: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by vinkodlak** [sveltejs/kit#1133] opened 2021-04-19 18:31 UTC
i get this error:

500
Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at parse_body (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/ssr.js:1330:60)
    at ssr (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/ssr.js:1448:9)
    at fetch (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/ssr.js:697:30)
    at load (index.svelte:3:27)
    at load_node (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/ssr.js:784:30)
    at respond (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/ssr.js:1006:21)
    at async render_page (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/ssr.js:1154:20)
    at async render (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/ssr.js:1467:10)
    at async ssr (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/ssr.js:1454:10)
    at async Immediate.<anonymous> (file:///Users/vinkov/svelte/novo/node_modules/@sveltejs/kit/dist/chunks/index.js:3297:23)

with this simple code:

```svelte
<script context="module">
  export async function load({fetch}) {
    const res = await fetch('/server', {
      method: 'POST',
      body: {}
    })

    const { name } = await res.json()

    return {
      props: {
        name
      }
    }
  }
</script>
<script>
  export let name
</script>

<h1>{name}, Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```

when body is null or '' is works fine
if i put JSON.stringify({...}) there is same error

server.js is simple as this:
```js
export async function post() {
  return {
    body: {
      name: 'My Name'
    }
  }
}
```

**Comment by vinkodlak** [comment] 2021-04-19 18:40
reverting to 80 works, breaks with 81

**Comment by Conduitry** [comment] 2021-04-19 19:17
Duplicate of #1127.

**Closed by Conduitry** 2021-04-19 19:17 UTC
