### ISSUE TITLE
Empty Body in POST and other requests

### ISSUE THREAD

**Issue by Osbornnnnn** [sveltejs/kit#6852] opened 2022-09-16 12:19 UTC
### Describe the bug

My problem is that on the server side when performing fetch, empty values are sent to the body.

API request: FormData is empty
![image](https://user-images.githubusercontent.com/36417885/190631476-7159372d-b513-40cb-802b-937b43273ed7.png)

FormData getting from Form -_-
![image](https://user-images.githubusercontent.com/36417885/190631833-920afc30-165b-401c-9325-1358ed9a7f19.png)

In +page.server.js  --  DONT WORK
In +page.js  --  WORK

### Reproduction

https://github.com/Osbornnnnn/SvelteKit-Bug-1

### System Info

```shell
System:                                                        
    OS: Windows 10 10.0.19043                                    
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor             
    Memory: 17.81 GB / 31.93 GB                                  
  Binaries:                                                      
    Node: 16.17.0 - F:\1Programm\nodejs\node.EXE
    npm: 8.15.0 - F:\1Programm\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.74
    @sveltejs/kit: next => 1.0.0-next.483
    svelte: ^3.44.0 => 3.50.1
    vite: ^3.1.0 => 3.1.1
```

### Severity

annoyance

**Comment by repsac-by** [comment] 2022-09-16 12:50
https://github.com/sveltejs/kit/issues/5710

This is a `undici` bug

**Comment by Conduitry** [comment] 2022-09-16 13:02
Closing as duplicate of #5710.

**Closed by Conduitry** 2022-09-16 13:02 UTC
