### ISSUE TITLE
`invalidate()` does not cause +layout.svelte endpoints to load 

### ISSUE THREAD

**Issue by oscarhermoso** [sveltejs/kit#6373] opened 2022-08-29 14:35 UTC
### Describe the bug

Expected: When calling `invalidate()`, the `load()` function will run for both `+page.server.js` and `+layout.server.js` endpoints.

Actual: When calling `invalidate()`, the `load()` function does not run for 
 `+layout.server.js` endpoints.

Was working in 1.0.0-next.443, now broken for versions >= 1.0.0-next.444.

### Reproduction

See below minimal repo that reproduces the bug, by having one counter on +page.server.js, and another counter in a `+layout.server.js` file.

https://github.com/oscarhermoso/layout-invalidate-bug

On page refresh, both counters increment as expected.

However, if you click the button to call `invalidate()`, only the `+page.server.js` counter increments.

Install previous svelte-kit version with `npm i @sveltejs/kit@1.0.0-next.443` to see previous behaviour working as expected.

### Logs

```shell
N/A
```

### System Info

```shell
System:
    OS: Linux 5.18 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 7.50 GB / 15.58 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Firefox: 103.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.68 
    @sveltejs/kit: ^1.0.0-next.445 => 1.0.0-next.445 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment] 2022-08-29 14:45
Duplicate of #6349 , fix was released a few seconds ago

**Closed by dummdidumm** 2022-08-29 14:45 UTC

**Comment by oscarhermoso** [comment] 2022-08-29 14:50
@dummdidumm legend, cheers
