### ISSUE TITLE
Page breaks on page change

### ISSUE THREAD

**Issue by hasinoorit** [sveltejs/kit#12424] opened 2024-07-01 07:12 UTC
### Describe the bug

The page content is not updating when clicking a link or using the goto('/path') method in Svelte 5. After clicking a link, the old page content is removed, but the new page content is not inserted into the DOM. No errors or warnings are logged in the console.
**Expected Behavior:**
The new page content should be inserted into the DOM when navigating to a new path using goto('/path').

### Reproduction

[stackblitz](https://stackblitz.com/~/github.com/hasinoorit/svbug)
[github](https://github.com/hasinoorit/svbug)

Run the development server.
Click on a link.
Observe that the old page content is removed.
Note that the new page content does not appear in the DOM.

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 81.42 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
    bun: 1.1.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.2 
    @sveltejs/kit: ^2.0.0 => 2.5.18 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.1 
    svelte: ^5.0.0-next.1 => 5.0.0-next.167 
    vite: ^5.0.3 => 5.3.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

This issue is only present in the development server.
It is not reproducible in Svelte 4; it works as expected.

**Comment by dummdidumm** [comment] 2024-07-01 07:50
Closing as duplicate of https://github.com/sveltejs/svelte/issues/12235

**Closed by dummdidumm** 2024-07-01 07:50 UTC
