### ISSUE TITLE
"export const prerender = false" is not working

### ISSUE THREAD

**Issue by moisesbites** [sveltejs/kit#5949] opened 2022-08-16 21:26 UTC
### Describe the bug

I'm using "plotly.js-finance-dist": "^2.14.0" for plot dashboard in a big app made with sveltekit.

Even if I putt in the `+page.js` and `+page.svelte`:

```JS
	export const prerender = false;
```

If I don't put in response on `hooks.ts`, `npm run dev` throw a error when I access the page with component that plot the dashboard:

```JS
const response = await resolve(event, {
		ssr: false
	})
```

If I don't put in prerender on `svelte.config.js`, `npm run build` throw a error when the compiler try to prerender the page:

```JS
prerender: {
			enabled: false
		}
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-nszg9o?file=svelte.config.js,src%2Froutes%2F%2Bpage.svelte,src%2Fhooks.js,src%2Froutes%2F%2Bpage.js&terminal=dev

### Logs

```shell
npm run dev

self is not defined
[18]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7003:1
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[254]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:47318:17
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[1]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:10:18
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[236]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:44704:8
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[6]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:95:18
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[12]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:125:21
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
r@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:798
@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:826
@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:88
@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:322
function@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:131047
Module.prototype._compile@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:219079
Module._extensions[".js"]@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:219743
Module.prototype.load@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:217769
Module._load@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:215340
@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:983448
_evaluate@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:292426
evaluate@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:291597
run@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:987352

npm run build
vite v3.0.7 building SSR bundle for production...
✓ 59 modules transformed.
.svelte-kit/output/server/vite-manifest.json                    3.04 KiB
.svelte-kit/output/server/index.js                              57.89 KiB
.svelte-kit/output/server/entries/pages/_layout.svelte.js       4.09 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js     0.60 KiB
.svelte-kit/output/server/entries/pages/_page.svelte.js         7.99 KiB
.svelte-kit/output/server/entries/pages/_page.js                0.05 KiB
.svelte-kit/output/server/entries/pages/about/_page.svelte.js   1.25 KiB
.svelte-kit/output/server/entries/pages/about/_page.js          0.15 KiB
.svelte-kit/output/server/entries/pages/todos/_page.svelte.js   5.92 KiB
.svelte-kit/output/server/entries/pages/todos/_page.server.js   1.22 KiB
.svelte-kit/output/server/chunks/index.js                       4.80 KiB
.svelte-kit/output/server/chunks/index2.js                      0.73 KiB
.svelte-kit/output/server/chunks/index3.js                      1.29 KiB
.svelte-kit/output/server/chunks/stores.js                      0.62 KiB
.svelte-kit/output/server/chunks/hooks.js                       0.49 KiB
[18]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7003:1
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[254]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:47318:17
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[1]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:10:18
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[236]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:44704:8
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[6]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:95:18
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
o/<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:682
[12]<@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:125:21
o@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:631
r@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:798
@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:826
@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:88
@/home/projects/sveltejs-kit-template-default-nszg9o/node_modules/plotly.js-finance-dist/plotly-finance.js:7:322
function@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:131047
Module.prototype._compile@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:219079
Module._extensions[".js"]@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:219743
Module.prototype.load@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:217769
Module._load@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:215340
@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:983448
_evaluate@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:292426
_evaluate@https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:292549

Error: 500 /
    at normalise_error_handler/<@file:///home/projects/sveltejs-kit-template-default-nszg9o/node_modules/ (sveltejs/kit/src/core/prerender/prerender.js:63:11)
    at save@file:///home/projects/sveltejs-kit-template-default-nszg9o/node_modules/ (sveltejs/kit/src/core/prerender/prerender.js:351:9)
    at visit@file:///home/projects/sveltejs-kit-template-default-nszg9o/node_modules/ (sveltejs/kit/src/core/prerender/prerender.js:238:7)
    at <anonymous> (<anonymous>)
[vite-plugin-svelte-kit] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at writeBundle/</<@file:///home/projects/sveltejs-kit-template-default-nszg9o/node_modules/ (sveltejs/kit/src/vite/index.js:406:14)
    at EventEmitter.prototype.emit (https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:155573)
    at ChildProcess/this._handle.onexit (https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:956235)
    at <anonymous> (https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:379477)
    at _0x2ad5fe (https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:137333)
    at _0x3ef042/< (https://sveltejs-kit-template-default-nszg9o.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:137073)
    at <anonymous> (<anonymous>)
```

### System Info

```shell
System:
    OS: Linux 5.15 Linux Mint 20.3 (Una)
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Memory: 16.10 GB / 23.37 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.17.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Chromium: 104.0.5112.79
    Firefox: 103.0.2
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/kit: 1.0.0-next.411 => 1.0.0-next.411 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.8
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment] 2022-08-17 18:34
There are two parts to this:
1. Prerendering: I can no longer reproduce the `npm build` issue, this was probably fixed through #5930 
2. Error during `npm dev`: This is expected because the page is rendered on the server by default, too. You need to set the `ssr` option inside the  [`handle` function](https://kit.svelte.dev/docs/hooks#handle):
```ts
/** @type {import('@sveltejs/kit').Handle} */
export const handle = async ({ event, resolve }) => {
	// this disables server side rendering for the homepage - adjust this to your needs
	return await resolve(event, { ssr: event.url.pathname !== '/' });
};
```

The first one was an error that was fixed, the second one is "as expected" and has a solution, therefore closing this.

**Closed by dummdidumm** 2022-08-17 18:34 UTC
Labels: bug, p1-important

**Comment by moisesbites** [comment] 2022-08-17 19:50
@dummdidumm 

OK. Thanks for the guidance.

But, I think this `export const prerender=false;` statement means that I don't want the page to be pre-rendered. That #2 is semantically a little weird.

No?

**Comment by dummdidumm** [comment] 2022-08-17 19:51
Prerender = render the page to html on build, not when the user hits the age
SSR = render the page on the server and send the So these are two different things

**Comment by moisesbites** [comment] 2022-08-17 19:53
> Prerender = render the page to html on build, not when the user hits the age SSR = render the page on the server and send the So these are two different things

Sorry. Thank you.
