### ISSUE TITLE
Send data from hooks to page load functions without a server load function

### ISSUE THREAD

**Issue by pilcrowOnPaper** [sveltejs/kit#6714] opened 2022-09-10 02:26 UTC
### Describe the problem

When implementing auth, it's impossible to run load functions in parallel. This is roughly how auth are implemented right now:

1. Check for the user in hooks, add user data in `locals`
2. Read `locals` in `+layout.server.ts` and add that to page data
3. `await parent()` in load functions to check for user

It would be great if we can move step 2 to a new function from a load function so it won't block all load functions below it from running. 

### Describe the proposed solution

I would like to see something similar to `getSession()` in hooks, that runs between hooks and load functions. This function can populate page data or populate a different new object.

### Alternatives considered

none

### Importance

would make my life easier

**Comment by cdcarson** [comment] 2022-09-12 13:51
> It would be great if we can move step 2 to a new function from a load function so it won't block all load functions below it from running.

Totally agree there needs to be a way to clearly separate business logic from data retrieval/caching. The former probably needs to be run every request (as used to be possible with `load' and `getSession`.) The latter only when a part of the cache is explicitly invalidated in client code. 

Related to #6315.

**Comment by Rich-Harris** [comment] 2022-11-10 22:08
@pilcrowOnPaper you seemed to have a change of heart in https://github.com/sveltejs/kit/issues/7107#issuecomment-1305855405 (and I think you're right that #7107 was a dupe of this) — does that mean this issue should be closed?

(For anyone following along: https://github.com/sveltejs/kit/issues/7107#issuecomment-1305808087 articulates why passing data from `locals` to client-side `load` functions is something we should avoid.)

**Comment by pilcrowOnPaper** [comment] 2022-11-10 23:33
@Rich-Harris oops, forgot to close this, thanks for reminding me!

**Closed** 2022-11-10 23:33 UTC
