### ISSUE TITLE
`load` doesn't have access to endpoint routes

### ISSUE THREAD

**Issue by sunny-mittal** [sveltejs/kit#1524] opened 2021-05-23 03:10 UTC
**Describe the bug**
Apologies if I'm just not understanding how `load` works but I set up a small test endpoint in /src/routes/api/test.ts:
```
const sleep = (time: number) => new Promise(res => { setTimeout(() => res(true), time) })
export const get = async () => {
  await sleep(1000)
  return {
    body: { str: 'it works!' }
  }
}
```
Then in my src/routes/index.svelte file:
```
<script lang="ts" context="module">
  export async function load() {
    const res = await fetch('/api/test')

    return {
      props: {
        data: await res.json()
      }
    }
  }
</script>

<script lang="ts">
  export let data: any
</script>

<pre>{JSON.stringify(data)}</pre>
```
Upon running this, I get the below logs

**Logs**
```
Invalid URL: /api/test
TypeError [ERR_INVALID_URL]: Invalid URL: /api/test
    at new NodeError (node:internal/errors:363:5)
    at onParseError (node:internal/url:537:9)
    at new URL (node:internal/url:613:5)
    at new Request (file:///Users/smittal/workspace/pizza-morte/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.109_svelte@3.38.2/node_modules/@sveltejs/kit/dist/install-fetch.js:1239:16)
    at file:///Users/smittal/workspace/pizza-morte/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.109_svelte@3.38.2/node_modules/@sveltejs/kit/dist/install-fetch.js:1448:19
    at new Promise (<anonymous>)
    at fetch (file:///Users/smittal/workspace/pizza-morte/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.109_svelte@3.38.2/node_modules/@sveltejs/kit/dist/install-fetch.js:1446:9)
    at index.svelte:3:27
    at Generator.next (<anonymous>)
    at eval (/Users/smittal/workspace/pizza-morte/src/routes/index.svelte:39:66)
```

**To Reproduce**
* Create a new app with `pnpm init svelte@next test-app`
* Add the code above in the relevant files (src/routes/api/test.ts, src/routes/index.svelte)
* Run the app -- crash

**Expected behavior**
The `load` method hits the endpoint and returns the data

**Stacktraces**
(see logs above, that's all it gives)

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 619.77 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.0.0/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.109
    svelte: ^3.34.0 => 3.38.2

- Chrome: 90.0.4430.212 

- Adapter: none -- just running the dev server
</details>

**Severity**
I'd say pretty severe; it blocks expected (to me) usage of `load` methods

**Additional context**
An additional piece of useful info is that changing nothing but moving the endpoint call into an `onMount` works great.

**Comment by benmccann** [comment] 2021-05-23 03:26
`load` definitely has access to endpoint routes. Please ask for help on Discord. I'm closing this since it's not a bug

**Closed by benmccann** 2021-05-23 03:26 UTC

**Comment by babichjacob** [comment] 2021-05-23 04:13
> Then in my src/routes/index.svelte file:
> 
> ```svelte
> <script lang="ts" context="module">
>   export async function load() {
> ```

You've missed accepting `fetch` as a parameter—this is the one that works as you expected:

```svelte
<script lang="ts" context="module">
    export async function load({ fetch }) {
```
