### ISSUE TITLE
`Svelte:head` issue, app does not compile

### ISSUE THREAD

**Issue by brgrz** [sveltejs/kit#1661] opened 2021-06-09 20:15 UTC
**Describe the bug**

When I include `<svelte:head>` within the index.svelte the compiler gives

`Cannot find module './transformers/module' Require stack: - D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\autoProcess.js - D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\index.js`

**To Reproduce**
Create new empty (skeleton) SvelteKit app. Add `<svelte:head>` to the index.svelte component and include some JS or CSS links (from CDN for example). The app won't run (500 error) with the above description.

**Expected behavior**
The app should run and svelte head should work. Is there a reason it doesn't work in SvelteKit apps? I did not find it documented anywhere nor is there any other issue open/closed on this topic.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

Require stack:
- D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\autoProcess.js
- D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\index.js
Error: Cannot find module './transformers/module'
Require stack:
- D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\autoProcess.js
- D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\autoProcess.js:36:77
    at async Object.transform (D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\autoProcess.js:36:29)
    at async D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\autoProcess.js:109:29
    at async script (D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte-preprocess\dist\autoProcess.js:137:33)
    at async process_single_tag (D:\GitHub\brgrz\sl-bugs\handler-violations\node_modules\svelte\compiler.js:30241:28)
    at async Promise.all (index 1)

</details>

**Information about your SvelteKit Installation:**

latest

<details>
  <summary>Diagnostics</summary>

Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 7.11.2 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.41)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.113
    svelte: ^3.38.2 => 3.38.2

</details>

**Severity**
Pretty severe

**Comment by Conduitry** [comment] 2021-06-09 20:26
The error indicates that you're using svelte-preprocess and that its auto-preprocess feature is getting confused by the type of a `<script>` - https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#auto-preprocessing

If that doesn't help, please provide a complete repro that can be cloned.

**Comment by brgrz** [comment] 2021-06-09 20:33
Svelte-preprocess is part of default SvelteKit skeleton project, I did not add it myself. 

The script tag has red squiggles regardless of having the `lang="ts"` attribute or not. The squiggles are gone and the app runs fine if <svelte:head> tag is removed from the code.

the issue is in the presence of `<svelte:head>` tag, now how does that effect svelte-preprocess I wouldn't know

**Comment by benmccann** [comment] 2021-06-11 03:09
@brgrz there's still not enough info here to reproduce the issue. I have a `<svelte:head>` tag in my project and it works just fine, so we'd need an example that breaks

**Comment by brgrz** [comment] 2021-06-17 06:58
Here is the repo. The only thing I did is create a new Sveltekit project, make it Skeleton, TS and Prettier on, then ran it and it ran fine. Added the `<svelte:head>` with a couple of CDN links and it now does not run anymore.

https://github.com/brgrz/sveltekit-bugs/tree/main/head-issue

**Comment by benmccann** [comment] 2021-06-17 13:38
Thanks, that made it clear what the issue is. Closing as duplicate of https://github.com/sveltejs/svelte-preprocess/issues/261. There's a workaround provided there

**Closed by benmccann** 2021-06-17 13:38 UTC
