### ISSUE TITLE
Allow layout.js without layout.svelte

### ISSUE THREAD

**Issue by stephane-vanraes** [sveltejs/kit#6746] opened 2022-09-12 07:43 UTC
### Describe the problem

In some cases you are not using layouts to render extra elements but rather to load shared data, or to check for permissions within a subtree.  This code resides fully in `+layout.js` or `+layout.server.js` and has no use for `+layout.svelte`.  It is however not possible to have these files in isolation and not having the `.svelte` file gives the following error:

```
node.component is not a function
TypeError: node.component is not a function
```

### Describe the proposed solution

Allow to have a `layout.js` file without `layout.svelte`.
The compiler can detect this situation and virtually inject a svelte file of the form:

```html
<slot />
```

### Alternatives considered

Actually making the `+layout.svelte` yourself, but this adds unnecessary boilerplate to the code.

### Importance

nice to have

**Comment by dummdidumm** [comment] 2022-09-12 07:50
Duplicate of #5967

**Closed by dummdidumm** 2022-09-12 07:50 UTC
