### ISSUE TITLE
international URL routes

### ISSUE THREAD

**Issue by LexRiver** [sveltejs/kit#5026] opened 2022-05-22 08:54 UTC
### Describe the bug

By using international domain name, I'm using international filenames for routes, for example:
```/routes/регистрация.svelte```
That all works, but when I'm trying to add tag ```<style></style>``` I'm getting the following error:
```
[plugin:vite-plugin-svelte] Invalid character
D:/lex/projects/termosib-agro.ru/termosib-shop-2022/termosib-shop-sk/src/routes/регистрация.svelte
    at btoa (node:buffer:1220:13)
    at SourceMap.toUrl (file:///D:/lex/projects/termosib-agro.ru/termosib-shop-2022/termosib-shop-sk/node_modules/svelte/compiler.mjs:27313:72)
    at dom (file:///D:/lex/projects/termosib-agro.ru/termosib-shop-2022/termosib-shop-sk/node_modules/svelte/compiler.mjs:27383:56)
    at compile (file:///D:/lex/projects/termosib-agro.ru/termosib-shop-2022/termosib-shop-sk/node_modules/svelte/compiler.mjs:32274:15)
    at compileSvelte2 (file:///D:/lex/projects/termosib-agro.ru/termosib-shop-2022/termosib-shop-sk/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:320:20)
    at async TransformContext.transform (file:///D:/lex/projects/termosib-agro.ru/termosib-shop-2022/termosib-shop-sk/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1714:25)
    at async Object.transform (D:\lex\projects\termosib-agro.ru\termosib-shop-2022\termosib-shop-sk\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38900:30)
    at async doTransform (D:\lex\projects\termosib-agro.ru\termosib-shop-2022\termosib-shop-sk\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:55857:29
```

Seems like this happening only while in ```npm run dev``` mode.

### Reproduction

Just create any international route like ```регистрация.svelte``` with ```<style></style>``` tag inside

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
    Memory: 7.40 GB / 15.98 GB
  Binaries:
    Node: 17.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.42
    @sveltejs/kit: next => 1.0.0-next.330
    svelte: ^3.44.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment] 2022-05-22 09:00
This sounds like a duplicate of https://github.com/sveltejs/svelte/issues/6714

**Closed by Conduitry** 2022-05-22 09:00 UTC
