### ISSUE TITLE
Sync-Cli Issue: Missing Types and TypeScript Version Mismatch in Monorepo Setup

### ISSUE THREAD

**Issue by Tjomas** [sveltejs/kit#11447] opened 2023-12-22 13:05 UTC
Hi,

this is entirely my mistake. However, some support from the sync-cli would have been desirable.

The following issue arose:
The Sync-Cli simply stopped calculating LayoutData, PageData, etc. The data in the $types was always "unknown." This happened because in the **"@sveltejs\kit\src\core\sync\write_types\index.js"** file, the **tweak_types** function used an old TypeScript (<5) ts.getModifiers that no longer exists. The corresponding catch block had no error output. So, you simply don't get any proxies, and everything runs through.

I understand that SvelteKit 2 requires TypeScript 5 as a minimum. Unfortunately, we have a monorepo. In the package with SvelteKit, TypeScript 5.3 was set. The build and the actual application could be executed successfully. Everything seemed to work. However, the import in **"ts.js" -> ts = (await import('typescript')).default;** took the TypeScript version from the root of the monorepo, which was unfortunately 4.7.2. You don't notice this, and everything works, except for the missing types. I'm not sure why it only takes the version from the root of the monorepo in this case.

But a simple warning in the catch block would have significantly facilitated the search.

Best regards,
Thomas

### Reproduction

Run pnpm i  and pnpm sync in the root.
Then the PageData is: export type PageData = Expand<Omit<PageParentData, keyof unknown> & OptionalUnion<EnsureDefined<unknown>>>;

https://stackblitz.com/edit/sveltejs-kit-template-default-kzgy8y?file=packages%2Fdemo-package%2Fsrc%2Froutes%2F%2Bpage.ts

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 25.98 GB / 63.63 GB
  Binaries:
    Node: 20.8.1 - ~\AppData\Local\Volta\tools\image\node\20.8.1\node.EXE
    npm: 10.1.0 - ~\AppData\Local\Volta\tools\image\npm\10.1.0\bin\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\Volta\tools\image\pnpm\8.9.2\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.77), ChromiumDev (121.0.2277.4)
    Internet Explorer: 11.0.22621.1
```

### Severity

annoyance

**Comment by eltigerchino** [comment] 2024-11-22 08:29
Closing as duplicate of https://github.com/sveltejs/kit/issues/11915

**Closed by eltigerchino** 2024-11-22 08:29 UTC
