### ISSUE TITLE
load() of index.svelte returns data of _layout.svelte

### ISSUE THREAD

**Issue by tw1t611** [sveltejs/kit#1338] opened 2021-05-05 08:28 UTC
**Describe the bug**
When using the load() function in _layout.svelte and index.svelte, the returned data of index gets overridden by _layout. 
The index props load once with the right data (I can see the page). Afterwards `export let data` gets overridden.

**Logs**
![image](https://user-images.githubusercontent.com/13353525/117114025-982bd180-ad8b-11eb-9a89-59638de9e366.png)

**To Reproduce**
Create similiar files an run the dev server:

index.svelte
```js
<script context="module">
  export async function load({ page, fetch }) {
    const query = ` some gql `;
    const response = await fetch("http://localhost:1337/graphql", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        query,
      }),
    });
    const json = await response.json();
    console.log("index: ", json);    // layout data

    return {
      props: {
        data: json,
      },
    };
  }
</script>

<script>
  export let data;
</script>
```

_layout.svelte
```js
<script context="module">
  export async function load({ page, fetch }) {
    const query = ` some other gql `;
    const response = await fetch("http://localhost:1337/graphql", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        query,
      }),
    });
    const json = await response.json();
    console.log("json: ", json);

    return {
      props: {
        data: json,
      },
    };
  }
</script>

<script>
  export let data;

  $: console.log("index:  ", data);  // undefined
</script>
```

**Expected behavior**
Load in index.svelte should query right data and props should not be overridden.

**Stacktraces**

<details>
  <summary>npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers</summary>
  System:
    OS: Linux 5.11 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 4800U with Radeon Graphics
    Memory: 843.08 MB / 15.06 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.3/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Firefox: 88.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.99 
    svelte: ^3.35.0 => 3.38.2 
    vite: ^2.1.2 => 2.2.4 

Occures on all static and node adapter.

</details>

**Severity**
blocking development of _layout.svelte and child components except <slot />

**Workaround**
If you have a similar issue, you could remove the load() function in _layout.svelte for now.

**Comment by tw1t611** [comment] 2021-05-05 09:28
Furthermore, if I request two queries in a row in index.svelte, the second query returns the data of the first.

```js 
    const pageData = await _fetch(pageQuery, fetch); // undefined
    const trustImagesData = await _fetch(trustImagesQuery, fetch) // page data
```

This seems to be related.

**Comment by babichjacob** [comment] 2021-05-05 15:47
Right away -- without testing -- I suspect the issue is that SvelteKit is using the same cache key (wherein the data from server-side `fetch` is included in the HTML) because the requests are to the same URL. 

Is this still what happens when you fetch to different URLs between the requests? Or if you disable `ssr` and `prerender`ing?

**Comment by benmccann** [comment] 2021-05-05 23:56
Closing as duplicate of https://github.com/sveltejs/kit/issues/633

**Closed by benmccann** 2021-05-05 23:56 UTC
Labels: bug
