### ISSUE TITLE
svelte-kit dev doesn't work due to "no such file" error

### ISSUE THREAD

**Issue by OliverHGray** [sveltejs/kit#2005] opened 2021-07-24 14:30 UTC
### Describe the bug

The Skeleton Project produced by npm init doesn't appear to be able to run with `npm run dev`, it produces the following error: `ENOENT: no such file or directory, open '**omitted**/test/.svelte-kit/dev/components/.svelte-kit/dev/components/layout.svelte'`.

There are no problems with running the app when built, only the dev server appears to have issues.

### Reproduction

`npm init svelte@next test`
Select `Skeleton Project`
Select Typescript: `Yes`
Select Linting: `No`
Select Prettier: `No`
`cd test`
`npm run dev`
Visit `localhost:3000` in browser and the error message will be displayed

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 625.56 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    npm: 7.20.0 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Firefox: 89.0.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.137 
    svelte: ^3.34.0 => 3.40.2
```

### Severity

serious, but I can work around it

### Additional Information

Note: I have other SvelteKit projects that run fine on this machine that I created months ago, but all new projects have this issue.

**Comment by Conduitry** [comment] 2021-07-24 15:05
Duplicate of #2001/#2004.

**Closed by Conduitry** 2021-07-24 15:05 UTC
