### ISSUE TITLE
Typescript added even tho requested no to

### ISSUE THREAD

**Issue by king612** [sveltejs/kit#4646] opened 2022-04-17 15:35 UTC
### Describe the bug

Generating a new app, I chose not to add typescript support.  I want to have a pure JS app.  TS was added anyway and is generating TS-related compile issues as I build the app out.  This appears to be a bug. 

### Reproduction

A generate new app with SvelteKit. Select No to the Typescript support prompt.  Observe that TS artifacts are added anyway. 

### System Info

```shell
macOS, chrome browser. Very recent kit version (last week)

I will add this when I get back to my machine.
```

### Severity

serious, but I can work around it

### Additional Information

Thank you for SvelteKit.  Really great product!

**Comment by Conduitry** [comment] 2022-04-17 16:11
I can't reproduce this with a new `npm init svelte` project and selecting all of the default options. We'll need to know specifically what you did to see this.

**Comment by king612** [comment] 2022-04-18 15:33
Following the basic sveltekit instructions and saying No to typescript prompt, after running, I have *.d.ts files all over plus a tsconfig.json file that were generated on running the project.  That is conflicting with other things I have installed.

So, what does saying No to typescript really mean?  Looks like it gets added on every build whether you want it or not.  That is not desirable, and apparently I have no way to suppress it?

**Comment by king612** [comment] 2022-04-18 16:34
Here's the system info.  I am also using Sveltestrap, which I know is in progress, but I don't believe it uses Typescript.  Here's the env info:

  System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.01 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.101
    Chrome: 100.0.4896.127
    Firefox: 66.0.1
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.311 
    svelte: ^3.47.0 => 3.47.0 

I'll get the specific TS build error I'm getting too.

**Comment by king612** [comment] 2022-04-18 16:52
OK, this is due to an apparently well known popper.js issue, so I guess you can close it...  I see the other issues both here and there.   Meanwhile, any workaround suggestions would be appreciated.

Cannot use import statement outside a module
/Users/john/projects/dems/node_modules/@popperjs/core/dist/esm/popper.js:1
import { popperGenerator, detectOverflow } from "./createPopper.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
       :

with this package.json:


{
  "name": "dems",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "package": "svelte-kit package",
    "preview": "svelte-kit preview",
    "prepare": "svelte-kit sync"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "svelte": "^3.47.0"
  },
  "type": "module",
  "dependencies": {
    "@fontsource/fira-mono": "^4.5.0",
    "@lukeed/uuid": "^2.0.0",
    "bootstrap": "^5.1.3",
    "cookie": "^0.4.1",
    "sveltestrap": "^5.9.0"
  }
}

**Comment by Conduitry** [comment] 2022-04-18 16:58
Closing this in favor of #4504. This doesn't sound related to TypeScript.

The `.d.ts` files created in `.svelte-kit` are intended - so that you can get intellisense in your editor if it supports it - but should not cause any build issues unless you opt in to type checking.

**Closed by Conduitry** 2022-04-18 16:58 UTC
Labels: awaiting submitter
