### ISSUE TITLE
$page.url.origin is set to https when a page is served over http

### ISSUE THREAD

**Issue by lovasoa** [sveltejs/kit#3248] opened 2022-01-08 20:13 UTC
### Describe the bug

$page.url is not setto the actual URL of the page in adapter-node when served over http 

### Reproduction

```svelte
<script>
	import { page } from '$app/stores';
</script>

{$page.url.origin}
```

Use adapter-node, compile and serve the application with`svelte-kit build && node build`, load `http://localhost:3000` in your browser. 

expected: `http://localhost:3000`
actual: `https://localhost:3000`

### System Info

```shell
latest sveltekit
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment] 2022-01-08 20:25
This is the intended behavior now, although perhaps it could be documented better. Production mode will assume https unless you have a [`protocol` header](https://kit.svelte.dev/docs#configuration-headers) configured and it's equal to `http` for this request.

**Comment by lovasoa** [comment] 2022-01-08 21:14
Is there a reason for that ? In what case is it useful to have a $page.url that is not the actual URL of the page ?

**Comment by Conduitry** [comment] 2022-01-09 01:43
We don't have access to the actual URL of the page unless there's a header that says what the protocol is. The Node adapter just serves over HTTP and you generally have an HTTPS proxy in front of that in production.

You can also override the protocol for all requests with svelte.config.js if you don't want to have a header sent during testing of the producing build.

**Comment by benmccann** [comment] 2022-01-09 02:12
I wonder if we can update it to use `:scheme` and `:authority` if the user is on HTTP/2?

For reference, it's handled here: https://github.com/sveltejs/kit/blob/dfb3bf57f632cb14c159836a0bdfde6a1cdd373e/packages/kit/src/core/build/build_server.js#L101

**Comment by lovasoa** [comment] 2022-01-09 08:40
But, whatever is used on the server, when my page renders on the client, it has access to the current URL, doesn't it? Couldn't it just read window.location on the client?

**Comment by dreitzner** [comment] 2022-01-10 14:20
for reference `window.location.protocol`

https://developer.mozilla.org/en-US/docs/Web/API/Location/protocol

**Comment by nhe23** [comment] 2022-01-12 22:35
After the first client-side navigation $page.url.origin is set correctly. So there is not really an issue on the client-side. However the first render comes from the server and therefore it is set to https (unless protocol header is set). 
It would be possible to pass an optional protocol property with the request object here: 
https://github.com/sveltejs/kit/blob/dfb3bf57f632cb14c159836a0bdfde6a1cdd373e/packages/kit/src/core/build/build_server.js#L88
The req object in the node-adapter is aware of its protocol (via [req.socket.getPeerCertificate()](https://nodejs.org/api/http.html#messagesocket) which is only set if https is used) so it could pass it to the render function.
Thoughts on this proposal?

**Comment by Conduitry** [comment] 2022-01-12 22:56
I don't think that would still work when a reverse proxy is providing the HTTPS. The output from the Node adapter always serves over HTTP and relies on another party for the encryption.

**Comment by nhe23** [comment] 2022-01-12 23:45
That's a valid point. So it does not make any sense to change anything on how the origin is set on the server-side.
However we could overwrite the protocol in the start function of the renderer, right here:
https://github.com/sveltejs/kit/blob/e881c7c57a3b136f92eba3aaef8952b11591a8e1/packages/kit/src/runtime/client/renderer.js#L162-L163 

like this
```diff
    // url.hash is empty when coming from the server
    url.hash = window.location.hash;
+   url.protocol = window.location.protocol;
```
This way $page.url.origin would be correct as soon as the start function has run. If no one is against this solution I'll create a PR tomorrow.

**Comment by nhe23** [comment] 2022-01-13 19:11
As @Rich-Harris pointed out in https://github.com/sveltejs/kit/pull/3318#issuecomment-1012179107 overwriting the protocol in the client is not desirable behaviour because it does not really fix the issue which is the protocol being incorrect in the server render. If needed the protocol should be configured by either [setting the header](https://kit.svelte.dev/docs#configuration-headers) or by directly [configuring the protocol](https://kit.svelte.dev/docs#configuration-protocol).

> This makes testing the compiled production application locally much more difficult. It has happened to me multiple times that the production build broke things that were working in dev mode, so I don't think it's reasonable to just skip testing the production build.

You could either run your tests with the production-built server behind a proxy that sets `x-forwarded-proto: http` or use a workflow like this: 
Build (with protocol set to http in svelte.config) -> test locally -> rebuild (with protocol set to https) -> deploy

Because changing the current behaviour is not desired we could add some information about this in the $app/stores section in the documentation.

**Comment by lovasoa** [comment] 2022-01-13 22:44
> As @Rich-Harris pointed out in #3318 (comment) overwriting the protocol in the client is not desirable behaviour because it does not really fix the issue which is the protocol being incorrect in the server render. 

I understand where he comes from, but still think that fixing the bug partially is better than not fixing it at all. There is no reason for `$page.url` to be incorrect on the client side other than matching the bug of the server side. 

> You could either run your tests with the production-built server behind a proxy that sets x-forwarded-proto: http or use a workflow like this:
> Build (with protocol set to http in svelte.config) -> test locally -> rebuild (with protocol set to https) -> deploy

How likely do you think it is that sveltekit users will follow a workflow like that ? Will **you** test your applications like that ? I don't think people are going to jump through these hoops to work around a bug in sveltekit. Either people will skip testing the build altogether, or they will get used to the bug and ignore it during testing...

**Comment by benmccann** [comment] 2022-01-13 22:57
there's no reason for it to be wrong on the server either, but y'all keep ignoring my great solution to that :rofl:  https://github.com/sveltejs/kit/issues/3248#issuecomment-1008213529

**Comment by nhe23** [comment] 2022-01-13 23:05
I'll try that out ... totally missed your comment 😄

**Comment by lovasoa** [comment] 2022-01-13 23:10
I think `svelte-kit build && node build` runs an HTTP1.1 server, doesn't it ?

**Comment by nhe23** [comment] 2022-01-13 23:26
Currently it is on HTTP1.1 ... but Polka supports HTTP2: https://github.com/lukeed/polka/issues/162 
I'll try that out and if it works I'll update my PR as this would be a much cleaner solution.

**Comment by benmccann** [comment] 2022-01-18 05:45
Does that stop us? If the site is not running via TLS (i.e. `:scheme` is missing) then we set the protocol to `http`. That seems like it'd still solve this issue

**Comment by lovasoa** [comment] 2022-01-18 09:01
Often, the node server is running over HTTP, but a reverse proxy serves the application to the final user as HTTPS. But I do agree that if we are running over HTTP and there is no [header hinting](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) that the connection to the end user was over HTTPS, we should assume HTTP, not HTTPS.

**Comment by nhe23** [comment] 2022-01-18 21:07
@benmccann Yes it does. The browser won't connect to a server that is on HTTP/2 and not secured. So it would not be possible to test an app, that was built with adapter-node with HTTP/2, locally. Or am I missing something?

**Comment by dreitzner** [comment] 2022-01-19 06:39
Maybe we can setup automatic TLS at least on dev?

**Comment by benmccann** [comment] 2022-01-19 21:09
Closing per the comment here: https://github.com/sveltejs/kit/pull/3318#issuecomment-1016847365

**Closed by benmccann** 2022-01-19 21:09 UTC

**Comment by wvhulle** [comment] 2022-04-06 14:19
I am sorry but I couldn't follow the technical details of the discussion. How do I explicitly set the headers to http so that my server serves http?

**Comment by omeryousaf** [comment] 2024-07-22 21:00
Just to let anyone who arrives here know there is a way mentioned in the docs https://kit.svelte.dev/docs/adapter-node#environment-variables-origin-protocolheader-hostheader-and-port-header to force sveltekit to recognise that the application is running over http.
