### ISSUE TITLE
{data.something} is reactive with streaming and processing in +layout.js but {@html data.something} is not

### ISSUE THREAD

**Issue by kvetoslavnovak** [sveltejs/kit#12045] opened 2024-03-27 21:13 UTC
### Describe the bug

I am fetching data. Smaller ones using standard way, bigger ones using streaming.  The data are in html format. In +layout.js I am adding id attributes to paragraphs. With client router everything work fine. But if I first load the relevant page {or reload this page) the id attributes are there when displayed like this {data.something}  but not like this  {@html data.something} .

So the data.something is processed in +layout.js and refreshes correctly but no in case when you show them with {@html ...} tag:/

The bug is very strange. The example hereinder is reproduction examplel,  I need to solve this bug in much bigger and compliacted application. Also cannot avodi using data in html format as they are form external api.

### Reproduction

https://github.com/eurlexa/SvelteKit--html-bug

The bug  in matter is shown in  src/routes/stream/+page.svelte. If you realod this page the bug will ocure.
```svelte
<h2>minimalData</h2>
{@html data.minimalData}
{data.minimalData}
```

`{data.minimalData}` is refreshed with id attributes but `{@html data.minimalData}` is not and id attributes are missing.
You can also see that 	`$: console.log(data);` has refreshed data as well.

`{@html hugeData}` which is streamed has all id attributes added correctly as well.

### System Info

```Shell
{
	"name": "streaming",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"lint": "prettier --check . && eslint .",
		"format": "prettier --write ."
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "^3.0.0",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^3.0.0",
		"@types/eslint": "^8.56.0",
		"eslint": "^8.56.0",
		"eslint-config-prettier": "^9.1.0",
		"eslint-plugin-svelte": "^2.35.1",
		"prettier": "^3.1.1",
		"prettier-plugin-svelte": "^3.1.2",
		"svelte": "^4.2.7",
		"vite": "^5.0.3"
	},
	"type": "module"
}

Chromium browser, Pop!_OS, VSCode
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment] 2024-04-07 05:29
Closing as duplicate of https://github.com/sveltejs/svelte/issues/8213

**Closed by gtm-nayan** 2024-04-07 05:29 UTC
