### ISSUE TITLE
Site: cannot click on scroll bar on large screens in docs

### ISSUE THREAD

**Issue by dangelomedinag** [sveltejs/kit#11315] opened 2023-12-14 16:10 UTC
### Describe the bug

inside https://kit.svelte.dev/docs on a large screen the 'ON THIS PAGE' section seems to cause you to not be able to click on the scroll bar.

![Grabación-2023-12-14-124808](https://github.com/sveltejs/kit/assets/64056830/35470cbf-6259-4336-88d3-e7981424fd0f)

### Reproduction

none

### System Info

```Shell
windows 11
Chrome Versión 120.0.6099.109
Edge Versión 120.0.2210.61
```

### Severity

serious, but I can work around it

**Comment by AdrianGonz97** [comment] 2023-12-14 19:02
I'm able to reproduce this issue when the viewport is sized from 1201px - 1450px in width. From 1451px and greater the issue goes away. 

I'm on Windows 11 and can reproduce on both Edge 120 and Brave 1.61.101

**Comment by dangelomedinag** [comment] 2023-12-14 19:15
@Conduitry  From a screen width of >1200px the problem occurs, as mentioned @AdrianGonz97

**Comment by eltigerchino** [comment] 2024-11-19 07:56
Closing this since the website got remade

**Closed by eltigerchino** 2024-11-19 07:56 UTC
Labels: documentation
