### ISSUE TITLE
In adapter-netlify split:true config is breaking SSR and other things.

### ISSUE THREAD

**Issue by brittneypostma** [sveltejs/kit#4872] opened 2022-05-11 19:15 UTC
### Describe the bug

When `split: true` is enabled in the `svelte.config.js` for `adapter-netlify`, SSR routes when navigated to with client side navigation gets a 404. The endpoint route will work on refresh, but the todo page goes to a Netlify 404 page does not exist skipping the `__error.svelte` route.

### Reproduction

Repo of demo app with `adapter-netlify`: https://github.com/brittneypostma/test-ssr-split

Preview deploy of site with `split: false` and `__error.svelte` working: https://627c04fe0cebc30008f3f36b--test-ssr-split.netlify.app/endpoint

Preview deploy of site with `split: true` and `__error.svelte` not catching on /todos refresh: https://627c046d20bc620009be8eef--test-ssr-split.netlify.app/endpoint

### Logs

```shell
`GET /endpoint/__data.json 404`
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 127.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox Developer Edition: 101.0
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.40 
    @sveltejs/adapter-netlify: 1.0.0-next.56 => 1.0.0-next.56 
    @sveltejs/kit: next => 1.0.0-next.326 
    svelte: ^3.46.0 => 3.48.0 
```

### Severity

serious, but I can work around it

### Additional Information

Only workaround is to turn off split, which isn't ideal.

**Comment by Rich-Harris** [comment] 2022-05-11 19:50
Ah... yep. This is an unanticipated problem of introducing page endpoints — the platform-level router won't execute the `/foo` function for `/foo/__data.json`, because it doesn't think it's a match. In Netlify terms, this line...

https://github.com/sveltejs/kit/blob/82cd1d7aa063a72d21ce1657b096796ff9502805/packages/adapter-netlify/index.js#L213

...probably needs to be accompanied by one with the `__data.json` suffix.

Currently that would mean adding that redirect for all routes, regardless of whether a given route a) is a page or b) has a corresponding endpoint. Ideally the `route` in `builder.createEntries((route) => {...})` would expose that information. It would be better still if adapters didn't need to be aware of this at all, though I'm not quite sure what that would look like.

A broader point: we really should have some e2e tests that would make it easier to catch these sorts of things.

**Comment by ericapisani** [comment] 2022-06-07 20:39
Happy to try and tackle this. 

From initial testing of the fix that Rich had suggested, it looks like a bit of a timing/race condition issue is at play as well at
https://github.com/sveltejs/kit/blob/6ca3508cd25197d9d57e509ea1196cc6d31dbafc/packages/adapter-netlify/index.js#L180

where the Promise returned by `createEntries` was completing before the entries for `todos` were pushed onto the `redirects` array and the array written to the `build/redirects` file.

> Currently that would mean adding that redirect for all routes, regardless of whether a given route a) is a page or b) has a corresponding endpoint. Ideally the route in builder.createEntries((route) => {...}) would expose that information.

From what I was able to find in the docs it looks like the `type` property for the `route` parameter within `builder.createEntries` would be either ['page' or 'endpoint'](https://kit.svelte.dev/docs/types#additional-types-routedefinition) - are there other values that `type` could potentially be that are  undocumented and that could be seen in `routes`?

If so, I can add some code to explicitly check for `page` or `endpoint` when adding the `__data.json` route, but at least from what I can see it seems like it's a safe assumption to make that the `route` will either be a `page` or an `endpoint`.

**Comment by brittneypostma** [comment] 2022-06-24 17:38
Could we open this back up? It looks like we are still breaking something along the way. I upgraded the [old site and it still 404's](https://test-ssr-split.netlify.app/endpoint), but a [new SvelteKit site gets a 500 error](https://svelte-split-ssr-test.netlify.app/endpoint) on those SSR routes. On a client side refresh, I can load the endpoint route on the "old" upgraded site, but the new one only gets a 500.

**Comment by winston0410** [comment] 2022-07-03 16:44
Any update on the issue? I am having the same issue, getting 404 even when I havnt set `split: true`. Basically this prevent running Sveltekit on Netlify right now.

**Comment by winston0410** [comment] 2022-07-04 17:38
@ericapisani  I have a repo to reproduce this here, I hope it will be helpful to you: https://github.com/winston0410/netlify-repo

**Comment by ericapisani** [comment] 2022-07-04 17:45
@brittneypostma 

> It looks like we are still breaking something along the way. I upgraded the [old site and it still 404's](https://test-ssr-split.netlify.app/endpoint)

I've forked the old test site that you had created and after [upgrading the version of @sveltejs/adapter-netlify to `1.0.0-next.65`](https://github.com/brittneypostma/test-ssr-split/compare/main...ericapisani:test-ssr-split:main), the site works correctly (no 404s or 500s when navigating to `/todos` or `/endpoints` pages, either directly or through client side navigation).

Deployed test site can be found [here](https://ep-svelte-2.netlify.app/)

If that site continues to experience issues with that upgrade, could you please specify what steps you're taking to reproduce error?

> ...a [new SvelteKit site gets a 500 error](https://svelte-split-ssr-test.netlify.app/endpoint) on those SSR routes

I've also [forked](https://github.com/ericapisani/svelte-split) the new SvelteKit site that you mentioned above, and it appears that the 500 error that you're mentioning is due to missing import. In [this file](https://github.com/brittneypostma/svelte-split/blob/3032425ef72c433124777aa6dce880e5c25907cb/src/hooks.js#L5) the following line is throwing a TypeError:

```
event.locals.userid = cookies['userid'] || crypto.randomUUID();
```

and it's due to `crypto` not being imported. After importing and redeploying that test site [appears to work as expected](https://ep-svelte-split.netlify.app/)

@winston0410 I was just going to ask about a repro project 😄 Thank you so much, I'll take a look now

**Comment by ericapisani** [comment] 2022-07-04 18:01
@winston0410 Just deployed the repro project you had provided by following the instructions in the README, and it appears to be [deploying correctly](https://ep-winston-repro.netlify.app/) with no 404 on the home page - is there a step that I'm missing to reproduce the error?

**Comment by winston0410** [comment] 2022-07-04 18:05
@ericapisani  Have you set `split: false` again? I think I have set it back to true, to verify it can deploy on my final commit, maybe that's why it deployed correctly

https://github.com/winston0410/netlify-repo/commit/aeccfd3594d311f3a7e4578768eac8336580d5fa

**Comment by ericapisani** [comment] 2022-07-04 18:14
@winston0410 Ah, that seems to have done the trick, thank you! Will continue investigating 🕵🏻‍♀️

**Comment by ericapisani** [comment] 2022-07-04 18:27
@winston0410 I think this is a cache issue of some kind. When I built and deployed the project with `split: true` and then changed it back to `false` without deleting the `build` directory, that's when I  encounter the 404 error.

When I removed the `build` directory between configuration changes and then run `ntl deploy --build --prod` things worked as expected. I've confirmed that all of the below scenarios deploy and run successfully:

**Test 1: Defaults**
```
adapter: adapter(),
```

**Test 2: Explicitly define default values**
```
adapter: adapter({
	edge: false,
	split: false
}),
```

**Test 3: Set split to true**
```
adapter: adapter({
	edge: false,
	split: true
}),
```

Would you mind giving that a try (deleting the `build` directory) and see if that resolves your issue?

**Comment by winston0410** [comment] 2022-07-04 20:35
@ericapisani I have just tried it again, and cache is the issue, that's a tricky one to catch! And I can confirm that after I have removed all the cache, `split:true` would work

**Comment by Rich-Harris** [comment] 2022-07-20 01:21
It sounds like we can close this again — thanks all

**Closed by Rich-Harris** 2022-07-20 01:21 UTC
Labels: bug, pkg:adapter-netlify, breaking change
