### ISSUE TITLE
adapter-static doesn't work with dynamic routes

### ISSUE THREAD

**Issue by pjebs** [sveltejs/kit#4278] opened 2022-03-09 10:07 UTC
### Describe the bug

SvelteKit built using adapter-static with dynamic routes simply does not work on S3 (static hosting) and github pages.

When you start your site's journey from `/` and then navigate using links to a dynamic route (i.e. /s/x/y), it works.

However if you directly try and go to `/s/x/y` (or alternatively refresh the page), you get a 404 page.

Is there any way to make the site work on s3 or github pages?
Or is dynamic routing with static-adapter not feasible?
**Perhaps an option to make sveltekit use `#`-based routing.**

### Reproduction

Create any site with dynamic routes and run it on s3.

### System Info

```shell
s3
```

### Severity

blocking all usage of SvelteKit

**Comment by PH4NTOMiki** [comment] 2022-03-09 10:39
I found this https://dev.to/alexeyromanchenko/how-to-deploy-spa-as-a-static-website-using-aws-s3-1adg and this https://medium.com/@P_Lessing/single-page-apps-on-aws-part-1-hosting-a-website-on-s3-3c9871f126 and this just by googling S3 SPA.
You can probably use something from those resources.

**Comment by PH4NTOMiki** [comment] 2022-03-09 11:00
As for the Github Pages, natively they don't support SPAs, but there is hacky workaround https://github.com/rafgraph/spa-github-pages
essentially you create `404.html` file inside static folder with this content:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Single Page Apps for GitHub Pages</title>
    <script type="text/javascript">
      // Single Page Apps for GitHub Pages
      // MIT License
      // https://github.com/rafgraph/spa-github-pages
      // This script takes the current url and converts the path and query
      // string into just a query string, and then redirects the browser
      // to the new url with only a query string and hash fragment,
      // e.g. https://www.foo.tld/one/two?a=b&c=d#qwe, becomes
      // https://www.foo.tld/?/one/two&a=b~and~c=d#qwe
      // Note: this 404.html file must be at least 512 bytes for it to work
      // with Internet Explorer (it is currently > 512 bytes)

      // If you're creating a Project Pages site and NOT using a custom domain,
      // then set pathSegmentsToKeep to 1 (enterprise users may need to set it to > 1).
      // This way the code will only replace the route part of the path, and not
      // the real directory in which the app resides, for example:
      // https://username.github.io/repo-name/one/two?a=b&c=d#qwe becomes
      // https://username.github.io/repo-name/?/one/two&a=b~and~c=d#qwe
      // Otherwise, leave pathSegmentsToKeep as 0.
      var pathSegmentsToKeep = 0;

      var l = window.location;
      l.replace(
        l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
        l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
        l.pathname.slice(1).split('/').slice(pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
        (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
        l.hash
      );

    </script>
  </head>
  <body>
  </body>
</html>
```

and in the `app.html` you add this before `%svelte.body%` (that's really important):
```html
<script>
      (function(l) {
        if (l.search[1] === '/' ) {
          var decoded = l.search.slice(1).split('&').map(function(s) { 
            return s.replace(/~and~/g, '&')
          }).join('?');
          window.history.replaceState(null, '',
              l.pathname.slice(0, -1) + decoded + l.hash
          );
        }
      }(window.location))
</script>
```

**Comment by PH4NTOMiki** [comment] 2022-03-09 11:06
Github Pages solution is a really hacky one, so if you can help it, don't use it. 
And you're probably better of with Cludflare Pages, Vercel, Netlify.
And if you want to have something like S3 (and cheaper) then you can use BunnyCDN (read this article https://bunny.net/blog/host-your-frontend-applications-on-the-edge/ on their blog)
(I don't have any affiliation with them, I just use them)

And for all of these you DO need to use `fallback` option for adapter config.
Hope that helps

**Comment by pjebs** [comment] 2022-03-09 11:19
Maybe sveltekit or static-adapter should have an option that will make it use `#` based routing. That will solve the problem for most people..

**Comment by PH4NTOMiki** [comment] 2022-03-09 11:23
> Maybe sveltekit or static-adapter should have an option that will make it use `#`-based routing. That will solve the problem for most people..

That's really really bad for SEO, because the normal SPA Google can actually render, but if it's using hash routing it can't figure out there are any other page except index/homepage.

**Comment by pjebs** [comment] 2022-03-09 11:25
@PH4NTOMiki How does the fallback option in `static-adapter` help since if you go to a dynamic route, the `/index.html` page is not available to display the fallback option.

**Comment by pjebs** [comment] 2022-03-09 11:27
Maybe by now, Google understands #-based routing since it's so common, that they can successfully interpret it like they do for `/` based routing.

**Comment by pjebs** [comment] 2022-03-09 11:33
yes the server can be configured to fallback, but how does static-adapter do anything about it's fallback option?

**Comment by PH4NTOMiki** [comment] 2022-03-09 11:44
`adapter-static` (not static-adapter) creates file with a file name that was set in `fallback` option so that you can configure a server to fall back to that file if the specific route is unavailable.

**Comment by pjebs** [comment] 2022-03-09 11:49
Aha. Thanks for explaining.

**Comment by benmccann** [comment] 2022-03-09 14:58
You need to set `trailingSlash: 'never'` if you're using S3. Closing as duplicate of https://github.com/sveltejs/kit/issues/3852

**Closed by benmccann** 2022-03-09 14:58 UTC

**Comment by pjebs** [comment] 2022-03-09 21:38
@PH4NTOMiki can you explain the significance of trailingslash = never?

**Comment by benmccann** [comment] 2022-03-10 04:29
https://kit.svelte.dev/docs/configuration#trailingslash
https://kit.svelte.dev/docs/adapters#supported-environments-static-sites

**Comment by pjebs** [comment] 2022-03-17 23:30
@PH4NTOMiki I set a fallback to `404.html`. I can see that a `404.html` file is generated, but the `index.html` page is no longer generated, so the site no longer works. It just displays the directory listing.

**Comment by pjebs** [comment] 2022-03-18 04:23
@PH4NTOMiki Can you help me diagnose this issue: https://github.com/sveltejs/kit/issues/4378
