### ISSUE TITLE
Upgrade issues from 1.0.0-next.208 to 1.0.0-next.303 

### ISSUE THREAD

**Issue by krr9** [sveltejs/kit#4470] opened 2022-03-31 01:08 UTC
### Describe the bug

When I upgraded my app to use version 1.0.0-next.303 (from next.208) I see the following error.

`✘ [ERROR] No matching export in "browser-external:stream" for import "Readable"`
 

### Reproduction

My app is working fine on version 208. The upgrade to version 303 causes the issue mentioned.

### Logs

```shell
> svelte-kit dev


  SvelteKit v1.0.0-next.303

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


✘ [ERROR] No matching export in "browser-external:stream" for import "Readable"

    node_modules/@sveltejs/kit/dist/node.js:1:9:
      1 │ import { Readable } from 'stream';
        ╵          ~~~~~~~~

6:00:59 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@sveltejs/kit/dist/node.js:1:9: ERROR: No matching export in "browser-external:stream" for import "Readable"
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 122.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /opt/homebrew/bin/node
    npm: 8.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.28 => 1.0.0-next.29 
    @sveltejs/kit: 1.0.0-next.303 => 1.0.0-next.303 
    @sveltejs/svelte-virtual-list: ^3.0.1 => 3.0.1 
    svelte: ^3.46.4 => 3.46.5
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment] 2022-03-31 03:35
We need a reproduction to investigate this.

**Comment by krr9** [comment] 2022-03-31 16:13
The issue can be replicated in this repo here 
https://github.com/krr9/tempapp

The issue is not seen when the sveltekit version is changed to next.208

**Comment by mcmxcdev** [comment] 2022-05-23 12:48
This is also still reproducible with the currently latest kit version, e.g. `1.0.0-next.338`

It seems to happen because `stream` is a node built-in library that is attempted to be used in browser context, similar issue:  https://github.com/aws-amplify/amplify-js/issues/9639

**Comment by benmccann** [comment] 2022-07-19 16:41
@krr9 the code related to streaming has changed a lot recently. Could you let us know if you're still seeing this? If so, could you push an update to your reproduction to update it to the latest version of SvelteKit?

**Comment by dummdidumm** [comment] 2022-07-20 09:56
I just had a quick look at the repo. After upgrading to the latest version and adding a `vite.config.js` and adjusting `app.html` I don't see the mentioned error anymore. But there are other errors coming from libraries but they seem unrelated. Therefore closing this issue. If this error persists in some other form, please post a minimum reproducible here or in a new issue.

**Closed by dummdidumm** 2022-07-20 09:56 UTC
Labels: bug, awaiting submitter
