### ISSUE TITLE
Add support for Vite 5

### ISSUE THREAD

**Issue by tonprince** [sveltejs/kit#11062] opened 2023-11-17 08:56 UTC
### Describe the problem

Please add support for Vite 5. When updating to version 5, I got an error when running npm i with the latest Sveltekit version:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @sveltejs/kit@1.27.6
npm ERR! Found: vite@5.0.0
npm ERR! node_modules/vite
npm ERR!   dev vite@"^5.0.0" from the root project
npm ERR!   peerOptional vite@"^3.0.0 || ^4.0.0 || ^5.0.0" from vitefu@0.2.5
npm ERR!   node_modules/vitefu
npm ERR!     vitefu@"^0.2.4" from @sveltejs/vite-plugin-svelte@2.5.2
npm ERR!     node_modules/@sveltejs/kit/node_modules/@sveltejs/vite-plugin-svelte
npm ERR!       @sveltejs/vite-plugin-svelte@"^2.5.0" from @sveltejs/kit@1.27.6
npm ERR!       node_modules/@sveltejs/kit
npm ERR!         dev @sveltejs/kit@"^1.27.6" from the root project
npm ERR!         1 more (@sveltejs/adapter-vercel)
npm ERR!       1 more (@sveltejs/vite-plugin-svelte-inspector)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^4.0.0" from @sveltejs/kit@1.27.6
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"^1.27.6" from the root project
npm ERR!   peer @sveltejs/kit@"^1.5.0" from @sveltejs/adapter-vercel@3.0.3
npm ERR!   node_modules/@sveltejs/adapter-vercel
npm ERR!     dev @sveltejs/adapter-vercel@"^3.0.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vite@4.5.0
npm ERR! node_modules/vite
npm ERR!   peer vite@"^4.0.0" from @sveltejs/kit@1.27.6
npm ERR!   node_modules/@sveltejs/kit
npm ERR!     dev @sveltejs/kit@"^1.27.6" from the root project
npm ERR!     peer @sveltejs/kit@"^1.5.0" from @sveltejs/adapter-vercel@3.0.3
npm ERR!     node_modules/@sveltejs/adapter-vercel
npm ERR!       dev @sveltejs/adapter-vercel@"^3.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Describe the proposed solution

Update Sveltekit and adapters to support latest release of Vite 5.

### Importance

nice to have

**Comment by vnphanquang** [comment] 2023-11-18 16:33
With `pnpm` I did not have the reported peer-dependency problem. However, I found another issue related to vite 5 and will list it down here, but let me know if a separate issue is better.

## Describe the problem

Paths for font assets are incorrect in build output. For example: 

In vite 4: `/_app/immutable/assets/font.woff2` (correct)
In vite 5: `/_app/immutable/assets/nodes/font.woff2` (incorrect)

Note the added `nodes` directory. The actual font file still lives at `/_app/immutable/assets/` and not in `nodes`. This nested `nodes` folder seems to be new in vite 5, it nows hosts all the built css.

## Reproduction

1. Bootstrap the demo project with `npm create svelte@latest` (use Svelte 4, not 5)
2. Upgrade to vite 5 and install dependencies
3. Build `pnpm build`
4. Preview `pnpm preview`
5. Go to `/about` page
6. Verify in network tab, fonts files are 404

**Comment by eltigerchino** [comment] 2023-11-19 14:57
> With `pnpm` I did not have the reported peer-dependency problem. However, I found another issue related to vite 5 and will list it down here, but let me know if a separate issue is better.
> 
> ## Describe the problem
> Paths for font assets are incorrect in build output. For example:
> 
> In vite 4: `/_app/immutable/assets/font.woff2` (correct) In vite 5: `/_app/immutable/assets/nodes/font.woff2` (incorrect)
> 
> Note the added `nodes` directory. The actual font file still lives at `/_app/immutable/assets/` and not in `nodes`. This nested `nodes` folder seems to be new in vite 5, it nows hosts all the built css.
> 
> ## Reproduction
> 1. Bootstrap the demo project with `npm create svelte@latest` (use Svelte 4, not 5)
> 2. Upgrade to vite 5 and install dependencies
> 3. Build `pnpm build`
> 4. Preview `pnpm preview`
> 5. Go to `/about` page
> 6. Verify in network tab, fonts files are 404 (there should also be console logs)

Thanks for reporting this. Can you please open a new issue with a downloadable repository?

**Comment by vnphanquang** [comment] 2023-11-20 02:46
@eltigerchino will do, should this be a bug or a feature request? I feel that it's both so not sure what to do...

**Comment by eltigerchino** [comment] 2023-11-20 02:47
> @eltigerchino will do, should this be a bug or a feature request? I feel that it's both so not sure what to do...

A bug request template should do

**Comment by vnphanquang** [comment] 2023-11-20 02:57
@eltigerchino https://github.com/sveltejs/kit/issues/11085 please let me know if any additional info is needed. Thanks :pray:

**Comment by mihaipoenaru** [comment] 2023-11-21 13:06
Can confirm I have the same issue. I'm not sure if vite 5 has any spicy updates except for performance, but it is a bit of an inconvenience to undo its upgrade every time I run an `ncu -u`

**Comment by Daschi1** [comment] 2023-11-21 14:35
> Can confirm I have the same issue. I'm not sure if vite 5 has any spicy updates except for performance, but it is a bit of an inconvenience to undo its upgrade every time I run an `ncu -u`

As a temporary fix for that, you can use `ncu -u -x vite`, which will exclude vite from the dependency upgrade.

**Comment by microdou** [comment] 2023-11-21 20:56
@mihaipoenaru You may create a `.ncurc` file to mitigate the inconvenience :)

```json
{
  "reject": [
    "vite"
  ]
}
```

**Comment by xmlking** [comment] 2023-11-21 21:22
with **Vite 5**,  when I `build/preview` prerender pages are missing CSS lines in HTML

when I switch back, to Vite 4.5.0 there are getting generated. e.g., 
```html
		<link href="./_app/immutable/assets/0.97e3f53f.css" rel="stylesheet">
		<link href="./_app/immutable/assets/ReloadPrompt.e3dfb3f1.css" rel="stylesheet">
		<link href="./_app/immutable/assets/3.aa8c5ae0.css" rel="stylesheet">
```

**Comment by jasperkelder** [comment] 2023-11-22 09:49
I'm using Bun as package manager and adapter-auto. Doing a local build and preview with Vite 5 causes no problems, but deployment to Vercel doesn't work right now:

bun install v1.0.13 (f5bf67bd)
 + vite@5.0.2
 9 packages installed [243.00ms]
error: linking esbuild: FileNotFound
Running "bun run build"
$ vite build
✘ [ERROR] Cannot start service: Host version "0.18.20" does not match binary version "0.19.7"
1 error
failed to load config from /vercel/path0/vite.config.ts
error during build:
Error: The service was stopped: write EPIPE

Switching Vercel's default Node.js 18.x to their 20.x beta didn't work either.

**Comment by sonyarianto** [comment] 2023-12-06 09:56
I just do `ncu --peer -u` it will ignore incompatible updates (based on peer dependencies)

**Comment by benmccann** [comment] 2023-12-10 19:32
Support for Vite 5 has been merged and will be released as part of SvelteKit 2 soon. Subscribe to notifications on https://github.com/sveltejs/kit/pull/11161 if you'd like to be notified when it is released. We'll also put up a blog post at svelte.dev/blog

**Closed by benmccann** 2023-12-10 19:32 UTC
Labels: vite

**Comment by tonprince** [comment] 2023-12-15 02:46
Thanks for the fast support of Vite 5. I just tested my app with the latest Sveltekit version and it works like a charm.

**Comment by sonyarianto** [comment] 2023-12-15 18:04
me too, my website now already with latest SvelteKit 2
