### ISSUE TITLE
From 1.0.0-next.71 to 1.0.0-next.72, warnings in console

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#986] opened 2021-04-12 22:17 UTC
**Describe the bug**
From `1.0.0-next.71` to `1.0.0-next.72`:

now I have these warning in console:

```
<Routes> received an unexpected slot "default".
<Routes> was created with unknown prop 'status'.
<Routes> was created with unknown prop 'error'.
```

![image](https://user-images.githubusercontent.com/41120635/114468405-b3bc1600-9beb-11eb-8768-401ef01e685c.png)

The code is the same.

**Comment by Conduitry** [comment] 2021-04-12 22:28
Duplicate of #981.

**Closed by Conduitry** 2021-04-12 22:28 UTC
