### ISSUE TITLE
Brand new project wants tailwindcss

### ISSUE THREAD

**Issue by pierresaid** [sveltejs/kit#2099] opened 2021-08-04 22:25 UTC
### Describe the bug

A brand new Svelt kit project created with npm init svelte@next my-app wants tailwind to run

### Reproduction

npm init svelte@next my-app
cd my-app
npm install
npm run dev -- --open

### Logs

```shell
Error: Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'
Require stack:
- /home/{userdir}/{path}/my-app/noop.js
```

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 24.39 GB / 24.92 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.1.0/bin/yarn
    npm: 7.16.0 - ~/.nvm/versions/node/v16.1.0/bin/npm
```

### Severity

serious, but I can work around it

**Comment by pierresaid** [comment] 2021-08-04 22:28
With further investigation it might be a problem with vite as I have the same problem with scaffolding a project with : 
npm init vite@latest

**Comment by Conduitry** [comment] 2021-08-04 22:39
The only place the text "tailwind" appears in this entire repo is in https://github.com/sveltejs/kit/blob/master/documentation/faq/80-integrations.md so this is highly unlikely to have anything to do with SvelteKit.

In any case, I can't reproduce this.

**Comment by benmccann** [comment] 2021-08-04 23:00
I'll go ahead and close this since it sounds like the issue is in Vite. Please file an issue over there. Thanks!

**Closed by benmccann** 2021-08-04 23:00 UTC
