### ISSUE TITLE
Broken +layout.server.js (1.0.0-next.409)

### ISSUE THREAD

**Issue by MajorBreakfast** [sveltejs/kit#5921] opened 2022-08-16 11:34 UTC
### Describe the bug

The data returned by `+layout.server.js` does not survive client side navigation

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-8owdvn

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.406 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.7
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment] 2022-08-16 11:36
Duplicate of #5904.

**Closed by Conduitry** 2022-08-16 11:36 UTC

**Comment by MajorBreakfast** [comment] 2022-08-16 11:39
@Conduitry Thx for the fast response. Would it be possible to adjust the title of the other issue? I'm not using `await parent()`, so I did not see that a similar issue has been reported already
