### ISSUE TITLE
Proper typing for `$page.data.session` just like `$session`?

### ISSUE THREAD

**Issue by jimjimjimhaha** [sveltejs/kit#6058] opened 2022-08-18 23:17 UTC
### Describe the problem

I feel like I'm missing something obvious. `$session` was removed in #5946 and the alternative proposed in #5883 is using layout load functions and retrieving the session info there and then returning it as part of the data; which I am doing, but I'm not sure how I should have proper typing for `$page.data.session`?! Previously I was declared the type of the session object in `app.d.ts`'s `App.Session`, and then just used the typed `$session` store everywhere, which was very convenient, I'm confused as to how I'm supposed to achieve something similar now?!

### Describe the proposed solution

I don't know, really

### Importance

i cannot use SvelteKit without it

**Comment by tcc-sejohnson** [comment] 2022-08-18 23:32
Closing as a duplicate of #5951. Read through the discussion there -- Rich is working on implementing this! :)

**Closed by tcc-sejohnson** 2022-08-18 23:32 UTC
