### ISSUE TITLE
Weird behavior with `page.query` change and `goto`

### ISSUE THREAD

**Issue by csangonzo** [sveltejs/kit#2785] opened 2021-11-12 09:52 UTC
### Describe the bug

I wanted to create a dropdown select in my navigation header, since I'll need this selected value as a global value used on the client and on the server as well I decided that I'll use a query param (if you have a good solution to create a global state that stays the same when refreshing the page and is available on the server and on the client without any woodoo stuff, please let me know :) ). So every time someone changes this value, the page has to refresh using this newly set id on the current page. First I tried with `$page.query.set('test',paramTest);`, since the documentation says:
> The load function is reactive, and will re-run when its parameters change, but only if they are used in the function. Specifically, if page.query, page.path, session, or stuff are used in the function, they will be re-run whenever their value changes. 

However I couldn't get the load function to rerun by changing the `page.query`, so I decided to pair it with `goto`. So now if I change (set) the query param and use `goto` afterwards it's fine.. except on every second click somehow.. I have a list of let's say four ids, if I'm on the first one (1) by default and I change it to the second (2), the load function runs and everything's fine, same for the third one (3), but if I continue, the fourth (4) one won't do anything, the load function won't run again. I can carry on with this and the first will run, the second won't, the third will and the fourth won't.
I have no idea why this happens, but it's kinda weird.

### Reproduction

I created a whole new sveltekit template with:
`npm init svelte@next my-app`
I added two extra files under `routes`:
`__layout.svelte`:

```html
<script>
    import { goto } from '$app/navigation';
    import { page } from '$app/stores';

    let paramTest = $page.query.get('test');
</script>

<nav>
    
	<a href="/">Home</a>
	<a href="/test">Test</a>

    <select 
    bind:value={paramTest}
    on:change={() => {
        $page.query.set('test',paramTest);
        goto(`?${$page.query.toString()}`);
    }}>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
    </select>
</nav>

<slot></slot>
```

`test.svelte`
```html
<script context="module">
	export async function load({ page}) {
        console.log('TEST LOAD',page.query.get('test'));
        const a = page.query.get('test');

        return {}
    }
</script>


<script lang="ts">
    import { page } from '$app/stores';
</script>


<p>
    This is a test page
    <br>
    Param: {$page.query.get('test')}
</p>
```

The even strangest part of this is that with the code below you can reproduce the issue:
```js
$page.query.set('test',paramTest);
goto(`?${$page.query.toString()}`);
```
but if I use it like this:
```js
let query = new URLSearchParams($page.query.toString());
query.set('test', paramTest);
goto(`?${query.toString()}`);
```
It works as expected. (thanks to this SO question: https://stackoverflow.com/questions/69606222/how-to-update-the-page-and-query-parameters-in-sveltekit/69837116 )

### Logs

```shell
[vite] connecting...
client.ts:52 [vite] connected.
test.svelte? [sm]:4 TEST LOAD 1
test.svelte:4 TEST LOAD 2
test.svelte:4 TEST LOAD 3
test.svelte:4 TEST LOAD 1
test.svelte:4 TEST LOAD 3
```

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 254.07 MB / 15.45 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 95.1.31.88
    Chrome: 95.0.4638.69
    Firefox: 94.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196 
    svelte: ^3.42.6 => 3.44.1
```

### Severity

serious, but I can work around it

**Comment by rmunn** [comment] 2021-11-13 06:23
I'm about 90% sure (haven't checked the code in detail yet) that you aren't supposed to actually **change** the value in the `$page` store. [The docs say](https://kit.svelte.dev/docs#modules-$app-stores) that "`page` is a **readable** store" (emphasis mine) "whose value reflects the object passed to load functions". There's nothing in Svelte-Kit's code that expects the value of the page store to change except when browser navigation happens, i.e. when the user clicks on a link or when you use `goto`.

The reason why using `goto` sometimes works and sometimes doesn't after you do `$page.query.set('foo', 'bar')` has to do with the internals of the Svelte-Kit code. I remember encountering something like this before, when someone modified an internal Svelte-Kit variable that it was expecting not to have modified (I think it had to do with derived stores). Can't find it now, but the behavior of working every other time (more or less) seems familiar to me.

But basically, you're supposed to treat the `$page.query` object as read-only; updating it will not only **not** change the query parameters in the browser, but it will also cause weird bugs as you're breaking an unwritten contract within Svelte-Kit's internal code (i.e., that the `$page.query` object will not be modified from outside). The actually supported way to change the query params of the URL is the same as the way to change *any* part of the URL: use `goto`.

In other words, of these two code snippets from your issue description, **this one is correct**:

```js
let query = new URLSearchParams($page.query.toString());
query.set('test', paramTest);
goto(`?${query.toString()}`);
```

And **this one is wrong**:

```js
$page.query.set('test',paramTest);
goto(`?${$page.query.toString()}`);
```

This is not a bug in Svelte-Kit, but it could be considered a bug report for the documentation since it seems the documentation could stand to be clearer. (And since I'm the one who wrote the bit of documentation you quoted — I recognize the phrasing — that's on me.) I won't close this issue yet since I still need to test it, but once I've tested that the issue only occurs when you use `$page.query.set()` which you're not supposed to do, I'll close this issue and open a new issue for a documentation update.

(Alternately, if you want to edit the issue title and change this to be a request for better documentation about `$page.query`, feel free to do so. I have access rights to close the issue and assign labels, but I'm not a member of the core team so I don't have access rights to edit your issue or its title. If you edit the issue and change it to a documentation issue, then that will save me time later since I won't have to close this issue and open a new one.)

**Comment by mohamadHarith** [comment] 2021-12-24 13:25
https://dev.to/mohamadharith/mutating-query-params-in-sveltekit-without-page-reloads-or-navigations-2i2b

**Comment by bluwy** [comment] 2021-12-24 13:38
As @rmunn mentioned, this is expected behaviour, and has been documented in #2811, so closing this.

**Closed by bluwy** 2021-12-24 13:38 UTC
Labels: documentation
