### ISSUE TITLE
kit and svelte are listed a devDependency in demos but needed for running build

### ISSUE THREAD

**Issue by iOiurson** [sveltejs/kit#1428] opened 2021-05-12 10:34 UTC
Once you built a project with `adapter-node`, `node build` does not work without `@sveltejs/kit` and `svelte` in `node_modules`.

```bash
Cannot find package '@sveltejs/kit' imported from /Users/Romain/Code/tutos/sveltekit-app/build/app.js
```

On the kit template projects (demo or skeleton), `@sveltejs/kit` and `svelte` are listed as `devDependencies`.
My understanding was that you should be able to run a project in production without any `devDependencies` installed.

Plus i thought that all prod `dependencies` were packaged by `rollup` (via `vite`) on build, which does not seem to be the case since we still have import such as
 
```js
// in build/app.js for DEMO APP
import cookie from "cookie";
```

I'm not sure why we should not keep `@sveltejs/kit` and `svelte` as `devDependencies`, but at the same time we currently need to have the corresponding folders in `node_modules`...

Am i missing something here ?

**Comment by Conduitry** [comment] 2021-06-08 20:13
Closing this as a duplicate of #1257. This should also be fixed by #1648.

**Closed by Conduitry** 2021-06-08 20:13 UTC
Labels: bug
