### ISSUE TITLE
Custom Loggers for Adapters

### ISSUE THREAD

**Issue by Pelps12** [sveltejs/kit#12640] opened 2024-09-02 18:22 UTC
### Describe the problem

When I do console.log in my backend (specifically Cloudflare Pages). I am restricted to the default logging tools the hosting service provides except I bring my own library and use a specific function to log the data. This can be hectic between local and prod environments. I would like this because Cloudflare Pages still doesn't have a persisted logging strategy.

### Describe the proposed solution

It would be nice if adapters could expose the Logger interface in a way that allows the developer to specify their logging implementation. I don't mind personally looking into it. I've been using SvelteKit for over 2 years.

### Importance

would make my life easier

**Comment by eltigerchino** [comment] 2024-10-22 06:28
closing as duplicate of https://github.com/sveltejs/kit/issues/2972

**Closed by eltigerchino** 2024-10-22 06:28 UTC
