### ISSUE TITLE
Subscribing to `page` store in `$layout.svelte` throws error

### ISSUE THREAD

**Issue by c-bandy** [sveltejs/kit#649] opened 2021-03-24 20:51 UTC
**Describe the bug**
Subscribing to the `page` in `$layout.svelte` throws an error.

**Logs**
![Screen Shot 2021-03-24 at 2 44 53 PM](https://user-images.githubusercontent.com/31383109/112381082-cbb90d80-8caf-11eb-8ddb-fc391a01d17e.png)

**To Reproduce**

Add this to the <script> block in `$layout.svelte`

```js
import { page } from "$app/stores";
page.subscribe(() => {});
```

**Expected behavior**
It should work!

**Stacktraces**

<details>
  <summary>Stack trace</summary>
<pre>
get_current_component@http://localhost:3000/node_modules/svelte/internal/index.mjs?v=e3e1bc30:649:15
getContext@http://localhost:3000/node_modules/svelte/internal/index.mjs?v=e3e1bc30:682:12
getStores@http://localhost:3000/.svelte/dev/runtime/app/stores.js:24:27
subscribe@http://localhost:3000/.svelte/dev/runtime/app/stores.js:50:17
instance/<@http://localhost:3000/src/routes/$layout.svelte?import:215:8
run@http://localhost:3000/node_modules/svelte/internal/index.mjs?v=e3e1bc30:18:12
mount_component/<@http://localhost:3000/node_modules/svelte/internal/index.mjs?v=e3e1bc30:1416:45
flush@http://localhost:3000/node_modules/svelte/internal/index.mjs?v=e3e1bc30:746:17
init@http://localhost:3000/node_modules/svelte/internal/index.mjs?v=e3e1bc30:1504:9
Root@http://localhost:3000/.svelte/dev/generated/root.svelte?import:574:7
createProxiedComponent@http://localhost:3000/node_modules/svelte-hmr/runtime/svelte-hooks.js:245:9
ProxyComponent@http://localhost:3000/node_modules/svelte-hmr/runtime/proxy.js:240:42
Proxy<Root>@http://localhost:3000/node_modules/svelte-hmr/runtime/proxy.js:340:11
start@http://localhost:3000/.svelte/dev/runtime/internal/start.js:409:15
async*start@http://localhost:3000/.svelte/dev/runtime/internal/start.js:811:17
@http://localhost:3000/:57:9
</pre>
</details>

**Information about your SvelteKit Installation:**
```
System:
  OS: macOS 11.2.3
  CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Memory: 3.25 GB / 32.00 GB
  Shell: 3.2.0 - /usr/local/bin/fish
Binaries:
  Node: 14.16.0 - /usr/local/bin/node
  Yarn: 1.22.10 - /usr/local/bin/yarn
  npm: 6.14.11 - /usr/local/bin/npm
Browsers:
  Chrome: 89.0.4389.90
  Firefox Developer Edition: 88.0
  Safari: 14.0.3
npmPackages:
  @sveltejs/kit: next => 1.0.0-next.58
  svelte: ^3.35.0 => 3.35.0
```

**Severity**
Blocking

**Comment by ivoberger** [comment] 2021-03-27 14:52
I had the same issue, fixed it by doing a browser check first. See here: https://github.com/ivoberger/ivoberger.com/blob/master/src/routes/%24layout.svelte#L11
Site is in production and everything seems to be working.

**Comment by c-bandy** [comment] 2021-03-30 00:54
> I had the same issue, fixed it by doing a browser check first. See here: https://github.com/ivoberger/ivoberger.com/blob/master/src/routes/%24layout.svelte#L11
> Site is in production and everything seems to be working.

Your workaround doesn't seem to work for me unfortunately

**Comment by Rich-Harris** [comment] 2021-04-02 21:42
Are you still experiencing this with the latest version? I can't reproduce it

**Comment by c-bandy** [comment] 2021-04-02 23:36
I can still reproduce this on the latest kit, however doing it like this seems to break:

```js
import { browser } from "$app/env"
import { onMount } from "svelte"

onMount(() => {
	if (browser) {
		page.subscribe(() => {})
	}
})
```

Should I update this issue or create a new one?

**Comment by Conduitry** [comment] 2021-04-02 23:42
That would be expected. To use the stores directly, you need to subscribe to the store synchronously during the initialization of the component (and not asynchronously later during mounting). If you want to be able to subscribe later, you need to grab the store synchronously by using `getStores` (like in Sapper). This is described in hhttps://kit.svelte.dev/docs#modules-app-stores

**Comment by c-bandy** [comment] 2021-04-02 23:50
OK! Shouldn't be too hard for me to adjust the logic then to fix this unrelated issue.

@ivoberger @alteredorange, does this work for you all on your end?

**Comment by ivoberger** [comment] 2021-04-03 08:04
Tinkered around with it a bit and while I had some odd behavioral at first (dynamic pages just weren't build) it now works reliably. I could subscribe to the `page` store without any checks around it.

**Comment by Rich-Harris** [comment] 2021-04-03 08:35
excellent, will close this, thanks

**Closed by Rich-Harris** 2021-04-03 08:35 UTC
Labels: bug
