### ISSUE TITLE
Can only call URL.toString on instances of URL

### ISSUE THREAD

**Issue by mattpilott** [sveltejs/kit#5112] opened 2022-05-29 23:20 UTC
### Describe the bug

Hola 👋

When using `new URL` in load(), Kit throws an error. I have gone back to find where this issue was introduced and it started with version 338, i suspect it was this merge https://github.com/sveltejs/kit/pull/4983

### Reproduction

https://github.com/mattpilott/sveltekit-repro-url-issue

Only change is in `routes/index`

```html
<script context="module">
   export async function load({ url }) {
      const nurl = new URL(url)
      nurl.searchParams.append('foo', 'bar')
      return {}
   }
</script>
```

### Logs

```shell
500

Can only call URL.toString on instances of URL
toString@[native code]
URL@[native code]
@http://localhost:3000/src/routes/index.svelte:36:22
asyncFunctionResume@[native code]
@http://localhost:3000/@fs/Users/Matt/Sites/lazay/.svelte-kit/runtime/client/start.js:989:37
asyncFunctionResume@[native code]
@http://localhost:3000/@fs/Users/Matt/Sites/lazay/.svelte-kit/runtime/client/start.js:1626:34
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 231.27 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /opt/homebrew/bin/node
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.1
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-vercel: 1.0.0-next.56 => 1.0.0-next.56 
    @sveltejs/kit: 1.0.0-next.345 => 1.0.0-next.345 
    svelte: ^3.48.0 => 3.48.0
```

### Severity

blocking an upgrade

### Additional Information

This is preventing me from leaving 338, thanks!!

**Comment by Conduitry** [comment] 2022-05-30 00:20
Duplicate of #5083. The issue is that the Proxy wrapping the URL doesn't support the `.toString()` method properly. You should be able to work around this in the meantime with `new URL(url.href)`.

**Closed by Conduitry** 2022-05-30 00:20 UTC
