### ISSUE TITLE
Do not run `load` function if in hook's `handle` I disabled ssr at all

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#3983] opened 2022-02-17 16:50 UTC
### Describe the problem

If I have:

- `hooks.ts`:

```ts
/** @type {import('@sveltejs/kit').Handle} */
export function handle({ event, resolve }) {
	return resolve(event, { ssr: false });
}
```

I should not have the below error in console:

```
window is not defined
```

if I don't use `if (browser) {}` in `context="module"`'s `load()` function.

### Importance

would make my life easier

**Comment by mrkishi** [comment] 2022-02-19 01:41
Are you sure `load()` is being called, as opposed to some import accessing `window` upon initialization?

Since `ssr` is a runtime option, the server has to bundle `load` in case it needs to be called. This means referenced imports can't be eliminated via tree-shaking. In turn, since the imports are still there, any side-effects should still happen.

As a quick test, the following worked as expected:

```js
export async function load({ load }) {
	window.blur();
	return {};
}
```

Let me know if I missed any other details from your environment that might cause the bug.

**Comment by frederikhors** [comment] 2022-02-19 08:24
> You need to await the resolve like this:
> 
> ```ts
> /** @type {import('@sveltejs/kit').Handle} */
> export async function handle({ event, resolve }) {
> 	return await resolve(event, { ssr: false });
> }
> ```

Are you sure about this?

From docs:

![image](https://user-images.githubusercontent.com/41120635/154793110-52f520a3-acce-4938-84f0-a20224db9bee.png)

**Comment by PH4NTOMiki** [comment] 2022-02-19 09:09
If you do anything else except return that resolve, then you have to use async/await, otherwise you don't have too

**Comment by PH4NTOMiki** [comment] 2022-02-19 09:10
And as far as the load problem goes, I'm also experiencing it, and I'll try to push PR for it, if I find where is the issue

**Comment by dummdidumm** [comment] 2022-02-19 09:13
Can someone please first provide an actual reproduction so we know what exactly you are talking about?

**Comment by antony** [comment] 2022-04-04 18:19
Closing this issue in the absence of a reproduction. Feel free to re-raise if a reproduction is created.

**Closed by antony** 2022-04-04 18:19 UTC
