### ISSUE TITLE
`svelte-kit build` should respect `vite.build.emptyOutDir`

### ISSUE THREAD

**Issue by kafwangure** [sveltejs/kit#1044] opened 2021-04-15 17:39 UTC
**Is your feature request related to a problem? Please describe.**
Building using `adapter-static`, files from the previous build are still in the build folder after a subsequent build. Vite has a [`build.emptyOutDir: true`](https://vitejs.dev/config/#build-emptyoutdir) default that svelte-kit seems to ignore.

**Describe the solution you'd like**
It would be nice if svelte-kit cleared the build directory, to avoid the build folder ballooning in size when doing multiple local builds.

**Describe alternatives you've considered**
Running `rm -rf ./build && svelte-kit build` is a good enough workaround for now.

**Comment by benmccann** [comment] 2021-04-15 20:17
Duplicate of https://github.com/sveltejs/kit/issues/1039

**Comment by kayakyakr** [comment] 2021-04-27 21:49
@benmccann did the fix for #1039 handle rebuild if a file has been removed? I experienced it locally (with version next.89, not sure when that went out) when I removed a .svelte route, the generated html file was still present in build.

**Comment by kayakyakr** [comment] 2021-05-03 18:35
This is still an issue with the latest. Seems like it needs to be an update to adapter-static. Recreation (for me):

1. Create an app with $layout, index, sveltePreprocess with scss, and adapter-static
2. In the $layout file, add some global styles
3. Build the app
4. Change the $layout file
5. Build the app again
6. In the build/app directory, there should now be two files named start.[hash].js

![start-breeding](https://user-images.githubusercontent.com/328628/116917508-bf17c580-ac1c-11eb-8b84-0b6a40c117ce.png)

Requesting a reopen.

**Closed** 2021-08-21 13:58 UTC
Labels: enhancement
