### ISSUE TITLE
Named layouts not prioritized over js/ts files

### ISSUE THREAD

**Issue by myhrmans** [sveltejs/kit#5196] opened 2022-06-11 22:18 UTC
### Describe the bug

When having a route that uses a named layout within the same route as a .ts or .js file they will be picked up instead of the .svelte with an @named-layout.svelte 

### Reproduction

https://github.com/myhrmans/sveltejs-kit-named-layout-bug/tree/master

--
https://stackblitz.com/edit/sveltejs-kit-template-default-zdt3y1

Go into todo - It will not load, if you refresh todo you will get the error "GET method is not allowed"

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 9.99 GB / 31.29 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 100.0.2
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment] 2022-06-12 00:04
Duplicate of https://github.com/sveltejs/kit/issues/5139, not immediately apparent because you have both a index.js and index.ts in the repro so you get a different error. Perhaps that should be a different error in itself.

**Closed** 2022-06-23 14:15 UTC
