### ISSUE TITLE
adapter-static (SPA mode): index.html not generated when prerender.enabled = false

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#1705] opened 2021-06-17 21:16 UTC
**Describe the bug**
The following config causes `adapter-static` -> `npm run build` to not include the root `index.html` file - the one that you always send to the client - as specified in the adapter settings object, which is required to actually load the SPA.

```javascript
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter({
			fallback: 'index.html'
		}),
		ssr: false,
		prerender: {
			enabled: false
		}
	}
};

export default config;
```

**Logs**
N/A

**To Reproduce**
1. `npm init svelte@next`
2. select the `skeleton project`, say no to everything typescript etc.
3. copy paste my config and install the static adapter

**Expected behavior**
I don't the file to not be included when disabling prerendering. It would make even more sense for it to be required to be set to false for the files to be generated.

**Stacktraces**
N\A

**Severity**
On a scale from 1 to 10, maybe a 3.3? I have no idea as this might be intended behavior that I am not aware off.

**Comment by UltraCakeBakery** [comment] 2021-06-17 21:18
Another way to describe this issue:

The `fallback` option file is not generated when `prerender.enabled` is `false`

**Comment by Conduitry** [comment] 2021-06-17 21:50
Sounds like a duplicate of #1588.

**Closed by Conduitry** 2021-06-17 21:50 UTC
