### ISSUE TITLE
`ReadableStream`, `NodeJS.ReadableStream` should be supported in `response.body`

### ISSUE THREAD

**Issue by fixiabis** [sveltejs/kit#4499] opened 2022-04-03 04:26 UTC
### Describe the bug

I want to send large files via stream, but not working, so:

I saw here, looks supported, `response.body` also could be `NodeJS.ReadableStream`:

https://github.com/sveltejs/kit/blob/143d17f70c525c0a0a929a4e466ada9360523b6a/packages/kit/src/node.js#L83-L91

Then I checked implementation in `kit/src/runtime/server/endpoint.js`:

https://github.com/sveltejs/kit/blob/143d17f70c525c0a0a929a4e466ada9360523b6a/packages/kit/src/runtime/server/endpoint.js#L96-L101

And `is_pojo` in `kit/src/runtime/server/utils.js`:

https://github.com/sveltejs/kit/blob/143d17f70c525c0a0a929a4e466ada9360523b6a/packages/kit/src/runtime/server/utils.js#L36-L51

Looks `response.body` could be `NodeJS.ReadableStream` or `ReadableStream`, but no, because: 

https://github.com/sveltejs/kit/blob/143d17f70c525c0a0a929a4e466ada9360523b6a/packages/kit/src/runtime/server/endpoint.js#L87-L91

There will throw an error preventing me from using it.

Additional type check added currently:

```js
if (
	!is_text(type) &&
	!(
		body instanceof Uint8Array ||
		(typeof ReadableStream !== 'undefined' && body instanceof ReadableStream) ||
		(body !== null && body._readableState && typeof body.pipe === 'function') ||
		is_string(body)
	)
) {
```

### Reproduction

```ts
// some endpoint script
export const get = (event) => {
  if (!permitted) {
    return { status: 403, body: 'You do not have permission to access the file.' };
  }

  const fileStream = fs.createReadStream(filePath);
  return { body: fileStream };
};
```

### System Info

```shell
Not important.
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment] 2022-04-03 08:55
This is a duplicate of #3419.

**Closed** 2022-04-03 08:56 UTC
