### ISSUE TITLE
VAR is declared in a module script and will not be reactive

### ISSUE THREAD

**Issue by istarkov** [sveltejs/kit#1855] opened 2021-07-08 17:25 UTC
On latest sveltekit Im starting to get following warnings on every import I have inside module scripts.

```
"CIRCLE_MAX_R" is declared in a module script and will not be reactive
```

for this 

```svelte
<!-- svelte-ignore module-script-reactive-declaration -->
<script lang="ts" context="module">
  import {
    CIRCLE_MAX_R,
    CIRCLE_MED_R,
    CIRCLE_MIN_R,
    CIRCLE_EDGE_R,
    SIZE,
  } from './consts';
</script>
```

How I can disable this warning at all as for me it seems really strange to have module level scripts and zero ability to import anything there?

PS: For svelte-check Im using `svelte-check --tsconfig ./tsconfig.json --compiler-warnings 'module-script-reactive-declaration:ignore'`

**Comment by Conduitry** [comment] 2021-07-08 17:27
Duplicate of https://github.com/sveltejs/svelte/issues/5954

**Closed by Conduitry** 2021-07-08 17:27 UTC

**Comment by istarkov** [comment] 2021-07-08 17:31
IMO it doesnt look as duplicate of that issue even I use `<!-- svelte-ignore module-script-reactive-declaration -->` probably there is a way to somehow pass in sveltekit `compiler-warnings` now?
