### ISSUE TITLE
[Adapter Netlify] multipart/form-data not supported

### ISSUE THREAD

**Issue by f-elix** [sveltejs/kit#5494] opened 2022-07-13 14:53 UTC
### Describe the bug

Since updating to Sveltekit v370 and adapter-netlify v68, forms with enctype `multipart/form-data` don't work anymore when deployed to Netlify. Even if no file is sent to the server, a `NotSupportedError` is thrown with the message `multipart/form-data not supported`.

This used to work fine, so I don't think the problem is with Netlify (unless they had an update I wasn't aware of).

### Reproduction

Repo: https://github.com/f-elix/netlify-multipart-formdata-bug

Deployed url: https://chipper-moxie-864d1d.netlify.app/

Go to the deployed url and submit the form to see the error.

### Logs

```shell
{
name: "NotSupportedError",
message: "multipart/form-data not supported",
stack: "NotSupportedError: multipart/form-data not supported",
code: "UND_ERR_NOT_SUPPORTED"
}
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.12 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.12.1 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 79.0
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.57 
    @sveltejs/adapter-netlify: ^1.0.0-next.68 => 1.0.0-next.68 
    @sveltejs/kit: next => 1.0.0-next.370 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^2.9.13 => 2.9.14
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment] 2022-07-20 09:12
Likely a duplicate of #5349 which was fixed through #5629 - could you check with the latest version of SvelteKit if this issue still persists?

**Comment by brittneypostma** [comment] 2022-07-21 13:53
I am seeing the same issue on a [new demo app](https://github.com/brittneypostma/test-edge-split) with adapter-netlify installed and `split: true` in the config file. I was testing [this issue](https://github.com/sveltejs/kit/issues/4872) to see if it had been resolved. I no longer get an error on the page, but now get the form not supported error below.
```
{
name: "NotSupportedError",
message: "multipart/form-data not supported",
stack: "NotSupportedError: multipart/form-data not supported",
code: "UND_ERR_NOT_SUPPORTED"
}
```
Cannot add todos to the `/todo` route.

**Comment by garytube** [comment] 2022-07-26 00:58
Facing this issue after updating from 360 to 394.

I have a ASP.net Backend which gets a  FormData send by SvelteKit.  

Always getting a 415 - Unsupported Media Type. 


Rolled back SvelteKit and it works again.

**Comment by sarahetter** [comment] 2023-02-13 19:59
Hey! Here from the Netlify frameworks team. I've just tested this with the current versions:
```
		"@sveltejs/adapter-netlify": "2.0.4",
		"@sveltejs/kit": "^1.5.0",
```
with a `+server.ts` file, and the form submits properly, and the response is as expected without error.

I believe this is alright to close as the broken versions are quite outdated.

**Closed** 2023-05-04 11:00 UTC
Labels: bug, pkg:adapter-netlify
