### ISSUE TITLE
Each block doesn't work and crash all app when parameter is not iterable

### ISSUE THREAD

**Issue by KKKaisar** [sveltejs/kit#12193] opened 2024-05-07 12:52 UTC
### Describe the problem

Some times I get the wrong data and then the whole app crashes cause each block doesn't work with something that is not iterable(object, null, undefined, number, etc.). I cannot even logout cause my code runs after mount. And I should {#if isIterable} or {#if exist} or {#if exist || iterable} checks everywhere even if I not consider login logout case. There is {:else} which works only when it is empty array. And I cannot use await blocks cause many times there is no promise and etc or promise result binds to specific variable which goes to other each block in component of component. If check to each blocks makes my code very large and ugly. Is there only each block or each in each in each. But in second case it makes my code even uglier and I want to drop my code.

### Describe the proposed solution

I would like to see {:catch er} addition to s-each-else group which prevents app crashing when it is in code. This will give a choice what to do if params are not iterable. Something like s-each(iterable)-else(iterable-empty)-catch(not-iterable)

### Alternatives considered

1)Or just make each block itself check if params are iterable values and if not then it is just like {#if con} block doesn't show and works {:else} block. This would be better cause there is a bug - each block works even if I write it in if block. I don't know why this happens, I just solved it and don't remember how. If checks are very annoying. This solution is the same like the main proposed solution, it is just ignores any error or just shows it in console
2)Or make another block like {#for} which will work like 1)

### Importance

i cannot use SvelteKit without it

**Comment by Conduitry** [comment] 2024-05-07 13:15
Duplicate of https://github.com/sveltejs/svelte/issues/9005 and other issues.

**Closed by Conduitry** 2024-05-07 13:15 UTC

**Comment by KKKaisar** [comment] 2024-05-07 13:26
@Conduitry the whole app crashes which doesn't happen when you use React or Vue, in them crashes only one function. If this is not problem then what is problem

**Comment by KKKaisar** [comment] 2024-05-07 14:25
@Rich-Harris as I read other issues many people asked for this feature

**Comment by Rich-Harris** [comment] 2024-05-07 14:50
There is a proper way to fix this problem — error boundaries — that we will implement once it's a possibility (the Svelte 5 rewrite is partly about enabling this). The fix you propose here is the wrong approach and isn't going to happen, and @-ing me isn't going to change that.

**Comment by KKKaisar** [comment] 2024-05-08 03:14
@Rich-Harris thank you. And sorry for @. The reason why I did is that Conduitry didn't say a couple of word that there is coming solution like you did and he closed as not planned, and in the referenced issues there is || [] solution which is good but errors are still there crashing whole app.
