### ISSUE TITLE
Prerender does not work properly after the optional parameter path.

### ISSUE THREAD

**Issue by yahao87** [sveltejs/kit#9913] opened 2023-05-12 05:50 UTC
### Describe the bug

I started writing code with the following structure.

![image](https://github.com/sveltejs/kit/assets/10890178/d38e16c2-85f4-4ce8-89c7-1e8395debf5b)

And when I did `npm run build` I got the following error:

```
Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /[[lang=locale]]/(app),  - /[[lang=locale]]/(app)/about,  - /[[lang=locale]]/(auth)/account-recovery,  - /[[lang=locale]]/(app)/contact,  - /[[lang=locale]]/(app)/dashboard,  - /[[lang=locale]]/(auth)/login
```

I started svelte for the first time yesterday so I have no idea what the problem is.
I can't use prerender with `optional parameters` ?
Should I write everything like below?
```
prerender: {
    concurrency: 1,
    crawl: true,
    entries: ['*', '/ko/', '/ko/contact', '/en/', '/contact', '/about', '/dashboard']
},
```

### Reproduction

routes/+layout.ts
```
export const prerender = true;
export const ssr = false;
```

svelte.config.js
```
import preprocess from "svelte-preprocess";
import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from "@sveltejs/kit/vite";
import path from "path";

/** @type {import('@sveltejs/kit').Config} */
const config = {
    preprocess: [
        vitePreprocess(),
        preprocess({
            sass: true,
            postcss: true,
        }),
    ],

    kit: {
        adapter: adapter({
            fallback: 'index.html' // may differ from host to host
        }),
        prerender: {
            concurrency: 1,
            crawl: true,
        },
        alias: {
            '$src': path.resolve('./src'),
            '$components': path.resolve('./src/components'),
        },
    },
};

export default config;
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 14.49 GB / 31.87 GB
  Binaries:
    Node: 16.19.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.140
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1
    @sveltejs/adapter-static: ^2.0.2 => 2.0.2
    @sveltejs/kit: ^1.5.0 => 1.16.3
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.5
```

### Severity

annoyance

**Comment by gtm-nayan** [comment] 2023-05-12 06:10
Please provide a proper reproduction for the issue as instructed by the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally **not enough**. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by yahao87** [comment] 2023-05-12 06:28
If you explain it with an actual url, the structure becomes as follows.
Each page has links connecting them to each other.
```
/        =>              /[[lang=locale]]/(app)/+page.svelte
/en/     =>              /[[lang=locale]]/(app)/+page.svelte
```
If the first page is `/en/`
Include the following link on a later page.
```
/en/about
/en/dashboard
/en/contact
```

If the first page is `/`
Include the following link on a later page.
```
/about
/dashboard
/contact
```

For example, each page has a link like this:
```
<script lang="ts">
    import { getStores, navigating, page, updated } from "$app/stores";

    export function transformUrl(url: string) {
        const { lang } = $page.params;
        if (!lang) return url;
        else if (url.startsWith(`/${lang}`) || url.startsWith("http"))
            return url;
        return `/${lang}` + url;
    }
</script>

<a href={transformUrl("/")}>/</a>
<a href={transformUrl("/about")}>/about</a>
<a href={transformUrl("/login")}>/login</a>
<a href={transformUrl("/dashboard")}>/dashboard</a>
<a href={transformUrl("/contact")}>/contact</a>
<a href={transformUrl("/account-recovery")}>/account-recovery</a>
```

The `entries` value in the `config` file had no effect.

**Comment by gtm-nayan** [comment] 2023-05-12 06:43
Once again, explaining arbitrary parts of your file structure through text is not enough. Upload a minimal reproduction in the form of a git repo otherwise I'm going to assume this works as intended based on the following example.

https://stackblitz.com/edit/sveltejs-kit-template-default-cmrtok?file=src%2Froutes%2F[[lang]]%2F(app)%2F%2Bpage.svelte&terminal=build

**Comment by yahao87** [comment] 2023-05-12 06:49
https://github.com/yahao87/svelte-ssg-build-fail-example
I just created a new project to reproduce the error situation.
Can you check the github link by putting it there?

**Comment by gtm-nayan** [comment] 2023-05-12 07:51
You have SSR disabled so there won't be any links to crawl. So you can't use the crawler to find the links. If you do actually want to prerender the whole thing then yes, you need to list them all out.

The bigger issue though is that the `*` entry bails on a route if it sees a `[` in the route id. The question would be whether it should pick up `/[[foo]]/bar` as `/bar` instead of just bailing but then that might be a breaking change cause it starts trying to render routes that weren't previously called and builds start failing on HTTP errors.

**Comment by yahao87** [comment] 2023-05-12 08:15
@gtm-nayan Thanks for pointing out that ssr must be enabled to crawl.
Actually, I couldn't understand the second sentence you wrote because I'm not good at English.
However, I solved it by referring to what you said.

add file `routes\[[lang=locale]]/+layout.ts`
```
export const trailingSlash = "always";
```

And I succeeded in building the desired form.
![image](https://github.com/sveltejs/kit/assets/10890178/1f60418c-8f02-41c9-b9b4-20645f544827)

thank you!

**Comment by yahao87** [comment] 2023-05-12 08:31
Wouldn't it be nice to see in the document below that even if you want to use only `prerender` for the purpose of creating `static file` like me, `crawl` does not work if `ssr` is inactive?

https://kit.svelte.dev/docs/configuration#prerender

**Comment by tcc-sejohnson** [comment] 2023-05-17 21:11
We do already explain this: https://kit.svelte.dev/docs/page-options#prerender-prerender-and-ssr

Going to close this since there's not actually a bug -- glad you got your issue figured out! 😁

**Closed** 2023-05-17 21:11 UTC
