### ISSUE TITLE
Have ability to infer the return type of page endpoint in `.svelte`

### ISSUE THREAD

**Issue by WildlandHerald** [sveltejs/kit#4381] opened 2022-03-18 09:56 UTC
### Describe the problem

Having endpoint `index.ts` we can define `get` method with a return type of `{ body: { example: string } }` like that:
```ts
export const get: RequestHandler = async () => {
    return {
        body: { example: 'value' }
    }
}
```
And then use it in page `index.svelte` like that:
```svelte
<script lang="ts">
    export let example
    console.log(example)
</script>
```
But the type of `example` in `index.svelte` file would be `any`, and there is no way to infer it even if we import the `get` method as type and try to use `Awaited<ReturnType<get>>`, because `body` is by design are of type `any`.

This is a problem because return types of endpoints can get complicated at times. For example if it's also a type generated by database ORM for complex query. And basically doubling them in your own interfaces is inefficient.

### Describe the proposed solution

Have automatic inference of return type in svelte file. (i have no idea how that could be done)

### Alternatives considered

Have sveltekit emit and export the return type of endpoint at generation stage so it could be imported and used wherever needed (especially usefull to type normal `fetch()` calls)

### Importance

would make my life easier

**Comment by dummdidumm** [comment] 2022-03-18 12:17
Duplicate of #647 . This request is part of that larger issue of having better generated types.

**Closed by dummdidumm** 2022-03-18 12:17 UTC
