### ISSUE TITLE
SvelteKit fresh install with playwright doesn't find test files

### ISSUE THREAD

**Issue by page-support** [sveltejs/kit#9804] opened 2023-04-29 16:17 UTC
### Cause
1. test files have to be named "{testname}.test.ts" for playwright to find them, but the default installation names the test "test.ts"
Unrelated to the "no tests found" but an additional speed bump is that playwright requiries ` npx playwright install` to function.

### Reproduction

npm create svelte@latest web-client-3 # select playwright, typescript and library project type
cd web-client-3
npm install
npm run test #=> Error: No tests found

### System Info

```Shell
package.json:
{
	"name": "web-client-3",
	"version": "0.0.1",
	"scripts": {
		"dev": "vite dev",
		"build": "vite build && npm run package",
		"preview": "vite preview",
		"package": "svelte-kit sync && svelte-package && publint",
		"prepublishOnly": "npm run package",
		"test": "playwright test",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"test:unit": "vitest",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"exports": {
		".": {
			"types": "./dist/index.d.ts",
			"svelte": "./dist/index.js"
		}
	},
	"files": [
		"dist",
		"!dist/**/*.test.*",
		"!dist/**/*.spec.*"
	],
	"peerDependencies": {
		"svelte": "^3.54.0"
	},
	"devDependencies": {
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/kit": "^1.5.0",
		"@sveltejs/package": "^2.0.0",
		"@typescript-eslint/eslint-plugin": "^5.45.0",
		"@typescript-eslint/parser": "^5.45.0",
		"eslint": "^8.28.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte": "^2.26.0",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"publint": "^0.1.9",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"tslib": "^2.4.1",
		"typescript": "^5.0.0",
		"vite": "^4.3.0",
		"vitest": "^0.25.3"
	},
	"svelte": "./dist/index.js",
	"types": "./dist/index.d.ts",
	"type": "module"
}
```

### Severity

annoyance

**Comment by gtm-nayan** [comment] 2023-04-29 17:28
Duplicate of #9793

**Closed by gtm-nayan** 2023-04-29 17:28 UTC
