### ISSUE TITLE
bug: `HttpError` imported from `@sveltejs/kit` is `undefined`

### ISSUE THREAD

**Issue by ollema** [sveltejs/kit#10267] opened 2023-06-27 19:57 UTC
### Describe the bug

Hi!

Not sure if this is a bug - or I missed something in the documentation - but I have the following problem.

I want to fetch some things from an external API in my `+page.server.ts`. I have some helper functions in `$lib/server/` that help me to do that.

In these, if I encounter error in the external API, I throw errors with something along the lines of:
```ts
export async function fetch_thing(parameter: string) {
  const response = await fetch(`${base_url}/api/thing/${parameter}`);
  if (!response.ok) {
    const external_error_message = JSON.stringify((await response.json()).detail);
    throw error(
      response.status,
      `could not fetch from external API: ${external_error_message}`
    );
  }
  return thing_schema.parse(await response.json());
}
```

In my `+page.server.ts` I then catch these with something along the lines of:
```ts
import { HttpError } from '@sveltejs/kit';

...

try {
  await fetch_thing(parameter);
} catch (e) {
  if (e instanceof HttpError && e.status === 422) {
    // do something
  }
}
```
but that results in:
```
TypeError: Right-hand side of 'instanceof' is not an object
```

It turns out that `HttpError` is undefined!

This is surprising to me:
<img width="447" alt="Screenshot 2023-06-27 at 21 39 42" src="https://github.com/sveltejs/kit/assets/31876997/dd88d968-7696-4cc6-af67-81d751e2eebb">

Is `HttpError` not meant for consumption so to speak? Am I doing something weird here?

If I'm not supposed to use `HttpError` then maybe that should be documented somewhere?

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-bmtmun?file=src%2Froutes%2F%2Bpage.server.ts

press Demo

### Logs

```Shell
TypeError: Right-hand side of 'instanceof' is not an object
```

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz
    Memory: 25.75 GB / 31.32 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.11.0 - ~/.local/share/pnpm/node
    npm: 8.19.2 - ~/.local/share/pnpm/npm
    pnpm: 8.6.3 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4 
    @sveltejs/kit: ^1.20.5 => 1.20.5 
    svelte: ^4.0.0 => 4.0.0 
    vite: ^4.3.9 => 4.3.9 
```

### Severity

annoyance

**Comment by gtm-nayan** [comment] 2023-06-27 23:47
Duplicate of #6009

**Closed by gtm-nayan** 2023-06-27 23:47 UTC
