### ISSUE TITLE
When deploying adapter-vercel, in prod "/__data.json" is not found if hook has ssr=false

### ISSUE THREAD

**Issue by jsilveira** [sveltejs/kit#5165] opened 2022-06-06 00:04 UTC
### Describe the bug

Some routes of a adapter-vercel fail only in production with `Failed to load data` due to path `/__data.json` returning 404 in the vercel deploy. It took me a long time to realize this happens only with ssr=false in a hook:

```
export const handle = async ({ event, resolve }) => {
		return await resolve(event, {ssr: false});
};
```

Maybe I'm doing something really dumb, but it took me many hours to narrow down this unexpected behaviour to the ssr=false option. What was really confusing is that in my original app not only everything works fine in development and preview, but also in vercel's deploy some routes (and their corresponding `__data.json` requests) work just fine, but `/` and some others don't. What am I missing here? I went over the docs, adapter-vercel doc, github issues and I still don't understand if I've run into a bug or my setup is somehow nonsense. 

Note that I started this repo cloning the official todo app example.

### Reproduction

https://github.com/jsilveira/bug-vercel-svelte

https://bug-vercel-svelte.vercel.app/

### System Info

```shell
System:
  Binaries:
    Node: 16.15.0
    Yarn: 1.19.1 
    npm: 8.5.5
  Browsers:
    Chrome: 101.0.4951.67
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.57 => 1.0.0-next.58
    @sveltejs/kit: 1.0.0-next.348 => 1.0.0-next.348
    svelte: ^3.47.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by d3rpp** [comment] 2022-06-11 04:17
Would it be possible to add
```html
<script context="module">
	export const prerender = false;
</script>
```
in the `src/routes/__layout.svelte` which would theoretically achieve the same result of turning off SSR for the whole project in this case 

you could also add this to the `svelte.config.js` in the `kit` object
```js
prerender: {
	enabled: false
}
```
if the end result you're going for is no SSR, which appears to be the case, this may be a pretty good workaround.

*Note:* I didn't test this on vercel, so if these workarounds don't work I have no idea how, but I know the first method works fine for disabling SSR for at the very least, sub-pages

https://gitlab.com/d3rpp/dev/-/blob/main/src/routes/blog/_blogpost.svelte

**Comment by jsilveira** [comment] 2022-06-11 17:41
Prerendering is not the same as ssr (it's for pre-generating a static version of a route). I've tried it anyway, and vercel deploy still fails with the same error (I've updated the repo and the vercel app accordingly)

**Comment by irg1008** [comment] 2022-06-14 14:11
Did you managed to fix this? Same thing happens to me with ssr on. Works perfectly on development.

**Comment by jsilveira** [comment] 2022-06-20 01:01
Unfortunately no, I had to disable ssr. It's not a problem for this particular project, but it is probably a deal-breaker for a lot of projects.

**Comment by brunobely** [comment] 2022-08-16 22:50
Turning off prerendering in `svelte.config.js` (in addition to disabling SSR in `handle`) did the trick for me.

**Comment by Saljooq** [comment] 2022-09-05 20:37
I feel like [this](https://github.com/sveltejs/kit/pull/6251) pull request is very close to this issue - it seems like it should've been fixed by now - I might be wrong about this

**Comment by dummdidumm** [comment] 2022-09-14 17:58
Can't reproduce this anymore

**Closed by dummdidumm** 2022-09-14 17:58 UTC
Labels: bug, p1-important
