### ISSUE TITLE
`find_anchor` doesn't handle removed elements correctly / is called erroneously after an element is removed

### ISSUE THREAD

**Issue by 42triangles** [sveltejs/kit#7890] opened 2022-11-30 15:43 UTC
### Describe the bug

Using `on:click` to remove an element or a (grand- etc)parent of that element results in `find_anchor` (defined in `packages/kit/src/runtime/client/utils.js`) being called with the element that is now not element of the DOM anymore, which in turn results in `element` becoming `null` while iterating up the hierarchy, which `find_anchor` does not handle.

### Reproduction

```svelte
<script>
    let list = ["X"];
</script>

{#each list as elem}
    <button on:click={() => { list = []; }}>{elem}</button>
{/each}
```
or as a repository (based on `npm create svelte@latest`, I hope that is minimal enough?): https://github.com/42triangles/repro-remove-elem-error

### Logs

```Shell
InstallTrigger is deprecated and will be removed in the future. utils.ts:8:12
[vite] connecting... client.ts:19:8
[vite] connected. client.ts:134:14
Uncaught TypeError: element is null
    find_anchor http://localhost:5173/node_modules/@sveltejs/kit/src/runtime/client/utils.js?v=d082ee91:118
    _start_router http://localhost:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=d082ee91:1447
    addEventListener eval:4
    _start_router http://localhost:5173/node_modules/@sveltejs/kit/src/runtime/client/client.js?v=d082ee91:1440
    start http://localhost:5173/@fs/home/dodo/repro-remove-elem-error/node_modules/@sveltejs/kit/src/runtime/client/start.js:43
    async* http://localhost:5173/:19
utils.js:118:7
```

### System Info

```Shell
System:
    OS: Linux 6.0 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 21.65 GB / 31.28 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 107.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.567 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4
```

### Severity

annoyance

### Additional Information

It looks like this doesn't result in any actual visible bugs beyond the error being shown in the console, though if `find_anchor` being called in this context is correct, the fix would be very simple too.

**Comment by dummdidumm** [comment] 2022-11-30 15:56
Duplicate of #7876

**Closed by dummdidumm** 2022-11-30 15:56 UTC
